[WIP] PP-4758: Change signature of GatewayClient
alphagov/pay-connector pull request #1029
Opened 2019-02-01 12:39 UTC by oswaldquek

In an effort to make code simpler, we want to remove some functional idioms
that aren't particularly suited to Java. GatewayClient returns an
`Either<GatewayError, GatewayClient.Response>` which make upstream calling
classes complicated as we end up doing bi-Mapping and the like which is ugly
and confusing. When something goes wrong the java way is to throw exceptions
and catch them, which is what this commit does. GatewayClient now returns a
`GatewayClient.Response` which is a successful response. Unfortunately this is
a massive change as it's used by all the payment providers bar Stripe and there
is no way to reduce this.

2019-02-08 12:51 UTC, mrlumbu requested changes
Overall this looks great - I definitely agree that switching to this way of doing things makes all the client code more readable, and will be a massive improvement when working with this code in the future.

There are some changes I have suggested in my comments. The main things I have suggested are:

- Map over `Optional` when possible. There seem to be cases where you have deliberately chosen not to - I'm not sure  whether this is a deliberate decision on your part, or if this just felt natural in the circumstances, or there's some other reason I've missed. I would prefer that we are consistent in this sort of thing.
- Have all the gateway errors you've introduced extend one abstract class - this will help tidy up all client code and make things cleaner
- Probably don't have a charge status associated with an Exception - I can't see how that will work, and even if it does it's quite confusing
- Theres some smaller things around code style as well, which I don't really have strong feelings about

A final comment - I would have preferred that all refactoring changes had been done in a separate PR, it is quite distracting in what is already a lot of changes. 

Happy to discuss any of this, and as I say, may have missed the reason for some of your decisions, so feel free to push back.

2019-02-08 12:51 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/GatewayClient.java
> +            throw e;
not sure what the purpose of this is?

2019-02-08 12:51 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqRefundHandler.java
> +            unmarshalled = unmarshallResponse(response, EpdqRefundResponse.class);
is there a reason you don't just return this here?

2019-02-08 12:51 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +            if (!epdqGatewayResponse.getBaseResponse().isPresent()) epdqGatewayResponse.throwGatewayError();
you seem to be deliberately not mapping over `Optional`s - is there a reason for this?

This bit would be fine as
```
return epdqGatewayResponse.getBaseResponse()
                    .map(EpdqQueryResponse::toChargeQueryResponse)
                    .orElseThrow(() -> new WebApplicationException("Things went wrong"));
```
wouldn't it?

2019-02-08 12:51 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +            if (!gatewayResponse.getBaseResponse().isPresent()) gatewayResponse.throwGatewayError();
same comment about mapping optionals

2019-02-08 12:51 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +    private static boolean responseDoesNotMatchWithUserResult(BaseAuthoriseResponse.AuthoriseStatus authoriseStatus, Auth3dsDetails.Auth3dsResult auth3DResult) {
would pefer if you did these kind of small refactorings in a separate PR - they are entirely tangential, and the PR is already pretty big

2019-02-08 12:51 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/GatewayErrors.java
> +            return AUTHORISATION_ERROR;
Am not sure how this is going to work - surely the charge status cannot be inferred from the gateway error alone - you need the context of what was being tried. I think it is cleaner for the Exception to just be an exception, and the calling class can figure out stuff about charge statuses with the context it has. Unless I'm missing something?

2019-02-08 12:51 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/GatewayErrors.java
> +    public interface ToGatewayError {
I suggest that you have one abstract class that all the contained Exceptions extend called `GatewayErrorException` or similar
with method `toGatewayError`

Then in all client code they can either rethrow or catch `GatewayErrorException` rather than having to refer to all three if we need more) Exceptions everywhere

I think the ToChargeStatus interface is unnecessary and confusing (see comment below)

So something like 
```
    public abstract class GatewayErrorException extends Exception {
        private GatewayErrorException(String message) {
            super(message);
        }

        public abstract GatewayError toGatewayError();
    }


    public class GenericGatewayErrorException extends GatewayErrorException {

        public GenericGatewayErrorException(String message) {
            super(message);
        }

        public GatewayError toGatewayError() {
            return new GatewayError(getMessage(), ErrorType.GENERIC_GATEWAY_ERROR);
        }

    }

    ...
 ```

2019-02-08 12:51 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/GatewayResponseUnmarshaller.java
> +    public static <T> T unmarshallResponse(GatewayClient.Response response, Class<T> clazz) throws GatewayConnectionErrorException {
this is not a serious comment, but I really don't like `clazz`

You could call it something like `unmarshallingTarget` or something?

2019-02-08 16:13 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/GatewayClient.java
> +            throw e;
i wasn't thinking straight... this catch block can be deleted!

2019-02-08 16:15 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/GatewayErrors.java
> +            return AUTHORISATION_ERROR;
You are right - I was overzealous in trying to reduce lines of code, rather than getting the calling class to match on each instance of exception and mapping each to a status which is the right thing to do.

2019-02-08 16:22 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +            if (!gatewayResponse.getBaseResponse().isPresent()) gatewayResponse.throwGatewayError();
the reason i've thrown the gateway error here is that it will be caught in the catch block a few lines below which then sets the authorisationStatus and stringifiedResponse. unfortunately the compiler will complain if we use `.orElseThrow(Supplier)` as the exception thrown from within a Supplier can't be caught in the catch block below.
i also don't think mapping the optional is the right thing to do here because it's not mapping from BaseResponse to another object, it's setting the transactionId, stringifiedResponse and authorisationStatus a few lines down.

2019-02-08 16:24 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqRefundHandler.java
> +            unmarshalled = unmarshallResponse(response, EpdqRefundResponse.class);
hmm, I was sure the compiler was complaining before but it appears it's my mistake. will fix.

2019-02-08 16:49 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/GatewayClient.java
> +            throw e;
oh... actually the purpose is to throw the `GatewayConnectionErrorException` properly, otherwise it will be caught by the `catch (Exception e)` block and rethrown as a `GenericGatewayErrorException`.

2019-02-08 16:51 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/GatewayResponseUnmarshaller.java
> +    public static <T> T unmarshallResponse(GatewayClient.Response response, Class<T> clazz) throws GatewayConnectionErrorException {
this comes from me probably reading too many hibernate docs in a previous life which had `clazz` all over the place

2019-02-08 17:41 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/GatewayErrors.java
> +    public interface ToGatewayError {
i've taken onboard your example class here. code is much cleaner and overall it has made this PR reduce the lines of code overall.

2019-02-11 12:47 UTC, mrlumbu approved these changes
Couple more minor comments, but happy with how this looks now.

🎉

2019-02-11 12:47 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +            } catch (GatewayErrorException e) {
feels like the below block could be extracted into `CardAuthoriseBaseService`? Not a biggie though

2019-02-11 12:47 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/GatewayClient.java
> +            throw e;
👍

2019-02-11 12:47 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +            if (!gatewayResponse.getBaseResponse().isPresent()) gatewayResponse.throwGatewayError();
ok 👍

2019-02-11 15:07 UTC, merged