PP-4779: Update and get gateway merchant id successfully
alphagov/pay-connector pull request #1039
Opened 2019-02-06 15:44 UTC by oswaldquek

We could have used the `PATCH /v1/frontend/accounts/{accountId}` method to
update the credentials but operationally curling `PATCH
/v1/frontend/accounts/{accountId}/gateway-merchant-id/{gatewayMerchantId}` manually is
simpler and will be deprecated once the functionality in self service to update
a gateway account with the gateway merchant id is in place.

@oswaldquek @gidsg

2019-02-06 17:24 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountFrontendResourceITest.java
> +        givenSetup().accept(JSON)
@gidsg I think this block can be deleted?

2019-02-06 18:36 UTC, kbottla requested changes

2019-02-06 18:36 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    @Path("/v1/frontend/accounts/{accountId}/gateway-merchant-id/{gatewayMerchantId}")
Can we post 'gatewayMerchantId' in body rather than pass in URL ?
Requests are logged and we will log merchant Id if it is passed in URL.

2019-02-06 18:36 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +            updatedCredentials.put("gateway_merchant_id", gatewayMerchantId);
> Map<String, String> credentials = gatewayAccount.getCredentials();
            Map<String, String> updatedCredentials = new HashMap<>(credentials);
            updatedCredentials.put("gateway_merchant_id", gatewayMerchantId);

Is there any reason a new HashMap is created here instead of something like
```
gatewayAccount
.getCredentials()
.put("gateway_merchant_id", gatewayMerchantId);
```

2019-02-06 18:36 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    @PATCH
I suppose there is going to be some functionality in toolbox to use this endpoint ?

2019-02-06 18:36 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    //Deprecate when self service has functionality to update the gateway merchant id
Is there any story to update self service ? Would be good to add reference here so someone can find and deprecate/remove this endpoint

2019-02-06 18:36 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +        return gatewayDao.findById(gatewayAccountId).map(gatewayAccount -> {
This went back to old ways of connector code with all functionality (transactional boundary, db updates, error handling.. ) in this endpoint. Given that we may remove endpoint (and with all other endpoints in this resource following same approach), don't see any issue to keep this way. But if this is going to be stay for a while we will need to refactor code into appropriate service.

2019-02-06 18:36 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountFrontendResourceITest.java
> +    public void getGatewayAccountWithInvalidAccount(){
Can we name it similar to other tests method names `shouldReturn404IfGatewayAccountDoesNotExist` and to be descriptive

2019-02-06 18:36 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountFrontendResourceITest.java
> +    public void getGatewayAccountWithoutMerchantId(){
Same as above for naming..

2019-02-06 18:36 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    @Path("/v1/frontend/accounts/{accountId}/gateway-merchant-id/{gatewayMerchantId}")
Path could be `/v1/accounts/{accountId}/gateway-merchant-id/{gatewayMerchantId}` if we are not going to invoke it through frontend/selfservice

2019-02-07 10:22 UTC, oswaldquek commented
Do not merge. I think the requirements around this story need to be slightly updated.

2019-02-07 10:26 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +            updatedCredentials.put("gateway_merchant_id", gatewayMerchantId);
yeah we tried that. it doesn't work. i think it's something to do with JPA seeing the same object (Map) reference and thinks it doesn't need to update the credentials.

2019-02-07 10:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +        return gatewayDao.findById(gatewayAccountId).map(gatewayAccount -> {
I will remove this endpoint. I just spoke to Jon and it will be easier to return the gateway merchant id in the call to `/v1/frontend/charges/{chargeId}` so frontend doesn't have to make an extra api call.

2019-02-07 10:30 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    @Path("/v1/frontend/accounts/{accountId}/gateway-merchant-id/{gatewayMerchantId}")
yup all good points. will fix these.

2019-02-07 12:13 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    @PATCH
toolbox and selfservice will use https://github.com/alphagov/pay-connector/blob/67e8a2378cb4152887e235b0b39f870fc5a45e53/src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java#L232.

i created this method to make it easier for me to manually update the gateway account with the gateway merchant id using `curl`. this is only temporary and when selfservice is updated to allow services to to update their account with their gateway merchant id this endpoint will be deleted.

2019-02-07 13:14 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    //Deprecate when self service has functionality to update the gateway merchant id
yes in here https://payments-platform.atlassian.net/browse/PP-4645. it's not prioritised yet though. there will probably be a few stories relating to self service.

2019-02-07 15:35 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    @Path("/v1/frontend/accounts/{accountId}/gateway-merchant-id/{gatewayMerchantId}")
i fixed this by deleting the path ;)
`PATCH /v1/api/accounts/accountId` will be used instead

2019-02-07 15:35 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    @PATCH
fixed

2019-02-07 15:35 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +    //Deprecate when self service has functionality to update the gateway merchant id
fixed

2019-02-07 15:38 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountFrontendResourceITest.java
> +    public void getGatewayAccountWithInvalidAccount(){
this test is deleted

2019-02-07 15:38 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountFrontendResourceITest.java
> +    public void getGatewayAccountWithoutMerchantId(){
this test is deleted

2019-02-07 16:47 UTC, gidsg commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +        return credentials.get("gateway_merchant_id");
does this handle the possible null case?

2019-02-08 09:44 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +        return credentials.get("gateway_merchant_id");
it doesn't matter as we usually return "null" if there's nothing. for example, 
```
    "gateway_account": {
        "version": 3,
        "requires3ds": false,
        "allowWebPayments": false,
        "notifySettings": null,
        "live": false,
        "gateway_account_id": 1,
        "payment_provider": "worldpay",
        "type": "test",
        "service_name": null,
        "analytics_id": null,

```

2019-02-08 10:18 UTC, kbottla requested changes

2019-02-08 10:18 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidator.java
> +        throwIfInvalidFieldOperation(payload, ADD_OP);
I think we need `replace` op too for updating existing

2019-02-08 10:18 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/GatewayAccountService.java
> +                            updatedCredentials.put("gateway_merchant_id", gatewayAccountRequest.valueAsString());
We need to check if gateway_merchant_id exists and update - if we allow `replace` op

2019-02-08 10:18 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidator.java
> +            case CREDENTIALS_GATEWAY_MERCHANT_ID:
I would like to see tests for this in `GatewayAccountRequestValidatorTest`

2019-02-08 11:00 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidator.java
> +            case CREDENTIALS_GATEWAY_MERCHANT_ID:
do we really need tests in `GatewayAccountRequestValidatorTest` as the positive test is covered by `GatewayAccountFrontendResourceITest. updateGatewayAccountWithGatewayMerchantId`? also, looking at `GatewayAccountRequestValidatorTest` there are only two positive tests `shouldNotThrow_whenAllValidationsPassed` and `shouldNotThrow_whenPathIsValidEmailCollectionMode` which suggests it's overkill to test everything at this unit test level as the rest are tested in the integration tests.

i'm also not convinced about testing for the negative as the validation of the gateway merchant id uses `throwIfInvalidFieldOperation` and `throwIfNullFieldValue` which are already tested.

2019-02-08 11:13 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidator.java
> +            case CREDENTIALS_GATEWAY_MERCHANT_ID:
I am happy about the positive test as it is covered in Integration test but we don't cover negative cases anywhere.

Although `throwIfInvalidFieldOperation` and `throwIfNullFieldValue` are tested, the method `validateGatewayMerchantId` itself is not. It means we can change it to anything without detected.

2019-02-08 14:41 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidator.java
> +        throwIfInvalidFieldOperation(payload, ADD_OP);
I've created a test in `GatewayMerchantIdITest.replaceGatewayMerchantId`

2019-02-08 14:44 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidator.java
> +            case CREDENTIALS_GATEWAY_MERCHANT_ID:
i've created a negative test in `GatewayAccountRequestValidatorTest.shouldThrowForInvalidMerchantGatewayIdPatchRequest`

2019-02-11 09:57 UTC, kbottla approved these changes
LGTM! You might want to update PR description since it doesn't reflect current state of changes

2019-02-11 09:57 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidator.java
> +            case CREDENTIALS_GATEWAY_MERCHANT_ID:
👍

2019-02-11 09:58 UTC, merged