PP-4779: Web payments flags
alphagov/pay-connector pull request #1043
Opened 2019-02-11 10:56 UTC by oswaldquek

Return `allow_apple_pay` and `allow_google_pay` in the call to
`/v1/frontend/charges/{chargeId}`. Example return json:

```
{
    "amount": 100,
    "state": {
        "finished": false,
        "status": "created"
    },
    "description": "description",
    "language": "en",
    "status": "CREATED",
    "gateway_account": {
        "version": 2,
        "requires3ds": false,
        "allowWebPayments": false,
        "notifySettings": null,
        "live": false,
        "gateway_account_id": 1,
        "payment_provider": "worldpay",
        "type": "test",
        ...
        "allow_apple_pay": false,
        "allow_google_pay": false,
```

## WHAT
_A brief description of the pull request:_

## HOW 
_Steps to test or reproduce:_

2019-02-11 13:08 UTC, kbottla requested changes

2019-02-11 13:08 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +        return allowWebPayments;
Why are we not adding new fields `allow_apple_pay` & `allow_google_pay` to database ? I think having two separate fields will give control to turn on/off applepay/googlepay independently.

With this config, services will always have applepay enabled ( if for some reason service cannot enable applepay at worldpay they may not be able to enable googlepay )

2019-02-11 13:08 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +        return allowWebPayments;
Not sure of the requirements for Applepay, but do we need merchant ID for applepay too ?

2019-02-11 13:08 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/AllowWebPaymentsITest.java
> +public class AllowWebPaymentsITest {
Can we name it `ChargesApiResourceAllowWebPaymentsITest` so IDE can detect these tests for resource class

2019-02-11 13:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +        return allowWebPayments;
hmm I think this is a good point (re. wanting googlepay and not apple pay). I'm not really sure and will ask for opinions.

2019-02-11 13:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +        return allowWebPayments;
merchant id isn't required for apple pay at the moment (or maybe it is but i don't know anything about apple pay)

2019-02-11 13:44 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +        return allowWebPayments;
ok looks like we do want separate fields. i'll make the database changes in another PR and push that out to production and return to work on this PR.

2019-02-11 17:42 UTC, oswaldquek commented
DO NOT MERGE until database migration has been done for https://github.com/alphagov/pay-connector/pull/1045

2019-02-12 10:52 UTC, kbottla reviewed
Looks good to me. Just a comment on including credentials in API response

2019-02-12 10:52 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +    public Map<String, String> getCredentials() {
What is the purpose of including all credentials here ? We will be exposing sensitive data (services credentials) if we return entire map.

2019-02-12 11:02 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +    public Map<String, String> getCredentials() {
i don't know why git is showing this as a thing i added. i added the above `public String getGatewayMerchantId()` instead. 🤷‍♂️

2019-02-12 11:06 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +    public Map<String, String> getCredentials() {
It may be because it is moved from `168-172`

2019-02-12 11:06 UTC, kbottla approved these changes

2019-02-12 11:07 UTC, merged