[WIP] PP-4779 extra tests and edge case handling
alphagov/pay-connector pull request #1052
Opened 2019-02-12 17:07 UTC by gidsg

## WHAT
Extra test and functionality for PP-4779

Given a charge exists in our system
And the account associated with the charge has no gateway merchant id
When I call
GET /v1/frontend/charges/{chargeId}
Then the gateway_merchant_id is null

Given I have a worldpay merchant id for a service
And the service exists in our system
And the service has no gateway account credentials
When I PATCH the worldpay merchant id
Then a 400 BAD REQUEST is returned

## HOW 
See user stories above

2019-02-13 11:24 UTC, gidsg commented
@oswaldquek I think this is ready for review now. I believe the Codacy warnings are a false-positive as `rest-assured` wraps the assertions in the tests.

2019-02-14 14:13 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/exception/MerchantIdWithoutCredentialsException.java
> +public class MerchantIdWithoutCredentialsException extends BadRequestException {
normally we do `implements ExceptionMapper` (see ValidationExceptionMapper and UnsupportedOperationExceptionMapper for example) but it seems InvalidKeyException extends BadRequestException too so there doesn't seem to be any standard for this. (This isn't a request to change it, just an observation.)

2019-02-14 14:17 UTC, oswaldquek requested changes

2019-02-14 14:17 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsITest.java
> +                .assertThat()
you don't need this `assertThat` line

2019-02-14 14:17 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsITest.java
> +                .statusCode(HttpStatus.SC_BAD_REQUEST);
could you also assert the error message `"Account Credentials are required to set a Gateway Merchant ID"`? an easy way of printing the actual returned json body is to use `.log().body()` after the `.then()` part. 

i think the assertion will be `.path("message", is("Account Credentials are required to set a Gateway Merchant ID"))`

2019-02-14 14:23 UTC, gidsg commented on src/main/java/uk/gov/pay/connector/gatewayaccount/exception/MerchantIdWithoutCredentialsException.java
> +public class MerchantIdWithoutCredentialsException extends BadRequestException {
OK, I took this style from https://github.com/alphagov/pay-connector/blob/a4f6a67778691ff82fc907d2b7830dfdc2aa8ff6/src/main/java/uk/gov/pay/connector/wallets/applepay/InvalidKeyException.java

2019-02-14 14:42 UTC, oswaldquek approved these changes

2019-02-14 15:10 UTC, merged