PP-4512 [WIP] Check with gateway before expiring
alphagov/pay-connector pull request #1059
Opened 2019-02-13 14:40 UTC by mrlumbu

Implements a check with gateway to see if charge is expirable before trying
to expire it.

2019-02-13 14:59 UTC, danworth commented on src/main/java/uk/gov/pay/connector/report/model/GatewayStatusComparison.java
> +        gatewayStatus = gatewayQueryResponse.getMappedStatus().isPresent() ?
Should `getGatewayStatus` a little further down return `Optional<ChargeStatus>` since it is called by `canBeCancelled()` within `DiscrepancyService` as:
`!gatewayStatusComparison.getGatewayStatus().toExternal().isFinished() &&`
which has the potential to NPE if `getGatewayStatus()` returns the possible `null`?

2019-02-13 16:17 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/report/model/GatewayStatusComparison.java
> +        gatewayStatus = gatewayQueryResponse.getMappedStatus().isPresent() ?
hmm, yeah. Probably needs a bit more thought

2019-02-14 09:13 UTC, danworth requested changes
I think there's a test file that can be removed (probably a left over from the first approach). 

My only musing is that using the unchecked IllegalArgumentException where checked exceptions are usually appropriate for predictable, but unpreventable errors that are reasonable to recover from. The unchecked doesn't force the user of `map` to consider the possible exception result (no `throws` on the method) but then its internal and perhaps we'd expect them to at least look at the method before using it :)
There's lot of debate over when and which to use so I'll leave it to your better judgement and I'm happy with which ever you decide (I think I'm mentioning it hear as I'm interested in your opinion, perhaps later over a cup of tea).

2019-02-14 09:13 UTC, danworth commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeExpiryResourceEpdqITest.java
> +    public void shouldHandleCaseWhereEpdqRespondsWithUnknownStatus() {
👍

2019-02-14 09:13 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/service/EpdqChargeExpiryServiceTest.java
> +public class EpdqChargeExpiryServiceTest {
This is empty and unused, I assume its no longer needed and should not be committed, sorry if I'm missing something.

2019-02-14 15:31 UTC, mrlumbu commented
Yes, I did consider making it a checked exception, and maybe it should be, although it is worth reading Effective Java on this point - he makes quite a good case for using checked exceptions very rarely. I think a better thing to do would be to handle the `IllegalArgumentException` within `EpdqPaymentProvider`, and wrap it into one of the errors it throws. I would quite like to get this fix out then refactor if that's ok, as this is fairly important to fix.

2019-02-14 15:33 UTC, mrlumbu commented
And yes, we should definitely discuss in more detail over some 🍵 
😃

2019-02-14 15:36 UTC, danworth approved these changes
Looks good.

2019-02-14 15:43 UTC, merged