PP-4860: Log successful/unsuccessful Google payments
alphagov/pay-connector pull request #1078
Opened 2019-02-18 16:19 UTC by oswaldquek

At present we aren't able to introduce smoke tests for Google payments, so we
need to introduce some monitoring. These log messages are inteded to be
searched for by our logging provider so as to build up some form of metric over
time.

2019-02-19 09:10 UTC, danworth requested changes
Looks good, only thing I believe needs changing is that this service is intended for all wallet types so need to replace the hard-coded `Google` with `walletAuthorisationData.getWalletType()`. Couple of other things if you're inclined to agree.

2019-02-19 09:10 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
>                  } else operationResponse.throwGatewayError();
Doesn't prevent approval, and nothing you've done, but I think enclosing the `else` condition in `{}` makes it a little clearer what is and isn't part of the else (more when viewing the github generated diff, originally looked like the new log line was part of the `else`.
```
else {
    operationResponse.throwGatewayError();
}
```

2019-02-19 09:10 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +                logger.info("Google pay authorisation success - charge_external_id={}, payment provider response={}",
Since this is shared for wallets I think `Google` should be replaced with reference to `walletAuthorisationData.getWalletType()`

2019-02-19 09:12 UTC, danworth commented
Sorry Oz, I see that you've requested review from @heathd  so I'll defer to his better judgement, feel free to dismiss mine :)

2019-02-20 18:02 UTC, oswaldquek commented
@danworth @heathd this is ready for review. Thanks.

2019-02-21 09:46 UTC, danworth requested changes
Looks good, few minor things about consistency with wallet logging elsewhere and whether to use `failure` rather than `unsuccessful`.

2019-02-21 09:46 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +        String successOrUnsuccessful = isSuccessful? "success" : "unsuccessful";
Perhaps use `failure` instead of `unsuccessful` since someone might inadvertently capture the `unsuccessful` cases if searching for `success` with regex that's a little too lose, e.g. using `success` rather than something like `\bsuccess\b`.

Could consider creating an Enum for this kind of thing rather than a String to aid consistency across logs but not entirely necessary.

2019-02-21 09:46 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +        String webPaymentType = walletType.equals(WalletType.GOOGLE_PAY)? "google-pay" : "apple-pay";
We already have log entries for wallets that use `WalletType.toString()` (`WalletService` line 32) and I think we should be consistent across all logs to help debugging. Perhaps this should use `WalletType.toString()` for the log entry.

For the metric name this works fine for now but should a should a third type be introduced, or we use a wallet metric elsewhere and want to ensure consistent naming it might be prudent to perhaps add a 'getMetricName()' to the `WalletType` enum?

2019-02-21 09:46 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +                logMetrics(chargeId, operationResponse, false, charge.getGatewayAccount().getGatewayName(),
Minor and only for consideration but could pass the `charge` rather than deconstructing some of its values into the method params to reduce the number of params.

2019-02-21 09:46 UTC, danworth commented on src/test/java/uk/gov/pay/connector/wallets/WalletAuthoriseServiceTest.java
> +    public void setUp() {
👍

2019-02-21 09:46 UTC, danworth commented on src/test/java/uk/gov/pay/connector/wallets/WalletAuthoriseServiceTest.java
> +    public void verifyLogging() throws Exception {
Nice to have the test for the logging.

2019-02-21 11:28 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +        String successOrUnsuccessful = isSuccessful? "success" : "unsuccessful";
Good point about searching the logs. Will change. Not sure about the Enum thing as this is just a small private method...

2019-02-21 11:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +                logMetrics(chargeId, operationResponse, false, charge.getGatewayAccount().getGatewayName(),
fixed

2019-02-21 11:32 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +        String webPaymentType = walletType.equals(WalletType.GOOGLE_PAY)? "google-pay" : "apple-pay";
I've used `WalletType.toString()` in the log now.
I think metrics and the `WalletType` are two very separate things so am not too keen on a `getMetricName` method on the `WalletType`.

2019-02-21 11:53 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +        String successOrUnsuccessful = isSuccessful? "success" : "unsuccessful";
That's ok 👍, FYI my intention wasn't for the benefit of just this simple private method but something that could be used whenever we're signalling success/failure in a log message to help consistency and avoid variations of `fail | failure | unsuccessful | not successful | etc..`, it would be something to point to and use consistently throughout the project. Happy as-is if you prefer.

2019-02-21 11:57 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +        String webPaymentType = walletType.equals(WalletType.GOOGLE_PAY)? "google-pay" : "apple-pay";
Sure, I guess we can't use `WalletType.toString()` for the metric name since it doesn't conform to the metric naming convention of using `-`? Not a huge problem since anyone introducing new metrics for wallet payments should look at the existing metrics and use the same name.

2019-02-21 12:17 UTC, danworth submitted a review, later dismissed
Looks good, thanks for considering my suggestions.

2019-02-21 12:17 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +                logMetrics(charge, operationResponse, false, walletAuthorisationData.getWalletType());
Very very minor and no need to change if you don't wish. It might be more expressive for the param to be a String (or better an enum) of `success` or `failure` rather than a boolean which is later converted within the method, on first look is isn't clear what the value represents.

2019-02-26 16:25 UTC, heathd submitted a review, later dismissed
Looks good to me

2019-02-26 16:26 UTC, heathd commented
one other thought.. it's good to log gateway account ID but I think we should do that by adding it via MDC to every log line

2019-02-28 12:11 UTC, oswaldquek commented
@heathd i can't see how we're logging gateway account id via MDC in the code?

2019-02-28 15:33 UTC, heathd approved these changes
looks good

2019-02-28 15:45 UTC, merged