PP-4758: Goodbye to the session identifier bifunction
alphagov/pay-connector pull request #1079
Opened 2019-02-18 16:48 UTC by oswaldquek

All the session identifier bifunction does is add a cookie to the http request. This is only useful for worldpay auth requests. Removing the `BiFunction<GatewayOrder, Builder, Builder> sessionIdentifier` field in GatewayClient will make it easier to deprecate StripeGatewayClient.

2019-02-19 14:05 UTC, alexbishop1 requested changes
This is a good changes that removes a useless abstraction (where we pretend there’s a so-generic-it’s-meaningless concept of a provider session ID, which is actually always a Worldpay cookie called “machine”) and makes both our code for Worldpay and the other gateways (which should have never had to know about this in the first place) simpler.

I have a couple of concerns about the implementation but the overall approach is great.

2019-02-19 14:05 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/GatewayClient.java
> +                                                 List<HttpCookie> cookies)
Since there’s only ever a single cookie, do we really need a list?

2019-02-19 14:05 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                    ImmutableList.of(new HttpCookie(WORLDPAY_MACHINE_COOKIE_NAME, gatewayOrder.getProviderSessionId().get())));
Hmm, this is going to blow up if there isn’t a provider session ID for some reason. In practice, there should be, but I think I would prefer it the absence of a value meant the cookie wasn’t sent at all. This will probably still result in the authorisation failing but it will be handled by our existing code authorisation errors, which is fairly graceful and cleans things up.

2019-02-19 14:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        when(mockGatewayClient.postRequestFor(isNull(), any(GatewayAccountEntity.class), any(GatewayOrder.class), any(List.class)))
I think `anyList()` is better because generics

2019-02-19 17:36 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/GatewayClient.java
> +                                                 List<HttpCookie> cookies)
I think it makes sense to be able to pass a list of cookies into an HttpClient. For stripe we have to send an authorisation header (which again is only one, sure).

2019-02-20 09:39 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/GatewayClient.java
> +                                                 List<HttpCookie> cookies)
i don't think it hurts to make this a generic case of passing in a list of cookies in this case

2019-02-20 09:42 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                    ImmutableList.of(new HttpCookie(WORLDPAY_MACHINE_COOKIE_NAME, gatewayOrder.getProviderSessionId().get())));
well, the `build3dsResponseAuthOrder` is a private method that sets a provider session id... maybe a better way would be to 
```
String providerSessionId = request.getProviderSessionId().orElse("")
GatewayClient.Response response = authoriseClient.postRequestFor(null, request.getGatewayAccount(), build3dsResponseAuthOrder(request, providerSessionId),
                    ImmutableList.of(new HttpCookie(WORLDPAY_MACHINE_COOKIE_NAME, providerSessionId)));
```
?

2019-02-20 10:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                    ImmutableList.of(new HttpCookie(WORLDPAY_MACHINE_COOKIE_NAME, gatewayOrder.getProviderSessionId().get())));
That would still send a blank cookie if there is no provider session ID. I know from bitter past experience that blank cookies can behave very strangely. I think I’d prefer if it didn’t send the cookie at all. Something like this:

```java
List<HttpCookie> cookies = request.getProviderSessionId()
        .map(providerSessionId -> Collections.singletonList(new HttpCookie(WORLDPAY_MACHINE_COOKIE_NAME, providerSessionId)))
        .orElse(Collections.emptyList());
GatewayClient.Response response = authoriseClient.postRequestFor( null, request.getGatewayAccount(), build3dsResponseAuthOrder(request), cookies);
```

2019-02-20 10:30 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                    ImmutableList.of(new HttpCookie(WORLDPAY_MACHINE_COOKIE_NAME, gatewayOrder.getProviderSessionId().get())));
I'll go with your suggestion 👍 
Although we're currently sending blank cookies!

2019-02-20 10:37 UTC, oswaldquek commented
thanks for the review @alexbishop1, i believe i've addressed all the issues.

2019-02-20 11:52 UTC, alexbishop1 approved these changes

2019-02-20 11:53 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                    ImmutableList.of(new HttpCookie(WORLDPAY_MACHINE_COOKIE_NAME, gatewayOrder.getProviderSessionId().get())));
Really? We should stop doing that!

2019-02-20 13:55 UTC, merged