PP-4847 Move and tweak ChargeQueryResponse
alphagov/pay-connector pull request #1091
Opened 2019-02-21 11:49 UTC by mrlumbu

ChargeQueryResponse is gateway agnostic so move to root of gateway package
Make getMappedStatus return an Optional, to acknowledge fact that we cannot
reliably mapped returned status to one of our statuses.

2019-02-21 18:27 UTC, oswaldquek requested changes

2019-02-21 18:27 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqStatusMapper.java
> +        return null;
can this return an Optional?

2019-02-22 09:34 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqStatusMapper.java
> +        return null;
yes. I was gonna change this in the next PR if that's ok. At the moment the only place this method is used is in the ChargeQueryResponse, which wraps it in an Optional anyway

2019-02-22 09:38 UTC, oswaldquek approved these changes

2019-02-22 10:02 UTC, merged