PP-4653: Card holder name and email validation
alphagov/pay-connector pull request #1127
Opened 2019-03-05 17:20 UTC by oswaldquek

These must be validated before being passed to worldpay, lest we end up in a
situation where worldpay processes the payment, but connector throws an
error due to the card holder name and/or being over 255 characters limit as
specified in the database.

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2019-03-05 18:44 UTC, danworth requested changes
Looks very good, especially the refactoring to separate out the tests. Thanks for adding the validation to `wallets/apple` end-point, I had that on my mind to do but never did 😞 Query about email being `character varying(254)` in the charges table rather than 255 like the others and whether the validation should be 254 rather than 255?

2019-03-05 18:44 UTC, danworth commented on src/test/java/uk/gov/pay/connector/it/resources/CardResourceAuthoriseApplePayITest.java
> +import org.apache.http.HttpStatus;
I like these two separate test files for google and apple, makes it much easier to see what is covered and where rather than being buried amongst the regular card IT flow 👍

2019-03-05 18:44 UTC, danworth commented on src/main/java/uk/gov/pay/connector/paymentprocessor/resource/CardResource.java
> +                                    @NotNull @Valid ApplePayAuthRequest applePayAuthRequest) {
👍

2019-03-05 18:44 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/model/WalletPaymentInfo.java
> +    @Length(max = 255, message = "Card holder name must be a maximum of 255 chars")
Looks good as-is, if you didn't already know you can reference the values with template strings like `{max}` e.g. `"Card holder name must be a maximum of {max} chars"` but probably more descriptive as-is 👍

2019-03-05 18:44 UTC, danworth commented on src/main/java/uk/gov/pay/connector/wallets/model/WalletPaymentInfo.java
> +    @Length(max = 255, message = "Email must be a maximum of 255 chars")
Strangely in the db I see email is 254
`email  character varying(254)`
whilst `cardholder_name character varying(255)`. Maybe this should be constrained to 254?

2019-03-06 16:37 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/wallets/model/WalletPaymentInfo.java
> +    @Length(max = 255, message = "Card holder name must be a maximum of 255 chars")
good spot

2019-03-07 07:54 UTC, danworth submitted a review, later dismissed
Looks good.

2019-03-07 10:15 UTC, danworth approved these changes
👍

2019-03-07 10:16 UTC, merged