PP-5003: Add fee table schema migration
alphagov/pay-connector pull request #1161
Opened 2019-03-19 16:17 UTC by sfount

* Adds initial columns required for modelling fees
* Indexing gateway processing details will follow when we know what keys
are required

2019-03-19 16:21 UTC, mrlumbu requested changes

2019-03-19 16:21 UTC, mrlumbu commented on src/main/resources/migrations.xml
> +            <column name="created" type="timestamp without timezone" />
can this be created_date for consistency

2019-03-19 16:21 UTC, mrlumbu commented on src/main/resources/migrations.xml
> +        <createIndex tableName="fees" indexName="itx_fees_gateway_transaction_id">
`s/itx/idx/` ?

2019-03-20 09:14 UTC, sfount commented on src/main/resources/migrations.xml
> +            <column name="created" type="timestamp without timezone" />
👍 will line this up with other entities

2019-03-20 09:23 UTC, mrlumbu commented on src/main/resources/migrations.xml
> +    </changeSet>
probs need index on charge_id and external_id

2019-03-20 09:29 UTC, sfount commented on src/main/resources/migrations.xml
> +    </changeSet>
I've added these indexes to the same change set

2019-03-20 10:27 UTC, sfount commented
EDIT: Update fee constraints given: 
> Fees are modelled separately to reflect the second account debit transaction that is required on the Stripe gateway. For this use case they are 1:1 for a charge which is enforced in 87c575f. If multiple fees for a given charge become a use case in the future this constraint can be updated along with the "view" code for charges and their fees.

2019-03-20 15:50 UTC, mrlumbu approved these changes

2019-03-20 15:52 UTC, merged