PP-5010 Add fee entity
alphagov/pay-connector pull request #1166
Opened 2019-03-21 13:23 UTC by mrlumbu

Adds FeeEntity, and mapping to ChargeEntity.

    At present the only way we want to expose the fee is as part of the
   charge, so this commit adds a `getFeeAmount` method to the charge.
   This can safely get first fee from the hypothetical fee list,
   because the DB has a unique constraint on the charge_id FK column
   in the `fees` table, so the number of fees for a given charge is
   guaranteed to be 0 or 1.

    Passes through fee from ChargeEntity to ChargesFrontendResource and
   ChargeApiResource.

2019-03-21 13:48 UTC, sfount approved these changes
Looks good from a functionality perspective -- code looks good but would be good for some more familiar with Connector/ our Java code to approve this too. 

👍  Testing the fee collected is reflected as correct fee amount

2019-03-21 13:55 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +    private List<FeeEntity> fees = Collections.emptyList();
Given the number of fees for a given charge is guaranteed to be 0 or 1, is there any reason for using `@OneToMany` and a `List` of fees here? Or is for some future functionality?

2019-03-21 13:57 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/dao/ChargeDaoITest.java
> +
i'm somewhat uncomfortable that this test is in excess of 1558 lines, and would look to splitting this out by functionality

2019-03-21 13:57 UTC, sfount requested changes
It might be a good idea to test the search resources/ API endpoints that fetch multiple charges at once, just to make sure the entity is correctly propagated and there is no custom logic that will have to be updated.

2019-03-21 14:31 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +    private List<FeeEntity> fees = Collections.emptyList();
For some reason I thought this wasn't possible without specifying fee_id on charge, but turns out it is 👍

2019-03-21 14:32 UTC, mrlumbu commented on src/test/java/uk/gov/pay/connector/it/dao/ChargeDaoITest.java
> +
I agree, but would rather not do as part of this PR, as it will just muddy the waters. I can do as a separate PR 👍

2019-03-21 15:27 UTC, oswaldquek requested changes
Just a comment on the use of Optional

2019-03-21 15:27 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +        if (fee != null) {
`Optional.ofNullable` could be used?

2019-03-21 15:27 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/dao/ChargeDaoITest.java
> +
i agree

2019-03-21 15:50 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +        if (fee != null) {
Not sure you can - it's the fee that might be null, not the amount? Or maybe optional is cleverer than I thought.

Having checked, it's not

2019-03-21 15:53 UTC, mrlumbu commented
> It might be a good idea to test the search resources/ API endpoints that fetch multiple charges at once, just to make sure the entity is correctly propagated and there is no custom logic that will have to be updated.
I would like to do this in a separate PR

2019-03-21 15:54 UTC, sfount submitted a review, later dismissed

2019-03-21 15:57 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +        if (fee != null) {
To be honest, I misread it and missed the `fee.getAmountCollected()` bit. but one can still use "ofNullable" like `Optional.ofNullable(fee).map(f -> f.getAmountCollected())`

2019-03-21 15:58 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +        if (fee != null) {
or `Optional.ofNullable(fee).map(FeeEntity::getAmountCollected)` even

2019-03-21 16:27 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +        if (fee != null) {
yeah, true, that is nicer

2019-03-22 09:06 UTC, oswaldquek approved these changes

2019-03-25 10:52 UTC, merged