PP-5042 Make cancelling use smaller, tighter transactions
alphagov/pay-connector pull request #1175
Opened 2019-03-28 17:17 UTC by alexbishop1

When cancelling a charge, don’t do the entire operation, including sending a cancellation message to the gateway, inside a single transaction because this gives lots of time for something else to come in and change the charge in the mean time. Instead, have transactions tightly around just the database updates and do the communication with the gateway outside a transaction. This means we will atomically change the status to a `READY` state, then communicate with the gateway, then atomically change the status to a terminal cancellation state. If anything else tries to change the charge while we’re talking to the gateway, it will observe the charge in a `READY` state and know to not try to do that.

2019-03-28 17:25 UTC, kbottla requested changes

2019-03-28 17:25 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeCancelService.java
> +    @Transactional
This method should be public for \@Transactional annotation to work as per https://github.com/google/guice/wiki/Transactions

2019-03-28 17:25 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeCancelService.java
> +    private void setChargeStatusTo(ChargeEntity chargeEntity, ChargeStatus chargeStatus) {
Same as above for public method

2019-03-29 10:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeCancelService.java
> +    @Transactional
Oops! Will fix

2019-03-29 12:13 UTC, kbottla submitted a review, later dismissed
LGTM 👍

2019-04-01 13:27 UTC, alexbishop1 commented
End-to-end tests alerted us that this change wasn’t persisting the statuses correctly. Fixed that by making the code retrieve the `ChargeEntity` from the DAO between transactions (which required unit test changes).

2019-04-01 13:46 UTC, kbottla approved these changes
LGTM!

2019-04-01 13:51 UTC, merged