Pp 5022 Log payment processing certificate time to expire
alphagov/pay-connector pull request #1184
Opened 2019-04-03 10:18 UTC by oswaldquek

2019-04-03 13:56 UTC, alexbishop1 requested changes
Looks good — one small suggestion

2019-04-03 13:56 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/wallets/applepay/ApplePayDecrypter.java
> +        long daysToExpiry = TimeUnit.MILLISECONDS.toDays(certificate.getNotAfter().getTime() - new Date().getTime());
This might be a bit more readable:

```java
long daysToExpiry = ChronoUnit.DAYS.between(Instant.now(), certificate.getNotAfter().toInstant());
```

(Not checked if it behaves exactly the same for partial days but it’ll be close enough for our purposes as we’re always going renew the certificate several days before.)

2019-04-03 14:11 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/wallets/applepay/ApplePayDecrypter.java
> +        long daysToExpiry = TimeUnit.MILLISECONDS.toDays(certificate.getNotAfter().getTime() - new Date().getTime());
fixed

2019-04-03 19:07 UTC, alexbishop1 requested changes
Thanks for making the change. Please remove a couple of unused imports and then this is good to go.

2019-04-03 19:07 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/wallets/applepay/ApplePayDecrypter.java
> +import java.util.concurrent.TimeUnit;
These two imports aren’t actually used in the latest revision of this code

2019-04-03 19:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/wallets/applepay/ApplePayDecrypter.java
> +        long daysToExpiry = TimeUnit.MILLISECONDS.toDays(certificate.getNotAfter().getTime() - new Date().getTime());
Might actually be nice to statically import `ChronoUnit.DAYS` so this code becomes:

```java
long daysToExpiry = DAYS.between(Instant.now(), certificate.getNotAfter().toInstant());
```

2019-04-04 15:52 UTC, alexbishop1 approved these changes

2019-04-04 15:53 UTC, merged