PP-4884 Add validation for ExternalMetadata
alphagov/pay-connector pull request #1216
Opened 2019-04-17 13:51 UTC by danworth

## WHAT YOU DID
- Add validation to `ExternalMetadata` based on composing validations which gives us a fine grain control and flexibility of messages/ limits.
- Create custom validations for map key length, map value length and map value types.
- I would like to add this as-is (subject to review comments of course) to progress the story and unblock future work. I will revisit with a view of increasing the sophistication of the error messages to to reference the keys when a value is invalid.

2019-04-17 15:09 UTC, alexbishop1 requested changes
Looks good — a few things to look at

2019-04-17 15:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/MapKeySize.java
> +    int min() default 0;
Isn’t the minimum one character for keys?

2019-04-17 15:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/MapKeySizeValidator.java
> +                .size() == 0;
I’m not joking — this is literally the second time in two days I’ve seen some code that filters a stream, collects to a list and then checks the size of the list. So take comfort in the fact that you’re in good company when I say there’s an easier way to do this:

```java
return theMap.keySet().stream().noneMatch(key -> key.length() < min || key.length() > max);
```

2019-04-17 15:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/MapValueAsStringSizeValidator.java
> +                .filter(Objects::nonNull)
This will essentially remove null values when validating rather than their presence causing an error, which I don’t think is what we want

2019-04-17 15:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/MapValueAsStringSizeValidator.java
> +                .size() == 0;
Another `noneMatch(…)` opportunity

2019-04-17 15:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/MapValueTypesValidator.java
> +                .size() == 0;
Another fine `noneMatch(…)` opportunity

2019-04-17 15:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ValidExternalMetadata.java
> +@MapValueTypes(types = {String.class, Integer.class, Boolean.class}, message = "metadata values must be of type String, Boolean or Integer")
Didn’t we say any JSON number rather than just integers?

2019-04-17 15:09 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +        validator = vf.getValidator();
Can this be inlined into the `validator` field declaration?

```java
private final Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
```

This will re-initialise `validator` for every test but I assume it’s not too expensive to create?

2019-04-17 15:09 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +        }
An alternative way to initialise this map could be:

```java
Map<String, Object> metadata = IntStream.rangeClosed(1, 11).boxed()
        .collect(Collectors.toUnmodifiableMap(i -> "key" + i, i -> "value" + i));
```

2019-04-17 15:09 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +                "key3", mapper.createObjectNode()
I think I’d prefer if this was two tests (one for array node and one for object node). Right now, it will pass even if the code were only rejecting array nodes and allowing object nodes, for example.

2019-04-17 15:09 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +    }
Can we have some tests for some other cases?

- Null keys (should fail)
- Null values (should pass)
- Empty string keys (should fail)
- Empty string values (should pass)

2019-04-17 15:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/MapValueAsStringSizeValidator.java
> +                .filter(Objects::nonNull)
Actually, I’ve now realised that since we allow null values, this will actually do the right thing

2019-04-18 07:17 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/MapKeySize.java
> +    int min() default 0;
Its possible to use an empty string as a key in a map. Since this validation could be used elsewhere I thought best to set the default to 0 to permit "" as a key. When we use this annotation to compose `ValidExternalMetadata` I set the `min=1` since for our purposes we're not allowing an empty string as a key.

2019-04-18 07:18 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/MapKeySizeValidator.java
> +                .size() == 0;
Thank you! I will use `noneMatch` and spread the word.

2019-04-18 07:20 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/MapValueAsStringSizeValidator.java
> +                .filter(Objects::nonNull)
yep. There's a point of best practice with bean validation that nulls shouldn't be considered invalid unless the check is specifically designed to treat them as such. This allows us to create compound annotations by re-using others and where necessary using something like `@NotNull` to catch the null case. This also allows it to be used for the instance of "I don't care if its null, but if it is present then it must be..."

2019-04-18 07:21 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/MapValueAsStringSizeValidator.java
> +                .size() == 0;
done, thanks!

2019-04-18 07:21 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/MapValueTypesValidator.java
> +                .size() == 0;
Done :)

2019-04-18 07:22 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/ValidExternalMetadata.java
> +@MapValueTypes(types = {String.class, Integer.class, Boolean.class}, message = "metadata values must be of type String, Boolean or Integer")
Yes, I've adapted this now to check if the type of the value is of a subtype to those permitted. So I've exchanged `Integer` for `Number`.

2019-04-18 07:23 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +        }
I'm happy to adopt new ways and this is more succinct without the boilerplate `for` loop. I've added it. Thanks.

2019-04-18 07:24 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +                "key3", mapper.createObjectNode()
Ok, done.

2019-04-18 07:27 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +    }
Interestingly, since we added the defensive copy with `Map.copyOf` it will not permit null values. So it isn't possible to create an instance of `ExternalMetadata` with null values. This will have to be caught as part of the deserialisation which will follow.

I've added empty string values (pass) and empty string keys (fail).

2019-04-18 07:28 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +    }
As demonstrated with `JShell`
```
jshell> myMap.put("key1", null)
$6 ==> null

jshell> var copyMap = Map.copyOf(myMap);
|  Exception java.lang.NullPointerException
|        at Objects.requireNonNull (Objects.java:221)
|        at ImmutableCollections$Map1.<init> (ImmutableCollections.java:732)
|        at Map.ofEntries (Map.java:1611)
|        at Map.copyOf (Map.java:1684)
|        at do_it$Aux (#7:1)
|        at (#7:1)
```

2019-04-18 07:31 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +        validator = vf.getValidator();
Ok, I'm on the fence for this but I've adopted it for the benefit of brevity (it feels a little wasteful to keep initialising it thought).

2019-04-18 08:26 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/MapKeySize.java
> +    int min() default 0;
Ah, I see

2019-04-18 08:27 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +    }
Of course. And we do want to disallow null values (I was getting confused with empty string values, which we do want to allow).

2019-04-18 09:02 UTC, alexbishop1 requested changes
This looks good. One thing (which I really should have mentioned in the first review, sorry) is that a lot of the new stuff for string validation uses the term “size” but the usual term for strings is “length”. Could you change it please? I know I’m being a bit picky but I think it would aid understanding.

2019-04-18 09:02 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +    }
This is just a suggestion but I quite like to put blank lines in tests so that there’s the setup/stubbing, then a blank line, then the actual call that you’re trying to test, then a blank line, then the assertions and verifications. I find it makes it easier to see what the test is testing at a glance and makes it a bit simpler to understand the differences between each test. Like this:

```java
@Test
public void shouldFailValidationForKeysToLong() {
    Map<String, Object> metadata = Map.of(TOO_LONG_KEY, "string");
    ExternalMetadata invalidExternalMetadata = new ExternalMetadata(metadata);

    Set<ConstraintViolation<ExternalMetadata>> violations = validator.validate(invalidExternalMetadata);

    assertThat(violations.size(), is(1));
    assertThat(violations.iterator().next().getMessage(), is("metadata keys must be between 1 and 30 characters long"));
}
```

2019-04-18 09:13 UTC, danworth commented
The reason I used `size` was to be consistent with the terms used by the Validation api which uses
`@Size` https://docs.oracle.com/javaee/7/api/javax/validation/constraints/Size.html. However, since the types we're validating are always Strings (for now), it might make more sense to refer to it as Length. I'll change it.

2019-04-18 12:39 UTC, alexbishop1 commented
I didn’t realise “size” is an existing convention so I’m less bothered about it now.

2019-04-18 12:42 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/model/ExternalMetadataTest.java
> +    }
I like this format, so I've updated to match.

2019-04-18 12:51 UTC, alexbishop1 submitted a review, later dismissed
Looks good — one final suggestion but it’s fairly minor

2019-04-18 12:51 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/MapValueTypesValidator.java
> +                .noneMatch(value -> !validType(value.getClass()));
Would `.allMatch(value -> validType(value.getClass()))` work here too?

2019-04-18 12:51 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/MapValueTypesValidator.java
> +                .noneMatch(value -> !validType(value.getClass()));
Or maybe even make the whole thing into this:

 ```java
return theMap.values().stream()
        .filter(Objects::nonNull)
        .map(Object::getClass)
        .allMatch(this::validType);
```

2019-04-18 12:56 UTC, alexbishop1 approved these changes

2019-04-18 13:06 UTC, merged