Pp 5108 patch allow zero amount
alphagov/pay-connector pull request #1217
Opened 2019-04-17 15:53 UTC by stephencdaly

Add valid path to gateway account patch request which updates the allow_zero_amount flag on a gateway account.

Co-Authored-By Yancoba Thompson <yancoba.thompson@digital.cabinet-office.gov.uk>

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2019-04-17 16:05 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/common/model/api/jsonpatch/JsonPatchRequest.java
> +        return value.asText();
Removed this validation as the existing patch requests for updating boolean values on gateway accounts (allow_google_pay and allow_apply_pay) allow string representations of booleans (and selfservice sends a string!) and so use this method. 
They probably shouldn't but we need to keep backwards compatibility for now until that's changed and allow both text and boolean values for now.

2019-04-18 13:20 UTC, alexbishop1 requested changes
Looks good in general but I have a few qualms about how it validates

2019-04-18 13:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/common/model/api/jsonpatch/JsonPatchRequest.java
> +        return value.asText();
I don’t think I follow why this is necessary — can’t `GatewayAccountService` call `valueAsBoolean()` for `allow_zero_amount` (but continue calling `valueAsString()` for `allow_google_pay` and `allow_apple_pay`?

This change would also mean that one could call `valueAsString()` on a numeric value and get its stringification, which is more loose than I think we want.

2019-04-18 13:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidator.java
> +    private void validateReplaceBooleanValue(JsonNode payload, String field) {
I think I’d prefer if we didn’t try to use the same validation for `allow_zero_amount` (which will be a boolean) and `allow_google_pay` and `allow_apple_pay` (which will be a string of either `"true"` or `"false"`). I think we’d be better off with two separate methods (with a view to fixing the abomination that is booleans-as-strings for Web payments config in the future).

2019-04-18 13:20 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidatorTest.java
> -    }
I see this has been removed because it’s now handled by the expanded and renamed `shouldThrowWhenRequestsAreInvalid` test.

2019-04-18 13:20 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/GatewayAccountServiceTest.java
> +        verify(mockGatewayAccountDao).merge(entity);
Since there’s only two possible values, I don’t think it would be too much of a stretch to also have a test for setting it to `false` (with the gateway account having it set to `true` at the beginning so we know it’s actually changing something).

2019-04-18 14:55 UTC, cobainc0 commented on src/test/java/uk/gov/pay/connector/service/GatewayAccountServiceTest.java
> +        verify(mockGatewayAccountDao).merge(entity);
👍 done

2019-04-18 14:55 UTC, cobainc0 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountRequestValidator.java
> +    private void validateReplaceBooleanValue(JsonNode payload, String field) {
As discussed, we will keep this for now with a view to updating `allow_google_pay` and `allow_apple_pay` to booleans rather than Strings.

2019-04-18 15:01 UTC, alexbishop1 approved these changes

2019-04-18 15:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/common/model/api/jsonpatch/JsonPatchRequest.java
> +        return value.asText();
As discussed, we’ll have this go in as it is, then change `allow_google_pay` and `allow_apple_pay` to use real (not stringified!) booleans, then change this back

2019-04-18 15:38 UTC, merged