PP-4884 Add ExernalMetadata to create charge request
alphagov/pay-connector pull request #1221
Opened 2019-04-18 14:06 UTC by danworth

- Add `ExternalMetadata` to `ChargeCreateRequest`
- Add `ExternalMetadata` to `ChargeService`
- Add test to `ChargeServiceTest`
- Add `ChargesApiCreateResourceITest` tests for externalMetadata.
- Add `ExternalMetadataDeserialiser`
- Add validation for map values being null.

## WHAT YOU DID
This does not include returning the metadata in the response which is covered by PP-4885. The ITest therefore checks that is has been persisted to the database and stops short of checking it is present in the successful response.

2019-04-18 14:25 UTC, danworth commented
The failing Codacy check is for `JUnit tests should include assert() or fail()` which isn't always appropriate for us when we're testing with a `RestAssured.ValidatableResponse`

2019-04-18 14:33 UTC, alexbishop1 commented
Yeah, we need to update the Codacy rules to better match our circumstances. They’re basically just the defaults right now.

2019-04-18 14:58 UTC, alexbishop1 requested changes
Looks good — just a few small things

2019-04-18 14:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ExternalMetadata.java
> +        this.metadata = metadata;
Were we not going to move the `Map.copyOf(…)` to the getter?

2019-04-18 14:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    chargeRequest.getExternalMetadata().orElse(null));
If it’s not too much bother, I think it might be good to have two constructors: one with external metadata and one without)

2019-04-18 14:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/util/ExternalMetadataDeserialiser.java
> +    public ExternalMetadata deserialize(final JsonParser p, final DeserializationContext ctxt) throws IOException {
Can we use something a bit more descriptive than `p`?

https://www.youtube.com/watch?v=wi-H6ohY37k

2019-04-18 14:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ValidExternalMetadata.java
> +@MapValueNotNull(message = "Field [metadata] values must not be null")
This is identical to the `@NotNull` error message. Maybe use `Field [metadata] must not be null` for that one and `Field [metadata] must not have null values` for this one?

2019-04-18 15:04 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    chargeRequest.getExternalMetadata().orElse(null));
I feel that would make it more complicated for not a huge gain? We would have to check whether getExternalMetadata is present before then selecting the correct version? I think the optional.orElse make its easy to see what's going on and it saves having two very similar constructors and keeps it more succinct.

2019-04-18 15:05 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/util/ExternalMetadataDeserialiser.java
> +    public ExternalMetadata deserialize(final JsonParser p, final DeserializationContext ctxt) throws IOException {
yes, good idea.

2019-04-18 15:06 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/ValidExternalMetadata.java
> +@MapValueNotNull(message = "Field [metadata] values must not be null")
Not quite identical, one has `value` the other `values` but I see your point. I'll update, thanks 👍

2019-04-18 15:46 UTC, alexbishop1 submitted a review, later dismissed
Still a couple of things I’m a little sad about but following our discussion I’m happy to approve

2019-04-18 15:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ExternalMetadata.java
> +        this.metadata = metadata;
As discussed, maybe it’s probably not worth having `Map.copyOf(…)` in the getter.

It makes me sad that we can’t make a private unmodifiable map from the source map because that would disallow null values and a pre-validation `ExternalMetadata` might have null values (it’s a real shame that the validation works this way because it makes it harder to have types that maintain their invariants — particularly in this case where the fact we’re converting a map into an `ExternalMetadata` means the `ExternalMetadata` doesn’t have the annotations on it so it’s not obvious what the constraints are).

2019-04-18 15:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    chargeRequest.getExternalMetadata().orElse(null));
Using a separate constructor would make it clear that a charge can be created without metadata. Though the fact that the getter returns an optional hopefully makes this clear.

I suppose the other alternative would be to have a `ChargeEntityBuilder`, which could be used like this:

```java
ChargeEntityBuilder chargeEntityBuilder = new ChargeEntityBuilder(
        chargeRequest.getAmount(),
        chargeRequest.getReturnUrl(),
        chargeRequest.getDescription(),
        ServicePaymentReference.of(chargeRequest.getReference()),
        gatewayAccount,
        chargeRequest.getEmail(),
        language,
        chargeRequest.isDelayedCapture());

chargeRequest.getExternalMetadata().ifPresent(ChargeEntityBuilder::withExternalMetadata);

ChargeEntity chargeEntity = chargeEntity.build();
```

2019-04-23 10:01 UTC, alexbishop1 requested changes
This is good. Just a few really small things.

2019-04-23 10:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ExternalMetadata.java
> +        this.metadata = new HashMap<>(Objects.requireNonNull(metadata));
`Objects.requireNonNull(metadata)` will just throw a `NullPointerException` if `metadata` is null, which is the same thing that will happen if the `HashMap` constructor is invoked with a null `metadata`, so I think this can just be `new HashMap(metadata)`

2019-04-23 10:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ExternalMetadata.java
> +        return Collections.unmodifiableMap(metadata);
I think I’d prefer it if this was `Map.copyOf(metadata)` so anyone can tell at a glance that it’s an [unmodifiable map](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.html#unmodifiable) (not to be confused with an [unmodifiable view collection](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Collection.html#unmodview)!) — in particular, that it will never have null values. (I recognise this will be slightly less efficient but I don’t think it’s going to make a noticeable difference for small maps we’d be dealing with.)

2019-04-23 10:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    chargeRequest.getExternalMetadata().orElse(null));
As discussed in person, we pinky-swear to add a builder if we add any more optional fields to `ChargeEntity` but will leave it for now

2019-04-23 10:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        return cardDetailsEntity;
This ended up much nicer!

2019-04-23 10:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/JsonMappingExceptionMapper.java
> +        ImmutableMap<String, String> entity = ImmutableMap.of("message", exception.getMessage());
Can just use `Map.of(…)` here

2019-04-23 10:07 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/model/ExternalMetadata.java
> +        this.metadata = new HashMap<>(Objects.requireNonNull(metadata));
Fair point, I've removed.

2019-04-23 10:09 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/model/ExternalMetadata.java
> +        return Collections.unmodifiableMap(metadata);
I felt that using `Collections.unmodifiableMap` had the benefit (relatively speaking) that it permits `null` values, so we don't end up in a position where we've accepted something through the constructor which we could never return, which makes me uneasy.

2019-04-23 10:11 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/JsonMappingExceptionMapper.java
> +        ImmutableMap<String, String> entity = ImmutableMap.of("message", exception.getMessage());
Good catch

2019-04-23 10:15 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ExternalMetadata.java
> +        return Collections.unmodifiableMap(metadata);
Yeah, I can see your point. In an ideal world, it would be cool if we could convert the object into another object after validating. But we don’t live in an ideal world. So I’m happy with `Collections.unmodifiableMap(…)`.

It’s a shame it’s a bit non-obvious that we have to allow the class to be instantiated with null values but it will never actually have them because of the validation.

2019-04-23 10:32 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/model/ExternalMetadata.java
> +        return Collections.unmodifiableMap(metadata);
Yes agreed. It seems the `@Valid` within a REST API relies on Jackson having deseriliased it and then validating it so we must permit invalid values through 😞 . I tried moving the validation to within the custom deserializer and validate based on calling the constructor having annotated the `metadata` parameter with `@ValidExternalMetadata`; this can be done manually with `ExecutableValidator.validateConstructorParameters()`. This validated it prior to instantiating the object and caught null values then throwing a `ConstraintViolationException`, but unfortunately Jackson catches any exception during marshalling and wraps in a `JsonProcessingException`. It also felt that moving the validation logic into the deserialisation wouldn't be obvious to someone in the future since `@Valid` would not invoke it (or if the validation was on both the constructor parameter and the class attribute, it would be called twice....)

2019-04-23 11:06 UTC, alexbishop1 approved these changes

2019-04-23 11:21 UTC, danworth commented
The Codacy prompts are based on needing `assert()` and no `_` in method names, both of which are not appropriate here. I'm merging as-is.

2019-04-23 16:03 UTC, merged