PP-5142 Use ErrorResponse to construct responses created by ResponseUtil
alphagov/pay-connector pull request #1256
Opened 2019-05-01 15:13 UTC by stephencdaly

- Modify ResponseUtil so that most of the methods that construct an error response use the ErrorResponse model.
- Modify tests to expect a "messages" array and to assert on the "error_identifier" - which has a value of "GENERIC" for all responses currently.
- Not all responses have been converted to use ErrorResponse yet.

2019-05-01 15:35 UTC, stephencdaly commented
Codacy errors are for underscores in test names, which we don't want to enforce

2019-05-01 16:11 UTC, alexbishop1 requested changes
Looks fine — just a couple of things with imports (which can be fixed in a new commit so I don’t have to look through all 300+ lines again!)

2019-05-01 16:11 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceITest.java
> +                .body("error_identifier", Matchers.is(ErrorIdentifier.GENERIC.toString()));
Please static import `is`

2019-05-01 16:11 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/wallets/applepay/ApplePayServiceTest.java
> +        MatcherAssert.assertThat(response.getMessages(), contains("oops"));
Please static import `assertThat`

2019-05-01 16:19 UTC, stephencdaly commented
Thanks for the review, I've pushed a commit with those changes

2019-05-01 16:36 UTC, alexbishop1 requested changes
Missed a few…

2019-05-01 16:36 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceITest.java
> +                .body("error_identifier", Matchers.is(ErrorIdentifier.GENERIC.toString()));
And this one

2019-05-01 16:36 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceITest.java
> +                .body("error_identifier", Matchers.is(ErrorIdentifier.GENERIC.toString()));
And this one

2019-05-01 16:36 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/wallets/googlepay/GooglePayServiceTest.java
> +        MatcherAssert.assertThat(response.getMessages(), contains("oops"));
And this one

2019-05-02 08:53 UTC, stephencdaly commented
I got all of them now

2019-05-02 09:09 UTC, stephencdaly commented
I just force pushed to remove some unused imports

2019-05-02 09:37 UTC, alexbishop1 requested changes
Please don’t hate me

2019-05-02 09:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/gatewayclient/GatewayInvalidUrlITest.java
> +        Assert.assertThat(app.getDatabaseTestHelper().getChargeStatus(testCharge.getChargeId()), is(CAPTURE_APPROVED_RETRY.getValue()));
Could you static import this too please (there are a few more in other files)

2019-05-02 09:47 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/it/gatewayclient/GatewayInvalidUrlITest.java
> +        Assert.assertThat(app.getDatabaseTestHelper().getChargeStatus(testCharge.getChargeId()), is(CAPTURE_APPROVED_RETRY.getValue()));
(╯°□°)╯︵ ┻━┻

2019-05-02 09:47 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/it/gatewayclient/GatewayInvalidUrlITest.java
> +        Assert.assertThat(app.getDatabaseTestHelper().getChargeStatus(testCharge.getChargeId()), is(CAPTURE_APPROVED_RETRY.getValue()));
sure

2019-05-02 10:45 UTC, alexbishop1 approved these changes

2019-05-02 10:49 UTC, merged