PP-5143 Allow zero amount charges if gateway account allows it
alphagov/pay-connector pull request #1297
Opened 2019-05-13 14:06 UTC by alexbishop1

If a gateway account is has `allow_zero_amount` set to `true`, allow a payment to be created with an amount of 0. If `allow_zero_amount` is `false`, return a 422 response with a new error:

```json
{
    "error_identifier": "ZERO_AMOUNT_NOT_ALLOWED",
    "message": ["Zero amount charges are not enabled for this gateway account"]
}
```

Details:

- Change the validation for amount from being `@Min(value = 1)` to `@Min(value = 0)`
- Make amount in `ChargeCreateRequest` a boxed type so that if it’s missing in the request it doesn’t default to 0 and then pass validation — this changes the error message returned if the amount is missing to explicitly complain it’s null (rather than just between the accepted values) but this is actually more accurate
- Update the amount out of range validation error message so it describes the new minimum of 0 rather than 1
- Put a check in `ChargeService` that throws a `ZeroAmountNotAllowedForGatewayAccountException` if an amount of 0 is provided but the gateway account has `allow_zero_amount` set to `false`
- Add an exception mapper to map the `ZeroAmountNotAllowedForGatewayAccountException` to the appropriate response

2019-05-13 15:28 UTC, oswaldquek requested changes

2019-05-13 15:28 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/app/ConnectorApp.java
> +        environment.jersey().register(new LoggingExceptionMapper<>() {
can lines 104-105 be collapsed into a single line please?

2019-05-13 15:28 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeCreateRequest.java
> +    private Long amount; // Long not long so missing doesn’t get deserialised to 0
If we have a test for a missing amount, I don't think we need this comment here.

2019-05-13 15:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/exception/ZeroAmountNotAllowedForGatewayAccountExceptionMapperTest.java
> +    public void toResponseReturns422JsonWithZeroAmountNotAllowedErrorIdentifierAndMessage() {
this seems like it's already covered in ChargeServiceTest.shouldReturn422WhenAmountIsZeroIfAccountDoesNotAllowIt

2019-05-13 15:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiCreateResourceITest.java
> +        String expectedDescription = "Test description";
can `expectedReference` and `expectedDescription` not be inlined? i don't see the value of declaring them separately as they're only used once in lines 253 and 254.

2019-05-13 16:08 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ConnectorApp.java
> +        environment.jersey().register(new LoggingExceptionMapper<>() {
Sure

2019-05-13 16:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeCreateRequest.java
> +    private Long amount; // Long not long so missing doesn’t get deserialised to 0
We do have a test that will fail — I thought it was worth noting because the behaviour is rather surprising but I can remove it if you think it’s unnecessary

2019-05-13 16:12 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/exception/ZeroAmountNotAllowedForGatewayAccountExceptionMapperTest.java
> +    public void toResponseReturns422JsonWithZeroAmountNotAllowedErrorIdentifierAndMessage() {
It’s `ChargesApiCreateResourceITest.shouldReturn422WhenAmountIsZeroIfAccountDoesNotAllowIt`, which is an integration test rather than a unit test. I was in two minds about the value of adding this unit test though, so I can remove it.

2019-05-13 16:15 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiCreateResourceITest.java
> +        String expectedDescription = "Test description";
They can, but all the tests follow this format. How about I leave it as it is for now and create a follow-up PR to make the change across all the tests in the class?

2019-05-14 07:44 UTC, oswaldquek requested changes
Thanks for addressing the comments. Just one more which was flagged by Codacy.

2019-05-14 07:44 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/exception/ZeroAmountNotAllowedForGatewayAccountExceptionMapper.java
> +    static final String RESPONSE_ERROR_MESSAGE = "Zero amount charges are not enabled for this gateway account";
Codacy flagged this. Should this be private?

2019-05-14 08:27 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/exception/ZeroAmountNotAllowedForGatewayAccountExceptionMapper.java
> +    static final String RESPONSE_ERROR_MESSAGE = "Zero amount charges are not enabled for this gateway account";
This is actually something where Codacy and IntelliJ give conflicting advice and in previous discussions we’ve said we should reconfigure Codacy. In any case, this constant used to be used by the test but since we don’t have a specific test for this class now, it can be made private.

2019-05-14 08:36 UTC, oswaldquek approved these changes

2019-05-14 10:04 UTC, merged