PP-5167 Managed message receiver
alphagov/pay-connector pull request #1316
Opened 2019-05-17 12:37 UTC by sfount

Basic life cycle for receiving messages; will be updated to use `CaptureQueue` abstraction with the introduction of https://github.com/alphagov/pay-connector/pull/1312

Requirements: 
- [ ] tests for deleting messages in the SQSQueueService 
- [ ] unit tests for receiver thread responding and logging

2019-05-20 12:03 UTC, sfount commented on pom.xml
> +            <exclusions>
This can be removed - it should have been addressed in https://github.com/alphagov/pay-connector/pull/1317/files

2019-05-20 13:57 UTC, kbottla commented on pom.xml
> +            <exclusions>
Addressed here https://github.com/alphagov/pay-connector/pull/1321 but this PR is failing on CI for some reason but works fine locally

2019-05-21 10:10 UTC, mrlumbu requested changes
Looks like a good start. I have made some suggestions around naming that I think clarify what's going on (at least for me). I also have some questions about the level at which things are happening - e.g. the CaptureQueue doing the capture itself. Might be good to talk this through

2019-05-21 10:10 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/queue/managed/SQSMessageReceiver.java
> +        int INITIAL_DELAY = 1;
`SCREAMING_SNAKE_CASE` is conventionally reserved for static final fields. I understand (and applaud) the intent to make this readable by using named variables, but please use camel case

2019-05-21 10:10 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/queue/managed/SQSMessageReceiver.java
> +public class SQSMessageReceiver implements Managed {
I don't think this class has anything to do with SQS, so should not refer to it in its name. Either `QueueMessageReciever` or `CaptureQueueMessageReciever` would be fine, depending on how we envisage this classes responsibilities growing in future (we don't have to decide now, so probably `CaptureQueueMessageReciever`?)

2019-05-21 10:10 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/queue/managed/SQSMessageReceiver.java
> +        int INITIAL_DELAY = 1;
also, ideally these values would be fetched from config, and set by env var with sensible defaults. Happy for that to be in a separate PR though

2019-05-21 10:10 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/queue/sqs/SqsQueueService.java
> +            Integer MAX_MESSAGES = 10;
I think this should either be in config, or just inline in the method call (it is clear what it is from name of method)

2019-05-21 10:10 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/queue/sqs/SqsQueueService.java
> +            ReceiveMessageResult receiveMessageResult = sqsClient.receiveMessage(receiveMessageRequest.withMessageAttributeNames(messageAttributeName));
```
ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest(queueUrl)
                    .withMaxNumberOfMessages(MAX_MESSAGES)
                    .withMessageAttributeNames(messageAttributeName);

            ReceiveMessageResult receiveMessageResult = sqsClient.receiveMessage(receiveMessageRequest);
```
?

2019-05-21 10:10 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/queue/sqs/SqsQueueService.java
> +    public DeleteMessageResult deleteMessage(String queueUrl, QueueMessage message) throws QueueException {
Slightly cleaner if this just took a `messageReceiptHandle`? Since that's all that's needed

2019-05-21 10:10 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/queue/CaptureQueue.java
> +                cardCaptureMessageProcess.runCapture(message);
I know you discussed this, but this seems like it's doing too much given the method name - I would expect the caller of `receiveCaptureMessages` to take the messages and do sensible things with them

2019-05-21 10:10 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/queue/managed/SQSMessageReceiver.java
> +    private final int TOTAL_MESSAGE_RECEIVER_THREADS = 1;
as with below, this should be in config (ideally), or `private static final`

2019-05-21 10:10 UTC, mrlumbu commented on src/test/java/uk/gov/pay/connector/queue/managed/SQSMessageReceiverTest.java
> +public class SQSMessageReceiverTest {
I salute your diligence but not sure we need these tests. What are they guarding against?

2019-05-21 10:10 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureMessageProcess.java
> +public class CardCaptureMessageProcess {
Not sure why this is a `Process`? Also not sure if we need this over just using `ChargeCaptureService`?

2019-05-21 11:22 UTC, sfount commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureMessageProcess.java
> +public class CardCaptureMessageProcess {
This will replace the current `CardCaptureProcess` when the feature flag is fully enabled, this is a parallel class with similar interface. Moved receive + process logic into this class to reduce complexity in `CaptureQueue`

2019-05-21 11:22 UTC, sfount commented on src/main/java/uk/gov/pay/connector/queue/sqs/SqsQueueService.java
> +            ReceiveMessageResult receiveMessageResult = sqsClient.receiveMessage(receiveMessageRequest.withMessageAttributeNames(messageAttributeName));
👍

2019-05-21 11:23 UTC, sfount commented on src/main/java/uk/gov/pay/connector/queue/sqs/SqsQueueService.java
> +    public DeleteMessageResult deleteMessage(String queueUrl, QueueMessage message) throws QueueException {
👍

2019-05-21 11:24 UTC, sfount commented on src/test/java/uk/gov/pay/connector/queue/managed/SQSMessageReceiverTest.java
> +public class SQSMessageReceiverTest {
This just tests that the correct number of processes is spun up by the scheduler - I think it will become more useful when there is more custom behaviour (rather than just one thread running)

2019-05-21 11:24 UTC, sfount commented on src/main/java/uk/gov/pay/connector/queue/CaptureQueue.java
> +                cardCaptureMessageProcess.runCapture(message);
Moved receive + process logic, ref: https://github.com/alphagov/pay-connector/pull/1316#discussion_r285974600

2019-05-21 12:15 UTC, mrlumbu submitted a review, later dismissed
👍Nice one

2019-05-21 12:15 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/queue/sqs/SqsQueueService.java
> +import com.amazonaws.services.sqs.model.*;
we try to avoid wildcard imports to keep @alexbishop1 happy. But can be done in next PR

2019-05-21 12:15 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureMessageProcess.java
> +        for (QueueMessage message: captureMessages) {
might be nice to `stream` this, but can be done later

2019-05-21 12:57 UTC, mrlumbu approved these changes

2019-05-21 15:20 UTC, merged