PP-5280 Fix SQSClient for non-standard SQS endpoint
alphagov/pay-connector pull request #1339
Opened 2019-05-24 13:21 UTC by kbottla

## WHAT YOU DID
- AWS SQS SDK defines non-standard endpoint as a custom SQS url (http://own-sqs-url).
  While endpoint is not needed in EC2 environment (SQS SDK will determine based on region),
  it is required (along with credentials)  while spinning up SQS equivalent containers for development/CI.

  The change includes initiating SQSClient with `endpoint and also credentials` required for development and CI

- Renamed `CardResourceCaptureWithSqsQueueITest` -> CardResourceCaptureWithSqsQueueIT (to failsafe plug way for integration tests)

## How to test

- CI should continue to pass
- Should pass locally with the below command even when `.aws` folder is users home directory
   ` mvn verify -Dit.test=uk.gov.pay.connector.it.resources.CardResourceCaptureWithSqsQueueIT`
## Code review checklist

### Documentation

- [x] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable

2019-05-24 14:48 UTC, mrlumbu requested changes
One suggestion

2019-05-24 14:48 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/app/ConnectorModule.java
> +        if (connectorConfiguration.getSqsConfig().isNonStandardServiceEndpoint()) {
do you think we should do some validation of the config to ensure that if `isNonStandardServiceEndpoint` is true that an endpoint is set?

2019-05-24 15:16 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/app/ConnectorModule.java
> +        if (connectorConfiguration.getSqsConfig().isNonStandardServiceEndpoint()) {
Integration tests are set with `isNonStandardServiceEndpoint` to true as its sole purpose is to support local development and CI. May be that is sufficient for this ?

If we want, is there a way to add validation to config fields based on the values of other ?

2019-05-24 15:28 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/app/ConnectorModule.java
> +        if (connectorConfiguration.getSqsConfig().isNonStandardServiceEndpoint()) {
don't think so (although @danworth may know of a way) - but you could still just check the condition holds and if not throw a RuntimeException of some sort

2019-05-24 15:28 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/app/ConnectorModule.java
> +        if (connectorConfiguration.getSqsConfig().isNonStandardServiceEndpoint()) {
but yeah, I guess this is just for tests for now, 👍

2019-05-24 15:29 UTC, mrlumbu approved these changes

2019-05-29 09:06 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/app/ConnectorModule.java
> +        if (connectorConfiguration.getSqsConfig().isNonStandardServiceEndpoint()) {
I will raise a separate PR for validation

2019-05-29 09:06 UTC, merged