PP-5317: emitting PaymentDetailsEnteredEvent
alphagov/pay-connector pull request #1431
Opened 2019-06-25 14:40 UTC by jankowiakmaria

* add `PaymentDetailsEnteredEvent` (tests covering producing the JSON)
* refactor `ChargeService` with proxy methods
* update definition of `emitEvent` in `ChargeService`

Questions/Doubts:
* I've refactored how wallet payment is being updated - instead of first calling `updateChargePostAuthorisation` and then setting email and wallet type (in Transactional context) it passes optional email and wallet and the `updateChargePostAuthorisation` updates the values if they exist. It caused one of the test to fail (the setup was putting an email address in the charge and the test was authorising with null value) - Is it deliberate behaviour? Is there a scenario where we have the email/wallet type already in the charge and we want to update them to `null` values?
* the other thing is: the timestamp is supposed to be taken from db (not part of this PR) when the `ChargeEventEntity` is inserted - the current logic retrieves all the charge events and gets the latest timestamp - the potential risk is that there might be another `ChargeEventEntity` inserted in the meantime.

Comments/Thoughts more than welcome.

2019-06-25 15:23 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +            throw e;
not sure why this has been added?

2019-06-26 07:57 UTC, jankowiakmaria commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +            throw e;
debugging leftover - thanks for catching it.

2019-06-26 08:19 UTC, mrlumbu requested changes

2019-06-26 08:19 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    public ChargeEntity updateChargeAndEmitEventPostAuthorisation(String chargeExternalId,
can be private, and I think this would make it clearer what the interface is given all these proxy methods

2019-06-26 08:19 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/events/PaymentDetailsEnteredEvent.java
> +}
suggestion for future: we should be able to push down more of the object construction to base class

2019-06-26 08:19 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/events/PaymentDetailsEnteredEvent.java
> +                .orElse(null);
think this should be an exception. We don't want to publish events with no timestamp, and there is no reason why there would be no events for a charge at this point in lifecycle

2019-06-26 09:39 UTC, mrlumbu approved these changes
👍 Looks good. As discussed, I think this PR highlights some areas where code could be improved, but that is beyond scope of this work

2019-06-26 09:45 UTC, merged