PP-5547 Add Json Web Token support
alphagov/pay-connector pull request #1602
Opened 2019-08-15 14:07 UTC by danworth

Create a JWTFacade class to offer simple creation of JWTs. This uses
`io.jsonwebtoken` which is listed as a reputable library on `jwt.io`, it
has a simple builder pattern to generate the tokens and an Apach 2.0
licence. It enforces key strength when signing and will not permit the
use of a key considered too weak for the desired algorithm (e.g. for
HSA256 the key must be greater than 256 bits). Since the Worldpay test
token is only 288 bits and we cannot change it, this initial
implementation uses HSA256 to sign the JWT, which is supported by
Worldpay.

This commit includes the first public method on the facade to generate a
Worldpay 3DS Flex DDC token and a unit test to ensure the token, when
decoded includes the correct header and body elements.

## How to test
I've added a unit test but you can independently check this generates valid tokens using https://www.jsonwebtoken.io

2019-08-15 14:33 UTC, alexbishop1 requested changes
Looks good — just a couple of things

2019-08-15 14:33 UTC, alexbishop1 commented on pom.xml
> +            <version>0.10.7</version>
Can you extract these version strings into a property?

2019-08-15 14:33 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/util/JwtFacade.java
> +public class JwtFacade {
I’d be really specific with this name and call it `Worldpay3dsFlexDdcJwtGenerator` or something. We’re going to want different JWTs in different places — if we have specific classes for generating each, we can inject just what we need wherever we need it.

2019-08-15 14:33 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/util/JwtFacade.java
> +     * Utility method to create a JWT token for Worldpay 3DS Flex DDC based upon the required claims
“JWT token” = “JSON Web Token token” 😀

2019-08-15 14:33 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/util/JwtFacadeTest.java
> +        assertThat(jws.getBody().get("jti"), notNullValue());
`is(notNullValue())` would be more consistent

2019-08-15 14:34 UTC, danworth commented on pom.xml
> +            <version>0.10.7</version>
yes good idea, I've got that change ready to go 👍

2019-08-15 14:34 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/util/JwtFacade.java
> +     * Utility method to create a JWT token for Worldpay 3DS Flex DDC based upon the required claims
lol I thought I'd stopped myself from doing that. Removed 😄

2019-08-15 14:50 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/util/JwtFacade.java
> +public class JwtFacade {
Renamed it JwtGenerator and we can look at what abstraction or specificity is required as it's use evolves with the future planned uses.

2019-08-15 14:51 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/util/JwtFacadeTest.java
> +        assertThat(jws.getBody().get("jti"), notNullValue());
Done 👍

2019-08-15 15:49 UTC, alexbishop1 requested changes
Thanks for making the changes. Just a couple of tiny things…

2019-08-15 15:49 UTC, alexbishop1 commented on pom.xml
> +        <jsonwebtoken.version>0.10.7</jsonwebtoken.version>
I’m being picky here but the library is called JJWT. It’s good to be unambiguous in case some horror means we end up with multiple JWT libraries!

2019-08-15 15:49 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/util/JwtGeneratorTest.java
> +    public void shouldCreateCorrectTokenForWorldPay3ds2() {
Missed this last time: can you make this `shouldCreateCorrectTokenForWorldpay3dsFlexDdc` or something, as we’ll be doing other Worldpay JWTs later.

2019-08-16 07:34 UTC, danworth commented on pom.xml
> +        <jsonwebtoken.version>0.10.7</jsonwebtoken.version>
Yes, don't worry about being picky, I'd rather you were.

2019-08-16 07:34 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/util/JwtGeneratorTest.java
> +    public void shouldCreateCorrectTokenForWorldPay3ds2() {
Yeah 👍

2019-08-16 08:51 UTC, alexbishop1 approved these changes

2019-08-16 12:57 UTC, merged