bau: Log when dropwizard shutdowns in tests
alphagov/pay-connector pull request #1613
Opened 2019-08-16 15:16 UTC by oswaldquek

Am not sure why SendRefundEmailIT.shouldSendEmailFollowingASuccessfulRefund
occasionally fails. When it does there is a log `Email notifications is
disabled by configuration` which would explain why the test failed but at this
point I'm not sure why dropwizard was started with a wrong config, as
SendRefundEmailIT overrides the `notifyConfig.emailNotifyEnabled` to be `true`.

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2019-08-16 16:26 UTC, stephencdaly requested changes

2019-08-16 16:26 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthServiceTest.java
> +    }
Guessing you didn't mean to commit this

2019-08-16 16:32 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthServiceTest.java
> +    }
removed

2019-08-19 08:47 UTC, stephencdaly approved these changes

2019-08-19 08:53 UTC, merged