PP-5402 Creates methods in ChargeService to persist TelephoneCharge to DB
alphagov/pay-connector pull request #1614
Opened 2019-08-17 14:14 UTC by nimalank7

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2019-08-20 15:36 UTC, mrlumbu requested changes
I think it would be good to have a quick chat about this, just so I understand the direction you're heading in. It maybe that it is necessary to separate the Telephone payment path as much as you have done, but I'm not totally convinced. I have also made comments about naming and unsafe use of Optionals that need addressing

2019-08-20 15:36 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    public Optional<TelephoneChargeResponse> findTelephoneCharge(TelephoneChargeCreateRequest telephoneChargeRequest, Long accountId, UriInfo uriInfo) {
not sure what the purpose of this method is?

2019-08-20 15:36 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private Optional<ChargeEntity> createTelephoneChargeEntity(TelephoneChargeCreateRequest telephoneChargeRequest, Long accountId, UriInfo uriInfo) {
I think the name should just be createCharge, there is nothing special about a telephone charge once it is created. The method will be clear enough because of the argument types

2019-08-20 15:36 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                .processorId((String) chargeEntity.getExternalMetadata().get().getMetadata().get("processor_id"))
what if the Optional external metadata is empty?

2019-08-20 15:36 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private ExternalMetadata storeExtraFieldsInMetaDataForTelephonePayments(TelephoneChargeCreateRequest telephoneChargeRequest) {
again, no need to reference telephone in method name - will be clear enough from types.

2019-08-20 15:36 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    public Optional<TelephoneChargeResponse> createTelephoneCharge(TelephoneChargeCreateRequest telephoneChargeCreateRequest, Long accountId, UriInfo uriInfo) {
Do we definitely need to return a `TelephoneChargeResponse` as opposed to a normal `ChargeResponse`? I'm a bit concerned that you are creating loads of new objects that look a lot like existing things

2019-08-21 14:44 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            if (telephoneChargeRequest.getAmount() == 0L && !gatewayAccount.isAllowZeroAmount()) {
does this logic not exist somewhere already?

2019-08-21 20:54 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private ExternalMetadata storeExtraFieldsInMetaDataForTelephonePayments(TelephoneChargeCreateRequest telephoneChargeRequest) {
Done.

2019-08-21 20:54 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    public Optional<TelephoneChargeResponse> createTelephoneCharge(TelephoneChargeCreateRequest telephoneChargeCreateRequest, Long accountId, UriInfo uriInfo) {
Refactored into ChargeResponse

2019-08-21 20:55 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                .processorId((String) chargeEntity.getExternalMetadata().get().getMetadata().get("processor_id"))
Added ifPresent to handle case.

2019-08-21 20:55 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private Optional<ChargeEntity> createTelephoneChargeEntity(TelephoneChargeCreateRequest telephoneChargeRequest, Long accountId, UriInfo uriInfo) {
Renamed method.

2019-08-21 20:55 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    public Optional<TelephoneChargeResponse> findTelephoneCharge(TelephoneChargeCreateRequest telephoneChargeRequest, Long accountId, UriInfo uriInfo) {
Used for idempotency in ChargesApiResource.

2019-08-21 20:56 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            if (telephoneChargeRequest.getAmount() == 0L && !gatewayAccount.isAllowZeroAmount()) {
Refactored into checkIfZeroAmountAllowed method.

2019-08-22 08:43 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private Optional<ChargeEntity> createCharge(TelephoneChargeCreateRequest telephoneChargeRequest, Long accountId, UriInfo uriInfo) {
I've just realised - you are passing this uriInfo all the way down then not using it

2019-08-22 08:44 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        } else if (code.equals("P0010")) {
as Codacy says, the literal should come first in this. Admittedly in this case you have checked null first, but still good habit to get in to

2019-08-22 09:05 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        } else if (code.equals("P0010")) {
Done.

2019-08-22 09:05 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private Optional<ChargeEntity> createCharge(TelephoneChargeCreateRequest telephoneChargeRequest, Long accountId, UriInfo uriInfo) {
Removed unused parameters.

2019-08-22 09:17 UTC, mrlumbu submitted a review, later dismissed

2019-08-22 10:09 UTC, mrlumbu approved these changes

2019-08-22 10:11 UTC, merged