PP-5613 Enforce ExternalMetadata Validation when saving ChargeEntity
alphagov/pay-connector pull request #1680
Opened 2019-09-04 07:40 UTC by danworth

We evaluate the `@ValidExternalMetadata` when accepting a create charge
request via an end-point however this is not evaluated when attempting
to persist a `ChargeEntity`. This means it is possible to create an
invalid instance of `ExternalMetadata` within Connector and then persist
it to the charges table. This change adds the `@Valid` annotation to the
`externalMetadata` attribute of `ChargeEntity` so that any JPA actions
to update or persist the entity will evaluate the validation, rolling
back the transaction if it fails.

## Outstanding
@nimalank7 the telephone payment flow is saving `null` values in the following tests which doesn't pass the `@ValidExternalMetadata` validation. Is it possible for this flow to not add `null` values into the external metadata please? Happy to discuss if this causes a problem, just let me know.
```
ChargesApiTelephonePaymentResourceIT.createTelephoneChargeForFailedStatusP0010:129
ChargesApiTelephonePaymentResourceIT.createTelephoneChargeForFailedStatusP0050:166
ChargesApiTelephonePaymentResourceIT.createTelephoneChargeForOnlyRequiredFields:65
ChargesApiTelephonePaymentResourceIT.shouldReturnResponseForAlreadyExistingTelephoneCharge:192
```

2019-09-04 16:24 UTC, oswaldquek commented
How does an external service cause a ChargeEntity to be saved without going through the create charge API? If it goes through another endpoint, we'll need an integration test for that endpoint so a proper response with clear reason is returned to that service.

2019-09-04 16:24 UTC, oswaldquek requested changes
How does an external service cause a ChargeEntity to be saved without going through the create charge API? If it goes through another endpoint, we'll need an integration test for that endpoint so a proper response with clear reason is returned to that service.

2019-09-05 08:29 UTC, danworth commented
Thanks Oz, I should have added a bit more context to this, and probably best to chat. 

This came about because the in progress telephone payments that @nimalank7 is working on is re-using the `externalMetadata` field of `ChargeEntity` to store some data. It doesn't come into Connector as an `externalMetadata` field with the `@ValidExternalMetadata` annotation on it, rather elements of a `TelephoneChargeCreateRequest` are deconstructed into an `ExternalMetadata` object [here](https://github.com/alphagov/pay-connector/blob/5833cca87254064231844bb769dc12e3af13ffbb/src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java#L744). The problem came about when Dom noticed during some QA of telephone payments that the metadata wasn't being displayed correctly in SelfService which was because it had objects for values, which isn't permitted by the validation. This change is really to close this loop hole and something I should have added when we originally created the `ExternalMetadata` so that it is validated in both API and persistence so they can never become out of sync. 

It's a good point about needing integration tests for this scenario. Nim is aware of this change and has updated telephone payments to conform to the validated form of `ExternalMetadata` e.g. no longer using objects or `null` for values. The response will be a 422 via the `ConstraintViolationMapper` but @nimalank7 will need to add those tests as part of his telephone payment work and probably need to add validation to any element being deconstructed into the `ExternalMetadata` to make sure it can be. 

Lets have a chat with Nim.

2019-09-17 09:43 UTC, danworth commented
Hi @nimalank7 for the benefit of a reviewer of this PR can you please confirm that you've made the necessary changes with regard to Telephone payments so that we can progress this PR, e.g. you have added all necessary validation to the elements of a create telephone payment request that will be added to external metadata so the correct error is returned.

2019-09-17 10:00 UTC, nimalank7 commented
Yep @danworth  I've written validation to enforce this. See the following PR [https://github.com/alphagov/pay-connector/pull/1694]

2019-09-17 10:03 UTC, danworth commented
@oswaldquek could you please review again in light of Nim updating his work to make this a safe change.

2019-09-20 09:28 UTC, oswaldquek approved these changes

2019-09-20 12:29 UTC, merged