PP-561 Return Card Type In V2 Endpoint
alphagov/pay-connector pull request #1797
Opened 2019-10-07 14:03 UTC by RoryMalcolm

- Returns the `card_type` in the getCharges v2 endpoint

2019-10-07 14:27 UTC, danworth reviewed
Is there a test to go with this, how do you know this works?

2019-10-07 14:27 UTC, stephencdaly submitted a review, later dismissed
Can you update a test for this?

2019-10-09 09:32 UTC, danworth requested changes
Few little things to consider, could you also update `TransactionDaoIT` to confirm the read of the new value?

2019-10-09 09:32 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/model/domain/Transaction.java
> +    public String getCardType() {
Seems this is optional and later on you do a `!= null` so this might be better returning `Optional<String>`

2019-10-09 09:32 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/service/TransactionSearchStrategy.java
> +        if(transaction.getCardType() != null) {
If you make the return type for `getCardType` `Optional<String>` you can do something like:
`transaction.getCardType().map(CardType::valueOf).ifPresent(cardDetails::setCardType);`

2019-10-09 09:32 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            persistedCard.setCardType(chargeEntity.getCardDetails().getCardType());
I don't think is necessary. `.toCard();` sets the card type so it will already be set won't it? For what its worth I don't think it even needs the `setCardBrand` besides it defaults to `""` rather than `null` - might be worth looking into and cleaning up?

2019-10-09 09:32 UTC, danworth commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiV2ResourceIT.java
> +        addChargeAndCardDetails(nextLong(), CREATED, ServicePaymentReference.of("ref-1"), "ref", now(), "", "http://service.url/success-page/", "aaa@bbb.test", cardHolderName, "1234", "CREDIT");
These all use `CREDIT`, perhaps you could use a mix of values for a little greater coverage?

2019-10-09 12:46 UTC, danworth approved these changes
Looks good 👍

2019-10-09 12:47 UTC, merged