PP-5791 Update Worldpay 3DS Flex Creds Endpoint
alphagov/pay-connector pull request #1880
Opened 2019-11-04 17:05 UTC by RoryMalcolm

- When the new worldpay 3DS2 Flex credentials endpoint is posted, the
required credentials are stored in the database.

- If there is an error in the submitted json credentials, an error
matching the user's mistake is returned with the correct message and
status code

- Added tests to ensure that the functionality is correct.

2019-11-04 17:19 UTC, RoryMalcolm commented
🤔 I dunno if I want to rerun this again just to get Codacy to run, it broke because I force pushed loads

2019-11-04 18:57 UTC, alexbishop1 requested changes
Looks pretty good — some mostly smallish changes requested.

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/dao/GatewayAccount3ds2CredentialsDao.java
> +public class GatewayAccount3ds2CredentialsDao extends JpaDao<Worldpay3ds2CredentialsEntity> {
Could you name this `Worldpay3dsFlexCredentialsDao` please? There’s no point pretending it’s more generic than it actually is.

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3ds2CredentialsEntity.java
> +@Table(name = "worldpay_3ds_flex_credentials")
I think we want `@SequenceGenerator` as well.

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3ds2CredentialsEntity.java
> +public class Worldpay3ds2CredentialsEntity {
Can we name this class `Worldpay3dsFlexCredentialsEntity` to more closely match the name of the product?

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3ds2CredentialsEntity.java
> +    public Long gatewayAccountId;
`public`?

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3ds2CredentialsEntity.java
> +    public String issuer;
Could we use specific types for `issuer` (and `organisationalUnitId` and `jwtMacKey`)? We already have a `WrappedStringValue` abstract class so each specific type can be quite simple:

```java
public class Worldpay3dsFlexIssuer extends WrappedStringValue {

    public Worldpay3dsFlexIssuer valueOf(String value) {
        return new Worldpay3dsFlexIssuer(value);
    }
    
    private Worldpay3dsFlexIssuer(String value) {
        super(value);
    }

}
```

JPA will require a converter hooked up with a `@Convert(converter = Worldpay3dsFlexIssuerJpaConverter.class)` annotation (look at `SupportedLanguageJpaConverter` for inspiration).

This would be a fairly large change (in terms of lines affected) so I’m happy for this to be done in a subsequent PR.

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3ds2CredentialsEntity.java
> +    public Long version;
The `version` field needs an `@Version` annotation but we can avoid all that (and keep consistency with the rest of connector) by just having this class extend `AbstractVersionedEntity`.

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/WorldpayUpdate3ds2CredentialsRequest.java
> +public class WorldpayUpdate3ds2CredentialsRequest {
Again, please use `3dsFlex` rather than `3ds2`.

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/WorldpayUpdate3ds2CredentialsRequest.java
> +    @NotNull(message = "issuer cannot be null")
These error messages don’t seem to quite match what we have specified in the story.

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResource.java
> +public class GatewayAccount3ds2CredentialsResource {
`Worldpay3dsFlexCredentialsResource`

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResource.java
> +    private GatewayAccount3ds2CredentialsService gatewayAccount3ds2CredentialsService;
These can (and should) be `final`.

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResource.java
> +                .map((gatewayAccountEntity) -> {
There should be some check in here that we’re actually dealing with a Worldpay gateway account.

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResource.java
> +                .orElseGet(() -> notFoundResponse(format("The gateway account id '%s' does not exist", gatewayAccountId)));
Could you make this match the “Not a Worldpay gateway account” error specified in the story please?

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/GatewayAccount3ds2CredentialsService.java
> +public class GatewayAccount3ds2CredentialsService {
`Worldpay3dsFlexCredentialsService`

2019-11-04 18:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/GatewayAccount3ds2CredentialsService.java
> +                .withVersion(1L)
Don’t set the version explicitly; JPA will handle this for us.

2019-11-04 18:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResourceIT.java
> +public class GatewayAccount3ds2CredentialsResourceIT {
`Worldpay3dsFlexCredentialsResourceIT`

2019-11-04 18:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResourceIT.java
> +    public void setWorldpay3dsCredentials() {
This is testing setting for the first time, right? Maybe `setWorldpay3dsFlexCredentialsWhenThereAreNonExisting` or something?

2019-11-04 18:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResourceIT.java
> +                " \"jwt_mac_key\":\"hihihihihi\"}";
While we still don’t have [text blocks](https://openjdk.java.net/jeps/355), inline JSON strings are quite ugly. It can be clearer to JSONify a `Map`:

```java
String payload new ObjectMapper().writeValueAsString(Map.of(
        "issuer", "testissuer",
        "organisational_unit_id", "hihihi",
        "jwt_mac_key", "hihihihihi"
));
```

2019-11-04 18:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResourceIT.java
> +    }
Good that we have a test for updating them.

2019-11-04 18:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResourceIT.java
> +                .statusCode(422)
The story said 400 but since this is an internal API, 422 is fine if it’s easier. Please update the acceptance criteria if we’re going to stick with 422.

2019-11-04 18:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResourceIT.java
> +    }
Maybe have some where the value is explicitly set to `null` (rather than being missing) as well?

2019-11-04 18:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResourceIT.java
> +    public void incorrectAccountId() {
Something like `nonExistentGatewayAccountReturns404` would be a bit clearer.

2019-11-04 18:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3ds2CredentialsResourceIT.java
> +                .log().all()
Left in a `log()`!

2019-11-05 14:34 UTC, alexbishop1 requested changes
Looks nice.

Assuming the specific types will be added in a future PR, there’s just a few small things here then this is good to do.

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentialsEntity.java
> +        sequenceName = "charges_charge_id_seq", allocationSize = 1)
The `name` and `sequenceName` don’t look correct…

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentialsEntity.java
> +    private Long gatewayAccountId;
I don’t think we want to use the gateway account ID as the primary key and we certainly don’t want it to be generated from a sequence. Have a separate `Long` column with `@Id` that uses the sequence and have the column for the gateway account ID just be a regular column.

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentialsEntity.java
> +    public static final class Worldpay3ds2CredentialsEntityBuilder {
`Worldpay3dsFlexCredentialsEntityBuilder`

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentialsEntity.java
> +        private Long version;
Don’t need this field.

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentialsEntity.java
> +        public Worldpay3ds2CredentialsEntityBuilder withVersion(Long version) {
No need for a setter for the version because it will always be managed implicitly by JPA.

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3dsFlexCredentialsResource.java
> +    private final Worldpay3dsFlexCredentialsService worldpay3DsFlexCredentialsService;
`worldpay3dsFlexCredentialsService`

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3dsFlexCredentialsResource.java
> +                .map((gatewayAccountEntity) -> {
Don’t need this many brackets.

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3dsFlexCredentialsResource.java
> +                    if (gatewayAccountEntity.getGatewayName().equalsIgnoreCase("worldpay")) {
It would probably be neater to use a `filter(…)` before the `map(…)` rather than an `if` statement. Also, we can get the string `"worldpay"` from `PaymentGatewayName.WORLDPAY.getName()`.

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/Worldpay3dsFlexCredentialsService.java
> +    public void setGatewayAccountWorldpay3ds2Credentials(WorldpayUpdate3dsFlexCredentialsRequest worldpayUpdate3DsFlexCredentialsRequest, GatewayAccountEntity gatewayAccountEntity) {
`setGatewayAccountWorldpay3dsFlexCredentials` and `worldpayUpdate3dsFlexCredentialsRequest`

2019-11-05 14:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/Worldpay3dsFlexCredentialsService.java
> +            var storedEntity = aWorldpay3ds2CredentialsEntity()
I wouldn’t call this `storedEntity` given that it’s actually new (whereas the one above _is_ stored!).

2019-11-05 14:34 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3DsFlexCredentialsResourceIT.java
> +public class GatewayAccount3DsFlexCredentialsResourceIT {
`GatewayAccount3dsFlexCredentialsResourceIT`

2019-11-05 17:13 UTC, alexbishop1 requested changes
Looks good — just a few tiny things

2019-11-05 17:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/WorldpayUpdate3dsFlexCredentialsRequest.java
> +    private WorldpayUpdate3dsFlexCredentialsRequest(WorldpayUpdate3ds2CredentialsRequestBuilder builder) {
`3ds2`! 😱

(and the builder)

2019-11-05 17:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3dsFlexCredentialsResource.java
> +                        gatewayAccountEntity.getGatewayName().equalsIgnoreCase(PaymentGatewayName.WORLDPAY.getName()))
It’s a constant string, just `equals(…)` is enough

2019-11-05 17:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccount3dsFlexCredentialsResource.java
> +                    if (gatewayAccountEntity.getGatewayName().equalsIgnoreCase("worldpay")) {
You can remove the `if` statement now!

2019-11-05 17:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentialsEntity.java
> +            worldpay3DsFlexCredentialsEntity.issuer = this.issuer;
`3ds` (and lines above)

2019-11-05 17:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/Worldpay3dsFlexCredentialsService.java
> +    private Worldpay3dsFlexCredentialsDao worldpay3DsFlexCredentialsDao;
`3ds`

2019-11-05 17:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/Worldpay3dsFlexCredentialsService.java
> +    public Worldpay3dsFlexCredentialsService(Worldpay3dsFlexCredentialsDao worldpay3DsFlexCredentialsDao) {
`3ds`

2019-11-05 17:13 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/DatabaseTestHelper.java
> +    public Map<String, Object> getWorldpay3ds2Credentials(Long accountId) {
`3dsFlex`

2019-11-05 17:28 UTC, alexbishop1 approved these changes

2019-11-05 17:38 UTC, merged

2019-11-05 17:38 UTC, rorymalcolm commented
Thanks to @alexbishop1 for his patience!