PP-5709: add shopperIPAddress to authorisation request (Worldpay)
alphagov/pay-connector pull request #1887
Opened 2019-11-05 16:13 UTC by jankowiakmaria

Adding shopperIPAddress attribute to authorisation request can be
used by Worldpay for fraud checks.
It's an IP address which has been used by payer.
We want to add it in all cases (not only for 3ds payments).

Changes:
* update to AuthCardDetails to include ip address
* update to WorldpayAuthoriseOrderTemplate.xml to include additional
attribute and change to the condition for displaying session element
when it's 3ds payment or we have information about IP address
* update to logic in WorldpayPaymentProvider to include property determining
when session element should be added to the request
* update to tests

2019-11-05 16:33 UTC, alexbishop1 requested changes
Looks good but I have a suggestion that I think might make it a bit simpler and there’s also some changes to the tests I don’t quite follow.

2019-11-05 16:33 UTC, alexbishop1 commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +                />
It might be possible to do this without needing `includesSession` (at the cost of a little bit of verbosity) by doing something like this:

```xml
<#if authCardDetails.ipAddress.isPresent()> 
<session id="${sessionId?xml}" shopperIPAddress="${authCardDetails.ipAddress.get()}"/>
<#elseif requires3ds>
<session id="${sessionId?xml}"/>
</#if>
```

2019-11-05 16:33 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +                .thenReturn(gatewayResponse);
I don’t understand why this has changed.

2019-11-05 16:33 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> -        } catch (GatewayException.GatewayErrorException e) {
Why is the try/catch being removed?

2019-11-05 16:33 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> -    public void shouldNotIncludeElementsWhen3DSecureNotEnabled() throws Exception {
I think we still want this test (in a modified form) because 3DS authorisations include an extra `browser` element with `acceptHeader` and `userAgentHeader` child elements.

2019-11-05 17:08 UTC, jankowiakmaria commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +                />
I considered this option.
TBH I don't mind - I can change it to ^^ if it's preferred.

2019-11-05 17:20 UTC, jankowiakmaria commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> -    public void shouldNotIncludeElementsWhen3DSecureNotEnabled() throws Exception {
This is a duplicate of `shouldNotInclude3dsElementsWhen3dsToggleDisabled` test.
The difference is - this one checks whether specific elements DON'T exist (`session`, `acceptHeader` and `userAgentHeader`), and the other one check the exact value of the payload (which is https://github.com/alphagov/pay-connector/blob/master/src/test/resources/templates/worldpay/valid-authorise-worldpay-request-excluding-3ds.xml file).
When you compare it with https://github.com/alphagov/pay-connector/blob/master/src/test/resources/templates/worldpay/valid-authorise-worldpay-request-including-3ds.xml (which is used in `shouldInclude3dsElementsWhen3dsToggleEnabled` test), exactly the above properties are missing from `...excluding...` file.

That's the reason I removed it - it's a duplicate.

2019-11-05 17:35 UTC, jankowiakmaria commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +                .thenReturn(gatewayResponse);
So that it doesn't throw - It didn't seem like the intention of the test is to validate anything other than constructed order request.
Not mocking a gateway with a valid response but to throw an exception seems like a quicker (?) way. The intention is not to test anything along these lines, so I thought I'll clean it up - given I'm changing it anyway.
(that's the reason I removed try/catch as well).

2019-11-06 12:02 UTC, alexbishop1 commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +                />
Yes, I think I would prefer that because otherwise `includesSession` is set quite far away from where it’s used, which means one has to look in two places to figure out what’s going on (not to mention that it’s an extra variable and one that unfortunately has the ultra-generic word “session” in the name).

2019-11-06 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +                .thenReturn(gatewayResponse);
OK, thanks for explaining. I looked at the full test and what you say makes sense. I thought perhaps the exception was thrown in order to check `WorldpayPaymentProvider` handles it but it just gets propagated up anyway.

2019-11-06 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> -    public void shouldNotIncludeElementsWhen3DSecureNotEnabled() throws Exception {
Yes, you’re right. Makes sense.

2019-11-07 09:05 UTC, jankowiakmaria commented
I'm wondering whether we should sanitise the value of the ip address - in case the connector is provided with some sort of gibberish shouldn't we just not use it (worldpay may fail otherwise (?)), but not fail the request?
Thoughts?

2019-11-07 09:24 UTC, alexbishop1 commented
Yeah, interesting question.

We can probably assume that any time we’re getting the IP address directly from the connection it’s valid. But most of the time it will be coming from the `X-Forwarded-For` header. While we can probably assume an IP address added by our loadbalancers is legit, we have no control over anything else in the header (it’s essentially untrusted user input).

Validating the value could be tricky — IP addresses can be surprisingly complex, especially when IPv6 is involved. And we have no guarantee that whatever validation rules we use will match what Worldpay supports. As far as I’m aware,`X-Forwarded-For` is non-standard, so there’s no format specified.

We could try to see how Worldpay handles invalid input. Do an authorisation against a Worldpay test account with gibberish in the `shopperIPAddress` and see what happens (you can use `uk.gov.pay.connector.it.contract.WorldpayPaymentProviderTest` for this).

2019-11-07 09:27 UTC, alexbishop1 requested changes
This looks good but could you please squash the commits? It will confuse future code archaeologists if we add `includesSession` in one commit and then remove it in the next one!

2019-11-07 09:45 UTC, jankowiakmaria commented
Ready for merge (the potential validation/sanitisation would be done separately).

2019-11-07 09:50 UTC, alexbishop1 approved these changes

2019-11-07 10:23 UTC, merged