PP-5409 Makes Cancellation of charges consistent with expiry logic
alphagov/pay-connector pull request #1909
Opened 2019-11-13 15:57 UTC by nimalank7

## WHAT YOU DID
This PR modifies the doCancel method in ChargeCancelService to make it consistent with the logic used with expiring charges in ChargeExpiryService.

It does this by:
- Making the same set of states cancellable as those which are expirable using ExpirableChargeStatus
- Charges with an authorisation stage of DURING_AUTHORISATION are checked with the gateway whether they are cancellable

## How to test

See the new tests in ChargeCancelServiceTest

2019-11-13 16:50 UTC, oswaldquek requested changes

2019-11-13 16:50 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        WorldpayCancelResponse worldpayResponse = mock(WorldpayCancelResponse.class);
I'd rather use real classes over mocks where possible, because it's using the real thing which gives me more confidence. In this case it's not too hard to do `WorldpayCancelResponse worldpayResponse = new WorldpayCancelResponse()`

2019-11-13 16:50 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        verifyNoMoreInteractions(ignoreStubs(mockChargeDao));
what's the purpose for not verifying any interactions with `mockChargeDao`?

2019-11-13 16:50 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        verifyNoMoreInteractions(ignoreStubs(mockChargeDao));
what's the purpose for not verifying any interactions with mockChargeDao?

2019-11-13 16:50 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        verifyNoMoreInteractions(ignoreStubs(mockChargeDao));
what's the purpose for not verifying any interactions with mockChargeDao?

2019-11-13 16:50 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        verifyNoMoreInteractions(ignoreStubs(mockChargeDao));
what's the purpose for not verifying any interactions with mockChargeDao?

2019-11-13 16:50 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        WorldpayCancelResponse worldpayResponse = mock(WorldpayCancelResponse.class);
see previous comment on preferring using real classes

2019-11-13 16:51 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeCancelFrontendResourceIT.java
> -    public void respondWith400_whenCancellationDuringAuth3DSReady() {
was this test removed because a charge in AUTHORISATION_3DS_READY can be cancelled now?

2019-11-13 16:55 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        WorldpayCancelResponse worldpayResponse = mock(WorldpayCancelResponse.class);
We can't use a real object as there's no way to set the cancelStatus on it. It doesn't have a constructor with parameters or a setter because it is deserialised from XML.

2019-11-13 16:56 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        verifyNoMoreInteractions(ignoreStubs(mockChargeDao));
I think I probably added this because the other tests are doing it. We haven't added any additional stubs to this mock, so not sure why we'd need to do this. Reckon we should remove from all tests?

2019-11-13 16:57 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeCancelFrontendResourceIT.java
> -    public void respondWith400_whenCancellationDuringAuth3DSReady() {
Yep

2019-11-14 14:11 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        WorldpayCancelResponse worldpayResponse = mock(WorldpayCancelResponse.class);
The `WorldpayCancelResponse` class returns the cancel status so there's no need to set the cancel status on it. I've tried `WorldpayCancelResponse worldpayResponse = new WorldpayCancelResponse()` for myself and it works.

2019-11-14 14:11 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        verifyNoMoreInteractions(ignoreStubs(mockChargeDao));
yeah, let's remove this as it doesn't add anything to the tests; the tests still pass if the line is removed.

2019-11-14 14:27 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        WorldpayCancelResponse worldpayResponse = mock(WorldpayCancelResponse.class);
Oh yeh of course! 🤦‍♂

2019-11-14 14:27 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        verifyNoMoreInteractions(ignoreStubs(mockChargeDao));
👍

2019-11-14 14:33 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        WorldpayCancelResponse worldpayResponse = mock(WorldpayCancelResponse.class);
Done

2019-11-14 14:33 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeCancelServiceTest.java
> +        verifyNoMoreInteractions(ignoreStubs(mockChargeDao));
Done (for the modified tests)

2019-11-14 14:35 UTC, oswaldquek approved these changes

2019-11-14 14:39 UTC, merged