PP-6075 Allow creation of moto charges
alphagov/pay-connector pull request #2050
Opened 2020-01-28 16:19 UTC by stephencdaly

Accept a `moto` boolean field in a create charge request. If moto payments are enabled for the gateway account, create a charge and persist it with the moto flag set to true.

If moto payments are not enabled for the gateway account, return a 422 response with the `MOTO_NOT_ALLOWED` error_identifier.

Return the `moto` field in charge API responses.

2020-01-28 17:13 UTC, oswaldquek requested changes
Minor comment about a test name change.
There are quite a few lines that are refactoring/cleanup which should go into a different PR in the future. This will make reviewing easier.

2020-01-28 17:13 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/exception/MotoPaymentNotAllowedForGatewayAccountExceptionMapper.java
> +        return Response.status(422)
The acceptance criteria state 409 but I think 422 is correct here. Could you update the acceptance criteria in the story please?

2020-01-28 17:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +        assertThat(createdChargeEntity.isMoto(), is(false));
i would rename this test to `createChargeWithDefaults`

2020-01-29 10:01 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +        assertThat(createdChargeEntity.isMoto(), is(false));
👍 done

2020-01-29 10:01 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/charge/exception/MotoPaymentNotAllowedForGatewayAccountExceptionMapper.java
> +        return Response.status(422)
done

2020-01-29 13:42 UTC, oswaldquek approved these changes

2020-01-29 13:46 UTC, merged