PP-6201 - Force capture notificatiosn for expunged charges
alphagov/pay-connector pull request #2194
Opened 2020-03-10 12:06 UTC by nimalank7

Description:
- Corresponds to PP-6201-Add CAPTURE_NOTIFICATION_FOR_EXPUNGED_CHARGE event to Ledger
- Since the charge doesn't exist in the database (as it is expunged) when we process capture notification we send it directly to the Event SQS queue without persisting

2020-03-10 17:10 UTC, stephencdaly requested changes

2020-03-10 17:10 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +                if ("CAPTURED".equals(newChargeStatus.get().getValue())) {
Use the ChargeStatus enum value rather than a hardcoded string.

2020-03-10 17:10 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/processor/ChargeNotificationProcessor.java
> +                kv(PAYMENT_EXTERNAL_ID, charge.getExternalId()),
can use `ChargeEntity.getStructuredLoggingArgs` to save lines of code to log all these keys.

2020-03-10 17:10 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/processor/ChargeNotificationProcessor.java
> +        logger.info(String.format("Forcibly changing charge status for externalId [%s] [%s]->[%s]",
Could the log line better describe what's going on? We don't actually know whether we're forcing a status change, all we know is we've got a capture notification for a charge that's been expunged.
Something like:
"Received capture notification for charge that was already expunged from connector"

2020-03-10 17:10 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/processor/ChargeNotificationProcessor.java
> +    public void processForcedCaptureForExpungedCharge(GatewayAccountEntity gatewayAccount, String gatewayTransactionId, Charge charge, ChargeStatus newStatus, ZonedDateTime gatewayEventDate) {
could the method be renamed to `processCaptureNotificationForExpungedCharge`

2020-03-10 17:10 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/events/model/charge/ExpungedChargeStatusCorrectedToCapturedToMatchGatewayStatus.java
> +public class ExpungedChargeStatusCorrectedToCapturedToMatchGatewayStatus extends PaymentEventWithoutDetails {
Hmm do we actually know that we've corrected a status though? For all we know the charge is already in a captured state in ledger.
I think it should be something along the lines of "CaptureNotificationReceivedForExpungedCharge" unless someone else had something to say about this.

2020-03-10 17:10 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/events/EventService.java
> +    public void emitEvent(Event event) throws QueueException {
why do we need this new method?

2020-03-10 17:10 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    public void forceCaptureForExpungedCharge(Charge charge, GatewayAccountEntity gatewayAccountEntity, ChargeStatus targetChargeState, ZonedDateTime gatewayEventDate) {
I don't think we need a method in the ChargeService for this, could we just directly emit the event from the NotificationProcessor?

I also don't think we're handling the QueueException well here, I think we should just use the `emitAndRecordEvent` method. Is there a reason not to?

2020-03-10 17:14 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/events/model/charge/ExpungedChargeStatusCorrectedToCapturedToMatchGatewayStatus.java
> +public class ExpungedChargeStatusCorrectedToCapturedToMatchGatewayStatus extends PaymentEventWithoutDetails {
or CAPTURE_CONFIRMED_BY_GATEWAY_NOTIFICATION as Steven suggested on the other PR

2020-03-11 09:24 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    public void forceCaptureForExpungedCharge(Charge charge, GatewayAccountEntity gatewayAccountEntity, ChargeStatus targetChargeState, ZonedDateTime gatewayEventDate) {
emitAndRecordEvent persists the ChargeEventEntity into the database which I don't think we want to do as we only want to send a capture notification to Ledger.

2020-03-11 09:25 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/events/EventService.java
> +    public void emitEvent(Event event) throws QueueException {
The other methods persist the recorded event to the database which I don't think we want to do as the charge is historic.

2020-03-11 09:31 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +                if ("CAPTURED".equals(newChargeStatus.get().getValue())) {
Done

2020-03-11 09:32 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/processor/ChargeNotificationProcessor.java
> +    public void processForcedCaptureForExpungedCharge(GatewayAccountEntity gatewayAccount, String gatewayTransactionId, Charge charge, ChargeStatus newStatus, ZonedDateTime gatewayEventDate) {
Done

2020-03-11 10:39 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/events/model/charge/ExpungedChargeStatusCorrectedToCapturedToMatchGatewayStatus.java
> +public class ExpungedChargeStatusCorrectedToCapturedToMatchGatewayStatus extends PaymentEventWithoutDetails {
or CaptureNOtificationForExpungedCharge as per the story in Jira.

2020-03-11 10:50 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/events/EventService.java
> +    public void emitEvent(Event event) throws QueueException {
If the event was successfully put on the Queue we don't want to record it; however if it was not successful we want to to record it so it will be picked up to be processed again. So I think the code here should look like 
```
    public void emitEvent(Event event, ZonedDateTime doNotRetryEmitUntilDate) {
        try {
            eventQueue.emitEvent(event);
        } catch (QueueException e) {
            emittedEventDao.recordEmission(event.getResourceType(), event.getResourceExternalId(),
                    event.getEventType(), event.getTimestamp(), doNotRetryEmitUntilDate);
            logger.error("Failed to emit event {} due to {} [externalId={}]",
                    event.getEventType(), e.getMessage(), event.getResourceExternalId());
        }
    }
```

2020-03-11 11:04 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    public void forceCaptureForExpungedCharge(Charge charge, GatewayAccountEntity gatewayAccountEntity, ChargeStatus targetChargeState, ZonedDateTime gatewayEventDate) {
yeah I think we can just call `EventService.emitEvent` after this line https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java#L121.
adding this  `forceCaptureForExpungedCharge` method seems excessive.

2020-03-11 11:23 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/events/EventService.java
> +    public void emitEvent(Event event) throws QueueException {
so after speaking to Steven F, the original 
```
public void emitEvent(Event event) throws QueueException {
  eventQueue.emitEvent(event);
}
```
looks fine. In theory if we return a 500 in response to `/v1/api/notifications/epdq` epdq should retry the notification. I will check with them.

2020-03-13 14:37 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/processor/ChargeNotificationProcessor.java
> +                kv(PAYMENT_EXTERNAL_ID, charge.getExternalId()),
Sure but I'd have to recreate the ChargeEntity from the Charge object to do that which would generate more lines of code to do that.

2020-03-13 14:41 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/processor/ChargeNotificationProcessor.java
> +        logger.info(String.format("Forcibly changing charge status for externalId [%s] [%s]->[%s]",
Done

2020-03-13 14:42 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/events/model/charge/ExpungedChargeStatusCorrectedToCapturedToMatchGatewayStatus.java
> +public class ExpungedChargeStatusCorrectedToCapturedToMatchGatewayStatus extends PaymentEventWithoutDetails {
I've changed it to CAPTURE_CONFIRMED_BY_GATEWAY_NOTIFICATION

2020-03-13 14:42 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/events/EventService.java
> +    public void emitEvent(Event event) throws QueueException {
I've kept it to merely emitEvent as above

2020-03-16 10:17 UTC, oswaldquek approved these changes

2020-03-16 10:21 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/processor/ChargeNotificationProcessor.java
> +                kv(PAYMENT_EXTERNAL_ID, charge.getExternalId()),
oh yeh my bad

2020-03-16 10:24 UTC, stephencdaly approved these changes
Just a comment about adding a comment

2020-03-16 10:24 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/events/EventService.java
> +    public void emitEvent(Event event) {
Could it be worth adding a comment here about what situation this method should be called in as opposed to `emitAndRecord` event - i.e. when the charge has already been expunged? It might save someone doing something wrong in the future.

2020-03-16 10:26 UTC, merged

2020-03-16 10:26 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/processor/ChargeNotificationProcessor.java
> +        logger.info(format("Force state transition from [%s] to [%s]", charge.getStatus(),  newStatus.getValue()),
probably don't need this additional comment here, we're already logging a comment above that gives us the information we need

2020-03-16 10:28 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +                if (CAPTURED.getValue().equals(newChargeStatus.get().getValue())) {
don't need the `.getValue` in both cases, can just be 
```if (CAPTURED.equals(newChargeStatus.get())) {```

2020-03-16 10:29 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
>          if (newChargeStatus.isPresent()) {
I think we generally prefer to use 
```.ifPresentOrElse(status -> {```

to avoid having to call `.get` on the Optional, as it's the more modern java-y way to do it.

2020-03-16 10:34 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/events/EventService.java
> +    public void emitEvent(Event event) {
I'll do this. I also want to write a comment on why we catch the QueueException and don't do anything further. I did think about this but didn't want to delay the PR any further as it's been open for a while.