PP-6362: Add color depth
alphagov/pay-connector pull request #2285
Opened 2020-04-23 15:47 UTC by oswaldquek

Add color depth to AuthCardDetails and EpdqPayloadDefinitionForNewOrder.

2020-04-23 17:31 UTC, alexbishop1 requested changes
I would have preferred it if the refactoring and the new functionality were in two separate pull requests: I found it quite taxing to follow.

It doesn’t look like there’s anything in here to ensure that the `browserColorDepth` we send to ePDQ is one of the ones they support (1, 2, 4, 8, 15, 16, 24 or 32) nor to ensure that we always send a value for every 3DS2 payment (defaulting to 24 if frontend either didn’t send a value at all or sent an invalid one).

2020-04-23 17:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +            authCardDetails.setJsScreenColorDepth(null);
I’m not sure mutating the request is the right thing to do here. I think we want to go down the path of only adding a value to the request to ePDQ if all the necessary conditions are met.

2020-04-23 17:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNewOrder.java
> +        }
This can be written as:

```java
templateData.getAuthCardDetails().getJsScreenColorDepth()
    .ifPresent(bcp -> parameterBuilder.add(BROWSER_COLOR_DEPTH, bcp));
```

However, I don’t think this is actually the right class. `EpdqPayloadDefinitionForNewOrder` is only used for non-3DS payments. For 3DS ones, we have `EpdqPayloadDefinitionForNew3dsOrder`, which extends this one. The decision of which one to use is made at the beginning of `buildAuthoriseOrder(…)` in `EpdqPaymentProvider`.

Since the data ePDQ require for a 3DS1 payment is a superset of the data required for a non-3DS payment, and the data ePDQ require for a 3DS2 payment is a superset of the data required for a 3DS1 payment, we could add another variant, `EpdqPayloadDefinitionForNew3ds2Order`, extending the existing `EpdqPayloadDefinitionForNew3dsOrder`.

This would mean that `buildAuthoriseOrder(…)` in `EpdqPaymentProvider` could decide, essentially, which parameters we’re going to send (based on the payment being non-3DS, 3DS1 or 3DS2) and `EpdqPayloadDefinitionForNew3ds2Order` could encapsulate the logic to always supply valid data (e.g checking the provided colour depth is valid according to ePDQ and putting in the default in if not).

2020-04-23 17:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForNewOrderTest.java
> +    }
Not sure these two tests are really testing the right thing. Ultimately, whether we send the `browserColorDepth` parameter is controlled by whether 3DS2 is enabled on the gateway account, not the content of the request from frontend.

We either need some logic earlier on to decide whether to populate the `browserColorDepth` in `epdqTemplateData` based on whether 3DS2 is enabled, or we need to always populate the `browserColorDepth` in `epdqTemplateData` and decide when we build the request to ePDQ whether to send it or not (which I think is more consistent with what we do elsewhere and therefore my preference).

2020-04-23 17:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProviderTest.java
> +    }
How is this actually testing the `browserColorDepth` parameter isn’t sent?

2020-04-24 09:01 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNewOrder.java
> +        }
I'm not sure how I followed through to the wrong class. This is probably as a result of how confusing the code is. I might have a think about refactoring the `buildAuthoriseOrder(…)` first. 👍 for introducing a `EpdqPayloadDefinitionForNew3ds2Order`, I will definitely do that.

2020-04-24 09:02 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForNewOrderTest.java
> +    }
I was trying to munge 3DS1 and 3DS2 code together here, which was why I made a test to ensure the `browserColorDepth` isn't sent if it isn't provided. However with the new `EpdqPayloadDefinitionForNew3ds2Order` class this will go away.

2020-04-24 09:04 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProviderTest.java
> +    }
Ah, because the `successAuthRequest` contains a sha sign calculated from all the params in the `AuthCardDetails`. The test will fail if the screen color depth is included in the caluclation. This was definitely not clear in the test and is worth a comment.

2020-04-24 09:07 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +            authCardDetails.setJsScreenColorDepth(null);
I'm generally for immutability but Java doesn't do this well and our code doesn't do this either with the getter and setter methods. I did this mutation because the screen color depth could (but very unlikely of course) be included in a non-3DS2 auth request, and the result would be the inclusion of it in the sha sign calculation.
I don't like this coupling though, and will think about how to make it better.

2020-04-24 09:08 UTC, oswaldquek commented
Thanks for the review. Yes, I made the carnal mistake of refactoring and coding new functionality in the same PR, something I find annoying in other PRs!
I also made some code mistakes here, partly because the epdq code is really confusing, so I think the best thing is to close this PR and make a new one.

2020-04-24 09:08 UTC, closed without merging

2020-04-24 09:15 UTC, oswaldquek commented
I also found it difficult where to start with this story. Originally I did an integration test but realised it would touch to many pieces of code and decided `EpdqPayloadDefinitionForNewOrder` (or `EpdqPayloadDefinitionForNew3ds2Order` in the up-and-coming PR) is the best place to start.