PP-6362: Delete EpdqOrderRequestBuilder
alphagov/pay-connector pull request #2289
Opened 2020-04-27 10:29 UTC by oswaldquek

EpdqOrderRequestBuilder was a class that had lots of indirection which it made
it difficult to figure out how a GatewayOrder was being built from the
operations (e.g. capture, authorise, cancel etc). This commit simplifies this
indirection by

- instantiating concrete subclasses of `EpdqPayloadDefinition`
- moving the building of the GatewayOrder into
  `EpdqPayloadDefinition.createGatewayOrder`
- removing inappropriate uses of inheritance and interfaces where possible

2020-04-27 10:46 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionMaintenanceOrderTest.java
> +    public void testOnlyTransactionIdIsSentIfBothTransactionIdAndOrderIdAvailable() {
this test was directly copied from https://github.com/alphagov/pay-connector/blob/master/src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForMaintenanceOrderTest.java#L59. i think the test name is inaccurate as the `extractPairs` variable in the test will have both the transaction id and order id populated.

2020-04-27 10:47 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionMaintenanceOrderTest.java
> +    public void testThatOrderIdIsSentIfTransactionIsNotAvailable() {
copied from https://github.com/alphagov/pay-connector/blob/master/src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForMaintenanceOrderTest.java#L70

2020-04-27 19:14 UTC, alexbishop1 requested changes
This is a really good improvement.

I would have preferred it to be delivered a bit more incrementally but I recognise that would be hard. Perhaps some of the changes like coalescing `EpdqSignedPayloadDefinition` and `FormUrlEncodedStringBuilder` into `EpdqPayloadDefinition` could have been done separately.

I like how a lot of the tests still assert the results by comparing to data loaded from (unchanged!) files. That gives me confidence that the behaviour is the same.

I’ve left some comments. Since this PR is already quite big, I’ve prefixed anything that can probably wait until a subsequent PR with “Perhaps not for now”. Anything that should definitely wait until a subsequent PR has been prefixed with “Not for now”.

One thing I’m less sure about is how the subclasses of `EpdqPayloadDefinition` now have `extract(…)` methods and an inherited `createGatewayOrder(…)` method that seem to operate at different levels. This is particularly noticeable in the tests. I think we should try to smooth that out in the future.

Not for now (obviously) but I think we can go even further than this and remove more intermediary classes like `EpdqTemplateData`. But what we have now, particularly the break-up of `EpdqOrderRequestBuilder`, is a great step forward in improving comprehensibility.

2020-04-27 19:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqCaptureHandler.java
> +        return new EpdqPayloadDefinitionForCaptureOrder().createGatewayOrder(templateData);
Perhaps not for now but it doesn’t look like `EpdqPayloadDefinitionForCaptureOrder` and friends actually hold any state. Could it be a singleton?

2020-04-27 19:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
>      private GatewayOrder buildQueryOrderRequestFor(ChargeEntity charge) {
Not for now, but this method appears to be identical to the one above except for how it obtains the charge ID.

2020-04-27 19:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinition.java
> +    private static final SignatureGenerator signatureGenerator = new EpdqSha512SignatureGenerator();
This constant name should be in `SCREAMING_SNAKE_CASE`.

2020-04-27 19:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinition.java
> +    private static final Charset EPDQ_APPLICATION_X_WWW_FORM_URLENCODED_CHARSET = Charset.forName("windows-1252");
This constant is now here and in `EpdqPaymentProvider` — I think it should only be in the latter.

2020-04-27 19:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinition.java
> +        templateData.setOperationType(getOperationType());
Not for now, but I think every concrete subclass of `EpdqPayloadDefinition` probably knows enough to add its own operation type as a constant rather than it being added to the data passed to it here.

2020-04-27 19:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinition.java
> +        requestParams.add(new BasicNameValuePair("SHASIGN", signatureGenerator.sign(templateParams, templateData.getShaInPassphrase())));
I found the `templateParams` and `requestParams` variable names a little non-obvious here. Maybe we could avoid needing both by restructuring the code a little:

```java
var params = new ArrayList<NameValuePair> = extract(templateData);
String signature = signatureGenerator.sign(params, templateData.getShaInPassphrase());
params.add(new BasicNameValuePair("SHASIGN", signature));
```

2020-04-27 19:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/ParameterBuilder.java
> +public class ParameterBuilder {
Could we call this `EpdqParameterBuilder`? The current name is a bit too generic.

2020-04-27 19:14 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForCancelOrderTest.java
> +    public void assertGatewayOrder() {
I think this test name (and the ones with the same name in other test classes) could be more descriptive.

2020-04-27 19:14 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForMaintenanceOrderTest.java
> -public class EpdqPayloadDefinitionForMaintenanceOrderTest {
If these test class were still here, would these tests still pass? It may well be that these tests are unnecessary but I’d feel more confident if we left them in place and saw them still pass after this refactoring. We can look at removing them later.

2020-04-27 19:14 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/templates/FormUrlEncodedStringBuilderTest.java
> -public class FormUrlEncodedStringBuilderTest {
This test is doing some interesting checks relating to encoding that I don’t think we want to lose, to the point where I’m pondering if merging `FormUrlEncodedStringBuilder` into `EpdqPaymentDefintion` is necessarily the right decision. Perhaps we could modify some of the new `assertGatewayOrder()` tests so they have data that covers the cases here.

2020-04-27 20:54 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinition.java
> +    private static final Charset EPDQ_APPLICATION_X_WWW_FORM_URLENCODED_CHARSET = Charset.forName("windows-1252");
Oh I forgot to delete it from `EpdqPaymentProvider`. Why should it in `EpdqPaymentProvider`? It's only needed when building the payload which happens in `EpdqPayloadDefinition`.

2020-04-27 21:21 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForMaintenanceOrderTest.java
> -public class EpdqPayloadDefinitionForMaintenanceOrderTest {
The tests here haven't been deleted. `testBaseValuePairs` and `testBaseValuePairsWithAmount` have been merged into `EpdqPayloadDefinitionMaintenanceOrderTest.shouldExtractParametersFromTemplate`. 
`testOnlyTransactionIdIsSentIfBothTransactionIdAndOrderIdAvailable` and `testThatOrderIdIsSentIfTransactionIsNotAvailable` have also been moved to `EpdqPayloadDefinitionMaintenanceOrderTest`.

2020-04-27 21:27 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/templates/FormUrlEncodedStringBuilderTest.java
> -public class FormUrlEncodedStringBuilderTest {
The reason why I didn't think these were necessary is because in the `assertGatewayOrder()` tests the following is tested:
```
assertEquals(TestTemplateResourceLoader.load(EPDQ_AUTHORISATION_3DS_REQUEST), gatewayOrder.getPayload());
```
This loads a file (https://github.com/alphagov/pay-connector/blob/master/src/test/resources/templates/epdq/authorisation-3ds-request.txt in this case) which essentially covers our bases here.

2020-04-27 21:27 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForCancelOrderTest.java
> +    public void assertGatewayOrder() {
changed to `assert_payload_and_order_request_type_are_as_expected`

2020-04-28 08:53 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForMaintenanceOrderTest.java
> -public class EpdqPayloadDefinitionForMaintenanceOrderTest {
I probably should have kept the name of the test to `EpdqPayloadDefinitionForMaintenanceOrderTest`. I'll make the change.

2020-04-28 08:54 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinition.java
> +        templateData.setOperationType(getOperationType());
👍 I'll do in the next PR.

2020-04-28 08:56 UTC, oswaldquek commented
Thanks for the review @alexbishop1. I'll make the "Not for now" and "Perhaps not for now" changes in the next PR.

2020-04-28 09:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinition.java
> +    private static final Charset EPDQ_APPLICATION_X_WWW_FORM_URLENCODED_CHARSET = Charset.forName("windows-1252");
Ah, yes, in that case it should only be in `EpdqPayloadDefinition`.

2020-04-28 09:13 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForMaintenanceOrderTest.java
> -public class EpdqPayloadDefinitionForMaintenanceOrderTest {
I see. I thought we’d lost some of the tests.

And how we ended up with  both `EpdqPayloadDefinitionMaintenanceOrderTest` and `EpdqPayloadDefinitionForMaintenanceOrderTest` makes the mind boggle somewhat!

2020-04-28 09:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/templates/FormUrlEncodedStringBuilderTest.java
> -public class FormUrlEncodedStringBuilderTest {
It covers things like encoding spaces but not some of the obscure cases like encoding characters that encode differently in Windows-1252 to UTF-8 (like é).

2020-04-28 09:21 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/templates/FormUrlEncodedStringBuilderTest.java
> -public class FormUrlEncodedStringBuilderTest {
Yeah but `FormUrlEncodedStringBuilder` was really just encapsulating `org.apache.http.client.utils.URLEncodedUtils.format` so it wasn't doing anything special. Do we really need to test library code?
I'll add it back in if you insist though.

2020-04-28 09:26 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/templates/FormUrlEncodedStringBuilderTest.java
> -public class FormUrlEncodedStringBuilderTest {
Nah, you’re good. I’ve just been burned by the earlier times when we got the character encoding wrong!

2020-04-28 09:30 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPayloadDefinitionForMaintenanceOrderTest.java
> -public class EpdqPayloadDefinitionForMaintenanceOrderTest {
there's only `EpdqPayloadDefinitionForMaintenanceOrderTest` now :)

2020-04-28 10:49 UTC, alexbishop1 approved these changes
Good stuff!

2020-04-28 10:50 UTC, merged