PP-6362: Send browser language to connector
alphagov/pay-connector pull request #2290
Opened 2020-04-27 15:32 UTC by oswaldquek

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2020-04-27 16:32 UTC, oswaldquek commented
Probably best to wait for https://github.com/alphagov/pay-connector/pull/2289 to be merged.

2020-04-28 13:13 UTC, alexbishop1 requested changes
Couple of minor qualms but this looks fine. Happy for it to go in now without the code to default to the right language since none of this will actually be used yet.

2020-04-28 13:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/model/AuthCardDetails.java
> +    public String getJsNavigatorLanguage() {
Since this could be null, we should return an `Optional<String>` here

2020-04-28 13:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqParameterBuilder.java
> +        parameters.removeIf(x -> x.getName().equals(name));
Maybe `existingParameter` rather than just `x`.

If we’re having to do this, I wonder if making this a map rather than a list would be more appropriate.

2020-04-28 13:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        if (isNotBlank(templateData.getAuthCardDetails().getJsNavigatorLanguage())) {
I think we should have a null check here but I don’t think we need a blank string check. `Locale.forLanguageTag("").toLanguageTag()` or `Locale.forLanguageTag(" ").toLanguageTag()` or similar will return `"und"` (undefined), which is a legitimate language tag. I don’t think we need to worry too much about the edge case of browsers sending something that isn’t a valid language tag (however, we do need to deal with JavaScript not being enabled and do the null check).

Plus, if we do a null check rather than a blank string check, we can have cool code like this:

```java
String language = Optional.ofNullable(templateData.getAuthCardDetails().getJsNavigatorLanguage())
    .map(Locale::forLanguageTag).map(Locale::toLanguageTag).orElse("en-GB");
```

2020-04-28 13:54 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/model/AuthCardDetails.java
> +    public String getJsNavigatorLanguage() {
I know but I want to use `Optional<String>` when a test calls for it. Maybe I should include the `public void should_include_default_browserLanguage` test in this PR too then.

2020-04-28 13:57 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqParameterBuilder.java
> +        parameters.removeIf(x -> x.getName().equals(name));
I think I will revert this code as it strictly test code used in `EpdqPayloadDefinitionForNew3ds2OrderTest.should_include_browserColorDepth` and is not production code.

2020-04-28 14:02 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/model/AuthCardDetails.java
> +    public String getJsNavigatorLanguage() {
Actually I will hold off on this for now. The reason I want to have the `should_include_default_browserLanguage` test in another PR is because the `browserLanguage` default depends on whether the card payment is in english or welsh which adds more extra code and is deserving of its own PR.

2020-04-28 14:03 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/model/AuthCardDetails.java
> +    public String getJsNavigatorLanguage() {
So the `Optional<String>` will go into the next PR.

2020-04-28 15:10 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        if (isNotBlank(templateData.getAuthCardDetails().getJsNavigatorLanguage())) {
i've amended to 
```
Optional.ofNullable(templateData.getAuthCardDetails().getJsNavigatorLanguage())
                .map(Locale::forLanguageTag).map(Locale::toLanguageTag).ifPresent(lang -> parameterBuilder.add(BROWSER_LANGUAGE, lang));
``` 
for now. 
Default values will be dealt with in the next PR.

2020-04-28 15:32 UTC, alexbishop1 requested changes
Looks good.

Could you squash the two commits together just so we don’t have code that’s added in one commit and then removed in the next?

2020-04-28 15:35 UTC, oswaldquek commented
@alexbishop1 done

2020-04-28 15:36 UTC, alexbishop1 approved these changes

2020-04-28 15:47 UTC, merged