PP-6362 - Add timezone offset to ePDQ 3DS2 parameters
alphagov/pay-connector pull request #2303
Opened 2020-05-01 10:39 UTC by nimalank7

Description:
- This adds jsTimezoneOffsetMins to ePDQ 3DS2 parameters

2020-05-01 11:48 UTC, alexbishop1 requested changes
Looking good overall. A few things…

2020-05-01 11:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    public final static String DEFAULT_BROWSER_TIMEZONE_OFFSET_MINS = EpdqPayloadDefinitionForNew3ds2Order.getCurrentOffsetInMinutes();
We shouldn’t store this in a constant because it will only be evaluated when the class loads for the first time after the application starts and the current UK time zone offset could change before the next restart. We should instead calculate this every time.

2020-05-01 11:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    private final static Pattern NUMBER_FROM_MINUS_840_TO_720 = Pattern.compile("-?[0-9]{1,3}");
The name isn’t quite right here because this allows anything from -999 to 999. Also, it will allow strange things like -0 or 012 (which would get parsed as octal). I think `-[1-9][0-9]{0,2}|0|[1-9][0-9]{0,2}` would work better.

2020-05-01 11:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        ZoneOffset currentUKOffset = ZoneId.of("Europe/London").getRules().getOffset(now);
Usually if there’s an initialism (like UK) in a camel case identifier, it’s treated as if it were a word: `currentUkOffset`.

2020-05-01 11:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        Integer currentUKOffsetInMins = currentUKOffset.getTotalSeconds()/-60;
The negative sign is a bit of a surprising head-scratcher here because JavaScript has this weird behaviour where ahead of UTC is a negative offset (I don’t know why: I found https://stackoverflow.com/questions/21102435/why-does-javascript-date-gettimezoneoffset-consider-0500-as-a-positive-off but I’m not sure it really clears it up). I’d be really tempted to make it a bit more verbose and name the variables to try to give the hapless reader a clue as to what’s going on:

```java
ZoneOffset currentUkOffset = ZoneId.of("Europe/London").getRules().getOffset(Instant.now());
int currentUkOffsetMinsInJavaFormatWithAheadOfUtcPositive = currentUkOffset.getTotalSeconds() / 60;
int currentUkOffsetMinsInJavaScriptFormatWithAheadOfUtcNegative = -currentUkOffsetMinsInJavaFormatWithAheadOfUtcPositive;
return String.valueOf(currentUkOffsetMinsInJavaScriptFormatWithAheadOfUtcNegative);
```

2020-05-01 11:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        return currentUKOffsetInMins.toString();
There’s no need to box the `int` into an `Integer` just to be able to `toString()` it. This would be equivalent:

```java
int currentUKOffsetInMins = currentUKOffset.getTotalSeconds()/-60;
return String.valueOf(currentUKOffsetInMins);
```

2020-05-01 11:48 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        assertThat(result, is(aParameterBuilder().build()));
Maybe I’m missing something here but I don’t see how this is checking the default offset is added.

2020-05-01 11:57 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    private final static Pattern NUMBER_FROM_MINUS_840_TO_720 = Pattern.compile("-?[0-9]{1,3}");
I agree with re-naming it. Is it necessarily bad to not allow -0 or 012 - we could just parse them as 0 and 12?

2020-05-01 12:05 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    public final static String DEFAULT_BROWSER_TIMEZONE_OFFSET_MINS = EpdqPayloadDefinitionForNew3ds2Order.getCurrentOffsetInMinutes();
Ah sorry yes! I've fixed that now.

2020-05-01 12:05 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        ZoneOffset currentUKOffset = ZoneId.of("Europe/London").getRules().getOffset(now);
Done

2020-05-01 12:05 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        assertThat(result, is(aParameterBuilder().build()));
Fixed when we build the parameter class the default offset is added.

2020-05-01 12:11 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        Integer currentUKOffsetInMins = currentUKOffset.getTotalSeconds()/-60;
Yep

2020-05-01 12:11 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        return currentUKOffsetInMins.toString();
Done

2020-05-01 13:17 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    private final static Pattern NUMBER_FROM_MINUS_840_TO_720 = Pattern.compile("-?[0-9]{1,3}");
I thought `Integer.parseInt(…)` did things like treated leading zeros as octal but I’ve [just checked and apparently it doesn’t do that](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Integer.html#parseInt(java.lang.String)). So maybe it wouldn’t be too bad. I do like the appeal of having a regex that tightly constrains what we accept though. Leaves fewer possible surprises in the future.

2020-05-01 13:52 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    private final static Pattern NUMBER_FROM_MINUS_840_TO_720 = Pattern.compile("-?[0-9]{1,3}");
Yep - the regex has been changed accordingly

2020-05-01 14:18 UTC, alexbishop1 requested changes
A couple of small things and an idea that should make this easier to test.

2020-05-01 14:18 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    private final static Pattern NUMBER_FROM_MINUS_840_TO_720 = Pattern.compile("-[1-9][0-9]{0,2}|0|[1-9][0-9]{0,2}");
This should really be `NUMBER_FROM_MINUS_999_TO_999` to avoid confusion.

2020-05-01 14:18 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +                .orElse(getCurrentBrowserOffsetInMinutes());
This should be `.orElseGet(this::getDefaultBrowserLanguage)` or the default will be calculated every time even if it’s not needed.

2020-05-01 14:18 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        assertThat(result, is(aParameterBuilder().build()));
Oh, I see now.

Ideally, we shouldn’t be relying on the current time in tests because it makes each run slightly different. In reality, we do that a lot. However, in this case we have the added twist that when this test runs in winter we’ll be testing the default winter offset (but not the summer one) and when it runs in summer we’ll be testing the default summer offset (but not the winter one).

There is a solution to this: it’s to use a [`Clock`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Clock.html). We can make `EpdqPayloadDefinitionForNew3ds2Order` take a `Clock` as a constructor parameter and call `clock.instant()` whenever it wants the current time.

In the real code to instantiate the `EpdqPayloadDefinitionForNew3ds2Order` object (which I believe hasn’t been written yet), we can pass in `Clock.systemUTC()`, which provides the real time. In the tests, we can pass in `Clock.fixed(…)` set to whatever non-changing time we like. This would allow us to have two variants of this test: one where it’s winter time and where it’s summer.

I don’t think we use `Clock`s for testing in this way yet but I think the unique daylight saving time differences here make it worth introducing.

2020-05-01 14:18 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    private final static Pattern NUMBER_FROM_MINUS_840_TO_720 = Pattern.compile("-[1-9][0-9]{0,2}|0|[1-9][0-9]{0,2}");
This should be `NUMBER_FROM_MINUS_999_TO_999`.

2020-05-01 16:25 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    private final static Pattern NUMBER_FROM_MINUS_840_TO_720 = Pattern.compile("-[1-9][0-9]{0,2}|0|[1-9][0-9]{0,2}");
Done

2020-05-01 16:26 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +                .orElse(getCurrentBrowserOffsetInMinutes());
Done

2020-05-04 08:47 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        assertThat(result, is(aParameterBuilder().build()));
Done

2020-05-04 09:55 UTC, alexbishop1 requested changes
Thanks for introducing the `Clock`. Just a couple of things.

2020-05-04 09:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    private String getCurrentBrowserOffsetInMinutes() {
This should have “default” somewhere in the name e.g. `getDefaultBrowserTimezoneOffsetInMinutes()`

2020-05-04 09:55 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +    private static final Clock britishSummerTimeClock = Clock.fixed(ZonedDateTime.parse("2020-05-06T10:10:10.100Z").toInstant(), ZoneId.of("Europe/London"));
Since this is a constant, we want `BRITISH_SUMMER_TIME_CLOCK` or similar.

We don’t actually need to use a `ZonedDateTime` here: `Instant` also has a `parse(…)` method so `Instant.parse("2020-05-06T10:10:10.100Z")` will have the same effect as `ZonedDateTime.parse("2020-05-06T10:10:10.100Z").toInstant()`.

Also, the time zone of the `Clock` probably shouldn’t be Europe/London. A bit confusing, I know, but connector always runs in UTC time, so the time zone of the real clock will be UTC. It doesn’t really matter though because `clock.instant()` returns an `Instant`, which is independent of time zones. Then we’ll use this instant to figure out what the current offset is for Europe/London. Confusing? Yes. Long and short of it is we should probably use `ZoneOffset.UTC` here.

Come to think of it, maybe the name should be `CLOCK_WITH_TIME_WHERE_UK_IS_IN_BST` or something.

2020-05-04 09:55 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        Clock gmtClock = Clock.fixed(ZonedDateTime.parse("2020-01-01T10:10:10.100Z").toInstant(), ZoneId.of("Europe/London"));
This clock should be a constant like the other one (or the other one should be a local variable; I don’t mind as long as it’s consistent).

2020-05-04 09:55 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        private String browserTimezoneOffsetMins = "-60";
It’s a bit confusing to have this as a default: `should_include_default_browserTimezoneOffsetMins_for_summer_time_when_timezone_offset_provided_is_invalid` should probably behave more similarly to `should_include_default_browserTimezoneOffsetMins_for_Gmt_when_timezone_offset_provided_is_invalid` where the default time zone offset to expect is explicitly specified in the test.

2020-05-04 10:24 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        private String browserTimezoneOffsetMins = "-60";
Done

2020-05-04 10:24 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        Clock gmtClock = Clock.fixed(ZonedDateTime.parse("2020-01-01T10:10:10.100Z").toInstant(), ZoneId.of("Europe/London"));
Done

2020-05-04 10:24 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +    private static final Clock britishSummerTimeClock = Clock.fixed(ZonedDateTime.parse("2020-05-06T10:10:10.100Z").toInstant(), ZoneId.of("Europe/London"));
Done

2020-05-04 10:24 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    private String getCurrentBrowserOffsetInMinutes() {
Done

2020-05-04 11:02 UTC, alexbishop1 requested changes
Looks good: just one small thing.

2020-05-04 11:02 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +    public void should_include_default_browserTimezoneOffsetMins_for_summer_time_when_timezone_offset_provided_is_invalid
I know `var epdqPayloadDefinitionFor3ds2NewOrder = new EpdqPayloadDefinitionForNew3ds2Order(FRONTEND_URL, language, BRITISH_SUMMER_TIME_OFFSET_CLOCK)` constructs the `EpdqPayloadDefinitionForNew3ds2Order` object with the appropriate `Clock` as a field but it would be good to have it explicitly here (like it is the other test) just to make it really clear what’s going on.

2020-05-04 11:09 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +    public void should_include_default_browserTimezoneOffsetMins_for_summer_time_when_timezone_offset_provided_is_invalid
Done

2020-05-04 11:17 UTC, alexbishop1 approved these changes

2020-05-04 11:26 UTC, merged