PP-6362 Refactor ePDQ 3DS tests
alphagov/pay-connector pull request #2317
Opened 2020-05-05 14:39 UTC by nimalank7

2020-05-05 16:36 UTC, alexbishop1 requested changes
Looks fine: just a couple of things.

2020-05-05 16:36 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderTest.java
> +    String successAuth3DSRequest() {
Convention is usually that “3DS” becomes “3ds” when it’s in a camel case method or variable name.

Also, I think this method should probably be `private` rather than default access (I know it just follows similar existing methods; we can change those too).

2020-05-05 16:36 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderTest.java
> +        gatewayAccount.setCredentials(ImmutableMap.of(
We can use the built-in `Map.of(…)` here.

2020-05-05 16:36 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderTest.java
> +                .withExternalId("mq4ht90j2oir6am585afk58kml")
Do we actually care about setting a specific external ID here?

2020-05-06 09:10 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderTest.java
> +    String successAuth3DSRequest() {
I don't think this can be the case as these methods are inherited in the EpdqPaymentProvider3ds test and so can't be made private.

2020-05-06 09:33 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderTest.java
> +        gatewayAccount.setCredentials(ImmutableMap.of(
Done

2020-05-06 09:40 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderTest.java
> +                .withExternalId("mq4ht90j2oir6am585afk58kml")
No but the successAuth3dsRequest is pulling in EPDQ_AUTHORISATION_3DS_REQUEST template. This template is used in the EpdqPayloadDefinitionForNewOrderTest where it is needed. I decided to use this template for the EpdqPaymentProviderTest to reduce duplication as it seems unnecessary to generate a separate fixture for this.

2020-05-06 09:54 UTC, alexbishop1 approved these changes

2020-05-06 09:56 UTC, merged