PP-6362 - Send extra 3DS2 details to ePDQ
alphagov/pay-connector pull request #2319
Opened 2020-05-06 11:25 UTC by nimalank7

Description:
- If the gateway account has 3DS2 enabled then it will send the extra parameter details across

2020-05-06 14:53 UTC, alexbishop1 requested changes
Looks promising but I have a few suggestions and I think we can make the test a bit more rigorous, as described below.

2020-05-06 14:53 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +                epdqPayloadDefinition = new EpdqPayloadDefinitionForNew3ds2Order(frontendUrl, request.getCharge().getLanguage(), Clock.systemUTC());
Per its Javadoc, `Clock.systemUTC()` returns an object that’s immutable and thread-safe, which are my two favourite words in the Java language. So we could have a singleton `Clock` and pass that in to each new `EpdqPayloadDefinitionForNew3ds2Order` we instantiate.

To do this, add a method to the Guice `ConnectorModule`:

```java
@Provides
@Singleton
public Clock systemUtcClock() {
    return Clock.systemUTC();
}
```

Then just add a `Clock` parameter to the `EpdqPaymentProvider` constructor annotated with the `@Inject` annotation. Guice will find the `Clock` from the `@Provides` method in `ConnectorModule` and inject it. The body of the constructor can then assign this to a field.

The beauty of doing this is that it means that anywhere we have class with an `@Inject` constructor, we can add a `Clock` parameter and Guice will inject the singleton UTC `Clock`.

2020-05-06 14:53 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +            }
Maybe a `switch` expression would work here?

```java
switch(request.getGatewayAccount().getIntegrationVersion3ds()) {
    case 2:
        epdqPayloadDefinition = new EpdqPayloadDefinitionForNew3ds2Order(frontendUrl, request.getCharge().getLanguage(), Clock.systemUTC());
        break;
    case 1:
    default:
        epdqPayloadDefinition = new EpdqPayloadDefinitionForNew3dsOrder(frontendUrl);
}
```

Not sure if it’s actually any better. I’ll leave it up to you.

2020-05-06 14:53 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderIT.java
> +    }
Possibly this could share some code with `buildTestGatewayAccountWith3DSEntity()`?

(Also, as I’ve said before, it should really be `3ds` in a method name.)

2020-05-06 14:53 UTC, alexbishop1 commented on src/test/resources/templates/epdq/authorisation-3ds2-request.txt
> +ACCEPTURL=http%3A%2F%2Fwww.frontend.example.com%2Fcard_details%2Fmq4ht90j2oir6am585afk58kml%2F3ds_required_in%2Fepdq&AMOUNT=500&CARDNO=5555444433331111&CN=Mr.+Payment&CURRENCY=GBP&CVC=737&DECLINEURL=
All the 3DS2 parameters are the defaults, aren’t they? Since we’ve decided that our testing is really an integration test, I think we might want to check actually setting the parameters on the `AuthCardDetails` to non-default values so that we check they actually eventually become the correct parameters in the payload.

However, testing the defaults does seem useful, so maybe we could have two tests: one where the parameters are set on `AuthCardDetails` and one where they’re not.

2020-05-06 17:54 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +            }
Not entirely sure what this adds so I'll leave it as it is.

2020-05-06 17:58 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderIT.java
> +    }
Refactored

2020-05-07 09:09 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +                epdqPayloadDefinition = new EpdqPayloadDefinitionForNew3ds2Order(frontendUrl, request.getCharge().getLanguage(), Clock.systemUTC());
Done

2020-05-07 09:09 UTC, nimalank7 commented on src/test/resources/templates/epdq/authorisation-3ds2-request.txt
> +ACCEPTURL=http%3A%2F%2Fwww.frontend.example.com%2Fcard_details%2Fmq4ht90j2oir6am585afk58kml%2F3ds_required_in%2Fepdq&AMOUNT=500&CARDNO=5555444433331111&CN=Mr.+Payment&CURRENCY=GBP&CVC=737&DECLINEURL=
Done

2020-05-07 10:45 UTC, alexbishop1 requested changes
Looks good. Just a couple of small things.

2020-05-07 10:45 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +                epdqPayloadDefinition = new EpdqPayloadDefinitionForNew3ds2Order(frontendUrl, request.getCharge().getLanguage(), Clock.systemUTC());
Went to all the effort of setting up a Guice-provided `Clock` but we’re not actually using it!

We want to add the `Clock` to the constructor parameters of this class:

```java
@Inject
public EpdqPaymentProvider(ConnectorConfiguration configuration,
                           GatewayClientFactory gatewayClientFactory,
                           Environment environment,
                           EpdqPayloadDefinitionForCancelOrder epdqPayloadDefinitionForCancelOrder,
                           EpdqPayloadDefinitionForCaptureOrder epdqPayloadDefinitionForCaptureOrder,
                           EpdqPayloadDefinitionForNewOrder epdqPayloadDefinitionForNewOrder,
                           EpdqPayloadDefinitionForQueryOrder epdqPayloadDefinitionForQueryOrder,
                           Clock clock) {
```

… then pass it in to the `EpdqPayloadDefinitionForNew3ds2Order` constructor when we instantiate it:

```java
epdqPayloadDefinition = new EpdqPayloadDefinitionForNew3ds2Order(frontendUrl, request.getCharge().getLanguage(), clock);
```

2020-05-07 10:45 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    @Inject
Ah, I see what you were trying to do!

This object is just instantiated by our code using `new` when needed, so `@Inject` won’t work here (we need to inject it in to the `EpdqPaymentProvider` — which is Guice-managed — then pass it down).

2020-05-07 10:45 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderIT.java
> +        authCardDetails.setJsScreenWidth("1500");
Minor, but could you make the height and width different? It provides a little bit of protection against the values being accidentally transposed.

2020-05-07 11:10 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/BaseEpdqPaymentProviderIT.java
> +        authCardDetails.setJsScreenWidth("1500");
Done

2020-05-07 11:10 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +    @Inject
Done

2020-05-07 11:33 UTC, alexbishop1 approved these changes

2020-05-07 11:45 UTC, merged