PP-6363 - Send HTTP Accept Header for authorisation for ePDQ 3DS2
alphagov/pay-connector pull request #2321
Opened 2020-05-07 14:30 UTC by nimalank7

Description:
- Sends the HTTP Accept Header for authorisation and provides a default value if none provided

2020-05-07 14:39 UTC, alexbishop1 requested changes
Looks good apart from one small thing…

2020-05-07 14:39 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        return Optional.ofNullable(templateData.getAuthCardDetails().getAcceptHeader()).orElse(DEFAULT_BROWSER_ACCEPT_HEADER);
We should also be using the `DEFAULT_BROWSER_ACCEPT_HEADER` if we the submitted one is the empty string.

2020-05-07 14:49 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +        return Optional.ofNullable(templateData.getAuthCardDetails().getAcceptHeader()).orElse(DEFAULT_BROWSER_ACCEPT_HEADER);
Good catch!

2020-05-07 16:05 UTC, alexbishop1 approved these changes

2020-05-07 16:05 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +                .filter(header -> !header.equals(""))
Another way to do this is to statically import `java.util.function.Predicate.not` and then do `filter(not(String::isEmpty))`.

2020-05-07 16:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider3dsIT.java
> +    @Ignore
As agreed, these tests are being temporarily ignored until all the new parameters have been implemented. There’s no risk to do this because no-one is using 3DS2 with ePDQ yet.

2020-05-07 16:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +    @Parameters({"null", ""})
I didn’t know  the string `"null"` would become an actual `null`!

2020-05-07 16:06 UTC, alexbishop1 requested changes
Whoops! Scrolled too fast and missed an unwanted change!

2020-05-07 16:06 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> -                    .add(HTTPACCEPT_URL, ACCEPT_HEADER)
Don’t remove this. We still want this to be sent.

2020-05-07 17:22 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +    @Parameters({"null", ""})
Yep hence the `@Nullable` annotation!

2020-05-07 17:22 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> -                    .add(HTTPACCEPT_URL, ACCEPT_HEADER)
What's the difference between ACCEPT_HEADER and the BROWSER_ACCEPT_HEADER? Do I change it to `.add(HTTPACCEPT_URL, BROWSER_ACCEPT_HEADER)?`

2020-05-11 09:55 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> -                    .add(HTTPACCEPT_URL, ACCEPT_HEADER)
Basically, we have to send the `Accept` header twice, in two different parameters: `HTTP_ACCEPT` (which is required for all 3DS payments) and `browserAcceptHeader` (which is required for 3DS2 payments).

We should probably make it so that we send the same value for both (right now `HTTP_ACCEPT` doesn’t get the same defaulting to `*/*` behaviour that `browserAcceptHeader` does.

In the test, we should be checking for the presence of both of parameters.

2020-05-11 10:45 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2Order.java
> +                .filter(header -> !header.equals(""))
Done

2020-05-11 10:46 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> -                    .add(HTTPACCEPT_URL, ACCEPT_HEADER)
Done

2020-05-11 13:41 UTC, alexbishop1 requested changes
Getting there! Just a couple of things…

2020-05-11 13:41 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3dsOrder.java
> +        }
This should really use the same code as `getBrowserAcceptHeader()` in `EpdqPayloadDefinitionForNew3dsOrder`. You can probably extract the common stuff into a single method.

2020-05-11 13:41 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +    private static final String ACCEPT_HEADER = "*/*";
Maybe we want this to not be the default one we use.

2020-05-11 13:41 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        assertThat(result, is(aParameterBuilder().build()));
Could you explicitly do `assertThat(result, is(aParameterBuilder().withBrowserAcceptHeader(EpdqPayloadDefinitionForNewOrderTest.DEFAULT_BROWSER_ACCEPT_HEADER).build()));` so it’s clear we expect the default to be used?

2020-05-11 13:41 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +                    .add(HTTPACCEPT_URL, browserAcceptHeader)
While you’re here, could you rename `HTTPACCEPT_URL` to `HTTP_ACCEPT_KEY`? The current name looks like a copypasta that doesn’t make much sense.

2020-05-11 14:17 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        assertThat(result, is(aParameterBuilder().build()));
Done

2020-05-11 14:17 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +    private static final String ACCEPT_HEADER = "*/*";
Done

2020-05-11 14:27 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +                    .add(HTTPACCEPT_URL, browserAcceptHeader)
Done

2020-05-11 14:28 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3dsOrder.java
> +        }
Done I put it in the super class and invoked the super class method

2020-05-11 15:12 UTC, alexbishop1 approved these changes

2020-05-11 15:18 UTC, merged