PP-6363 - Send HTTP User agent header to ePDQ 3DS2
alphagov/pay-connector pull request #2322
Opened 2020-05-07 15:55 UTC by nimalank7

Description:
- This sends the HTTP User agent header to ePDQ 3DS2 for authorisation or else provides a default value

2020-05-07 16:15 UTC, alexbishop1 requested changes
Looks good — just a couple of things.

2020-05-07 16:15 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> +        authCardDetails.setUserAgentHeader("Opera/9.8");
Niche!

2020-05-07 16:15 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> -                    .add(HTTPUSER_AGENT_URL, USER_AGENT_HEADER)
I think this wants to stay. We should probably make sure we do the same normalisation for this one (the defaulting to `Mozilla/5.0` if we don’t get a User-Agent header) as we do for the the new parameter.

Also could you rename `HTTPUSER_AGENT_URL` to `HTTP_USER_AGENT` or something? There’s no need for `URL` to be in there and it confuses me!

2020-05-11 13:03 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/epdq/payload/EpdqPayloadDefinitionForNew3ds2OrderTest.java
> -                    .add(HTTPUSER_AGENT_URL, USER_AGENT_HEADER)
Done

2020-05-11 15:46 UTC, alexbishop1 approved these changes

2020-05-11 15:53 UTC, merged