PP-6346 Stripe transfer records pay transaction id for reconciliation
alphagov/pay-connector pull request #2329
Opened 2020-05-11 17:31 UTC by sfount

Require a `charge` or `refund` external ID when making a Stripe
transfer so that these can be used to simply and clearly reconcile
transactions with bank payouts.

2020-05-12 09:39 UTC, sfount commented on src/main/java/uk/gov/pay/connector/gateway/stripe/request/StripeTransferMetadata.java
> +    private final String reconciliationTransactionId;
Proposal to change to `govuk_pay_transaction_external_id` to make this clearer to understand outside of this feature context

2020-05-12 15:03 UTC, kbottla requested changes
Looks good, just a few minor comments

2020-05-12 15:03 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/request/StripeTransferMetadata.java
> +        return "metadata[" + key + "]";
```suggestion
        return format("metadata[%s]", key);
```

2020-05-12 15:03 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/request/StripeTransferInRequest.java
> +        super(amount, gatewayAccount, stripeChargeId, idempotencyKey, stripeGatewayConfig, govukPayTransactionExternalId);
Can we have an assertion here https://github.com/alphagov/pay-connector/blob/5ac4d251a1b7009cfc4f90260565951e8e4556f3/src/test/java/uk/gov/pay/connector/gateway/stripe/request/StripeTransferInRequestTest.java#L26 for new metadata field

2020-05-12 15:03 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/request/StripeTransferOutRequest.java
> +        super(amount, gatewayAccount, sourceTransactionId, idempotencyKey, stripeGatewayConfig, govukPayTransactionExternalId);
similarly an assertion here https://github.com/alphagov/pay-connector/blob/846e580b882d26a9fc64aae1822ddaf4f0d496e4/src/test/java/uk/gov/pay/connector/gateway/stripe/request/StripeTransferOutRequestTest.java#L23 for new metadata field

2020-05-12 15:03 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/request/StripeTransferMetadata.java
> +    public Map<String, String> format() {
```suggestion
    public Map<String, String> getParams-- or something similar ?() {
```

2020-05-13 07:58 UTC, sfount commented
@kbottla thanks for the useful comments, addressed them all in https://github.com/alphagov/pay-connector/commit/f6add7a76cb03ce7cafd1fdfb76e2142103f462f

2020-05-13 08:07 UTC, sfount commented on src/main/java/uk/gov/pay/connector/gateway/stripe/request/StripeTransferOutRequest.java
> +        super(amount, gatewayAccount, sourceTransactionId, idempotencyKey, stripeGatewayConfig, govukPayTransactionExternalId);
Agreed 👍 good catch

2020-05-13 09:50 UTC, kbottla approved these changes

2020-05-13 09:59 UTC, merged