PP-6256 - Add US states and Canadian provinces and territories mapping
alphagov/pay-connector pull request #2501
Opened 2020-08-19 19:00 UTC by nimalank7

Description:
- This gives the mapping from the various ZIP and postal codes to the relevant US and Canadian provinces.
- Since a later PR will turn on the actual mapping in ChargeService it merely runs through the code and calculates the provinces but doesn't do anything with them
- The Utils have been made static so that we can simply call the method
- I have excluded the Santa postcode. I didn't do any further granular analysis of Canadian post codes as there are far too many exceptions in say the 'A' category which made it unfeasible. So even if 'A6...' is an unassigned postcode the code will assign it to the relevant territory/province.

## How to test
- Run the Utils test

2020-08-20 09:42 UTC, alexbishop1 requested changes
This looks like it’s along the right lines. I’ve left some suggestions.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        }
We can use `ifPresent(…)` rather than `isPresent()` here:

```java
if (authCardDetails.getAddress().ifPresent(address -> {
        AddressEntity addressEntity = new AddressEntity(address);
        processRegionForCanadaOrUs(addressEntity);
        detailsEntity.setBillingAddress(addressEntity);
});

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        String country = addressEntity.getCountry().toLowerCase();
We don’t actually need to do this for the reasons described below.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        String normalisedPostalCode = addressEntity.getPostcode().replaceAll("\\s", "");
It would be more efficient to only do this once we know we’re dealing with a US or Canadian address.

Also, we should upper-case the postcode here, using `toUpperCase(Locale.ENGLISH)`.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            case "usa":
So it’s not at all obvious at this point in the code but `addressEntity.getCountry()` will always give you an ISO 3166-1 alpha-2 country code, so we only need to check for “US” and “CA”.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritory.java
> +public class CanadaProvinceTerritory {
This would work great as an enum.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritoryUtils.java
> +public class CanadaProvinceTerritoryUtils {
`Utils` is so generic. I’d call this `CanadianPostcodeToProvinceOrTerritoryMapper` or something.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritoryUtils.java
> +    private final static Pattern postalAddress = Pattern.compile("[A-Z][0-9][A-Z][0-9][A-Z][0-9]");
Use `SCREAMING_SNAKE_CASE` for constant names.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritoryUtils.java
> +    private final static Pattern postalAddress = Pattern.compile("[A-Z][0-9][A-Z][0-9][A-Z][0-9]");
I suppose `[A-WY-Z][0-9][A-Z][0-9][A-Z][0-9]` would exclude an initial X and make the two regexen mutually exclusive.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritoryUtils.java
> +            new AbstractMap.SimpleEntry<>("A", provinceTerritoryOf("NL", "Newfoundland and Labrador")),
We can use `Map.entry(…)` in place of `new AbstractMap.SimpleEntry<>(…)` to make it a lot shorter (and we can even static import `Map.entry` to make it even shorter).

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritoryUtils.java
> +            new AbstractMap.SimpleEntry<>("H", provinceTerritoryOf("QC", "Quebec")),
If we use an enum for provinces and territories as suggested above, we can just reference that rather than repeatedly stating that Quebec’s abbreviation is QC.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritoryUtils.java
> +        if ("H0H0H0".equals(normalisedPostalCode)) {
Should probably extract “H0H0H0” to a constant with a meaningful name like `SANTA_CLAUS_POSTAL_CODE` or `I_BET_WHEN_CANADA_POST_WERE_BEING_CUTE_GIVING_SANTA_HIS_OWN_POSTAL_CODE_THEY_DID_NOT_CONSIDER_COMPUTER_PROGRAMMERS_WOULD_HAVE_TO_SPECIAL_CASE_IT`.

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsState.java
> +public class UsState {
I think it would be cleanest to separate out the domain object that represents a US state from the ZIP codes that match it (much like you’ve done for Canada).

2020-08-20 09:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsState.java
> +        return zipCodeInteger <= getHighestZipCode() && zipCodeInteger >= getLowestZipCode();
This all feels quite complicated. Honestly, I think having a thousand-line file that maps each three-digit code to a state would be the simplest thing to do. (If we grab the page source of https://en.wikipedia.org/wiki/List_of_ZIP_Code_prefixes it should be fairly easy to use some text editor magic to generate most of the file for us.)

2020-08-20 16:16 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        }
Done

2020-08-20 16:16 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        String country = addressEntity.getCountry().toLowerCase();
Done

2020-08-20 16:16 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        String normalisedPostalCode = addressEntity.getPostcode().replaceAll("\\s", "");
Done

2020-08-20 16:17 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            case "usa":
Done

2020-08-20 16:17 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritoryUtils.java
> +            new AbstractMap.SimpleEntry<>("A", provinceTerritoryOf("NL", "Newfoundland and Labrador")),
Done

2020-08-20 16:17 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritoryUtils.java
> +            new AbstractMap.SimpleEntry<>("H", provinceTerritoryOf("QC", "Quebec")),
Done

2020-08-20 16:17 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/CanadaProvinceTerritoryUtils.java
> +        if ("H0H0H0".equals(normalisedPostalCode)) {
Done

2020-08-20 16:17 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsState.java
> +public class UsState {
Done - I replaced it with an enum following what I did with Canada

2020-08-20 16:17 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsState.java
> +        return zipCodeInteger <= getHighestZipCode() && zipCodeInteger >= getLowestZipCode();
Done

2020-08-21 10:52 UTC, alexbishop1 requested changes
This is getting there. I made a few suggestions.

Can we also think about an appropriate package to put all this stuff in rather than just `uk.gov.pay.connector.util`? Maybe `uk.gov.pay.connector.address` or something?

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        String country = addressEntity.getCountry();
I’d just inline this into the `switch` statement.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        String normalisedPostalCode = addressEntity.getPostcode().replaceAll("\\s", "").toUpperCase(Locale.ENGLISH);
It would be more efficient to only do this when we know the country is the US or Canada (we can extract it into a private method to avoid duplicating the code).

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +public class CanadaPostcodeToProvinceOrTerritoryMapper {
It turns out in Canada they’re call “postal codes” rather than “postcodes” so to be pedantic, this should really be `CanadaPostalCodeToProvinceOrTerritoryMapper`.

Sorry.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +    private final static Pattern POSTAL_ADDRESS = Pattern.compile("[A-Z][0-9][A-Z][0-9][A-Z][0-9]");
This is really a `WELL_FORMED_POSTAL_CODE`.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +    private final static String SANTA_CLAUS_POSTAL_CODE = "H0H0H0";
🎅🏻

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +            entry("Y", CanadaProvinceTerritory.YUKON)
I’d static import `CanadaProvinceTerritory.NEWFOUNDLAND_AND_LABRADOR` and friends to make this a bit cleaner.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +    public enum CanadaProvinceTerritory {
I think this can live in its own file.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +        NORTHWEST_TERRITORIES("NT", "Northwest Territories");
Can we put these in some sort of logical order?

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +        CanadaProvinceTerritory(String abbreviation, String fullStateName) {
It’s a province or territory, not a state!

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +            this.fullName = fullStateName;
Although it’s strictly unnecessary, if you do this:

```java
this.abbreviation = Objects.requireNonNull(abbreviation);
this.fullName = Objects.requireNonNull(fullStateName);
```

… it makes it really obvious to the reader that neither value can be null.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateMapping.java
> +public class UsStateMapping {
Maybe `UsZipCodeToStateMapper` for consistency?

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateMapping.java
> +    We have to use this initializiation method because it causes a compiler error otherwise. See https://youtrack.jetbrains.com/issue/IDEA-245963
We can be a bit more explicit here and say “Map.ofEntries(…) with hundreds of arguments is excessively slow to compile” or similar.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateMapping.java
> +    public final static Map<String, String> ZIP_CODE_TO_US_STATE_ABBREVIATIONS = new HashMap<>() {{
We can wrap this whole thing in `Map.copyOf(…)` to make it unmodifiable.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateMapping.java
> +        put("005", "NY");
Might be more flexible if we mapped to a `UsState` rather than an abbreviation string.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +public class UsStateUtils {
I think this can probably be merged into `UsStateMapping`.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +    private final static Pattern stateWithZipCode = Pattern.compile("[A-Z]{2}[0-9]{5}");
🐍

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +    private final static Pattern zipCodeFourPlus = Pattern.compile("[0-9]{5}-[0-9]{4}");
It’s called ZIP+4 so `ZIP_PLUS_FOUR` would be a more appropriate name.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +    private final static Map<String, UsState> US_STATE_ABBREVIATIONS = Map.ofEntries(
I think if we make `ZIP_CODE_TO_US_STATE_ABBREVIATIONS` map to a `UsState`, we won’t need this.

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +        return stateAbbreviation.map(state -> US_STATE_ABBREVIATIONS.get(state));
```java
return stateAbbreviation.map(US_STATE_ABBREVIATIONS::get);
```

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +        SOUTH_CAROLINA("NC", "South Carolina"),
Don’t conflate the Carolinas!

2020-08-21 10:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +        ALASKA("AK", "Alaska");
Order seems a bit arbitrary here. Can we order them alphabetically or by order of admission to the union or something?

2020-08-24 10:29 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +    private final static Map<String, UsState> US_STATE_ABBREVIATIONS = Map.ofEntries(
We do need this because we want to be able to go from a state abbreviation in the ZIP code to the US state.

2020-08-24 12:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +    private final static Map<String, UsState> US_STATE_ABBREVIATIONS = Map.ofEntries(
Ah, I see. But we should be able to avoid explicitly listing the associations between the abbreviations and the states…

```java
private static final Map<String, UsState> = Arrays.stream(UsState.values()).collect(toUnmodifiableMap(UsState::getAbbreviation, identity()));
```

(Need to static import `java.util.stream.Collectors.toUnmodifiableMap` and ` java.util.function.Function.identity` for that to work.)

2020-08-24 12:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +    private final static Map<String, UsState> US_STATE_ABBREVIATIONS = Map.ofEntries(
Done

2020-08-24 12:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +            entry("Y", CanadaProvinceTerritory.YUKON)
Done.

2020-08-24 12:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +    private final static Pattern POSTAL_ADDRESS = Pattern.compile("[A-Z][0-9][A-Z][0-9][A-Z][0-9]");
Done

2020-08-24 12:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +public class CanadaPostcodeToProvinceOrTerritoryMapper {
Done

2020-08-24 12:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        String normalisedPostalCode = addressEntity.getPostcode().replaceAll("\\s", "").toUpperCase(Locale.ENGLISH);
Done

2020-08-24 12:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        String country = addressEntity.getCountry();
Done

2020-08-24 12:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +    public enum CanadaProvinceTerritory {
Done

2020-08-24 12:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +        CanadaProvinceTerritory(String abbreviation, String fullStateName) {
Done

2020-08-24 12:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/CanadaPostcodeToProvinceOrTerritoryMapper.java
> +            this.fullName = fullStateName;
Done

2020-08-24 12:48 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateMapping.java
> +public class UsStateMapping {
Done

2020-08-24 12:48 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateMapping.java
> +    We have to use this initializiation method because it causes a compiler error otherwise. See https://youtrack.jetbrains.com/issue/IDEA-245963
Done

2020-08-24 12:48 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateMapping.java
> +    public final static Map<String, String> ZIP_CODE_TO_US_STATE_ABBREVIATIONS = new HashMap<>() {{
Done

2020-08-24 12:48 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateMapping.java
> +        put("005", "NY");
Done

2020-08-24 12:48 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +public class UsStateUtils {
Perhaps but I think that would end up cluttering the class and make it a little unreadable. It's easier to just have it in its own file.

2020-08-24 12:49 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +    private final static Pattern stateWithZipCode = Pattern.compile("[A-Z]{2}[0-9]{5}");
Done

2020-08-24 12:49 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +    private final static Pattern zipCodeFourPlus = Pattern.compile("[0-9]{5}-[0-9]{4}");
Done.

2020-08-24 12:49 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +        return stateAbbreviation.map(state -> US_STATE_ABBREVIATIONS.get(state));
Done

2020-08-24 12:49 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +        SOUTH_CAROLINA("NC", "South Carolina"),
Done.

2020-08-24 12:49 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/util/UsStateUtils.java
> +        ALASKA("AK", "Alaska");
Done.

2020-08-26 09:20 UTC, alexbishop1 requested changes
My main suggestion is to look at using capturing groups in the regexen to extract the prefixes for look-ups. Other than that, I think this is almost there.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +    private final static Pattern WELL_FORMED_X_POSTAL_ADDRESS = Pattern.compile("X[0-9][A-Z][0-9][A-Z][0-9]");
Being pedantic here but these should really be `WELL_FORMED_POSTAL_CODE` and `WELL_FORMED_X_POSTAL_CODE`.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +    );
Checked that these are correct.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +    );
Checked that these are correct.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +        String firstThreeLetters = normalisedPostalCode.substring(0, 3);
We could avoid having to do this by using capturing groups in the regexen.

If we changed `WELL_FORMED_X_POSTAL_ADDRESS` to be `(X[0-9][A-Z])[0-9][A-Z][0-9]` (note the parentheses around the first three characters, we could do something like this:

```java
var xPostalCodeMatcher = WELL_FORMED_X_POSTAL_ADDRESS.matcher(normalisedPostalCode);
if (xPostalCodeMatcher.matches()) {
    var firstThreeCharacters = xPostalCodeMatcher.group(1);
    return Optional.ofNullable(X_POSTAL_CODE_TERRITORY_MAP.get(firstThreeCharacters));
}
```

And similar for the non-X postal codes.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaProvinceOrTerritory.java
> +    CanadaProvinceOrTerritory(String abbreviation, String fullStateName) {
It’s Canada. No states here!

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/NorthAmericaRegion.java
> +public interface NorthAmericaRegion {
Other than the geography lesson, is this interface actually buying us anything?

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsState.java
> +    IDAHO("ID", "Idaho"),
Note to self: watch _My Own Private Idaho_ some time.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsState.java
> +    WASHINGTON_DC("DC", "District of Colombia"),
“District of Columbia”.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsState.java
> +    WYOMING("WY", "Wyoming");
Apart from the exceptions noted, these look correct.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMap.java
> +        put("008", VIRGINIA);
I think this should be the US Virgin Islands.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMap.java
> +        put("999", ALASKA);
I’ve checked these and — with the exception noted above — I think they’re correct.

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +    private final static Pattern WELL_FORMED_STATE_WITH_ZIP_FOUR_PLUS = Pattern.compile("[A-Z]{2}[0-9]{5}-[0-9]{4}");
`WELL_FORMED_STATE_WITH_ZIP_PLUS_FOUR`

2020-08-26 09:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +            return getStateFromZipCode(normalisedZipCode.substring(0, 3));
We could use the same trick to use the regex to extract the first few characters.

2020-08-26 09:20 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapperTest.java
> +        assertThat(canadaProvinceTerritory.get().getFullName(), is ("Newfoundland and Labrador"));
We can just assert that it’s equal to the enum value, rather than checking the abbreviation and full name separately.

2020-08-26 09:20 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapperTest.java
> +    public void shouldNotReturnAStateForSantaPostCode() {
This should really be `PostalCode` for consistency.

2020-08-26 09:20 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapperTest.java
> +    public void shouldReturnTheCorrectStateForHighestValidZipCode() {
Are these highest and lowest tests the most appropriate now we’re not using ranges to match?

2020-08-26 09:20 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapperTest.java
> +        Optional<UsState> usState = UsZipCodeToStateMapper.getState("00000");
Wouldn’t 000 or something be better?

2020-08-26 11:39 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +    private final static Pattern WELL_FORMED_X_POSTAL_ADDRESS = Pattern.compile("X[0-9][A-Z][0-9][A-Z][0-9]");
Done

2020-08-26 11:39 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +        String firstThreeLetters = normalisedPostalCode.substring(0, 3);
Done. I didn't do it for the US as I'm using `||` with 2 matchers.

2020-08-26 11:39 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaProvinceOrTerritory.java
> +    CanadaProvinceOrTerritory(String abbreviation, String fullStateName) {
Done.

2020-08-26 11:41 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/NorthAmericaRegion.java
> +public interface NorthAmericaRegion {
In the next PR it saves a few lines of code. 
`switch(addressEntity.getCountry()) {
case "US"
case "CA"
 Optional<NorthAmericanRegion>(...).map(region -> region.getAbbreviation)
}`

2020-08-26 11:41 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsState.java
> +    IDAHO("ID", "Idaho"),
Ha

2020-08-26 11:41 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsState.java
> +    WASHINGTON_DC("DC", "District of Colombia"),
Done.

2020-08-26 11:41 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMap.java
> +        put("008", VIRGINIA);
Done.

2020-08-26 11:41 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +    private final static Pattern WELL_FORMED_STATE_WITH_ZIP_FOUR_PLUS = Pattern.compile("[A-Z]{2}[0-9]{5}-[0-9]{4}");
Done

2020-08-26 11:44 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +            return getStateFromZipCode(normalisedZipCode.substring(0, 3));
I don't think we can. In the case for WELL_FORMED_ZIP_CODE and WELL_FORMED_ZIP_FOUR_PLUS - we'd have to create 2 String variables which hold the first 3 characters from either matcher. Otherwise we'd have to have 4 separate if blocks.

2020-08-26 11:45 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapperTest.java
> +        assertThat(canadaProvinceTerritory.get().getFullName(), is ("Newfoundland and Labrador"));
Done

2020-08-26 11:45 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapperTest.java
> +    public void shouldNotReturnAStateForSantaPostCode() {
Done

2020-08-26 11:45 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapperTest.java
> +    public void shouldReturnTheCorrectStateForHighestValidZipCode() {
No apologies I forgot to remove these.

2020-08-26 11:45 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapperTest.java
> +        Optional<UsState> usState = UsZipCodeToStateMapper.getState("00000");
No because the test is checking whether it is in the correct zip code format but isn't actually assigned to anything. So it has to be 5 characters.

2020-08-26 14:59 UTC, alexbishop1 requested changes
One request relating to a naming thing. Another suggestion of how we could use possibly use capturing groups for US ZIP codes, which I’ll leave to your discretion. Other than that, looks good!

2020-08-26 14:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +        var postalCodeMatcher = WELL_FORMED_POSTAL_CODE.matcher(normalisedPostalCode);
Sucks a bit that we create matchers we might not use but I can’t thing of easy way to avoid this without making the code complicated.

2020-08-26 14:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +    private final static Pattern WELL_FORMED_STATE_WITH_ZIP_FOUR_PLUS = Pattern.compile("[A-Z]{2}[0-9]{5}-[0-9]{4}");
Still looks like `FOUR_PLUS` to me…

2020-08-26 14:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +            return getStateFromZipCode(normalisedZipCode.substring(0, 3));
We could do it if we used combined the regular ZIP and ZIP+4 regexen…

```java
private final static Pattern WELL_FORMED_STATE_WITH_ZIP_AND_OPTIONAL_PLUS_FOUR = Pattern.compile("([A-Z]{2})[0-9]{5}(?:-[0-9]{4})?");
private final static Pattern WELL_FORMED_ZIP_WITH_OPTIONAL_PLUS_FOUR = Pattern.compile("([0-9]{3})[0-9]{2}(?:-[0-9]{4})?");
```

2020-08-26 14:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapperTest.java
> +        assertThat(canadaProvinceTerritory.get().getFullName(), is (CanadaProvinceOrTerritory.NEWFOUNDLAND_AND_LABRADOR.getFullName()));
This could just be:

```java
assertThat(canadaProvinceTerritory.get(), is(CanadaProvinceOrTerritory.NEWFOUNDLAND_AND_LABRADOR));
```

2020-08-26 14:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +    private final static Pattern WELL_FORMED_POSTAL_CODE = Pattern.compile("([A-Z])[0-9][A-Z][0-9][A-Z][0-9]");
Not going to insist on this but generally the order is `private static final` (applies to a few places).

2020-08-26 15:43 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapperTest.java
> +        assertThat(canadaProvinceTerritory.get().getFullName(), is (CanadaProvinceOrTerritory.NEWFOUNDLAND_AND_LABRADOR.getFullName()));
Done

2020-08-26 15:44 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +    private final static Pattern WELL_FORMED_POSTAL_CODE = Pattern.compile("([A-Z])[0-9][A-Z][0-9][A-Z][0-9]");
Done

2020-08-26 16:07 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +        var postalCodeMatcher = WELL_FORMED_POSTAL_CODE.matcher(normalisedPostalCode);
Yeah - I had to quickly look up what non-capturing groups in regexes are! But that change does make it easier.

2020-08-26 16:19 UTC, alexbishop1 requested changes
Looks great apart from a rogue capital letter at the beginning of a variable name.

2020-08-26 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +            String FirstThreeCharacters = wellFormedZipCodeAndOptionalPlusFourMatcher.group(1);
A capital `F`?

2020-08-26 16:24 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +            String FirstThreeCharacters = wellFormedZipCodeAndOptionalPlusFourMatcher.group(1);
Done.

2020-08-26 16:27 UTC, alexbishop1 approved these changes
🎉

2020-08-26 16:34 UTC, merged