PP-6256 - Send US states and Canadian provinces or territories to gateway, ledger and database
alphagov/pay-connector pull request #2502
Opened 2020-08-19 22:19 UTC by nimalank7

Description:
- Since the mappings are now in place we can store the US states and Canadian provinces in the charge database, a PaymentDetailsEnteredEvent which contains the address_state_province and sent to Ledger as well as being sent to the payment gateways

2020-08-28 11:31 UTC, alexbishop1 requested changes
This looks like it’s along the right lines. Comments mostly relate to reducing duplication and tests.

2020-08-28 11:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            AddressEntity addressEntity = new AddressEntity(address);
Good spot!

We could actually do this:

```java
authCardDetails.getAddress().map(AddressEntity::new).ifPresent(addressEntity -> {
    // …
});
```

2020-08-28 11:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
>      private void processRegionForCanadaOrUs(AddressEntity addressEntity) {
The word “process” is a bit vague. Maybe `addUsStateOrCanadaProvinceTerritory` or something?

2020-08-28 11:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                UsZipCodeToStateMapper.getState(getNormalisedPostalCode(addressEntity))
I think it would be preferable if `UsZipCodeToStateMapper` (and `CanadaPostalcodeToProvinceOrTerritoryMapper`) were dependency-injected instantiated objects that we called non-static methods on.

2020-08-28 11:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/smartpay/SmartpayOrderRequestBuilder.java
> +    }
This is very similar to the code in `ChargeService` (and I expect other classes I haven’t gotten to yet). I think we should extract this to a separate class with a method that takes an `Address` (from where it can get both the country and the ready-for-normalisation postcode) and returns a `Optional<NorthAmericanRegion>` (I take back everything I said about that being an unnecessary interface!). The caller can then decide if it wants the abbreviation or the full name and set it on whatever the appropriate object is.

2020-08-28 11:31 UTC, alexbishop1 commented on src/main/resources/templates/smartpay/Smartpay3dsRequiredOrderTemplate.xml
> +                        <ns2:stateOrProvince><#if stateOrProvince?has_content>${stateOrProvince}</#if></ns2:stateOrProvince>
This should be `${stateOrProvince?xml}` to make the necessary escaping is applied.

2020-08-28 11:31 UTC, alexbishop1 commented on src/main/resources/templates/smartpay/SmartpayAuthoriseOrderTemplate.xml
> +                        <ns2:stateOrProvince><#if stateOrProvince?has_content>${stateOrProvince}</#if></ns2:stateOrProvince>
`${stateOrProvince?xml}`

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/model/domain/ChargeEntityFixture.java
> +        return cardDetailsEntity;
Any reason this can’t be just…?

```java
var cardDetailsEntity = defaultCardDetails().setBillingAddress(addressEntity);
return cardDetailsEntity;
```

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +        assertThat(chargeSpy.getCardDetails().getBillingAddress().get().getStateOrProvince(), is("DC"));
If we injected the mapper as suggested in an earlier comment, we could stub out the ZIP code to state mapping, which would mean this test wouldn’t rely on the external knowledge that 20500 is Washington DC.

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/smartpay/SmartpayOrderRequestBuilderTest.java
> +        Address address = new Address("41", "Scala Street", "EC2A 1AE", "London", null, "GB");
I’d be really tempted to explore a follow-up PR that removes the county stuff from `Address` altogether. It’s just confusing.

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProviderTest.java
> +    public void shouldAuthorise_ForAddressInUs() throws Exception {
Not sure this test is buying us a huge deal as we don’t assert anything about the request and it doesn’t change anything about the response.

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/SmartpayPaymentProviderTest.java
> +    public void shouldSendSuccessfullyAnOrderForMerchantWithUsAddressInRequest() throws Exception {
Maybe one for Canada too?

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/CardResourceAuthoriseIT.java
> +    public void shouldStoreAddressStateProvinceForAuthorisedChargeFromUs() {
`FromUs` makes it sound like it’s… from us. Maybe `FromUsa` or `FromUnitedStates`?

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/CardResourceAuthoriseIT.java
> +                "DC",
Is this right? This test is testing a call to connector, right? And connector never receives the state in the call, it infers it internally.

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/resources/templates/smartpay/special-char-valid-authorise-smartpay-3ds-request.xml
> -                        <ns2:stateOrProvince>London --&gt;</ns2:stateOrProvince>
Maybe the `--&gt;` should be moved to another element. Looks like this test is trying to check entities are handled correctly.

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/resources/templates/worldpay/valid-authorise-worldpay-request-full-address.xml
> -                            <state>London county</state>
https://commons.wikimedia.org/wiki/File:County_Hall_(8710618372).jpg

2020-08-28 11:31 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +
We might want a variant of `updateChargeAndEmitEventPostAuthorisation_shouldEmitEvent` for when the country is the US or Canada to check the state/province/territory gets sent to ledger.

2020-08-28 16:38 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            AddressEntity addressEntity = new AddressEntity(address);
Done.

2020-08-28 16:38 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
>      private void processRegionForCanadaOrUs(AddressEntity addressEntity) {
Done.

2020-08-28 16:42 UTC, nimalank7 commented on src/main/resources/templates/smartpay/Smartpay3dsRequiredOrderTemplate.xml
> +                        <ns2:stateOrProvince><#if stateOrProvince?has_content>${stateOrProvince}</#if></ns2:stateOrProvince>
Done.

2020-08-28 16:42 UTC, nimalank7 commented on src/main/resources/templates/smartpay/SmartpayAuthoriseOrderTemplate.xml
> +                        <ns2:stateOrProvince><#if stateOrProvince?has_content>${stateOrProvince}</#if></ns2:stateOrProvince>
Done.

2020-08-28 17:03 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProviderTest.java
> +    public void shouldAuthorise_ForAddressInUs() throws Exception {
Yeah that's true - and also it's covered in the contract tests.

2020-08-28 17:18 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/it/resources/CardResourceAuthoriseIT.java
> +                "DC",
Oh yes your right I've set it to null.

2020-08-28 17:26 UTC, nimalank7 commented on src/main/resources/templates/smartpay/Smartpay3dsRequiredOrderTemplate.xml
> +                        <ns2:stateOrProvince><#if stateOrProvince?has_content>${stateOrProvince}</#if></ns2:stateOrProvince>
Done

2020-08-28 17:27 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/charge/model/domain/ChargeEntityFixture.java
> +        return cardDetailsEntity;
Ah I just realised this method is never called so I've removed it.

2020-08-28 17:30 UTC, nimalank7 commented on src/test/resources/templates/smartpay/special-char-valid-authorise-smartpay-3ds-request.xml
> -                        <ns2:stateOrProvince>London --&gt;</ns2:stateOrProvince>
Done

2020-08-28 17:39 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/it/contract/SmartpayPaymentProviderTest.java
> +    public void shouldSendSuccessfullyAnOrderForMerchantWithUsAddressInRequest() throws Exception {
Done

2020-08-28 17:39 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/it/resources/CardResourceAuthoriseIT.java
> +    public void shouldStoreAddressStateProvinceForAuthorisedChargeFromUs() {
Done

2020-08-31 17:14 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/smartpay/SmartpayOrderRequestBuilder.java
> +    }
Done.

2020-08-31 17:39 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +        assertThat(chargeSpy.getCardDetails().getBillingAddress().get().getStateOrProvince(), is("DC"));
I've stubbed it out now.

2020-08-31 17:50 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +
Done.

2020-08-31 19:26 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                UsZipCodeToStateMapper.getState(getNormalisedPostalCode(addressEntity))
Done.

2020-09-01 14:42 UTC, alexbishop1 requested changes
I think this is almost there. A few minor suggestions about code style and a couple of slightly larger ones about injecting more so that we can stub things out in tests and not keep repeatedly checking that the 20500 ZIP code is Washington DC.

2020-09-01 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    .ifPresent(northAmericanRegion -> addressEntity.setStateOrProvince(northAmericanRegion.getAbbreviation()));
I spent longer than I care to admit fiddling with this to see if there’s a way we can remove the need for the nested `ifPresent(…)` methods. It’s hard because we have to deal with both the address and a state or province maybe not being present. In the end I came up with this:

```java
authCardDetails.getAddress().ifPresent(address -> {
    northAmericanRegionMapper.getNorthAmericanRegionForCountry(address)
            .map(NorthAmericaRegion::getAbbreviation)
            .ifPresent(stateOrProvinceAbbreviation -> {
                var addressEntity = new AddressEntity(address);
                addressEntity.setStateOrProvince(stateOrProvinceAbbreviation);
                detailsEntity.setBillingAddress(addressEntity);
            });
});
```

It’s not beautiful by any means but it does mean we can call `NorthAmericanRegionMapper.getNorthAmericanRegionForCountry(Address)` rather than `NorthAmericanRegionMapper.getNorthAmericanRegionForCountry(AddressEntity)`, which then means we don’t need the latter, which removes some duplication.

2020-09-01 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/smartpay/SmartpayOrderRequestBuilder.java
> +        );
```java
authCardDetails.getAddress()
        .flatMap(northAmericanRegionMapper::getNorthAmericanRegionForCountry)
        .map(NorthAmericaRegion::getAbbreviation)
        .ifPresent(smartpayTemplateData::setStateOrProvince);
```

2020-09-01 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/request/StripePaymentMethodRequest.java
> +                    .ifPresent(stateOrProvince -> localParams.put("billing_details[address[state]]", stateOrProvince.getFullName()));
Could also do this:

```java
northAmericanRegionMapper.getNorthAmericanRegionForCountry(address)
        .map(NorthAmericaRegion::getFullName)
        .ifPresent(stateOrProvince -> localParams.put("billing_details[address[state]]", stateOrProvince));
```

2020-09-01 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilder.java
> +                        .ifPresent(stateOrProvince -> worldpayTemplateData.setState(stateOrProvince.getAbbreviation()))
```java
authCardDetails.getAddress()
        .flatMap(northAmericanRegionMapper::getNorthAmericanRegionForCountry)
        .map(NorthAmericaRegion::getAbbreviation)
        .ifPresent(worldpayTemplateData::setState);
```

2020-09-01 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +
It should be possible to make this `CanadaProvinceOrTerritory` rather than `NorthAmericaRegion`. Might have to change `getNorthAmericanRegionForCountry(…)` in `NorthAmericanRegionMapper` to return `Optional<? extends NorthAmericaRegion>` to get it all to compile.

2020-09-01 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/NorthAmericanRegionMapper.java
> +    public Optional<NorthAmericaRegion> getNorthAmericanRegionForCountry(AddressEntity addressEntity) {
As suggested in earlier comments, I think we can just have the `Address` variant of this method.

2020-09-01 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +    public Optional<NorthAmericaRegion> getState(String normalisedZipCode) {
I think this can actually stay as `UsState`.

2020-09-01 14:42 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +    public void shouldUpdateStateOrProvinceForChargeWhenCountryIsUs() {
Does this test differ significantly from the previous one?

2020-09-01 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/smartpay/SmartpayOrderRequestBuilder.java
> +        this.northAmericanRegionMapper = new NorthAmericanRegionMapper();
Not sure about using `new` here. If it were injected, we could stub it in the tests.

2020-09-01 14:42 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/smartpay/SmartpayOrderRequestBuilderTest.java
> +        Address usAddress = new Address("10 WCB", null, "20500", "Washington D.C.", null, "US");
If `NorthAmericanRegionMapper` were injected into `SmartpayOrderRequestBuilder`, we could just stub it with `given(mockNorthAmericanRegionMapper.get(usAddress)).willReturn(UsState.WASHINGTON_DC)`, which would mean this test wouldn’t rely on the mapping between the 20500 ZIP code and Washington DC.

2020-09-01 14:42 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/stripe/request/StripePaymentMethodRequestTest.java
> +        authCardDetails.setAddress(address);
Again, if `NorthAmericanRegionMapper` were injected, we could just stub it rather than having to provide a real Canadian address.

2020-09-01 14:42 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilderTest.java
> +    public void shouldGenerateValidAuthoriseOrderRequestForAddressWithMState() throws Exception {
`M`

2020-09-01 14:42 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/northamericaregion/NorthAmericanRegionMapperTest.java
> +}
You’ll be stunned to read that once again, I’m recommending injecting `UsZipCodeToStateMapper` and `CanadaPostalcodeToProvinceOrTerritoryMapper`.

That way, we could really hone this test down to just checking the logic it’s responsible for (checking if the country is “US” or “CA” and getting the calling the appropriate mapper). So we could end up with tests like this:

```java
private static final String POSTCODE = "I am a postcode!";

@Before
public void setUp() {
    given(mockUsZipCodeToStateMapper.getState(POSTCODE)).willReturn(UsState.WASHINGTON_DC);
    given(mockCanadaPostalcodeToProvinceOrTerritoryMapper.getProvinceOrTerritory(POSTCODE)).willReturn(CanadaProvinceOrTerritory.NUNAVUT);
}

@Test
public void shouldReturnTheCorrectProvinceOrTerritoryForValidAddressInCanada() {
    var Address new Address();
    address.setCountry("CA");
    address.setPostcode(POSTCODE);

    var provinceOrTerritory = mapper.getNorthAmericanRegionForCountry(address);

    assertThat(provinceOrTerritory.isPresent(), is (true));
    assertThat(provinceOrTerritory.get(), is (CanadaProvinceOrTerritory.NUNAVUT));
}

// And a similar test for the US

// And a similar test for a country that’s neither the US or Canada
```

2020-09-01 15:10 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +    public void shouldUpdateStateOrProvinceForChargeWhenCountryIsUs() {
Yes. The other test is checking whether an event has been emitted - this test is for whether the ChargeEntity has been updated with the correct state. I did think about combining the tests together but that would be mixing state and behaviour verification together.

2020-09-01 17:34 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    .ifPresent(northAmericanRegion -> addressEntity.setStateOrProvince(northAmericanRegion.getAbbreviation()));
This doesn't work I don't think. In the event that the stateOrProvinceAbbreviation isn't present then the consumer won't be called and so the addressEntity will never be passed into detailsEntity which is incorrect. Regardless of whetherstateOrProvinceAbbreviation is present we want the AddressEntity to be set in the CardDetailsEntity. I've done a proposed refactoring.

2020-09-01 17:47 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/request/StripePaymentMethodRequest.java
> +                    .ifPresent(stateOrProvince -> localParams.put("billing_details[address[state]]", stateOrProvince.getFullName()));
Sure.

2020-09-01 17:49 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    .ifPresent(northAmericanRegion -> addressEntity.setStateOrProvince(northAmericanRegion.getAbbreviation()));
Whoops, you’re right. Something like this then:

```java
authCardDetails.getAddress().ifPresent(address -> {
    var addressEntity = new AddressEntity(address);
    northAmericanRegionMapper.getNorthAmericanRegionForCountry(address)
            .map(NorthAmericaRegion::getAbbreviation)
            .ifPresent(addressEntity::setStateOrProvince);
    detailsEntity.setBillingAddress(addressEntity);
});
```

Alternatively, we could make it so that `Address` as well as the `AddressEntity` stores the state or province (it’s a bit weird that it’s only on one right now) and do something like this:

```java
authCardDetails.getAddress().ifPresent(address -> {
    northAmericanRegionMapper.getNorthAmericanRegionForCountry(address)
            .map(NorthAmericaRegion::getAbbreviation)
            .ifPresent(address::setStateOrProvince);
    });

    var addressEntity = new AddressEntity(address);
    detailsEntity.setBillingAddress(addressEntity);
```

But then that means we’d be mutating something in the `AuthCardDetails`, which I’m not thrilled about.

2020-09-01 17:50 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilder.java
> +                        .ifPresent(stateOrProvince -> worldpayTemplateData.setState(stateOrProvince.getAbbreviation()))
Done.

2020-09-01 17:50 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/NorthAmericanRegionMapper.java
> +    public Optional<NorthAmericaRegion> getNorthAmericanRegionForCountry(AddressEntity addressEntity) {
Done.

2020-09-01 17:53 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilderTest.java
> +    public void shouldGenerateValidAuthoriseOrderRequestForAddressWithMState() throws Exception {
Oops!

2020-09-01 17:54 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/northamericaregion/NorthAmericanRegionMapperTest.java
> +}
Sure unfortunately I can't do DI because the Smartpay/Worldpay methods constructors are called via static methods and I can't inject using `@Inject` as the classes aren't managed by the Guice container. Similar remarks apply to Stripe.

2020-09-01 18:44 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/CanadaPostalcodeToProvinceOrTerritoryMapper.java
> +
I agree. Originally I couldn't get Mockito to compile but now I've figured it out using the `Answer` interface.

2020-09-01 18:45 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    .ifPresent(northAmericanRegion -> addressEntity.setStateOrProvince(northAmericanRegion.getAbbreviation()));
Yep that's the one I've done.

2020-09-01 18:46 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/northamericaregion/UsZipCodeToStateMapper.java
> +    public Optional<NorthAmericaRegion> getState(String normalisedZipCode) {
Done.

2020-09-02 09:49 UTC, alexbishop1 approved these changes
I think this is good to go in. Thanks for your hard work responding to all the comments!

2020-09-02 09:49 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    });
This could be just `ifPresent(addressEntity::setStateOrProvince)`.

2020-09-02 09:49 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/northamericaregion/NorthAmericanRegionMapperTest.java
> +}
Even if we can’t easily do DI in the gateway-specific order request builders, we could still have this class have `UsZipCodeToStateMapper` and `CanadaPostalcodeToProvinceOrTerritoryMapper` injected (the order request builders would just have to do something like `mapper = new NorthAmericanRegionMapper(new UsZipCodeToStateMapper(), new CanadaPostalcodeToProvinceOrTerritoryMapper())`).

2020-09-02 09:53 UTC, merged