PP-6991: Split out DnsUtils
alphagov/pay-connector pull request #2631
Opened 2020-10-22 11:33 UTC by oswaldquek

Split out DnsUtils into its two functions: an IP to domain matcher and reverse
DNS lookup.

Doing this will allow the reverse DNS lookup to be stubbed out in tests, thus
removing the need for an actual network to be present. We don't need tests for
the reverse DNS lookup as code to do this is from a cookbook and not part of
our business logic.

This is the second of a series of PRs that aims to make the pay-connector build not depend on having a network available.

2020-10-22 11:58 UTC, oswaldquek commented
@alexbishop1 We could still keep the reverse dns lookup tests but put an `@Ignore` on it?

2020-10-22 13:36 UTC, alexbishop1 requested changes
Looks good. Just a few small suggestions.

2020-10-22 13:36 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/IpDomainMatcher.java
> +    private static final Logger logger = LoggerFactory.getLogger(IpDomainMatcher.class);
This should really be `LOGGER` because it’s a constant.

2020-10-22 13:36 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/IpDomainMatcher.java
> +    private ReverseDnsLookup reverseDnsLookup;
This can be `final`.

2020-10-22 13:36 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/IpDomainMatcher.java
> +            Optional<String> host = reverseDnsLookup.lookup(ipAddress);
I know this was like this when you got here but we can make it a bit more functional. Something like this:

```java
return reverseDnsLookup(ipAddress).map(host -> {
    if (!host.endsWith(domain + ".")) {
        logger.error("Reverse DNS lookup on ip '{}' - resolved domain '{}' does not match '{}'", ipAddress, host, domain);
        return false;
    }
    return true;
}).orElseThrow(() -> new Exception(format("Host not found for ip address '%s'", ipAddress)));
```

2020-10-22 13:36 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ReverseDnsLookup.java
> +        String reverseIp = join(".", components.toArray(new String[0])) + ".in-addr.arpa";
I think these lines could go in `IpDomainMatcher` (changing what this method expects) so that this class literally just has the lookup and no other logic in it.

2020-10-22 13:36 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ReverseDnsLookup.java
> +        String reverseIp = join(".", components.toArray(new String[0])) + ".in-addr.arpa";
The last line could also be written as `String reverseIp = components.stream().collect(Collectors.joining(".", "", ".in-addr.arpa"));` — not sure if that’s really any nicer though.

2020-10-22 13:36 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ReverseDnsLookup.java
> +            env.put("java.naming.factory.initial", "com.sun.jndi.dns.DnsContextFactory");
Please put generic type parameters on the `Hashtable`!

In fact, because the Javadoc for `InitialDirContext` says it won’t modify the `Hashtable`, we can probably make it a constant and just keep reusing the same one:

```java
private static final Hashtable<String, String> INITIAL_DIR_CONTEXT_ENV = new Hashtable<>(Map.of("java.naming.factory.initial", "com.sun.jndi.dns.DnsContextFactory"));
```

2020-10-22 13:36 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/IpDomainMatcherTest.java
> +    }
Maybe also a test with just a single IP address too (similar to `reverseDnsShouldReturnHostIfIpIsValid` in `DnsUtilsITest`)?

2020-10-22 13:37 UTC, alexbishop1 commented
> @alexbishop1 We could still keep the reverse dns lookup tests but put an `@Ignore` on it?

We could keep them unignored. They’d hit the network still but at least it would only be in a set of well-contained tests that don’t test anything else.

2020-10-22 16:22 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/util/ReverseDnsLookup.java
> +        String reverseIp = join(".", components.toArray(new String[0])) + ".in-addr.arpa";
I think these lines should remain in this class as extracting the "QUESTION SECTION" is part of doing a reverse dns lookup. It's nicer for the method signature to take the IP address. See this `dig` command to see what I mean about the "QUESTION SECTION":
```
>dig -x 195.35.90.1 

; <<>> DiG 9.10.6 <<>> -x 195.35.90.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24835
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;1.90.35.195.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
1.90.35.195.in-addr.arpa. 500	IN	PTR	hello.worldpay.com.
```

2020-10-22 16:38 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ReverseDnsLookup.java
> +        String reverseIp = join(".", components.toArray(new String[0])) + ".in-addr.arpa";
I see your point. It’s just that we end up with a few lines of code that would ordinarily be easy to test but which are hard to test because they’re mixed up in this class.

We could have a separate (injected) class that’s just responsible for going from an IP address to the `.in-addr.arpa` name. That would be then be easy to test but would still leave the method signature in `ReverseDnsLookup` as it is.

I’ll leave it up to your judgement.

2020-10-23 11:56 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/util/ReverseDnsLookup.java
> +        String reverseIp = join(".", components.toArray(new String[0])) + ".in-addr.arpa";
I created a `DnsPointerResourceRecord` class (and a corresponding test) for this.

2020-10-23 12:44 UTC, alexbishop1 approved these changes
Nice!

2020-10-23 12:44 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/DnsPointerResourceRecord.java
> +                .isEquals();
Just `return this.reverseIp.equals(that.reverseIp);` would do the trick.

2020-10-23 12:58 UTC, merged