PP-6948 - Log Worldpay 3DS Flex for 2nd authorisation request
alphagov/pay-connector pull request #2684
Opened 2020-11-17 09:37 UTC by nimalank7

Description:
- This PR fills a gap in our logging for Worldpay 3DS/Flex payments by logging out whether the payload for the 2nd authorisation request is 3DS or Flex

2020-11-17 09:41 UTC, alexbishop1 requested changes

2020-11-17 09:41 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +            return chargeEntity.getGatewayAccount().getWorldpay3dsFlexCredentials() != null ? " using Flex" : " using 3DS1";
I’m not quite sure about doing it this way. We want to make it possible to disable 3DS Flex without removing the credentials.

Ideally, we’d inspect the payload that we’re about to send to Worldpay to see if it has a device data collection result.

2020-11-17 18:13 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +            return chargeEntity.getGatewayAccount().getWorldpay3dsFlexCredentials() != null ? " using Flex" : " using 3DS1";
Done used the paResponse instead

2020-11-18 09:07 UTC, alexbishop1 requested changes
Looks good. Can we also add structured logging? We could call it `3ds_integration` or something with a value of `3DS1` or `3DS Flex`. That way we could reuse the same key with different values for other gateways if necessary (but we should only add it for Worldpay requests for now, since they’re the only ones that have different variants).

2020-11-18 09:07 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +            return auth3dsResult.getPaResponse() != null ? " using 3DS1" : " using Flex";
Slightly picky but let’s call it “3DS Flex” to match the name of the Worldpay product.

2020-11-18 12:58 UTC, alexbishop1 requested changes

2020-11-18 12:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/util/Authorisation3dsResponseSummaryStructuredLogging.java
> +public class Authorisation3dsResponseSummaryStructuredLogging {
I can see you’re following the pattern we use for the first authorisation request but I think this might be overkill to just add one parameter that we can easily calculate at the point we do the logging.

2020-11-18 14:28 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gateway/util/Authorisation3dsResponseSummaryStructuredLogging.java
> +public class Authorisation3dsResponseSummaryStructuredLogging {
Modified it to remove the classes and place it into the method.

2020-11-18 14:43 UTC, alexbishop1 requested changes

2020-11-18 14:43 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +    private String logWorldpay3dsOrFlex(Auth3dsResult auth3dsResult, ChargeEntity charge, Object[] structuredLoggingArguments) {
I think this method is trying to do too much. How about you instead you define an private enum in this class called `TypeOf3dsRequest` or something with values like `WORLDPAY_3DS_CLASSIC`, `WORLDPAY_3DS_FLEX` and `NONE_OF_THE_ABOVE`. Then have this method return that. Then you can call this method once near the start and store its result in a local variable. Then use if statements or switch statements to add the appropriate structured logging arguments or bits to the log line.

2020-11-18 16:31 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +    private String logWorldpay3dsOrFlex(Auth3dsResult auth3dsResult, ChargeEntity charge, Object[] structuredLoggingArguments) {
Yep changes made.

2020-11-18 16:56 UTC, alexbishop1 requested changes
Getting there…

2020-11-18 16:56 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +    enum TypeOf3dsRequest {
I think we can make this private.

2020-11-18 16:56 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +    private TypeOf3dsRequest logWorldpay3dsOrFlex(Auth3dsResult auth3dsResult, ChargeEntity charge) {
The name of this method doesn’t really fit any more.

2020-11-18 16:56 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +    }
I still think this is a bit overwrought.

How about immediately after the `var worldPay3dsOrFlexLogMessage = logWorldpay3dsOrFlex(auth3dsResult, updatedCharge);` line we just do this:

```java
var structuredLoggingArguments = updatedCharge.getStructuredLoggingArgs();
if (worldPay3dsOrFlexLogMessage == WORLDPAY_3DS_CLASSIC) {
    structuredLoggingArguments = ArrayUtils.addAll(structuredLoggingArguments, new StructuredArgument[] {kv(INTEGRATION_3DS_VERSION, "3DS")});
} else if (worldPay3dsOrFlexLogMessage == WORLDPAY_3DS_FLEX) {
    structuredLoggingArguments = ArrayUtils.addAll(structuredLoggingArguments, new StructuredArgument[] {kv(INTEGRATION_3DS_VERSION, "3DS Flex")});
}
```

2020-11-18 17:03 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +    }
Done.

2020-11-18 17:03 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +    private TypeOf3dsRequest logWorldpay3dsOrFlex(Auth3dsResult auth3dsResult, ChargeEntity charge) {
Changed.

2020-11-18 17:04 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/Card3dsResponseAuthService.java
> +    enum TypeOf3dsRequest {
We won't be able to do the static import if it is made private.

2020-11-18 17:06 UTC, alexbishop1 approved these changes

2020-11-18 17:13 UTC, merged