PP-7336: Update Epdq, Smartpay and Sandbox notification services to perform IP firewalling
alphagov/pay-connector pull request #2694
Opened 2020-11-24 12:11 UTC by adityapahuja

## WHAT YOU DID
This pull request has three commits.

1. The first commit updates Epdq Notification Service to perform IP firewalling so that only requests coming from Epdq can be processed. It adds unit tests and an integration test to ensure that Epdq Notification Service can process requests coming from Epdq and reject other requests which are not from Epdq. It also updates Notification Resource to specify which notification got rejected in a log message. It adds `EPDQ_ALLOWED_CIDRS` environment variable to README for Connector application. Connector application uses this environment variable containing a list of allowed Epdq CIDRs so that it can perform IP firewalling on incoming notifications from Epdq.
2. The second commit updates Smartpay Notification Service to perform IP firewalling so that only requests coming from Smartpay can be processed. It adds unit tests and an integration test to ensure that Smartpay Notification Service can process requests coming from Smartpay and reject other requests which are not from Smartpay. It adds `SMARTPAY_ALLOWED_CIDRS` environment variable to README for Connector application. Connector application uses this environment variable containing a list of allowed Smartpay CIDRs so that it can perform IP firewalling on incoming notifications from Smartpay.
3. The third commit updates Sandbox Notification Service to perform IP firewalling so that only requests coming from Sandbox can be processed. It adds unit tests and an integration test to ensure that Sandbox Notification Service can process requests coming from Sandbox and reject other requests which are not from Sandbox. It adds `SANDBOX_ALLOWED_CIDRS` environment variable to README for Connector application. Connector application uses this environment variable containing a list of allowed Sandbox CIDRs so that it can perform IP firewalling on incoming notifications from Sandbox.

## Code review checklist

### Logging

- [x] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [x] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
Yes, the following three new environment variables are introduced.
    - EPDQ_ALLOWED_CIDRS
    - SMARTPAY_ALLOWED_CIDRS
    - SANDBOX_ALLOWED_CIDRS

* Added new API / updated existing API definition
No.

2020-11-24 15:22 UTC, oswaldquek requested changes
I've reviewed the EPDQ code changes for now. Looks good but just general comments about 
* structured logging and
* inlining assertions
Also in the future it'd be good to separate out the code changes into smaller PRs, one for each gateway account.

2020-11-24 15:22 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/webhook/resource/NotificationResource.java
> +            LOGGER.info(String.format("Rejected notification from provider=Worldpay for IP '%s'", ipAddress), kv("notification_source", ipAddress));
It'd be better if the `provider=worldpay` could be logged as a structured logging argument. e.g.
```
{ 
   @timestamp: 2020-11-24T15:13:13.014Z
   @version: 1
   container: connector
   environment: production-2
   logger_name: xxxx
   message: xxx
   provider: worldpay
}
```

2020-11-24 15:22 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/webhook/resource/NotificationResource.java
> +            LOGGER.info(String.format("Rejected notification from provider=Epdq for IP '%s'", forwardedIpAddresses), kv("notification_source", forwardedIpAddresses));
same comment as above for structured logging

2020-11-24 15:22 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/webhook/resource/NotificationResource.java
> +            LOGGER.info(String.format("Rejected notification from provider=Stripe for IP '%s'", forwardedIpAddresses), kv("notification_source", forwardedIpAddresses));
same comment as above for structured logging

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +        assertTrue(result);
Nothing major but the above two lines could be collapsed to `assertTrue(notificationService.handleNotificationFor(payload, FORWARDED_IP_ADDRESSES))`

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +        assertTrue(result);
these can be inlined

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +        assertTrue(result);
these can be inlined

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +        assertTrue(result);
these can be inlined

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +        assertTrue(result);
these can be inlined

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +        assertTrue(result);
these can be inlined

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +        assertTrue(result);
these can be inlined

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +        assertTrue(result);
these can be inlined

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +        assertTrue(result);
these can be inlined

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceTest.java
> +        assertTrue(result);
these can be inlined

2020-11-24 15:22 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceTest.java
> +        assertFalse(result);
these can be inlined

2020-11-24 15:42 UTC, adityapahuja commented on src/main/java/uk/gov/pay/connector/webhook/resource/NotificationResource.java
> +            LOGGER.info(String.format("Rejected notification from provider=Worldpay for IP '%s'", ipAddress), kv("notification_source", ipAddress));
I was wondering about the odd looking field `provider=Stripe` in the following code in `NotificationResource.java` (line: 119).

```
LOGGER.info("Responding to notification from provider=Stripe with 200 {}", response);
```
I am not familiar with the structured logging argument. Your example helps. To get the provider into the structured logging argument, I would need to amend the code you highlighted into the following code. Does this look correct?

```
LOGGER.info(String.format("Rejected notification from %s for IP '%s'", PaymentGatewayName.WORLDPAY.getName(), ipAddress), 
                    kv("provider", PaymentGatewayName.WORLDPAY.getName()), 
                    kv("notification_source", ipAddress));
```

2020-11-24 15:47 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/webhook/resource/NotificationResource.java
> +            LOGGER.info(String.format("Rejected notification from provider=Worldpay for IP '%s'", ipAddress), kv("notification_source", ipAddress));
Yeah that looks correct. You can see https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/paymentprocessor/service/QueryService.java#L47 for an example, which uses standard logging keys we have. 
Sorry the bad examples are currently in NotificationResource! We should try and use structured logging whenever we can, it makes searching in splunk easier.

2020-11-24 15:56 UTC, adityapahuja commented
> I've reviewed the EPDQ code changes for now. Looks good but just general comments about
> 
> * structured logging and
> * inlining assertions
>   Also in the future it'd be good to separate out the code changes into smaller PRs, one for each gateway account.

I remember @alexbishop1 mentions that the number of lines must be under 500 for a single pull request. This pull request meets this requirement. This pull request has three separate commits and they are independent of each other. Would you like me to raise a pull request for each commit?

2020-11-24 15:59 UTC, adityapahuja commented on src/main/java/uk/gov/pay/connector/webhook/resource/NotificationResource.java
> +            LOGGER.info(String.format("Rejected notification from provider=Worldpay for IP '%s'", ipAddress), kv("notification_source", ipAddress));
Thanks @oswaldquek . I will make the changes.

2020-11-24 15:59 UTC, oswaldquek commented
@adityapahuja No it's ok, no need to raise separate PRs for now. 500 lines seems a lot!

2020-11-24 16:48 UTC, adityapahuja commented
I have made two further commits. The first commit is for using structured logging in Notification Resource and the second commit is for inlining assertions.

2020-11-24 17:08 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/webhook/resource/NotificationResource.java
> +                kv("provider", SMARTPAY.getName()),
Sorry to be a pain, but we should use `uk.gov.pay.logging.LoggingKeys.PROVIDER` here, similar to how https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/paymentprocessor/service/QueryService.java#L47 does it.

2020-11-24 17:31 UTC, adityapahuja commented on src/main/java/uk/gov/pay/connector/webhook/resource/NotificationResource.java
> +                kv("provider", SMARTPAY.getName()),
Done. There is no "notification_source" in LoggingKeys. 😱

2020-11-24 17:33 UTC, oswaldquek approved these changes

2020-11-24 17:34 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/webhook/resource/NotificationResource.java
> +                kv("provider", SMARTPAY.getName()),
Thanks. Yeah, might be a good idea to add it in pay-java-commons if you have the time. But I wouldn't want to block approving this PR because it's not in there right now.

2020-11-25 09:24 UTC, alexbishop1 commented
On the maximum line changes count, we don’t have any hard and fast rules because that would be inflexible. We just have guidelines. The guidelines are that in general try to keep PRs under 200 lines and if that’s not possible for some reason, under 500 lines. But it’s all context-dependent. For example, adding 500 lines of YAML configuration is different to changing 500 lines of complex logic. And if you do something like add a new class, you might have dozens of lines of imports and boilerplate that won’t tax the reviewer so shouldn’t really count.

Fundamentally, the most important thing is to keep PRs small and understandable by not changing too much at once while still ensuring each PR merge results in something releasable. The line count rules are just a guidelines to help meet that goal.

(I haven’t looked in any detail at the changes in this PR so I can’t comment if it’s too large or not.)

2020-11-25 11:30 UTC, merged