PP-7417: Service level test for valid 3ds flex credentials
alphagov/pay-connector pull request #2716
Opened 2020-12-01 15:59 UTC by oswaldquek

Service level test for the following two scenarios in PP-7417:
Scenario 1: working live account credentials
Scenario 3: working test account credentials

2020-12-01 16:49 UTC, alexbishop1 requested changes
Looks like a good start but I’m concerned the tests are a little too loose in terms of what they will allow.

2020-12-01 16:49 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationService.java
> +                    return response.getStatus() == HttpStatus.SC_OK;
Feel free to put some blank lines in this to break it up into logical parts.

2020-12-01 16:49 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationService.java
> +                }).get();
This `get()` is going to crash and burn if the gateway account isn’t there. Can we do something more graceful, even if it’s throwing an exception?

2020-12-01 16:49 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        when(invocationBuilder.post(any(Entity.class))).thenReturn(response);
Is there any way we can make this stubbing more specific? Right now, once the service has the gateway account, it could be making basically any request.

2020-12-01 16:49 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        when(worldpay3dsFlexJwtService.generateDdcToken(any(GatewayAccount.class), any(Worldpay3dsFlexCredentials.class), any(ZonedDateTime.class)))
We should be able to stub exact values of the gateway account and its credentials.

2020-12-01 16:54 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationService.java
> +                }).get();
On balance I thought leaving it as `get()` would be ok for now as I have the following tests to implement:
```
    @Test
    @Disabled
    void gateway_account_does_not_exist() {
        //TODO implement
    }

    @Test
    @Disabled
    void gateway_account_is_not_a_worldpay_account() {
        //TODO implement
    }
```
and I want to make PRs as small as possible. But I can just throw a RuntimeException for now if you prefer.

2020-12-01 17:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationService.java
> +                }).get();
Since it’s currently unused code, I’m happy with whatever approach you want to take.

2020-12-01 17:02 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        when(invocationBuilder.post(any(Entity.class))).thenReturn(response);
I do have a `verify(client).target(threeDsFlexDdcUrls.get(type));` in the test which resolves the `client.target` part. I can add a verification for the `invocationBuilder.post`. I'd rather do this than make the stubbing very specific as I like how clean the tests look currently as I don't want to pollute them with `when...thenReturn` lines.

2020-12-01 17:09 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        when(worldpay3dsFlexJwtService.generateDdcToken(any(GatewayAccount.class), any(Worldpay3dsFlexCredentials.class), any(ZonedDateTime.class)))
I think this will be difficult as the Worldpay3dsFlexJwtService is called with a `ZonedDateTime.now()`: 
```worldpay3dsFlexJwtService.generateDdcToken(GatewayAccount.valueOf(gatewayAccountEntity), flexCredentials, ZonedDateTime.now())```
And unfortunately everything needs to be mocked exactly or mocked with `any`.
I can rectify this by using a `verify` in the test.

2020-12-01 17:14 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        when(invocationBuilder.post(any(Entity.class))).thenReturn(response);
Yeah, it’s the actual POST body I’m most concerned about.

2020-12-01 17:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        when(worldpay3dsFlexJwtService.generateDdcToken(any(GatewayAccount.class), any(Worldpay3dsFlexCredentials.class), any(ZonedDateTime.class)))
You have to use matchers for every argument but they don’t all need to be `any(…)`. You should be able to do something like this:

```java
when(worldpay3dsFlexJwtService.generateDdcToken(eq(exactGatewayAccount), eq(exactWorldpay3dsFlexCredentials), any(ZonedDateTime.class)))
```

2020-12-01 17:51 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        when(worldpay3dsFlexJwtService.generateDdcToken(any(GatewayAccount.class), any(Worldpay3dsFlexCredentials.class), any(ZonedDateTime.class)))
Ugh, it doesn't work :(
However this does ```verify(worldpay3dsFlexJwtService).generateDdcToken(eq(GatewayAccount.valueOf(gatewayAccount)), eq(flexCredentials), any(ZonedDateTime.class));```

2020-12-01 17:56 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        when(invocationBuilder.post(any(Entity.class))).thenReturn(response);
Unfortunately the Entity class doesn't have a nice equals method so I've gone with
```
        verify(invocationBuilder).post(entityArgumentCaptor.capture());
        assertEquals(((Form) entityArgumentCaptor.getValue().getEntity()).asMap(),
                new MultivaluedHashMap<String, String>() {{
                    add("JWT", DDC_TOKEN);
                }});
        assertEquals(entityArgumentCaptor.getValue().getMediaType(), MediaType.APPLICATION_FORM_URLENCODED_TYPE);

```

2020-12-01 17:57 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationService.java
> +                }).get();
I've made it throw a RuntimeException for now.

2020-12-02 09:46 UTC, alexbishop1 requested changes
Looks good but can we have another go at trying use stubbing instead of verification? Happy to lend a hand when I have a free moment.

2020-12-02 09:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccount.java
> +        return new EqualsBuilder()
`Objects.equals(…)` does basically the same thing and is part of the standard library.

2020-12-02 09:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccount.java
> +        return new HashCodeBuilder(17, 37)
`Objects.hash(…)` does basically the same thing and is part of the standard library.

2020-12-02 09:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        verify(client).target(threeDsFlexDdcUrls.get(type));
I’m amazed we have to do this. Surely ` when(client.target(threeDsFlexDdcUrls.get(type))).thenReturn(webTarget)` works?

2020-12-02 10:00 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        verify(client).target(threeDsFlexDdcUrls.get(type));
I mentioned before about not liking polluting code with `when...thenReturn` lines, but putting in `when(client.target(threeDsFlexDdcUrls.get(type))).thenReturn(webTarget)` doesn't look so bad actually, so I will do that.

2020-12-02 10:05 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/Worldpay3dsFlexCredentialsValidationServiceTest.java
> +        when(worldpay3dsFlexJwtService.generateDdcToken(any(GatewayAccount.class), any(Worldpay3dsFlexCredentials.class), any(ZonedDateTime.class)))
I'm not sure why this work for me yesterday but it does now 🤷‍♂️

2020-12-02 12:01 UTC, alexbishop1 approved these changes, later dismissed

2020-12-02 12:42 UTC, alexbishop1 approved these changes

2020-12-02 13:47 UTC, merged