PP-7417: Validation for Worldpay 3DS Flex Jwt Mac Key parameter
alphagov/pay-connector pull request #2730
Opened 2020-12-04 16:35 UTC by oswaldquek

2020-12-04 17:05 UTC, alexbishop1 requested changes
Looks fine apart from the non-deterministic tests.

2020-12-04 17:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/validation/Worldpay3dsFlexJwtMacKeyValidatorTest.java
> +        IntStream.range(1, 20).forEach(i -> assertTrue(validator.isValid(UUID.randomUUID().toString(), null)));
Really not sure about having non-deterministic tests.

2020-12-04 17:17 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gatewayaccount/validation/Worldpay3dsFlexJwtMacKeyValidatorTest.java
> +        IntStream.range(1, 20).forEach(i -> assertTrue(validator.isValid(UUID.randomUUID().toString(), null)));
I wanted to convince myself lower cased UUIDs were always produced but happy to remove this.

2020-12-04 17:19 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gatewayaccount/validation/Worldpay3dsFlexJwtMacKeyValidatorTest.java
> +        IntStream.range(1, 20).forEach(i -> assertTrue(validator.isValid(UUID.randomUUID().toString(), null)));
Some people like non-deterministic tests to find edge cases which I'm not against.

2020-12-07 08:33 UTC, alexbishop1 requested changes
Just a couple of small test changes and I think this is good.

2020-12-07 08:33 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/validation/Worldpay3dsFlexJwtMacKeyValidatorTest.java
> +        assertTrue(validator.isValid(UUID.randomUUID().toString(), null));
I’m still sceptical of using randomness in the tests but I since I don’t think it’s likely we’ll have some valid values that pass and some valid values that fail, I’m OK with this.

2020-12-07 08:33 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/validation/Worldpay3dsFlexJwtMacKeyValidatorTest.java
> +    void test_for_valid_uppercase_UUID() {
Can we name this to indicate that upper-case values are considered invalid?

2020-12-07 08:33 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gatewayaccount/validation/Worldpay3dsFlexJwtMacKeyValidatorTest.java
> +    @ValueSource(strings = { "53f0917f101a442", "incorrect", "abcdef", "12345678901234567890123_" })
Can we have a couple of “near miss” invalid values here e.g. a UUID that’s 8-4-4-6-10 rather than 8-4-4-4-12, or a UUID that has the letter “h” in it?

2020-12-07 09:58 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gatewayaccount/validation/Worldpay3dsFlexJwtMacKeyValidatorTest.java
> +    @ValueSource(strings = { "53f0917f101a442", "incorrect", "abcdef", "12345678901234567890123_" })
Good shout, done.

2020-12-07 11:30 UTC, alexbishop1 approved these changes

2020-12-07 11:33 UTC, merged