PP-5640: Add exemption request to authorisation order
alphagov/pay-connector pull request #2738
Opened 2020-12-09 13:06 UTC by oswaldquek

An exemption request should be added to the authorisation order if:
- Worldpay gateway account has exemption_engine set to true in the
  worldpay_3ds_flex_credentials table
- the gateway account has 3-D Secure enabled

2020-12-09 16:51 UTC, alexbishop1 requested changes
Looks like it should do the job. Just a few small things.

2020-12-09 16:51 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilder.java
> +        private boolean exemptionEngine;
`exemptionEngineEnabled` maybe? Just to make the method names read more naturally.

2020-12-09 16:51 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                : false;
This can be rewritten as:

```java
boolean exemptionEngine = request.getGatewayAccount().isRequires3ds() &&
    Optional.ofNullable(request.getGatewayAccount().getWorldpay3dsFlexCredentials())
            .map(Worldpay3dsFlexCredentials::isExemptionEngine)
            .orElse(false);
```

However, I wonder if we actually need this flag to consider whether or not 3DS is enabled. Presumably it’s just going to be used inside the template and we can nest it inside a check that 3DS is enabled.

2020-12-09 16:51 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentials.java
> +    private boolean exemptionEngine;
Do we need to update the `equals(…)` and `hashCode()` methods here?

2020-12-09 16:51 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentials.java
> +        return exemptionEngine;
Looks like this could return null in some cases. Do we want that or should we default it to false?

2020-12-09 16:51 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +
Is it feasible to remove some of the duplication in these tests?

2020-12-09 17:03 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                : false;
It looks like the following works in the template:
```            
            <#if requires3ds && exemptionEngineEnabled>
                <exemption type="OP" placement="AUTHORISATION"/>
            </#if>
```

2020-12-09 17:06 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentials.java
> +        return exemptionEngine;
I'm not sure... I think it's the Worldpay3dsFlexCredentials that could be null, not the exemption engine flag which is by default false in the database?

2020-12-09 17:10 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilder.java
> +        private boolean exemptionEngine;
👍

2020-12-09 17:11 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +
Done

2020-12-09 17:11 UTC, oswaldquek commented
@alexbishop1 Thanks for the review. I've addressed the comments in a few commit to make viewing the changes easier. Happy to merge the commits if everything is ok.

2020-12-09 18:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentials.java
> +        return exemptionEngine;
The existing constructor will leave it as null if it’s invoked (maybe that constructor isn’t required any more).

2020-12-09 18:17 UTC, alexbishop1 requested changes
Looks good, just a couple of tiny things.

2020-12-09 18:17 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentialsEntity.java
> +    }
I think this could do with the `Enabled` treatment too.

2020-12-09 18:17 UTC, alexbishop1 commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +            </#if>
If this was moved a line up so it’s above the `</#if>` that closes the `<#if requires3ds>`, it could just be `<#if exemptionEngineEnabled>`.

2020-12-10 09:45 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentials.java
> +        return exemptionEngine;
Won't it be `false` by default?

2020-12-10 10:03 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentialsEntity.java
> +    }
Done

2020-12-10 10:04 UTC, oswaldquek commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +            </#if>
Done

2020-12-10 13:23 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentials.java
> +        return exemptionEngine;
Yeah, you’re right, it will. But is the constructor that doesn’t set it even needed now?

2020-12-10 13:42 UTC, alexbishop1 submitted a review, later dismissed
This looks good. Can you check if the three-arg variant of the `Worldpay3dsFlexCredentials` constructor can be removed? If so, please do that, otherwise I think this is good to go.

2020-12-10 14:13 UTC, oswaldquek commented
@alexbishop1 Strictly speaking the three-arg constructor can be removed. I didn't because it's used in a few places (mainly tests) so I thought it'd be convenient to leave it.
I've discovered that https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/gatewayaccount/model/Worldpay3dsFlexCredentialsEntity.java#L44-L50 can be removed though!

2020-12-10 15:01 UTC, alexbishop1 approved these changes
Looks good!

2020-12-10 15:02 UTC, merged