Pp 5641 scenario 2
alphagov/pay-connector pull request #2763
Opened 2020-12-16 14:22 UTC by oswaldquek

These commits fulfil scenario 2 of PP-5641.

2020-12-16 14:43 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                LOGGER.info(logMessage, structuredLoggingArguments);
This has been copied from CardAuthoriseService. I'd like to extract this out into a LoggerForSplunk class of some sort but that would done in another PR.

2020-12-17 18:02 UTC, alexbishop1 requested changes
Logic looks fine but I think we could try to encapsulate some of it a bit more.

2020-12-17 18:02 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        return Optional.ofNullable(exemptionResponseResult).map(r -> isBlank(r) ? null : exemptionResponseResult);
Java 11+ has an `isBlank()` method on `String`, so we can use that if we know the string isn’t null (which of course it won’t be here).

Also, we can use `filter(…)` and `Predicate.not(…)` here:

```java
return Optional.ofNullable(exemptionResponseResult).filter(not((String::isBlank)));
```

However, do we really think we’re going to get an `exemptionResponse` element with an blank `result` attribute? The docs at https://developer.worldpay.com/docs/wpg/scaexemptionservices/exemptionengine#exemption-response say there’s only three possible values, so I think we can assume it won’t happen.

2020-12-17 18:02 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +    private static final List<String> SOFT_DECLINE_EXEMPTION_RESPONSE_RESULTS = List.of("REJECTED", "OUT_OF_SCOPE");
A `Set` is probably more appropriate here (though it feels like we should be able to do all this with enums).

2020-12-17 18:02 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (response.getBaseResponse().isPresent()) {
Is there someone we can yank these 30 or so lines to a separate method or, even better, a separate class?

Ideally, we probably want it to look something like this:

```java
GatewayResponse<WorldpayOrderStatusResponse> response = worldpayAuthoriseHandler.authoriseWithPossibleExemption(request);
if (worldpayExemptionResponseFigurerOuterer.isSoftDecline()) {
    // Some logging stuff here?
    response = worldpayAuthoriseHandler.authoriseWithoutExemption(request);
}
return response;
```

2020-12-17 18:02 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (response.getBaseResponse().isPresent()) {
Should be able to use `ifPresent(…)` here.

2020-12-17 18:02 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                    SOFT_DECLINE_EXEMPTION_RESPONSE_RESULTS.contains(worldpayOrderResponse.getExemptionResponseResult().get())) {
A little gnarly. How about something like this?

```java
boolean lastEventIsRefused = worldpayOrderResponse.getLastEvent().map("REFUSED"::equals).orElse(false);
boolean exemptionResultIsRejectedOrOutOfScope = worldpayOrderResponse.getExemptionResponseResult()
            .map(SOFT_DECLINE_EXEMPTION_RESPONSE_RESULTS::contains)
            .orElse(false);

if (lastEventIsRefused && exemptionResultIsRejectedOrOutOfScope) {
    // etc. etc.
}
```

2020-12-17 18:02 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                // Used by Splunk saved search
This probably won’t be used in a saved search, at least not initially

2020-12-17 18:02 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                LOGGER.info(logMessage, structuredLoggingArguments);
Yeah, this is proliferating. As well `CardAuthoriseService`, we also have this in the Apple Pay and Google Pay authorisation code and probably somewhere else. We probably want a separate class we can just throw responses at to get logged whenever we deem it necessary.

2020-12-18 09:55 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (response.getBaseResponse().isPresent()) {
Logging aside (which I'm going to get rid in another PR), this is what it looks like now:
```
        GatewayResponse<WorldpayOrderStatusResponse> response = worldpayAuthoriseHandler.authorise(request);
        if (response.getBaseResponse().isPresent() && response.getBaseResponse().get().isSoftDecline()) {
            return worldpayAuthoriseHandler.authorise(request, true);
        }
        return response;
```

2020-12-18 09:57 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (response.getBaseResponse().isPresent()) {
I've now got it as 
```
        if (response.getBaseResponse().isPresent() && response.getBaseResponse().get().isSoftDecline()) {
            return worldpayAuthoriseHandler.authorise(request, true);
        }
```
which is easy to read. I'm not really sure about using `.ifPresent` for the sake of using it; sometimes I find it makes code more clunky to read.

2020-12-18 09:58 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                    SOFT_DECLINE_EXEMPTION_RESPONSE_RESULTS.contains(worldpayOrderResponse.getExemptionResponseResult().get())) {
I've put this all in `WorldpayOrderStatusResponse.isSoftDecline` now.

2020-12-18 09:59 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                LOGGER.info(logMessage, structuredLoggingArguments);
I'll leave this to another PR as I think there's enough going on this PR at the moment!

2020-12-18 10:04 UTC, oswaldquek commented
I still want to add some testing around soft declines as per the following spec from Worldpay:
<img width="706" alt="Screenshot 2020-12-18 at 10 03 34" src="https://user-images.githubusercontent.com/9698354/102601636-5a9a1500-4118-11eb-8a9a-37a2d5147101.png">

2020-12-18 17:32 UTC, alexbishop1 requested changes
Looks good. Just one thing about a test and a couple of other suggestions.

2020-12-18 17:32 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +    public boolean isSoftDecline() {
I’d not thought about putting the logic to determine if it’s a soft decline in `WorldpayOrderStatusResponse`. Good idea. (While I still think this class and its friends conflate being a representation of the actual response and our interpretation of it, this is what we have for now, so putting this new logic in here makes sense).

2020-12-18 17:32 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +                .orElse(false);
It’s a little confusing that `e` is repeated but means a different thing each time.

Could do this:

```java
return Optional.ofNullable(lastEvent)
        .filter("REFUSED"::equals)
        .flatMap(lastEvent -> Optional.ofNullable(exemptionResponseResult).map(SOFT_DECLINE_EXEMPTION_RESPONSE_RESULTS::contains))
        .orElse(false);
```

Or maybe just this:

```java
return Optional.ofNullable(lastEvent).map("REFUSED"::equals).orElse(false)
        && Optional.ofNullable(exemptionResponseResult).map(SOFT_DECLINE_EXEMPTION_RESPONSE_RESULTS::contains).orElse(false);
```

2020-12-18 17:32 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        return Optional.ofNullable(lastEvent).map(r -> r.isBlank() ? null : lastEvent);
I think I said in the last review that I don’t think we need to worry about `lastEvent` being a blank string.

2020-12-18 17:32 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (response.getBaseResponse().isPresent() && response.getBaseResponse().get().isSoftDecline()) {
If you really want to avoid `ifPresent(…)` (which I can see would be a bit of a pain because you want to return from the method but you’ll be stuck in the lambda), you can do this:

```java
if (response.getBaseResponse().map(WorldpayOrderStatusResponse::isSoftDecline).orElse(false)) {
  // …
}
```

Or possibly that but with a boolean local variable:

```java
boolean isSoftDecline = response.getBaseResponse().map(WorldpayOrderStatusResponse::isSoftDecline).orElse(false);

if (isSoftDecline) {
    // …
}
```

2020-12-18 17:32 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponseTest.java
> +    @ValueSource(strings = { "OUT_OF_SCOPE", "REJECTED", })
Stray comma here (not that it likely makes a difference).

2020-12-18 17:32 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(worldpayAuthoriseHandler).authorise(cardAuthRequest, true);
Shouldn’t need to verify if we’re stubbing.

2020-12-21 09:38 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        return Optional.ofNullable(lastEvent).map(r -> r.isBlank() ? null : lastEvent);
We do actually. Some contract tests fail (shouldBeAbleToSendAuthorisationRequestForMerchantUsing3dsWithoutAddress, submit3DS2FlexAuthRequest_requiresChallenge, shouldBeAbleToSendAuthorisationRequestForMerchantUsing3dsWithoutAddress) because it appears there isn't a `lastEvent`. However as there's a new `WorldpayOrderStatusResponse.isSoftDecline` method I should be able to revert this.

2020-12-21 09:51 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        return Optional.ofNullable(lastEvent).map(r -> r.isBlank() ? null : lastEvent);
To be clear, I was querying that try to handle a blank `lastEvent` (e.g. `""` or `" "`) as opposed to a null `lastEvent` because there’s no such element in the XML response.

2020-12-21 10:06 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        return Optional.ofNullable(lastEvent).map(r -> r.isBlank() ? null : lastEvent);
Oh sorry, I misread. However I think wanting to return an Optional.empty if something is blank is a reasonable line of thinking and nothing too controversial.

2020-12-21 10:06 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (response.getBaseResponse().isPresent() && response.getBaseResponse().get().isSoftDecline()) {
I've gone with the former here.

2020-12-21 11:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        return Optional.ofNullable(lastEvent).map(r -> r.isBlank() ? null : lastEvent);
It’s not controversial if a blank `lastEvent` is actually a possibility but it doesn’t sound like it can be so I think it just adds a little extra complexity. Furthermore, if we have code to handle a blank `lastEvent` then it could make our future selves think that’s a possibility, which clouds our understanding of what Worldpay may respond with.

2020-12-21 11:41 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        return Optional.ofNullable(lastEvent).map(r -> r.isBlank() ? null : lastEvent);
> it could make our future selves think that’s a possibility, which clouds our understanding of what Worldpay may respond with.
Very valid point. But it's possible I might have seen that `isNotBlank` is used copiously in the `toString` method and took that as a hint. Anyway, if there's nothing else, can you approve the PR?

2020-12-21 12:17 UTC, alexbishop1 approved these changes

2020-12-21 12:17 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        return Optional.ofNullable(lastEvent).map(r -> r.isBlank() ? null : lastEvent);
Yeah, I’m not keen on how we use `isNotBlank(…)` in the `toString()`. I’m not going to hold approval for this PR on this.

2020-12-21 12:50 UTC, merged