PP-5642: Set exemption_3ds for a charge to EXEMPTION_NOT_REQUESTED
alphagov/pay-connector pull request #2782
Opened 2020-12-31 13:26 UTC by oswaldquek

Set exemption_3ds for a charge to EXEMPTION_NOT_REQUESTED if exemption engine
for the gateway account is not enabled. I.e., an authorisation request is made
without an exemption.

Also added an integration test which is useful to verify all the persistence
code has been wired correctly.

A ChargeDao is injected into WorldpayPaymentProvider and is used to update the
ChargeEntity. Unfortunately using a ChargeService caused a circular dependency
error because ChargesApiResource -> ChargeService -> PaymentProviders ->
WorldpayPaymentProvider -> ChargeService.

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2020-12-31 14:58 UTC, alexbishop1 requested changes
Looks along the right lines.

2020-12-31 14:58 UTC, alexbishop1 commented on .secrets.baseline
> -  "generated_at": "2020-12-16T14:18:37Z",
Curious we ended up with two of these!

2020-12-31 14:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +    private Exemption3ds exemption3ds;
Do we want this to appear in the response at this stage?

2020-12-31 14:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +    @Column(name = "exemption_3ds")
I think we want `@Enumerated(EnumType.STRING)` here or the value that’s persisted will be the ordinal of the enum.

2020-12-31 14:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (!WorldpayOrderBuilder.isExemptionEngineEnabled(request)) {
There’s a risk here that whether or not the Exemption Engine is enabled may change between when we record in the database and when we build the request. Can we avoid this? Perhaps we could calculate whether or not the Exemption Engine is enabled once and then pass it to `WorldpayAuthoriseHandler` and then down to `WorldpayOrderRequestBuilder`, which would respect that rather than doing its own check to see if the Exemption Engine is enabled.

2020-12-31 14:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            charge.setExemption3ds(EXEMPTION_NOT_REQUESTED);
We might want a test in `ChargeDaoIT` to check this roundtrips (similar to `shouldCreateNewChargeWithParityCheckStatus()`.

2020-12-31 15:28 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +    private Exemption3ds exemption3ds;
Technically this doesn't fulfil any acceptance criteria (even if I think we know we're going to need it in the future). This is here because it's useful to verify the `WorldpayCardResourceIT. should_set_exemption_not_requested_when_request_made_without_an_exemption` test which does pertain to the acceptance criteria. But I see you're in suggesting we create a test in the ChargeDaoIT which would obviate the need for this integration test so I could go with that.

2020-12-31 16:17 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> -
This was moved to WorldpayPaymentProviderTest. should_not_include_exemption_if_account_has_no_worldpay_3ds_flex_credentials

2020-12-31 16:17 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> -    void should_not_include_exemption_element_if_account_has_exemption_engine_set_to_false() throws Exception {
This was moved to WorldpayPaymentProviderTest. should_not_include_exemption_if_account_has_exemption_engine_set_to_false

2020-12-31 16:18 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> -    void should_not_include_exemption_element_if_account_has_exemption_engine_set_to_true_but_the_authorisation_is_made_in_response_to_a_soft_decline() throws Exception {
This is equivalently tested in WorldpayPaymentProviderTest. should_retry_without_exemption_flag_when_authorising_with_exemption_flag_results_in_soft_decline so could be deleted

2020-12-31 16:19 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> -    void should_include_exemption_element_if_account_has_exemption_engine_set_to_true() throws Exception {
This was moved to WorldpayPaymentProviderTest .should_include_exemption_if_account_has_exemption_engine_set_to_true.

2020-12-31 16:20 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> -    void should_not_include_exemption_element_if_account_has_exemption_engine_set_to_true_but_3ds_is_not_enabled() throws Exception {
Moved to WorldpayPaymentProviderTest .should_not_include_exemption_if_account_has_exemption_engine_set_to_true_but_3ds_is_not_enabled

2020-12-31 16:21 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (!WorldpayOrderBuilder.isExemptionEngineEnabled(request)) {
This sounds sensible. However what seemed like a simple idea resulted in a larger commit than expected: https://github.com/alphagov/pay-connector/pull/2782/commits/b5284e0dca74f7ebf70997f5446f272715cd2f87. Happy reviewing!

2020-12-31 16:21 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +    @Column(name = "exemption_3ds")
Fixed

2020-12-31 16:23 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +    private Exemption3ds exemption3ds;
Deleted this as due to the new `ChargeDaoIT.should_update_charge_with_exemption_3ds` test.

2020-12-31 16:24 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            charge.setExemption3ds(EXEMPTION_NOT_REQUESTED);
New `ChargeDaoIT.should_update_charge_with_exemption_3ds` test added.

2020-12-31 16:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            charge.setExemption3ds(EXEMPTION_NOT_REQUESTED);
I think I've never written a Dao test during my time in Pay!

2021-01-04 16:21 UTC, alexbishop1 reviewed
This looks pretty good. Left some comments but I’m not sure any of them will actually require changes (hence neither approving nor requesting changes).

One other thing that might be worth considering is changing the `WorldpayAuthoriseHandler.authorise(…)` so that rather than being one method with a boolean parameter to indicate whether the Exemption Engine should be used or not, it’s two methods called `authoriseWithExemption(…)` and `authoriseWIthoutExemption(…)` (say). But that might be something to explore in a follow-up PR.

2021-01-04 16:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        }
I wonder if ultimately we’ll end up doing this after the request has been made because that’s when we’ll be updating the flag if we did request an exemption (because we’ll only know if it’s honoured or not when we have the response). But it’s fine here for now.

2021-01-04 16:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +    void should_include_exemption_element() throws Exception {
I think the `should_include_exemption_element_if_account_has_exemption_engine_set_to_true` name was clearer.

2021-01-04 16:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +    void should_not_include_exemption_element() throws Exception {
I’m a bit confused about what’s happening here. We have 3DS and the Exemption Engine enabled but we’re not sending an exemption?

2021-01-04 16:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    void should_set_exemption_not_requested_when_request_made_without_an_exemption() throws Exception {
I wonder if perhaps this could be combined into the previous tests, so that if we expect an exemption not to be requested we both check that request and that we record that fact.

2021-01-04 16:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        assertEquals(chargeDaoArgumentCaptor.getValue().getExemption3ds(), EXEMPTION_NOT_REQUESTED);
Another way to do this might be use in-order verification to check the `setExemption3ds(…)` and `merge(…)` methods are called in that order (but this way is also fine).

2021-01-04 16:24 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        }
This is fine for now. The next few scenarios (which I've already started working on) will force a move of this code block till after the request has been made.

2021-01-04 16:26 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +    void should_not_include_exemption_element() throws Exception {
Yes it's because of the `false` in 
```
worldpayAuthoriseHandler.authorise(new CardAuthorisationGatewayRequest(chargeEntityFixture.build(), getValidTestCard()), false);
```
I can see this is a bit confusing; I like the suggestion of having the `authoriseWithExemption(…)` and `authoriseWithoutExemption(…)` so will update this.

2021-01-04 16:32 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        assertEquals(chargeDaoArgumentCaptor.getValue().getExemption3ds(), EXEMPTION_NOT_REQUESTED);
I think I'll leave this as is.

2021-01-04 16:42 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +    void should_include_exemption_element() throws Exception {
Done

2021-01-04 16:42 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +    void should_not_include_exemption_element() throws Exception {
I've updated the signatures to be `authoriseWithExemption(…)` and `authoriseWithoutExemption(…)` so hopefully this is clearer now.

2021-01-04 16:43 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    void should_set_exemption_not_requested_when_request_made_without_an_exemption() throws Exception {
Good shout; done.

2021-01-06 11:05 UTC, alexbishop1 approved these changes

2021-01-06 11:06 UTC, merged