PP-5642: Exemption honoured, rejected and out-of-scope scenarios
alphagov/pay-connector pull request #2788
Opened 2021-01-06 12:53 UTC by oswaldquek

Set charge's exemption_3ds=EXEMPTION_HONOURED if exemption was honoured.
Set charge's exemption_3ds=EXEMPTION_REJECTED if exemption was rejected.
Set charge's exemption_3ds=EXEMPTION_OUT_OF_SCOPE if exemption was out of
scope.

2021-01-06 14:42 UTC, alexbishop1 requested changes
Looks like this should work. I’ve made some suggestions, at least some of which might be feasible.

I’m also becoming a bit concerned that the `authorise(…)` method in `WorldpayPaymentProvider` is getting a bit big (and the class’s test class is now over 500 lines). It might be worth exploring if we can extract some of its functionality into a separate service (which would sit between `WorldpayPaymentProvider` and `WorldpayAuthoriseHandler`).

2021-01-06 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            if (response.getBaseResponse().get().getExemptionResponseResult().orElse("").equals("REJECTED")) {
Might be possible to avoid doing `get()` on the `Optional` by changing the lines above:

```java
response.getBaseResponse().ifPresent(baseResponse -> {
    if (baseResponse.isSoftDecline()) {
       // etc. etc.
   }
});
```

Also, rather than `getExemptionResponseResult().orElse("").equals("REJECTED"))`, we can do `getExemptionResponseResult().map("REJECTED"::equals).orElse(false)`.

2021-01-06 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            exemption3ds = EXEMPTION_HONOURED;
Rather than having `exemption3ds` set on several different lines, it might be feasible to do it once by replacing `responseIsHonoured(…)` with a method that calculates it all cases using a method signature like this:

```java
private Optional<Exemption3ds> determineExemption(boolean exemptionEngineEnabled, GatewayResponse<WorldpayOrderStatusResponse> response) {
    // etc. etc.
}
```

The `Optional` being because we won’t be able get anything if there was an error and there’s nothing meaningful in the response body.

Then we might be able to call it and update the charge in one shot:

```java
determineExemption(exemptionEngineEnabled, response).ifPresent(exemption3ds -> updateChargeWithExemption3ds(exemption3ds, request.getCharge()));
```

2021-01-06 14:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +    private Boolean responseIsHonoured(GatewayResponse<WorldpayOrderStatusResponse> response) {
I think this name needs “exemption” in it somewhere and it should probably return a primitive `boolean` rather than an autoboxed `Boolean`.

2021-01-06 14:42 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        var secondResponse = getGatewayResponse(WORLDPAY_AUTHORISATION_SUCCESS_RESPONSE);
These might possibly be clearer if they’re inlined to where they’re used.

2021-01-06 14:42 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(mockAppender, times(2)).doAppend(loggingEventArgumentCaptor.capture());
Why did this change?

2021-01-06 16:32 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            if (response.getBaseResponse().get().getExemptionResponseResult().orElse("").equals("REJECTED")) {
I'm ambivalent to using 
```
response.getBaseResponse().ifPresent(baseResponse -> {
    if (baseResponse.isSoftDecline()) {
       // etc. etc.
   }
});
```
as it adds more lines to compared to
```
            if (response.getBaseResponse().get().getExemptionResponseResult().map("REJECTED"::equals).orElse(false)) {
                updateChargeWithExemption3ds(EXEMPTION_REJECTED, request.getCharge());
            } else if (response.getBaseResponse().get().getExemptionResponseResult().map("OUT_OF_SCOPE"::equals).orElse(false)) {
                updateChargeWithExemption3ds(EXEMPTION_OUT_OF_SCOPE, request.getCharge());
            }

```
and I don't think it adds to readability.

2021-01-06 16:37 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            exemption3ds = EXEMPTION_HONOURED;
I would have liked to have a method that calculates all cases and call it once near the end of `WorldpayPaymentProvider.authorise` too. However I don't think this is feasible (without introducing new variables) as we need to calculate the `exemption_3ds` value straight away after a soft decline and before the retry as the retry assigns the result to the `GatewayResponse<WorldpayOrderStatusResponse> response`.

2021-01-06 16:41 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +    private Boolean responseIsHonoured(GatewayResponse<WorldpayOrderStatusResponse> response) {
I've gotten rid of this method.

2021-01-06 16:43 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(mockAppender, times(2)).doAppend(loggingEventArgumentCaptor.capture());
Because in addition to the logs that are being tested in this test, `Updated exemption_3ds of charge to EXEMPTION_REJECTED` as well.

2021-01-06 16:44 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(mockAppender, times(2)).doAppend(loggingEventArgumentCaptor.capture());
Perhaps I could merge `should_set_exemption_rejected_when_request_made_with_an_exemption` into this test as well?

2021-01-06 16:48 UTC, oswaldquek commented
@alexbishop1 I've committed some [changes](https://github.com/alphagov/pay-connector/pull/2788/commits/079fdfad47973af8e703ca815549c8a8d6adf534) that hopefully make the code cleaner. 

I don't think `WorldpayPaymentProvider.authorise` is that bad actually? I don't think it's hard to read and a large chunk of the lines is taken up by the logging:
```
           var authorisationRequestSummary = generateAuthorisationRequestSummary(request.getCharge(), request.getAuthCardDetails());

            authorisationLogger.logChargeAuthorisation(
                    LOGGER,
                    authorisationRequestSummary,
                    request.getCharge(),
                    authorisationService.extractTransactionId(request.getCharge().getExternalId(), response)
                            .orElse("missing transaction ID"),
                    response,
                    request.getCharge().getChargeStatus(),
                    request.getCharge().getChargeStatus());
```

2021-01-07 10:38 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            if (response.getBaseResponse().get().getExemptionResponseResult().orElse("").equals("REJECTED")) {
It’s really the `get()` I’m worried about. It could still be done with `if`/`else` by using `flatMap()`:

```java
if (response.getBaseResponse().flatMap(WorldpayOrderStatusResponse::getExemptionResponseResult).map("REJECTED"::equals).orElse(false)) {
    updateChargeWithExemption3ds(EXEMPTION_REJECTED, request.getCharge());
} else if (response.getBaseResponse().flatMap(WorldpayOrderStatusResponse::getExemptionResponseResult).map("OUT_OF_SCCOPE"::equals).orElse(false)) {
    updateChargeWithExemption3ds(EXEMPTION_OUT_OF_SCOPE, request.getCharge());
}
```

2021-01-07 12:48 UTC, alexbishop1 requested changes
I’ve got a couple of suggestions that I think could simplify this a bit further.

2021-01-07 12:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                            .ifPresent(exemption3ds -> updateChargeWithExemption3ds(exemption3ds, request.getCharge())));
This could be:

```java
response.getBaseResponse()
        .flatMap(worldpayOrderStatusResponse -> determineExemption(exemptionEngineEnabled, worldpayOrderStatusResponse))
        .ifPresent(exemption3ds -> updateChargeWithExemption3ds(exemption3ds, request.getCharge()));
```

2021-01-07 12:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        });
We could remove a little bit of duplication by doing something like this:

```java
response.getBaseResponse().flatMap(WorldpayOrderStatusResponse::getExemptionResponseResult).ifPresent(exemption3ds -> {
    if ("REJECTED".equals(exemption3ds)) {
        updateChargeWithExemption3ds(EXEMPTION_REJECTED, request.getCharge());
    } else if ("OUT_OF_SCOPE".equals(exemption3ds)) {
        updateChargeWithExemption3ds(EXEMPTION_OUT_OF_SCOPE, request.getCharge());
    }
});
```

A more radical idea might be to dispense with this method altogether and replace the `updateChargeExemptionForSoftDecline(request, response);` line above (line 171 as I write this) with this:

```java
response.getBaseResponse().flatMap(WorldpayOrderStatusResponse::getExemptionResponseResult).ifPresent(exemption3ds -> {
    if ("REJECTED".equals(exemption3ds)) {
        updateChargeWithExemption3ds(EXEMPTION_REJECTED, request.getCharge());
    } else if ("OUT_OF_SCOPE".equals(exemption3ds)) {
        updateChargeWithExemption3ds(EXEMPTION_OUT_OF_SCOPE, request.getCharge());
    }
});
```

2021-01-07 12:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +    }
It makes me a little sad that this method can’t handle determining the exemption for a soft decline as well. I think we can make it do it by changing the method signature a little bit:

```java
private Optional<Exemption3ds> determineExemption(boolean exemptionEngineEnabled, GatewayResponse<WorldpayOrderStatusResponse> response) {
    if (!exemptionEngineEnabled) {
        return Optional.of(EXEMPTION_NOT_REQUESTED);
    }

    return response.getBaseResponse().flatMap(WorldpayOrderStatusResponse::getExemptionResponseResult).map(exemption3ds -> {
        switch (exemption3ds) {
            case "HONOURED":
                return EXEMPTION_HONOURED;
            case "REJECTED":
                return EXEMPTION_REJECTED;
            case "OUT_OF_SCOPE":
                return EXEMPTION_OUT_OF_SCOPE;
            default:
                return null;
        }
    });
}
```

Then we call it immediately after the `worldpayAuthoriseHandler.authoriseWithExemption(…)` or `worldpayAuthoriseHandler.authoriseWithoutExemption(…)` call (line 168 as I write this):

```java
var exemption3ds = determineExemption(exemptionEngineEnabled, response).orElse(null);
```

Then later on we can just do things like `if (exemption3ds == Exemption3ds.REJECTED)` etc.

2021-01-07 12:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +    }
Actually, come to think of it, I don’t think we have a hard requirement to store `REJECTED` or `OUT_OF_SCOPE` only if it’s a soft decline (it might even be desirable to store it in other cases, such as if the payment is `AUTHORISED` but the exemption is `OUT_OF_SCOPE` — if such a thing is even possible). So I think we could actually make this method do the updating itself:

```java
private void storeExemption(boolean exemptionEngineEnabled, CardAuthorisationGatewayRequest request, GatewayResponse<WorldpayOrderStatusResponse> response) {
    if (!exemptionEngineEnabled) {
        updateChargeWithExemption3ds(Exemption3ds.EXEMPTION_NOT_REQUESTED);
    } else {
        response.getBaseResponse().flatMap(WorldpayOrderStatusResponse::getExemptionResponseResult).ifPresent(exemption3ds -> {
            switch (exemption3ds) {
                case "HONOURED":
                    updateChargeWithExemption3ds(Exemption3ds.HONOURED);
                    break;
                case "REJECTED":
                    updateChargeWithExemption3ds(Exemption3ds.EXEMPTION_REJECTED);
                    break;
                case "OUT_OF_SCOPE":
                    updateChargeWithExemption3ds(Exemption3ds.EXEMPTION_OUT_OF_SCOPE);
                    break;
                default:
                    // We asked for an exemption but the response did not say anything about it
             }
      	});
    }
}
```

2021-01-08 10:50 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            if (response.getBaseResponse().get().getExemptionResponseResult().orElse("").equals("REJECTED")) {
I don't think it's possible to establish a response is a soft decline and having `response.getBaseResponse().get()` to fail.

2021-01-08 10:54 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                            .ifPresent(exemption3ds -> updateChargeWithExemption3ds(exemption3ds, request.getCharge())));
Personally, I value readability of code more than using functional idioms. I definitely like seeing how people would do things differently! In this case I find this more difficult to read because
* I think in terms of `if...else...if...else`
* I always have to google what flatMap means whenever I see it being used
* It's not obvious to deduce what the type of `response.getBaseResponse().flatMap(worldpayOrderStatusResponse -> determineExemption(exemptionEngineEnabled, worldpayOrderStatusResponse))` is

2021-01-08 10:55 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +    }
I like this idea.

2021-01-08 15:07 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +    }
I've implemented this method and called it `calculateAndStoreExemption`.

2021-01-08 15:07 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                            .ifPresent(exemption3ds -> updateChargeWithExemption3ds(exemption3ds, request.getCharge())));
Well, this code block disappeared with the new `calculateAndStoreExemption` method.

2021-01-08 15:08 UTC, oswaldquek commented
@alexbishop1 This is ready for review again. Thanks.

2021-01-08 16:11 UTC, alexbishop1 requested changes
Looks good: I think centralising storing the exemption makes it more straightforward. Just a couple of a tiny suggestions.

2021-01-08 16:11 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            calculateAndStoreExemption(exemptionEngineEnabled, request.getCharge(), response);
I think we can move this out to immediately after the first authorisation request (line 168 as I write this). That way we wouldn’t need the `else` block.

2021-01-08 16:11 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                                "charge_external_id={}", exemption3ds, charge.getExternalId());
I wonder if we should log this at a higher level because I don’t think we should get any values we don’t expect (as opposed to no value, which won’t reach this line).

2021-01-08 16:22 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +            calculateAndStoreExemption(exemptionEngineEnabled, request.getCharge(), response);
Good shout, fixed.

2021-01-08 16:22 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                                "charge_external_id={}", exemption3ds, charge.getExternalId());
I've logged this at WARN.

2021-01-08 16:47 UTC, alexbishop1 approved these changes
Good stuff!

2021-01-08 16:49 UTC, merged