PP-1282 backward compatible fix for potential break in payment confirmation view during deployment
alphagov/pay-connector pull request #290
Opened 2016-11-11 09:04 UTC by kakumara

## WHAT
Note: the scenario can only happen during production deployment where a card authorisation has happened in the connector node with `release 76` version while confirmation details page data load is happening with a `release 77` version of the connector node. 

 - Added a @Deprecated `ConfirmationDetailsEntity` object which be loaded if a matching record exists from `confirmation_details` table and will be used to populate Frontend charge response if its not null.

2016-11-11 09:17 UTC, kakumara commented
rebuild

2016-11-11 09:39 UTC, kakumara commented
rebuild

2016-11-11 15:47 UTC, ckalista commented
Code review completed - looking good!

2016-11-14 10:38 UTC, imranbohoran requested changes

2016-11-14 10:38 UTC, imranbohoran commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> +
As discussed, for the scenario we are trying to handle (one node having the new code and the confirmation landing on a node that still has the old code), this change will not make any difference as this is the new code. As you suggested the saving to the new and old structure seems the safest way to get this out in a backward compatible way.

2016-11-14 11:17 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> +
Good catch! 👍  
Fixed by duplicating card details in old `confirmation_details` table.

2016-11-14 11:51 UTC, imranbohoran approved these changes

2016-11-14 11:52 UTC, imranbohoran commented
👍

2016-11-14 11:52 UTC, merged