PP-7977 Add Administrator Endpoints
alphagov/pay-connector pull request #2919
Opened 2021-05-04 15:03 UTC by rorymalcolm

- Move the adminstrator tasks endpoints away from the admin port to the default port

- Add resource tests to ensure that the functionality remains the same

- Remove the unused threadpool limitation on execution

- Remove extant admin task workers and services

2021-05-04 16:20 UTC, oswaldquek requested changes
Haven't reviewed the test code yet as there are two comments for the non-test code.

2021-05-04 16:20 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/events/HistoricalEventEmitterService.java
> +    private Long getDoNotRetryEmitUntilDuration(Map<String, List<String>> parameters) {
This method appears to be unused.

2021-05-04 16:20 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/events/HistoricalEventEmitterService.java
> +    public void emitRefundEventsOnlyById(Long startId, OptionalLong maybeMaxId, Long doNotRetryEmitUntilDuration) {
Does this `emitRefundEventsOnlyById` method need to be called from a corresponding method `EmittedEventResource`? Can't see this at the moment.

2021-05-05 14:01 UTC, rorymalcolm commented on src/main/java/uk/gov/pay/connector/events/HistoricalEventEmitterService.java
> +    public void emitRefundEventsOnlyById(Long startId, OptionalLong maybeMaxId, Long doNotRetryEmitUntilDuration) {
fixed

2021-05-05 14:01 UTC, rorymalcolm commented on src/main/java/uk/gov/pay/connector/events/HistoricalEventEmitterService.java
> +    private Long getDoNotRetryEmitUntilDuration(Map<String, List<String>> parameters) {
fixed

2021-05-05 15:06 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/events/resource/EmittedEventResource.java
> +        RecordType recordType = maybeRecordType == null ? CHARGE : RecordType.fromString(maybeRecordType);
What happens if `maybeRecordType` isn't one of `charge` or `refund`? Not sure if we can the `maybeRecordType` parameter in the method to be `RecordType` but worth exploring.

2021-05-05 15:07 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/report/resource/ParityCheckerResource.java
> +                                @QueryParam("parity_check_status") String mayBeParityCheckStatus,
`maybeParityCheckStatus`

2021-05-05 15:07 UTC, rorymalcolm commented on src/main/java/uk/gov/pay/connector/events/resource/EmittedEventResource.java
> +        RecordType recordType = maybeRecordType == null ? CHARGE : RecordType.fromString(maybeRecordType);
It would throw an exception on the `fromString` parsing, this is an internal only endpoint so shouldn't have random stuff thrown at it, I'm not 100% sure on dropwizard arguments to resource methods but can check

2021-05-05 15:29 UTC, oswaldquek requested changes
Couple of comments.
I also think it would be good to have javadoc on the resource classes/methods. But this can be done in another PR.

2021-05-05 15:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/report/resource/ParityCheckerResource.java
> +                                @QueryParam("parity_check_status") String mayBeParityCheckStatus,
`maybeParityCheckStatus`

2021-05-05 15:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/events/HistoricalEventEmitterService.java
>      private long maxId;
I know you didn't write this code but personally I'd like to see maxId be made into a local variable in the method. I know this will work here as dropwizard spins up one class of `HistoricalEventEmitterService` and `EmittedEventResource` per incoming request but I would rather avoid us needing to know this information. Take it or leave it though! I'll make this change if you decide to skip this.

2021-05-05 15:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/events/resource/EmittedEventResource.java
> +        RecordType recordType = maybeRecordType == null ? CHARGE : RecordType.fromString(maybeRecordType);
Given this is an internal only endpoint I'm happy to forego coding validations here. But I think it would be great to have a proper response message.

2021-05-05 15:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/report/ParityCheckerService.java
>      private long maxId;
This maxId can be made a local variable easily. We should do that here.

2021-05-05 15:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/tasks/RecordType.java
> +                    StringUtils.equals(type.getValue().toUpperCase(), recordTypeParam)) {
This could be simplified to 
```
if (type.name().equals(recordTypeParam.toUpperCase()))
```

2021-05-05 15:29 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +        historicalEventEmitterService.emitHistoricEventsById(1L, OptionalLong.empty(), 1L);
The test is `executeForRefundsOnly_shouldNotProcessIfRefundRecordDoesNotExist` but the method being tested is `emitHistoricEventsById`, not `emitRefundEventsOnlyById`.

2021-05-05 15:29 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/events/resource/EmittedEventResourceTest.java
> +    public void shouldReturn200OnHistorictEventById() {
typo - should be `shouldReturn200onHistoricEventById`

2021-05-05 15:29 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/events/resource/EmittedEventResourceTest.java
> +        assertThat(response.getStatus(), is(Status.INTERNAL_SERVER_ERROR.getStatusCode()));
I know this is an internal microservice but can we make this return 400 bad request please. Sorry to be annoying.

2021-05-05 15:29 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/report/resource/ParityCheckerResourceTest.java
> +        assertThat(response.getStatus(), is(Response.Status.INTERNAL_SERVER_ERROR.getStatusCode()));
should return 400 bad request

2021-05-06 10:57 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +    public void emitHistoricEventsById_shouldNotProcessIfRefundRecordDoesNotExist() {
I think this should be `emitHistoricEventsById_shouldNotProcessIfRecordDoesNotExist`. It doesn't matter whether if it's a charge or refund record.

2021-05-06 10:58 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/events/resource/EmittedEventResourceTest.java
> +    public void shouldReturn200onHistorictEventById() {
Still a typo here `Historict`

2021-05-06 11:10 UTC, oswaldquek approved these changes

2021-05-06 12:30 UTC, merged