PP-1079 - Enabling Smartpay Refund
alphagov/pay-connector pull request #293
Opened 2016-11-14 17:34 UTC by kakumara

## WHAT
- Pushed the `getTransactionId` method down the `BaseResponse` hierarchy as not
       all gateway responses need this method such as for instance refund responses.
    - `getTransactionId` method added in `BaseAuthoriseResponse` as needed by all
       authorisation responses.
    - Introduced `BaseRefundResponse` used as base class model for all refund responses.
       Note that not all gateway providers return a refund reference. For instance for Worldpay
       since we generates the reference upfront and submit alongside the refund request, the
       provider doesn't return it back to us as part of the response hence `getReference` has
       been modeled as an Optional.
    - Added correct mappings for the XML(Un)marshaller to be able to (de-)serialise refund
       request/responses from Smartpay.
    - New reference field in `RefundEntity` which becomes the reference used to reconsile
       refund notifications with the original refund request orders.
    - Database mapping updated to add a reference field to the refund database table and also
       migrated existing refunds that have the reference field prepolulated with external refund id.
    - The refund lookup during notification handling is now based on the reference instead
       of the refund external id.
    - Introduced a new `generateRefundReference` method which all payment provider must
       supply their own implementation depending wether or not the provider is responsible
       to generate the reference upfront.
    - `ChargeRefundService` slightly changed the way refund requests are being issued to
       accomodate Smarpay which generates its own reference for the refunds that we want
       to capture for later on during reconsiliation when we receive notifications.
    - `NotificationService` was updated to lookup refunds based on their reference rather than
       external refund id.
    - Removed restriction that was put in place for MVP that prevented from issuing refunds for
       Smartpay.

2016-11-15 09:44 UTC, kakumara commented
rebuild

2016-11-15 10:19 UTC, kakumara commented
rebuild

2016-11-15 10:43 UTC, kakumara commented
rebuild

2016-11-15 11:45 UTC, heathd commented
What is the plan for `externalId` on `Refund`? Will that continue to be used as well as `reference`? or will it be removed?

2016-11-15 14:11 UTC, rauligs requested changes
👍  LGTM. Only two minor suggestions.

2016-11-15 14:11 UTC, rauligs commented on src/main/java/uk/gov/pay/connector/service/ChargeRefundService.java
> +            Supplier<String> referenceF = () -> {
Can these be created as two methods (one per supplier). They are suppliers which are immediately consumed.

2016-11-15 14:11 UTC, rauligs commented on src/test/java/uk/gov/pay/connector/it/resources/worldpay/WorldpayRefundITest.java
> +        assertThat(refundsFoundByChargeId, hasItems(aRefundMatching(refundId, is(notNullValue()), defaultTestCharge.getChargeId(), refundAmount, "REFUND SUBMITTED")));
At least in the happy path scenario, is it possible to assert that refund externalId is same as the reference?

2016-11-16 09:34 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/ChargeRefundService.java
> +            Supplier<String> referenceF = () -> {
👍  fair point

2016-11-16 09:55 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/it/resources/worldpay/WorldpayRefundITest.java
> +        assertThat(refundsFoundByChargeId, hasItems(aRefundMatching(refundId, is(notNullValue()), defaultTestCharge.getChargeId(), refundAmount, "REFUND SUBMITTED")));
Its already there is you see the the matcher. (see RefundMatcher.java)

2016-11-16 11:24 UTC, kakumara commented
@heathd re: comment.
AFAIK there is no plan. This field can be used in anyway we want. But I think it better to have the 2 fields, given that it is meant for `merchant's transaction reference` which could be interpreted as a reference from a government department that integrate with us. If they send us one we can pass it to payment gateway if it helps reconciliation or similar.

Generally, `external_id` is something we introduced globally (beyond refund) as an id from GOV.UK Pay for our clients. They were meant to hide the primary keys of our tables. It was just convenient to send it as merchant-reference in the refunds case .

2016-11-16 14:29 UTC, heathd commented
👍  looks good to me

We should make sure that Till is aware that although this is safe to ship to production and that technically it enables smartpay refunds to work, we're not ready to really do smartpay refunds in production until we have made the changes to properly record PSP references throughout the lifecycle of the refund.

2016-11-16 14:29 UTC, merged