PP-8125 - Update Stripe notifications to search gateway_account_credentials
alphagov/pay-connector pull request #3014
Opened 2021-06-16 11:59 UTC by nimalank7

Description:
- When a Stripe payout notification is processed we want to search the gateway_account_credentials table for the credentials before proceeding
- An additional check is added to PayoutEmitterService and PayoutReconcileProcess to verify whether the GatewayAccountCredentialsEntity exists then checking if the GatewayAccountEntity exists before proceeding

2021-06-17 16:07 UTC, kbottla submitted a review, later dismissed
LGTM!

2021-06-23 15:47 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/payout/PayoutReconcileProcess.java
> +                .orElseThrow(() -> new RuntimeException(format("Gateway account credentials with Stripe connect account ID [%s] not found.", stripeAccountId)));
we could add a service method to get gateway account for credential. This method will become much simpler

```
private String getStripeApiKey(String stripeAccountId) {
        GatewayAccountEntity gatewayAccountEntity = gatewayAccountCredentialsService.findGatewayAccountForCredentialKeyAndValue(
                StripeCredentials.STRIPE_ACCOUNT_ID_KEY, stripeAccountId);
        
        return gatewayAccountEntity.isLive() ? stripeGatewayConfig.getAuthTokens().getLive() : stripeGatewayConfig.getAuthTokens().getTest();
    }
```

2021-06-23 15:47 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/payout/PayoutEmitterService.java
> +                throw new GatewayAccountNotFoundException(format("Gateway account with Stripe connect account ID %s not found.", connectAccount));
We can move all this code and error handling to GatewayAccountCredentialsService which can be reused in PayoutReconcileProcess.

Once moved this method will read simple. Something like

```
private Event getPayoutCreatedEvent(String connectAccount, StripePayout payout) {
        GatewayAccountEntity gatewayAccountEntity = gatewayAccountCredentialsService.findGatewayAccountForCredentialKeyAndValue(
                StripeCredentials.STRIPE_ACCOUNT_ID_KEY, connectAccount);
        
        return PayoutCreated.from(gatewayAccountEntity.getId(), payout);
    }
```

2021-06-25 07:44 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/payout/PayoutEmitterService.java
> +                throw new GatewayAccountNotFoundException(format("Gateway account with Stripe connect account ID %s not found.", connectAccount));
Done.

2021-06-25 07:45 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/payout/PayoutReconcileProcess.java
> +                .orElseThrow(() -> new RuntimeException(format("Gateway account credentials with Stripe connect account ID [%s] not found.", stripeAccountId)));
Done.

2021-06-25 09:26 UTC, SandorArpa requested changes, later dismissed

2021-06-25 09:26 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gatewayaccount/exception/GatewayAccountCredentialsNotFoundException.java
> +        super(notFoundResponse(format(message)));
No need to format message here

2021-06-25 16:10 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/exception/GatewayAccountCredentialsNotFoundException.java
> +        super(notFoundResponse(format(message)));
This is needed so that I can create the error message for Stripe see `GatewayAccountCredentialsService`

2021-06-28 22:43 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/payout/PayoutReconcileProcessTest.java
> -        verify(payoutReconcileQueue, never()).markMessageAsProcessed(payoutReconcileMessage.getQueueMessage());
Is this test already covered anywhere i.e. not marking message as processed if there is an exception

2021-06-28 22:43 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccountcredentials/service/GatewayAccountCredentialsService.java
> +                .orElseThrow(() -> new RuntimeException(format("Gateway account credentials with Stripe connect account ID [%s] not found.", stripeAccountId)));
Any reason we throw RuntimeException instead of `GatewayAccountCredentialsNotFoundException`

2021-06-28 22:43 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccountcredentials/service/GatewayAccountCredentialsService.java
> +                .orElseThrow(() -> new RuntimeException(format("Gateway account with Stripe connect account ID [%s] not found.", stripeAccountId)));
Similar, any reason we can't throw `GatewayAccountNotFoundException`

2021-06-30 10:01 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/payout/PayoutReconcileProcessTest.java
> -        verify(payoutReconcileQueue, never()).markMessageAsProcessed(payoutReconcileMessage.getQueueMessage());
No. But since the exception handling is in the `GatewayAccountCredentialsService` and tested already I thought I'd remove this test as there was no way to assert on the log message anymore. If the `GatewayAccountCredentialsService` throws an exception then the thread is interrupted where it is at. I'm not sure we need to specifically test that the message isn't mark as processed when an exception is thrown for when gateway account and gateway account credentials are empty.

2021-06-30 10:01 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gatewayaccountcredentials/service/GatewayAccountCredentialsService.java
> +                .orElseThrow(() -> new RuntimeException(format("Gateway account credentials with Stripe connect account ID [%s] not found.", stripeAccountId)));
Sorry I've fixed this now.

2021-06-30 10:01 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/gatewayaccountcredentials/service/GatewayAccountCredentialsService.java
> +                .orElseThrow(() -> new RuntimeException(format("Gateway account with Stripe connect account ID [%s] not found.", stripeAccountId)));
Sorry I've fixed this now.

2021-06-30 10:45 UTC, kbottla approved these changes
LGTM!

2021-06-30 10:45 UTC, merged