PP-8438 Optionally accept `service_id` on create account route
alphagov/pay-connector pull request #3163
Opened 2021-08-11 08:31 UTC by sfount

POST `/v1/api/accounts/` accepts `service_id` in the request body and
writes this to the corresponding database column.

Parameter is currently nullable in order to not break before consumers
are updated.

2021-08-11 08:54 UTC, alexbishop1 requested changes
What’s here looks good but feels like there should be some tests in `CreateGatewayAccountResourceIT`.

2021-08-11 08:58 UTC, sfount commented
> What’s here looks good but feels like there should be some tests in `CreateGatewayAccountResourceIT`.

🤦  covered in `GatewayAccountResourceIT.java` but didn't realise they were split up in the test layout, will add those now.

2021-08-11 16:01 UTC, alexbishop1 requested changes

2021-08-11 16:01 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/CreateGatewayAccountResourceIT.java
> +    public void getAccountShouldReturnServiceId() {
Name doesn’t seem very fitting here: `createAGatewayAccountWithServiceId` or something would be better.

2021-08-12 08:55 UTC, alexbishop1 approved these changes

2021-08-12 09:31 UTC, merged