Pp 8441 add service id and live to payments payouts events gg
alphagov/pay-connector pull request #3206
Opened 2021-09-01 10:09 UTC by gidsg

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
**WIP DRAFT PR TO RUN TESTS ON CONCOURSE**
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2021-09-02 14:57 UTC, alexbishop1 requested changes
Looks fine. Just a couple of minor of things.

2021-09-02 14:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/charge/AuthorisationErrorCheckedWithGatewayChargeWasMissing.java
> +        super(serviceId, isLive, resourceExternalId, timestamp);
We seem to be inconsistent on whether we call it `live` or `isLive` — can we standardise on one or the other?

2021-09-02 14:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/charge/PaymentEvent.java
> +    private boolean live;
I can’t think of a reason why these shouldn’t be `final`.

2021-09-02 14:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/payout/PayoutEvent.java
> +    private boolean live;
Again, these can probably be `final`.

2021-09-02 14:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/EventServiceTest.java
> +        Event event = new PaymentEvent("service-id", true,"external-id", now());
Missing a space.

2021-09-03 08:43 UTC, gidsg commented on src/test/java/uk/gov/pay/connector/events/EventServiceTest.java
> +        Event event = new PaymentEvent("service-id", true,"external-id", now());
fixed in 802f246d8167ee6942c8871367c065a27db808f8

2021-09-03 08:43 UTC, gidsg commented on src/main/java/uk/gov/pay/connector/events/model/charge/AuthorisationErrorCheckedWithGatewayChargeWasMissing.java
> +        super(serviceId, isLive, resourceExternalId, timestamp);
fair point! Have standardised on `live` now in https://github.com/alphagov/pay-connector/pull/3206/commits/a39d53f0c054f4257ed1fe5f03bdac7bb360df5d.

2021-09-03 08:59 UTC, gidsg commented on src/main/java/uk/gov/pay/connector/events/model/payout/PayoutEvent.java
> +    private boolean live;
Hmm, when I try to do this I get a compilation error:
```
variable live might not have been initialized
```
any ideas?

2021-09-03 09:12 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/payout/PayoutEvent.java
> +    private boolean live;
OK, that’ll be because there’s the other constructor that doesn’t set them and we don’t explicitly set default values when the fields are declared. That makes perfect sense so leave them as non-`final` for now (we can reconsider if the other constructor goes away).

2021-09-03 09:32 UTC, gidsg commented
as suggested @alexbishop1 I have squashed the commits addressing the PR comments.

2021-09-03 10:49 UTC, alexbishop1 approved these changes

2021-09-03 11:30 UTC, merged