PP-8540 log ip address
alphagov/pay-connector pull request #3255
Opened 2021-09-30 13:23 UTC by gidsg

DRAFT

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2021-10-01 13:42 UTC, gidsg commented
OK @alexbishop1 as discussed off-of-Github, I've removed the Optional field but used it when serialising. If we're happy with this approach I can squash the commits!

2021-10-01 14:02 UTC, alexbishop1 requested changes
I think it’s fine to not include anything if there isn’t an IP address (which I don’t think will happen in practice). Please remove the rogue import and squash the commits.

2021-10-01 14:02 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthorisationRequestSummaryStringifier.java
> +import org.apache.commons.cli.Option;
Suspicious import 🧐

2021-10-01 14:22 UTC, gidsg commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthorisationRequestSummaryStringifier.java
> +import org.apache.commons.cli.Option;
@alexbishop1 Good spot 👀  have removed and squashed in 36c3c60

2021-10-04 18:02 UTC, alexbishop1 approved these changes

2021-10-05 08:10 UTC, merged