PP-8947 - Fix CaptureConfirmed Event to properly check fees
alphagov/pay-connector pull request #3356
Opened 2021-12-16 13:10 UTC by nimalank7

Description:
- From locally testing it looks like Google Guice @Transactional will persist the charge (i.e. flush the EntityManager changes) so no need to explicitly
 call feeDao.persist(...). Adding CascadeType.Persist and then setting the FeeEntity on the charge will ensure it is flushed to the database (tested locally
 and the fees were correctly persisted)
- Previously the CaptureConfirmed event would always emit the fee because only after the code progressed would the fees actually be persisted. This meant that the fee
check on CaptureConfirmed event would always be 0. Refactoring the code and ensuring the fees are added to the ChargeEntity before emitted the event removes the bug

2021-12-16 16:44 UTC, alexbishop1 requested changes
Requested a couple of changes. I’m convinced that reordering the code so that we persist the fees before we emit the captured event is the right thing to do but I’m less sure about the changes to how we actually persist fees.

2021-12-16 16:44 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureService.java
> +                    });
This could be:

```java
feeList.stream().map(fee -> new FeeEntity(charge, clock.instant(), fee.getAmount(), fee.getFeeType())).forEach(charge::setFee);
```

2021-12-16 16:44 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +    @OneToMany(mappedBy = "chargeEntity", cascade = CascadeType.PERSIST)
I’m a little concerned that this is the only time in this class where we use `cascade = CascadeType.PERSIST`. It may be that’s legitimate but are we sure we’re not deviating from established patterns?

2021-12-16 16:44 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureService.java
> +                    });
This means we’re now sending the event for the fee before we’ve persisted the fee. This makes me feel a little uncomfortable but I see we already do this with the `Gateway3dsInfoObtained` so maybe it’s OK.

2021-12-16 16:44 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureServiceTest.java
> -        verify(mockFeeDao, times(1)).persist(any());
Without something like this it seems we’re not testing that we’re persisting the fees any more. Do we have an integration test that checks this? If not, might we want to consider writing one?

2021-12-17 09:45 UTC, kbottla reviewed
I think the fee list are not available when CaptureConfirmed event because of order of events when processing capture response

1. updateChargePostCapture() is called first which will 
     a.  update charge status to CAPTURED 
     b.  adds transition to state transition queue which emits CAPTURE_CONFIRMED event after a certain delay. so possible that CAPTURE_CONFIRMED is emitted before/while fee entities are being persisted. 
2. Fee is persisted and added to charge entity

So changing order - persisting fee , adding feeEntities to charge, and updating charge status (`updateChargePostCapture `) last could work.

2021-12-17 09:45 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureService.java
> +                        charge.setFee(feeEntity);
we should rename `setFee` on chargeEntity. `setFee` got me thinking that we are setting one fee entity on the charge. May be we rename it to `addFee` or something more clear

2021-12-17 13:11 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureService.java
> +                        charge.setFee(feeEntity);
Done.

2021-12-17 13:11 UTC, nimalank7 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureServiceTest.java
> -        verify(mockFeeDao, times(1)).persist(any());
Written a new service integration test.

2021-12-17 13:11 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +    @OneToMany(mappedBy = "chargeEntity", cascade = CascadeType.PERSIST)
This is the only way to persist the fees via the ChargeEntity.

2021-12-17 13:11 UTC, nimalank7 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureService.java
> +                    });
Made the change.

2021-12-17 14:42 UTC, alexbishop1 approved these changes

2021-12-17 14:42 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureServiceIT.java
> +        List<String> feeAmountColumnValues = listOfFees.stream().map(map -> map.get("amount_collected").toString()).collect(Collectors.toList());
🗺

2021-12-17 14:56 UTC, merged