Pp 9330 endpoint to create agreement
alphagov/pay-connector pull request #3492
Opened 2022-03-03 11:37 UTC by kundanscorpio

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2022-03-03 11:42 UTC, gidsg commented on src/main/java/uk/gov/pay/connector/agreement/model/AgreementEntity.java
> +import javax.persistence.*;
We try to avoid wildcard imports, see: https://gds-way.cloudapps.digital/manuals/programming-languages/java.html#imports

2022-03-03 11:42 UTC, nlsteers commented
Can you fill out the comment and squash some of these commits to tidy up? Commit messages should also include the ticket number so that they are mapped to the Jira story automatically.

2022-03-03 11:43 UTC, gidsg commented on src/main/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResource.java
> +import javax.ws.rs.*;
See other comment https://github.com/alphagov/pay-connector/pull/3492/files#r818574925

2022-03-03 13:05 UTC, alexbishop1 requested changes
Looks fairly good. I think all the builder stuff to create the domain objects might be a bit overwrought but I encouraged you down that route so I’m not going to complain!

Made a few suggestions, which are mostly minor code changes and some additional tests. We seem to be testing all the substantial new classes except `AgreementDao` but that does so little right now that I think it’s OK.

The sequence of commits is a little circuitous, with lots of in-progress commits and fixes for things that broke along the way. Usually we try to do some squashing to avoid this. It’s OK for a PR to consist of several commits, each delivering a new little bit of value, but we try to avoid commits that reveal the back-and-forth stuff that happened while the code was being written but never got released. In this case, I’d probably just squash all the commits into one.

Also, each commit should start with the story number (so ‘PP-9330’ in this case): it’s useful for future readers of the change history and allows Jira to link the commits to the appropriate story.

In terms of code size, this is about the limit of what we’d want a PR to be.

2022-03-03 13:05 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/agreement/model/AgreementEntity.java
> +import javax.persistence.*;
We do not use wildcard imports (see https://gds-way.cloudapps.digital/manuals/programming-languages/java.html#imports for why).

2022-03-03 13:05 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/agreement/model/AgreementEntity.java
> +        //AgreementEntity agreementEntity = new AgreementEntity();
Delete this please.

2022-03-03 13:05 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResource.java
> +import javax.ws.rs.*;
Another wildcard.

2022-03-03 13:05 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResource.java
> +    private static final String ACCOUNT_ID = "accountId";
This constant is only used once so just hardcode `"accountId"` there.

2022-03-03 13:05 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +            <column name="agreement_id" type="bigserial" autoIncrement="true">
This does not seem right. We always use `id` for the primary keys of our tables. If there’s something that’s preventing it from working as it currently is, we should figure that out and fix it.

Additionally, this migration has already been run in the test, staging and production environments, so we cannot change it (we can add new migrations if necessary, of course).

Finally, we do not include migrations and code changes in the same pull request because there’s one release per pull request. The usual strategy is to create a PR with the migration, then a separate PR with the code change, which should assume the migration has already been run.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceIT.java
> +public class AgreementResourceIT {
Could you name this `AgreementsApiResourceIT` for consistency please?

Since this is a whole new test file, could you try writing it in JUnit 5? See https://docs.google.com/presentation/d/1Z1VSjvhxU7tffKTx6vCHd3AY5WIyZLE0awOjOiHsJ2Q/edit for a five-minute guide to the differences from JUnit 4 (including the annotations required to do a Dropwizard integration test). Happy to provide further help if you need it.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceIT.java
> +    public void testShouldCreateAgreement() throws JsonProcessingException {
This isn’t JUnit 3, you don’t need to prefix the test name with ‘test’! 😀

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceIT.java
> +                .body("created_date", notNullValue());
Our usual pattern for doing this in connector (which is horrible because it relies on the current time) is to do this:

```java
.body("created_date", matchesPattern("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(.\\d{1,3})?Z"))
.body("created_date", isWithin(10, SECONDS));
```

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceIT.java
> +        LocalDateTime activeEndDate = LocalDate.parse("2021-03-01").atStartOfDay();
Since these get converted to `Instant`s later, we can just do:

```
var createdDate = Instant.parse("2021-01-01T00:00:00");
var activeStartDate = Instant.parse("2021-02-01T00:00:00");
var activeEndDate = Instant.parse("2021-03-01T00:00:00");
```

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceIT.java
> +                .build();
Do we actually need to add the credentials to make the test work? It’s a lot of code for something we don’t actually care about for this test.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceIT.java
> +}
We could have a test in here that checks we do something sensible when we get an invalid reference in the request (too long etc.) or not reference at all.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceTest.java
> +        AgreementResponse ar = new AgreementResponseBuilder().withAgreementId("aid").withReference(REFERENCE_ID).withServiceId("serviceid").withCreatedDate(Instant.now()).build();
Best to avoid relying on the current time in tests: since the actual time does not matter, we could just use `Instant.parse("2022-03-03T12:00:00Z")` (feel free to add an air of mystery by choosing a date that’s meaningful to you but nobody else!).

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceTest.java
> +        when(agreementService.create(any(AgreementCreateRequest.class), any(Long.class))).thenReturn(Optional.ofNullable(ar));
Not a fan of all the `any`s. For `any(AgreementCreateRequest.class)` we could instead stick an `equals(…)` method on `AgreementCreateRequest` so we can easily compare the expected and actual. For `any(Long.class)` you should be able to use the actual gateway account ID.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceTest.java
> +        Map myMap = Map.of("reference", REFERENCE_ID);
`myMap` is not the most descriptive name: I’d just inline this into the `post(…)` line below.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceTest.java
> +    private static AgreementService agreementService = mock(AgreementService.class);
I don’t think this wants to be static.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceTest.java
> +        when(agreementService.create(any(AgreementCreateRequest.class), eq(NOT_VALID_ACCOUNT_ID))).thenThrow(nfe);
This can be:

```java
when(agreementService.create(any(AgreementCreateRequest.class), eq(NOT_VALID_ACCOUNT_ID))).thenThrow(NotFoundException.class);
```

… eliminating the need for the `nfe` local variable.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementResourceTest.java
> +        Map myMap = Map.of("reference", REFERENCE_ID);
🗺️

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +@RunWith(JUnitParamsRunner.class)
This does not seem to use parameterised tests, so it can just use  the standard Mockito runner.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +public class AgreementServiceTest {
Again, since this is a whole new test class, please use JUnit 5.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +        service = new AgreementService(mockedAgreementDao, mockedGatewayAccountDao, Clock.systemUTC());
Use `Clock.fixed(…)` rather than something that depends on the actual real time.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +    	assertNotNull(response.get());
If there was an empty Optional, the `response.get()` call would actually throw a NullPointerException, so the `assertNotNull(…)` call would never be made. Usually we do something like `assertThat(response.isPresent(), is(true));`.

2022-03-03 13:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +    	assertEquals(SERVICE_ID, response.get().getServiceId());
Usually we prefer `assertThat(actual, is(expected))` to `assertEquals(expected, actual)`.

2022-03-07 13:47 UTC, gidsg commented on pom.xml
> +        <jackson.version>2.13.1</jackson.version>
These look like downgrades, guess this file should be reverted to master.

2022-03-07 13:48 UTC, gidsg commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceTest.java
> +        Map myMap = Map.of("reference", REFERENCE_ID);
Can we give this a more descriptive name, or just inline it?

2022-03-07 17:37 UTC, alexbishop1 requested changes
Thanks for making the changes but it looks like a few things I commented on last time have not been addressed. Happy to discuss if you disagree with any of them or want more reasoning.

2022-03-07 17:37 UTC, alexbishop1 commented on pom.xml
> +            <version>1.2.10</version>
Not sure what happened here but we definitely do not want to be downgrading dependencies.

2022-03-07 17:37 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/queue/tasks/PaymentTaskMessage.java
> +
🤨

2022-03-07 17:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceIT.java
> +    public AgreementsApiResourceIT() {
I left a few comments about this file in my last review (back when it was called `AgreementResourceIT.java`). As discussed earlier, fine to leave the test as JUnit 4 but my other comments still stand (happy to debate any of them if you disagree, of course).

2022-03-07 17:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceTest.java
> +class AgreementsApiResourceTest {
Again, a few comments from my last review about this file (back when it was called `AgreementResourceTest`), which still need looking at.

2022-03-07 17:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +    public MockitoRule rule = MockitoJUnit.rule();
Is this rule actually being used for anything?

2022-03-07 17:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +        Clock clock = Clock.fixed(Instant.parse(instantExpected), ZoneId.of("UTC"));
`ZoneOffset.UTC` is _slightly_ shorter than `ZoneId.of("UTC")` (and avoids a magic string literal).

2022-03-07 17:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +        assertThat(SERVICE_ID, is(response.get().getServiceId()));
Indentation has gone a bit wonky here.

2022-03-08 10:35 UTC, jbz149 commented on pom.xml
> +            <version>1.2.10</version>
the pom.xml is not from us.
we will remove it on the next squash.

2022-03-08 15:33 UTC, jbz149 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceTest.java
> +class AgreementsApiResourceTest {
All comments reviewed

2022-03-08 16:59 UTC, alexbishop1 requested changes
In terms of the code, I’m happy apart from one unused method parameter (noted in a comment below). The mixture of JUnit 4 and 5 is fine for now.

The commit message is not great at current. Could it be reworded? Something like “PP-9930 Endpoint to create agreement” followed by any other pertinent information would be fine.

In addition, the tests seem to be failing, which will need to be fixed before this is merged. Happy to assist with looking into this.

2022-03-08 16:59 UTC, alexbishop1 commented on pom.xml
> +            <version>1.2.10</version>
I assume we’re still waiting on that squash!

2022-03-08 16:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResource.java
> +            @Context UriInfo uriInfo
Not spotted this before now but I think we can remove the `UriInfo` because it’s never used.

2022-03-09 14:53 UTC, alexbishop1 approved these changes

2022-03-09 15:48 UTC, merged