Pp 9315 worldpay accept language
alphagov/pay-connector pull request #3511
Opened 2022-03-10 15:43 UTC by gidsg

WIP

## WHAT YOU DID
_A brief description of the pull request:_

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2022-03-30 15:57 UTC, alexbishop1 requested changes
Looks good but there’s something I think can be simplified.

2022-03-30 15:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/LanguageHeaderParser.java
> +    public static String getPreferredLocaleFromAcceptHeader(String acceptLanguageHeader) {
It would be more accurate to call the class `AcceptLanguageHeaderParser` and the method `getPreferredLanguageFromAcceptLanguageHeader(…)`.

I also think I’d prefer it if this was not static and parser were injected where it’s needed.

2022-03-30 15:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/LanguageHeaderParser.java
> +        final var DEFAULT_LOCALE = "en-GB";
This should probably be a `private static final` constant.

2022-03-30 15:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/LanguageHeaderParser.java
> +                        return locale.map(Locale::toLanguageTag).orElse(DEFAULT_LOCALE);
I think this is overkill. I do not think it’s necessary to check the language tag is recognised by Java. The parser will make sure the language tag is well-formed, which I think should be enough. The Worldpay 3DS Flex docs put no constraints on the content of the `<browserLanguage>` element so I assume anything that’s well-formed should be good enough. I doubt it’s going to explode if we send an unrecognised (but well-formed) language tag.

So I think it can be as simple as this (some stuff extracted to a private method to minimise the coverage of the try/catch block):

```java
public static String getPreferredLanguageFromAcceptLanguageHeader(String acceptLanguageHeader) {
    return parseLanguageRanges(acceptLanguageHeader)
                .stream()
                .map(Locale.LanguageRange::getRange)
                .filter(not(languageRange -> languageRange.equals("*")))
                .findFirst()
                .orElse(DEFAULT_LOCALE);
}

private static List<Locale.LanguageRange> parseLanguageRanges(String acceptLanguageHeader) {
    if (acceptLanguageHeader == null) {
        return Collections.emptyList();
    }
    try {
        return Locale.LanguageRange.parse(acceptLanguageHeader);
    } catch (IllegalArgumentException e) {
        return Collections.emptyList();
    }
}

```

2022-03-30 15:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/WorldpayPaymentProviderTest.java
> +    public void shouldBeAbleToSendAuthorisationRequestForMerchantUsing3dsWithNonJs() {
`Using3dsFlex` really.

2022-03-30 15:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/WorldpayPaymentProviderTest.java
> +            assertThat(res.getGatewayParamsFor3ds().get().toAuth3dsRequiredEntity().getThreeDsVersion(), startsWith("2"));
`"2."` maybe?

2022-03-30 16:34 UTC, gidsg commented on src/main/java/uk/gov/pay/connector/util/LanguageHeaderParser.java
> +                        return locale.map(Locale::toLanguageTag).orElse(DEFAULT_LOCALE);
@alexbishop1 The `toLanguageTag` here is doing some extra work here. Not just checking the locale is recognised. It converts to the `languageTag` which changes e.g. from `en-gb` to `en-GB` which matches what's in Worldpay's documentation.

2022-03-30 16:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/LanguageHeaderParser.java
> +                        return locale.map(Locale::toLanguageTag).orElse(DEFAULT_LOCALE);
I would hope the case would not matter but I see your point about matching Worldpay’s example. I wonder if there’s a way to normalise the language tag without requiring Java to recognise it.

2022-03-31 09:24 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/LanguageHeaderParser.java
> +                        return locale.map(Locale::toLanguageTag).orElse(DEFAULT_LOCALE);
OK, I’ve been playing with this and it seems that if we call `Locale.forLanguageTag(…).toLanguageTag()` we’ll get normalisation without restricting ourselves to only locales that Java recognises.

For example, `Locale.forLanguageTag("en-gb").toLanguageTag()` gives us `"en-GB"` and `Locale.forLanguageTag("sR-cYRl-Hs").toLanguageTag()` (Serbian in Cyrllic script as used in Serbia) gives us `"sr-Cyrl-HS"`.

The important part is that is seems to be cool about unrecognised language tags: `Locale.forLanguageTag("yy-xy").toLanguageTag()` gives us `"yy-XY"`.

We do have to be careful to filter out `*` as that gives us `"und"` (we are of course assuming that Worldpay does not want us to send `*`).

[`Locale.forLanguageTag(…)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Locale.html#forLanguageTag(java.lang.String)) does do some other conversions but I guess these will be OK.

Of course, this could still be taking us quite far from what the browser gives us but we’re not trying to preserve what the browser sent us, we’re trying to send a useful value to Worldpay. So making sure what the browser gives us is well-formed and then normalising it (with a bit of canonicalisation) without filtering out unrecognised language tags feels like a reasonable approach.

Anyway, I think this will work:

```java
public static String getPreferredLanguageFromAcceptLanguageHeader(String acceptLanguageHeader) {
    return parseLanguageRanges(acceptLanguageHeader)
                .stream()
                .map(Locale.LanguageRange::getRange)
                .filter(not(languageRange -> languageRange.equals("*")))
                .map(Locale::forLanguageTag)
                .map(Locale::toLanguageTag)
                .findFirst()
                .orElse(DEFAULT_LOCALE);
}

private static List<Locale.LanguageRange> parseLanguageRanges(String acceptLanguageHeader) {
    if (acceptLanguageHeader == null) {
        return Collections.emptyList();
    }
    try {
        return Locale.LanguageRange.parse(acceptLanguageHeader);
    } catch (IllegalArgumentException e) {
        return Collections.emptyList();
    }
}
```

2022-04-01 08:31 UTC, gidsg commented
@alexbishop1 I believe I've addressed all your comments now. Please may you re-review?

2022-04-01 08:58 UTC, alexbishop1 requested changes
This looks good. Just one extra assertion and we’re done.

2022-04-01 08:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/AcceptLanguageHeaderParserTest.java
> +        assertThat(acceptLanguageHeaderParser.getPreferredLanguageFromAcceptLanguageHeader("en-GB,en-US;q=0.9,en;q=0.8"), is("en-GB"));
Could we maybe add a test where `en-gb` becomes `en-GB`, just to show that this is behaviour we explicitly want?

2022-04-01 09:05 UTC, gidsg commented on src/test/java/uk/gov/pay/connector/util/AcceptLanguageHeaderParserTest.java
> +        assertThat(acceptLanguageHeaderParser.getPreferredLanguageFromAcceptLanguageHeader("en-GB,en-US;q=0.9,en;q=0.8"), is("en-GB"));
@alexbishop1 I don't _think_ that's what happens. Rather Java was returning `en-gb` part way through the transformation process. e.g. 
```
jshell> Locale.LanguageRange.parse("en-GB,en-US;q=0.9,en;q=0.8")
$4 ==> [en-gb, en-us;q=0.9, en;q=0.8]
```
The existing tests should show the returned value using the current code is the expected behaviour, so I think that's sufficient?

2022-04-01 09:06 UTC, gidsg commented on src/test/java/uk/gov/pay/connector/util/AcceptLanguageHeaderParserTest.java
> +        assertThat(acceptLanguageHeaderParser.getPreferredLanguageFromAcceptLanguageHeader("en-GB,en-US;q=0.9,en;q=0.8"), is("en-GB"));
i.e. we are not claiming to support the behaviour you describe, even if that is the current behaviour, we wouldn't expect user-agents to send a lower case value.

2022-04-01 09:07 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/AcceptLanguageHeaderParserTest.java
> +        assertThat(acceptLanguageHeaderParser.getPreferredLanguageFromAcceptLanguageHeader("en-GB,en-US;q=0.9,en;q=0.8"), is("en-GB"));
What I meant is that if the `Accept-Language` header is `en-gb` the eventual output will be `en-GB` i.e. we explicitly expect some normalisation to happen.

2022-04-01 09:22 UTC, gidsg commented on src/test/java/uk/gov/pay/connector/util/AcceptLanguageHeaderParserTest.java
> +        assertThat(acceptLanguageHeaderParser.getPreferredLanguageFromAcceptLanguageHeader("en-GB,en-US;q=0.9,en;q=0.8"), is("en-GB"));
@alexbishop1 thanks, have added and force-pushed

2022-04-01 09:41 UTC, alexbishop1 approved these changes

2022-04-01 09:48 UTC, merged