PP-9334: add new table for payment instruments and foreign keys to charges and agreements tables
alphagov/pay-connector pull request #3525
Opened 2022-03-15 16:28 UTC by gidsg

Co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov.uk>

## WHAT YOU DID
Add database migration

## How to test

Check code makes sense, migrations should run successfully when app is run locally

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2022-03-15 17:30 UTC, alexbishop1 requested changes

2022-03-15 17:30 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +                <constraints nullable="true"/>
Will we ever have a payment instrument without a start date?

2022-03-15 17:30 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +            <column name="payment_instrument_id" type="bigserial">
I think this should be `bigint` (although the column referenced by the foreign key constraint auto-increments, _this_ column does not).

2022-03-15 17:30 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +            <column name="payment_instrument_id" type="bigserial">
`bigint`

2022-03-16 09:13 UTC, gidsg commented on src/main/resources/migrations.xml
> +                <constraints nullable="true"/>
Could there in practice be any difference between the `start_date` and `created_date` i.e. could the payment instrument ever be added and the start date added later?

2022-03-16 09:52 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +                <constraints nullable="true"/>
Let’s leave it for now; we can always change it later.

2022-03-16 09:52 UTC, alexbishop1 approved these changes

2022-03-16 09:55 UTC, merged