PP-9331 modify payments endpoint to support setting up payment instruments
alphagov/pay-connector pull request #3549
Opened 2022-03-23 19:13 UTC by jbz149

2022-03-24 14:00 UTC, alexbishop1 requested changes
Looks great apart from one tiny test naming thing.

The description of this PR is a bit generic: something closer to the commit message would be great.

2022-03-24 14:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +    public static Response agreementNotFoundResponse(String message) {
I wonder if having an overloaded `notFoundResponse(ErrorIdenifier, String)` method (calling an overloaded `buildErrorResponse(ErrorIdentifier, String, String)` method) might work here. But this is fine for now.

2022-03-24 14:00 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceCreateIT.java
> +    public void shouldReturn400AndErrorIdAgreementNotFoundWhenAgreementIsNotFound() {
404 (not 400)

2022-03-24 16:06 UTC, jbz149 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceCreateIT.java
> +    public void shouldReturn400AndErrorIdAgreementNotFoundWhenAgreementIsNotFound() {
We have this from the acceptance criteria in PP-9331 :

If agreement ID does not exist, return this with a 400(?):

{
  "field": "set_up_agreement",
  "code": "P0103",
  "description": "Invalid attribute value: set_up_agreement. Agreement ID does not exist"
}

2022-03-24 16:25 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceCreateIT.java
> +    public void shouldReturn400AndErrorIdAgreementNotFoundWhenAgreementIsNotFound() {
Hmm, would have thought we’d have `.statusCode(HttpStatus.SC_BAD_REQUEST)` then.

2022-03-25 11:13 UTC, sfount reviewed
Code change looks good, question about modifying the public response

2022-03-25 11:13 UTC, sfount commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +    private boolean savePaymentInstrumentToAgreement;
Serialising this will expose the `save_payment_instrument_to_agreement` property to the charge response returned by the API to external calls. 

As far as I'm aware this is an internal flag that will be used during the payment process, it's also not currently documented anywhere so would likely cause confusion as it would start showing up on all create payment requests. Is there part of the spec that called for this in particular or can this be removed?

2022-03-28 15:31 UTC, alexbishop1 requested changes
Looks fine but I think we can delete some more unused code and the method organisation in `ResponseUtil` needs some tweaks.

2022-03-28 15:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/builder/AbstractChargeResponseBuilder.java
> +    }
I think this can go now we’re not including the property in `ChargeResponse`.

2022-03-28 15:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/builder/AbstractChargeResponseBuilder.java
> +    }
I think this can go now we’re not including the property in `ChargeResponse`.

2022-03-28 15:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeEntity.java
> +                    Instant.now(Clock.system(ZoneOffset.UTC)),
I don’t think this change actually makes any difference (because `Instant` has no time zone) so will return the same time from any current-time `Clock`).

2022-03-28 15:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                .withSavePaymentInstrumentToAgreement(chargeEntity.isSavePaymentInstrumentToAgreement());
I think this can go now we’re not including the property in `ChargeResponse`.

2022-03-28 15:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +    public static Response agreementNotFoundResponse(String message) {
I think this method is not actually used.

2022-03-28 15:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +    private static Response buildAgreementNotFoundErrorResponse(Status status, String message) {
I think this method is not actually used.

2022-03-28 15:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +    }
To match the conventions in this file, I think we want a public/private method pair like this:

```java
public static Response notFoundResponse(ErrorIdentifier errorIdentifier, String message) {
    LOGGER.info(message);
    return buildErrorResponse(NOT_FOUND, errorIdentifier, message);
}

private static Response buildErrorResponse(Status status, ErrorIdentifier errorIdentifier, String message) {
    ErrorResponse errorResponse = new ErrorResponse(errorIdentifier, List.of(message));
    return responseWithEntity(status, errorResponse);
}
```

2022-03-28 15:48 UTC, jbz149 commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +    public static Response agreementNotFoundResponse(String message) {
Strangely that method is used.
The exception mapper was never called

2022-03-30 14:31 UTC, alexbishop1 approved these changes

2022-03-30 14:32 UTC, alexbishop1 requested changes
Actually, please squash the two commits into one.

2022-04-01 12:44 UTC, alexbishop1 approved these changes

2022-04-01 13:51 UTC, merged