PP-1776 Provider level gateway clients
alphagov/pay-connector pull request #355
Opened 2017-03-17 17:23 UTC by imranbohoran

## WHAT
_A brief description of the pull request:_

- As part of allowing for retry on captures, we have decided to configure our gateway clients to timeout earlier than wait for the egress proxy to timeout. However this also means that we want to have the gateway clients to be configurable per operation(i.e. auth, capture, client, refund).
- This PR provides the capability to configure clients for each gateway and for each operation.
- The timeout for capture in particular has been reduced to 10s as there's no point on us waiting for 60s for it to timeout (based on the metrics we have for capture response times). It either succeeds in about 600ms or it doesn't for over 1 minute.

## Still to do

The newly introduced [GatewayOperation](https://github.com/alphagov/pay-connector/blob/PP-1776_provider_level_gateway_clients/src/main/java/uk/gov/pay/connector/service/GatewayOperation.java) has some overlap in purpose with [PaymentGatewayName](https://github.com/alphagov/pay-connector/blob/PP-1776_provider_level_gateway_clients/src/main/java/uk/gov/pay/connector/resources/PaymentGatewayName.java). We think we should refactor to remove this duplication and intend to do that in a subsequent pull request. However, we're keen to ship this code increment as-is and do the refactoring in another PR.

with @heathd

2017-03-17 17:51 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-03-20 12:24 UTC, ckalista requested changes
Code review completed - looks good to me 👍

2017-03-20 12:24 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/BasePaymentProvider.java
> +    protected <U extends GatewayRequest> GatewayResponse sendReceive(U request, GatewayOperation operation, Function<U, GatewayOrder> order,
This method is currently not been used - that's perfectly fine as it is here in preparation for the rest of the refactoring. However this new method is practically a copy-paste of the one up above which seems like a code smell. Should we not try to refactor the two methods to make one call the other as it is typically done with overloads?

2017-03-20 12:24 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/ClientFactory.java
> +        if (conf.getGatewayConfigFor(gateway).getJerseyClientOverrides() != null) {
`conf.getGatewayConfigFor(gateway).getJerseyClientOverrides` could be extracted into a local variable to improve readability.

2017-03-20 12:24 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/PaymentProviders.java
> +    private PaymentProvider createSmartPayProvider(GatewayConfig config,
`config` parameter is not needed anymore - may be a good opportunity to remove it.

2017-03-20 12:24 UTC, ckalista commented on src/main/resources/config/config.yaml
> +  # Defines the socket timeout (SO_TIMEOUT), which is the
👍  for the documentation.

2017-03-20 13:04 UTC, daniele-occhipinti requested changes

2017-03-20 13:04 UTC, daniele-occhipinti commented on src/main/java/uk/gov/pay/connector/service/GatewayOperationClientBuilder.java
> +    public GatewayOperationClientBuilder() {
It seems this constructor can be made private.

2017-03-20 13:04 UTC, daniele-occhipinti commented on src/main/resources/config/config.yaml
> +      readTimeout: 10000ms
Maybe expressing those timeouts in seconds is more readable (fewer zeros). I am not sure whether that is supported. On the other hand, I understand timeouts are usually expressed in ms.

2017-03-20 13:04 UTC, daniele-occhipinti commented on src/test/java/uk/gov/pay/connector/service/smartpay/SmartpayPaymentProviderTest.java
> +import static org.mockito.Matchers.any;
is this line necessary, given the line above?

2017-03-20 13:58 UTC, ghost commented
There were errors, for info, please see...

2017-03-20 14:22 UTC, ghost commented
There were errors, for info, please see...

2017-03-20 14:45 UTC, imranbohoran commented on src/main/java/uk/gov/pay/connector/service/BasePaymentProvider.java
> +    protected <U extends GatewayRequest> GatewayResponse sendReceive(U request, GatewayOperation operation, Function<U, GatewayOrder> order,
👍 It was a hangover and unnecessary override from the previous implementation. Removed it.

2017-03-20 14:45 UTC, imranbohoran commented on src/main/java/uk/gov/pay/connector/service/ClientFactory.java
> +        if (conf.getGatewayConfigFor(gateway).getJerseyClientOverrides() != null) {
👍 Done

2017-03-20 14:46 UTC, imranbohoran commented on src/main/java/uk/gov/pay/connector/service/PaymentProviders.java
> +    private PaymentProvider createSmartPayProvider(GatewayConfig config,
👍 Yes, its not need indeed. Removed.

2017-03-20 14:46 UTC, imranbohoran commented on src/main/resources/config/config.yaml
> +  # Defines the socket timeout (SO_TIMEOUT), which is the
I'll 👍 your 👍 , for reading it 😄

2017-03-20 14:47 UTC, imranbohoran commented on src/main/resources/config/config.yaml
> +      readTimeout: 10000ms
This is going to change and will be less number of millis, so not changing anything right now.

2017-03-20 14:47 UTC, imranbohoran commented on src/main/java/uk/gov/pay/connector/service/GatewayOperationClientBuilder.java
> +    public GatewayOperationClientBuilder() {
👍 It certainly could. Done.

2017-03-20 14:48 UTC, imranbohoran commented on src/test/java/uk/gov/pay/connector/service/smartpay/SmartpayPaymentProviderTest.java
> +import static org.mockito.Matchers.any;
Yes it's needed. If not there are conflicts with `any` from another library.

2017-03-20 15:11 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-03-20 15:45 UTC, daniele-occhipinti approved these changes

2017-03-20 15:50 UTC, ckalista approved these changes

2017-03-20 15:51 UTC, merged