PP-1777 capture background process retries
alphagov/pay-connector pull request #363
Opened 2017-03-24 12:31 UTC by heathd

With @imranbohoran 

In #358 we added the background process and a retrying mechanism, however it would continue to retry captures indefinitely.

This PR adds support for retrying capture attempts in a sensible way. Key changes:

- 6d61fef tuned the timeouts of both capture and auth
- a7ea9f0 set status to error if maximum retries exceeded
- 5e80a32 configuration of maximum retries

## Notes for reviewer

We tried using a `guage` to record the queue length in hosted graphite. However this didn't seem to work. We've changed to a `meter`, however this doesn't seem to be quite the right thing either. We suggest just shipping this change and we can improve the metrics later.

Please review the setting of timeout values (see screenshots of actual timings attached)

![screen shot 2017-03-22 at 13 54 42](https://cloud.githubusercontent.com/assets/61065/24294280/c3c9ce2c-108d-11e7-8619-aa8849901fc9.png)
![screen shot 2017-03-22 at 13 55 07](https://cloud.githubusercontent.com/assets/61065/24294281/c3cdf362-108d-11e7-99e4-9ffcd23de63a.png)
![screen shot 2017-03-22 at 13 56 32](https://cloud.githubusercontent.com/assets/61065/24294282/c3d03ed8-108d-11e7-8f6b-edfbd9ef3579.png)
![screen shot 2017-03-22 at 13 57 26](https://cloud.githubusercontent.com/assets/61065/24294284/c3d2f07e-108d-11e7-9576-00b4c55c0b4c.png)
![screen shot 2017-03-22 at 13 57 49](https://cloud.githubusercontent.com/assets/61065/24294285/c3d39632-108d-11e7-8ff8-2e51aa121bc2.png)
![screen shot 2017-03-22 at 14 05 51](https://cloud.githubusercontent.com/assets/61065/24294286/c3e09490-108d-11e7-9eaf-8ee7c1a2620c.png)
![screen shot 2017-03-22 at 14 06 59](https://cloud.githubusercontent.com/assets/61065/24294287/c3e3bcb0-108d-11e7-9b62-3c864997b6a4.png)

2017-03-24 13:07 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-03-24 15:49 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-03-27 15:23 UTC, simad requested changes

2017-03-27 15:23 UTC, simad commented on src/main/java/uk/gov/pay/connector/app/CaptureProcessConfig.java
> +    public java.time.Duration getRetryFailuresEveryAsJavaDuration() {
An API for this is to encapsulate the conversion in a small class which returns a dropwizard duration or a java duration, using field methods like `duration.asDropwizard()` or `duration.asJava()`. This is usually a good way to keep it nice and tight, but as this config class is already quite small and self contained, I don't feel so strongly about making this change.

2017-03-27 15:23 UTC, simad commented on src/test/java/uk/gov/pay/connector/service/CardCaptureProcessTest.java
> +    public static final int MAXIMUM_RERTRIES = 10;
Typo in `MAXIMUM_RERTRIES`

2017-03-27 15:23 UTC, simad commented on src/test/resources/config/client-factory-test-config-with-smartpay-timeout-override.yaml
> +captureProcessConfig:
Why are we adding the config here? This file is used only in the client factory tests, so we could avoid editing it for all the other tests. In truth this config duplication is a bit useless, we could raise a jira ticket as tech debt

2017-03-27 15:48 UTC, heathd commented on src/test/resources/config/client-factory-test-config-with-smartpay-timeout-override.yaml
> +captureProcessConfig:
as far as I could make out, Dropwizard requires this element to be present due to the way it deserializes the YAML using jax-rs. We couldn't figure out how to make an optional config section.

2017-03-27 16:18 UTC, heathd commented
@simad rebased and addressed comments

2017-03-27 16:49 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-03-28 09:23 UTC, simad approved these changes

2017-03-28 09:23 UTC, merged