PP-9369: Authorise recurring Sandbox payment process charge without user
alphagov/pay-connector pull request #3651
Opened 2022-04-27 18:02 UTC by jbz149

Add new exception : AgreementNotActiveException.java
Add new exception mapper : AgreementNotActiveExceptionMapper.java
Process charges for recurring payments.

2022-05-03 10:02 UTC, sfount requested changes
Concept looks good, a number of places where the code could quite easily throw unknown exceptions that should be guarded against, question on an additional bit of functionalities fit

meta: could the pr name be updated to reflect what it's doing rather than the jira ticket

2022-05-03 10:02 UTC, sfount commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        if (chargeEntity.getAuthorisationMode() == AuthorisationMode.AGREEMENT) return false;
This is added without any kind of test coverage -- I wonder if this is worth splitting out to its own separate PR. Happy for that to go in here but we should have some kind of assertions about the behaviour.

2022-05-03 10:02 UTC, sfount commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            AgreementEntity agreementEntity = agreementEntityOptional.get();
If the agreement doesn't exist, this will throw a `NullPointerException`, in favour of this we should chain these optional requests to always result in a uniform `AgreementNotActiveException` (I believe the way it's currently designed the agreement is required to exist as a separate assertion)

2022-05-03 10:02 UTC, sfount commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            PaymentInstrumentStatus instrumentStatus = agreementEntity.getPaymentInstrument().getPaymentInstrumentStatus();
Similar with above, payment instruments are much less likely to be in a guaranteed state at the time of this call -- we should be guarding against this not existing to ensure the code ends in a known state

2022-06-21 11:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        if (chargeEntity.getAuthorisationMode() == AuthorisationMode.AGREEMENT) return false;
Should now be covered by tests.

2022-06-21 11:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            AgreementEntity agreementEntity = agreementEntityOptional.get();
Sorted.

2022-06-21 11:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            PaymentInstrumentStatus instrumentStatus = agreementEntity.getPaymentInstrument().getPaymentInstrumentStatus();
Also sorted (with some help from https://github.com/alphagov/pay-connector/pull/3747).

2022-06-22 09:39 UTC, sfount reviewed
Looks great! All issues listed above addressed in a very clear and resilient way. Looks like there's a bit of now-redundant code that can be removed, if you'd prefer to do that in a follow up I'm happy to approve this

2022-06-22 09:39 UTC, sfount commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +                    checkAgreementHasActivePaymentInstrument(agreementEntity);
🙌 avoids two round trips to the db, and code path is clear

2022-06-22 09:39 UTC, sfount commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private Optional<AgreementEntity> getAgreementIfAgreementIdSpecified(String agreementId) {
It looks like this method is no longer called by the code above (in favour of what looks like simpler in-lining), I think it can be removed.

2022-06-22 10:18 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private Optional<AgreementEntity> getAgreementIfAgreementIdSpecified(String agreementId) {
Removed.

2022-06-22 10:25 UTC, sfount approved these changes

2022-06-22 10:47 UTC, merged