PP-9528 Serialise agreement events
alphagov/pay-connector pull request #3688
Opened 2022-05-09 16:15 UTC by sfount

New base events implementing the `Event` interface.

`AgreementEvent` and `PaymentInstrumentEvent` implement the simplest
possible level of top fields:
* service identifier
* live

Add POJOs to serialise the data that needs to be persisted during the
agreement and payment journey lifecycle. Extend base level agreement and
payment instrument events.

--- 

This data will drive the event store projections and should therefore line up with:

* https://github.com/alphagov/pay-ledger/blob/master/src/main/java/uk/gov/pay/ledger/agreement/entity/AgreementEntity.java
* https://github.com/alphagov/pay-ledger/blob/master/src/main/java/uk/gov/pay/ledger/agreement/entity/PaymentInstrumentEntity.java

---

This pull request doesn't do anything with the events but prepares them to be used (emitted) during the agreement/ recurring payment flow.

2022-05-11 11:12 UTC, alexbishop1 requested changes
I think we can make the `live` `Boolean` fields into `boolean`s but otherwise fine.

2022-05-11 11:12 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/charge/AgreementEvent.java
> +    private Boolean live;
Looks like this can be primitive and then we wouldn’t have to worry about it possibly being null.

2022-05-11 11:34 UTC, sfount commented on src/main/java/uk/gov/pay/connector/events/model/charge/AgreementEvent.java
> +    private Boolean live;
we've had some issues with primitive values on event superclasses before
https://github.com/alphagov/pay-connector/pull/3276
https://github.com/alphagov/pay-connector/pull/3279

I'm confident there's a better pattern for this but `null` values not being serialised hasn't bitten us before where default values have.

2022-05-12 09:56 UTC, alexbishop1 approved these changes

2022-05-12 10:07 UTC, merged