PP-9527 Consume ledger events endpoint
alphagov/pay-connector pull request #3689
Opened 2022-05-09 18:01 UTC by sfount

Depends on https://github.com/alphagov/pay-connector/pull/3688

---

Adds `postEvent` utility method to parse and POST anything extending
`Event` to Ledger's event endpoint.

Expect an `202 Accepted` response or appropriately throw a Ledger
exception to be handled upstream.

The uility is not used in this change. It will be used during the
agreement and recurring payment journeys.

2022-05-17 13:22 UTC, alexbishop1 requested changes
Looks fairly straightforward but it’s network IO and is that ever straightforward. Few comments below. Another thing is that we’re setting the connect timeout but not the read timeout — do we want to configure that as well?

2022-05-17 13:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +    }
Can we make this return a [`Duration`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Duration.html)? It’s a more appropriate type for what it is and we could just call the method `getLedgerPostEventTimeout()` and not encode the units in its name. If where we actually use it we just need a `long` of milliseconds we can easily use `Duration.toMillis()` to convert.

2022-05-17 13:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/RestClientFactory.java
> +    public static Client buildClient(RestClientConfig clientConfig, Long connectTimeoutInMillis) {
Again, this should ideally take a `Duration`.

2022-05-17 13:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/client/ledger/service/LedgerService.java
> +    private Response postEventList(List<Event> events) {
This could just be called `postEvents(…)`: it’s obvious from the parameter that it takes a `List`.

2022-05-17 13:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/client/ledger/service/LedgerService.java
> +        var uri = UriBuilder.fromPath(ledgerUrl).path("/v1/event");
Seems the URI is constant so we could just calculate it once in the constructor.

2022-05-17 13:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/client/ledger/service/LedgerService.java
> +                .post(Entity.json(events));
I assume this can throw exceptions — are we happy to let them bubble up?

2022-05-17 13:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/client/ledger/service/LedgerServiceTest.java
> +        when(mockBuilder.post(any())).thenReturn(mockResponse);
The `any()` makes this very loose in terms of what it will accept…

2022-05-17 13:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/client/ledger/service/LedgerServiceTest.java
> +        var event = new AgreementCreated("service-id", false, "resource-id", null, ZonedDateTime.now());
`ZonedDateTime.now(ZoneOffset.UTC)` or this is going to create different timestamps depending on the time zone of the computer.

2022-05-17 13:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/client/ledger/service/LedgerServiceTest.java
> +        verify(mockBuilder).post(Entity.json(List.of(event)));
Had to scroll up to remind myself what `mockBuilder` — could this be named better?

2022-05-23 13:00 UTC, sfount commented on src/main/java/uk/gov/pay/connector/client/ledger/service/LedgerService.java
> +                .post(Entity.json(events));
I think the main error surface when dealing with events would be in constructing the event itself (incorrect, missing data etc.). 

I think by the time it it's being passed to this endpoint to be processed we're fairly sure we'll get a POST body out if it. If not I can't think of what we'd do other than propagate to the calling code either way. Definitely room for improvement but I think OK for now.

2022-05-23 13:18 UTC, sfount commented
> Looks fairly straightforward but it’s network IO and is that ever straightforward? Few comments below. Another thing is that we’re setting the connect timeout but not the read timeout — do we want to configure that as well?

I've added a story to ensure we've got sensible defaults for this client (it feeds in with other work off the back of worldpay investigation) -- the connect timeout at least isolates connector trying to reach this endpoint from other activities which is why it was originally in the spec.

2022-05-26 10:44 UTC, alexbishop1 approved these changes

2022-05-26 10:44 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +    public Long getLedgerPostEventTimeoutInMillis() {
Do we need this method now we have `getLedgerPostEventTimeout()`?

2022-05-26 12:25 UTC, sfount commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +    public Long getLedgerPostEventTimeoutInMillis() {
At the moment it's needed by jackson to validate the not null constraint, in this ticket I've suggested that all of this is moved out to a separate configuration which can properly use durations etc. https://github.com/alphagov/pay-connector/pull/3689#issuecomment-1134669919

2022-05-26 12:25 UTC, merged