PP-1897 Fixed a bug in the metric to track the size of the queue of c…
alphagov/pay-connector pull request #369
Opened 2017-04-04 14:49 UTC by daniele-occhipinti

## WHAT

A Meter was used for tracking the size of the queue, but a Meter is to measure the rate of events over time.
We rather need to just log the size of the queue overtime, which is just an integer.
Among the Metrics available in Dropwizard, probably the Gauge is the more appropriate,
but that is not very efficient as that would need to calculate the size of the queue (which changes
very slowly) at regular interval. A CachedGauge is then a better option, but that complicates
things a bit and we still don't have control on when the metric collection is triggered.
That's why I have decided to use a Counter, which still makes sense, but we need to use it
a bit cleverly, as it just provide methods to increment or decrement the counter. Ideally,
to consider in the futre, is to create a new Metric (probably inheriting from Counter) which
would allow us to set a value directly with a set method.

For more information, you can see Dropwizard Metrics guide.

2017-04-04 16:05 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-04-04 16:12 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-04-04 16:33 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-04-04 16:42 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-04-04 17:20 UTC, ckalista requested changes

2017-04-04 17:20 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/CardCaptureProcess.java
> +        if (newQueueSize > currentQueueSizeCounter) {
Instead of decreasing, we can increase with a negative value which eliminates the need for a conditional check.

2017-04-04 17:20 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/CardCaptureProcess.java
> +            updateQueueSizeMetric(queueSize);
Not sure this should be in the finally - if anything wrong happens in chargeDao.countChargesForCapture() we don't want to update the metric as we don't know what to update it with.

2017-04-05 09:23 UTC, daniele-occhipinti commented
Chris, I have pushed both the changes you recommended.

2017-04-05 09:27 UTC, ckalista approved these changes

2017-04-05 09:27 UTC, ckalista commented
LGTM

2017-04-05 09:50 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-04-05 09:51 UTC, ghost commented
There were no errors, go have a cup of coffee...

2017-04-05 09:54 UTC, merged