PP-9529 Recurring journey events
alphagov/pay-connector pull request #3692
Opened 2022-05-10 10:42 UTC by sfount

Depends on https://github.com/alphagov/pay-connector/pull/3689, which depends on https://github.com/alphagov/pay-connector/pull/3688

---

Write details to event store when payment instrument is created.

Transactional guarantee: the payment instrument is guaranteed to have
been written to the database, if posting the event fails, the payment
instrument will be rolled back.

Write details to the event store when an agreement is created.
Agreements can currently only be created by as the result of an API
request.

Transaction guarantee: the agreement must be written to the database, if
posting the event fails, the agreement will be rolled back.

Persist information about an agreement setup being completed with a
given payment instrument.

Ensure it's run an an appropriate transactional enclosure to ensure the
properties in the working database reflect the event audit trail.

Add stubs and coverage for new endpoint now being used.

2022-05-26 13:59 UTC, alexbishop1 requested changes
Looks basically fine. Just a couple of things.

2022-05-26 13:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/charge/PaymentInstrumentCreated.java
> +                        this.expiryDate = Optional.ofNullable(cardDetails.getExpiryDate()).map(String::valueOf).orElse(null);
I think this would be a little clearer if it were like this:

```java
this.lastDigitsCardNumber = Optional.ofNullable(cardDetails.getLastDigitsCardNumber()).map(LastDigitsCardNumber::toString).orElse(null);
this.expiryDate = Optional.ofNullable(cardDetails.getExpiryDate()).map(CardExpiryDate::toString).orElse(null);
```

2022-05-26 13:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/LinkPaymentInstrumentToAgreementServiceTest.java
> +        verify(ledgerService).postEvent((List<Event>) ArgumentMatchers.any());
Can we not do anything more specific than `ArgumentMatchers.any()`?

2022-05-30 12:12 UTC, sfount commented on src/test/java/uk/gov/pay/connector/charge/service/LinkPaymentInstrumentToAgreementServiceTest.java
> +        verify(ledgerService).postEvent((List<Event>) ArgumentMatchers.any());
Have wrangled this in https://github.com/alphagov/pay-connector/commit/8a4910c9e48b4d032c1cf91e3ee47c2b955d4cac

2022-05-30 12:58 UTC, alexbishop1 approved these changes

2022-05-31 14:39 UTC, merged