PP-9644 make token expiry date configurable
alphagov/pay-connector pull request #3772
Opened 2022-06-09 11:27 UTC by nlsteers

## WHAT YOU DID

Added a configuration option for token expiry, allowing for more a aggressive deletion policy in the performance testing environment

2022-06-09 12:29 UTC, alexbishop1 requested changes
Logic and tests look fine but prefer to use `Durations` rather than `int`s and `Instant`s rather than `ZonedDateTime`s. (I have an entire presentation on the latter. No, really. I’ll share it with you.)

2022-06-09 12:29 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ChargeSweepConfig.java
> +    }
Make this return a [`Duration`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Duration.html): it’s a more appropriate type and it will probably make the calculation code simpler.

```java
public Duration getTokenExpiry() {
    return Duration.ofDays(tokenExpiryDays);
}
```

2022-06-09 12:29 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
> +        ZonedDateTime tokenExpiryDate = getExpiryDateForTokens();
Make this an `Instant` rather than a `ZonedDateTime`.

2022-06-09 12:29 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
> +        return tokenDao.deleteTokensOlderThanSpecifiedDate(tokenExpiryDate);
This can take an `Instant` and convert it to a `ZonedDateTime` before passing to `TokenDao`.

2022-06-09 12:29 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
> +    private ZonedDateTime getExpiryDateForTokens() {
This can return an `Instant` rather than a `ZonedDateTime`.

2022-06-09 15:36 UTC, nlsteers commented on src/main/java/uk/gov/pay/connector/app/ChargeSweepConfig.java
> +    }
Done, also changed to seconds as that's how the other thresholds are measured

2022-06-09 15:37 UTC, nlsteers commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
> +        return tokenDao.deleteTokensOlderThanSpecifiedDate(tokenExpiryDate);
Done.

2022-06-09 15:37 UTC, nlsteers commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
> +    private ZonedDateTime getExpiryDateForTokens() {
Done.

2022-06-09 15:37 UTC, nlsteers commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
> +        ZonedDateTime tokenExpiryDate = getExpiryDateForTokens();
Done.

2022-06-09 16:08 UTC, alexbishop1 requested changes
I didn’t realise you were going to change all the other expiry stuff to `Duration`s!

There’s a couple of things I think aren’t quite right with the logging and the tests.

2022-06-09 16:08 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ChargeSweepConfig.java
> +    private int tokenExpiryThreshold;
I think I’d prefer this to be called `tokenExpiryThresholdInSeconds` or sometging (inconsistent with the others but it can serve as an example to them).

2022-06-09 16:08 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
>          logger.debug("Charge expiry window size for awaiting_delay_capture in seconds: [{}]", chargeExpiryWindowSeconds);
How is `chargeExpiryWindowSeconds` going to be output in the logs now it’s a `Duration` rather than `int`?

2022-06-09 16:08 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeExpiryServiceTest.java
> +    private static final Duration TOKEN_EXPIRY_WINDOW_SECONDS = Duration.ofSeconds(604800);
You could do something like `Duration.ofSeconds(7 * 24 * 60 * 60)` if you want to make it less mysterious.

2022-06-09 16:08 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeExpiryServiceTest.java
> +        when(mockTokenDao.deleteTokensOlderThanSpecifiedDate(any(ZonedDateTime.class))).thenReturn(1);
Since we have a fixed clock, we should know the exact time that we’re expecting to be passed in.

2022-06-09 16:08 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeExpiryServiceTest.java
> +                        format("Charges found for expiry - number_of_charges=2, since_date=%s, awaiting_capture_date=%s", expectedChargeExpiryDate, expectedChargeAwaitingCaptureExpiryDate)
Rather than using string formatting, we could have fixed strings here, which would make sure the timestamps are being output as we expect.

2022-06-09 16:08 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/Worldpay3dsFlexJwtServiceTest.java
> +    private static final Duration TOKEN_EXPIRY_DURATION_SECONDS = Duration.ofSeconds(5400);
This name doesn’t need `SECONDS` in it any more.

2022-06-09 16:08 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/Worldpay3dsFlexJwtServiceTest.java
> +        Duration expectedTokenExpirationTimeEpochSeconds = paymentCreationTimeEpochSeconds19August2029.plus(TOKEN_EXPIRY_DURATION_SECONDS);
I don’t think these represent durations: they look like Unix timestamps.

2022-06-09 17:50 UTC, nlsteers commented on src/main/java/uk/gov/pay/connector/app/ChargeSweepConfig.java
> +    private int tokenExpiryThreshold;
Done.

2022-06-09 17:50 UTC, nlsteers commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
>          logger.debug("Charge expiry window size for awaiting_delay_capture in seconds: [{}]", chargeExpiryWindowSeconds);
Good catch, fixed.

2022-06-09 17:50 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeExpiryServiceTest.java
> +    private static final Duration TOKEN_EXPIRY_WINDOW_SECONDS = Duration.ofSeconds(604800);
Done.

2022-06-09 17:50 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeExpiryServiceTest.java
> +        when(mockTokenDao.deleteTokensOlderThanSpecifiedDate(any(ZonedDateTime.class))).thenReturn(1);
Updated.

2022-06-09 17:51 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeExpiryServiceTest.java
> +                        format("Charges found for expiry - number_of_charges=2, since_date=%s, awaiting_capture_date=%s", expectedChargeExpiryDate, expectedChargeAwaitingCaptureExpiryDate)
No worries, have fixed the clock to a specific moment in time and updated.

2022-06-09 17:51 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/service/Worldpay3dsFlexJwtServiceTest.java
> +        Duration expectedTokenExpirationTimeEpochSeconds = paymentCreationTimeEpochSeconds19August2029.plus(TOKEN_EXPIRY_DURATION_SECONDS);
Yep, fixed.

2022-06-09 17:51 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/service/Worldpay3dsFlexJwtServiceTest.java
> +    private static final Duration TOKEN_EXPIRY_DURATION_SECONDS = Duration.ofSeconds(5400);
Done.

2022-06-09 19:24 UTC, alexbishop1 approved these changes
Awesome, looks good.

2022-06-09 19:24 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
> +        Duration chargeExpiryWindowSeconds = chargeSweepConfig.getDefaultChargeExpiryThreshold();
Minor but this variable and similar don’t really need `Seconds` in their names any more.

2022-06-09 19:24 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeExpiryServiceTest.java
> +    private final Clock fixedClock = Clock.fixed(Instant.ofEpochSecond(1654732800), ZoneId.of("UTC")); // Thu 9 June 2022 00:00:00
You could also do `Instant.parse("2022-06-09T00:00:00Z")`.

2022-06-09 19:24 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeExpiryServiceTest.java
> +    private static final Duration CHARGE_EXPIRY_WINDOW = Duration.ofSeconds((long) (1.5 * 60 * 60));
Since floating point arithmetic scares me, I’d probably do `90 * 60`.

2022-06-09 19:24 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/Worldpay3dsFlexJwtServiceTest.java
> +        assertThat(jws.getBody(), hasEntry("exp", (int) expectedTokenExpirationTimeEpochSeconds.getEpochSecond()));
Slightly surprised you need the cast here.

2022-06-10 08:53 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/service/Worldpay3dsFlexJwtServiceTest.java
> +        assertThat(jws.getBody(), hasEntry("exp", (int) expectedTokenExpirationTimeEpochSeconds.getEpochSecond()));
The assertion fails on account of the postfixed `L` without the cast.

2022-06-10 08:54 UTC, merged