PP 1494 ePDQ auth support
alphagov/pay-connector pull request #378
Opened 2017-04-25 09:47 UTC by ckalista

## WHAT
_A brief description of the pull request:_

- Built out the class hierarchy for ePDQ authorisation responses, mapping all supported status codes to the following internal statuses:
   - Status `5` to `AUTHORISATION SUCCESS`
   - Status `50`, `51` to `AUTHORISATION SUBMITTED`
   - Status `2` to `AUTHORISATION REJECTED`
   - Any other status to `AUTHORISATION ERROR`
- Introduced a new transient waiting state `AUTHORISATION_SUBMITTED`, which we should not see many occurrences of as authorisation are almost never deferred in real life. The rare instances of non-immediate authorisation (ePDQ status `50` and `51`) are treated as errors, hence `AUTHORISATION_SUBMITTED` is mapped to `EXTERNAL_ERROR_GATEWAY`.
- The state engine has been updated to handle the new `AUTHORISATION_SUBMITTED` status that was introduced to cater for situations when ePDQ defers authorisation which we then treat as an error. The precondition for a charge to transition to `AUTHORISATION_SUBMITTED` is to be in a state of `AUTHORISATION_READY` although it is not mandatory for a charge to transition through `AUTHORISATION_SUBMITTED` in order to proceed to `AUTHORISATION_SUCCESS`, `AUTHORISATION_REJECTED`, `AUTHORISATION_CANCELLED` or `AUTHORISATION_ERROR`. In other words `AUTHORISATION_SUBMITTED` is optional and transient.
 - Transaction that are deferred during authorisation return a 400 bad response with an error message: `This transaction was deferred.`
- The initial implementation of `EpdqPaymentProvider` offers support for authorisation operation only at this stage. When building the authorisation request, the `ORDER ID` submitted to the payment provider in this implementation is going to be the `external charge id` for now until we are provided with more insight by HMCTS as to what sort of reference would be preferable instead in order to aid reconciliation.
- Credentials in `GatewayAccount` has been extended with a SHA passphrase which is required for any request payload signature.
- The configuration has a new section under `epdq` for `urls` and `jerseyClientOverrides` settings. Note that the Jersey Client settings are provisional and subject to change once we have collected real metrics and in a position to set sensible default values.
- New utility class `TestTemplateResourceLoader` used in tests to facilitate loading all request/response payloads that are made available as resources under `src/test/resources/templates`.
- Added argument check ensuring the passphrase is not blank for EPDQ message payment signature.

2017-04-26 11:34 UTC, mrlumbu reviewed
Generally really good. All my comments are just comments rather than things I definitely think need to be changed, but would be good to discuss.

2017-04-26 11:34 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +        return SmartpayStatusMapper.get();
is this right? At least this could do with a comment to explain

2017-04-26 11:34 UTC, mrlumbu commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +@Ignore("Ignoring as this test is failing in Jenkins because it's failing to locate the certificates - PP-1707")
should this be ignored?

2017-04-26 11:34 UTC, mrlumbu commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqCardResourceITest.java
> +public class EpdqCardResourceITest extends ChargingITestBase {
This is a bit unfair as you are following patterns set down across connector codebase, but do you think it would be better to push some of these tests down to PaymentProvider unit test level. It feels wrong to me that there are 5 integration tests and 2 provider unit tests

2017-04-26 11:34 UTC, mrlumbu commented on src/test/java/uk/gov/pay/connector/it/resources/smartpay/SmartpayNotificationResourceWithAccountSpecificAuthITest.java
> +import static uk.gov.pay.connector.util.TestTemplateResourceLoader.SMARTPAY_NOTIFICATION_CAPTURE;
unused import

2017-04-26 11:34 UTC, mrlumbu commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqCardResourceITest.java
> +    @Test
Just a question really: do we always just pass on the payment provider error message upstream - I would've thought it would make more sense to send up a generic error message?

2017-04-26 14:59 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +        return SmartpayStatusMapper.get();
Agreed, this shouldn't have been there. I have changed it in favour of an exception until we need an implementation most likely when we will look at supporting ePDQ notifications.

2017-04-26 15:01 UTC, ckalista commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +@Ignore("Ignoring as this test is failing in Jenkins because it's failing to locate the certificates - PP-1707")
Yes, there test should not be exercised as part the unit test suite by CI. However the code in here is extremely during development to spike new integration features with ePDQ.

2017-04-26 15:01 UTC, ckalista commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +@Ignore("Ignoring as this test is failing in Jenkins because it's failing to locate the certificates - PP-1707")
Yes, these test should not be exercised as part the unit test suite by CI. However the code in here is extremely during development to spike new integration features with ePDQ.

2017-04-26 15:04 UTC, ckalista commented on src/test/java/uk/gov/pay/connector/it/resources/smartpay/SmartpayNotificationResourceWithAccountSpecificAuthITest.java
> +import static uk.gov.pay.connector.util.TestTemplateResourceLoader.SMARTPAY_NOTIFICATION_CAPTURE;
Fixed. 👍

2017-04-26 15:09 UTC, ckalista commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqCardResourceITest.java
> +    @Test
You are absolutely right. The underlying error message from the payment provider is propagated all the way through. This is something I am not happy with either however for now I have just embraced what has been done for the other Gateways.

2017-04-26 16:31 UTC, ckalista commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqCardResourceITest.java
> +public class EpdqCardResourceITest extends ChargingITestBase {
Agreed, probably something worth looking but as a separate piece of work as it would require refactoring the tests of other providers.

2017-04-27 08:28 UTC, mrlumbu approved these changes

2017-04-27 08:52 UTC, daniele-occhipinti requested changes

2017-04-27 08:52 UTC, daniele-occhipinti commented on src/main/java/uk/gov/pay/connector/service/BasePaymentProvider.java
> +        return sendReceive(null, request, order, clazz, responseIdentifier);
Can we try to rename this? True is is not a public method, but still it is a bit puzzling when you read it.

2017-04-27 08:52 UTC, daniele-occhipinti commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +        return request -> anEpdqAuthoriseOrderRequestBuilder()
nice!

2017-04-27 08:52 UTC, daniele-occhipinti commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +                .withPspId("gov6nh")
is this some dummy data because we implement the feature?
Are we merging to master with this?

2017-04-27 09:30 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +                .withPspId("gov6nh")
Well spotted, this shouldn't have been committed in the first place. I have force-pushed removing those two private methods.

2017-04-27 09:31 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/BasePaymentProvider.java
> +        return sendReceive(null, request, order, clazz, responseIdentifier);
I am not keen to doing that now. I think in general this area require improvement but as it is shared with other gateways it should be a separate piece of work.

2017-04-27 09:48 UTC, daniele-occhipinti commented on src/main/java/uk/gov/pay/connector/service/BasePaymentProvider.java
> +        return sendReceive(null, request, order, clazz, responseIdentifier);
OK, that makes sense - I will create a separate ticket for it and general refactoring.

2017-04-27 11:02 UTC, daniele-occhipinti approved these changes

2017-04-27 11:03 UTC, merged