PP-1924 epdq cancel support
alphagov/pay-connector pull request #384
Opened 2017-05-02 16:04 UTC by mrlumbu

- Added extra statuses `USER CANCEL SUBMITTED`, `SYSTEM CANCEL SUBMITTED`,
`EXPIRE CANCEL SUBMITTED`, to handle fact that ePDQ can return 'cancel in progress' response.
- Added ePDQ cancel response class that handles cancel and submitted statuses
- Implemented cancel for ePDQ payment provider

- Previously the cancel integration test did not actually test whether the
cancellation had been successful, so effectively was not testing anything.
This commit adds a check that the charge after cancellation is in the correct
state.

with @daniele-occhipinti and @ckalista

2017-05-02 16:05 UTC, mrlumbu commented
rebuild

2017-05-02 16:07 UTC, mrlumbu commented
rebuild

2017-05-04 17:04 UTC, alexbishop1 requested changes
Looks very good overall but I’ve suggested a couple of simple-to-implement simplifications that I think are worth examining.

2017-05-04 17:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/DefaultStateTransitions.java
> +            .put(EXPIRE_CANCEL_READY,           validTransitions(EXPIRE_CANCEL_FAILED, EXPIRED, EXPIRE_CANCEL_SUBMITTED))
Really minor but could you put `EXPIRE_CANCEL_SUBMITTED` first in the array to be consistent with `CAPTURE_READY` (and do the same for the transitions for `SYSTEM_CANCEL_READY` and `USER_CANCEL_READY`)?

2017-05-04 17:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/ChargeCancelService.java
> +        return statusFlow.getFailureTerminalState();
I think this can be simplified to this:

```java
return cancelResponse.getBaseResponse().map(response -> {
     switch (response.cancelStatus()) {
        case CANCELLED:
            return statusFlow.getSuccessTerminalState();
        case SUBMITTED:
            return statusFlow.getSubmittedState();
        default:
            return statusFlow.getFailureTerminalState();
        }
}).orElse(statusFlow.getFailureTerminalState());
```

If we examine the original code, I think this is an exhaustive list of how the input conditions map to the outputs:

* `cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.CANCELLED` → `statusFlow.getSuccessTerminalState()`
* `cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.SUBMITTED` → `statusFlow.getSubmittedState()`
* `cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.ERROR` → `statusFlow.getFailureTerminalState()`
* `cancelResponse.isSuccessful() && !cancelResponse.getBaseResponse().isPresent()` → `NoSuchElementException` (unreachable?)
* `!cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.CANCELLED` → `statusFlow.getSuccessTerminalState()`
* `!cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.SUBMITTED` → `statusFlow.getSubmittedState()`
* `!cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.ERROR` → `statusFlow.getFailureTerminalState()`
* `!cancelResponse.isSuccessful() && !cancelResponse.getBaseResponse().isPresent()` → `statusFlow.getFailureTerminalState()`

Note the line I have marked as unreachable: I assume that we are working on the assumption that `cancelResponse.isSuccessful() && !cancelResponse.getBaseResponse().isPresent()` will never happen.

If we play through the same inputs with the code suggested above, we get these outputs:

* `cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.CANCELLED` → `statusFlow.getSuccessTerminalState()`
* `cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.SUBMITTED` → `statusFlow.getSubmittedState()`
* `cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.ERROR` → `statusFlow.getFailureTerminalState()`
* `cancelResponse.isSuccessful() && !cancelResponse.getBaseResponse().isPresent()` → `statusFlow.getFailureTerminalState()` (unreachable?)
* `!cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.CANCELLED` → `statusFlow.getSuccessTerminalState()`
* `!cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.SUBMITTED` → `statusFlow.getSubmittedState()`
* `!cancelResponse.isSuccessful() && cancelResponse.getBaseResponse().isPresent() && CancelStatus.ERROR` → `statusFlow.getFailureTerminalState()`
* `!cancelResponse.isSuccessful() && !cancelResponse.getBaseResponse().isPresent()` → `statusFlow.getFailureTerminalState()`

Apart from the unreachable one, the outputs are the same. So I think the suggested code above would be an appropriate replacement.

2017-05-04 17:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/ChargeExpiryService.java
> +        return statusFlow.getFailureTerminalState();
You can probably do a similar simplification to the one I suggested above here.

2017-05-04 17:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqCancelResponse.java
> +        if (CANCELLED.equals(status)) {
Could use a `switch` statement rather than a series of `if`s here.

2017-05-04 17:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqCancelResponse.java
> +        return null;
Pondering why it’s `null` rather than `Optional.empty()` but as this is overriding a method in an existing base class, I suspect that ship has already sailed.

2017-05-05 09:15 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/service/ChargeCancelService.java
> +        return statusFlow.getFailureTerminalState();
Top class reviewing, that

2017-05-05 14:10 UTC, daniele-occhipinti commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqCancelResponse.java
> +        return null;
That's indeed the case.

2017-05-05 14:17 UTC, daniele-occhipinti commented on src/main/java/uk/gov/pay/connector/service/ChargeCancelService.java
> +        return statusFlow.getFailureTerminalState();
Simply awesome, Alex!

2017-05-08 16:05 UTC, alexbishop1 approved these changes

2017-05-08 16:05 UTC, merged