PP-1500 Added missing integration tests for EPDQ notification endpoint
alphagov/pay-connector pull request #405
Opened 2017-07-06 14:21 UTC by ckalista

## WHAT
_A brief description of the pull request:_

A new endpoint for handling EPDQ notifications has been introduced with an oversight to provide proper integration test coverage for it. `EpdqNotificationResourceITest` rectifies this.

2017-07-06 14:52 UTC, ckalista commented
rebuild

2017-07-07 11:17 UTC, alexbishop1 requested changes
Looks good but a few references to Worldpay slipped through!

I think it would be valuable to add a test to check nothing happens to the payment if the SHASIGN isn’t correct.

2017-07-07 11:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqNotificationResourceITest.java
> +    private static final String RESPONSE_EXPECTED_BY_WORLDPAY = "[OK]";
I don’t think so!

2017-07-07 11:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqNotificationResourceITest.java
> +    public void shouldHandleAWorldpayNotification() throws Exception {
Still not Worldpay!

2017-07-07 13:21 UTC, ckalista commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqNotificationResourceITest.java
> +    private static final String RESPONSE_EXPECTED_BY_WORLDPAY = "[OK]";
Indeed and addressed.

2017-07-07 13:21 UTC, ckalista commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqNotificationResourceITest.java
> +    public void shouldHandleAWorldpayNotification() throws Exception {
Addressed.

2017-07-07 13:21 UTC, ckalista commented
All code review suggestions have been applied.

2017-07-07 14:24 UTC, alexbishop1 submitted a review, later dismissed

2017-07-07 14:24 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqNotificationResourceITest.java
> +    private static final String RESPONSE_EXPECTED_BY_EPDQ = "[OK]";
I don’t think ePDQ actually care, so maybe we shouldn’t assert this

2017-07-11 10:04 UTC, alexbishop1 approved these changes

2017-07-11 12:46 UTC, merged