PP-8693 Return 402 for gateway errors
alphagov/pay-connector pull request #4145
Opened 2022-11-08 12:00 UTC by james-peacock-gds

## WHAT YOU DID
- Connector currently returns 500 when there are gateway errors.
- When front end receives 500 from connector this implies the problem is with connector rather than with the PSP, and causes unnecessary alerts.
- Instead 402 will now be returned when there are gateway errors.
- A change will also be made to the front end so that it handles 402. Front end will display the same error page to the user as it does for 500.

2022-11-08 16:14 UTC, kbottla requested changes

2022-11-08 16:14 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/paymentprocessor/resource/CardResource.java
> +import static uk.gov.pay.connector.util.ResponseUtil.*;
Think the IDE setting needs to change. We don't use wildcard imports https://gds-way.cloudapps.digital/manuals/programming-languages/java.html#imports

2022-11-08 16:14 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +import static javax.ws.rs.core.Response.Status.*;
Same here for wild card imports

2022-11-08 16:14 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/worldpay/WorldpayCardResourceIT.java
> +import static javax.ws.rs.core.Response.Status.*;
Wildcard imports

2022-11-08 16:15 UTC, kbottla commented
depends on https://github.com/alphagov/pay-frontend/pull/3171

2022-11-08 16:43 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/paymentprocessor/resource/CardResource.java
> +import static uk.gov.pay.connector.util.ResponseUtil.*;
thanks, have corrected preferences and made changes

2022-11-08 16:43 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/worldpay/WorldpayCardResourceIT.java
> +import static javax.ws.rs.core.Response.Status.*;
done

2022-11-08 16:44 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +import static javax.ws.rs.core.Response.Status.*;
done

2022-11-09 14:16 UTC, kbottla approved these changes
LGTM! We should also update API specs for all endpoints but can be done in a separate PR  https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/paymentprocessor/resource/CardResource.java#L143

2022-11-09 14:34 UTC, merged