PP-10314 log errors for Stripe payment rejection
alphagov/pay-connector pull request #4173
Opened 2022-11-22 14:58 UTC by SandorArpa

## WHAT YOU DID
- log error code and message for Stripe 3DS failed payments
- log `outcome` for both 3DS and non-3DS payment failures

2022-11-23 12:10 UTC, kbottla commented on openapi/connector_spec.yaml
> +        stripeNotificationLog:
Can we exclude this field as this is not something required for `/v1/frontend/charges/{chargeId}/3ds` endpoint?

2022-11-23 12:10 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/model/Auth3dsResult.java
> +    private String stripeNotificationLog;
Can this be renamed to something like gatewayResponse or gatewayResponseStringified? It is not a log.

2022-11-23 12:10 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/model/response/Gateway3DSAuthorisationResponse.java
> +    public static Gateway3DSAuthorisationResponse of(String stringified, BaseAuthoriseResponse.AuthoriseStatus authorisationStatus, Gateway3dsRequiredParams gateway3dsRequiredParams) {
Is the method on line 58 still required?
`    public static Gateway3DSAuthorisationResponse of(BaseAuthoriseResponse.AuthoriseStatus authorisationStatus, Gateway3dsRequiredParams gateway3dsRequiredParams) {
`

2022-11-23 12:10 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeNotificationService.java
> +            String logs = StripeNotificationLogBuilder.buildLogString(paymentIntent);
Can we have a method on Payment intent ? It could be something like `paymentIntent.stringify()`. This way it could be used for Non-3DS payments too.

2022-11-23 12:10 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/StripeNotificationLogBuilder.java
> +public class StripeNotificationLogBuilder {
Can we name it something like PaymentIntentStringifier?

2022-11-23 12:10 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/StripeNotificationLogBuilder.java
> +    public static String buildLogString(StripePaymentIntent paymentIntent) {
Maybe `stringify` for name?

2022-11-23 12:10 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/StripeNotificationLogBuilder.java
> +            if (charge.getStatus() != null && charge.getStatus().equals("failed")) {
Don't think we need to check for failed status. 

We can just append fields if they are not null.

2022-11-23 13:26 UTC, SandorArpa commented on openapi/connector_spec.yaml
> +        stripeNotificationLog:
👍

2022-11-23 13:26 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/model/Auth3dsResult.java
> +    private String stripeNotificationLog;
👍

2022-11-23 13:26 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/model/response/Gateway3DSAuthorisationResponse.java
> +    public static Gateway3DSAuthorisationResponse of(String stringified, BaseAuthoriseResponse.AuthoriseStatus authorisationStatus, Gateway3dsRequiredParams gateway3dsRequiredParams) {
👍

2022-11-23 13:26 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeNotificationService.java
> +            String logs = StripeNotificationLogBuilder.buildLogString(paymentIntent);
👍

2022-11-23 13:27 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/StripeNotificationLogBuilder.java
> +public class StripeNotificationLogBuilder {
👍

2022-11-23 13:27 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/StripeNotificationLogBuilder.java
> +    public static String buildLogString(StripePaymentIntent paymentIntent) {
👍

2022-11-24 17:37 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/StripeNotificationLogBuilder.java
> +            if (charge.getStatus() != null && charge.getStatus().equals("failed")) {
👍

2022-11-25 10:17 UTC, kbottla requested changes

2022-11-25 10:17 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/model/response/Gateway3DSAuthorisationResponse.java
> +    public static Gateway3DSAuthorisationResponse of(String stringified, BaseAuthoriseResponse.AuthoriseStatus authorisationStatus, Gateway3dsRequiredParams gateway3dsRequiredParams) {
Can the field be renamed for readability?
```suggestion
    public static Gateway3DSAuthorisationResponse of(String stringifiedResponse, BaseAuthoriseResponse.AuthoriseStatus authorisationStatus, Gateway3dsRequiredParams gateway3dsRequiredParams) {
```

2022-11-25 10:17 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeNotificationService.java
> +import uk.gov.pay.connector.gateway.stripe.util.PaymentIntentStringifier;
Unused import?

2022-11-25 10:17 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifier.java
> +                joiner.add(format("Stripe authorisation %s response ", charge.getStatus()));
Of all the fields, only payment_intent_id is available all the time on the PaymentIntent object. charge, outcome, charge status and so on won't be available for specific scenarios (ex: payment intent cancelled - `bdtrk4saeteeekkedr713id4sr`). So we should add fields only when they are not null.

`Stripe authorisation response` can be outside of any `map(->`. And we can also add payment intent id. The rest of the fields are optional.

2022-11-25 10:17 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifier.java
> +        optionalStripeCharge.map(charge -> {
There is another `optionalStripeCharge.map(charge -> {` on line 20. Can these be combined?

2022-11-28 11:19 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/model/response/Gateway3DSAuthorisationResponse.java
> +    public static Gateway3DSAuthorisationResponse of(String stringified, BaseAuthoriseResponse.AuthoriseStatus authorisationStatus, Gateway3dsRequiredParams gateway3dsRequiredParams) {
👍

2022-11-28 11:21 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeNotificationService.java
> +import uk.gov.pay.connector.gateway.stripe.util.PaymentIntentStringifier;
👍

2022-11-28 11:22 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifier.java
> +                joiner.add(format("Stripe authorisation %s response ", charge.getStatus()));
👍

2022-11-28 11:22 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifier.java
> +        optionalStripeCharge.map(charge -> {
👍

2022-11-28 17:14 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifier.java
> +            delimitedJoiner.add("status: " + charge.getStatus());
Can we move this to the bottom as the last item appended? so the order of fields is consistent with https://github.com/alphagov/pay-connector/pull/4173/files#diff-811d702926cff03115e3b417441012ac0a206ff3162780d816af654aae54075eR67

2022-11-28 17:38 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifier.java
> +            delimitedJoiner.add("status: " + charge.getStatus());
👍

2022-11-28 20:47 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifier.java
> +            delimitedJoiner.add("code: " + charge.getFailureCode());
I think this is still not addressed? https://github.com/alphagov/pay-connector/pull/4173#discussion_r1031894344 

> we should add fields only when they are not null.

Also applicable for `appendOutcomeLogs`

2022-11-30 11:02 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifier.java
> +            delimitedJoiner.add("code: " + charge.getFailureCode());
👍

2022-11-30 15:07 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifierTest.java
> +        assertThat(stringified, containsString("outcome.type: issuer_declined"));
Can we add an assertion for `decline code:` too?

2022-11-30 15:23 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/gateway/stripe/util/PaymentIntentStringifierTest.java
> +        assertThat(stringified, containsString("outcome.type: issuer_declined"));
👍

2022-11-30 15:51 UTC, kbottla approved these changes

2022-11-30 15:51 UTC, merged