PP-2422 Send ePDQ refund requests and handle immediate responses
alphagov/pay-connector pull request #418
Opened 2017-08-01 14:01 UTC by SandorArpa

Sends `RFD` (partial refund) requests to ePDQ. Expects either status `81` (refund pending) or `71` (deletion pending) responses (usually be 81 but can be 71 if the capture has not yet been processed), which become `REFUND SUBMITTED`. Other responses become `REFUND ERROR`.

Refund references are constructed by concatenating the `PAYID` (gateway transaction ID) with a solidus followed by the `PAYIDSUB` (number that increments with each operation) from the response. The same `PAYID` and `PAYIDSUB` will be included in the subsequent notification, which will allow us to do the lookup by reference.

Pseudo feature flag (hardcoded boolean set to true for tests and false for real) used to stop refunds from working because we haven’t added support for handling the subsequent notifications yet. This means that pressing the refund button in selfservice or using publicapi will continue to display an error as it currently does.

with @juanjoqmelian
with @alexbishop1

2017-08-01 14:33 UTC, SandorArpa commented
rebuild

2017-08-02 09:46 UTC, ckalista requested changes
Looks good. 

Just wondering since we have decided to handle status `71` which according to the comment could only happen if the payment hasn't been captured:
- is it even possible to have such an occurrence considering we only allow refunds post full capture of a charge.
- if it is a valid genuine scenario, what do we do with these refunds?

Also would you be able to add a little bit more context in the commit message. There are a few changes worth documenting in the commit message.

2017-08-02 09:46 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqRefundResponse.java
> +        return Optional.of(transactionId + "/" + payIdSub);
Careful here - if for whatever reason either `payIdSub` OR `transactionId` is empty or null we should probably assume we don't have a valid reference. For instance consider a situation where we are not able to extract the `payIdSub` and hence build a reference which is always the same `trasactionId` + `/` for all refunds for that particular payment, - although very unlikely I am sure it could lead to some strange mismatches.

2017-08-02 09:46 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForMaintenanceOrder.java
> +        String amount = templateData.getAmount();
Is it mandated by Barclay to have the amount as first parameter? If not maybe better to push it down a bit for readability, possibly after `PSW_KEY`?

2017-08-02 10:00 UTC, alexbishop1 commented
> Just wondering since we have decided to handle status 71 which according to the comment could only happen if the payment hasn't been captured:
> • is it even possible to have such an occurrence considering we only allow refunds post full capture of a charge.
> • if it is a valid genuine scenario, what do we do with these refunds?

According to ePDQ, we can actually get a `71` if the payment is in status `9` (“the time scale for the deletion option showing instead of refund can be closer to 24-36 hours, and so it is still possible to delete a transaction in status `9`”). From our perspective, we treat it just like any other refund: whether ePDQ treat it as a true refund or a deletion doesn’t matter to us; we just need to make sure we handle all the possible statuses.

> Also would you be able to add a little bit more context in the commit message. There are a few changes worth documenting in the commit message.

Yeah, was thinking that. Will rewrite the commit message to make it more like the pull request description.

2017-08-02 10:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqRefundResponse.java
> +        return Optional.of(transactionId + "/" + payIdSub);
Yes, that `&&` should be a `||`.

2017-08-02 10:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForMaintenanceOrder.java
> +        String amount = templateData.getAmount();
It’s not actually required that the parameters are in alphabetical order (that comment is a bit outdated) but we do have to sort the parameters alphabetically in order to calculate the SHA signature. So I’m inclined to keep them in alphabetical order always.

2017-08-02 10:48 UTC, ckalista commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForMaintenanceOrder.java
> +        String amount = templateData.getAmount();
Sure, I don't really have a preference so long as there is some rational let's leave as it is.

2017-08-02 11:42 UTC, alexbishop1 commented
Addressed comments, rewrote original commit message, added new integration test, changed pseudo feature flag to real feature flag (to facilitate integration test). Can you take another look please, @ckalista?

2017-08-02 11:44 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqRefundResponse.java
> +        return Optional.of(transactionId + "/" + payIdSub);
Fixed (by amending original commit).

2017-08-02 12:45 UTC, ckalista approved these changes

2017-08-02 12:45 UTC, merged