PP-2398 Added refund history capabilities
alphagov/pay-connector pull request #424
Opened 2017-08-16 14:26 UTC by ckalista

## WHAT
_A brief description of the pull request:_

- Leveraged `EclipseLink` extended support for tracking all changes made to `refunds` table. The `EclipseLink HistoryPolicy` has been configured on a `ClassDescriptor` via a custom `HistoryCustomizer` which one enabled with the appropriate `@Customizer` annotation on the `RefundEntity` will insert a row into the `refunds_history` table on every update to the primary `refunds` table to track the rows state. The history table also defines a start and end timestamp, so that the state of any row at any point in time can be determined.
- The `liquidbase` migration script was updates to add the `refunds_history` table in the database schema.
- Added an index on the `refunds_history` table to optimise performances while searching the history by `charge_id`.
- A POJO called `RefundHistory` was introduced as a data holder for refund history
   entries. It comes with appropriate SQL result set mappings to enable JPA native queries
   to map result sets direclty onto it.
- `RefundDao` was extended with a `searchHistoryByChargeId` method as its name implies allowing to search refunds by `chargeId` from the history.
- `ChargeEventsResource` has been reworked to incorporate refund events in its response messages. The structure of an event in the payload has been extended with a discriminator representative of the type of event which can be either: `PAYMENT` or `REFUND`. All events are listed in ascending order according to the `update` date.

2017-08-16 14:59 UTC, maxcbc commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceITest.java
> +        return
Does this need a new line between `return` and `with`?

2017-08-16 14:59 UTC, maxcbc commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceITest.java
> +                withDatabaseTestHelper(databaseTestHelper)
Does this need a new line between return and with?

2017-08-16 17:03 UTC, ckalista commented
Addressed code review comments from @maxcbc

2017-08-21 09:20 UTC, rauligs requested changes
Just one comment. It looks good!

2017-08-21 09:20 UTC, rauligs commented on src/main/java/uk/gov/pay/connector/model/domain/RefundHistory.java
> +        setCreatedDate(new UTCDateTimeConverter().convertToEntityAttribute(createdDate));
New instance of UTCDateTimeConverter per RefundHistory, can this be extracted? Same in HistoryStartDate and HistoryEndDate

2017-08-30 08:42 UTC, rauligs approved these changes

2017-08-30 08:45 UTC, merged