PP-2399 show which user issued the refund
alphagov/pay-connector pull request #435
Opened 2017-08-31 10:46 UTC by ebiere

## WHAT
Show who issued the refund

## HOW 
Call the refund API populating the refundedBy parameter in the refund request object.
The refund object created contains the details populated in the request object refundedby parameter

2017-08-31 11:21 UTC, alexbishop1 requested changes
Functionally this looks like it should do the job but the tests cop out a bit by using null everywhere so we’re not really checking that we actually store the new data.

The branch needs rebasing and the commits should be squashed into one (we literally have commits that undo changes in previous commits, which is noise we don’t want in our revision history!).

Also, have we already had a conversation about the benefits of storing a string versus a reference to the user who issued the refund? Both have advantages and disadvantages but I think it’s worth having a broader discussion if we haven’t already (entirely possible this happened when I was elsewhere and I missed it but now is a good time to check before we go too far down the current path).

2017-08-31 11:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/ChargeRefundService.java
> +            logger.info("Card refund request sent - charge_external_id={}, status={}, amount={}, transaction_id={}, account_id={}, operation_type=Refund, amount_available_refund={}, amount_requested_
Change `refundedBy` to `refunded_by` to match the snake case we use in the logging please

2017-08-31 11:21 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +    <changeSet id="add refundedBy column to refunds table" author="">
Should be `refunded_by` to match the column name

2017-08-31 11:21 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +    <changeSet id="add refundedBy column to refunds_history table" author="">
Should be `refunded_by` to match the column name

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +        return RefundGatewayRequest.valueOf(new RefundEntity(chargeEntity, refundAmount, null));
I think we might want to pass an actual dummy value here rather than null. Although we allow the column in the database to be `null` to account for the fact that we did not record this data in the past, in the future we should always record a user when we create a refund, so there `null` will never be passed to the constructor. I think it would be clearer if the test reflected this.

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/SmartpayPaymentProviderTest.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, 1L, null);
Again, might want to pass an actual value here

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/WorldpayPaymentProviderTest.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, 1L, null);
Again, might want to pass an actual value here

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/RefundDaoJpaITest.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, 100L, null);
This should use an actual value and assert that the refund stores this value

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/RefundDaoJpaITest.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, 100L, null);
Again, this should use an actual value and assert that the refund stores this value

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/RefundDaoJpaITest.java
> +        RefundEntity refundEntity1 = new RefundEntity(chargeEntity, 100L, null);
Again, this should use an actual value and assert that the refund stores this value

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/RefundDaoJpaITest.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, 100L, null);
Again, this should use an actual value and assert that the refund stores this value

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/RefundEntityFixture.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, amount, null);
Another case where I think we want to use an actual value

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/RefundEntityTest.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, amount, null);
Again, this should use an actual value and assert that the refund stores this value

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        ChargeRefundService.Response gatewayResponse = chargeRefundService.doRefund(accountId, externalChargeId, new RefundRequest(amount, charge.getAmount(), null)).get();
You know what I’m going to say here: use a real value and check it’s stored

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        ChargeRefundService.Response gatewayResponse = chargeRefundService.doRefund(accountId, externalChargeId, new RefundRequest(amount, charge.getAmount(), null)).get();
…

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        ChargeRefundService.Response gatewayResponse = chargeRefundService.doRefund(accountId, externalChargeId, new RefundRequest(amount, charge.getAmount(), null)).get();
…

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        ChargeRefundService.Response gatewayResponse = chargeRefundService.doRefund(accountId, externalChargeId, new RefundRequest(amount, charge.getAmount(), null)).get();
…

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        ChargeRefundService.Response gatewayResponse = chargeRefundService.doRefund(accountId, externalChargeId, new RefundRequest(amount, charge.getAmount(), null)).get();
…

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +            chargeRefundService.doRefund(accountId, externalChargeId, new RefundRequest(100L, 0, null));
…

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +            chargeRefundService.doRefund(accountId, externalChargeId, new RefundRequest(100L, 0, null));
…

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        ChargeRefundService.Response gatewayResponse = chargeRefundService.doRefund(accountId, externalChargeId, new RefundRequest(amount, capturedCharge.getAmount(), null)).get();
…

2017-08-31 11:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProviderTest.java
> +        return RefundGatewayRequest.valueOf(new RefundEntity(chargeEntity, chargeEntity.getAmount() - 100, null));
…

2017-08-31 11:42 UTC, ebiere commented on src/main/java/uk/gov/pay/connector/service/ChargeRefundService.java
> +            logger.info("Card refund request sent - charge_external_id={}, status={}, amount={}, transaction_id={}, account_id={}, operation_type=Refund, amount_available_refund={}, amount_requested_
done

2017-08-31 11:42 UTC, ebiere commented on src/main/resources/migrations.xml
> +    <changeSet id="add refundedBy column to refunds table" author="">
done

2017-08-31 11:42 UTC, ebiere commented on src/main/resources/migrations.xml
> +    <changeSet id="add refundedBy column to refunds_history table" author="">
done

2017-08-31 11:53 UTC, ebiere commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +        return RefundGatewayRequest.valueOf(new RefundEntity(chargeEntity, refundAmount, null));
Dummy value passed.
This data is not persisted in this instance because RefundEntity is only acting as a DTO for the RefundGatewayRequest.... So it is not persisted during this gateway call process...

2017-08-31 11:56 UTC, ebiere commented on src/test/java/uk/gov/pay/connector/it/contract/SmartpayPaymentProviderTest.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, 1L, null);
Dummy value passed.
This data is not persisted in this instance because RefundEntity is only acting as a DTO for the RefundGatewayRequest.... So it is not persisted during this gateway call process...

2017-08-31 11:57 UTC, ebiere commented on src/test/java/uk/gov/pay/connector/it/contract/WorldpayPaymentProviderTest.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, 1L, null);
Dummy value passed.
This data is not persisted in this instance because RefundEntity is only acting as a DTO for the RefundGatewayRequest.... So it is not persisted during this gateway call process...

2017-09-01 14:22 UTC, alexbishop1 requested changes
Pretty close but I think we need to take another look at the naming and not forget to update the documentation

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/RefundRequest.java
> +    @JsonProperty("refunded_by")
Given that we have now decided that this will contain the external ID of the user who issued the refund, we might want to think again about the name. Probably `user_external_id` (seems to match the existing convention for external IDs in internal APIs).

Also, the connector API specification should be updated to document this field.

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/RefundRequest.java
> +    private String refundedBy;
Again, name should probably be `userExternalId` or something

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/RefundRequest.java
> +        this.refundedBy = refundedBy;
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/RefundRequest.java
> +    public String getRefundedBy() { return refundedBy; }
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/RefundResponse.java
> +                .addProperty("refunded_by", refundEntity.getRefundedBy())
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/RefundEntity.java
> +    @Column(name = "refunded_by")
The name of the column should probably be `user_external_id` (we don’t seem to have any database columns that refer to external IDs in other databases but this seems like a reasonable convention)

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/RefundEntity.java
> +    private String refundedBy;
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/RefundEntity.java
> +        this.refundedBy = refundedBy;
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/RefundEntity.java
> +        return refundedBy;
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/RefundEntity.java
> +        this.refundedBy = refundedBy;
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/RefundEntity.java
> +                ", refundedBy='" + refundedBy + '\'' +
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/RefundHistory.java
> +        setRefundedBy(refundedBy);
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/ChargeRefundService.java
> +            logger.info("Card refund request sent - charge_external_id={}, status={}, amount={}, transaction_id={}, account_id={}, operation_type=Refund, amount_available_refund={}, amount_requested_
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +            <column name="refunded_by" type="text">
Don’t forget to update this (and the ID!)

2017-09-01 14:22 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +            <column name="refunded_by" type="text">
Don’t forget to update this (and the ID!)

2017-09-01 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/RefundDaoJpaITest.java
> +        assertThat(refundByIdFound.get(0), hasEntry("refunded_by", refundedBy));
Another place where the name should probably be updated

2017-09-01 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/RefundEntityFixture.java
> +    public static String refundedBy = "Alex";
Although I’m flattered, we should probably make this hexadecimal like an external ID (also rename the field)

2017-09-01 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/RefundEntityTest.java
> +        RefundEntity refundEntity = new RefundEntity(chargeEntity, amount, refundedBy);
Can you add an assertion to `shouldConstructANewEntity` please to check the getter returns this please?

2017-09-01 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/DatabaseTestHelper.java
> +                h.createQuery("SELECT external_id, reference, amount, status, created_date, charge_id, refunded_by " +
Don’t forget to update this

2017-09-01 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/DatabaseTestHelper.java
> +                h.createQuery("SELECT external_id, reference, amount, status, created_date, charge_id, refunded_by " +
Don’t forget to update this

2017-09-01 14:25 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        ChargeRefundService.Response gatewayResponse = chargeRefundService.doRefund(accountId, externalChargeId, new RefundRequest(amount, charge.getAmount(), null)).get();
Actual probably don’t need to check it’s stored (the other tests don’t check every single property, presumably because the other tests probably cover this well enough)

2017-09-04 10:05 UTC, alexbishop1 requested changes
Looks good but please use hex for the doc/test external user IDs and squash the two commits into one

2017-09-04 10:05 UTC, alexbishop1 commented on docs/api_specification.md
> +    "user_external_id": "Alex"
Make this something hexadecimal (because that’s what it will be) please

2017-09-04 10:05 UTC, alexbishop1 commented on docs/api_specification.md
> +    "user_external_id":"Alex",
Also should be hex

2017-09-04 10:05 UTC, alexbishop1 commented on docs/api_specification.md
> +                "user_external_id":"Alex",
Hex

2017-09-04 10:05 UTC, alexbishop1 commented on docs/api_specification.md
> +    "user_external_id": "Alex",
Hex

2017-09-04 10:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/RefundEntityFixture.java
> +    public static String userExternalId = "Alex";
Hex!

2017-09-04 10:47 UTC, alexbishop1 approved these changes
I think external IDs are always lower-case hex but close enough

2017-09-04 12:00 UTC, merged