WIP - PP-10512-Implement-deleteStoredPaymentDetails-for-Worldpay
alphagov/pay-connector pull request #4383
Opened 2023-03-09 15:33 UTC by james-peacock-gds

* DRAFT *
- Add Worldpay implementation for deleteStoredPaymentDetails interface method
- Build delete token order applying agreement and paymentTokenID to template

2023-03-13 10:26 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                .withMerchantCode(AuthUtil.getWorldpayMerchantCode(request.getGatewayCredentials(), request.getAuthorisationMode()))
This is an interesting one - as there isn't an "authorisation mode" associated with this request.

Possibly we need a method in `AuthUtil` that directly gets the credentials used for managing tokens without providing an authorisation mode and call that here. I think these credentials will be the credentials used to create the token (authorisation mode `WEB`), rather than the credentials used to take recurring payments. Although maybe we can use either?

2023-03-13 11:05 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/queue/tasks/handlers/DeleteStoredPaymentDetailsTaskHandler.java
> +        } catch (GatewayException ex) {
I don't think we should catch this exception as this will mean we silently fail to delete the token and don't retry. We should propagate it up to the TaskQueueMessage handler, where it will be caught and handled appropriately.
If `TaskQueueMessageHandler` handles an exception, it will not mark the SQS message as processed, and so it will be retried some time later. If processing the message repeatedly fails, the message will be sent to a dead letter queue and we will get alerted to Zendesk for support to investigate.

2023-03-13 12:37 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                .withMerchantCode(AuthUtil.getWorldpayMerchantCode(request.getGatewayCredentials(), request.getAuthorisationMode()))
new method added as discussed

2023-03-13 12:38 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/queue/tasks/handlers/DeleteStoredPaymentDetailsTaskHandler.java
> +        } catch (GatewayException ex) {
changed as requested.

2023-03-13 14:38 UTC, stephencdaly requested changes

2023-03-13 14:38 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +    public static Map<String, String> getGatewayAccountCredentialsForManagingTokens(Map<String, Object> gatewayCredentials) {
This is more for constructing an auth header using the appropriate credentials set out of the credentials - so maybe it should be called something like `getAuthHeaderForManagingTokens` or `getGatewayAccountCredentialsForManagingTokensAsAuthHeader` (quite long) if you want to match the other methods.

2023-03-13 14:38 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                                   @Named("WorldpayDeleteTokenGatewayClient") GatewayClient deleteTokenClient, WorldpayWalletAuthorisationHandler worldpayWalletAuthorisationHandler,
could you put the WorldpayWalletAuthorisationHandler argument on the next line please?

2023-03-13 14:38 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                getGatewayAccountCredentialsAsAuthHeader(request.getGatewayCredentials(), null));
We should use our new method in AuthUtils for getting the authorization header for managing tokens

2023-03-13 14:38 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        return getWorldpayDeleteTokenGatewayResponse(response);
I don't think this method actually needs to return anything as we don't use the response. For Stripe we won't return anything from the method that makes the request - we know its successful if no exception is thrown. So I think this method and `paymentProvider#deleteStoredPaymentDetails` can both return `void`

2023-03-13 14:38 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                .withMerchantCode(AuthUtil.getWorldpayMerchantCode(request.getGatewayCredentials(), request.getAuthorisationMode()))
We've added a new method for getting the authorisation header - we need one for getting the merchant code without having to provide and authorisation mode and need to call it from here too.

2023-03-13 14:38 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +    public GatewayResponse<WorldpayDeleteTokenResponse> deleteStoredPaymentDetails(DeleteStoredPaymentDetailsGatewayRequest request) throws GatewayException {
I think we need a non-"contract" test for this that checks that we build the XML to send to Worldpay correctly. The "contract" test isn't run on CI and is just for locally verifying changes work with the actual Worldpay gateway. We need a test that will run on CI to provide proper coverage.

`src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java` would be an appropriate place for this, and there are other tests there that do assertions on the XML sent to Worldpay

2023-03-13 17:55 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                .withMerchantCode(AuthUtil.getWorldpayMerchantCode(request.getGatewayCredentials(), request.getAuthorisationMode()))
this has now been added

2023-03-13 17:55 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +    public static Map<String, String> getGatewayAccountCredentialsForManagingTokens(Map<String, Object> gatewayCredentials) {
name updated

2023-03-13 17:55 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                                   @Named("WorldpayDeleteTokenGatewayClient") GatewayClient deleteTokenClient, WorldpayWalletAuthorisationHandler worldpayWalletAuthorisationHandler,
done

2023-03-13 17:55 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                getGatewayAccountCredentialsAsAuthHeader(request.getGatewayCredentials(), null));
done

2023-03-13 17:56 UTC, james-peacock-ho commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        return getWorldpayDeleteTokenGatewayResponse(response);
amended as requested

2023-03-13 17:56 UTC, james-peacock-ho commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +    public GatewayResponse<WorldpayDeleteTokenResponse> deleteStoredPaymentDetails(DeleteStoredPaymentDetailsGatewayRequest request) throws GatewayException {
tests added for payload and headers

2023-03-14 10:37 UTC, stephencdaly approved these changes
LGTM!

2023-03-14 10:37 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        assertThat(headers.getValue().get(AUTHORIZATION), is(expectedHeader));
As the setup for this test is the same as for the other test you've added - my opinion would be that its better to just add the additional assertions to the same test.

2023-03-14 10:41 UTC, merged