PP-2576 Add refund created in sandbox
alphagov/pay-connector pull request #441
Opened 2017-09-11 15:54 UTC by maxcbc

# PP-2576 Add refund created in sandbox
with @SandorArpa

## WHY
Refund submitted isn't showing in the transaction events (in Sandbox)

## WHAT
* Made sandbox refund lifecycle mirror gateway refund lifecycle
i.e. CREATED -> REFUND SUBMITTED -> REFUNDED

## HOW
* Added additional step when creating a refund if creation is successful and using a sandbox account where the refund is automatically moved to a REFUNDED status

2017-09-12 08:07 UTC, rauligs requested changes
I have made some suggestions. We can discuss them later

2017-09-12 08:07 UTC, rauligs commented on src/main/java/uk/gov/pay/connector/service/ChargeRefundService.java
> +                    Optional<Response> refundResult = refundWithGateway(chargeEntity, refundRequest);
- I would add an executeNext() step keeping all a bit separated filtering out those Responses not Sandbox
- I would make it a bit cleaner by doing something the filter using.

```
 private Optional<Response> refundWithGateway(ChargeEntity charge, RefundRequest refundRequest) {
        return Optional.ofNullable(transactionFlowProvider.get()
                .executeNext(createRefund(providers, charge, refundRequest))
                .executeNext(doGatewayRefund(providers))
                .executeNext(setRefundAsSubmitted())
                .executeNext(setSandboxRefundAsRefunded())
                .complete().get(Response.class));
    }
```
end in that step, receiving the result response:

```
refundResult.isSandbox()
 - then set to refunded and update, return
 - otherwise just return the given response
```

It is just I would be very explicit on each step. We can discuss it

2017-09-12 08:07 UTC, rauligs commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        verify(mockRefundDao, times(2)).merge(any(RefundEntity.class));
- Rather than set number of times, I would check for one time set as SUBMITTED and a second time as REFUNDED.

2017-09-12 08:08 UTC, rauligs commented
Also needs rebasing

2017-09-26 09:36 UTC, juanjoqmelian approved these changes
LGTM

2017-09-26 09:36 UTC, juanjoqmelian commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +import static org.mockito.Mockito.*;
I'd change your IDE settings to avoid using wildcard imports. No need to change it, just to avoid it in the future.

2017-09-26 09:41 UTC, rauligs approved these changes

2017-09-26 10:07 UTC, merged