PP-10864 remove smartpay part 3
alphagov/pay-connector pull request #4431
Opened 2023-03-29 13:27 UTC by SandorArpa

## WHAT YOU DID
- remove the rest of smartpay code

2023-03-30 13:55 UTC, james-peacock-gds approved these changes, later dismissed
LGTM

2023-03-30 14:57 UTC, nlsteers requested changes, later dismissed
Pinning this while we fix `staging-2`

2023-04-27 12:51 UTC, kbottla submitted a review, later dismissed

2023-04-27 12:51 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
Any reason we need to ignore unknown properties here?

2023-04-27 12:51 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/gatewayclient/ClientFactoryIT.java
> -        app = startApp("config/client-factory-test-config-with-smartpay-timeout-override.yaml", false);
Can file `client-factory-test-config-with-smartpay-timeout-override.yaml` be removed too ?

2023-04-27 12:51 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountSearchParams.java
> +    @Pattern(regexp = "sandbox|worldpay|epdq|stripe",
We still have smartpay LIVE accounts that have not switched PSP. We need this longer to be able to search in Toolbox

2023-04-27 12:51 UTC, kbottla commented on src/test/resources/config/client-factory-test-config-with-smartpay-timeout-override.yaml
This file can be removed entirely as it is no longer referenced anywhere

2023-04-27 12:59 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
👍

2023-04-27 13:00 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/gatewayclient/ClientFactoryIT.java
> -        app = startApp("config/client-factory-test-config-with-smartpay-timeout-override.yaml", false);
👍

2023-04-27 13:01 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountSearchParams.java
> +    @Pattern(regexp = "sandbox|worldpay|epdq|stripe",
👍

2023-04-27 13:01 UTC, SandorArpa commented on src/test/resources/config/client-factory-test-config-with-smartpay-timeout-override.yaml
👍

2023-05-02 08:29 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +import uk.gov.pay.connector.app.config.*;
Wildcard import?

2023-05-02 10:12 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +import uk.gov.pay.connector.app.config.*;
👍

2023-05-02 10:15 UTC, kbottla approved these changes

2023-05-02 10:15 UTC, merged