PP-2755 - Added userExternalId as 'submitted_by' in transactions events response
alphagov/pay-connector pull request #444
Opened 2017-09-15 15:17 UTC by maxcbc

- added 'submitted_by' key in transactions event response so that we can show who submitted a refund in selfservice

2017-09-18 09:59 UTC, alexbishop1 requested changes
Looks like it will do the job but I think the tests need a few tweaks

2017-09-18 09:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/DatabaseFixtures.java
> +        String submittedBy;
Maybe something to indicate this is an external ID? `submittedByUserExternalId` or something?

2017-09-18 09:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceITest.java
> +                .withSubmittedBy("ABC123")
Please yank this out to a constant and add something similar for `refundedTestRefund2` (because realistically from now on all of our refunds are going to have an associated external ID for the user who submitted it)

2017-09-18 09:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceITest.java
> +                .body("events[3]", new TransactionEventMatcher("REFUND", withState("submitted", "false"), "10", historyRefund1SubmittedStartDate, testReferenceRefund1, null))
This shouldn’t work. Our refund has a submitted by user external ID but when we do the matching we tell it that we expect the submitted by user external ID  to be null. It’s only “working” because the `matchesSafely(Map<String, Object>)` method in `TransactionEventMatcher` hasn’t been updated to compare the submitted by user external ID. Please update it to do this and change these assertions.

2017-09-18 09:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/matcher/TransactionEventMatcher.java
> +    private String submittedBy;
Maybe call this `refundSubmittedBy`

2017-09-18 09:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/TransactionEventTest.java
> +        TransactionEvent event1 = new TransactionEvent(Type.REFUND, "charge", "success", extractState(EXTERNAL_SUBMITTED), 100L, ZonedDateTime.now(),null);
Please use actual user external IDs here (and everywhere else in this file) to reflect that this will never be null in practice

2017-09-19 10:22 UTC, maxcbc commented on src/test/java/uk/gov/pay/connector/model/TransactionEventTest.java
> +        TransactionEvent event1 = new TransactionEvent(Type.REFUND, "charge", "success", extractState(EXTERNAL_SUBMITTED), 100L, ZonedDateTime.now(),null);
I've left some examples with null in. This is because it will be null if the request comes through public API

2017-09-19 12:49 UTC, maxcbc commented on src/test/java/uk/gov/pay/connector/matcher/TransactionEventMatcher.java
> +    private String submittedBy;
👍

2017-09-19 12:49 UTC, maxcbc commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceITest.java
> +                .body("events[3]", new TransactionEventMatcher("REFUND", withState("submitted", "false"), "10", historyRefund1SubmittedStartDate, testReferenceRefund1, null))
👍

2017-09-19 12:49 UTC, maxcbc commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceITest.java
> +                .withSubmittedBy("ABC123")
👍

2017-09-19 12:49 UTC, maxcbc commented on src/test/java/uk/gov/pay/connector/it/dao/DatabaseFixtures.java
> +        String submittedBy;
👍

2017-09-19 13:59 UTC, alexbishop1 requested changes
Looks good but please extract the external ID constant used in TransactionEventTest

2017-09-19 13:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/TransactionEventTest.java
> +        TransactionEvent event1 = new TransactionEvent(Type.REFUND, "charge", "success", extractState(EXTERNAL_SUBMITTED), 100L, ZonedDateTime.now(),"r378y387y8weriyi");
Extract this to a constant, please

2017-09-19 14:30 UTC, maxcbc commented on src/test/java/uk/gov/pay/connector/model/TransactionEventTest.java
> +        TransactionEvent event1 = new TransactionEvent(Type.REFUND, "charge", "success", extractState(EXTERNAL_SUBMITTED), 100L, ZonedDateTime.now(),"r378y387y8weriyi");
Done 👍

2017-09-19 15:31 UTC, alexbishop1 approved these changes

2017-09-19 16:08 UTC, merged