PP-10964 Handle Handle Stripe card_decline_rate_limit_exceeded error code as authorisation rejected
alphagov/pay-connector pull request #4558
Opened 2023-05-31 16:05 UTC by AbdirizakIdris

## WHAT YOU DID
- Updated the Stripe authorisation error handling logic to handle errors with type invalid_request_error and code ```java
card_decline_rate_limit_exceeded ``` by updating the state to ```java AUTHORISATION_REJECTED ```

2023-05-31 16:13 UTC, SandorArpa approved these changes, later dismissed
LGTM

2023-05-31 16:15 UTC, kbottla requested changes

2023-05-31 16:15 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/json/StripeAuthorisationFailedResponse.java
> +                || "invalid_request_error".equals(errorResponse.getError().getType())
The condition should be as below:

```
if (errorResponse != null && errorResponse.getError() != null
                && ("card_error".equals(errorResponse.getError().getType())
                || ("invalid_request_error".equals(errorResponse.getError().getType()) 
                && "card_decline_rate_limit_exceeded".equals(errorResponse.getError().getCode())))) {
```

For error type `invalid_request_error`, we can get different error codes. Only for `card_decline_rate_limit_exceeded` error code, payment status should be rejected.

2023-06-06 15:02 UTC, kbottla approved these changes, later dismissed

2023-06-06 15:02 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/gateway/stripe/StripeCaptureHandlerTest.java
> +        String errorResponse = load(STRIPE_ERROR_RESPONSE);
Can simplify this
```suggestion
        String errorMessage = load(STRIPE_ERROR_RESPONSE)
                              .replace("{{code}}", "resource_missing");
```

2023-06-06 15:02 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/gateway/stripe/StripeCaptureHandlerTest.java
> +        String errorResponse = load(STRIPE_ERROR_RESPONSE);
Same as above


```suggestion
        String errorMessage = load(STRIPE_ERROR_RESPONSE)
                              .replace("{{code}}", "resource_missing");
```

2023-06-06 15:02 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/gateway/stripe/StripeRefundHandlerTest.java
> +        String errorResponse = load(STRIPE_ERROR_RESPONSE);
Same as above for both test changes here

2023-06-06 16:25 UTC, kbottla approved these changes

2023-06-06 16:33 UTC, merged