PP-11152 Use credentials POJO for building gateway requests
alphagov/pay-connector pull request #4630
Opened 2023-07-17 10:34 UTC by stephencdaly

Use the GatewayCredentials representation of the credentials when retrieving the credentials for use when making requests to the payment gateways.

As part of this, make the change to get the credentials for a customer initiated recurring Worldpay payment from the
`recurring_customer_initiated` nested credentials, rather than the root credentials. Credentials for accounts used for Worldpay recurring payments have already been updated on all environments to include `recurring_customer_initiated` credentials.

2023-07-17 16:01 UTC, alexbishop1 requested changes
Overall this change makes the code much nicer. Just a few small qualms.

2023-07-17 16:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +    }
Maybe having a separate method rather than an `isRecurring` flag might make this a bit simpler?

2023-07-17 16:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +                });
Feels like this should be able to reuse some of the logic in the method above.

2023-07-17 16:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +    public static Map<String, String> getGatewayAccountCredentialsForManagingTokensAsAuthHeader(GatewayCredentials credentials) {
It’s not too clear that `Tokens` means tokens for recurring payments here.

2023-07-17 16:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +        String value = "Basic " + Base64.getEncoder().encodeToString(new String(username + ":" + password).getBytes());
`new String(username + ":" + password).getBytes()` can just be `(username + ":" + password).getBytes()` but it should really be `(username + ":" + password).getBytes(StandardCharsets.UTF_8)` to make it less platform-dependent.

2023-07-17 16:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +                .max(comparing(GatewayAccountCredentialsEntity::getActiveStartDate))
Why was this change made?

2023-07-17 16:01 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/util/AuthUtilTest.java
> +    void getWorldpayAuthHeader_shouldThrowExceptionWhenNoCredentials_forRecurringCustomerInitiated() {
Can we try to be consistent with the naming convention for tests in this class?

2023-07-17 16:01 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/wallets/WorldpayWalletAuthorisationHandlerTest.java
> +            String expectedHeader = "Basic " + Base64.getEncoder().encodeToString(new String( username + ":" + password).getBytes());
Please always specify a charset when using `String.getBytes()`.

2023-07-17 16:01 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/CreateGatewayAccountResourceIT.java
> +        String StripeAccountId = "abc";
Capital letter at the start of a local variable name?

2023-07-17 16:23 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +    }
If we do that, we would be moving the logic to a different place, and repeating it in multiple places.
The logic could be made simpler if we were to remove the legacy credentials at some point.

2023-07-17 16:25 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +                });
I did briefly consider that, however I feel that by trying to re-use the logic we would end up having to apply more mental gymnastics to understanding it.
Re-using the logic would be much easier if we were able to get rid of the legacy credentials - as then we're just dealing with one-off credentials.

Possibly we could re-use just the recurring credentials part..

2023-07-17 16:25 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +    public static Map<String, String> getGatewayAccountCredentialsForManagingTokensAsAuthHeader(GatewayCredentials credentials) {
This was already the name of the method, I could rename it.

2023-07-17 16:26 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +        String value = "Basic " + Base64.getEncoder().encodeToString(new String(username + ":" + password).getBytes());
Could improve that, but it was existing behaviour.

2023-07-17 16:31 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +                .max(comparing(GatewayAccountCredentialsEntity::getActiveStartDate))
Ah yes I forgot about this change. This was because I removed and replaced the usages of the above `public Map<String, Object> getCredentials(String paymentProvider) {` method, which had this logic.

It feels like better behaviour to get the most recently active credential for the provider (if there is one) rather than just the first. I could potentially make the effort to separate this out to a different PR if you think that is worthwhile.

2023-07-17 16:32 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/gateway/util/AuthUtilTest.java
> +    void getWorldpayAuthHeader_shouldThrowExceptionWhenNoCredentials_forRecurringCustomerInitiated() {
As long as it's clear what an individual test is testing, does it matter than naming isn't consistent? I don't want to end up renaming all the tests to make them consistent...

2023-07-18 08:39 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +    }
Perhaps I was not clear. I meant we could have a `getWorldpayMerchantCode(GatewayCredentials credentials)` method containing everything that’s currently outside the `if` block and a `getWorldpayMerchantCodeForRecurring(GatewayCredentials credentials, AuthorisationMode authorisationMode)` method containing everything that’s currently inside the `if` block. It would just make the body of each method a little shorter. Each call site would call the appropriate version of the method, rather than passing the `isRecurring` flag.

2023-07-18 08:41 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountEntity.java
> +                .max(comparing(GatewayAccountCredentialsEntity::getActiveStartDate))
It’s fine to stay in this PR now it’s here.

2023-07-18 08:41 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/util/AuthUtilTest.java
> +    void getWorldpayAuthHeader_shouldThrowExceptionWhenNoCredentials_forRecurringCustomerInitiated() {
I suppose so.

2023-07-18 09:00 UTC, alexbishop1 approved these changes
As my childhood dentist used to say: “You’ll do!”

2023-07-18 09:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +                    String password = worldpayCredentials.getLegacyOneOffCustomerInitiatedPassword().orElseThrow(NoCredentialsInUsableStateException::new);
Probably not for now but I’m almost tempted to suggest we add a `getLegacyCredentials()` method that returns a `WorldpayMerchantCodeCredentials` object created on the fly, so we can harmonise how we treat legacy and new credentials.

2023-07-18 09:39 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +                    String password = worldpayCredentials.getLegacyOneOffCustomerInitiatedPassword().orElseThrow(NoCredentialsInUsableStateException::new);
Yeh maybe that would help simplify some things, if it were done in a way that doesn't make it less clear.

2023-07-18 09:41 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/util/AuthUtil.java
> +    }
That's what I understood by your first comment. But the call sites are often for code that could be either for a recurring payment or one-off payment. There's one or 2 places where it only applies to one or the other. But for authorise (customer present), authorise 3ds, capture, query, refund it's all shared code between one-off and recurring.

2023-07-18 09:42 UTC, merged