PP-10833 consider idempotency key records when expunging charges
alphagov/pay-connector pull request #4632
Opened 2023-07-18 11:11 UTC by AbdirizakIdris

## WHAT 
- Currently we are expunging charges and idempotency keys after 24 hours * It is possible that the charge is expunged from the connector but the Idempotency key stays. For a new request with the same idempotency key but expunged charge, Connector will throw ChargeNotFoundException. So we need to check if the idempotency key record exists for charge before expunging from the connector database

  - extended conditions to check if the idempotency key record exists for charge, If so, don’t expunge the charge

2023-07-18 14:15 UTC, kbottla requested changes

2023-07-18 14:15 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/expunge/service/ChargeExpungeService.java
> +                    if (chargeEntity.getAuthorisationMode() == AuthorisationMode.AGREEMENT) {
Would probably be better if the condition is in method `parityCheckAndExpungeIfMet`.

In `parityCheckAndExpungeIfMet` method, check for agreement mode and idempotency record can be last one condition

```
if (!inTerminalState(chargeEntity)) {
...
} else if (chargeEntity.getPaymentGatewayName() == STRIPE && isStripePaymentMissingFees(chargeEntity)) {
....
} else if (......idempotency-record-exists){
   ///log..
}
 else if (parityCheckService.parityCheckChargeForExpunger(chargeEntity)) {
            expungeCharge(chargeEntity);
```

2023-07-18 14:15 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/expunge/service/ChargeExpungeService.java
> +                            }
See the above comment. 

Ideally, if the condition is added to this method it can be as below before the try/catch block. We can also avoid duplicating code across if/else blocks

```
if ( charge.authorisation_mode == AGREEMENT  and idempotency_record_exists) {
   // log
  continue;
}
```

2023-07-18 14:15 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/expunge/service/ChargeExpungeService.java
> +                    if (chargeEntity.getAuthorisationMode() == AuthorisationMode.AGREEMENT) {
Can test(s) be added for this change?

2023-07-20 20:50 UTC, AbdirizakIdris commented on src/main/java/uk/gov/pay/connector/expunge/service/ChargeExpungeService.java
> +                    if (chargeEntity.getAuthorisationMode() == AuthorisationMode.AGREEMENT) {
updated into this method now

2023-07-21 08:52 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/expunge/service/ChargeExpungeService.java
> +                chargeService.updateChargeParityStatus(chargeEntity.getExternalId(), SKIPPED);
We can remove this line. If we skip the charge it won't be tried for expunging for about 24 hours. 

In this case, charges can be tried again sooner.

2023-07-21 08:52 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/expunge/service/ChargeExpungeService.java
> +                logger.info("Charge not expunged from connector because Idempotency exists for charge in AGREEMENT mode {}",
```suggestion
                logger.info("Charge not expunged from connector because Idempotency record exists for charge",
```

2023-07-21 08:52 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/expunge/service/ChargeExpungeServiceTest.java
> +    void expunge_shouldNotExpungeChargeIfAgreementModeWithExistingIdempotency() {
```suggestion
    void expunge_shouldNotExpungeChargeIfAuthorisationModeIsAgreementModeAndIdempotencyRecordExists() {
```

2023-07-21 08:52 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/expunge/service/ChargeExpungeServiceTest.java
> +    void expunge_shouldExpungeChargeIfAgreementModeWithNOExistingIdempotency() {
```suggestion
    void expunge_shouldExpungeChargeIfAuthorisationModeIsAgreementAndIdempotencyRecordDoesNotExist() {
```

2023-07-21 08:52 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/expunge/service/ChargeExpungeServiceTest.java
> +    void expunge_shouldExpungeChargeIfNotAgreementModeAndNOExistingIdempotency() {
```suggestion
    void expunge_shouldExpungeChargeIfAuthorisationModeIsNotAgreement() {
```

2023-07-21 12:00 UTC, AbdirizakIdris commented on src/main/java/uk/gov/pay/connector/expunge/service/ChargeExpungeService.java
> +                logger.info("Charge not expunged from connector because Idempotency exists for charge in AGREEMENT mode {}",
Great spot, thanks!

2023-07-21 13:29 UTC, kbottla approved these changes

2023-07-21 14:33 UTC, merged