PP-10528: New endpoint to resend charge confirmation emails
alphagov/pay-connector pull request #4679
Opened 2023-08-09 15:35 UTC by alan-gds

`/v1/api/accounts/{accountId}/charges/{chargeId}/resend-confirmation-email`

2023-08-09 16:01 UTC, stephencdaly requested changes, later dismissed
Logic all looks good, we just need to consider expunged charges and it's probably better if we get rid of the Future stuff with the timeout.

2023-08-09 16:01 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/charge/resource/ChargesApiResource.java
> +                    var chargeEntity = chargeService.findChargeByExternalId(chargeId);
We're getting a `Charge` using `findCharge`  and then getting a `ChargeEntity` using `findChargeByExternalId`.

I think the right thing to do here is to just get the `Charge` and use that to send the email. If you look at the logic of what these 2 methods do, `findCharge` first tries look for the charge in connector's database, and if it doesn't find it there, makes a request to ledger to get it. This is to deal with the case where charges have been expunged from connector, which currently happens after a day.

`findChargeByExternalId` however, only looks in connector's database.

When resending an email, it might be quite likely the charge has been expunged, so we need to deal with this.

My suggestion would be to start by updating `UserNotificationService$sendPaymentConfirmedEmail` to accept a `Charge` rather than a `ChargeEntity`, or adding a separate method that accepts a `Charge` and does any extra steps to get all the info needed for the email. The difference between these 2 types is that a `ChargeEntity` represents a charge from connector's database but a `Charge` represents a charge obtained from either connector or ledger. Hopefully the `Charge` already has all the information we need to send the email.

2023-08-09 16:01 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/charge/resource/ChargesApiResource.java
> +                                .get(5, TimeUnit.SECONDS)
I think that this method currently returns a `Future` because we don't want to wait around for the email to send when we send as part of the capture process.

I think for this case, we're happy waiting around for a response - and the timeout should probably just be the standard timeout for the Notify client. What I'd probably suggest here is creating a separate method in `UserNotificationService` that synchronously makes the request to Notify, making sure to share the code that makes the request.

2023-08-09 16:01 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/charge/resource/ChargesApiResource.java
> +                            return gatewayErrorResponse("Failed to send email");
This will return the correct thing, as we want to return a 402, and `gatewayErrorResponse` returns a 402. However, it's slightly confusing as a "gateway error" would usually refer to an error contacting a payment gateway - Worldpay, Stripe etc.

I'd be inclined to directly call `buildErrorResponse(PAYMENT_REQUIRED, message);` or rename the `gatewayErrorResponse` method if you can think of a suitable name to avoid this confusion.

2023-08-09 16:01 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceTest.java
> +                .header("Idempotency-Key", "")
The `.header("Idempotency-Key", "")` won't mean anything for this request, best to leave it out to avoid confusion.

2023-08-09 16:01 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceTest.java
> +    }
Would be good to add one integration test in addition to these unit tests.

2023-08-10 15:02 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/charge/resource/ChargesApiResource.java
> +                })
A more Java 8+ way of doing this would be something like
```suggestion
                                .map(charge -> userNotificationService.sendPaymentConfirmedEmailSynchronously(charge, account)
                            .map((reference) -> noContentResponse())
                            .orElseGet(() -> gatewayErrorResponse("Failed to send email")))
```

2023-08-10 15:02 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/usernotification/service/UserNotificationService.java
> +    public Future<Optional<String>> sendPaymentConfirmedEmail(Charge charge, GatewayAccountEntity gatewayAccountEntity) {
I think this is only called by the method above, so it could be inlined or made private?

2023-08-10 15:02 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/usernotification/service/UserNotificationService.java
> +    public Optional<String> sendPaymentConfirmedEmailSynchronously(Charge charge, GatewayAccountEntity gatewayAccountEntity) {
We should probably add unit tests for this new method

2023-08-10 15:02 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/usernotification/service/UserNotificationService.java
> +        }
Yeh should probably try to de-duplicate the code up until here? It looks shared between the synchronous and non-synchronous methods?

2023-08-10 16:00 UTC, alan-gds commented on src/main/java/uk/gov/pay/connector/usernotification/service/UserNotificationService.java
> +    public Future<Optional<String>> sendPaymentConfirmedEmail(Charge charge, GatewayAccountEntity gatewayAccountEntity) {
Good spot.  This overload stopped being used once I added an additional overload for sending the email synchronously.

2023-08-10 16:26 UTC, alan-gds commented on src/main/java/uk/gov/pay/connector/charge/resource/ChargesApiResource.java
> +                })
Yeah, it felt clunky when I wrote it; definitely prefer the suggestion.  I use a functional style instinctually when I'm writing Scala, but somehow it doesn't come so naturally to me in Java. 😅

2023-08-25 11:07 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/charge/resource/ChargesApiResource.java
> +                                .map(charge -> userNotificationService.sendPaymentConfirmedEmailSynchronously(charge, account)
Indentation looks a little off here

2023-08-25 11:07 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceResendConfirmationEmailIT.java
> +        String paymentProvider = "epdq";
I'd just select a different payment provider for this test as epdq is currently being retired - sandbox should do

2023-08-25 11:07 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/usernotification/service/UserNotificationServiceTest.java
> +    void shouldSendPaymentConfirmationEmailSynchronouslyIfEmailNotifyIsEnabled() throws Exception {
We probably just need some additional unit tests for the cases when the email won't be sent. It would just be duplicating all the tests like `shouldNotSendEmail_IfEmailEnabledButChargeDoesNotHaveAnEmailAddress` for this method.
We should do this because although the code for this is shared in a private method for this class, if any modifications are made to the public method under test to change how this code is called, we might break this functionality and not be able to tell.

2023-08-30 15:23 UTC, kbottla approved these changes

2023-08-30 15:33 UTC, merged