bau: Remove EPDQ config
alphagov/pay-connector pull request #4690
Opened 2023-08-18 10:11 UTC by oswaldquek

As part of PP-11272, we want to remove EPDQ-related environment variables. This means removing the EPDQ config which depends on EPDQ environment variables. This PR deletes the minimum required to get PP-11272 unblocked; there are certainly more that can be deleted but this can be done at a later time.

TODO: check we don't have EPDQ smoke and e2e tests before deploying.

2023-08-21 15:36 UTC, stephencdaly requested changes
Looks good, we should just make sure we test things on test-12 before deploying to prod to make sure we're happy that if anyone tries to create an ePDQ payment or refund that connector doesn't get in an odd state.

Do we also want to make sure there are no ePDQ payments in the connector database on all environments before deploying, just to make sure we don't inadvertently run into the situation that occurred when we tried to remove Smartpay code? I don't remember the exact cause of that.

Just a comment about some tests that have been removed that I think we want to keep.

2023-08-21 15:36 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/it/resources/DiscrepancyResourceIT.java
> -public class DiscrepancyResourceIT extends ChargingITestBase {
The discrepancy checker is also useful for Worldpay, so I think we should keep these tests but make them for Worldpay?

2023-08-21 15:37 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayCleanupResourceIT.java
> -public class GatewayCleanupResourceIT extends ChargingITestBase {
Likewise for this, the gateway cleanup is now also used for Worldpay and Stripe, so I think we should just change the payment provider used for these tests.

2023-08-22 13:01 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/DiscrepancyResourceIT.java
> -    public void shouldHandleCaseWhereChargeIsInUnknownState() {
I have removed this test as there's no worldpay equivalent for `epdqMockClient.mockUnknown()` two lines below.

2023-08-22 13:03 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/DiscrepancyResourceIT.java
> -        String chargeId2 = addCharge(ChargeStatus.EXPIRED, "ref", Instant.now().minus(8, DAYS), "irrelevant");
I removed chargeId2 because:
- it is exactly the same as chargeId1
- [mockAuthorisationQueryAndCancel](https://github.com/alphagov/pay-connector/pull/4690/files#diff-df1f6d7a0271ccf4b4021db42324138fdb2b2383a90ca7529c9d5a01dbe364bcR162) would be more complicated as I'd have to set the scenario state for two charge ids: STARTED -> "payment status queried" -> STARTED -> "payment status queried"

2023-08-23 09:41 UTC, stephencdaly approved these changes
LGTM! Just be careful when deploying

2023-08-23 10:05 UTC, merged