PP-11465 move apple pay decryption to worldpay code
alphagov/pay-connector pull request #4708
Opened 2023-09-07 17:27 UTC by james-peacock-gds

WIP
Done so far:
- pass WalletAuthorisationRequest through to payment-provider-specific code. 
- add getWalletType to WalletAuthorisationRequest interface.
- move extraction of wallet data to the Worldpay order builder code, including decryption of Apple payment data.
- update test fixtures accordingly

TO DO:
- extraction of card expiry date from payment provider response.

2023-09-12 08:42 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/wallets/applepay/ApplePayService.java
> +    public ApplePayService(WalletAuthoriseService authoriseService) {
Can we just delete the ApplePayService and GooglePayService subclasses now? Looks like all they do is set the `walletType` for the WalletService, which we can get from the `WalletAuthorisationRequest`

2023-09-12 09:00 UTC, alexbishop1 requested changes
Fundamentally this just moves the decryption code somewhere else and looks fine. Some suggestions for a few specifics.

2023-09-12 09:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        }
Oh, yikes, this is a bit 😬!

This is what I would do:

1. Add a new static `valueOf(YearMonth)` method to `CardExpiryDate`
2. Use regexes (or similar) to check that `expiryDateMonth` and `expiryDateYear` are in the expected formats
3. Assuming they are, convert them to `ints` and use `YearMonth.of(int, int)` to get a `YearMonth`
5. Call the new `CardExpiryDate,valueOf(YearMonth)` method to get a `CardExpiryDate`

2023-09-12 09:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/wallets/WorldpayWalletAuthorisationHandler.java
> +        return (GooglePayAuthRequest) request.getWalletAuthorisationRequest();
A `switch` statement might work better here. It does almost feel like `WalletAuthorisationRequest` should be an interface with Apple Pay- and Google Pay-specific subtypes.

2023-09-12 09:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/wallets/WorldpayWalletAuthorisationHandler.java
> +        LOGGER.info("Decrypting apple pay payload for charge with id {}", chargeId);
“Apple Pay”

2023-09-12 09:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/wallets/WorldpayWalletAuthorisationHandler.java
> +        LOGGER.info("Finished decryption for id {}", chargeId);
Do we really need a log line saying we finished decrypting?

2023-09-12 09:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthorisationRequestToAuthCardDetailsConverter.java
> +import java.time.format.DateTimeFormatter;
Is this ever used?

2023-09-12 09:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +            Optional<CardExpiryDate> cardExpiryDate = operationResponse.getBaseResponse().flatMap(BaseAuthoriseResponse::getCardExpiryDate);
Some would argue we shouldn’t have variables of type `Optional` and this should either be a `CardExpiryDate` or null.

2023-09-12 09:00 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponseTest.java
> +        assertThat(worldpayOrderStatusResponse.getCardExpiryDate().get(), is(CardExpiryDate.valueOf("11/99")));
This is really minor but can we pick an expiry date in this millennium?

2023-09-12 11:13 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        }
Agreed, I was 😬 too. Are you suggesting that 2,3,4 above should all be done within this getter method? If expiryDateMonth and expiryDateYear aren't in expected format, would you agree catching and logging as an error and returning Optional.empty() is appropriate or is there a better approach?

2023-09-12 14:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        }
Yes, something like this:

```java
// Way up near the beginning of the file in constantland
private static final Pattern TWO_DIGIT_MONTH = Pattern.compile("[0-9]{2}");
private static final Pattern FOUR_DIGIT_YEAR = Pattern.compile("[1-9][0-0}{3}");

// Back down at the getter
public Optional<CardExpiryDate> getCardExpiryDate() {
    if (expiryDateMonth == null || !TWO_DIGIT_MONTH.matcher(expiryDateMonth).matches()) {
        LOGGER.error(format("Expiry date month in Worldpay response for transaction {} is in an unexpected format.", transactionId));
        return Optional.empty();
    }
    
    if (expiryDateYear == null || !FOUR_DIGIT_YEAR.matcher(expiryDateYear).matches()) {
        LOGGER.error(format("Expiry date year in Worldpay response for transaction {} is in an unexpected format.", transactionId));
        return Optional.empty();
    }

    var expiryDateYearMonth = YearMonth.of(Integer.parseInt(expiryDateYear), Integer.parseInt(expiryDateMonth));
    return Optional.of(CardExpiryDate.valueOf(expiryDateYearMonth));
}

2023-09-13 15:52 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/wallets/applepay/ApplePayService.java
> +    public ApplePayService(WalletAuthoriseService authoriseService) {
done!

2023-09-13 15:52 UTC, james-peacock-ho commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        }
done!

2023-09-13 16:48 UTC, alexbishop1 requested changes
Almost there!

2023-09-13 16:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +    private static final Pattern FOUR_DIGIT_YEAR = Pattern.compile("[1-9][0-9]{3}");
Since `CardExpiryDate` only supports years in the range 2000–2099, this should probably be `20[0-9]{2}`.

2023-09-13 16:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderStatusResponse.java
> +        }
If the validation regex is good enough, this try/catch should be unnecessary.

2023-09-13 16:48 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/wallets/WorldpayWalletAuthorisationHandler.java
> +                throw new IllegalArgumentException("Wallet Type not recognised");
We should include what `request.getWalletAuthorisationRequest().getWalletType()` in the exception so we know what unrecognised value we’ve been given.

2023-09-13 16:48 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/wallets/WalletServiceTest.java
> +        assertThat(authorisationResponse.getEntity(), is(ImmutableMap.of("status", "AUTHORISATION SUCCESS")));
We can use `Map.of(…)` here.

2023-09-14 10:28 UTC, alexbishop1 approved these changes

2023-09-14 10:29 UTC, alexbishop1 commented
Please squash the commits when merging.

2023-09-14 10:41 UTC, merged