PP-11385 Extract expiry date from Stripe auth response
alphagov/pay-connector pull request #4716
Opened 2023-09-18 14:26 UTC by stephencdaly

For Stripe wallet payments, we are not able to obtain the expiry date for the card before authorising. The payment method, included in the payment intent response includes the expiry date. Extract the expiry date from the authorisation response so we can store it on the charge for wallet payments.

2023-09-18 15:43 UTC, alexbishop1 reviewed
This is likely fine but I’ve got a couple of things to check.

2023-09-18 15:43 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +    private static CardExpiryDate extractCardExpiryDate(StripePaymentIntentResponse stripePaymentIntent) {
Maybe this should return an `Optional<CardExpiryDate>` and then do `extractCardExpiryDate(stripePaymentIntent).orElse(null)` when it’s used in the earlier line?

2023-09-18 15:43 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +                YearMonth yearMonth = YearMonth.of(card.getCardExpiryYear(), card.getCardExpiryMonth());
I assume we’re sure that `card.getCardExpiryYear()` will always return a four-digit year and `card.getCardExpiryMonth()` will always return a 1-indexed month?

2023-09-18 15:43 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +                return CardExpiryDate.valueOf(yearMonth);
This will throw an `IllegalArgumentException` if `yearMonth` is before 2000-01 or after 2099-12… worth handling?

2023-09-18 15:43 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/request/StripePaymentIntentRequest.java
> +        return Collections.singletonList("payment_method.card");
`List.of(…)` is cooler 😎

2023-09-18 15:43 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/response/StripeCard.java
> +    private Integer cardExpiryMonth;
Is it `Integer` (as opposed to `int`) because this could be null? If so, do we need to consider the possibility of a `NullPointerException` when it’s fed into `YearMonth.of(…)`?

2023-09-18 16:06 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +                return CardExpiryDate.valueOf(yearMonth);
Can Sentry just get that

2023-09-18 16:06 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +                YearMonth yearMonth = YearMonth.of(card.getCardExpiryYear(), card.getCardExpiryMonth());
Yeh I'm going to trust the Stripe API docs on this one..

2023-09-18 16:06 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/stripe/response/StripeCard.java
> +    private Integer cardExpiryMonth;
I have added in some handling for these being null.

2023-09-18 16:06 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +    private static CardExpiryDate extractCardExpiryDate(StripePaymentIntentResponse stripePaymentIntent) {
Yeh good idea, changed

2023-09-19 08:17 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +                return CardExpiryDate.valueOf(yearMonth);
The equivalent Worldpay code in `WorldpayOrderStatusResponse` checks the range (because it gets the year as a string and checks it matches the regex `20[0-9]{2}`). Do we know if Stripe is doing any checks on the year before sending it back to us or is there a risk it’s just echoing back what the wallet gave us (which means it’s essentially user input)? I think I’d feel happier if we did catch this.

(Slight aside: wondering if `CardExpiryDate` should have a static `isValid(YearMonth)` method to encapsulate the valid range in one place and avoid it leaking all over the code — one of the problems `CardExpiryDate` was supposed to fix in the first place.)

2023-09-19 08:26 UTC, alexbishop1 requested changes
In addition to the comments with this review, there are also some separate replies to your responses to comments from my previous review (sorry, didn’t quite think it through).

2023-09-19 08:26 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +                }
Does this need to be inside the try/catch?

2023-09-19 08:26 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +                YearMonth yearMonth = YearMonth.of(card.getCardExpiryYear(), card.getCardExpiryMonth());
Would it be hideous amounts of work to make `card.getCardExpiryYear()` return `Optional<Year>` and `card.getCardExpiryMonth()` return `Optional<Month>`?

2023-09-19 08:35 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +                return CardExpiryDate.valueOf(yearMonth);
Done

2023-09-19 08:36 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeAuthorisationResponse.java
> +                }
Moved

2023-09-19 08:37 UTC, alexbishop1 approved these changes

2023-09-19 09:25 UTC, merged