PP-11601 Improved rejected authorisation error handling
alphagov/pay-connector pull request #4749
Opened 2023-10-05 11:28 UTC by olatomgds

## WHAT YOU DID
Improved rejected authorisation error handling

## How to test

- How should it be reviewed? 
Software engineer with experience of connector integration and error handling
- What feedback do you need? 
That changes works and will not break current frontend payment authorisation logic and error handling

### Documentation
 https://payments-platform.atlassian.net/browse/PP-11601

2023-10-06 09:08 UTC, stephencdaly requested changes

2023-10-06 09:08 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +        return buildErrorResponse(BAD_REQUEST, AUTHORISATION_REJECTED, message);
We should only return the AUTHORISATION_REJECTED error message for an authorisation rejected response, rather than all bad request (400) responses. Look in `WalletService` for where we build the authorisation rejected response for wallet authorisation requests. We might want to add an extra method in this file to build a response that is specifically for authorisation rejected.

2023-10-06 11:58 UTC, olatomgds commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +        return buildErrorResponse(BAD_REQUEST, AUTHORISATION_REJECTED, message);
Changes made as per chat. Thanks

2023-10-06 13:49 UTC, stephencdaly requested changes
Looks good, just your intelliJ settings need to be updated to remove wildcard imports.

Once you're done could you squash your commits down to 1 commit please so I can review the commit message too.

2023-10-06 13:49 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +import static javax.ws.rs.core.Response.Status.*;
We don't like to use wildcard imports. Could you follow the instructions [here](https://gds-way.cloudapps.digital/manuals/programming-languages/java.html#imports) to change your intelliJ settings so that it won't insert wildcard imports, and then optimise the imports again.

2023-10-06 13:49 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/wallets/WalletService.java
> +import static uk.gov.pay.connector.util.ResponseUtil.*;
Wildcard import here too

2023-10-09 08:34 UTC, olatomgds commented on src/main/java/uk/gov/pay/connector/util/ResponseUtil.java
> +import static javax.ws.rs.core.Response.Status.*;
Resolved, thanks

2023-10-09 08:34 UTC, olatomgds commented on src/main/java/uk/gov/pay/connector/wallets/WalletService.java
> +import static uk.gov.pay.connector.util.ResponseUtil.*;
Resolved

2023-10-09 11:36 UTC, stephencdaly approved these changes
Looks good to me!

2023-10-09 11:57 UTC, merged