PP-2777 create table transaction
alphagov/pay-connector pull request #484
Opened 2017-11-06 11:29 UTC by chrisgrimble

Start writing and updating the Transaction table as well as the Charges 
table.

Check that a PaymentRequest has a charge transaction before 
modifying it. This is needed until we back fill the transactions table with
anything from charges. Once that has been done this commit can be
reverted. Have done it this way as it is a relatively small change which
will be easy to revert. Thought about creating a new ChargeTransaction
when you call getChargeTransaction if it did not exist. However this
required a ChargeEntity to be passed to getChargeTransaction() and the
changes were becoming considerable. Want this to be easy to remove once
the transactions table has been back filled.

- Mapped Transactions table to Transactions entity which links to the
PaymentRequestEntity.
- Made TransactionEntity reference PaymentRequestEntity. This creates a
bidirectional relationship which means the transaction can be inserted
with a single sql statement. Otherwise JPA will try to insert the
Transaction with a null in the payment_request_id column, then create
another statement to update the the payment_request_id.
- Moved chargeStatusUpdate to ChargeService from ChargeFrontendResource.
- Update Transactions when change status.
- Setting gatewayTransactionId on the chargeTransaction in the same
places as it is set on the charge.
- Add a hasChargeTransaction() to PaymentRequestEntity.
- Check hasChargeTransaction() before making a change to the charge
transaction.

2017-11-07 11:16 UTC, alexbishop1 requested changes
Looks like it should do the job but I haven’t exhaustively checked for everywhere we update the status of a payment and formally proved the use of transactions (in the database sense).

I do think it may be worth looking at centralising status updates so that they all go through one place and we can handle the updating in both places (and maybe even appending to the event history tables) there. It would make future changes easier (not just when we remove the old `charges` table but also if we decide to do consistent logging or fire metrics at Graphite for every status change). I suggested adding this to `ChargeService` but I wouldn’t be opposed to having a new `StatusUpdater` that deals solely with updating statuses: it’s a major part of what connector does, after all (whether or not connector should do this is a whole other discussion!).

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/PaymentRequestDao.java
> +    public Optional<PaymentRequestEntity> updateChargeTransactionStatus(String externalId, ChargeStatus newChargeStatus) {
Not sure this class is the right place for this method. It feels like updating the status of a transaction should be something that’s done via a `TransactionDao` (yes, I know that name is already used: it can be renamed) or something. I realise the fact that right now not everything in the `charges` table will have something equivalent in the `transactions` table complicates things.

We may perhaps want to go further and try centralising how we do status updates. Right now, it’s usually done by directly modifying the `ChargeEntity` and then persisting it. If we instead called a centralised method (maybe on `ChargeService`), we could have that do the updating of the `ChargeEntity` and, if applicable, the `TransactionEntity` in the same place. Later, we could add code to insert into the `TransactionEvents` table. Then, we want to stop writing to the `Charges` table, we’d only have to do the change in one place (more or less). And in eighteen months time when we’re changing how the database stores data again, we wouldn’t have to go find everywhere we change statuses again.

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/ChargeEntity.java
> +        if (defaultTransitions().isValidTransition(fromString(this.status), targetStatus)) {
Why was this changed?

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/PaymentRequestEntity.java
> +    public TransactionEntity getChargeTransaction() {
Ideally this would be called something simple like `getCharge()` but maybe we should address this after we don’t have two things called “charge” in the system

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/PaymentRequestEntity.java
> +        return transactions.stream().filter(byChargeTransactions()).findFirst().orElseThrow(
This scares me a little bit. It’s expected that people should do this, right?

```
if (paymentRequestEntity.hasChargeTransaction()) {
    paymentRequestEntity.getChargeTransaction().setStatus(newChargeStatus);
}
```

We could instead make this method return an `Optional` (with an `Optional.empty()` instead of an exception) and expect people to use it like this:

```
paymentRequestEntity.getChargeTransaction().ifPresent(transaction -> transaction.setStatus(newChargeStatus));
```

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/transaction/TransactionEntity.java
> +public class TransactionEntity extends AbstractEntity {
I may have missed some of the discussion but I thought there was a general consensus that we would use single table inheritance here and have `TransactionEntity` be abstract (probably) with a concrete `ChargeTransactionEntity` (or whatever we decide to call it) and eventually a `RefundTransactionEntity`, each exposing just the fields they care about.

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/transaction/TransactionEntity.java
> +    private void checkValidStateTransition(ChargeStatus newChargeStatus) {
I’d be quite tempted to roll this in to the `setStatus(ChargeStatus)` method

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> -                    if (CURRENT_STATUSES_ALLOWING_UPDATE_TO_NEW_STATUS.contains(ChargeStatus.fromString(chargeEntity.getStatus()))) {
Why has this check been removed?

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CancelServiceFunctions.java
> +            paymentRequestDao.updateChargeTransactionStatus(chargeEntity.getExternalId(), statusFlow.getLockState());
I think it would be clearer if the `statusFlow.getLockState()` was pulled out into a local variable (called `newStatus`, say) declared just before the `chargeEntity.setStatus(ChargeStatus)` call (with the call to that method changed to pass in `newStatus`). And maybe this line should be moved up. It’s not immediately clear that this is setting the same value on the `ChargeEntity` and the `TransactionEntity`.

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/Card3dsResponseAuthService.java
> +import uk.gov.pay.connector.model.domain.*;
You’re going against the proposed GDS Java style guide with wildcard imports

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/Card3dsResponseAuthService.java
> +            Optional<PaymentRequestEntity> paymentRequestEntity = paymentRequestDao.updateChargeTransactionStatus(chargeEntity.getExternalId(), status);
Feels a little funky that this method both changes something and returns something else

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseService.java
> +        return chargeDao.findByExternalId(chargeId).map((ChargeEntity chargeEntity) -> {
Unnecessary cast?

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseService.java
> +                });
This is basically a duplicate of the new code in `Card3dsResponseAuthoriseService` and below. I know it’s going to be fairly short-lived but it might be worth separating it out.

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/ChargeService.java
> +    private static final List<ChargeStatus> CURRENT_STATUSES_ALLOWING_UPDATE_TO_NEW_STATUS = newArrayList(CREATED, ENTERING_CARD_DETAILS);
So that’s where the code from `ChargeFrontendResource` went! I’m not sure it really belongs here: as I understand it, the restrictions are supposed to only be enforced if processing a status update request from frontend, so `ChargeFrontendResource` seems like the right place to do this.

2017-11-07 11:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/ChargeService.java
> +    public Optional<ChargeEntity> updateStatus(String externalId, ChargeStatus newChargeStatus) {
If this method is going to stay here, we should probably rename it to make clear the restricted circumstances in which it’s appropriate to call it

2017-11-07 11:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/PaymentRequestDaoITest.java
> +        assertThat(paymentRequestEntity.getCreatedDate().getNano() % 1000000, is(0));
Why do we care about this?

2017-11-07 11:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/PaymentRequestDaoITest.java
> +    public void shouldThrowException_whenUpdatingToInvalidState() throws Exception {
It would be nice if the initial state was explicitly, er, stated in this test

2017-11-07 11:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/PaymentRequestEntityFixture.java
> +    public PaymentRequestEntityFixture withTransactions(List<TransactionEntity> transactions) {
If you made this varargs instead (`withTransactions(TransactionEntity... transactions)`), it would make the calling code look nicer

2017-11-07 11:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/PaymentRequestEntityTest.java
> +    public void shouldReturnChargeTransactionWhenThereIsManyTransactions() throws Exception {
Nice test

2017-11-07 11:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/Card3dsResponseAuthServiceTest.java
> +        PaymentRequestEntity paymentRequestEntity = PaymentRequestEntityFixture.aValidPaymentRequestEntity().build();
Since there’s another test that uses the result of `PaymentRequestEntityFixture.aValidPaymentRequestEntity().build()`, we could move this to be a field

2017-11-07 11:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/CardAuthoriseServiceTest.java
> +        verify(mockPaymentRequestDao).updateChargeTransactionStatus(charge.getExternalId(), AUTHORISATION_SUCCESS);
Use in-order verification here?

2017-11-07 11:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/CardCaptureServiceTest.java
> +        verify(mockPaymentRequestDao).updateChargeTransactionStatus(charge.getExternalId(), CAPTURE_SUBMITTED);
Another possible in-order verification opportunity

2017-11-07 11:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeCancelServiceTest.java
> +    private PaymentRequestDao mockedPaymentRequestDao;
The prefix `mock` (as opposed to `mocked` seems to be more prevalent in this file)

2017-11-07 11:16 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeServiceTest.java
> +        when(mockedChargeDao.findByExternalId(anyString()))
You know the specific external ID this will be called with

2017-11-07 11:24 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/model/domain/ChargeEntity.java
> +        if (defaultTransitions().isValidTransition(fromString(this.status), targetStatus)) {
This gets the allowed transaction transitions. We used to need to pass in the gateway name to find this out but it was not being used so we removed the argument and changed the method name. It is statically imported from PaymentGatewayStateTransitions.

2017-11-07 11:26 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/model/domain/PaymentRequestEntity.java
> +    public TransactionEntity getChargeTransaction() {
Yep think this will cause confusion naming it that now.

2017-11-07 11:28 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/model/domain/PaymentRequestEntity.java
> +        return transactions.stream().filter(byChargeTransactions()).findFirst().orElseThrow(
This will be reverted once the transactions table has been backfilled. Did look at returning an optional but the change set was getting massive so decided this would be easier to revert in a few days time once the backfill has been done.

2017-11-07 11:32 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/model/domain/transaction/TransactionEntity.java
> +    private void checkValidStateTransition(ChargeStatus newChargeStatus) {
Ok

2017-11-07 11:38 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/CancelServiceFunctions.java
> +            paymentRequestDao.updateChargeTransactionStatus(chargeEntity.getExternalId(), statusFlow.getLockState());
Ok, except pulled out newStatus at the start of the method, as it is used earlier on and does make the code easier to read as newStatus.

2017-11-07 11:45 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/Card3dsResponseAuthService.java
> +import uk.gov.pay.connector.model.domain.*;
Ok

2017-11-07 12:11 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/Card3dsResponseAuthService.java
> +            Optional<PaymentRequestEntity> paymentRequestEntity = paymentRequestDao.updateChargeTransactionStatus(chargeEntity.getExternalId(), status);
Ok split into two methods

2017-11-07 13:24 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseService.java
> +        return chargeDao.findByExternalId(chargeId).map((ChargeEntity chargeEntity) -> {
Yep

2017-11-07 13:34 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseService.java
> +                });
ok

2017-11-07 13:43 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/it/dao/PaymentRequestDaoITest.java
> +    public void shouldThrowException_whenUpdatingToInvalidState() throws Exception {
Ok

2017-11-07 13:45 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/model/domain/PaymentRequestEntityFixture.java
> +    public PaymentRequestEntityFixture withTransactions(List<TransactionEntity> transactions) {
Ok

2017-11-07 13:46 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/model/domain/PaymentRequestEntityTest.java
> +    public void shouldReturnChargeTransactionWhenThereIsManyTransactions() throws Exception {
Thanks

2017-11-07 13:50 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/Card3dsResponseAuthServiceTest.java
> +        PaymentRequestEntity paymentRequestEntity = PaymentRequestEntityFixture.aValidPaymentRequestEntity().build();
Ok

2017-11-07 13:54 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/CardAuthoriseServiceTest.java
> +        verify(mockPaymentRequestDao).updateChargeTransactionStatus(charge.getExternalId(), AUTHORISATION_SUCCESS);
Ok didn't know you could do that on a single mock but guess there is no reason not too.

2017-11-07 13:56 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/CardCaptureServiceTest.java
> +        verify(mockPaymentRequestDao).updateChargeTransactionStatus(charge.getExternalId(), CAPTURE_SUBMITTED);
Ok

2017-11-07 13:57 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/ChargeCancelServiceTest.java
> +    private PaymentRequestDao mockedPaymentRequestDao;
Ok

2017-11-07 13:59 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/ChargeServiceTest.java
> +        when(mockedChargeDao.findByExternalId(anyString()))
Ok

2017-11-07 15:09 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/model/domain/transaction/TransactionEntity.java
> +public class TransactionEntity extends AbstractEntity {
Done

2017-11-07 15:18 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> -                    if (CURRENT_STATUSES_ALLOWING_UPDATE_TO_NEW_STATUS.contains(ChargeStatus.fromString(chargeEntity.getStatus()))) {
Done

2017-11-07 15:20 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/ChargeService.java
> +    private static final List<ChargeStatus> CURRENT_STATUSES_ALLOWING_UPDATE_TO_NEW_STATUS = newArrayList(CREATED, ENTERING_CARD_DETAILS);
Decide we would leave this here but the method where this is used is now updateFromInitialStatus not just updateStatus

2017-11-07 15:20 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/ChargeService.java
> +    public Optional<ChargeEntity> updateStatus(String externalId, ChargeStatus newChargeStatus) {
Decide we would leave this here but the method where this is used is now updateFromInitialStatus not just updateStatus

2017-11-07 15:21 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/it/dao/PaymentRequestDaoITest.java
> +        assertThat(paymentRequestEntity.getCreatedDate().getNano() % 1000000, is(0));
Was already like that. Not too sure why this was done but don't want to be changing other things at the moment.

2017-11-08 15:02 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/dao/PaymentRequestDao.java
> +    public Optional<PaymentRequestEntity> updateChargeTransactionStatus(String externalId, ChargeStatus newChargeStatus) {
Have moved the status update logic to StatusUpdater object. Looked at also updating the ChargeEntity in there too but was causing too many changes to our current code which we were trying not to change. Also would like to keep the StatusUpdater just dealing with the new objects (PaymentRequestEntity, TransactionEntity etc) not the old ones (ChargesEntity).

2017-11-09 15:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/PaymentRequestDao.java
> +    public Optional<PaymentRequestEntity> updateChargeTransactionStatus(String externalId, ChargeStatus newChargeStatus) {
Looks like this method still exists in `PaymentRequestDao` even though there is now a `StatusUpdater`

2017-11-09 15:09 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/ChargeEntity.java
> +        if (defaultTransitions().isValidTransition(fromString(this.status), targetStatus)) {
At some point (not now), we should probably stop pretending that different payment gateways have different state transitions and merge `StateTransitions` and `DefaultStateTransitions`

2017-11-09 17:46 UTC, alexbishop1 requested changes
Almost there — just a handful of fairly minor things and then I think it should be good to go (if you look me in the eye and promise you’ve tracked down everywhere we change charge statuses and are convinced the database transactions are sound!)

2017-11-09 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/transaction/ChargeTransactionEntity.java
> +public class ChargeTransactionEntity extends TransactionEntity<ChargeStatus> {
This is much more concise now. Good job!

2017-11-09 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
>      private static final List<ChargeStatus> CURRENT_STATUSES_ALLOWING_UPDATE_TO_NEW_STATUS = newArrayList(CREATED, ENTERING_CARD_DETAILS);
This can go now

2017-11-09 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> +            return badRequestResponse(msg);
We’re repeating the error message here (it’s the `IllegalArgumentException` message from `ChargeStatus.fromString(String)`): I think wrapping the `ChargeStatus.fromString(String)` in a try/catch and `return`ing `badRequestResponse(e.getMessage())` (closer to how it behaved before would be fine)

2017-11-09 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/Card3dsResponseAuthService.java
> +                });
Can we call the `setGatewayTransactionId(ChargeEntity, String, Optional<PaymentRequestEntity>)` superclass method to reduce duplication?

2017-11-09 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseBaseService.java
> +    }
Again, can we leverage the superduper class here?

2017-11-09 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseService.java
> +                });
So… going to do that? 😃

2017-11-09 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> + @Transactional
Spurious leading space here

2017-11-09 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +    private PaymentRequestDao paymentRequestDao;
This can be `final`

2017-11-09 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +        });
Could do the below but maybe it’s taking things a bit far 😃

```
paymentRequestDao.findByExternalId(externalId)
    .filter(PaymentRequestEntity::hasChargeTransaction)
    .ifPresent(paymentRequestEntity -> paymentRequestEntity.getChargeTransaction().setStatus(newChargeStatus));
```

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/PaymentRequestDaoITest.java
> +    public void shouldUpdateTransactionStatus() throws Exception {
I wonder if this test (and the two below) belong here now: in the future, we may be able to do some status changes without going via a `PaymentRequest` (e.g. if we get a notification and use the gateway transaction ID to retrieve the charge). Probably worth revisiting when that’s the case.

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/PaymentRequestDaoITest.java
> +        assertThat(paymentRequestEntity.getChargeTransaction().getId(), is(IsNull.notNullValue()));
You can static import `notNullValue()` for a readability win

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/CardCaptureServiceTest.java
> +        verify(mockStatusUpdater).updateChargeTransactionStatus(charge.getExternalId(), CAPTURE_READY);
More in-order verification opportunities

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/CardCaptureServiceTest.java
> +        verify(mockStatusUpdater).updateChargeTransactionStatus(charge.getExternalId(), CAPTURE_APPROVED_RETRY);
Further in-order verification opportunities

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeExpiryServiceTest.java
> +    private PaymentRequestDao mockPaymentRequestDao;
This is never used

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeServiceTest.java
> +    public void shouldUpdateTransactionStatus_whenUpdatingChargeStatus()  throws Exception {
Please rename this to make it clear it’s using the narrow `ChargeService.updateFromInitialStatus(String, ChargeStatus)` method

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +        someExternalId = "someExternalId";
Just inline this into the field declaration (which you can make into a fine SCREAMING_SNAKE_CASE constant)

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +        ChargeStatus newChargeStatus = ChargeStatus.ENTERING_CARD_DETAILS;
I’m not convinced having this variable is really buying us anything; I think it will be clear what’s going on if we just repeat `ENTERING_CARD_DETAILS` each time

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +        new StatusUpdater(mockPaymentRequestDao).updateChargeTransactionStatus(someExternalId, newChargeStatus);
I’m not going to insist on this but I usually like to have the class under test as a field

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +        verifyNoMoreInteractions(paymentRequest);
I’m generally in agreement with the notion that stubbing doesn’t usually need to be verified, so I’d remove these two lines

2017-11-09 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +}
New line at the end of the file, please

2017-11-14 18:29 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseService.java
> +                });
Yep added the method and then don't appear to have used it.

2017-11-14 18:29 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> + @Transactional
Done

2017-11-14 18:30 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +    private PaymentRequestDao paymentRequestDao;
Done

2017-11-14 18:31 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +        });
Codes going to go as soon as we have back filled so won't do but yep could have been done.

2017-11-14 18:33 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/it/dao/PaymentRequestDaoITest.java
> +    public void shouldUpdateTransactionStatus() throws Exception {
Ok

2017-11-14 18:38 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/it/dao/PaymentRequestDaoITest.java
> +        assertThat(paymentRequestEntity.getChargeTransaction().getId(), is(IsNull.notNullValue()));
Ok its notNullValue imported by Matchers but don't see why that can't be used here.

2017-11-14 18:40 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/CardCaptureServiceTest.java
> +        verify(mockStatusUpdater).updateChargeTransactionStatus(charge.getExternalId(), CAPTURE_READY);
Done

2017-11-14 18:41 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/CardCaptureServiceTest.java
> +        verify(mockStatusUpdater).updateChargeTransactionStatus(charge.getExternalId(), CAPTURE_APPROVED_RETRY);
Done

2017-11-14 18:42 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/ChargeExpiryServiceTest.java
> +    private PaymentRequestDao mockPaymentRequestDao;
Done

2017-11-14 18:43 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/ChargeServiceTest.java
> +    public void shouldUpdateTransactionStatus_whenUpdatingChargeStatus()  throws Exception {
Done

2017-11-14 18:47 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +        someExternalId = "someExternalId";
Have done as it can be a constant. 

At some time we should chat about the way we initialise things for tests. Generally much clearer if we just do it in one place and the only place you can initialise everything is in a setup method.

2017-11-14 18:49 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +        ChargeStatus newChargeStatus = ChargeStatus.ENTERING_CARD_DETAILS;
Done

2017-11-14 18:50 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +        new StatusUpdater(mockPaymentRequestDao).updateChargeTransactionStatus(someExternalId, newChargeStatus);
Ok haven't as I'm not sure I would here

2017-11-14 18:54 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +        verifyNoMoreInteractions(paymentRequest);
If we don't do this then we being explicit about the paymentRequets' charge transaction being updated

2017-11-14 18:55 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +}
Done

2017-11-15 10:10 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
>      private static final List<ChargeStatus> CURRENT_STATUSES_ALLOWING_UPDATE_TO_NEW_STATUS = newArrayList(CREATED, ENTERING_CARD_DETAILS);
done

2017-11-15 10:10 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> +            return badRequestResponse(msg);
Done

2017-11-15 10:12 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/Card3dsResponseAuthService.java
> +                });
Done

2017-11-15 10:12 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseBaseService.java
> +    }
done

2017-11-15 12:51 UTC, alexbishop1 requested changes
One final thing…

2017-11-15 12:51 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseService.java
> +                });
I think we can use the superclass `setGatewayTransactionId` method here

2017-11-15 13:20 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseService.java
> +                });
Done

2017-11-15 13:49 UTC, alexbishop1 approved these changes
We made it in the end!

This is a very important step in our data restructuring, good work!

2017-11-15 13:54 UTC, mrlumbu commented
🎉

2017-11-15 13:54 UTC, merged