PP-2876 Documentation for proposed API for dashboard figures
alphagov/pay-connector pull request #489
Opened 2017-11-14 19:14 UTC by alexbishop1

In a documentation-driven development style, this is the proposed API that connector will implement in order to serve the successful payments, refunded payments and net income figures on the forthcoming selfservice dashboard page (which will be implemented in PP-2877).

2017-11-15 14:29 UTC, jonheslop submitted a review, later dismissed
🚀

2017-11-16 18:13 UTC, mrlumbu requested changes

2017-11-16 18:13 UTC, mrlumbu commented on docs/api_specification.md
> +GET /v1/api/dashboard/123/summary?from_date=2017-11-03T00:00:00Z&to_date=2017-11-10T00:00:00Z
would it not make more sense for it to be `v1/api/account/123/transaction-summary` or something. Ie. it's a sub-resource of accounts
I know people hate REST these days, but i still like it :(

2017-11-20 18:36 UTC, alexbishop1 commented on docs/api_specification.md
> +GET /v1/api/dashboard/123/summary?from_date=2017-11-03T00:00:00Z&to_date=2017-11-10T00:00:00Z
Fair enough.

2017-11-23 13:30 UTC, mrlumbu approved these changes

2017-11-23 13:59 UTC, merged