Pp 11553 create new endpoint for stripe refund
alphagov/pay-connector pull request #4906
Opened 2023-12-22 11:24 UTC by AbdirizakIdris

## WHAT YOU DID
- Add newRefundReversalResource file with new endpoint for failed refund reversal

2023-12-22 12:44 UTC, stephencdaly requested changes, later dismissed
Changes look good, and meet the acceptance criteria!

I've just suggested some style changes.

2023-12-22 12:44 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/charge/exception/ChargeNotFoundForRefundException.java
> +public class ChargeNotFoundForRefundException extends WebApplicationException {
It looks like we always want the same exception method, regardless of whether it's the charge or refund that isn't found. I think you could just use `RefundNotFoundForChargeException` in all cases?

2023-12-22 12:44 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/refund/resource/RefundReversalResource.java
> +@Tag(name = "RefundsReversal")
Other tags are in sentence case - so "Refunds reversal" maybe? Although I think it might make sense to just come under the "Refunds" tag as it's directly related to refunds.

2023-12-22 12:44 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/refund/resource/RefundReversalResource.java
> +        if (PaymentGatewayName.STRIPE.getName().equals(charge.getPaymentGatewayName())) {
Code can be quite hard to read when you have lots of nested `if` statements.

You can avoid having nested if statements by reversing the condition and having a return statement in the if statement. It looks like this blog explains it quite well https://medium.com/swlh/return-early-pattern-3d18a41bba8 

So this might become:

```
if (!PaymentGatewayName.STRIPE.getName().equals(charge.getPaymentGatewayName())) {
    return Response.status(Response.Status.BAD_REQUEST)
                    .entity("Operation only available for Stripe")
                    .build();
}

2023-12-22 12:44 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/refund/resource/RefundReversalResource.java
> +            if(charge.getGatewayAccountId().equals(gatewayAccount.getId())) {
Again, reversing the `if` and returning would make this easier to read.

2023-12-22 12:44 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/refund/resource/RefundReversalResource.java
> +                if(refund.getChargeExternalId().equals(chargeExternalId)) {
If we're reversing all the other `if` statements as suggested, I think it would make sense to reverse this one too to follow the same pattern.

2023-12-22 12:44 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/refund/resource/RefundReversalResourceTest.java
> +    }
There should be a blank line between tests

2023-12-22 12:44 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/refund/resource/RefundReversalResourceTest.java
> +    }
Blank line missing

2023-12-22 12:44 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/refund/resource/RefundReversalResourceTest.java
> +        GatewayAccountEntity gatewayAccountEntity = aGatewayAccountEntity()
I don't think this test needs to construct a GatewayAccountEntity or set it on the ChargeEntity as it won't be used by the code under test.

2023-12-22 12:44 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/refund/resource/RefundReversalResourceTest.java
> +    void shouldReturn404WhenWrongChargeIsPassed() {
Is this test testing specifically when the charge does not belong to the gateway account in the request? If so could the test name be improved to reflect this specifically?

2023-12-22 12:44 UTC, stephencdaly commented on src/main/java/uk/gov/pay/connector/refund/resource/RefundReversalResource.java
> +            if(charge.getGatewayAccountId().equals(gatewayAccount.getId())) {
Could you also make sure you auto-format the code in intellij - there should be a space between `if` and `(`.
If you use the shortcut Option + Command + L it will auto-format the file.

2023-12-22 12:44 UTC, stephencdaly commented on src/test/java/uk/gov/pay/connector/refund/resource/RefundReversalResourceTest.java
> +    }
Blank line needed

2023-12-22 14:40 UTC, AbdirizakIdris commented on src/main/java/uk/gov/pay/connector/refund/resource/RefundReversalResource.java
> +        if (PaymentGatewayName.STRIPE.getName().equals(charge.getPaymentGatewayName())) {
Good suggestion

2023-12-27 16:44 UTC, oswaldquek approved these changes

2023-12-27 17:27 UTC, merged