PP-12302 refactor connector part 1
alphagov/pay-connector pull request #4998
Opened 2024-03-01 17:43 UTC by SandorArpa

## WHAT YOU DID

The first iteration of removing our reliance on the `junitparams` framework, and paving the road to use `Junit5`.
This iteration addresses the simple cases and replaces the `@RunWith` annotation based execution of integration tests with inherited `@ClassRule` one.
Introduced `NewChargingITestBase` and `NewGatewayAccountResourceTestBase` classes. These shall be renamed without the New prefix once we refactored all of the integration tests.

2024-03-04 12:21 UTC, alexbishop1 requested changes
Despite the length of this PR, most of the changes are mercifully simple.

Since this is changing quite a lot, could you run the tests on master and on this branch and compare the number to make sure we’re not accidentally excluding any?

Left a few comments: nothing major.

2024-03-04 12:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
Is this definitely necessary?

2024-03-04 12:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceIT.java
> +    @BeforeClass
This seems to still work if it’s a `@Before` method, which would probably be preferable to void sharing state between tests.

2024-03-04 12:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeCancelResource204ResponseParameterizedIT.java
> +    }
JUnit 4 parameterised tests have such a beautiful syntax…

2024-03-04 12:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +    @BeforeClass
Again, this seems to work as `@Before`

2024-03-04 12:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsParameterizedIT.java
> +    public boolean isGooglePayAllowed;
What do these parameters do?

2024-03-04 12:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsParameterizedIT.java
> +    }
This is opaque enough that I think a comment explaining what’s going on would be useful because I have no idea!

2024-03-04 12:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/rules/AppWithPostgresAndSqsRule.java
> +public class AppWithPostgresAndSqsRule implements TestRule {
I assume this has been copied from somewhere else.

2024-03-04 12:28 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceIT.java
> +    @BeforeClass
👍

2024-03-04 12:28 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeCancelResource204ResponseParameterizedIT.java
> +    }
:(

2024-03-04 12:28 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +    @BeforeClass
👍

2024-03-04 12:30 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsParameterizedIT.java
> +    public boolean isGooglePayAllowed;
They are telling JUnit which value to assign to the variables from the @Parameterized.Parameters() array.

2024-03-04 12:30 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/rules/AppWithPostgresAndSqsRule.java
> +public class AppWithPostgresAndSqsRule implements TestRule {
Yes

2024-03-04 12:36 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsParameterizedIT.java
> +    }
👍

2024-03-04 17:07 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
No, fixed it 👍

2024-03-05 14:53 UTC, alexbishop1 requested changes
Looks fine: just one `static` I think does not need to be.

2024-03-05 14:53 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceIT.java
> +    private static DatabaseFixtures.TestAccount testAccount;
I’d be surprised if this has to be static.

2024-03-05 14:53 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsParameterizedIT.java
> +    // { setAllowGooglePayFlag, setGatewayMerchantId, isGooglePayAllowed }
That’s clearer, thanks.

2024-03-05 15:06 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceIT.java
> +    private static DatabaseFixtures.TestAccount testAccount;
👍

2024-03-05 15:09 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsParameterizedIT.java
> +    // { setAllowGooglePayFlag, setGatewayMerchantId, isGooglePayAllowed }
👍

2024-03-05 16:36 UTC, alexbishop1 submitted a review, later dismissed

2024-03-06 09:54 UTC, alexbishop1 approved these changes

2024-03-06 10:11 UTC, merged