PP-2756 add PATCH request validator for GatewayAccountResource
alphagov/pay-connector pull request #501
Opened 2017-11-23 13:24 UTC by SandorArpa

- add a request validator to be used by GatewayAccountResource
- implement notify_settings specific validation (this is needed as the PATCH request contains nested nodes

2017-11-23 13:48 UTC, kakumara commented
I think its good if you complete all the validations in this PR (including support for `remove`) rather than leaving it for another

2017-11-23 13:48 UTC, kakumara requested changes

2017-11-23 13:48 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/app/ConnectorModule.java
> +        bind(RequestValidator.class).in(Singleton.class);
I don't think this is required. Given that it has a no-arg constructor. Guice should be able to inject this.

2017-11-23 13:48 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        throw new UnsupportedOperationException("Not supported");
😱 ```throw new UnsupportedOperationException("Not supported");```

2017-11-23 13:48 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        if(payload != null && payload.has(FIELD_OPERATION_PATH) && payload.findValue(FIELD_OPERATION_PATH).asText().equals("notify_settings")) {
Is this necessary? request validator can give you that directly.

2017-11-23 13:48 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        put(FIELD_OPERATION, asList("replace"));
what about `remove` as we discussed ?

2017-11-23 13:48 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        Optional<List<String>> checkList = requestValidator.checkIfExistsOrEmpty(payload,
`checkList` ? u mean errors ?

2017-11-23 13:48 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/model/domain/GatewayAccount.java
> +    public static final String FIELD_VALUES = "values";
it should be `value`. see https://payments-platform.atlassian.net/browse/PP-2756

2017-11-23 13:48 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        JsonNode valueNode = payload.get(FIELD_VALUES);
for `op` : `remove` there won't be a `value` filed. So this check should be only if `op` is `replace`

2017-11-23 13:48 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidatorTest.java
> +                "Field [op] is required"));
you can check for `path` error as well

2017-11-23 13:48 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidatorTest.java
> +    public void shouldError_whenAllFieldsAreMissing() throws Exception {
perhaps `whenMandatoryFieldsAreMissing` given that `value` is optional

2017-11-23 13:48 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidatorTest.java
> +    @Test(expected = UnsupportedOperationException.class)
👎

2017-11-23 13:55 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/app/ConnectorModule.java
> +        bind(RequestValidator.class).in(Singleton.class);
👍

2017-11-23 13:57 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/model/domain/GatewayAccount.java
> +    public static final String FIELD_VALUES = "values";
👍

2017-11-23 13:57 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        put(FIELD_OPERATION, asList("replace"));
I was going to that in the next commit but forgot it :(

2017-11-23 13:58 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        throw new UnsupportedOperationException("Not supported");
👍

2017-11-23 14:15 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        if(payload != null && payload.has(FIELD_OPERATION_PATH) && payload.findValue(FIELD_OPERATION_PATH).asText().equals("notify_settings")) {
👍

2017-11-23 14:15 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        Optional<List<String>> checkList = requestValidator.checkIfExistsOrEmpty(payload,
errorList

2017-11-23 14:46 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        throw new UnsupportedOperationException();
This is bad. 👎  why `UnsupportedOperationException` you should be returning either Optiona<Errors> or Optional.empty()

2017-11-23 14:46 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        if(payload.findValue(FIELD_OPERATION_PATH).asText().equals("notify_settings")) {
perhaps a constant for `notify_settings`

2017-11-23 14:46 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        if(payload.findValue(FIELD_OPERATION_PATH).asText().equals("notify_settings")) {
FYI, for a situation with what `operations` are bounded to a `path` here are some examples from adminusers 
https://github.com/alphagov/pay-adminusers/blob/master/src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java#L80
https://github.com/alphagov/pay-adminusers/blob/master/src/main/java/uk/gov/pay/adminusers/validations/UserPatchValidations.java#L39

2017-11-23 15:08 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        if(payload.findValue(FIELD_OPERATION_PATH).asText().equals("notify_settings")) {
Both examples are dealing with singular validations. In our case we allow both `replace` and `remove`

2017-11-23 16:48 UTC, kakumara submitted a review, later dismissed
LGTM

2017-11-24 09:51 UTC, kakumara approved these changes
LGTM

2017-11-24 09:52 UTC, merged