PP-12302 update IT tests before junit5 migration
alphagov/pay-connector pull request #5045
Opened 2024-03-21 14:58 UTC by hjvoid

## WHAT YOU DID
Update integration tests to use the dropwizard extension before continuing to implement the overriding custom extends of ConnectorApp.

## How to test
Run the IT tests. 

## Code review checklist
Check in with Sandor before merging.

2024-03-22 14:24 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/extension/AppWithPostgresAndSqsExtension.java
> +    private final int ledgerWireMockPort = PortFactory.findFreePort();
This can occasionally cause problems with ports being duplicated causing tests to fail, as there is no guarantee that the ports will be unique unless each port is used before the next one is found.

2024-03-26 12:03 UTC, alexbishop1 requested changes
Despite the overall size, most of these changes are fairly mechanical. Left a few comments and questions. Also, please squash the commits.

2024-03-26 12:03 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/base/ChargingITestBaseExtension.java
> +        wireMockServer.findUnmatchedRequests().getRequests();
Why does only this method have this?

2024-03-26 12:03 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeCancelResourceResponseIT.java
> +    public static Collection<Object[]> statusCode400() {
This would be nicer if it returned a `Stream<Arguments>`.

2024-03-26 12:03 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeCancelResourceResponseIT.java
> +    public static Collection<Object[]> statusCode204() {
This would be nicer if it returned a `Stream<Arguments>`.

2024-03-26 12:03 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsIT.java
> +        if (setGatewayMerchantId) addGatewayMerchantIdToGatewayAccount();
Egyptian brackets please:

```java
if (setAllowGooglePayFlag) {
    allowWebPaymentsOnGatewayAccount("allow_google_pay");
}
```

2024-03-26 12:03 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsIT.java
> +    static Collection<Object[]> permissions() {
Again, `Stream<Arguments>` would be nicer.

2024-03-26 12:03 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayCleanupResourceIT.java
> -                .build();
Is this just not required for the test?

2024-03-26 13:50 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeCancelResourceResponseIT.java
> +    public static Collection<Object[]> statusCode204() {
Fixed

2024-03-26 13:50 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeCancelResourceResponseIT.java
> +    public static Collection<Object[]> statusCode400() {
Fixed

2024-03-26 13:55 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsIT.java
> +    static Collection<Object[]> permissions() {
Fixed

2024-03-26 13:56 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayCleanupResourceIT.java
> -                .build();
We can add it back, but it makes no difference in the outcome of the intended tests. If we were to add it back we should change the nature of the given tests so we are actually testing that clean up shall be performed with retired credentials.

2024-03-26 13:58 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceAllowWebPaymentsIT.java
> +        if (setGatewayMerchantId) addGatewayMerchantIdToGatewayAccount();
Fixed

2024-03-26 14:05 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/base/ChargingITestBaseExtension.java
> +        wireMockServer.findUnmatchedRequests().getRequests();
Good question, it doesn't need it 🤦

2024-03-26 15:21 UTC, alexbishop1 submitted a review, later dismissed
Please squash the commits when you merge.

2024-03-26 16:59 UTC, alexbishop1 approved these changes

2024-03-26 17:02 UTC, merged