PP-12302 Refactor integration tests to use JUnit5
alphagov/pay-connector pull request #5058
Opened 2024-03-27 15:16 UTC by DomBelcher

## WHAT YOU DID
Refactor RefundReversalResourceIT inetrgation test to use JUnit5
Add constructor to AppWithPostgresAndSqsExtension accepting custom extension of ConnectorApp class

## How to test
Run integration tests

2024-03-27 17:27 UTC, SandorArpa requested changes

2024-03-27 17:27 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeRefundsResourceIT.java
> +//    private StripeMockClient stripeMockClient;
Can we remove commented out code?

2024-03-27 17:27 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeRefundsResourceIT.java
> +//        stripeMockClient = new StripeMockClient(app.getWiremockserver());
Same as above

2024-03-28 09:16 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeRefundsResourceIT.java
> +//    private StripeMockClient stripeMockClient;
Fixed

2024-03-28 09:16 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeRefundsResourceIT.java
> +//        stripeMockClient = new StripeMockClient(app.getWiremockserver());
Fixed

2024-03-28 09:31 UTC, SandorArpa approved these changes
🍬

2024-03-28 11:56 UTC, merged