Pp 2778 write refunds to transactions
alphagov/pay-connector pull request #509
Opened 2017-11-28 14:03 UTC by chrisgrimble

## WHAT
Start writing to the transactions table whenever we do a refund.
Have also started writing refund events to the 
transaction_events table which had been broken out to a 
different story. This is because this code is shared with 
ChargeTransactions and was easier to leave in than disable.

## HOW 
- Created RefundTransactionEntity and 
RefundTransactionEventEntity.
- Added method to the StatusUpdater to update status on 
RefundTransactionEntity.
- Call method on StatusUpdater whenever we we changing
the status on RefundEntity.

2017-11-29 14:35 UTC, alexbishop1 requested changes
Unfortunately, these changes assume that there will only ever be one refund for a particular payment request, which isn’t the case (there can be many). We need to support multiple refunds, including finding the the right refund to update.

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/PaymentRequestEntity.java
> +    public Optional<RefundTransactionEntity> getRefundTransaction() {
This doesn’t feel quite right: a payment request (or charge if you have an old-fashioned view of our domain) can have multiple refunds associated with it, so I would expect this method to return a list.

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/transaction/TransactionEntity.java
> +public abstract class TransactionEntity<E extends Status, T extends TransactionEventEntity<E>> extends AbstractVersionedEntity {
The letters are a bit non-obvious here: maybe `E` could be `S` for `Status` (OK with `TransactionEventEntity` being either `T` for `TransactionEventEntity` or `E` for `Event`)

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/transaction/TransactionEntity.java
> +        addTransactionEvent(transactionEvent, newStatus);
I like the coupling of setting the status and adding a transaction event here

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/transaction/TransactionEventEntity.java
> +    private TransactionEntity<E, ? extends TransactionEventEntity> transaction;
This probably shouldn’t be a wildcard because for any concrete implementation, it’s always going to be the same type at every point in this class where the wildcard is used. Fortunately, we can eliminate the wildcard.

In this class, change the class declaration from `TransactionEventEntity<E extends Status>` to the self-referential `TransactionEventEntity<E extends Status, T extends TransactionEventEntity<E, T>>`.

Next, go to the `TransactionEntity` class and change its declaration from `TransactionEntity<E extends Status, T extends TransactionEventEntity<E>>` to `TransactionEntity<E extends Status, T extends TransactionEventEntity<E, T>>`.

Then go to the `ChargeTransactionEventEntity` class make it so that it `extends TransactionEventEntity<ChargeStatus, ChargeTransactionEventEntity>`. After that, go to the `RefundTransactionEventEntity` and make it so that it `extends TransactionEventEntity<RefundStatus, RefundTransactionEventEntity>`.

Then you can go back to this class and change every `? extends TransactionEventEntity` to `T`.

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +    public void updateChargeTransactionStatus(String externalId, ChargeStatus newChargeStatus) {
Nice extraneous space removal

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +    public void updateRefundTransactionStatus(String externalId, RefundStatus newRefundStatus) {
Might want to name `externalId` so it’s clear that it’s the external ID of the payment request, not the refund (which has its own different external ID)

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +            if (optionalRefundTransaction.isPresent()) {
I can’t wait for Java 9’s `Optional.ifPresentOrElse()`

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +            Optional<RefundTransactionEntity> optionalRefundTransaction = paymentRequestEntity.getRefundTransaction();
This means we’re always going to update the first refund we find for a payment request, which may not be the one we want

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +                logger.info(String.format("Changing refund transaction status for externalId [%s] transactionId [%s] [%s]->[%s]",
This is a bit ambiguous: `externalId` relates to the payment request but `transactionId` relates to the refund (and is the database ID — generally we don’t log these in code, preferring to use external IDs or similar).

Also, with SLF4J, we don’t need to use `String.format`: it directly understands `{}` placeholders, for example:

```
logger.info("After eating {}, I like to eat {} and {}", "chips", "cake", "ice-cream");
```

The SLF4J folks also claim it’s much faster than `String.format`.

2017-11-29 14:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +                        String.format("Not updating refund transaction status for externalId [%s] to [%s] charge transaction not found",
It’s the refund that’s not found, not the charge

2017-11-29 14:35 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/PaymentRequestEntityTest.java
> +}
We would probably benefit from having tests that check a payment request returns the right refund when it has a charge and refunds

2017-11-29 14:35 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/transaction/RefundTransactionEntityTest.java
> +import static org.junit.Assert.*;
Our Java style guide says we should not use wildcard imports

2017-11-29 14:35 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/transaction/RefundTransactionEntityTest.java
> +        assertThat(transactionEntity.getUserExternalId(), is(refundEntity.getUserExternalId()));
I think it would be nicer if the user external ID were explicitly specified (in the say way that `externalId` and `amount` are)

2017-11-29 14:35 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/transaction/RefundTransactionEntityTest.java
> +        assertThat(transactionEvents.get(0).getStatus(), is(expectedStatus));
Might be nice to check the updated timestamp gets set correctly here but the fact that we don’t control the clock will make it a pain

2017-11-29 14:35 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/StatusUpdaterTest.java
> +
We need tests to check that we handle updating a status correctly when mulitple refunds exist for a single payment request

2017-12-01 13:12 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/model/domain/transaction/RefundTransactionEntityTest.java
> +        assertThat(transactionEvents.get(0).getStatus(), is(expectedStatus));
Would be nice to control the date from a date provider which is injected into the object. However this is created by eclipse link so is not as simple as just injecting it when the object is created.

2017-12-01 13:18 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
> +    public void updateChargeTransactionStatus(String externalId, ChargeStatus newChargeStatus) {
Removed

2017-12-04 15:58 UTC, alexbishop1 requested changes
Assuming you’ve caught everywhere we change refund statuses, the logic looks sound now so no major changes requested.

We should probably rename `StatusUpdater` to `ChargeStatusUpdater` now that we have a `RefundStatusUpdater`.

2017-12-04 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/transaction/TransactionEventEntity.java
> +    private TransactionEntity<S, ? extends TransactionEventEntity> transaction;
See my previous https://github.com/alphagov/pay-connector/pull/509#discussion_r153751551

2017-12-04 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/PaymentProvider.java
> +    }
I’m not entirely convinced this reads any better than`getPaymentGatewayName().toString()` would, which we could do by implementing `toString()` on `PaymentGatewayName`

2017-12-04 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/RefundStatusUpdater.java
> +    private static final Logger logger = LoggerFactory.getLogger(StatusUpdater.class);
Wrong class!

2017-12-04 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/RefundStatusUpdater.java
> +        String errorMessage = format("Not updating refund transaction status for refundReference [%s] to [%s] charge transaction not found",
It’s the refund transaction that’s not found, not the charge transaction

2017-12-04 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/RefundStatusUpdater.java
> +        String errorMessage = format("Not updating refund transaction status for refundReference [%s] to [%s] charge transaction not found",
I can see why we’re doing this create-an-error-message-in-advance-just-in-case malarky but it gives undue prominence to the errors and makes the flow less obvious.

I think it might be better to go with something like this instead:

```
    public void updateRefundTransactionStatus(PaymentGatewayName provider, String refundReference, RefundStatus newRefundStatus) {
        Optional<RefundTransactionEntity> refundTransactionOptional = refundTransactionDao.findByProviderAndReference(provider, refundReference);
        if (refundTransactionOptional.isPresent()) {
            updateRefundTransactionStatus(refundTransactionOptional.get(), newRefundStatus);
        } else {
            logger.info("Not updating refund transaction status for refundReference [%s] to [%s] refund transaction not found",
                    refundReference,
                    newRefundStatus.getValue());
        }
    }

    public void setReferenceAndUpdateTransactionStatus(String refundExternalId, String refundReference, RefundStatus newRefundStatus) {
        Optional<RefundTransactionEntity> refundTransactionOptional = refundTransactionDao.findByExternalId(refundExternalId);
        refundTransactionOptional.ifPresent(refundTransaction -> refundTransaction.setRefundReference(refundReference));
        if (refundTransactionOptional.isPresent()) {
            updateRefundTransactionStatus(refundTransactionOptional.get(), newRefundStatus);
        } else {
            logger.info("Not updating refund transaction status for externalId [%s] to [%s] refund transaction not found",
                    refundExternalId,
                    newRefundStatus.getValue());
        }
    }

    private static void updateRefundTransactionStatus(RefundTransactionEntity refundTransaction, RefundStatus newRefundStatus) {
        logger.info("Changing refund transaction status for refundReference [{}] transactionId [{}] [{}]->[{}]",
                refundTransaction.getRefundReference(),
                refundTransaction.getId(),
                refundTransaction.getStatus().getValue(),
                newRefundStatus.getValue()
        );
        refundTransaction.updateStatus(newRefundStatus);
    }
```

We can replace the `isPresent`s with `ifPresentOrElse` when we upgrade to Java 9

2017-12-04 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/RefundStatusUpdater.java
> +                format("Not updating refund transaction status for externalId [%s] to [%s] charge transaction not found",
It’s the refund transaction that’s not found, not the charge transaction

2017-12-04 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/RefundStatusUpdater.java
> +                    refundTransaction.getId(),
`refundTransaction.getId()` is the database ID of the refund. I assume this shoud have been the refund’s external ID or maybe something relating to the associated charge or payment request

2017-12-04 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/RefundStatusUpdater.java
> +            logger.info(errorMessage);
I wonder if this should be a higher level than info…

2017-12-04 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/StatusUpdater.java
>                          chargeTransaction.getId(),
This should probably be `chargeTransaction.getGatewayTransactionId()`

2017-12-04 15:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/PaymentRequestEntityTest.java
> +        refundTransaction.setRefundExternalId(refundReference);
The local variable is called `refundReference` but it’s used as the external ID

2017-12-04 15:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/transaction/RefundTransactionEntityBuilder.java
> +    public RefundTransactionEntityBuilder withRefindReference(String refundReference) {
`withRefundReference`

2017-12-04 15:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        );
I think `shouldOverrideGeneratedReferenceIfProviderReturnAReference` and `shouldStoreEmptyGatewayReferenceIfGatewayReturnsAnError` might want updating too

2017-12-04 17:00 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +        );
Done

2017-12-04 18:13 UTC, alexbishop1 requested changes
Looks basically done. Please rebase and then add another commit to rename `StatusUpdater` to `ChargeStatusUpdater`.

2017-12-05 10:25 UTC, alexbishop1 requested changes
Looks great except that `RefundStatusUpdaterTest` seems to have been accidentally renamed to `RefundChargeStatusUpdaterTest`

2017-12-05 11:02 UTC, alexbishop1 approved these changes
🎁

2017-12-05 11:02 UTC, merged