PP-12173 upgrade to Dropwizard 3
alphagov/pay-connector pull request #5107
Opened 2024-04-09 14:00 UTC by SandorArpa

## WHAT YOU DID## WHAT YOU DID

- upgrade to Dropwizard 3

2024-04-10 13:45 UTC, alexbishop1 requested changes
Looking good! Just a few small tweaks and I think we’re there!

2024-04-10 13:45 UTC, alexbishop1 commented on .github/dependabot.yml
> +          - ">= 4"
We can use the same comment as https://github.com/alphagov/pay-adminusers/blob/659a230d6a4d6b66cb54ec807b70caa3fc07e419/.github/dependabot.yml#L10-L13 for consistency.

2024-04-10 13:45 UTC, alexbishop1 commented on pom.xml
> +                <version>3.0.6</version>
There’s a 3.0.7 now.

2024-04-10 13:45 UTC, alexbishop1 commented on pom.xml
> +        </dependency>
Can you put this next to the other Guice dependencies?

2024-04-10 13:45 UTC, alexbishop1 commented on pom.xml
> +            <version>3.4.1</version>
We’re up to 3.5.2 now.

2024-04-10 13:45 UTC, alexbishop1 commented on pom.xml
> +
Rogue blank line?

2024-04-10 13:45 UTC, alexbishop1 commented on pom.xml
> +            <version>3.0.6</version>
Should also be 3.0.7.

2024-04-10 13:45 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/ClientFactory.java
> +                .name(format("%s.%s", gatewayName, operation)).build();
I assume this pattern comes is copied somewhere else where we’re already using HttpClient 5?

2024-04-10 13:45 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/TokenDaoJpaIT.java
> +        assertThat(tokenDao.findByTokenId("present-day-token").isPresent(), is(true));
Good spot!

2024-04-10 14:01 UTC, SandorArpa commented on .github/dependabot.yml
> +          - ">= 4"
👍

2024-04-10 14:01 UTC, SandorArpa commented on pom.xml
> +                <version>3.0.6</version>
👍

2024-04-10 14:02 UTC, SandorArpa commented on pom.xml
> +        </dependency>
👍

2024-04-10 14:03 UTC, SandorArpa commented on pom.xml
> +            <version>3.4.1</version>
👍

2024-04-10 14:03 UTC, SandorArpa commented on pom.xml
> +
👍

2024-04-10 14:03 UTC, SandorArpa commented on pom.xml
> +            <version>3.0.6</version>
👍

2024-04-10 14:05 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/dao/TokenDaoJpaIT.java
> +        assertThat(tokenDao.findByTokenId("present-day-token").isPresent(), is(true));
👍

2024-04-10 14:38 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/ClientFactory.java
> +                .name(format("%s.%s", gatewayName, operation)).build();
No, I re-wrote it. We don't use this setup anywhere else.
Dropwizard 3:
`
+- io.dropwizard:dropwizard-client:jar:3.0.7:compile
|  +- org.glassfish.jersey.core:jersey-client:jar:2.41:compile
|  +- org.apache.httpcomponents.client5:httpclient5:jar:5.3.1:compile
|  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2.4:compile
|  +- org.apache.httpcomponents.core5:httpcore5:jar:5.2.4:compile
|  \- io.dropwizard.metrics:metrics-httpclient5:jar:4.2.25:compile`
and it comes with `com.codahale.metrics.httpclient5.InstrumentedHttpClientConnectionManager` which depends on apache's client5.

2024-04-10 15:58 UTC, alexbishop1 requested changes
Just a couple of final things and then we’re good!

2024-04-10 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/ClientFactory.java
> +                .socketFactoryRegistry(org.apache.hc.core5.http.config.RegistryBuilder.<ConnectionSocketFactory>create()
I don’t think `RegistryBuilder` needs to be full qualified.

2024-04-10 15:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/ClientFactory.java
> +                .timeToLive(TimeValue.of(java.time.Duration.ofMillis(connectionTimeToLive.toMilliseconds())))
We could avoid the confusion with the two different `Duration` types (argh!) by doing this:

```java
.timeToLive(TimeValue.ofMilliseconds(connectionTimeToLive.toMilliseconds()))
```

2024-04-10 16:02 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/ClientFactory.java
> +                .timeToLive(TimeValue.of(java.time.Duration.ofMillis(connectionTimeToLive.toMilliseconds())))
Good catch 👍

2024-04-10 16:02 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/ClientFactory.java
> +                .socketFactoryRegistry(org.apache.hc.core5.http.config.RegistryBuilder.<ConnectionSocketFactory>create()
👍

2024-04-10 16:05 UTC, alexbishop1 approved these changes, later dismissed
🥳

2024-04-10 16:09 UTC, alexbishop1 submitted a review, later dismissed

2024-04-12 08:44 UTC, alexbishop1 requested changes
A couple of dependencies are in the wrong place in the POM (which makes no functional difference, just makes it a little harder to follow).

2024-04-12 08:44 UTC, alexbishop1 commented on pom.xml
> +        </dependency>
This should be in the `<!-- Main dependencies that are imported from one of the BOMs…` bit.

2024-04-12 08:44 UTC, alexbishop1 commented on pom.xml
>          </dependency>
All three of thre JJWT dependencies belong in the `<!-- Main dependencies that need explicit versions -->` bit.

2024-04-12 08:53 UTC, SandorArpa commented on pom.xml
> +        </dependency>
👍

2024-04-12 08:53 UTC, SandorArpa commented on pom.xml
>          </dependency>
🤦

2024-04-12 10:21 UTC, alexbishop1 approved these changes
🥳

2024-04-12 10:31 UTC, merged