Pp 12354 using service id instead of gateway
alphagov/pay-connector pull request #5148
Opened 2024-04-22 13:49 UTC by james-peacock-gds

Adding endpoints with serviceId / accountType parameters in place of gatewayAccountId.

2024-04-26 13:29 UTC, DomBelcher submitted a review, later dismissed
A few things worth discussing/thinking about further

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +                .body("credentials", is(nullValue()));
This is more a problem with the obfuscation of creating the gateway accounts, but it's not clear whether the card_types and credentials are null because they're not returned, or they just don't exist on the account - I think it's actually both in this case, there are no credentials created on the gateway account, but if there were they wouldn't be returned

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +                .body("requires3ds", is(true));
I think this test could be combined with `getAccountByServiceIdAndAccountTypeShouldNotReturnCredentialsOrCardTypes`

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +                .body("corporate_prepaid_debit_card_surcharge_amount", is(corporatePrepaidDebitCardSurchargeAmount));
This could also be combined with `getAccountByServiceIdAndAccountTypeShouldNotReturnCredentialsOrCardTypes`

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +                .body("credentials", is(nullValue()));
I've dug into this and it seems that this is an outdated test. The `credentials` field on `gateway_accounts` was dropped (#3117) but this test persisted. I assume it can safely be deleted

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountFrontendResourceIT.java
> +        app.createAGatewayAccountWithServiceId("a-service-id");
My feeling is we shouldn't use this method of creating accounts, as it works by doing a POST request to the `/v1/api/accounts` endpoint, rather than inserting a record directly into the database, which makes the test depend on that endpoint functioning correctly as well.

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +    void shouldReturnAccountInformationForGetAccountByServiceIdAndAccountType_withWorldpayCredentials() {
The naming of the tests is a bit inconsistent, and they could be broken up a bit to increase readability - e.g. 
`getAccountByServiceIdAndAccountType_withWorldpayCredentials_shouldReturnAccountInformation`

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +                .withDatabaseTestHelper(app.getDatabaseTestHelper())
I think this method of creating a test account is better as it works directly with the database. It is also possible to use `app.getDatabaseFixtures()` instead of using the static `DatabaseFixtures`

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +    void shouldReturnAccountInformationForGetAccountByServiceIdAndAccountType_withWorldpayCredentials() {
Another option would be to use the `@Nested` annotation in JUnit5 to create groups of tests for each method, e.g. having 

```
@Nested
class GetAccountByServiceIdAndAccountType {
  @Test
  void withWorldpayCredentials_shouldReturnAccountInformation() {
    // test body
  }
  // rest of tests...
}
```

which would make it easier to separate the tests for different methods. Could also use the `@DisplayName` annoation to show the API endpoint instead of the class name, e.g. `@DisplayName("GET /v1/services/{serviceId}/{accountType}/account")`

This would be a break from current convention but could be a nice convention to establish going forward - maybe worth further discussion

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +    void shouldNotReturn3dsFlexCredentials_whenGatewayAccountHasNoCreds_byServiceIdAndAccountType_byServiceIdAndAccountType() {
Method name duplicates `byServiceIdAndAccountType`

2024-04-26 13:29 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +    void shouldReturn3dsFlexCredentials_whenGatewayAccountHasCreds_byServiceIdAndAccountType() {
Could be combined with `shouldReturnAccountInformationForGetAccountByServiceIdAndAccountType_withWorldpayCredentials` - I think we should look to combine the happy path tests into a few which test important cases, e.g. `worldpay` and `stripe` payment providers, and possibly `test` and `live` account types.

2024-04-26 14:52 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +                .body("credentials", is(nullValue()));
The `card_types` parameter also appears to be outdated. The `getCardTypes()` method on `GatewayAccountEntity` was previously annotated with `@JsonProperty(card_types)`, so this tested that wasn't returned, but this has since changed. Not sure it's worth keeping around, it certainly feels overkill to have a test dedicated to it

2024-05-07 11:14 UTC, oswaldquek requested changes
For the future, a PR for one endpoint would be better :)

2024-05-07 11:14 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/GatewayAccountResource.java
> +                .map(gatewayAccount -> successResponseWithEntity(ImmutableMap.of(CARD_TYPES_FIELD_NAME, gatewayAccount.getCardTypes())))
Could use the standard Java Map instead of ImmutableMap here...

2024-05-07 11:14 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/dao/GatewayAccountDaoIT.java
> +                .insert();
Can we add another gateway account to make sure the code won't fall over if there are two accounts?

2024-05-07 11:14 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +    void shouldReturnAccountInformation_withWorldpayCredentials_whenGetByServiceIdAndAccountType() {
Could shorten this to shouldReturnWorldpayAccountInformation_whenGetByServiceIdAndAccountType. The test tests all the account information exists, not just the worldpay credentials so we can remove this from the test name.

2024-05-07 11:14 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +                .body("gateway_account_credentials[0].gateway_account_id", is(accountIdAsInt))
accountIdAsInt is only used here, so it could inlined as `Math.toIntExact(accountId)` and line 135 can go.

2024-05-07 11:14 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceIT.java
> +    void shouldReturnAccountInformation_withStripeCredentials_whenGetByServiceIdAndAccountType() {
Like the test above, do we want to test for all the returned parameters, rather than just the credentials?

2024-05-07 12:09 UTC, oswaldquek approved these changes

2024-05-08 10:52 UTC, merged