PP-12374 Pass Wallet Payments authorisation success to metrics and alerts
alphagov/pay-connector pull request #5182
Opened 2024-05-01 15:43 UTC by marcotranchino

With a previous PR[1], we have clarified the logs written by Connector when a
Google Pay or an Apple Pay payment is rejected, by indicating the charge
status more clearly, and then that the connection request had been
successful, despite the payment didn't go through.

With this change, we are now correcting the `successOrFailure` value being
passed on to metrics and alerts.

Previously we were passing success or failure depending on the connection to
the Payment Gateway being successful or not.

With this change, we are now passing `success` only in two cases:
- if the payment has gone through, i.e. only for a charge status of
  `AUTHORISATION SUCCESS`
- if 3D Secure authorisation is required, i.e. for a charge status of
  `AUTHORISATION_3DS_REQUIRED`

The latter happens only in a small proportion of Google Pay payments, and we
have agreed to count these as success(close enough and there will not be many
of them).

For all other charge status values, we will from now on be passing on the
`failure` value.

Further information in JIRA[2].

[1]
https://github.com/alphagov/pay-connector/pull/5176

[2]
https://payments-platform.atlassian.net/browse/PP-12374

## REQUEST FOR FEEDBACK

Are we happy to count success just for AUTHORISATION_SUCCESS ?
In src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeStatus.java we have other options that are not failures, e.g. AUTHORISATION_SUBMITTED or CAPTURE_APPROVED etc.

Would we want to pass something other than success/failure for those cases?

## How to test

Manually, locally
Searching in Splunk after deployment

## Code review checklist

### Logging

- [ ] ~~only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert~~.

### Documentation

- [ ] ~~Updated README.md for any of the following ?~~

* ~~Introduced any new environment variables / removed existing environment variable~~
* ~~Added new API / updated existing API definition~~

2024-05-02 08:59 UTC, marcotranchino commented
I have discussed with @jfharden and ascertained that if this PR is approved as is, there is no need to change any metrics or dashboards, given that this PR is only changing what counts as success and what counts as failure, and there's no change to the possible values. [Further details in JIRA](https://payments-platform.atlassian.net/browse/PP-12374).

2024-05-03 08:50 UTC, alexbishop1 requested changes
Looks good! Just a few minor suggestions.

> Are we happy to count success just for AUTHORISATION_SUCCESS ?
In src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeStatus.java we have other options that are not failures, e.g. AUTHORISATION_SUBMITTED or CAPTURE_APPROVED etc.
>
> Would we want to pass something other than success/failure for those cases?

Most of those statuses cannot happen at this point. Almost all of the time it’s going to be `AUTHORISATION_SUCCESS`, `AUTHORISATION_REJECTED` or (more rarely) `AUTHORISATION_ERROR`.

For Google Pay, a small number of payments may go `AUTHORISATION_3DS_REQUIRED`, which is neither success nor failure (it’s saying 3D Secure authorisation is required). We can probably count these as success (close enough and there will not be many of them).

Anything else either is not going to happen at this point or can be classed as a failure.

2024-05-03 08:50 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +        }
This might be a good opportunity for a ternary operator.

2024-05-03 08:50 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/wallets/WalletAuthoriseServiceTest.java
> +        verify(mockAppender, times(4)).doAppend(loggingEventArgumentCaptor.capture());
I’d say `atLeast(1)` rather than `times(4)` to make this less brittle.

2024-05-03 09:40 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +        }
Amended, thanks! :)

2024-05-03 09:40 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/wallets/WalletAuthoriseServiceTest.java
> +        verify(mockAppender, times(4)).doAppend(loggingEventArgumentCaptor.capture());
Amended, thanks! :)

2024-05-03 09:43 UTC, marcotranchino commented
Hi @alexbishop1 
Thanks for the review! 
I have made the suggested amendments, so this is now ready for re-review.
Cheers :)

2024-05-03 12:20 UTC, marcotranchino commented
~~[Concourse-ci integration tests are failing ](https://pay-cd.deploy.payments.service.gov.uk/builds/122348060) but the issue seems to be unrelated to this change ([I have verified that they fail with a copy from main too](https://github.com/alphagov/pay-connector/pull/5193)).~~

2024-05-03 13:59 UTC, alexbishop1 requested changes
Change the wildcard imports and this is good to go.

2024-05-03 13:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/wallets/WalletAuthoriseServiceTest.java
> +import static org.mockito.Mockito.*;
Please do not use wildcard imports.

2024-05-03 14:06 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/wallets/WalletAuthoriseServiceTest.java
> +import static org.mockito.Mockito.*;
Amended, thanks

2024-05-03 14:07 UTC, marcotranchino commented
Amended, thanks!

2024-05-07 08:33 UTC, alexbishop1 approved these changes

2024-05-07 08:39 UTC, merged