PP-12354 Add get Stripe account by serviceId
alphagov/pay-connector pull request #5207
Opened 2024-05-08 14:11 UTC by james-peacock-gds

- add endpoint to get Stripe account by serviceId and accountType
- add integration tests

2024-05-08 16:20 UTC, DomBelcher requested changes
Nice work, just a few small suggestions

2024-05-08 16:20 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +                .orElseThrow(NotFoundException::new);
We could add in specific error messages for if no account is found, or the account is not a Stripe account, or there are no stripe credentials

2024-05-08 16:20 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/StripeAccountResourceIT.java
> +        public void getStripeAccountReturnsSuccessfulResponse() {
Could remove `public` modifier and `getStripeAccount` from method name, as this is included in the nested class name - similarly for other tests
While these are existing tests, it's only a minor change that should improve readability

2024-05-08 16:20 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/StripeAccountResourceIT.java
> +        public void getStripeAccountReturnsSuccessfulResponse() {
As above, could shorten to `returnsSuccessfulResponse`, and remove `public`

2024-05-09 14:10 UTC, DomBelcher requested changes
Nice work, just a couple of very minor changes

2024-05-09 14:10 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/StripeAccountResourceIT.java
> +                    .body("message[0]", is(format("Gateway account not found for service ID [unknown-service-id] and account type [test]")));
`format` isn't necessary if hardcoding the `serviceId` and `accountType`

2024-05-09 14:10 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/StripeAccountResourceIT.java
> +                    .post("/v1/api/accounts/" + accountId + "/credentials");
Might as well add a `.then().statusCode(200)` here

2024-05-09 14:11 UTC, oswaldquek commented
Separation between the `@Nested` GetStripeAccountByGatewayAccountId and GetStripeAccountByServiceIdAndAccountType - nice! 🎉

2024-05-09 14:20 UTC, DomBelcher approved these changes
Nice work 👍

2024-05-09 14:44 UTC, merged