PP-12357-Create-agreement-by-serviceId
alphagov/pay-connector pull request #5225
Opened 2024-05-13 16:42 UTC by james-peacock-gds

- Add new endpoint to create an agreement for a specific serviceId and accountType.

2024-05-14 08:37 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResource.java
> +                .orElseThrow(NotFoundException::new);
I think you'd be able to do this all within the `Optional` using `flatMap`, something like
```
gatewayAccountService.getGatewayAccountByServiceIdAndAccountType(serviceId, accountType)
        .or(() -> { /* throw error ... */ })
        .map(GatewayAccountEntity::getId)
        .flatMap(gatewayAccountId -> agreementService.create(agreementCreateRequest, gatewayAccountId))
        .orElseThrow(NotFoundException::new)
```

2024-05-14 08:37 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResource.java
> +        return Response.status(SC_CREATED).entity(agreementResponse).build();
It might also be possible to just return the `agreementResponse`, although maybe this is necessary to set the status code

2024-05-16 13:33 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResource.java
> +                .orElseThrow(NotFoundException::new);
thanks, done something similar

2024-05-16 13:34 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResource.java
> +        return Response.status(SC_CREATED).entity(agreementResponse).build();
yes i think this is how the status code is set

2024-05-16 15:41 UTC, DomBelcher requested changes
Nice work, just a few things to address

2024-05-16 15:41 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/agreement/service/AgreementService.java
> +    public Optional<AgreementResponse> create(AgreementCreateRequest agreementCreateRequest, String serviceId, GatewayAccountType accountType) {
Rather than overloading the `create` method, can this be renamed `createByServiceIdAndAccountType`?

2024-05-16 15:41 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/agreement/service/AgreementService.java
> +        return agreementResponseBuilder.build();
You could avoid having to having to use a local variable for the response builder by doing 
```
return new AgreementResponseBuilder()
      .withAgreementId(agreementEntity.getExternalId())
      .withCreatedDate(agreementEntity.getCreatedDate())
      .withReference(agreementEntity.getReference())
      .withServiceId(agreementEntity.getServiceId())
      .withLive(agreementEntity.isLive())
      .withDescription(agreementEntity.getDescription())
      .withUserIdentifier(agreementEntity.getUserIdentifier())
      .build();

```

2024-05-16 15:41 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceTest.java
> +            .addResource(new AgreementsApiResource(agreementService, gatewayAccountService))
With the change to lookup the gateway account in `AgreementService` it's no longer necessary to have the gateway account service be available to `AgreementsApiResource`, so you could revert to the original constructor

2024-05-16 15:41 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceTest.java
> +    class createAgreementByGatewayAccountId {
Capitalise class name

2024-05-16 15:41 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceTest.java
> +        void returnsSuccessfulResponse() {
Could add `_forValidRequest` to the test name, but may be somewhat redundant

2024-05-16 15:41 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/agreement/resource/AgreementsApiResourceTest.java
> +    class createAgreementByServiceIdAndAccountType {
Capitalise class name

2024-05-16 15:41 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +    class byGatewayAccountId {
Capital

2024-05-16 15:41 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +    class byServiceIdAndAccountType {
capital

2024-05-16 15:41 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +        }
It would be good to test that the agreement is actually created in the database, either by calling an API endpoint if one exists, or by querying the database if not

2024-05-17 11:47 UTC, DomBelcher requested changes
Nice work, just some minor things

2024-05-17 11:47 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +
Might as well delete this line unless there's some specific reason for having it - while it was already in the codebase I'm not sure there's any point to it, other than maybe separating the API call code from the assertions, but I've not seen it done anywhere else. It's probably just an old typo that snuck in

2024-05-17 11:47 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +        void shouldReturn204AndCancelAgreement() {
A question about how the tests are divided up - at the moment they're in two nested blocks, `ByGatewayAccountId` and `ByServiceIdAndAccountType`, are these to group together the all the tests for each of the two classes of endpoints, rather than the tests for each endpoint? This test is for the `cancel` endpoint, although it's the only one there is for that endpoint.

2024-05-17 11:52 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +        void shouldReturn204AndCancelAgreement() {
yes, I think ultimately it would be best to have four nested classes, to cover create by gw, create by service, cancel by gw and cancel by service - I can make that change when I add the new cancel endpoint

2024-05-17 11:53 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +
well spotted, removed.

2024-05-20 10:34 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +    }
You could remove this constructor, although it doesn't really matter whether it's in or not

2024-05-20 10:34 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +            ));
Again optional but you could replace the uses of `objectMapper.writeValueAsString` with `toJson` from `uk.gov.pay.connector.util.JsonEncoder`, which would mean you could also remove the `throws JsonProcessingException` from the tests using `objectMapper`

2024-05-20 10:46 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +    }
thanks, removed.

2024-05-20 10:46 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +            ));
thanks, will look at this change in next PR

2024-05-20 11:01 UTC, DomBelcher approved these changes
Nice work 👍

2024-05-20 11:02 UTC, merged