PP-11555 create transfer to send back to connect account
alphagov/pay-connector pull request #5254
Opened 2024-05-20 11:10 UTC by AbdirizakIdris

## WHAT YOU DID
- handle error thrown when creating Stripe transfer

2024-05-20 15:28 UTC, alexbishop1 requested changes
Looks like a good start. Some suggestions in the comments.

2024-05-20 15:28 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/RefundReversalResourceIT.java
> +        Map<String, Object> emptymap = new HashMap<>();
There is a wonderful thing `Collections.emptyMap()`, which would work here. I’d just put it inline where it’s used (so on line 151 replace `emptymap` with `Collections.emptyMap()`).

2024-05-20 15:28 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/RefundReversalResourceIT.java
> +        when(mockStripeSdkClient.getRefund(eq(STRIPE_REFUND_ID), anyBoolean())).thenReturn(null);
I suspect we want this to actually return something real or it’s not going to progress far enough to actually do the transfer.

2024-05-20 15:28 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/RefundReversalResourceIT.java
> +                .statusCode(Response.Status.INTERNAL_SERVER_ERROR.getStatusCode());
We should also assert that the body contains the error message. You can do this with `.body(…)`. For an example, look at some of the tests for errors in `CardResourceAuthoriseIT`.

If you want to peek at what the body actually is, you can add `.log().body();` to the end and it will be output in the test logs (don’t forget to remove this before you commit!).

2024-05-31 14:32 UTC, alexbishop1 requested changes
Looking better! Finish tidying it up and squash the commits and I’ll take a final look.

2024-05-31 14:32 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeSdkClient.java
> +        System.out.println(transferRequest);
Remember to remove this before merging.

2024-05-31 14:32 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/refund/service/RefundReversalService.java
> +                    format("There was an error trying to get refund with ID:%s from Stripe", refundExternalId + e.getMessage()));
Message should be updated: it could be an error with the transfer.

2024-05-31 14:32 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/RefundReversalResourceIT.java
> +        doThrow(new ApiException(" an error occurred", "500", null, null, null))
Perhaps use something a little less generic (maybe “A specific exception message” or something) so it’s clearer when we assert it’s there later on.

2024-05-31 14:32 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/RefundReversalStripeConnectTransferRequestBuilderTest.java
> +        //String[] expandArray = (String[]) builderRequest.get("expand");
Remove this line please.

2024-06-27 11:13 UTC, AbdirizakIdris commented
Closing this - Made a new PR https://github.com/alphagov/pay-connector/pull/5365

2024-06-27 11:13 UTC, closed without merging