PP-12357 Cancel agreement by service ID
alphagov/pay-connector pull request #5263
Opened 2024-05-21 09:27 UTC by james-peacock-gds

- add endpoint to cancel agreement by service ID and account type
- add method to find agreement by external ID, service ID and account type
- make AgreementDAO find agreement method names more specific as this is clearer than overloading
- add unit and integration tests

2024-05-21 14:13 UTC, oswaldquek requested changes

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +            public void shouldThrowGatewayAccountNotFoundException() {
I think you should stick to the original naming `shouldThrowException_whenGatewayAccountNotFound`. `shouldThrowGatewayAccountNotFoundException` doesn't say under what circumstance a Not Found Exception is thrown.

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +            public void shouldThrowAgreementNotFoundException() {
`shouldThrowException_whenGatewayAccountNotFound`

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +            public void withUserDetails_ShouldMoveToCancelStatusForActivePaymentInstrument() {
I know you didn't write this test but we should take the opportunity to make this name better. I have no clue what this test description is trying to convey. I suggest something like `cancelAgreementSuccessfully`.

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +            public void withoutUserDetails_ShouldMoveToCancelStatusForActivePaymentInstrument() {
I suggest something like `canCancelAgreementSuccessfullyIfUserDetailsNotProvided`.

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +            public void shouldThrowGatewayAccountNotFoundException() {
`shouldThrowNotFoundException_whenGatewayAccountDoesNotExist`

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +            public void withUserDetails_ShouldMoveToCancelStatusForActivePaymentInstrument() {
I suggest something like `cancelAgreementSuccessfully`.

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/agreement/service/AgreementServiceTest.java
> +            public void withoutUserDetails_ShouldMoveToCancelStatusForActivePaymentInstrument() {
I suggest something like `canCancelAgreementSuccessfullyIfUserDetailsNotProvided`.

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                .insert();
Is it not possible to create this using an API call?

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                app.getDatabaseTestHelper().addPaymentInstrument(paymentInstrumentParams);
Is it not possible to create a payment instrument using an API call?

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                app.getDatabaseTestHelper().addAgreement(agreementParams);
Is it not possible to create an agreement using an API call?

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                var paymentInstrumentMap = app.getDatabaseTestHelper().getPaymentInstrument(paymentInstrumentParams.getPaymentInstrumentId());
Is it not possible to get a payment instrument using an API call?

2024-05-21 14:13 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                var agreementMap = app.getDatabaseTestHelper().getAgreementByExternalId(agreementId);
Is it not possible to get an agreement using an API call?

2024-05-21 14:13 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/agreement/dao/AgreementDao.java
> +                .filter(agreementEntity -> agreementEntity.isLive() ? accountType.equals(GatewayAccountType.LIVE) : accountType.equals(GatewayAccountType.TEST))
It's unlikely doing this will have a negative performance impact, but it's good practice to use a join query like [this](https://github.com/alphagov/pay-ledger/blob/8c355acb4816049e552f7de582d876cfcdda180d/src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java#L29). In a world where there could be many gateway account types, it's more optimal to get the database to return only the relevant data, rather than returning all and filtering it in java.

2024-05-21 16:05 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                .insert();
yes, accounts are created via the API for the createAgreement by serviceId tests. But for the cancel agreement tests, the test data is created in the database directly because it's laborious to apply a payment instrument to an agreement via the API

2024-05-21 16:06 UTC, james-peacock-ho commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                app.getDatabaseTestHelper().addPaymentInstrument(paymentInstrumentParams);
see above

2024-05-21 16:06 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                app.getDatabaseTestHelper().addAgreement(agreementParams);
see above

2024-05-22 09:54 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                app.getDatabaseTestHelper().addAgreement(agreementParams);
have changed this so the gateway account and agreement are created by API call.

2024-05-22 09:55 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                .insert();
have changed this so the gateway account and agreement are created by API call, but the payment instrument is created in the database for the reasons above.

2024-05-22 09:56 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/agreement/dao/AgreementDao.java
> +                .filter(agreementEntity -> agreementEntity.isLive() ? accountType.equals(GatewayAccountType.LIVE) : accountType.equals(GatewayAccountType.TEST))
turns out we don't even need a join, just another boolean in the query.

2024-05-22 09:58 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/agreement/dao/AgreementDao.java
> +                "AND ae.live = :live";
Can you check if `ae.live` means the agreement is "live", or if this is referring to whether the gateway account is live.

2024-05-22 10:05 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/agreement/dao/AgreementDao.java
> +                "AND ae.live = :live";
It means the gateway account is live.https://github.com/alphagov/pay-connector/blob/b7c5157e34474690f4949dc4c1b1ac74a4a46f9b/src/main/java/uk/gov/pay/connector/agreement/service/AgreementService.java#L88

2024-05-22 10:07 UTC, oswaldquek approved these changes

2024-05-22 10:08 UTC, merged