PP-12356 Add PATCH /v1/api/service/{serviceId}/[test|live]/credentials/{credentialsId} endpoint
alphagov/pay-connector pull request #5264
Opened 2024-05-21 13:38 UTC by DomBelcher

## WHAT YOU DID
 - Add `PATCH /v1/api/service/{serviceId}/[test|live]/credentials/{credentialsId}` endpoint
 - Add tests for endpoint
 - Add constructor to `GatewayAccountNotFoundException` to create exception for service ID and account type

## How to test
 - Run tests

2024-05-21 15:46 UTC, james-peacock-gds requested changes
Looks really good. A couple of points for discussion (not necessarily changes required) and some minor things to remove/rename.

2024-05-21 15:46 UTC, james-peacock-gds commented on src/main/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResource.java
> +                    .findFirst())
should some of the above logic be handled using a join in the db query? I guess one upside of doing it the way you've done it is you can throw a GatewayAccountNotFoundException if there's no account.

2024-05-21 15:46 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResourceIT.java
> +
remove commented code above

2024-05-21 15:46 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResourceIT.java
> +            }
I don't understand why this message is produced. What have digital wallets to do with this?

2024-05-21 15:46 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResourceTest.java
> +        class CreateGatewayAccountCredentials_byServiceIdAndAccountType {
I think we can remove _byServiceIdAndAccountType because that's in the outer class name

2024-05-21 15:46 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResourceTest.java
> +        class Update3dsFlexCredentials_byServiceIdAndAccountType {
I think we can remove _byServiceIdAndAccountType because that's in the outer class name

2024-05-21 15:46 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResourceTest.java
> +        class ValidateWorldpay3dsCredentials_byServiceIdAndAccountType {
I think we can remove _byServiceIdAndAccountType because that's in the class name

2024-05-21 15:46 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResourceTest.java
> +        class PatchGatewayAccountCredentials_byServiceIdAndAccountType {
I think we can remove _byServiceIdAndAccountType because that's in the class name

2024-05-21 15:49 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResourceIT.java
> +
Good spot, thanks

2024-05-22 09:53 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResource.java
> +                    .findFirst())
It's worth considering but I'll look at this in another PR

2024-05-22 09:54 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/gatewayaccountcredentials/resource/GatewayAccountCredentialsResourceIT.java
> +            }
This is apparently a legacy from when only Worldpay supported digital wallets, but the `gateway_merchant_id` field is still only applicable to Worldpay. I've updated the error message to be more accurate

2024-05-22 10:20 UTC, james-peacock-gds submitted a review, later dismissed

2024-05-22 11:16 UTC, james-peacock-gds approved these changes, later dismissed
LGTM

2024-05-22 11:31 UTC, james-peacock-gds approved these changes
still good

2024-05-22 11:32 UTC, merged