PP-12358 degateway resend confirmation email endpoint
alphagov/pay-connector pull request #5308
Opened 2024-06-03 14:07 UTC by nlsteers

## WHAT YOU DID

- add new endpoint to charges api resource for resending confirmation emails with `serviceId` and `accountType`
- update unit and integration tests
- update surefire and failsafe configurations to show JUnit 5 '@DisplayName' in the maven logs
- update `DatabaseFixtures` helper methods to return `GatewayAccountType`
- update OpenAPI spec

2024-06-03 16:01 UTC, DomBelcher requested changes
Nice work, just a few suggestions/comments

2024-06-03 16:01 UTC, DomBelcher commented on openapi/connector_spec.yaml
> +      operationId: resendConfirmationEmail_1
I guess the `_1` is added automatically due to overloading the `resendConfirmationEmail` method - so far I think all the new endpoints have methods ending `ByServiceIdAndAccountType`, admittedly it's a bit verbose but it does make it easier to find the de-gatewayed methods. For the sake of consistency I'd advocate continuing that but its not a hill I'll die on

2024-06-03 16:01 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/charge/resource/ChargesApiResource.java
> +                .orElseGet(() -> responseWithChargeNotFound(chargeId));
You could combine all the logic into one flow by using `or` and `flatMap` on the result of `getGatewayAccountByServiceIdAndAccountType`, something like
```
return gatewayAccountService.getGatewayAccountByServiceIdAndAccountType(...)
    .or(() -> /* throw gateway account not found error */)
    .flatMap(account -> chargeService.findCharge(...))
    .or(() -> /* throw charge not found error */)
    .flatMap(charge -> userNotificationService.sendPaymentConfirmedEmailSynchronously(...))
    .orElseGet(() -> /* failed to send email response */)
```

2024-06-03 16:01 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceResendConfirmationEmailIT.java
> +    private static final ITestBaseExtension TEST_BASE_EXTENSION = new ITestBaseExtension("sandbox", APP.getLocalPort(), APP.getDatabaseTestHelper());
Because `AppWithPostgresAndSqsExtension` and `ITestBaseExtension` aren't primitive I'd argue against treating them as constants (even if there's no methods for mutating them) - making them `final` is sensible however I would advocate for camel case naming, even if just for consistency across the codebase

2024-06-03 16:01 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceResendConfirmationEmailIT.java
> +        class ByServiceIdAndAccountType {
It messes with your `Given`-`When` pattern a bit but so far we've structured the nesting as `ByAccountId`/`ByServiceIdAndAccountType` on the top level, with the individual method tests on the next level - I think that way is preferable, particularly if the `ByAccountId` endpoints will one day be deprecated

2024-06-03 16:01 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceResendConfirmationEmailIT.java
>              ChargesApiResourceResendConfirmationEmailIT.ConnectorAppWithCustomInjector.class,
Not your code I know but while we're here is it worth looking at whether we can remove the need for this mock and make this more of a proper integration test? My guess is the notification client makes an HTTP request that we should be able to stub with wiremock, although if the config options aren't there to make it easy to drop a new URL in for the notification client it might be a fair bit of work.

2024-06-03 16:01 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceResendConfirmationEmailIT.java
> +                        .post(format("/v1/api/service/%s/account/%s/charges/%s/resend-confirmation-email", testAccount.getServiceId(), testAccount.getGatewayAccountType(), chargeId))
We should avoid using the test account from `ITestBaseExtension` where possible in new endpoints as it's created in the database rather than by an API call

2024-06-03 16:01 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceTest.java
> +        class WhenAccountIdIsProvided {
As in the integration tests, current convention is to group by gatewayed/degatewayed at the top level

2024-06-03 16:01 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceTest.java
> +            void createCharge_invalidAuthorisationMode_shouldReturn400() {
Could remove the `createCharge_` prefix from the test names since it's under a nested block

2024-06-03 16:01 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/dao/DatabaseFixtures.java
> +            String userExternalId = testRefund.getSubmittedByUserExternalId();
Is this change intentional?

2024-06-03 16:10 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/it/dao/DatabaseFixtures.java
> +            String userExternalId = testRefund.getSubmittedByUserExternalId();
hmm, not sure how that got in there

2024-06-03 16:16 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceTest.java
> +        class WhenAccountIdIsProvided {
sure but I have two different endpoints being tested in this class. Perhaps one should be broken out into a separate file but I wasn't of a mind to change too much about existing tests for unchanged endpoints in this PR

2024-06-04 08:37 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceResendConfirmationEmailIT.java
> +    private static final ITestBaseExtension TEST_BASE_EXTENSION = new ITestBaseExtension("sandbox", APP.getLocalPort(), APP.getDatabaseTestHelper());
Strings aren't primitive either but we treat those as constants 😄. 

Happy to stick with established conventions here though.

2024-06-04 10:03 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceResendConfirmationEmailIT.java
> +        class ByServiceIdAndAccountType {
yeah no prob, I'll move them around

2024-06-04 10:31 UTC, nlsteers commented on src/main/java/uk/gov/pay/connector/charge/resource/ChargesApiResource.java
> +                .orElseGet(() -> responseWithChargeNotFound(chargeId));
I just lifted the old one but this is a nice idea

2024-06-04 12:54 UTC, nlsteers commented on openapi/connector_spec.yaml
> +      operationId: resendConfirmationEmail_1
yep good spot

2024-06-04 12:55 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/it/dao/DatabaseFixtures.java
> +            String userExternalId = testRefund.getSubmittedByUserExternalId();
reverted

2024-06-04 16:01 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceResendConfirmationEmailIT.java
> +                        .post(format("/v1/api/service/%s/account/%s/charges/%s/resend-confirmation-email", testAccount.getServiceId(), testAccount.getGatewayAccountType(), chargeId))
removed

2024-06-04 16:01 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/charge/resource/ChargesApiResourceResendConfirmationEmailIT.java
>              ChargesApiResourceResendConfirmationEmailIT.ConnectorAppWithCustomInjector.class,
will leave this for another time

2024-06-04 16:25 UTC, DomBelcher approved these changes
Nice work 👍

2024-06-05 08:28 UTC, merged