PP-12359 Add degatewayed endpoint for charge events
alphagov/pay-connector pull request #5358
Opened 2024-06-19 15:24 UTC by james-peacock-gds

Add get charge events by service id endpoint

2024-06-20 14:33 UTC, oswaldquek requested changes
I think the tests could be structured in a way that makes understanding easier.

2024-06-20 14:33 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +                    .get(format(CHARGE_EVENTS_BY_SERVICE_ID_URL, SERVICE_ID, GatewayAccountType.TEST, CHARGE_ID))
No biggie but I personally it easier to read if "/v1/api/accounts/%s/charges/%s/events" were inlined here.

2024-06-20 14:33 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +            createCaptureEvents(testCharge, createdDate);
I think it'd make it easier to understand if the events created in this method, and the AUTHORISATION_READY event, were all put into one method called `addFutureEvents`, so it's easily understood those wouldn't be returned by the API call.

2024-06-20 14:33 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +            createCaptureEvents(testCharge, createdDate);
same comment as above

2024-06-20 14:33 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +                    .withChargeStatus(AUTHORISATION_READY).withDate(createdDate.plusSeconds(2)).insert();
There's a massive amount of test setup here; I'd get rid of this line as it's already tested in shouldGetAllEventsForAGivenChargeWithoutRefunds and they are not events that will be returned by a call to the API.

2024-06-20 14:33 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +            ZonedDateTime historyRefund2SubmittedStartDate = createdDate.plusSeconds(11);
Hmm why are all these refunds returned, given their start dates are in the future, i.e. `createdDate.plusSeconds()`?

2024-06-20 14:33 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +                    .get(format(CHARGE_EVENTS_BY_SERVICE_ID_URL, SERVICE_ID, GatewayAccountType.TEST, "non-existent-charge"))
Hmm where is a gateway account with SERVICE_ID added in the database?

2024-06-20 14:33 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +            app.getDatabaseTestHelper().addGatewayAccount(gatewayAccountParams);
Since at a high level we're moving away from gateway accounts, I think it'd be better to follow a set up like [this](https://github.com/alphagov/pay-connector/blob/master/src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceUpdateIT.java#L38-L49). That way it's easily seen a gateway account was created with a service Id.

2024-06-20 15:01 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +            createCaptureEvents(testCharge, createdDate);
I think the fact that the events are in the future is a red herring, because all of the relevant events will be returned regardless of date. For realism I could set the start time to yesterday so all of them are in the past.

2024-06-21 14:04 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +                    .get(format(CHARGE_EVENTS_BY_SERVICE_ID_URL, SERVICE_ID, GatewayAccountType.TEST, CHARGE_ID))
updated

2024-06-21 14:05 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +            createCaptureEvents(testCharge, createdDate);
there is no filter on dates so in fact future-dated events would be returned but to avoid any confusion i've set the charge creation and associated events to yesterday's date so all events are in the past.

2024-06-21 14:06 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +                    .withChargeStatus(AUTHORISATION_READY).withDate(createdDate.plusSeconds(2)).insert();
I've done what I can to reduce the word count here by having shared methods for creating the required test entities, and comments and make it clear what is happening.

2024-06-21 14:07 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +            ZonedDateTime historyRefund2SubmittedStartDate = createdDate.plusSeconds(11);
as far as I can tell there is nothing to prevent future dates being returned

2024-06-21 14:08 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +                    .get(format(CHARGE_EVENTS_BY_SERVICE_ID_URL, SERVICE_ID, GatewayAccountType.TEST, "non-existent-charge"))
this is now added in the API call to create the account

2024-06-21 14:08 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +            app.getDatabaseTestHelper().addGatewayAccount(gatewayAccountParams);
done

2024-06-21 15:38 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +        //create the gateway account via the API
This comment probably isn't needed

2024-06-21 15:38 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceIT.java
> +        //create a £1 payment for that account
This comment probably isn't needed

2024-06-21 15:39 UTC, oswaldquek approved these changes
Some comments aren't needed, but it's not worth waiting another build for. 
The other comments are really useful and helps me understand how the system works better!

2024-06-21 15:58 UTC, merged