PP-12619: Apply strategy for returning gateway account by service id and account type
alphagov/pay-connector pull request #5430
Opened 2024-07-11 15:56 UTC by oswaldquek

If a service has multiple gateway accounts,
* If a Stripe test account is found, return it
* Otherwise return the sandbox test account
* Obviously, if there’s only one test account found, return that one, regardless of whether it is a sandbox, Stripe, or Worldpay test account
* The only way for a Worldpay test account to be returned is if that’s the only test gateway account found on that service

2024-07-11 15:57 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/service/GetGatewayAccountByServiceIdAndAccountTypeTest.java
> +        //TODO
This will implemented in next PR

2024-07-12 06:39 UTC, james-peacock-gds requested changes
One small change to a test name.

As well as the exception test that you are doing in the next PR, maybe also:
- include a test scenario where there are obscure accounts like Smartpay? (or do these no longer exist for test or live?)
- integration test for the get /v1/api/service/{serviceId}/account/{accountType} endpoint?

2024-07-12 06:39 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/dao/GatewayAccountDaoIT.java
>      void findByServiceIdAndAccountType_shouldReturnMostRecentlyAddedAccount_whenMultipleAccountsExist() {
Maybe the name of this test should change as the behaviour is different

2024-07-12 12:11 UTC, james-peacock-gds approved these changes
LGTM!

2024-07-12 12:14 UTC, merged