PP-12619: Throw error if there are multiple live gateway accounts
alphagov/pay-connector pull request #5437
Opened 2024-07-12 15:36 UTC by oswaldquek

Throw error if there are multiple live gateway accounts associated with a service.

2024-07-12 16:05 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/GatewayAccountService.java
> +        }
Since the `gatewayAccounts` list is the result of finding the accounts for that service ID/type combo, every account in the list should be either test or live, in which case you can just do `if(accountType.equals(LIVE) && gatewayAccounts.size() > 1)` - not that it really matters, it's probably only the tiniest fraction more perfomant, although it does save doing the check when querying for test accounts

2024-07-15 10:27 UTC, james-peacock-gds requested changes

2024-07-15 10:27 UTC, james-peacock-ho commented on src/main/java/uk/gov/pay/connector/gatewayaccount/exception/MultipleLiveGatewayAccountsException.java
> +        super(conflictErrorResponse(format("Multiple live gateway accounts found for service [%s]", serviceId)));
This exception wording makes sense when the existence of multiple live accounts has been identified. But in the case where there is an attempt to create a live account when one already exists, shouldn't the wording be different, e.g. "There is already a live gateway account for this service."?
Alternatively, could make the wording a bit broader to cover both scenarios - e.g. "Services should only have a single live gateway account".

2024-07-15 10:45 UTC, james-peacock-gds approved these changes

2024-07-15 12:12 UTC, merged