PP-2784 Add NOT NULL constraint on transaction_id card_3ds
alphagov/pay-connector pull request #545
Opened 2018-01-11 16:52 UTC by georgeracu

- Removed field charge_id from Card3dsEntity
- This column is not needed anymore as the linking is done via
transaction_id
- Removed DropWizard task to backfill this column
- Added NOT NULL constraint on transaction_id card_3ds as from now on is required not null

2018-01-11 17:20 UTC, alexbishop1 submitted a review, later dismissed
Looks good, with the same performance testing caveat as #544

2018-01-12 09:38 UTC, alexbishop1 requested changes
Please update the description to reflect the additional database changes this is making now

2018-01-12 09:38 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +    </changeSet>
I think we’re going to want to drop the default value that uses this sequence before doing this:

```
<changeSet id="drop default value from charge_id column in card_3ds table" author="">
    <dropDefaultValue tableName="card_3ds" columnName="charge_id"/>
</changeSet>
```

2018-01-12 10:45 UTC, georgeracu commented on src/main/resources/migrations.xml
> +    </changeSet>
Has been updated and amended commit

2018-01-15 10:36 UTC, alexbishop1 submitted a review, later dismissed
Looks good, with the same mild fear as #544 (test that adding the `NOT NULL` constraint isn’t too slow)

2018-01-18 13:10 UTC, chrisgrimble commented on src/main/resources/migrations.xml
> +    </changeSet>
Don't we just want to drop the charge_id column on card_3ds?

2018-01-18 13:34 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +    </changeSet>
I wouldn’t want to drop the column until we’re certain the backfilling was successful

2018-01-19 10:38 UTC, alexbishop1 submitted a review, later dismissed

2018-01-19 14:59 UTC, alexbishop1 approved these changes

2018-01-19 15:24 UTC, merged