PP-12915: Complete functionality when stripe test account is requested
alphagov/pay-connector pull request #5464
Opened 2024-07-26 14:41 UTC by oswaldquek

`POST /v1/service/{serviceId}/request-stripe-test-account` already creates a test account on Stripe's end. This commit additionally:
* Creates a gateway account in connector with payment provider "stripe" and type "test"
* Disables the old sandbox account
* Handles error scenarios

2024-07-29 10:06 UTC, DomBelcher requested changes

2024-07-29 10:06 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +                    @ApiResponse(responseCode = "400", description = "Stripe Connect Account already exists, or existing test account is not a Sandbox one"),
I think a `409` makes more sense in this case

2024-07-29 10:06 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountRequest.java
> +    public static final class GatewayAccountRequestBuilder {
If this is an inner class on `GatewayAccountRequest` you could just call it `Builder`, and even have `builder()` method on `GatewayAccountRequest` so it can be instantiated as `GatewayAccountRequest.builder()`

2024-07-29 10:06 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountRequest.java
> +        private @NotBlank String providerAccountType;
Does the `@NotBlank` annotation do anything here, as there's no use of `@Valid` when creating the builder? (although I admit my understand of the Javax validation API is patchy)

2024-07-29 10:06 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        JsonNode patchRequest = objectMapper.valueToTree(
I think it would be simpler & clearer to just add a `GatewayAccountService.disableAccount` method

2024-07-29 10:06 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/extension/AppWithPostgresAndSqsExtension.java
> +    public CreateGatewayAccountResponse setupSandboxGatewayAccount(String serviceId, String serviceName) {
I think this should be in `ITestBaseExtension`

2024-07-29 10:50 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/GatewayAccountRequest.java
> +        private @NotBlank String providerAccountType;
Not sure how the `@NotBlank` got in there

2024-07-29 11:06 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/extension/AppWithPostgresAndSqsExtension.java
> +    public CreateGatewayAccountResponse setupSandboxGatewayAccount(String serviceId, String serviceName) {
I'll move this method back into a private method in StripeAccountResourceIT. I feel ITestBaseExtension is a quagmire and I don't want to exacerbate it by adding a new method with a name that's close to other method names in that class thus making that class more bloated.

2024-07-29 13:27 UTC, DomBelcher requested changes

2024-07-29 13:27 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +                    @ApiResponse(responseCode = "409", description = "Not found - Account with serviceId does not exist")
Sorry I should have been clearer with my earlier comment - I think a `409` makes sense if there is already a Stripe account or the current test account isn't a sandbox account. If there's no test account with the specified service ID I'm a bit torn on whether a `404` or `409` makes more sense. The [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409) would suggest that maybe a `409` is correct, given the example of creating `/a/b/c/d/` requiring `/a/b/c/` to exist, but whether this is to be taken as gospel I don't know.

2024-07-29 13:27 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        }
As above re. `400` vs `404` vs `409`

2024-07-29 13:27 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        this.objectMapper = objectMapper;
The object mapper isn't needed if not disabling the account via `PATCH` request

2024-07-29 13:27 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +                    @ApiResponse(responseCode = "200", description = "OK"),
Maybe a `201` is more appropriate if the account is created successfully

2024-07-29 13:27 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        Account testAccount = stripeAccountService.createTestAccount(sandboxGatewayAccount.getServiceName());
This still throws a `RuntimeException` if creating the account fails for any reason - does this need changing? It would result in the API returning a `500`, but I think a `502` would be correct

2024-07-29 13:27 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        gatewayAccountService.disableAccount(sandboxGatewayAccount.getId());
Do we need to give any thought to how we handle potential errors with creating the new gateway account or disabling the old one, or any other potential sad paths? Is it for example possible for two `request-stripe-test-account` requests to come in before the first has time to complete, and two Connect accounts or Gateway accounts to be created as a result? 

As a side note, should we add in some check on `GatewayAccountService.createGatewayAccount` that creating the new account won't duplicate an existing account, e.g. creating a second Stripe test account - I know this already exists as a check for creating a live account, but not for test accounts

2024-07-29 13:27 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +import static uk.gov.service.payments.commons.model.jsonpatch.JsonPatchKeys.FIELD_VALUE;
A lot of these imports can be removed

2024-07-29 13:29 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        Account testAccount = stripeAccountService.createTestAccount(sandboxGatewayAccount.getServiceName());
Ugh I was going to fix the RuntimeException stuff but slipped my mind...

2024-07-29 13:36 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/extension/AppWithPostgresAndSqsExtension.java
> +    public CreateGatewayAccountResponse setupSandboxGatewayAccount(String serviceId, String serviceName) {
I agree on `ITestBaseExtension` being a bit bloated, it's part of why I think we should keep `AppWithPostgesAndSqsExtension` as lean as possible. I think it highlights a potential issue of doing things via the API - if we use the test helpers and the associated builders then we wouldn't need a whole host of `createXwithY` methods, etc.

2024-07-29 15:21 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        Account testAccount = stripeAccountService.createTestAccount(sandboxGatewayAccount.getServiceName());
I'm going to go for a `500` here. The runtime exception wraps a StripeException which could be a number of things - e.g. AuthenticationException, InvalidRequestException, RateLimitException - which encompasses a number of scenarios, some of which could be a client rather than a server fault, so it seems better to return a generic `500` rather than `502`.

2024-07-29 15:30 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +                    @ApiResponse(responseCode = "409", description = "Not found - Account with serviceId does not exist")
It's not that you weren't clear - I changed the wrong line 🤦

2024-07-29 15:50 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +                    @ApiResponse(responseCode = "409", description = "Not found - Account with serviceId does not exist")
Given that throughout our code we return a 404 when a resource doesn't exist, we should keep it that way here.

2024-07-29 15:54 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        }
I think it should be a 409 if the existing test account is not a sandbox one, because 1) it indicates the current state isn't correct and 2) it's nearly the same case for if a Stripe test account already exists.

2024-07-29 15:57 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +                    @ApiResponse(responseCode = "200", description = "OK"),
My opinion is that a 200 should be returned because the resource "Stripe test account" is created on Stripe's server; it's not a resource we can direct the user to. A URL is usually returned with a 201 and this wouldn't be applicable here.

2024-07-29 16:17 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        gatewayAccountService.disableAccount(sandboxGatewayAccount.getId());
> Is it for example possible for two request-stripe-test-account requests to come in before the first has time to complete, and two Connect accounts or Gateway accounts to be created as a result?

Hmm, good thinking. It has occurred to me I haven't associated the Stripe connect account id (beginning with "acct_") with the newly created gateway account in connector. I'll need to add a gateway account credential for this. 

We can't prevent multiple connect accounts from being created in the scenario you're proposing, but once a Stripe gateway account has been associated to a connector gateway account, then we can essentially check for that existence and leave any subsequent Stripe connect accounts as orphans. If you have a look in an example [Stripe test account on toolbox](https://toolbox.payments.service.gov.uk/gateway_accounts/7180) you can see it's mapped to acct_1PVrIHRbaqVLkZV5. As long as that's fixed we don't need to worry about multiple `request-stripe-test-account`s creating multiple Stripe connect accounts.

>As a side note, should we add in some check on GatewayAccountService.createGatewayAccount that creating the new account won't duplicate an existing account, e.g. creating a second Stripe test account - I know this already exists as a check for creating a live account, but not for test accounts

I think this is very unlikely to happen but this is something we should do.

Considering all the above, it feels lots of thinking and is probably best to go in a next PR?

2024-07-30 09:49 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        }
Yeah I think 409 for both makes sense

2024-07-30 12:04 UTC, DomBelcher reviewed
Great work! Just a few very minor points which may not even need addressing

2024-07-30 12:04 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +                    @ApiResponse(responseCode = "404", description = "Not found - Account with serviceId does not exist")
Might as well reorder these so they're in ascending order

2024-07-30 12:04 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/StripeGatewayAccountRequest.java
> +        return Optional.ofNullable(credentials);
I'm not sure this method is even atually used, only `getCredentialsAsMap` seems to be. Maybe it can just be removed?

2024-07-30 12:04 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/StripeGatewayAccountRequest.java
> +        return Optional.ofNullable(credentials).map(StripeCredentials::toMap).orElse(newHashMap());
Not that it matters much but I think we could use `Map.of()` instead of `newHashMap()` as the Map seems to never be mutated, but it may be a virtually pointless change

2024-07-30 12:36 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/StripeGatewayAccountRequest.java
> +        return Optional.ofNullable(credentials);
Strange, IntelliJ didn't flag this up for me.

2024-07-30 12:37 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/StripeGatewayAccountRequest.java
> +        return Optional.ofNullable(credentials).map(StripeCredentials::toMap).orElse(newHashMap());
Yeah it's a pointless change and not worth waiting on a new build for, but I'm going to push a new commit anyway and it's better to use standard JDK classes.

2024-07-30 12:42 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/model/StripeGatewayAccountRequest.java
> +        return Optional.ofNullable(credentials).map(StripeCredentials::toMap).orElse(newHashMap());
> it's better to use standard JDK classes.

Not entirely pointless then, only almost :smile:

2024-07-30 12:52 UTC, DomBelcher approved these changes
Nice work!

2024-07-30 12:54 UTC, merged