PP-12876 Make serviceId mandatory when creating accounts
alphagov/pay-connector pull request #5496
Opened 2024-08-09 16:30 UTC by james-peacock-gds

- Ensure serviceId cannot be null or blank in a GatewayAccountRequest
- Update tests to meet this requirement
- GatewayAccountResourceITBaseExtensions has a lot of helper methods to create gateway accounts, so many that it undermines their usefulness and the class is quite cluttered. I've created a CreateGatewayAccountRequestBuilder to provide flexibility for creating the request payload with different parameters, a method for creating an account using this class, and I've refactored the tests to use that method and deleted the old helper methods.

2024-08-12 10:48 UTC, DomBelcher requested changes
Nice work, just a couple of suggestions

2024-08-12 10:48 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +    public static GatewayAccountResourceITBaseExtensions testBaseExtension = new GatewayAccountResourceITBaseExtensions(app.getLocalPort());
While we're here I wonder if we should rename `GatewayAccountResourceITBaseExtensions` - it's not actually a JUnit extension any more, as the lifecycle methods have all been removed

2024-08-12 10:48 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +    public static AppWithPostgresAndSqsExtension app = new AppWithPostgresAndSqsExtension();
You shouldn't need the app extension, if the constructor just takes the app port you can set up requests with `given().port(...)`

2024-08-12 10:48 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +    protected ValidatableResponse createAGatewayAccount(Map<String, String> createGatewayAccountPayload) {
Very minor but I prefer `createGatewayAccount` to `createAGatewayAccount`

2024-08-12 10:48 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +        Map<String, String> payload = new HashMap<String, String> (Map.ofEntries(
I don't think you need to use `Map.ofEntries`, `Map.of(k1, v1, k2, v2, ...)` should work

2024-08-12 10:48 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +    protected String createAGatewayAccountAndExtractAccountId(Map<String, String> createGatewayAccountPayload) {
Is there ever a need to return create the gateway account and extract something other than the account ID? If so `createAGatewayAccount` could just return the account ID by default

2024-08-12 10:48 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +            return payload;
If you return `Map.copyOf(payload)` you can make the resulting map unmodifiable, which motivates proper use of the builder

2024-08-12 10:48 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +        Map<String, String> payload = new HashMap<String, String> (Map.ofEntries(
Also make the `payload` private to ensure it's only accessible via the builder

2024-08-12 12:20 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +    public static GatewayAccountResourceITBaseExtensions testBaseExtension = new GatewayAccountResourceITBaseExtensions(app.getLocalPort());
done

2024-08-12 12:21 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +    public static AppWithPostgresAndSqsExtension app = new AppWithPostgresAndSqsExtension();
I've given that a try but I think some setup is done in the app extension, because it seems no gateway accounts are created without it (maybe it's the db setup?)

2024-08-12 12:22 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +    protected ValidatableResponse createAGatewayAccount(Map<String, String> createGatewayAccountPayload) {
agree

2024-08-12 12:24 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +    protected String createAGatewayAccountAndExtractAccountId(Map<String, String> createGatewayAccountPayload) {
there used to be.. but not any more. thanks

2024-08-12 13:58 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITBaseExtensions.java
> +    public static AppWithPostgresAndSqsExtension app = new AppWithPostgresAndSqsExtension();
updated as discussed

2024-08-13 09:58 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                String gatewayAccountId = testHelpers.createGatewayAccount(
Does this do anything different than the `createGatewayAccount` call in the `@BeforeEach` block?

2024-08-13 09:58 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceCreateIT.java
> +            //ValidatableResponse response = GatewayAccountResourceITBaseExtensions.createAGatewayAccountFor(app.getLocalPort(), "sandbox", "my test service", "analytics");
Delete this commented out line

2024-08-13 09:58 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITHelpers.java
> +    protected String createGatewayAccount(Map<String, String> createGatewayAccountPayload) {
It probably doesn't make much difference but I don't think this needs to be `protected`, `public` should be fine

2024-08-13 10:10 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceCreateIT.java
> +            //ValidatableResponse response = GatewayAccountResourceITBaseExtensions.createAGatewayAccountFor(app.getLocalPort(), "sandbox", "my test service", "analytics");
oops thanks

2024-08-13 10:10 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                String gatewayAccountId = testHelpers.createGatewayAccount(
good point, moving the beforeEach up a level

2024-08-13 10:14 UTC, james-peacock-gds commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITHelpers.java
> +    protected String createGatewayAccount(Map<String, String> createGatewayAccountPayload) {
ok done

2024-08-13 10:34 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/it/resources/AgreementsApiResourceIT.java
> +                String gatewayAccountId = testHelpers.createGatewayAccount(
Ah the diff hid that it was in a separate block, I think it works where it is now though

2024-08-13 10:35 UTC, DomBelcher approved these changes
Nice work

2024-08-13 10:38 UTC, merged