PP-13091 auto complete stripe setup tasks for test accounts
alphagov/pay-connector pull request #5520
Opened 2024-08-22 16:13 UTC by nlsteers

## WHAT YOU DID

- when requesting a stripe test account, ensure that all set up tasks are completed as part of account creation

2024-08-23 11:11 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        stripeAccountSetupService.completeTestAccountSetup(testStripeAccount);
Is it possible to refactor `gatewayAccountService.createGatewayAccount` to return a `GatewayAccountEntity` and pass directly that to `stripeAccountSetupService.completeTestAccountSetup` without having to re-fetch it from the database, and wrap the whole method in a `@Transactional` annotation? I'm not sure if it would mess with the persistence context though

2024-08-23 11:11 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/GatewayAccountService.java
> +                    gatewayAccountEntity.setDisabledReason(disabledReason);
Nice addition 👍

2024-08-23 11:11 UTC, DomBelcher commented on src/test/java/uk/gov/pay/connector/gatewayaccount/service/StripeAccountSetupServiceTest.java
> +    void completeTestAccountSetupShouldCompleteAllTasksForStripeTestAccounts() {
Could wrap these in a `@Nested` block and remove the `completeTestAccountSetup` prefix from each test name

2024-08-23 11:16 UTC, nlsteers commented on src/test/java/uk/gov/pay/connector/gatewayaccount/service/StripeAccountSetupServiceTest.java
> +    void completeTestAccountSetupShouldCompleteAllTasksForStripeTestAccounts() {
👍🏻

2024-08-27 14:02 UTC, nlsteers commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        stripeAccountSetupService.completeTestAccountSetup(testStripeAccount);
https://github.com/alphagov/pay-connector/pull/5520/commits/0350c2990d8b6545540778369d5c12f8a6a0755b

2024-08-27 14:21 UTC, DomBelcher requested changes

2024-08-27 14:21 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/service/GatewayAccountService.java
> +import static uk.gov.pay.connector.gatewayaccount.resource.GatewayAccountRequestValidator.*;
Needs changing back to individual imports

2024-08-27 14:21 UTC, DomBelcher commented on src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountResource.java
> +        GatewayAccountEntity testStripeAccount = gatewayAccountService.createGatewayAccount(stripeGatewayAccountRequest);
I like the change from `stripeTestAccount` -> `stripeTestConnectAccount` - May as well name this `testStripeGatewayAccount` to completely avoid any ambiguity about what kind of account they each are

2024-08-27 14:33 UTC, DomBelcher approved these changes

2024-08-27 15:02 UTC, merged