Send corporate exemption with Worldpay authorisation request for corporate cards if enabled
alphagov/pay-connector pull request #5535
Opened 2024-09-04 11:27 UTC by hjvoid

## WHAT YOU DID
Ensure that if corporate exemptions are enabled and a corporate card is used, then the charges tabel of the connector database is updatd to the value of optimised and the authorisation request to Worldpay includs `<exemption type="OP" placement="OPTIMISED"/>` element inside the order element

## How to test

- How should it be reviewed? 
- What feedback do you need? 
    - Unsure if the `WorldpayAuthoriseOrderTemplate.xml` if statement lines I have added can be better written i.e. if/else?
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

2024-09-23 15:10 UTC, marcotranchino commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +            <#if (corporateExemptionEnabled && !exemptionEngineEnabled) || (corporateExemptionEnabled && exemptionEngineEnabled)>
This expression 

```javascript

<#if (corporateExemptionEnabled && !exemptionEngineEnabled) || (corporateExemptionEnabled && exemptionEngineEnabled)>
```

can be simplified with:

```javascript
<#if corporateExemptionEnabled>
```

Unless the business logic should be doing something different?

2024-09-24 09:14 UTC, hjvoid commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +            <#if (corporateExemptionEnabled && !exemptionEngineEnabled) || (corporateExemptionEnabled && exemptionEngineEnabled)>
Good spot!

2024-09-24 09:48 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilder.java
> +        logger.info("Corporate Exemption is: " + corporateExemptionEnabled + " for " + worldpayTemplateData.sessionId);
Hugo, 
Sandor and I are wondering if you meant this log to remain, if we need it, 
or whether it was needed just for testing. What do you think?

2024-09-24 09:54 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        response = exemptionEngineEnabled
The test should be with **(exemptionEngineEnabled || corporateExemptionsEnabled)** instead of just **exemptionEngineEnabled**.

2024-09-24 09:59 UTC, hjvoid commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilder.java
> +        logger.info("Corporate Exemption is: " + corporateExemptionEnabled + " for " + worldpayTemplateData.sessionId);
Yeah it's part of the AC's:

> And the line Requesting CORPORATE exemption - charge_external_id=abcdefghijklmnopqrstuvwxyz is logged

2024-09-24 10:00 UTC, marcotranchino commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +            <#elseif !authCardDetails.corporateCard && corporateExemptionEnabled && exemptionEngineEnabled>
We can remove the following from this elseif: **&& corporateExemptionEnabled**
Because we don't care about it because the card is not corporate.

2024-09-24 10:03 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +    @ParameterizedTest
We think that this is great. No need to separate the tests! 🙌🏼

2024-09-24 10:08 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilderTest.java
> +        );
Hugo, 
We are thinking that it would be beneficial to have another test to check what happens when it's 

arguments(false, false, NEED_TO_FIGURE_OUT_WHAT_GOES_HERE, true).

2024-09-24 10:12 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    void should_send_worldpay_authorisation_without_exemption_if_exemption_engine_false_and_corporate_card_is_used() throws Exception {
This does not make it clear whether corporate exemption is enabled.
Alex B has confirmed that corporate exemption could be enabled and working even if the exemption engine is disabled.

2024-09-24 10:18 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +                arguments(true, OPTIMISED, false)
This is good! 👍🏼

2024-09-24 10:21 UTC, marcotranchino requested changes
Great work, @hjvoid ! 🙌 
However we believe that we should consider the case when the corporate exemption is enabled but the exemption engine is disabled.
Alex B has confirmed that, in that case, corporate exemptions should still work.

2024-09-24 10:31 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilder.java
> +        logger.info("Corporate Exemption is: " + corporateExemptionEnabled + " for " + worldpayTemplateData.sessionId);
Ah I see, thanks for clarifying! :)

2024-09-24 14:29 UTC, hjvoid commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    void should_send_worldpay_authorisation_without_exemption_if_exemption_engine_false_and_corporate_card_is_used() throws Exception {
This test is being removed as it describes incorrect logic. I have added a new arguments to the `exemptionValues` function in the soon to be renamed `should_send_worldpay_authorisation_with_exemption_if_exemption_engine_or_corporate_exemptions_enabled` test instead.

2024-09-24 14:57 UTC, hjvoid commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilderTest.java
> +        );
I've added the those values to the test above (see line 525) and used a previously used template `WORLDPAY_VALID_AUTHORISE_WORLDPAY_3DS_REQUEST_MIN_ADDRESS` which tallies with the template comparison we need. Alternatively I could make a new template and call it something more descriptive, however, we would end up with 3 templates which are identical.

2024-09-25 13:24 UTC, marcotranchino approved these changes
Great work, @hjvoid ! 🙌🏼
All the points raised in the review with @SandorArpa have been addressed. 👍🏼

2024-09-26 08:17 UTC, merged