PP-11559 after async refund transfer send events to ledger
alphagov/pay-connector pull request #5549
Opened 2024-09-17 01:10 UTC by AbdirizakIdris

## Background
- A Stripe refund succeeded initially but later failed asynchronously. We do not handle this failure case automatically
- Funds for a refund are taken from our Stripe platform account as soon as the request to make the refund succeeds. We then make a transfer from the service’s connect account to our platform account. If the refund later fails, Stripe returns the money to our platform account.
- To correct this, we need to make a new transfer from our platform account to the connect account.
- We then add a new payment into Pay with required details

## WHAT YOU DID
- Added events for `RefundFailureFundsSentToConnectAccount`, `RefundStatusCorrectedToErrorByAdmin` and `PaymentStatusCorrectedToSuccessByAdmin` 
- Called these events in `RefundReversalService` to be posted in Ledger

2024-09-24 15:04 UTC, alexbishop1 requested changes
This is along the right lines. There’s a few bits where I think we’re extending from the wrong class so fix those first because they’ll have the biggest ripple effects.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/refund/PaymentStatusCorrectedToSuccessByAdminEventDetails.java
> +    private final Long netAmount;
It does not look like any of these `Long`s will ever be be null, so I think they can be primitive `long`s (this applies to the other `Long`s in the rest of the class).

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/refund/PaymentStatusCorrectedToSuccessByAdminEventDetails.java
> +    private final ZonedDateTime capturedDate;
It pains me that this is a `ZonedDateTime` and not an `Instant` but every other `EventDetails` class is the same so it’s fine.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/refund/PaymentStatusCorrectedToSuccessByAdminEventDetails.java
> +    private final String transactionId;
I don’t think the `transactionId` is required: it’s covered by the `resourceExternalId` in the associated event.

It does look like `reference` has been missed though.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/refund/RefundFailureFundsSentToConnectAccountEventDetails.java
> +    private final Long amount;
Again, the `Long`s in this class can be `long`s.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/refund/RefundFailureFundsSentToConnectAccountEventDetails.java
> +    private final String transactionId;
Like `PaymentStatusCorrectedToSuccessByAdminEventDetails`, I think this can go.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/refund/RefundStatusCorrectedToErrorByAdminEventDetails.java
> +    String transactionId;
I think these `parentTransactionId`, `transactionType` and `transactionId` are unnecessary because they will be inferred from the `resourceExternalId` in the associated event.

I think an `adminGithubId` needs to be added though.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/refund/PaymentStatusCorrectedToSuccessByAdmin.java
> +public class PaymentStatusCorrectedToSuccessByAdmin extends RefundEvent {
Although this even will be sent in the context of managing a refund, it’s actually a payment event so it should extend `PaymentEvent`.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/refund/PaymentStatusCorrectedToSuccessByAdmin.java
> +    public static PaymentStatusCorrectedToSuccessByAdmin from(Refund refund, Charge charge, String randomIdGenerator, ZonedDateTime timestamp) {
The `randomIdGenerator` is actually the random ID generated by the generator but by this point it’s the ID of the new payment that represents the transfer. We conventionally refer to a payment ID (or refund ID) in the events code as the `resourceExternalId`.

And please make `timestamp` be an `Instant` rather than a `ZonedDateTime`.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/refund/PaymentStatusCorrectedToSuccessByAdmin.java
> +                        "AdminGithubId (nameGds)",
This probably wants to be the actual GitHub user, which I think we get from toolbox when it calls the endpoint.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/refund/RefundFailureFundsSentToConnectAccount.java
> +public class RefundFailureFundsSentToConnectAccount extends RefundEvent {
Again, this is actually a `PaymentEvent`.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/refund/RefundStatusCorrectedToErrorByAdmin.java
> +                ZonedDateTime.now().toInstant()
`Instant.now()` will do what you want.

2024-09-24 15:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/refund/service/RefundReversalService.java
> +        RandomIdGenerator randomIdGenerator = new RandomIdGenerator();
The `RandomIdGenerator` should be injected into the constructor of this class.

2024-09-24 15:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/RefundReversalServiceTest.java
> +    void shouldCreateCorrectEventsAfterRefundReversalToPostToLedger() throws StripeException {
There’s an argument to be made that this should part of a complete happy path test but let’s ponder that later.

2024-09-24 15:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/RefundReversalServiceTest.java
> +        assertTrue(postedEvents.get(2) instanceof RefundStatusCorrectedToErrorByAdmin);
Could maybe assert on some of the important parts of these events (the IDs, messages etc.) to make sure we’re passing in the right data.

2024-10-02 12:13 UTC, AbdirizakIdris commented on src/main/java/uk/gov/pay/connector/events/model/refund/PaymentStatusCorrectedToSuccessByAdmin.java
> +                        "AdminGithubId (nameGds)",
Not sure how to retrieve GitHub User from toolbox

2024-10-08 12:14 UTC, alexbishop1 requested changes
I think this is almost there!

2024-10-08 12:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/refund/RefundFailureFundsSentToConnectAccountEventDetails.java
> +    private final Long amount;
Looks like these are still `Long` objects rather than `long` primitives.

2024-10-08 12:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/refund/PaymentStatusCorrectedToSuccessByAdmin.java
> +public class PaymentStatusCorrectedToSuccessByAdmin extends RefundEvent {
This still extends `RefundEvent`, not `PaymentEvent`.

2024-10-08 12:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/refund/PaymentStatusCorrectedToSuccessByAdmin.java
> +                charge.getExternalId(),
Careful here: one of these should be the refund ID and one should be the charge ID.

2024-10-08 12:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/refund/resource/RefundReversalResource.java
> +        refundReversalService.reverseFailedRefund(gatewayAccount, refund, charge, githubAndZendeskCredential);
I think might want to pass the GitHub user and the Zendesk ticket ID as separate parameters — they’re only initially together because of how they get sent to the endpoint so we can split them after that.

2024-10-08 12:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/refund/PaymentStatusCorrectedToSuccessByAdmin.java
> +    public static PaymentStatusCorrectedToSuccessByAdmin from(Refund refund, Charge charge, ZonedDateTime timestamp, GithubAndZendeskCredential githubId) {
This should take an `Instant`, not a `ZonedDateTime`.

2024-10-09 15:25 UTC, alexbishop1 approved these changes

2024-10-09 15:39 UTC, merged