PP-13051 corporate exemption with Worldpay authorisation request
alphagov/pay-connector pull request #5582
Opened 2024-10-08 10:47 UTC by hjvoid

## WHAT YOU DID
Ensure that if corporate exemptions are enabled and a corporate card is used, then the charges tabel of the connector database is updatd to the value of optimised and the authorisation request to Worldpay includs <exemption type="OP" placement="OPTIMISED"/> element inside the order element

## How to test

- How should it be reviewed?

    - Check the code and test manually if possible.

* What feedback do you need

    - I've made the test on Line 223 of src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java a parameterised test for readability but realise this may be better as two separate tests?

    - I have read the ticket as 3D secure enabled meaning the requires_3ds column of the gateway_accounts table.
    - I suspect there's a better way of structuring my changes in [WorldpayAuthoriseOrderTemplate.xml](https://github.com/alphagov/pay-connector/pull/5535/files#diff-a18066368d3d8d932d82af7fd4458986a47b0d41cf495b7432c8497767664976)
    - I'm not sure if the naming of the tests in [WorldpayPaymentProviderTest.java](https://github.com/alphagov/pay-connector/pull/5535/files#diff-d64f06829c2303c7615e41d361e4db01df11be2bc86524770d875079b99d79fd) could be made more explicit.
    - Added a logger within `WorldpayPaymentProvider.java` for whether a corporate card has been used as per Krishna's suggestion.

* Updates since previous merge
   -  Clean up src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml . Sadly we need to keep <#if corporateExemptionEnabled || exemptionEngineEnabled> on line 83 otherwise the next if statement doesn't kick in.
   -  Added a logger that registers if a corporate card has been used and includes the `external_id`.
   -  `WorldpayOrderBuilder` cannot be tested directly as it’s an interface and technically has no logic to test. I've added two more tests to `WorldpayAuthoriseTestHandlerTest.java` instead to include checks for the `isCorporateExemptionEnabled` boolean value instead.

* Steps to test

    - Checkout this branch as well as pp-13038-toggle-corporate-exemptions-button pay-toolbox branch (this may not be needed if this branch has been merged by the time of writing).
    - In pay-connector you will need to change the test Worldpay URLs and test threeDsFlexDdcUrls in config.yaml to the worldpay test urls. You can find theses in pay-magic-urls in pay-infra.
    - Run connector from local branch:
`pay local launch --cluster endtoend --local connector`
    - Create a user:
`pay local user`
    - Run toolbox locally and go to the gateway account for the service just created.
    - Go to ‘Manage PSP’ and switch to Worldpay.
    - This will create a worldpay credentials record (in gateway_account_credentials) but the status needs to be changed
to ACTIVE so you can use APIs or a SQL update. Don't forget to add an `active_start_date`. Alternatively you can run the following query `update gateway_account_credentials set state = 'ACTIVE', active_start_date = now()  where id = 2;`.
    - Remember to set `requires_3ds` to true in the DB on the gateway account.
    - Now set the `worldpay_3ds_flex_credentials` using the following query insert into `worldpay_3ds_flex_credentials(id, gateway_account_id, issuer, organisational_unit_id, jwt_mac_key, version, exemption_engine, corporate_exemptions) values (1,1, 'issuer', 'organisational_unit_id', 'jwt_mac_key', 1,  false, false); `. The correct values can be found on the Worldpay developer docs.
    - Now if you `select * from worldpay_3ds_flex_credentials` you can toggle the exemption_engine and corporate_exemption properties as necessary.
    - Now set your account credentials using the selfservice UI by going first to settings and then to "Your PSP - Worldpay" menu. You will need to obtain these from someone with access to pay-low-pass.
    - Now create a new payment link in order to make some test transactions.
    - You can check if CORPORATE or OPTIMISED has been set if you `select * from charges`.
    - You can use the mock card numbers in the card numbers tech docs to test corporate/non-corporate cards https://docs.payments.service.gov.uk/testing_govuk_pay/#mock-card-numbers
    - You should also check that each transaction has a `REQUESTED_3DS_EXEMPTION` event that is either set to `OPTIMISED` or `CORPORATE` dependant upon how you set `exemption_engine`, `corporate_exemptions` and whether you use a corporate card or not.

2024-10-18 10:08 UTC, SandorArpa submitted a review, later dismissed

2024-10-18 10:08 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        response = exemptionEngineEnabled
How about corporate exemption? Shouldn't this variable be corporateExemptionsOrExemptionEngineEnabled?

2024-10-18 12:41 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        response = exemptionEngineEnabled
I have made the change. I need to look into failing tests now.

2024-10-21 13:23 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        response = exemptionEngineEnabled
The changes discussed in this conversation have now been removed after an additional chat in video call between me, @SandorArpa and @alexbishop1

2024-10-22 11:57 UTC, alexbishop1 requested changes

2024-10-22 11:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderBuilder.java
> +                        .orElse(false);
I’m not sure this logic is quite right. If the gateway account has corporate exemptions enabled (the right side of the expression) then that should be enough. The DDC result only comes into play when we think the request might result in 3DS being required, which it won’t be if we’ve requested an exemption (we’ll get a soft decline instead).

2024-10-22 11:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilder.java
> +        logger.info("Corporate Exemption is: " + corporateExemptionEnabled + " for " + worldpayTemplateData.sessionId);
I assume `sessionId` is the GOV.UK Pay payment ID? It’s not great to rely on that but I see we’re doing it elsewhere in this class as well.

2024-10-22 11:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        Exemption3dsType exemptionType = corporateExemptionsEnabled && cardIsCorporate ? CORPORATE : OPTIMISED;
Although this will work, it feels a bit not quite right because it will set the `exemptionType` to `OPTIMISED` if no exemption is being requested.

I think we might want to do something like this instead (this code basically replaces the entire first part of the method):

```java
boolean corporateExemptionsEnabledAndCorporateCardUsed = isCorporateExemptionsEnabled(request) && isCorporateCard(request, charge);
boolean exemptionEngineEnabled = isExemptionEngineEnabled(request);

if (corporateExemptionsEnabledAndCorporateCardUsed) {
    charge = updateChargeWithRequested3dsExemption(charge, Exemption3dsType.CORPORATE);
} else if (exemptionEngineEnabled) {
    charge = updateChargeWithRequested3dsExemption(charge, Exemption3dsType.OPTIMISED);
}

GatewayResponse<WorldpayOrderStatusResponse> response = …
```

A further advantage of this is we now have a `corporateExemptionsEnabledAndCorporateCardUsed` boolean we could potentially pass down through the `WorldpayOrderRequestBuilder` into the template, meaning we would not have to repeat logic and reducing the chances of our code that records the exemption type differing from the code that actually sends the exemption.

2024-10-22 11:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        LOGGER.info("Card is corporate card: {} for charge_external_id={}", authCardDetails.isCorporateCard(), charge.getExternalId());
Not sure the logging should happen here; perhaps after this method is called.

2024-10-22 11:57 UTC, alexbishop1 commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +        </#if>
Seems like this could just be:

```
<#if corporateExemptionEnabled && authCardDetails.corporateCard>
<exemption type="CP" placement="AUTHORISATION"/>
<#elseif exemptionEngineEnabled>
<exemption type="OP" placement="OPTIMISED"/>
</#if>
```

(The first `#if` could be `<#if corporateExemptionsEnabledAndCorporateCardUsed>` if my suggestion above is implemented.)

2024-10-22 11:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +            boolean corporateCard
Can these be named to make it clearer with are inputs and which are outputs? So `corporateExemption` would be `corporateExemptionEnabled` and `exemptionType` would be `expectedExemptionType` etc. Maybe also reorder them so the inputs are first followed by the outputs.

2024-10-22 11:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +    void should_not_set_corporate_exemption_unless_gateway_account_has_3dsFlex_credentials_and_card_details_has_3ds_flex_Ddc_result(
As discussed above, the logic of requiring a DDC result does not seem quite right.

2024-10-22 11:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +    }
Since these are only used for one test each, I wonder if [`@CsvSource`](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-CsvSource) may be more readable, due to keeping the arguments close to the tests.

2024-10-22 11:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilderTest.java
> +    void shouldGenerateValidAuthoriseOrderRequestAndIncludeCorrectExemptionResponse(Boolean corporateExemptions, Boolean exemptionEngine, String testTemplate, Boolean corporateCard) throws Exception
Again, I think this could be rejigged to make the inputs and outputs clearer.

2024-10-22 11:57 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    void should_send_corporate_exemption_with_worldpay_authorisation_if_corporate_exemptions_disabled_and_corporate_card_is_used() throws Exception {
This seems wrong: we should never be requesting a corporate exemption if corporate exemptions are disabled!

2024-10-22 12:16 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        LOGGER.info("Card is corporate card: {} for charge_external_id={}", authCardDetails.isCorporateCard(), charge.getExternalId());
Do we want to always log it or if corporate card only? Or if corporate engine enabled and corporate card?

2024-10-22 12:17 UTC, SandorArpa commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +        </#if>
I think we should implement it in PP-13276. That's where we are simplifying things and planned to pass something like `corporateExemptionsEnabledAndCorporateCardUsed`

2024-10-22 12:28 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilderTest.java
> +    void shouldGenerateValidAuthoriseOrderRequestAndIncludeCorrectExemptionResponse(Boolean corporateExemptions, Boolean exemptionEngine, String testTemplate, Boolean corporateCard) throws Exception
It shall be replaced by CsvSource

2024-10-23 14:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        LOGGER.info("Card is corporate card: {} for charge_external_id={}", authCardDetails.isCorporateCard(), charge.getExternalId());
Probably the latter but the former could also be useful.

2024-10-23 14:30 UTC, alexbishop1 requested changes
Getting there…

2024-10-23 14:30 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        }
I think outputting `corporate exemption is enabled false` might be a little unclear — can we reword it?

2024-10-23 14:30 UTC, alexbishop1 commented on src/main/resources/templates/worldpay/WorldpayAuthoriseOrderTemplate.xml
> +        </#if>
Actually, I think we should change this now. Currently it looks like if corporate exemptions are enabled and the Exemption Engine is not enabled but it is not a corporate card it will still request an Exemption Engine exemption!

2024-10-23 14:30 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +            """
You can actually do this:

```java
@CsvSource(textBlock = """
        true, true, CP, AUTHORISATION,
        …
        """)
```

Not that it really matters.

You can also add `useHeadersInDisplayName = true` and then add a header row, which could be useful to make it clearer what the boolean values mean (the headers also appear in the test output when it lists the permutations).

2024-10-23 14:30 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +            boolean corporateCard,
Calling this `corporateCardNumberEntered` might be a tad clearer.

2024-10-23 14:30 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayAuthoriseHandlerTest.java
> +            String exemptionPlacement) throws Exception {
This could be `expectedExemptionPlacement`.

2024-10-23 14:30 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayOrderRequestBuilderTest.java
> +    void shouldGenerateValidAuthoriseOrderRequestAndIncludeCorrectExemptionResponse(Boolean corporateExemptions, Boolean exemptionEngine, String testTemplate, Boolean corporateCard) throws Exception
It does not appear to have been replaced by `CsvSource`.

2024-10-23 14:30 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    )
Since there’s only two permutations, I think this might be best done as two separate tests.

2024-10-25 09:39 UTC, alexbishop1 requested changes
Looking good. Just a couple of final things.

2024-10-25 09:39 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyLoggingTypeOf3dsExemption(CORPORATE, chargeEntity.getExternalId());
Is there anything we can do here to check it’s not sending the Exemption Engine exemption?

2024-10-25 09:39 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    void should_not_send_corporate_exemption_with_worldpay_authorisation_if_corporate_exemption_is_not_enabled_and_exemption_engine_enabled_and_corporate_card_used() throws Exception {
Although `should_not_send_corporate_exemption` is true, it’s more objectively `should_send_optimised_exemption`.

2024-10-25 09:39 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/TestTemplateResourceLoader.java
> +    public static final String WORLDPAY_VALID_AUTHORISE_3DS_REQUEST_EXEMPTION_AUTHORISATION = WORLDPAY_BASE_NAME + "/valid-authorise-worldpay-3ds-request-exemption-authorisation.xml";
Both this constant and the filename should have ‘corporate’ in there somewhere.

2024-10-25 10:23 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyLoggingTypeOf3dsExemption(CORPORATE, chargeEntity.getExternalId());
Not really, we cannot stub WorldpayOrderBuilder where the use is determined.

2024-10-25 10:28 UTC, alexbishop1 approved these changes

2024-10-25 10:37 UTC, merged