PP-13052 handle Worldpay authorise corporate exemption
alphagov/pay-connector pull request #5616
Opened 2024-10-28 15:57 UTC by SandorArpa

## WHAT YOU DID

Handle Worldpay authorisation response for requests with corporate exemptions

2024-10-29 12:54 UTC, alexbishop1 requested changes, later dismissed
Looks fine (within the context that the existing code is a little tricky to follow) but a couple of things warrant a further look.

2024-10-29 12:54 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(worldpayAuthoriseHandler, times(1)).authorise(cardAuthRequest, DO_NOT_SEND_EXEMPTION_ENGINE_REQUEST);
Probably want a ` verifyNoMoreInteractions(worldpayAuthoriseHandler)` to make sure it actually doesn’t try to retry.

2024-10-29 12:54 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyEventEmitted(chargeEntity, EXEMPTION_REJECTED, 2);
I’m don’t understand why these happen twice.

2024-10-29 12:54 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (response.getBaseResponse().map(WorldpayOrderStatusResponse::isSoftDecline).orElse(false) && !corporateExemptionsEnabledAndCorporateCardUsed) {
I wonder if this check should be encapsulated in a `authorisationWithExemptionRequestSoftDeclinedButRetryableWithoutExemption(…)` method.

2024-10-31 11:47 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +        if (response.getBaseResponse().map(WorldpayOrderStatusResponse::isSoftDecline).orElse(false) && !corporateExemptionsEnabledAndCorporateCardUsed) {
Method extracted.

2024-10-31 11:58 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(worldpayAuthoriseHandler, times(1)).authorise(cardAuthRequest, DO_NOT_SEND_EXEMPTION_ENGINE_REQUEST);
Added.

2024-10-31 15:03 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyEventEmitted(chargeEntity, EXEMPTION_REJECTED, 2);
The two emissions are coming from:

- updateChargeWithRequested3dsExemption - When we first request the exemption
- updateChargeWithExemption3ds - When we get the response


```java
    @Transactional
    public ChargeEntity updateChargeWithRequested3dsExemption(ChargeEntity chargeEntity, Exemption3dsType exemption3dsType) {
        chargeEntity.setExemption3dsRequested(exemption3dsType);
        LOGGER.info("Requesting {} exemption - charge_external_id={}", exemption3dsType, chargeEntity.getExternalId());
        eventService.emitAndRecordEvent(Requested3dsExemption.from(chargeEntity, Instant.now()));

        return chargeDao.merge(chargeEntity);
    }
```

```java
    @Transactional
    public void updateChargeWithExemption3ds(Exemption3ds exemption3ds, ChargeEntity charge, String reason) {
        charge.setExemption3ds(exemption3ds);
        if (reason == null) {
            LOGGER.info("Updated exemption_3ds of charge to {} - charge_external_id={}", exemption3ds, charge.getExternalId());
        } else {
            LOGGER.info("Updated exemption_3ds of charge to {} (reason {}) - charge_external_id={}", exemption3ds.name(), reason, charge.getExternalId());
        }
        chargeDao.merge(charge);
        eventService.emitAndRecordEvent(Gateway3dsExemptionResultObtained.from(charge, Instant.now()));
    }
```

Shall I replace the verifyEventEmitted with two assertions checking that the 2 events are instanceof Gateway3dsExemptionResultObtained and Requested3dsExemption respectively?

2024-10-31 15:09 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyEventEmitted(chargeEntity, EXEMPTION_REJECTED, 2);
I’m still a bit confused but if they’re different events then yes.

2024-10-31 15:10 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyEventEmitted(chargeEntity, EXEMPTION_REJECTED, 2);
OK !

2024-10-31 15:26 UTC, marcotranchino commented
> Looks fine (within the context that the existing code is a little tricky to follow) but a couple of things warrant a further look.

Thanks, @alexbishop1 . This should be ready for re-review 😸

2024-11-05 15:41 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyEventEmitted(chargeEntity, EXEMPTION_REJECTED, 2);
This is now resolved as we are testing for the specific event we are expecting to see.

2024-11-05 15:50 UTC, alexbishop1 requested changes
Looking a lot clearer!

2024-11-05 15:50 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(eventService, times(timesEventEmitterCalled)).emitAndRecordEvent(eventCaptor.capture());
I think this can be updated like the other one.

2024-11-05 16:18 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(eventService, times(timesEventEmitterCalled)).emitAndRecordEvent(eventCaptor.capture());
Amended, thanks! :)

2024-11-05 16:26 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyChargeUpdatedWith(EXEMPTION_REJECTED, 2);
Why does this still happen twice?

2024-11-05 16:56 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyChargeUpdatedWith(EXEMPTION_REJECTED, 2);
I will remove it.

2024-11-05 17:03 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verifyChargeUpdatedWith(EXEMPTION_REJECTED, 2);
The two events emitted are Gateway3dsExemptionResultObtained and Requested3dsExemption. 
The changes we made allow us to check specifically for the Gateway3dsExemptionResultObtained event, so we don't need the confusing assertion anymore.

2024-11-05 17:29 UTC, alexbishop1 requested changes
I think we’re almost there!

2024-11-05 17:29 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    private void verifyEventEmitted(ChargeEntity chargeEntity, Exemption3ds exemption3ds, int timesEventEmitterCalled)  {
We can lose the `timesEventEmitterCalled` parameter now since it’s always 1.

In fact, I think this method can go altogether and we can just inline the verifications.

2024-11-06 09:23 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    private void verifyEventEmitted(ChargeEntity chargeEntity, Exemption3ds exemption3ds, int timesEventEmitterCalled)  {
Suggestion implemented, thanks!

2024-11-06 14:34 UTC, alexbishop1 requested changes
I think there’s a bit more that could be done to make it clearer.

2024-11-06 14:34 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    private void verifyChargeUpdatedWith(Exemption3ds exemption3ds, int chargeUpdated) {
The second argument is always 1 now so it can go.

2024-11-06 14:34 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        InstantSource instantSource = InstantSource.fixed(Instant.parse(INSTANT_EXPECTED));
We can make this `InstantSource` into a field so we have one for the whole test suite.

2024-11-06 14:34 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(worldpayAuthoriseHandler, times(1)).authorise(cardAuthRequest, SEND_CORPORATE_EXEMPTION_REQUEST);
`times(1)` is the default so does not need to be explicitly specified.

2024-11-06 14:34 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(eventService, times(1)).emitAndRecordEvent(expectedExemptionResultEvent);
This unfortunately hides the important part of the event, which is the `Exemption3ds` value of `EXEMPTION_REJECTED`.

We could do something like this instead:

```java
var exemptionRejectedEvent = new Gateway3dsExemptionResultObtained(chargeEntity.getServiceId(), chargeEntity.getGatewayAccount().isLive(), chargeEntity.getGatewayAccount().getId(), chargeEntity.getExternalId(), new Gateway3dsExemptionResultObtainedEventDetails(EXEMPTION_REJECTED.toString()), INSTANT_EXPECTED);
verify(eventService).emitAndRecordEvent(exemptionRejectedEvent);
```

2024-11-06 14:34 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        verify(eventService, times(1)).emitAndRecordEvent(expectedExemptionResultEvent);
This whole method can go now and be replaced with the two lines I mentioned above wherever it’s called

```java
var exemptionSomethingEvent = new Gateway3dsExemptionResultObtained(chargeEntity.getServiceId(), chargeEntity.getGatewayAccount().isLive(), chargeEntity.getGatewayAccount().getId(), chargeEntity.getExternalId(), new Gateway3dsExemptionResultObtainedEventDetails(DESIRED_VALUE.toString()), INSTANT_EXPECTED);
verify(eventService).emitAndRecordEvent(exemptionSomethingEvent);

2024-11-06 14:53 UTC, marcotranchino commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +    private void verifyChargeUpdatedWith(Exemption3ds exemption3ds, int chargeUpdated) {
Amended, thanks.

2024-11-06 16:52 UTC, marcotranchino commented
Much more readable! 💥 :) 
Ready for re-re-...-review!

2024-11-06 16:55 UTC, alexbishop1 approved these changes

2024-11-07 09:19 UTC, merged