PP-13240 set requires_3ds to false
alphagov/pay-connector pull request #5629
Opened 2024-11-07 11:37 UTC by SandorArpa

## WHAT YOU DID

requires_3ds set to false and GATEWAY_DOES_NOT_REQUIRE_3DS_AUTHORISATION event emitted when transitioning to AUTHORISATION SUCCESS or AUTHORISATION REJECTED if if requires_3ds is not already true

2024-11-08 17:40 UTC, alexbishop1 requested changes
Logic looks fine but I think there‘s some improvements we could make.

2024-11-08 17:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        });
```java
chargeDao.findByExternalId(chargeExternalId).ifPresent(chargeEntity -> {
    chargeEntity.setRequires3ds(requires3ds);
    chargeDao.merge(chargeEntity);
});
```

2024-11-08 17:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/charge/GatewayDoesNotRequires3dsAuthorisationEventDetails.java
> +public class GatewayDoesNotRequires3dsAuthorisationEventDetails extends EventDetails {
“Requires” should be “Require”.

2024-11-08 17:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/charge/GatewayDoesNotRequires3dsAuthorisationEventDetails.java
> +    }
You know, I’d just have a public no-args constructor and be done with it.

2024-11-08 17:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/model/charge/GatewayDoesNotRequires3dsAuthorisation.java
> +public class GatewayDoesNotRequires3dsAuthorisation extends PaymentEvent {
“Requires” should be “Require”.

2024-11-08 17:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseService.java
> +            if (updatedCharge.getRequires3ds() == null || !updatedCharge.getRequires3ds()) {
Perhaps I’m overthinking this but I wonder if some cannily-named private methods might make the semantics clearer:

```java
private boolean canDefinitelyDetermineIf3dsWasRequired(ChargeStatus status) {
    return status == AUTHORISATION_SUCCESS || status == AUTHORISATION_REJECTED;
}

private boolean alreadyRequired3ds(ChargeEntity chargeEntity) {
    return Boolean.TRUE.equals(chargeEntity.getRequires3ds());
}

// …

if (canDefinitelyDetermineIf3dsWasRequired(newStatus) && !alreadyRequired3ds(chargeEntity)) {
    // …
}
```

2024-11-08 17:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseService.java
> +                chargeService.updateRequires3ds(updatedCharge.getExternalId(), false);
This feels odd because we’re essentially setting it twice.

Can we make `updateRequires3ds(…)` return the updated `ChargeEntity` and then use that for the rest of the method?

2024-11-08 17:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseService.java
> +                eventService.emitAndRecordEvent(GatewayDoesNotRequires3dsAuthorisation.from(updatedCharge, Instant.now()));
If we inject an `InstantSource` (just add a parameter to the constructor) then we can use `instantSource.instant()` here, which will allow us to control the time in tests.

2024-11-08 17:40 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +    private EventService mockedEventServiceForCardAuthService;
It seems a bit odd to have separate mock `EventService`s when in reality they would be the same one. I assume this was done to make it easier to assert on what events are and are not being sent.

I see a lot of `verifyNoInteractions(mockedEventServiceForCardAuthService)` — with a single mock `EventService`, something like `verifyNoMoreInteractions(…)` or even `verify(mockEventService, never()).emitAndRecordEvent(any(GatewayDoesNotRequires3dsEvent.class))` could be used.

2024-11-08 17:40 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +        assertThat(eventDetails.isRequires3DS(), is(false));
If `GatewayDoesNotRequires3dsAuthorisation` and `GatewayDoesNotRequires3dsAuthorisationEventDetails` had `equals(…)` methods on them, we could create a matching `GatewayDoesNotRequires3dsAuthorisation` object and then do `verify(mockedEventServiceForCardAuthService).emitAndRecordEvent(gatewayDoesNotRequires3dsAuthorisation)`.

2024-11-11 09:30 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +    private EventService mockedEventServiceForCardAuthService;
In reality EventService would be the same, however using Mockito only registers use in class. `verify(mockEventService, never()).emitAndRecordEvent(any(GatewayDoesNotRequires3dsEvent.class))` would always be true as the mock does not register any interactions from the second class when used in two mock constructors 🤷

2024-11-11 15:45 UTC, alexbishop1 requested changes
Looks good but I think there’s a couple more optimisations that can be made to the tests.

2024-11-11 15:45 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/charge/GatewayDoesNotRequire3dsAuthorisationEventDetails.java
> +    }
Since there are no other constructors, this can be omitted and the compiler will give us it for free.

2024-11-11 15:45 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/events/eventdetails/charge/GatewayDoesNotRequire3dsAuthorisationEventDetails.java
> +                this.requires3DS == ((GatewayDoesNotRequire3dsAuthorisationEventDetails) o).requires3DS;
Should really override `hashCode()` here too.

2024-11-11 15:45 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseService.java
> +                updatedCharge = chargeService.updateRequires3ds(updatedCharge.getExternalId(), false).get();
Rather than just `get()`, maybe have an `orElseThrow(…)` with an `IllegalStateException` with a message saying the charge has vanished from the database or something, just so we have more to go on if this assumption ever does cease to hold.

2024-11-11 15:45 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +    private EventService mockedEventService;
Minor but it’s a little inconsistent to use the `mocked` prefix when everything else in this class uses `mock`.

2024-11-11 15:45 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +        assertThat(event, equalTo(emittedEvent));
Strictly speaking you could make an equal `PaymentDetailsEvent` event like you do with the `GatewayDoesNotRequire3dsAuthorisation` and then just do the standard `verify(mockedEventService).emitAndRecordEvent(event)` but instantiating a `PaymentDetailsEvent` requires a monstrous number of arguments so maybe it’s best it’s done this way.

2024-11-11 15:45 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +    void doAuthoriseApi_shouldNotOverrideRequires3ds_IfAlreadyTrue() throws Exception {
Good spot.

2024-11-11 15:45 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +        assertThat(eventDetails.isRequires3DS(), is(false));
How is this different to what `verifyGatewayDoesNotRequire3dsEventWasEmitted(charge)` does?

2024-11-12 17:05 UTC, alexbishop1 requested changes
Looking good, just a few bits where I think we can remove duplication and simplify a little.

2024-11-12 17:05 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +        }
Can we someone how extract this so the same logic is not in two different places?

2024-11-12 17:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +        assertThat(event, equalTo(emittedEvent));
I think this can call the `verifyGatewayDoesNotRequire3dsEventWasEmitted(…)` method instead.

2024-11-12 17:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +        verify(mockEventService, never()).emitAndRecordEvent(any(GatewayDoesNotRequire3dsAuthorisation.class));
For consistency, should we also have `assertThat(charge.getRequires3ds(), is(nullValue())`?

2024-11-12 17:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseServiceTest.java
> +        assertThat(event, equalTo(emittedEvent));
The `verify(mockEventService, times(2))` is a bit brittle.

I think just doing `verify(mockEventService).emitAndRecordEvent(event)` (where `event` is the `GatewayDoesNotRequire3dsAuthorisation` object) should do the trick.

2024-11-12 17:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/WorldpayCardAuthoriseServiceTest.java
> +    private EventService mockedEventService;
Another `mocked` versus `mock` inconsistency.

2024-11-13 18:10 UTC, alexbishop1 requested changes
Looking good! Just a couple of final things.

2024-11-13 18:10 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    }
Can we inline this into the other new method now?

2024-11-13 18:10 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    public ChargeEntity updateRequires3ds(ChargeEntity chargeEntity) {
I wonder if we could make the naming clearer here? I’m having trouble thinking what it could be though. Maybe `updateRequires3dsPostAuthorisation(…)` or something?

2024-11-13 18:10 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseService.java
> +        updatedCharge = chargeService.updateRequires3ds(updatedCharge);
Now I’m wondering if we could move this into `ChargeService`’s `updateChargePostCardAuthorisation(…)` (and `updateChargePostWalletAuthorisation(…)`)…

2024-11-13 18:10 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/WorldpayCardAuthoriseServiceTest.java
> +        assertThat(event, equalTo(emittedEvent));
I assume this could also be replaced with a call to `verifyGatewayDoesNotRequire3dsEventWasEmitted(…)`.

2024-11-13 18:10 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/paymentprocessor/service/WorldpayCardAuthoriseServiceTest.java
> +        assertThat(event, equalTo(emittedEvent));
I think this could be replaced with:

```java
GatewayDoesNotRequire3dsAuthorisation event = GatewayDoesNotRequire3dsAuthorisation.from(chargeEntity, fixedInstantSource.instant());
verify(mockEventService).emitAndRecordEvent(event);
```

2024-11-14 09:35 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardAuthoriseService.java
> +        updatedCharge = chargeService.updateRequires3ds(updatedCharge);
No

2024-11-14 09:37 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    }
Why? Keep as little as possible in @Transactional methods

2024-11-14 15:29 UTC, alexbishop1 requested changes
Nice work! One comment where I think we can make a small bit of code more elegant and another comment which reveals I don’t understand JPA as well as I should do.

2024-11-14 15:29 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            }
Do we actually need to get the `ChargeEntity` from the database if we already have it? Can we not just modify the passed-in one?

2024-11-14 15:29 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +                    default -> throw new UnsupportedOperationException(format("Wallet type %s not recognised", walletAuthorisationRequest.getWalletType()));
Should be able to do this:

```java
GatewayResponse<BaseAuthoriseResponse> operationResponse = switch (walletAuthorisationRequest.getWalletType()) {
    case APPLE_PAY -> authoriseApplePay(charge, walletAuthorisationRequest);
    case GOOGLE_PAY -> authoriseGooglePay(charge, walletAuthorisationRequest);
    default -> throw new UnsupportedOperationException(format("Wallet type %s not recognised", walletAuthorisationRequest.getWalletType()));
};
```

2024-11-14 15:42 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +            }
It's detached. We could get away with just passing on external id

2024-11-15 10:50 UTC, alexbishop1 approved these changes

2024-11-15 10:50 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/wallets/WalletAuthoriseService.java
> +                };
🎉

2024-11-15 10:51 UTC, merged