PP-13331 create exemption object when appropriate
alphagov/pay-connector pull request #5636
Opened 2024-11-15 17:31 UTC by SandorArpa

## WHAT YOU DID

Add Exemption and Outcome objects to ChargeResponse. Populate new objects with appropriate values when needed.

2024-11-19 16:52 UTC, alexbishop1 requested changes
Looks good. A few suggestions, some of which are musts and some of which are maybe-if-you-feel-like-its.

2024-11-19 16:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +    @Schema(example = "{\"exemption\"{ \"requested\": true}")
Missing `:` after `\"exemption\"`

2024-11-19 16:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +    @Schema(description = "Object containing information about exemption request of the payment.")
In the schema descriptions, could we say “3DS exemption” rather than just “exemption” to make it clearer out of context?

2024-11-19 16:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +            private String result;
This could be an enum (used together with `@JsonSerialize(using = ToStringSerializer.class)` and an overridden `toString()` method).

2024-11-19 16:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +        @Schema(description = "Indicating the type of the exemption was requested for the payment, if applicable.", example = "corporate")
Maybe indicate that this might not be present?

2024-11-19 16:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +        public boolean getRequested() {
I think we usually use the `is` prefix for booleans (c.f `isMoto()`)

2024-11-19 16:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        ChargeResponse.Exemption exemption = getExemption(chargeEntity);
Could just inline this into the `.withExemption(…)` call lower down

2024-11-19 16:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private static ChargeResponse.Exemption getExemption(ChargeEntity chargeEntity) {
This is really more `buildExemptionResponseObject(…)`.

Since `ChargeService` is the longest Java class ever written*, I think we can extract this into its own class that’s injected into `ChargeService`. Might make unit testing easier too.

\* Not verified

2024-11-19 16:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        return exemption;
The nested `if` statements in this made me think harder than I wanted to on a rainy Tuesday afternoon but I think part of that is just the logic (particularly the relationship between what `chargeEntity.getExemption3ds()` and `chargeEntity.getExemption3dsRequested()` — which is never what we would have planned from the outset) is complicated.

But I love a good challenge so I had a go at seeing what I could come up with. I have something that I think is equivalent in functionality. It’s still fairly complex but I’ll leave it with you to decide if you want to make use it of it:

```java
ChargeResponse.Exemption exemptionObject = switch (chargeEntity.getExemption3ds()) {
    case EXEMPTION_NOT_REQUESTED -> {
        var exemption = new ChargeResponse.Exemption();
        exemption.setRequested(false);
        yield exemption;
    }
    case EXEMPTION_HONOURED, EXEMPTION_REJECTED, EXEMPTION_OUT_OF_SCOPE -> {
        var exemption = new ChargeResponse.Exemption();
        exemption.setRequested(true);
        var outcome = new ChargeResponse.Exemption.Outcome();
        outcome.setResult(chargeEntity.getExemption3ds().getDisplayName());
        exemption.setOutcome(outcome);
        yield exemption;
    }
    case null -> {
        if (chargeEntity.getExemption3dsRequested() != null) {
            var exemption = new ChargeResponse.Exemption();
            exemption.setRequested(true);
            yield exemption;
        }
        yield null;
    }
};

if (exemptionObject != null && chargeEntity.getExemption3dsRequested() == CORPORATE) {
    exemptionObject.setType("corporate");
}

return exemptionObject;
```

2024-11-19 16:52 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/model/Exemption3ds.java
> +    }
Might be possible to override `toString()` here but since figuring out if it’s used elsewhere is fraught with danger, I understand why you might not

2024-11-19 16:52 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceExemptionTest.java
> +                .thenReturn(new ExternalTransactionState(EXTERNAL_CREATED.getStatus(), false));
Can this not be put into the `@Before` method?

2024-11-19 16:52 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceExemptionTest.java
> +        exemption3dsType, type
Can we come up with a more meaningful name than `type`? Perhaps `typeInExemptionResponseObject` or similar?

2024-11-19 16:52 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceExemptionTest.java
> +                .thenReturn(new ExternalTransactionState(EXTERNAL_CREATED.getStatus(), false));
It would actually be `ENTERING_CARD_DETAILS` or something but that’s not really important

2024-11-19 16:52 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceExemptionTest.java
> +}
What about scenarios where the `exemption` object is not included in the response?

2024-11-19 16:52 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceIT.java
> +        void shouldGetExemptionWhenAllSet() {
What does `All` mean in this context?

2024-11-19 16:57 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +        @Schema(description = "Indicating the type of the exemption was requested for the payment, if applicable.", example = "corporate")
It says `if applicable`

2024-11-19 17:01 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private static ChargeResponse.Exemption getExemption(ChargeEntity chargeEntity) {
Yes, as I said either in the next iteration or in a firebreak I'm going to move anything to do with populating ChargeResponse to `ChargeResponseBuilderPopulator`

2024-11-19 17:05 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        return exemption;
> The nested `if` statements in this made me think harder than I wanted to on a rainy Tuesday afternoon 
 So you created an equally hard to digest solution that needs a separate if call 😆

2024-11-19 17:08 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceExemptionTest.java
> +        exemption3dsType, type
Well, it perfectly matches `response.getExemption().getType()`

2024-11-19 17:09 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceExemptionTest.java
> +}
In the IT test

2024-11-19 17:10 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceIT.java
> +        void shouldGetExemptionWhenAllSet() {
Every and each available values that might make up an Exemption object

2024-11-19 17:26 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceExemptionTest.java
> +                .thenReturn(new ExternalTransactionState(EXTERNAL_CREATED.getStatus(), false));
Nay, `ENTERING_CARD_DETAILS` is not an `ExternalChargeState`. It's more likely `EXTERNAL_SUBMITTED`

2024-11-20 09:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/model/ChargeResponse.java
> +        @Schema(description = "Indicating the type of the exemption was requested for the payment, if applicable.", example = "corporate")
Of course it does. Sorry!

2024-11-20 09:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        return exemption;
The separate `if` was just because I was trying to avoid code duplication! But I take your point. We could easily hoist it up into the `switch`, maybe also jiggling around the `if` inside the `case null` to avoid nested `if` statements:

```java
return switch (chargeEntity.getExemption3ds()) {
    case EXEMPTION_NOT_REQUESTED -> {
        var exemption = new ChargeResponse.Exemption();
        exemption.setRequested(false);
        yield exemption;
    }
    case EXEMPTION_HONOURED, EXEMPTION_REJECTED, EXEMPTION_OUT_OF_SCOPE -> {
        var exemption = new ChargeResponse.Exemption();
        exemption.setRequested(true);
        if (chargeEntity.getExemption3dsRequested() == CORPORATE) {
            exemption.setType("corporate");
        }
        var outcome = new ChargeResponse.Exemption.Outcome();
        outcome.setResult(chargeEntity.getExemption3ds().getDisplayName());
        exemption.setOutcome(outcome);
        yield exemption;
    }
    case null -> {
        if (chargeEntity.getExemption3dsRequested() == null) {
            yield null;
        }
        var exemption = new ChargeResponse.Exemption();
        exemption.setRequested(true);
        if (chargeEntity.getExemption3dsRequested() == CORPORATE) {
            exemption.setType("corporate");
        }
        yield exemption;
    }
};
```

That also means we no longer need to examine the exemption response object we’re building to make further decisions about what to do: the logic is entirely based on the values of the two enums.

We’ve also ended up with something where one `switch` arm contains all the code to build the exemption response object for a particular value of `Exemption3ds`.

I think it’s kind of neat anyway! 😀

2024-11-20 10:13 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        return exemption;
It's still much more complicated to read than my updated to be more readable code. Mine has an if, a nested if, and and an else if. Yours has six ifs (switch case counts as if).

2024-11-20 11:35 UTC, alexbishop1 requested changes
Jut a few final minor things.

2024-11-20 11:35 UTC, alexbishop1 commented on openapi/connector_spec.yaml
> +      example: "{\"exemption:\"{ \"requested\": true}"
Colon should go after the quotation mark and there should be an extra closing curly brace at the end. Also, the spacing seems a bit off here. With the colon relocated and the curly brace added, it will be `{"exemption":{ "requested": true}}` but I suspect `{"exemption": {"requested": true}}` is what was intended.

2024-11-20 11:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    private ChargeResponse.Exemption buildExemptionResponseObject(ChargeEntity chargeEntity) {
I suppose this could just take `Exemption3ds` and `Exemption3dsRequested` parameters rather than the whole `ChargeEntity`.

2024-11-20 11:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +    }
This method could take an `Exemption3ds` and return the `Outcome` but given it’s only three lines and it’s only called once we could just inline it in the method above.

2024-11-20 11:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/model/Exemption3ds.java
> +    }
Do we need `getDisplayName()` any more now we have `toString()`?

2024-11-20 11:35 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceExemptionTest.java
> +    @Test
These tests are much nicer now more stuff has been moved to the `@Before` method! 🎉

2024-11-20 11:35 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceExemptionTest.java
> +    void shouldFindChargeWithExemptionFalse_whenExemption3dsNotRequested() {
Should this be `WithExemptionRequestedFalse`?

2024-11-20 11:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        return exemption;
I think you’d have to count `exemption.setRequested(chargeEntity.getExemption3ds() != EXEMPTION_NOT_REQUESTED)` as effectively another `if` and the ternary operators for setting the type are effectively doubly-nested `if`s but I do find the updated code in the PR easier to follow so let’s go with that.

2024-11-20 11:37 UTC, SandorArpa commented on openapi/connector_spec.yaml
> +      example: "{\"exemption:\"{ \"requested\": true}"
🤦

2024-11-20 15:48 UTC, alexbishop1 approved these changes

2024-11-21 09:03 UTC, merged