PP_13241 Add historicalEventEmitter for requires3ds
alphagov/pay-connector pull request #5643
Opened 2024-11-19 17:53 UTC by hjvoid

## WHAT YOU DID
Historical Event Emitter should emit an event when a charge does not require 3ds.

## How to test

- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.

## Code review checklist

### Logging

- [ ] only emit log lines at ERROR level which require immediate attention from a support engineer. These will trigger a zendesk alert.

### Documentation

- [ ] Updated README.md for any of the following ?

* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition

2024-11-21 13:39 UTC, alexbishop1 requested changes

2024-11-21 13:39 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +    private void processGateway3DSAuthorisation(ChargeEntity charge, List<ChargeEventEntity> chargeEventEntities, boolean forceEmission) {
Looks like this is only doing the `GATEWAY_FOES_NOT_REQUIRE_3DS_AUTHORISATION` event (I assume we already have something for the `GATEWAY_REQUIRES_3DS_AUTHORISATION` event) so the method could probably be renamed

2024-11-21 13:39 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +        if(charge.getRequires3ds() != null && !charge.getRequires3ds()) {
`if (Boolean.FALSE.equals(charge.getRequires3ds())` will do the same thing (it’s null-safe) and describes the intent a bit better

2024-11-21 13:39 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +                Event doesNotRequire3DSAuthorisation = GatewayDoesNotRequire3dsAuthorisation.from(event.getChargeEntity(), event.getChargeEntity().getCreatedDate());
I don’t think `event.getChargeEntity().getCreatedDate()` is right: I think you want the timestamp of the charge event

2024-11-21 13:39 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +        }
You can actually do this all in one stream operation and reach functional nirvana:

```java
chargeEventEntities
    .stream()
    .filter(chargeEventEntity ->
            chargeEventEntity.getStatus() == AUTHORISATION_SUCCESS || chargeEventEntity.getStatus() == AUTHORISATION_REJECTED)
    .findFirst()
    .map(chargeEventEntity ->
            GatewayDoesNotRequire3dsAuthorisation.from(chargeEventEntity.getChargeEntity(),
                    chargeEventEntity.getChargeEntity().getCreatedDate())
    ).filter(gatewayDoesNotRequire3dsAuthorisation ->
            forceEmission || !emittedEventDao.hasBeenEmittedBefore(gatewayDoesNotRequire3dsAuthorisation)
    ).ifPresent(gatewayDoesNotRequire3dsAuthorisation -> {
        eventService.emitAndRecordEvent(gatewayDoesNotRequire3dsAuthorisation, getDoNotRetryEmitUntilDate());
        logger.info("Gateway does not require 3DS Authorisation event emitted for [chargeExternalId={}]", charge.getExternalId());
    });
```

2024-11-21 13:39 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +        if (chargeRequires3ds && !transactionRequires3ds) {
As we just discussed on a call, this logic is complex.I think we might be able to use enums to separate out determining what data connector has what data ledger has from evaluating whether or not they match:

```java
enum ConnectorAuthorisationSummaryState {
    CONNECTOR_HAS_REQUIRES_3DS_TRUE,
    CONNECTOR_HAS_REQUIRES_3DS_FALSE,
    CONNECTOR_HAS_REQUIRES_3DS_NULL_BUT_HAS_3DS_REQUIRED_DETAILS,
    CONNECTOR_HAS_REQUIRES_3DS_NULL_AND_NO_3DS_REQUIRED_DETAILS
}

private static ConnectorAuthorisationSummaryState calculateConnectorAuthorisationSummaryState(ChargeEntity chargeEntity) {
    if (chargeEntity.getRequires3ds() == null) {
        if (chargeEntity.get3dsRequiredDetails() == null) {
            return CONNECTOR_HAS_REQUIRES_3DS_NULL_AND_NO_3DS_REQUIRED_DETAILS;
        } else {
            return CONNECTOR_HAS_REQUIRES_3DS_NULL_BUT_HAS_3DS_REQUIRED_DETAILS;
        }
    } else if (chargeEntity.getRequires3ds()) {
        return CONNECTOR_HAS_REQUIRES_3DS_TRUE;
    } else {
        return CONNECTOR_HAS_REQUIRES_3DS_FALSE;
    }
}

enum LedgerAuthorisationSummaryState {
    LEDGER_HAS_AUTHORISATION_SUMMARY_WITH_THREE_D_S_REQUIRED_TRUE,
    LEDGER_HAS_AUTHORISATION_SUMMARY_WITH_THREE_D_S_REQUIRED_FALSE,
    LEDGER_HAS_NO_AUTHORISATION_SUMMARY,
    LEDGER_HAS_SOMETHING_COMPLETELY_DIFFERENT
}

private LedgerAuthorisationSummaryState calculateLedgerAuthorisationSummaryState(LedgerTransaction transaction) {
    if (transaction.getAuthorisationSummary() == null) {
        return LEDGER_HAS_NO_AUTHORISATION_SUMMARY;
    } else {
        if (transaction.getAuthorisationSummary().getThreeDSecure() == null) {
            return LEDGER_HAS_SOMETHING_COMPLETELY_DIFFERENT;
        } else {
            if (transaction.getAuthorisationSummary().getThreeDSecure().isRequired()) {
                return LEDGER_HAS_AUTHORISATION_SUMMARY_WITH_THREE_D_S_REQUIRED_TRUE;
            } else {
                return LEDGER_HAS_AUTHORISATION_SUMMARY_WITH_THREE_D_S_REQUIRED_FALSE;
            }
        }
    }
}

private boolean matchAuthorisationSummary(ChargeEntity chargeEntity, LedgerTransaction transaction) {
    if (chargeEntity.getCreatedDate().isBefore(CHECK_AUTHORISATION_SUMMARY_PARITY_AFTER_DATE)) {
        return true;
    }

    ConnectorAuthorisationSummaryState connectorAuthorisationSummaryState = calculateConnectorAuthorisationSummaryState(chargeEntity);
    LedgerAuthorisationSummaryState ledgerAuthorisationSummaryState = calculateLedgerAuthorisationSummaryState(transaction);

    return switch (connectorAuthorisationSummaryState) {
        case CONNECTOR_HAS_REQUIRES_3DS_NULL_AND_NO_3DS_REQUIRED_DETAILS -> {
            if (ledgerAuthorisationSummaryState != LEDGER_HAS_NO_AUTHORISATION_SUMMARY) {
                logger.info("Field value does not match between ledger and connector [field_name={}]", "authorisation_summary.three_d_secure.required",
                        kv(FIELD_NAME, "authorisation_summary.three_d_secure.required"));
                yield false;
            }
            yield true;
        }
        case CONNECTOR_HAS_REQUIRES_3DS_FALSE -> {
            if (ledgerAuthorisationSummaryState != LEDGER_HAS_AUTHORISATION_SUMMARY_WITH_THREE_D_S_REQUIRED_FALSE) {
                logger.info("Field value does not match between ledger and connector [field_name={}]", "authorisation_summary.three_d_secure.required",
                        kv(FIELD_NAME, "authorisation_summary.three_d_secure.required"));
                yield false;
            }
            yield true;
        }
        case CONNECTOR_HAS_REQUIRES_3DS_TRUE, CONNECTOR_HAS_REQUIRES_3DS_NULL_BUT_HAS_3DS_REQUIRED_DETAILS -> {
            if (ledgerAuthorisationSummaryState != LEDGER_HAS_AUTHORISATION_SUMMARY_WITH_THREE_D_S_REQUIRED_TRUE) {
                logger.info("Field value does not match between ledger and connector [field_name={}]", "authorisation_summary.three_d_secure.required",
                        kv(FIELD_NAME, "authorisation_summary.three_d_secure.required"));
                yield false;
            }
            yield isEquals(chargeEntity.get3dsRequiredDetails().getThreeDsVersion(),
                    transaction.getAuthorisationSummary().getThreeDSecure().getVersion(), "authorisation_summary.three_d_secure.version");
        }
    };
}
```

2024-11-21 13:39 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +        verify(eventService, times(1)).emitAndRecordEvent(any(GatewayDoesNotRequire3dsAuthorisation.class), isNotNull());
`times(1)` is redundant (it’s the default)

2024-11-21 13:39 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +    @MethodSource("valuesForParityCheck")
If you name the method the same as the test then you don’t need a `@MethodSource` annotation

2024-11-21 13:39 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +            Boolean chargeEntitySwitch
Is this really whether it has 3DS data or not? And can it be a `boolean` rather than a `Boolean`?

2024-11-21 13:39 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +    void parityCheck_shouldReturnMatchForThreeDSecureRequired(){
I’m not convinced this is right: I think if ledger has `authorisation_summary.three_d_secure.required` as `false` then connector should have `requires3ds` as `false` too

2024-11-22 17:04 UTC, alexbishop1 requested changes
Looks good. There’s one extra place where I think we might need to do a version check.

2024-11-22 17:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +                    .findFirst()
Not sure we can guarantee what order we get the events in in the list — maybe sort it by what `getUpdated()` returns first?

2024-11-22 17:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                yield true;
Now I think about it, we should probably check that connector’s `chargeEntity.get3dsRequiredDetails().getThreeDsVersion()` and ledger’s `transaction.getAuthorisationSummary().getThreeDSecure().getVersion()` are both null here

2024-11-22 17:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +            boolean chargeEntitySwitch
I think rather than using a boolean here we could instead pass in the desired `ChargeEntity`

2024-11-25 11:50 UTC, hjvoid commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +                    .findFirst()
I've added this in, but I think it may already being sorted via the method on line 114?

2024-11-26 17:03 UTC, alexbishop1 requested changes
Sorry this took so long. Looks good overall but I think we could test a few more combinations. Using a coverage checker may be a good way of checking we hit all the branches of the parity check.

2024-11-26 17:03 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +                    .findFirst()
That method name does sound like a giveaway! OK, please remove the sorting I asked you to add!

2024-11-26 17:03 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +        verify(eventService, times(1)).emitAndRecordEvent(any(GatewayDoesNotRequire3dsAuthorisation.class), isNotNull());
Unnecessary `times(1)`

2024-11-26 17:03 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +    private static ChargeEntity chargeEntityWith3ds;
Is it possible to avoid making these static? It imperils the independence of the tests. It seems these are static because they’re used in the static factory `@MethodSource` methods. Could we instead have these factory methods create entirely new `ChargeEntity` objects?

2024-11-26 17:03 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +
So it looks like we have the following combinations tested in the tests that are added by this PR:

| Connector `requires_3ds` | Connector `get3dsRequiredDetails()` | Ledger `AuthorisationSummary` |
|--------|--------|--------|
| `null` | Not `null` | `null` | Cell |
| `null` | Not `null` | Not `null` but no `three_d_secure` |
| `null` | Not `null` | `three_d_secure.required` is `false` |
| `null` | Not `null` | `three_d_secure.version` does not match |
| `null` | `null` | `three_d_secure.required` is `true` | 
| `null` | Not `null` | `three_d_secure.required` is `false` |
| `null` | `null`  | `three_d_secure.required` is `true` | 
| `true` | Not `null` | `three_d_secure.required` is `true` |
| `false` | Not `null` | `three_d_secure.required` is `false` |
| `null` | `null` | `null` | 

Can we add a few more? We do not seem to have a test for the matching `null`/Not `null`/`three_d_secure.required` is `true` combo. There are very few tests where connector’s `requires_3ds` is not `null` and also few tests that check the version.

2024-11-28 14:22 UTC, hjvoid commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +
Have added an extra test for the `true` and `false` values of `requires_3ds`. Also added additional test for positive match of `getThreeDSecure().setVersion`. We already have a negative check on line 394.

2024-11-28 17:30 UTC, alexbishop1 requested changes
Thanks for making those changes. I think the tests are getting clearer and I like that IntelliJ’s code coverage checker thinks the tests are executing every path.

I do think we could do a bit more to make sure we’re testing all the various combinations though, as described in the comment below.

2024-11-28 17:30 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +        }
Ooh, I like this because it makes it quite explicit what combinations we’re testing. However in the case of the `ChargeEntity`, there’s not just whether `requires3ds` is `true`, `false` or `null`, there’s also whether `get3dsRequiredDetails()` returns `null` or not. So if my maths is right there’s basically six relevant different states a `ChargeEntity` can be in (though some of those — like `requires3ds` being `true` but `get3dsRequiredDetails()` returning `null`) are nonsensical.

Could we try to make these fine methods explicitly consider setting up `get3dsRequiredDetails()` too? This would make the combinations easier to see.

If we had similar methods for creating the `LedgerTransaction` (with or without the `authorisation_summary`, `authorisation_summary.three_d_secure` etc.), we should be able to fairly easily check all the relevant combinations, which would give us greater confidence there’s no edge cases missed in the tests.

2024-12-04 17:10 UTC, alexbishop1 requested changes
This is looking good. I think we might want one or two more version mismatch tests but other that it’s just minor things.

2024-12-04 17:10 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +        ChargeEntity chargeEntityWith3dsRequiredDetailsBut3dsRequiredNull = ChargeEntityFactory.createWith3dsRequiredDetailsBut3dsRequiredNull();
Feels like these could maybe be fields

2024-12-04 17:10 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +    private static Stream<Arguments> parityCheck_shouldReturnDataMismatchFor3dsDataDiscrepencies() {
Can this go next to its test?

2024-12-04 17:10 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                        LedgerTransactionFactory.createWith3dSecureVersionMismatch(chargeEntityWith3dsRequiredDetailsBut3dsRequiredNull),
This is the only one with a version mismatch but I suspect we also want it for other casers like `requires3ds` in connector and `requires_3ds` in ledger being `true`

2024-12-04 17:10 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +        }
Do we actually need these? Or will the parity checker cry if we use an empty list?

2024-12-05 13:53 UTC, hjvoid commented
@alexbishop1 All updated with changes when you're ready 🙂

2024-12-05 16:51 UTC, alexbishop1 approved these changes, later dismissed
Awesome, thanks for persevering to get this into shape!

2024-12-05 16:51 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                ),
I’d be tempted to also make the `LedgerTransaction`s constants too!

2024-12-06 11:21 UTC, hjvoid commented
@alexbishop1  `LedgerTransaction`s updated 🚀 💥

2024-12-06 11:24 UTC, alexbishop1 approved these changes
Lovely!

2024-12-06 11:31 UTC, merged