[DRAFT]PP-13333 parity checker checks exemption data matches
alphagov/pay-connector pull request #5669
Opened 2024-12-13 10:38 UTC by hjvoid

## WHAT YOU DID
Adding checks in parity checker for 3ds exemption data.

## How to test
TBC

## Code review checklist
TBD

### Logging
TBC

2024-12-18 12:04 UTC, alexbishop1 requested changes
Looks good. Mostly stylistic changes requested. A couple of small logic changes and some more tests also.

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +            });
This can all be done as one:

```java
chargeEventEntities
    .stream()
    .filter(event -> event.getStatus() == AUTHORISATION_SUCCESS || event.getStatus() == AUTHORISATION_REJECTED)
    .findFirst()
    .map(event -> Gateway3dsExemptionResultObtained.from(charge, event.getUpdated().toInstant()))
    .filter(threeDsInfoEvent -> forceEmission || !emittedEventDao.hasBeenEmittedBefore(threeDsInfoEvent))
    .ifPresent(threeDsInfoEvent -> eventService.emitAndRecordEvent(threeDsInfoEvent, getDoNotRetryEmitUntilDate()));
```

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +            });
I think `threeDsInfoEvent` has been copied and pasted from elsewhere. `gateway3dsExemptionResultObtainedEvent` would be better.

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +            });
Can we add some logging (inside the `ifPresent(…)` to say we’re outputting the event (we have similar for other events)?

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +            });
Similarly:

```java
chargeEventEntities
    .stream()
    .filter(event -> TERMINAL_AUTHENTICATION_STATES.contains(event.getStatus()))
    .findFirst()
    .map(event -> Requested3dsExemption.from(charge, event.getUpdated().toInstant()))
    .filter(requested3dsExemptionEvent -> forceEmission || !emittedEventDao.hasBeenEmittedBefore(requested3dsExemptionEvent))
    .ifPresent(requested3dsExemptionEvent -> eventService.emitAndRecordEvent(requested3dsExemptionEvent, getDoNotRetryEmitUntilDate()));
```

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +            });
Also add some logging here too.

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +        }
This can all be done in a single elegant switch expression that explicitly enumerates all possible values:

```java
return switch (chargeEntity.getExemption3dsRequested()) {
    case null -> CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_NULL;
    case OPTIMISED -> CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_OPTIMISED;
    case CORPORATE -> CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_CORPORATE;
};
```

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +        }
Because we’re living in the future, switch expressions can handle null now:

```java
return switch (chargeEntity.getExemption3ds()) {
    case null -> CONNECTOR_HAS_EXEMPTION_NULL;
    case EXEMPTION_HONOURED -> CONNECTOR_HAS_EXEMPTION_HONOURED;
    case EXEMPTION_REJECTED -> CONNECTOR_HAS_EXEMPTION_REJECTED;
    case EXEMPTION_NOT_REQUESTED -> CONNECTOR_HAS_EXEMPTION_NOT_REQUESTED;
    case EXEMPTION_OUT_OF_SCOPE -> CONNECTOR_HAS_EXEMPTION_OUT_OF_SCOPE;
};
```

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +import static uk.gov.pay.connector.tasks.service.LedgerExemptionState.*;
We don’t like wildcard import statements

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            return LEDGER_EXEMPTION_NULL;
For consistency with similar enums, name this `LEDGER_HAS_NO_EXEMPTION`

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            return LEDGER_EXEMPTION_REQUESTED_FALSE;
`LEDGER_HAS_EXEMPTION_WITH_REQUESTED_FALSE`

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            return LEDGER_EXEMPTION_REQUESTED_TRUE;
`LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_AND_NO_OUTCOME`

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            }
Rather than throwing an exemption, this should be represented by a state that will cause the parity checker to fail, called `LEDGER_HAS_EXEMPTION_WITH_OUTCOME_WITH_NO_RESULT` or similar

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                        : LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_HONOURED;
This first one should be called `LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_WITH_RESULT_HONOURED`.

I’m concerned here that we’re implicitly assuming that any value other than `corporate` matches. I think we should be more explicit. Unfortunately, the best way I can think of to handle this is nested switches:

```java
case "honoured" -> switch (transaction.getExemption().getType()) {
    case null -> LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_NO_TYPE_AND_OUTCOME_WITH_RESULT_HONOURED;
    case "corporate" -> LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_WITH_RESULT_HONOURED;
    default -> LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_UNEXPECTED_TYPE_AND_OUTCOME_WITH_RESULT_HONOURED;
};
```

Have one of those for `rejected` and `out of scope` too.

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                        : LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_HONOURED;
Also, this would be so much nicer if the `exemption` object (and its children) in `LedgerTransaction` were a record because we could use pattern matching so we should definitely make that change in the future

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            return CONNECTOR_HAS_EXEMPTION_NULL;
`CONNECTOR_HAS_EXEMPTION_RESULT_NULL` might be a bit clearer

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                case EXEMPTION_OUT_OF_SCOPE -> CONNECTOR_HAS_EXEMPTION_OUT_OF_SCOPE;
On the right hand side, maybe make them `CONNECTOR_HAS_EXEMPTION_RESULT…` for clarity

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +        );
I like the way we ended up with the valid combinations explicitly listed

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ConnectExemption3dsRequestedState.java
> +public enum ConnectExemption3dsRequestedState {
`Connector` (not `Connect`) and we can do `3dsExemption` (we only have it the other way round sometimes because identifiers cannot start with digits)

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ConnectExemption3dsState.java
> +public enum ConnectExemption3dsState {
Maybe `Connector3dsExemptionResultState`

2024-12-18 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/Exemption3dsStateCombination.java
> +public class Exemption3dsStateCombination {
This is a perfect candidate for a record and we could then make it a local record and declare it _inside_ the `matchExemption3dsFields(…)` method:

```java
private boolean matchExemption3dsFields(ChargeEntity chargeEntity, LedgerTransaction transaction) {
    // …

    record Exemption3dsStateCombination(ConnectExemption3dsRequestedState requestedState,
            ConnectExemption3dsState connectorState,
            LedgerExemptionState ledgerState) {}

    Set<Exemption3dsStateCombination> validCombinations = Set.of(…);

    // …
}
```

2024-12-18 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +    void shouldDoStuffWithRequested3dsExemptionObtained(Exemption3ds exemption3ds, ChargeStatus chargeStatus) throws QueueException {
`DoStuff` 🤨

2024-12-18 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +        verify(eventService, times(1)).emitAndRecordEvent(argument.capture(), isNotNull());
No need for `times(1)`: it’s the default

2024-12-18 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +                Arguments.of(EXEMPTION_OUT_OF_SCOPE, AUTHORISATION_SUCCESS)
Presumably we want `AUTHORISATION_REJECTED` too?

2024-12-18 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +    void shouldCheckEventTypeIsNot3dsWhen3dsDetailsSetToNull(){
Not sure what this is supposed to be testing

2024-12-18 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +        );
There are other terminal authorisation states as well but it would be silly to test them all

2024-12-18 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +        );
I think we want (possibly as part of another test) ones with corporate exemptions too.

And probably at least some where it doesn’t match (focus on the most likely ones, like connector having an exemption result but ledger not).

2024-12-18 12:16 UTC, hjvoid commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +import static uk.gov.pay.connector.tasks.service.LedgerExemptionState.*;
Woops!

2024-12-18 12:27 UTC, hjvoid commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +    void shouldCheckEventTypeIsNot3dsWhen3dsDetailsSetToNull(){
Clarified with clearer name.

2025-02-17 10:51 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            return LEDGER_EXEMPTION_NULL;
@AbdirizakIdris

2025-02-17 10:51 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            return LEDGER_EXEMPTION_REQUESTED_FALSE;
Marco

2025-02-17 10:51 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            return LEDGER_EXEMPTION_REQUESTED_TRUE;
@AbdirizakIdris

2025-02-17 10:52 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            }
Marco

2025-02-17 10:52 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/tasks/service/ConnectExemption3dsState.java
> +public enum ConnectExemption3dsState {
@AbdirizakIdris

2025-02-17 11:39 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            return LEDGER_EXEMPTION_REQUESTED_FALSE;
Done.

2025-02-17 14:15 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            }
Done.

2025-02-18 16:30 UTC, marcotranchino commented
@AbdirizakIdris and I are now working on a separate branch linked to the following draft PR: https://github.com/alphagov/pay-connector/pull/5725

To import the new commits into this branch, first rebase on the main branch and then cherry-pick the commits.

2025-02-18 16:38 UTC, AbdirizakIdris commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            return CONNECTOR_HAS_EXEMPTION_NULL;
Renamed in the other draft branch https://github.com/alphagov/pay-connector/pull/5725

2025-02-18 16:43 UTC, AbdirizakIdris commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                case EXEMPTION_OUT_OF_SCOPE -> CONNECTOR_HAS_EXEMPTION_OUT_OF_SCOPE;
Done in the other pr draft https://github.com/alphagov/pay-connector/pull/5725

2025-02-20 09:53 UTC, marcotranchino commented on src/main/java/uk/gov/pay/connector/tasks/service/ConnectExemption3dsState.java
> +public enum ConnectExemption3dsState {
This has been done in the other branch

2025-02-21 09:51 UTC, hjvoid commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                        : LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_HONOURED;
This has been updated, as have the valid combinations that they are checked against in the `validCombinations` set variable.

2025-02-21 10:57 UTC, hjvoid commented on src/main/java/uk/gov/pay/connector/tasks/service/Exemption3dsStateCombination.java
> +public class Exemption3dsStateCombination {
I've set up a new ticket for change this to a record.

2025-02-25 10:59 UTC, alexbishop1 requested changes
Looking a lot better. A few suggestions, mostly related to renaming and a couple of places where I think we’re telling the parity checker to accept situations that should never happen.

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +                    .filter(threeDsInfoEvent -> forceEmission || !emittedEventDao.hasBeenEmittedBefore(threeDsInfoEvent))
I think we agreed to rename this to `gateway3dsExemptionResultObtainedEvent`

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +                        logger.info("Charges 3ds Exemption Result data event emitted for [chargeExternalId={}]", charge.getExternalId());
I don’t think “Charges” or “data” are necessary in the log message but maybe I’m just being picky

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +                        logger.info("Charges 3ds Exemption data event emitted for [chargeExternalId={}]", charge.getExternalId());
Same here

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                    default -> LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_HONOURED;
For consistency, call this `LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_UNEXPECTED_TYPE_AND_OUTCOME_WITH_RESULT_HONOURED`

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                    case "corporate" -> LEDGER_EXEMPTION_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_REJECTED;
For consistency, call this `LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_WITH_RESULT_REJECTED`

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                    default -> LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_REJECTED;
For consistency, call this `LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_UNEXPECTED_TYPE_AND_OUTCOME_WITH_RESULT_REJECTED`

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                    case "corporate" -> LEDGER_EXEMPTION_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_OUT_OF_SCOPE;
For consistency, call this `LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_WITH_RESULT_OUT_OF_SCOPE`

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                    default -> LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_OUT_OF_SCOPE;
For consistency, call this `LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_UNEXPECTED_TYPE_AND_OUTCOME_WITH_RESULT_OUT_OF_SCOPE`

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                default -> throw new IllegalStateException("Unexpected outcome result: " + result);
To avoid the parity checker failing altogether, have a `LEDGER_HAS_EXEMPTION_WITH_OUTCOME_WITH_UNEXPECTED_RESULT` that never matches

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +            case EXEMPTION_NOT_REQUESTED -> CONNECTOR_HAS_EXEMPTION_RESULT_REQUESTED;
I think this should be `CONNECTOR_HAS_EXEMPTION_RESULT_NOT_REQUESTED`

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                new Exemption3dsStateCombination(CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_NULL, CONNECTOR_HAS_EXEMPTION_RESULT_HONOURED, LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_HONOURED),
I’m not sure we want this line: `LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_HONOURED` — suggested to be renamed `LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_UNEXPECTED_TYPE_AND_OUTCOME_WITH_RESULT_HONOURED` elsewhere — should never happen because ledger only returns `"type": "corporate"` or no `"type"` at all

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                new Exemption3dsStateCombination(CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_NULL, CONNECTOR_HAS_EXEMPTION_RESULT_REJECTED, LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_REJECTED),
Again, I don’t think we want this line

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                new Exemption3dsStateCombination(CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_NULL, CONNECTOR_HAS_EXEMPTION_RESULT_OUT_OF_SCOPE, LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_OUT_OF_SCOPE),
Nor this one

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +        String connectorVersion = ofNullable(chargeEntity.get3dsRequiredDetails())
Not sure changing `Optional.ofNullable(…)` to `ofNullable(…)` is improving things here

2025-02-25 10:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ConnectorExemption3dsRequestedState.java
> +public enum ConnectorExemption3dsRequestedState {
`Connector3dsExemptionRequestedState` for consistency

2025-02-25 10:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +        assertThat(eventCaptor.getAllValues().get(0).getEventType(), is("PAYMENT_DETAILS_ENTERED"));
Should probably check the length of `eventCaptor.getAllValues()` to make sure there’s no other events hiding there

2025-02-25 10:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/events/HistoricalEventEmitterServiceTest.java
> +                () -> assertThat(gatewayExemptionDetails.getExemption3ds(), is(exemption3ds == null ? null : exemption3ds.toString()))
I suspect `exemption3ds.toString()` wants to be `exemption3ds.name()`

2025-02-25 10:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                Arguments.of(OPTIMISED, EXEMPTION_OUT_OF_SCOPE, "out of scope", true)
These strings should actually be `EXEMPTION_HONOURED.name()` and `EXEMPTION_REJECTED.name()` etc. (the `toString()` values are only used for display, not sent in the events)

2025-02-25 10:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                Arguments.of(CORPORATE, EXEMPTION_OUT_OF_SCOPE, "out of scope", true)
Same thing with the strings here

2025-02-25 10:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                Arguments.of(null, EXEMPTION_HONOURED, "out of scope", true)
Same thing with the strings here.

Also, the last one is identical to the one before. I presume the first argument should be `OPTIMISED`.

2025-02-25 10:59 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                Arguments.of(CORPORATE, EXEMPTION_REJECTED, "honoured", true)
Strings!

2025-02-25 15:47 UTC, hjvoid commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                Arguments.of(OPTIMISED, EXEMPTION_OUT_OF_SCOPE, "out of scope", true)
Our `Exemption3ds` type only has a `getDisplayName` which we can use. e.g.
`Arguments.of(null, EXEMPTION_HONOURED, EXEMPTION_HONOURED.getDisplayName(), true)`

2025-02-26 10:26 UTC, hjvoid commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                Arguments.of(OPTIMISED, EXEMPTION_OUT_OF_SCOPE, "out of scope", true)
We leave everything as strings rather than deserialising back into enums. Discussed on Slack.

2025-02-26 10:26 UTC, hjvoid commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                Arguments.of(CORPORATE, EXEMPTION_OUT_OF_SCOPE, "out of scope", true)
We leave everything as strings rather than deserialising back into enums. Discussed on Slack.

2025-02-26 10:27 UTC, hjvoid commented on src/test/java/uk/gov/pay/connector/tasks/service/ChargeParityCheckerTest.java
> +                Arguments.of(CORPORATE, EXEMPTION_REJECTED, "honoured", true)
We leave everything as strings rather than deserialising back into enums. Discussed on Slack.

2025-02-26 15:01 UTC, alexbishop1 requested changes
Just some renaming and removing one invalid combination to do, I think

2025-02-26 15:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +                    .filter(threeDsInfoEvent -> forceEmission || !emittedEventDao.hasBeenEmittedBefore(threeDsInfoEvent))
This has still not bee changed!

2025-02-26 15:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                    case "corporate" -> LEDGER_EXEMPTION_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_REJECTED;
Still needs renaming!

2025-02-26 15:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                    case "corporate" -> LEDGER_EXEMPTION_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_OUT_OF_SCOPE;
Still needs renaming!

2025-02-26 15:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +        Set<Exemption3dsStateCombination> validCombinations = Set.of(
Sorry for only mentioning it now but can you make `validCombinations` into a `private static final Set<Exemption3dsStateCombination> VALID_3DS_EXEMPTION_COMBINATIONS` constant? It’s a bit wasteful to build the set from scratch for each payment.

2025-02-26 15:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +                new Exemption3dsStateCombination(CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_NULL, CONNECTOR_HAS_EXEMPTION_RESULT_HONOURED, LEDGER_HAS_EXEMPTION_WITH_REQUESTED_TRUE_UNEXPECTED_TYPE_AND_OUTC
I think we want to remove this one

2025-02-26 15:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/tasks/service/ChargeParityChecker.java
> +        );
With the exception of the one mentioned above, I’ve checked all of these against the acceptance criteria in the story and they’re good

2025-02-26 15:06 UTC, hjvoid commented on src/main/java/uk/gov/pay/connector/tasks/HistoricalEventEmitter.java
> +                    .filter(threeDsInfoEvent -> forceEmission || !emittedEventDao.hasBeenEmittedBefore(threeDsInfoEvent))
Hasn't it? 😕

2025-02-26 15:52 UTC, alexbishop1 approved these changes

2025-02-26 15:54 UTC, merged