Pp 3450 epdq 3ds auth request
alphagov/pay-connector pull request #587
Opened 2018-03-08 16:24 UTC by chrisgrimble

Create and handle an EPDQ 3ds authorise request. The request needs a extra fields on it to tell EPDQ the request is a 3ds authorise request. This includes some callback url that EPDQ will send the user to once 3ds has been completed. For now these are not confirmed and may need to change when we do the frontend logic for this. EPDQ will then return a response with a status of 46 and a new element containing some html. The html needs to be save. Then later on frontend will make a new request for the charge data and this needs to include the html.

- Mapped the correct status code.
- created a separated request builder for authorise 3ds (putting non-existent frontend URLs for now).
- Map the response from EPDQ and add the new html to the entities above.
- Add html to the response from connector.

2018-03-12 17:58 UTC, alexbishop1 requested changes

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/Auth3dsDetailsDTO.java
> +public class Auth3dsDetailsDTO {
This name is a bit confusing because we also have `Auth3dsDetails`, which is only used for 3D Secure for Worldpay (but could potentially be used by other payment gateways that have a Worldpayesque 3D Secure flow). Perhaps we could clarify things by renaming `Auth3dsDetails` (and its friends`Auth3dsResponseGatewayRequest`, which `Card3dsResponseAuthService`) to something that indicates they’re basically Worldpay-specific.

But I digress. This `Auth3dsDetailsDTO` class will only ever have `issuerUrl` and `paRequest` set, or `htmlOut` set. Could we perhaps make this into an interface, called, say, `GatewayParamsFor3DSecure` (since that’s what it is: the parameters we need from the gateway to set up the 3D Secure authentication process for the user) and then have concrete `WorldpayParamsFor3DSecure` and `EpdqParamsFor3DSecure` implementations?

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/ChargeResponse.java
> +        @JsonProperty("htmlOut")
Devoid of its 3D Secure context, the name `htmlOut` is a bit vague (to be fair, `issuerUrl` has the same problem)

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/Card3dsEntity.java
> +        return chargeTransactionEntity != null ? chargeTransactionEntity.equals(that.chargeTransactionEntity) : that.chargeTransactionEntity == null;
What was wrong with `Objects.equal`?

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/Auth3dsDetailsEntity.java
> +    public Auth3dsDetailsEntity(Auth3dsDetailsDTO auth3dsDetails) {
Having this variable called `auth3dsDetails` when it’s an `Auth3dsDetailsDTO` object and not an `Auth3dsDetails` object is going to confuse and confound people

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/BaseAuthoriseResponse.java
> +    Optional<Auth3dsDetailsDTO> getAuth3dsDetails();
This is nicer. Yay for encapsulation!

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqAuthorisationResponse.java
> +        if(WAITING_3DS.equals(status)) {
I think we’ve reached the point where this should become a `switch` statement

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqAuthorisationResponse.java
> +            return Optional.of(new Auth3dsDetailsDTO(null, null, htmlAnswer));
Overloaded constructor to avoid this null-ugliness? Or maybe that subclassing idea I suggested in an earlier comment

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqAuthorisationResponse.java
> +    public String getStatus() {
This seems to only be used in tests and equivalent information can be retrieved using the `authoriseStatus` method

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqOrderRequestBuilder.java
> +        private String frontendUrl;
`frontendUrl` for that?

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +        String epdqCallbackUrl = String.format("%s/card_details/%s/3ds_required_in", templateData.getFrontendUrl(), templateData.getOrderId());
This variable exists in a class with `Epdq` in the name: it doesn’t need to be prefixed with `epdq`. Also, it’s a redirect URL, rather than a callback URL.

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +                .add("EXCEPTIONURL", epdqCallbackUrl + "/exception")
Not sure we want to put a term like `exception` in our URLs — `error`, maybe?

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +}
This class is very similar to `EpdqPayloadDefinitionForNewOrder` and it’s likely changes to that will require changes to this class. Can we somehow extend what we already have?

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +    private final String frontendUrl;
Can you name this field such that its purpose of this field is clearer?

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +                epdqOrderRequestBuilder = anEpdq3DsAuthoriseOrderRequestBuilder(frontendUrl);
Ternary operator maybe?

2018-03-12 17:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/worldpay/WorldpayOrderStatusResponse.java
> +            joiner.add("issuerURL: " + paRequest);
The label’s wrong here! Also, it’s just an opaque string — is there any value to outputting this?

2018-03-12 17:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +    private void setUpAndCheckThatEpdqIsUp(boolean require3ds) {
Not fond of using an `boolean` for this: how about differently-named methods (that mostly defer to a common third method)?

2018-03-12 17:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +        String validSandboxCard = "4000000000000002";
Why was this changed? Also, `validSandboxCard` should probably be `validEpdqCard` (I appreciate this was like this before you got there)

2018-03-12 17:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqCardResourceITest.java
> +import static uk.gov.pay.connector.model.domain.ChargeStatus.*;
We’ve standardised on non-wildcard imports

2018-03-12 17:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/CardAuthoriseServiceTest.java
> +        assertThat(card3ds.getHtmlOut(), is(notNullValue()));
Can’t we test for an actual value?

2018-03-12 17:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/CardAuthoriseServiceTest.java
> +    private void providerWillRequireEpdq3ds() throws XMLUnmarshallerException {
This could do with a better name like `epdqProviderWillRequire3ds` — also, `providerWillRequire3ds` should become something like `worldpayProviderWillRequire3ds`

2018-03-12 17:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProviderTest.java
> +import static uk.gov.pay.connector.util.TestTemplateResourceLoader.*;
No wildcard imports!

2018-03-12 17:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProviderTest.java
> +    public void shouldAuthorise3DRequest() {
`3ds`

2018-03-12 17:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProviderTest.java
> +        assertThat(response.getBaseResponse().get().getStatus(),is("46"));
Assert on `authoriseStatus()` here please

2018-03-13 09:56 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProviderTest.java
> +        assertThat(response.getBaseResponse().get().getStatus(),is("46"));
👍

2018-03-13 09:56 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProviderTest.java
> +    public void shouldAuthorise3DRequest() {
👍

2018-03-13 09:56 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProviderTest.java
> +import static uk.gov.pay.connector.util.TestTemplateResourceLoader.*;
:|

2018-03-13 09:58 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProviderTest.java
> +import static uk.gov.pay.connector.util.TestTemplateResourceLoader.*;
😑

2018-03-13 10:12 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/service/CardAuthoriseServiceTest.java
> +    private void providerWillRequireEpdq3ds() throws XMLUnmarshallerException {
👍

2018-03-13 10:27 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/service/CardAuthoriseServiceTest.java
> +        assertThat(card3ds.getHtmlOut(), is(notNullValue()));
could do: But will pollute the code a bit having to add 2 extra setters (just for testing) 😑

2018-03-13 10:27 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/BaseAuthoriseResponse.java
> +    Optional<Auth3dsDetailsDTO> getAuth3dsDetails();
🎉

2018-03-13 10:35 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/model/ChargeResponse.java
> +        @JsonProperty("htmlOut")
well, its inside a `Auth3dsData` context. So clients will read as `auth_3ds_data.htmlOut`. We tried to comply to the `out` and `in` concept of 3ds handover in frontend so this being the html form for `out` going. We couldn't think of a better name to be honest !

2018-03-13 10:36 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/model/domain/Card3dsEntity.java
> +        return chargeTransactionEntity != null ? chargeTransactionEntity.equals(that.chargeTransactionEntity) : that.chargeTransactionEntity == null;
This is intellij auto-generated. Do we care? 🤔

2018-03-14 11:09 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqAuthorisationResponse.java
> +    public String getStatus() {
👍

2018-03-14 11:11 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqOrderRequestBuilder.java
> +        private String frontendUrl;
yes, its needed in order to tell epdq, what are the redirection points to send the user back to

2018-03-14 11:16 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +        String epdqCallbackUrl = String.format("%s/card_details/%s/3ds_required_in", templateData.getFrontendUrl(), templateData.getOrderId());
renamed to `frontend3dsIncomingUrl`

2018-03-14 11:16 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +                .add("EXCEPTIONURL", epdqCallbackUrl + "/exception")
👍

2018-03-14 11:25 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +}
👍 (_although i hate inheritence_)

2018-03-14 11:31 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +    private final String frontendUrl;
This is the same of config's `frontendUrl` variable. I guess its global and known to everyone everywhere. the only thing I can think of is `frontendBaseUrl` but not sure if that serves any extra purpose.

2018-03-14 14:34 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +                epdqOrderRequestBuilder = anEpdq3DsAuthoriseOrderRequestBuilder(frontendUrl);
😑  really? okay 👍

2018-03-14 14:36 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/worldpay/WorldpayOrderStatusResponse.java
> +            joiner.add("issuerURL: " + paRequest);
probably not. But it has always been there. So I'm going to leave this refactoring for another day

2018-03-14 14:43 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +    private void setUpAndCheckThatEpdqIsUp(boolean require3ds) {
👍

2018-03-14 14:46 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +        String validSandboxCard = "4000000000000002";
This was needed. This card works for both 3ds and non-3ds scenarios.

2018-03-14 14:47 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqCardResourceITest.java
> +import static uk.gov.pay.connector.model.domain.ChargeStatus.*;
👍

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/ChargeResponse.java
> +        @JsonProperty("htmlOut")
Missed that it’s in an inner class: in that case, the name is fine

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/EpdqParamsFor3DSecure.java
> +public class EpdqParamsFor3DSecure implements GatewayParamsFor3DSecure {
OK, I know I suggested this name but it seems our convention is to use `3ds` rather than `3DSecure` in class names, so please do that

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/EpdqParamsFor3DSecure.java
> +    public final String htmlOut;
`public`?

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/WorldpayParamsFor3DSecure.java
> +    public final String paRequest;
Stop airing our dirty laundry in `public`!

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/Card3dsEntity.java
> +        return chargeTransactionEntity != null ? chargeTransactionEntity.equals(that.chargeTransactionEntity) : that.chargeTransactionEntity == null;
I actually have lots of opinions about the perils of autogenerated `equals`, `hashCode` and `toString` methods but that’s perhaps something for the pub.

In this case, I’m OK with it.

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/GatewayAccountEntity.java
> +    public boolean requires3ds() {
I like this renaming

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/BaseAuthoriseResponse.java
> +    Optional<? extends GatewayParamsFor3DSecure> getAuth3dsDetails();
Rename this method please.

I would really to not use the wildcard `?` type here (so we’d make the class be `BaseAuthoriseResponse<T>` where `T extends GatewayParamsFor3DSecure`, `getAuth3dsDetails()` would return `T` and we’d have `EpdqAuthorisationResponse implements  BaseAuthoriseResponse<EpdqParamsFor3DSecure>` etc.).

But I know adding generics like this can be like tugging a loose thread, so I’m not going to insist on it. But maybe try? You have my permission to revert after ten minutes if it’s turning into a giant mess.

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqAuthorisationResponse.java
> +        if (WAITING_3DS.equals(status)) {
I still think this should be a `switch` statement

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqOrderRequestBuilder.java
> +        private String frontendUrl;
I’m still not too clear on what it actually means. What actual value would this have? I think we can tease out a less generic name.

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +        String frontend3dsIncomingUrl = String.format("%s/card_details/%s/3ds_required_in", templateData.getFrontendUrl(), templateData.getOrderId());
`frontendUrlToRedirectUserToAfterTheyComplete3dsAuthentication`, maybe? It’s long but it makes it really clear where this URL is used in the 3D Secure flow (I get confused by all this in, out, shake-it-all-about stuff).

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +}
So are you going to do that then? 😃

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +    private final String frontendUrl;
If this never changes, I wonder if we could somehow use a constant to make it clearer…

2018-03-15 12:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/worldpay/WorldpayOrderStatusResponse.java
> +            joiner.add("issuerURL: " + paRequest);
What I meant was that the `paRequest` was not included in the `toString()` previously and I don’t think there’s much reason to add it

2018-03-15 12:06 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +        String validSandboxCard = "4000000000000002";
Fair enough on the value. Variable name still needs renaming though!

2018-03-15 12:06 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqCardResourceITest.java
> +                .body("status", Matchers.is(AUTHORISATION_3DS_REQUIRED.toString()))
Static import `is` please (more readable)

2018-03-15 12:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/ChargeResponse.java
> +        @JsonProperty("htmlOut")
But is this a Base64-encoded value? Maybe the name could indicate that.

2018-03-15 12:06 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/CardAuthoriseServiceTest.java
> +        assertThat(card3ds.getHtmlOut(), is(notNullValue()));
But you did it anyway! 😃

2018-03-15 12:13 UTC, alexbishop1 requested changes
Looks better! Thanks for making the changes. Just a few things remaining.

2018-03-15 12:18 UTC, alexbishop1 approved these changes
As discussed, since none of my requests are show-stoppers, I will approve this in order that you can get this merged and unblock other things, on the condition you address the remaining comments in a subsequent PR.

2018-03-15 12:24 UTC, kakumara commented
I'll address the remaining in the next PR

2018-03-15 12:25 UTC, merged

2018-03-15 14:07 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/model/EpdqParamsFor3DSecure.java
> +public class EpdqParamsFor3DSecure implements GatewayParamsFor3DSecure {
🤕

2018-03-15 14:14 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/model/EpdqParamsFor3DSecure.java
> +    public final String htmlOut;
👍

2018-03-15 14:20 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/model/WorldpayParamsFor3DSecure.java
> +    public final String paRequest;
It was deliberate (). Note it is `final` and it is a DTO. This avoid the clutters of getters(). 

Although, in this case I've refactored the uses of them to use other means for testing (so removed public)). But this particular aspect is something I would vote over having to  generate clutters of getters and setters on DTO classes.

2018-03-15 14:29 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +        String frontend3dsIncomingUrl = String.format("%s/card_details/%s/3ds_required_in", templateData.getFrontendUrl(), templateData.getOrderId());
So on this case, this name is consistent with the existing 3ds implementation flow. There is a concept of `3ds_out` and `3ds_in` already spanned across connector and frontend. This refers to the same `in` url. we believe whoever going to work on 3ds should be aware of these 2 aspects of 3ds? Happy to discuss.

2018-03-15 14:48 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqAuthorisationResponse.java
> +        if (WAITING_3DS.equals(status)) {
This is a relative opinion. I've changed it to a `switch` but in this case we feel if statements are more readable than switch.

2018-03-15 14:48 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqOrderRequestBuilder.java
> +        private String frontendUrl;
I've renamed to `frontendBaseUrl`.

2018-03-15 14:49 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +}
done it

2018-03-15 14:50 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPaymentProvider.java
> +    private final String frontendUrl;
This is not a constant unfortunately. Its set by dependency injection at startup

2018-03-15 14:52 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +        String validSandboxCard = "4000000000000002";
of course 😖 👍

2018-03-15 14:54 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqCardResourceITest.java
> +                .body("status", Matchers.is(AUTHORISATION_3DS_REQUIRED.toString()))
👍

2018-03-15 15:02 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/BaseAuthoriseResponse.java
> +    Optional<? extends GatewayParamsFor3DSecure> getAuth3dsDetails();
Yes. I went through the exact same thought and got tangled my self. It all fine until SandboxAuthoriseResponse and SmartpayAuthoriseResponse cannot extend with a type because they don't exist (at least yet). so given that this seems to be the closest i can get to.

2018-03-15 15:28 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/model/domain/GatewayAccountEntity.java
> +    public boolean requires3ds() {
but that broke the build 😢  🔴

2018-03-16 09:38 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqAuthorisationResponse.java
> +        if (WAITING_3DS.equals(status)) {
Changed my mind (after chatting with couple of others) , the switch more unreadable (relatively) compared to the if's here. Particularly when there's a `or`/ `and` involved in somewhere.

2018-03-16 11:23 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/WorldpayParamsFor3DSecure.java
> +    public final String paRequest;
Fair enough; thanks for explaining. `public` fields are less of a concern if they’re immutable.

2018-03-16 11:24 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/BaseAuthoriseResponse.java
> +    Optional<? extends GatewayParamsFor3DSecure> getAuth3dsDetails();
Well, thanks for trying!

2018-03-16 11:35 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +        String frontend3dsIncomingUrl = String.format("%s/card_details/%s/3ds_required_in", templateData.getFrontendUrl(), templateData.getOrderId());
I think the _out_ and _in_ stuff has mostly been restricted to frontend so far (and I never found those terms that descriptive anyway). But you’re right that it is a convention, so I’m happy to leave this as it is.

2018-03-16 11:37 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqPayloadDefinitionForNew3dsOrder.java
> +}
Sorry for not noticing you’d started extending `EpdqPayloadDefinitionForNewOrder`. There’s still quite a bit of duplication though, which it would be nice to address (in particular things like the `concatAddressLines` method being in both classes).

2018-03-16 14:25 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/EpdqParamsFor3DSecure.java
> +public class EpdqParamsFor3DSecure implements GatewayParamsFor3DSecure {
This has been done in https://github.com/alphagov/pay-connector/pull/588/files

2018-03-16 16:53 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqOrderRequestBuilder.java
> +        private String frontendUrl;
This has been done in https://github.com/alphagov/pay-connector/pull/588/files

2018-03-16 16:58 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/contract/EpdqPaymentProviderTest.java
> +        String validSandboxCard = "4000000000000002";
This has been done in https://github.com/alphagov/pay-connector/pull/588/files

2018-03-16 17:16 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/WorldpayParamsFor3DSecure.java
> +    public final String paRequest;
This has been done in https://github.com/alphagov/pay-connector/pull/588/files