PP-3526 smartpay 3ds required request handling
alphagov/pay-connector pull request #603
Opened 2018-03-23 15:23 UTC by kakumara

This must wait for https://github.com/alphagov/pay-connector/pull/602 and until we get a success response for the contract test. 
## WHAT

Includes:
- 3ds require elements added to the smartpay order template based on Gateway account 3ds require flag.
- Card3dsEntity and Auth3dsDetailsEntity extended to use the new field `md` specific to smartpay.
- extended SmartpayAuthorisationResponse to extract the 3ds required elements out of the XML response. (issuerUrl, paRequest, md). Also determining the authorisationStatus() based on `RedirectShopper` status.

2018-03-23 16:31 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/epdq/EpdqOrderRequestBuilder.java
> +        return new EpdqOrderRequestBuilder(epdqTemplateData, AUTHORISE_3DS_ORDER_TEMPLATE_BUILDER, OrderRequestType.AUTHORISE_3DS, AUTHORISE_OPERATION_TYPE);
Why did this change for smartpay

2018-03-23 16:47 UTC, chrisgrimble requested changes

2018-03-23 16:47 UTC, chrisgrimble commented on src/main/resources/migrations.xml
> +    </changeSet>
Don't we need to deploy this first as one branch then start using it in the Java in a later release? Maybe we can get away with this as no one will do a 3ds payment until we turn it on.

2018-03-23 16:47 UTC, chrisgrimble commented on src/test/java/uk/gov/pay/connector/it/contract/SmartpayPaymentProviderTest.java
> +    //TODO: fix this before merging
You said it yourself

2018-03-23 16:47 UTC, chrisgrimble commented on src/main/java/uk/gov/pay/connector/service/smartpay/SmartpayAuthorisationResponse.java
> +        }
More a question but before we defaulted to REJECTED rather than error. I guess this isn't really a problem but will end up with a different page in frontend when things go wrong?

2018-03-23 16:50 UTC, kakumara commented on src/main/resources/migrations.xml
> +    </changeSet>
yes. This is because this branch is still based on the DB change branch. but once it goes on this rebased this will disappear from here

2018-03-23 16:55 UTC, kakumara commented on src/main/java/uk/gov/pay/connector/service/smartpay/SmartpayAuthorisationResponse.java
> +        }
Yes. I realised out smartpay response mapping was not inline with other payment providers as I did this. even a network error (soap fault) we are marking as AUTH REJECTED which is wrong. We are handling these nicely in worldpay and epdq, so I changed the default to ERROR while REJECTED is only if smartpay tells us REJECTED.

2018-03-23 16:56 UTC, kakumara commented on src/test/java/uk/gov/pay/connector/it/contract/SmartpayPaymentProviderTest.java
> +    //TODO: fix this before merging
Yep, I still get a error 500 from smartpay. So we have to wait till we get some response from smartpay support before we push this to master. Will be fixing it!

2018-03-27 12:26 UTC, chrisgrimble submitted a review, later dismissed
LGTM

2018-03-28 11:10 UTC, chrisgrimble approved these changes
Rebased so LGTM

2018-03-28 13:00 UTC, merged