BAU: Add performance report resource
alphagov/pay-connector pull request #607
Opened 2018-04-07 18:58 UTC by tlwr

We need a better way to get performance platform data, I propose we
query the database, to do this we need an API endpoint which returns to
us the relevant data.

This creates a resource at `/v1/api/reports/performanceReport` which
returns the volume of captured payments, and the total amount in pence.

We can then query this from an ad-hoc task within our infrastructure which will ensure this gets to the relevant people and to the performance platform.

I fully expect to get roasted with this PR as I haven't written serious
java in about 4 or 5 years. Especially because I used vim and so there are probably a ton of unused imports. Also no tests...

@alexbishop1 :eyes: pls

solo @tlwr

2018-04-09 10:14 UTC, alexbishop1 requested changes
Good start!

I note that when we query, we just get the totals for everything (i.e. from the beginning of time until now). I presume if we want daily reports or whatever, we might want to restrict by date. This could be tricky though because charges only have a created date, which might not match the date it was captured, so we could end up missing some.

We might instead want to query the `charge_events` table instead (which does have timestamps for captures), find all the charges that were captured on a particular day, then join back on to the `charges` table to get the amounts.

2018-04-09 10:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/report/PerformanceReportEntity.java
> +public class PerformanceReportEntity {
As you’ve discovered, this isn’t going to work because there’s no primary key. Since this class doesn’t represent anything real in the database, I don’t think we need to actually use an `@Entity` class here. We could just have a POJO and initialise it directly by interrogating the query result rather than relying on JPA’s entity mapping.

2018-04-09 10:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/report/PerformanceReportEntity.java
> +    private final static Logger logger = LoggerFactory.getLogger(PerformanceReportEntity.class);
Don’t need a logger if you’re not doing any logging!

2018-04-09 10:14 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/PerformanceReportResource.java
> +    @Path("/v1/api/reports/performanceReport")
We prefer to have URLs like `performance-report`

2018-04-10 16:58 UTC, alexbishop1 submitted a review, later dismissed
Assuming we don’t need to filter by date yet, this is getting there

2018-04-10 16:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/PerformanceReportDao.java
> +            long[] results = (long[]) entityManager.get()
Unfortunately, this cast doesn’t work. Even if it did, not all the returned columns are longs (the `AVG` ends up as a double).

From my fairly rudimentary knowledge of JPA, mapping the results of a query to a POJO without involving an entity of a bunch of XML is a bit of a pain. Using a native query makes it more so.

However, your query is not actually beyond the capabilities of JPQL, so we can use plain `createQuery`. Something like this should allow us to get a `PerformanceReportEntity` object out:

```
"SELECT NEW uk.gov.pay.connector.model.domain.report.PerformanceReportEntity(COUNT(c.amount), SUM(c.amount), AVG(c.amount)) FROM ChargeEntity c WHERE c.status = :status"
```

But perhaps someone with a better grasp of SQL than me may be able to offer a better suggestion.

2018-04-10 16:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/PerformanceReportDao.java
> +                    .setParameter("status", CAPTURED)
We need to convert the enum variant to a string: `CAPTURED.toString()`

2018-04-10 16:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/report/PerformanceReportEntity.java
> +    private long averageAmount;
This needs to be a double because it’s a floating point number

2018-04-10 16:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/report/PerformanceReportEntity.java
> +    private long averageAmount;
All of these fields can be `final`

2018-04-10 16:58 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/PerformanceReportResource.java
> +public class PerformanceReportResource {
To make this work, you also need to add `PerformanceReportResource.class` to `ConnectorApp`

2018-05-25 10:17 UTC, tlwr commented
Rebased this onto master and have added Alex's request

2018-05-29 09:01 UTC, alexbishop1 requested changes
Needs more glue code to hook everything up

2018-05-29 09:01 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ConnectorApp.java
> +import uk.gov.pay.connector.resources.PerformanceReportResource;
You also need a `environment.jersey().register(injector.getInstance(PerformanceReportResource.class));` line in the `run(ConnectorConfiguration, Environment)` method in this class.

2018-05-29 09:14 UTC, tlwr commented on src/main/java/uk/gov/pay/connector/app/ConnectorApp.java
> +import uk.gov.pay.connector.resources.PerformanceReportResource;
done

2018-05-29 14:06 UTC, alexbishop1 requested changes
Getting there!

2018-05-29 14:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/PerformanceReportDao.java
> +                    .createNativeQuery("SELECT NEW uk.gov.pay.connector.model.domain.report.PerformanceReportEntity(COUNT(c.amount), SUM(c.amount), AVG(c.amount)) FROM ChargeEntity c WHERE c.status =
As discussed in an outdated comment, this needs to be `createQuery` now

2018-05-29 14:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/PerformanceReportDao.java
> +                    .setMaxResults(1)
This will fail hard if there aren’t any payments. Since that’s not going to happen much in the real world, not sure how much of a concern that is.

2018-05-29 14:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/report/PerformanceReportEntity.java
> +    private final float averageAmount;
The query will give us a `double` rather than a float (also update the constructor and getter)

2018-05-29 16:45 UTC, alexbishop1 approved these changes
I’m still not entirely convinced that getting a count of all payments ever made using the platform is especially useful, but the code works (and should be fast due to the index on the `status` column) so I trust you know what you’re doing

2018-05-29 17:23 UTC, merged