PP-3059: WIP This should obfuscate email in connector untested.
alphagov/pay-connector pull request #627
Opened 2018-06-22 09:12 UTC by whpearson

This should obfuscate the email in logs from connector.

Planning to test, but putting up for comment on methedology.

2018-06-22 09:43 UTC, alexbishop1 requested changes
I’ve made a comment about a way of doing this I think might be a bit neater

2018-06-22 09:43 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeSearchParams.java
> +        return queryParams.toString().replaceAll("email=[^&+]", "email=*****" );
My regex foo is a little weak but I’m not sure if this regex will actually match what we want

2018-06-22 09:43 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeSearchParams.java
> +        return queryParams.toString().replaceAll("email=[^&+]", "email=*****" );
Also, `queryParams` is already a string: you don’t need to `toString()` it!

2018-06-22 09:43 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeSearchParams.java
> +    public String buildFilteredQueryParams() throws PatternSyntaxException {
We can probably make this method name more specific: `buildQueryParamsRedactingPii` (“PII” = “personally-identifiable information”) maybe?

Rather than building the query params and then doing a search-and-replaces on the resulting string, I think it might be a bit cleaner to exclude the email when building the query params. This could be done in a minimally invasive way by doing something like this:

```java
public String buildQueryParams() {
    return buildQueryParams(false);
}

public String buildQueryParamsRedactingPii() {
    return buildQueryParams(true);
}

private String buildQueryParams(boolean redactPii) {
    StringBuilder builder = new StringBuilder();
    if (transactionType != null) {
        builder.append("&transaction_type=").append(transactionType.getValue());
    }
    if (isNotBlank(reference))
        builder.append("&reference=").append(reference);
    if (email != null)
        if (redactPii) {
            builder.append("&email=****");
        } else {
            builder.append("&email=").append(email);
        }
    if (fromDate != null)
        builder.append("&from_date=").append(fromDate);
    if (toDate != null)
        builder.append("&to_date=").append(toDate);
    if (page != null)
        builder.append("&page=").append(page);
    if (displaySize != null)
        builder.append("&display_size=").append(displaySize);

    getExternalStates().stream()
            .findFirst()
            .ifPresent(state -> builder.append("&state=").append(state));

    String paymentStates = this.externalChargeStates.stream()
            .collect(Collectors.joining(","));

    String refundStates = this.externalRefundStates.stream()
            .collect(Collectors.joining(","));

    if (isNotEmpty(paymentStates)) {
        builder.append("&payment_states=").append(paymentStates);
    }

    if (isNotEmpty(refundStates)) {
        builder.append("&refund_states=").append(refundStates);
    }

    if (!cardBrands.isEmpty()) {
        cardBrands.forEach(cardBrand -> builder.append("&card_brand=").append(cardBrand));
    }
    return builder.toString().replaceFirst("&", "");
}
```

(We could also avoid the need to remove the first ampersand by using a `StringJoiner` — or maybe something designed to create URL query strings — but let’s not try to fix all the world’s problems here.)

2018-06-22 12:51 UTC, whpearson commented on src/main/java/uk/gov/pay/connector/dao/ChargeSearchParams.java
> +    public String buildFilteredQueryParams() throws PatternSyntaxException {
Sounds like a better approach.

2018-06-22 16:31 UTC, alexbishop1 requested changes
Looking good.

This could probably do with at least one test in `ChargeSearchParamsTest`. You can just copy the first one, make it call the `buildQueryParamsWithPiiRedaction()` method and change the expected result to include `&email=xxxx`.

2018-06-22 16:31 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeSearchParams.java
> +    public String buildQueryParams(boolean redactPii) {
This should be `private` (as we only want people to call the two `public` methods)

2018-06-25 15:42 UTC, tlwr submitted a review, later dismissed

2018-06-25 16:00 UTC, alexbishop1 requested changes
Looks good: just a minor stylistic point about curly braces

2018-06-25 16:00 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeSearchParams.java
> +        }
Can you always use curly braces even for single-line `if`/`else` statements please?

Alternatively, I’d be OK with a ternary operator like this:

```java
if (email != null) {
    builder.append("&email=");
    redactPii ? builder.append("****") : builder.append(email);
}
```

… but some people really, really don’t like ternary operators!

2018-06-25 16:33 UTC, alexbishop1 submitted a review, later dismissed
Great stuff!

Left a couple of comments about trivial things but I’m not going to hold approval on them

2018-06-25 16:33 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeSearchParams.java
> +import java.util.regex.PatternSyntaxException;
This import can be removed; sorry, didn’t notice this until now

2018-06-25 16:33 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeSearchParams.java
> +            else {
We prefer this style:

```java
} else {
```

2018-06-25 16:33 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeSearchParams.java
> +        return (this.buildQueryParams(false));
Don’t need the outer parentheses here (applies to the method below too)

2018-06-26 12:03 UTC, alexbishop1 approved these changes
👌

2018-06-26 12:43 UTC, merged