PP-4119 Improve capture queue reporting
alphagov/pay-connector pull request #656
Opened 2018-08-14 13:43 UTC by danworth

Currently we only capture the total size of the charges waiting to be sent to the provider to be processed. However it is more useful to split this into two measures:
- The number of charges eligible to be processed now.
- The number of charges that are within the waiting period to be retried and so are not eligible at that moment.

Therefore the existing `gateway-operations.capture-process.queue-size` metric has been modified to count only charges which can be retried (whilst not applying the configurable batch size limit used by `findChargesForCapture`). A new metric named `gateway-operations.capture-process.waiting-queue-size` has been added to show the charges which are waiting to be retried because they were last attempted within the delay period (this is configurable but currently set to an hour).

As part of this work we have also:
- modified the metric type from `Counter` to `Gauge` which seems more appropriate.
- modified the log message at the end of the capture run to report the number of successful retries and those that failed. This introduces a check on the `GatewayResponse` and a new category in the log message `failed_capture`.

Tests have been added to confirm the registration of the gauges and that they return the correct value.

2018-08-15 13:55 UTC, alexbishop1 requested changes
Left a few comments — there’s only a couple that I think might be actual problems; the rest are really just questions to help me understand what exactly we’re trying to measure here.

I think some of the names (like `countChargesForCapture`, `queueSize` and `waitingQueueSize`) could be renamed to make it clearer what they represent.

2018-08-15 13:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +                ") ";
So this query is intended to find all payments that are in the (conceptual) capture queue (those with statuses of `CAPTURE APPROVED` and `CAPTURE APPROVED RETRY`) except those that have had a failed capture attempt (indicated by a transition to `CAPTURE APPROVED RETRY`) within the last _x_ time units (`notAttemptedWithin`)?

2018-08-15 13:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +                .setParameter("eventStatus", CAPTURE_APPROVED_RETRY)
Because this is only `CAPTURE_APPROVED_RETRY` (and not `CAPTURE_APPROVED`), if one calls this method with a duration of, say, 3 minutes, they will not get payments that have been scheduled for a retry within the last 3 minutes but they will get payments that have been scheduled for a first capture attempt within the last 3 minutes. Is this what you want?

2018-08-15 13:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +                ") ";
Am I right in thinking this finds all payments that are in the (conceptual) capture queue and have had a failed capture attempt within the last _x_ time units?

2018-08-15 13:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +                .setParameter("captureApprovedStatus", CAPTURE_APPROVED.getValue())
I don’t think you need this: if a payment has a `CAPTURE APPROVED RETRY` event, its status cannot be `CAPTURE APPROVED`

2018-08-15 13:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +    public int countChargesForCapture(Duration notAttemptedWithin) {
It looks like this method is very similar to the existing `findChargesForCapture` except it does a count rather returning a list — potential to avoid code duplication?

2018-08-15 13:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CardCaptureProcess.java
> +            queueSize = chargeDao.countChargesForCapture(captureConfig.getRetryFailuresEveryAsJavaDuration());
Due to the similarity between `ChargeDao.countChargesForCapture(Duration)` and `ChargeDao.findChargesForCapture(int, Duration)`, if the number of payments to capture is below `captureConfig.getBatchSize()` then there’s the possibility to wait until we have after `chargesToCapture` has been calculated and use the `size()` of that (obviously this may have performance implications if `captureConfig.getBatchSize()` is significantly smaller).

2018-08-15 13:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CardCaptureProcess.java
> +                logger.info("Capturing : " + chargesToCapture.size() + " of " + waitingQueueSize + " charges");
Not sure this going to say what you want: `waitingQueueSize` isn’t the total number of payments that are in the capture queue period, it’s just those that have had a failed capture attempt within the last `captureConfig.getRetryFailuresEveryAsJavaDuration()`. If I’m understanding it right, the total will be `queueSize + waitingQueueSize`.

2018-08-15 13:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CardCaptureProcess.java
>              Collections.shuffle(chargesToCapture);
We shuffle the payments before capturing them (presumably to stop one that causes a catastrophic error spoiling everyone’s fun every time)? I never knew that!

2018-08-16 08:06 UTC, danworth commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +                ") ";
Correct.

2018-08-16 08:07 UTC, danworth commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +                .setParameter("eventStatus", CAPTURE_APPROVED_RETRY)
Yes, if we have already attempted to capture a charge within the `notAttemptedWithin` period then we do not want to include it in this count. If it's new, `CAPTURE APPROVED` then we should include it, even if it moved to that state within the `notAttemptedWithin`.  Is that what you mean?

2018-08-16 08:07 UTC, danworth commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +                ") ";
Yes, that is the intention.

2018-08-16 08:11 UTC, danworth commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +                .setParameter("captureApprovedStatus", CAPTURE_APPROVED.getValue())
Yes I think you're right. I've removed it and the tests still pass...

2018-08-16 08:13 UTC, danworth commented on src/main/java/uk/gov/pay/connector/service/CardCaptureProcess.java
> +            queueSize = chargeDao.countChargesForCapture(captureConfig.getRetryFailuresEveryAsJavaDuration());
Great idea, I've implemented that logic.

2018-08-16 08:14 UTC, danworth commented on src/main/java/uk/gov/pay/connector/service/CardCaptureProcess.java
> +                logger.info("Capturing : " + chargesToCapture.size() + " of " + waitingQueueSize + " charges");
Yes you are right, thank you! Updated to use the sum of the two counts.

2018-08-16 08:45 UTC, danworth commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +    public int countChargesForCapture(Duration notAttemptedWithin) {
Ok good point, I've factored out the common where clause.

2018-08-16 10:55 UTC, heathd commented
can you squash the 'pseudo code' commit as well?

2018-08-17 09:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +                .setParameter("eventStatus", CAPTURE_APPROVED_RETRY)
Yeah, I mostly just want to make sure we both agree on what the queries are supposed to be doing 😃

2018-08-17 09:26 UTC, alexbishop1 submitted a review, later dismissed

2018-08-20 13:03 UTC, alexbishop1 approved these changes

2018-08-21 08:56 UTC, merged