PP-3840 Allow searching by cardholder name and last digits of card number
alphagov/pay-connector pull request #666
Opened 2018-08-29 10:33 UTC by simad

## WHAT
- Added those query params both in publicapi and in selfservice. 
- Cardholder name will match on partial search, eg. searching for `Jane` will match both `Jane Doe` and `Bob Somejane`, while last digit of card number must be provided in full, as in searching for `12` won't match `1234`

2018-08-29 15:18 UTC, alexbishop1 requested changes
Looks good: just a few small things

2018-08-29 15:18 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +            predicates.add(likePredicate(cb, charge.get(CARD_DETAILS).get("cardHolderName"), params.getCardHolderName().toString().toLowerCase()));
I don’t think we need the `toLowerCase()` here: the `likePredicate(CriteriaBuilder, Path<String>, String)` method will take care of that for us.

Using `.toLowerCase()` is equivalent to`.toLowerCase(Locale.getDefault())`, which is probably equivalent to `.toLowerCase(Locale.ENGLISH)` or `.toLowerCase(Locale.UK)` for us. Due to different languages having different lower-casing rules, this may make the search do interesting things with non-English names. There’s also the issue of it probably being desirable to have “garcia” match “García”. Probably not something we need to address now (this is a complex problem) but worth bearing mind for the future.

2018-08-29 15:18 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/TransactionDao.java
> +        }
Why do we not need something similar for the last four digits?

2018-08-29 15:18 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/dao/TransactionDao.java
> +                .map(ChargeStatus::getValue)
🥇

2018-08-29 15:18 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/CardHolderName.java
> +public class CardHolderName {
😍

2018-08-29 15:18 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/LastDigitsCardNumber.java
> +        this.lastDigitsCardNumber = Objects.requireNonNull(lastDigitsCardNumber);
It would be nice to be able to guarantee that this string contains exactly four digits. Unfortunately, it looks like there’s no validation on the incoming search parameter so this can contain whatever string was entered.

So, open question: could we validate the incoming last four digits search parameter? Would that be a good idea?

2018-08-29 15:18 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/ChargeDaoITest.java
> +        assertCharge("visa", testCharge, charges.get(0));
Surely asserting on the cardholder name would be better?

2018-08-29 15:18 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/ChargeDaoITest.java
> +                .withCardHolderNameLike(CardHolderName.of("pay"));
It might clearer what’s going on if we explicitly set the cardholder name in the fixture, so the fact that the search parameter is a substring is more obvious

2018-08-29 15:18 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceGetChargesJsonITest.java
> +    }
Test for last four digits as well?

2018-08-29 15:49 UTC, simad commented on src/main/java/uk/gov/pay/connector/dao/TransactionDao.java
> +        }
Because we decided not to have that filtering in selfservice :/

2018-08-29 15:49 UTC, simad commented on src/test/java/uk/gov/pay/connector/it/dao/ChargeDaoITest.java
> +        assertCharge("visa", testCharge, charges.get(0));
😳

2018-08-29 15:53 UTC, simad commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +            predicates.add(likePredicate(cb, charge.get(CARD_DETAILS).get("cardHolderName"), params.getCardHolderName().toString().toLowerCase()));
Nicely spotted, didn't think about the locale. It is true, we call the default `toLowerCase()` when escaping the like predicate, so it's something to think about. I have to say we are not doing much about l18n, in general, for obvious reasons.

2018-08-29 15:55 UTC, simad commented on src/main/java/uk/gov/pay/connector/model/LastDigitsCardNumber.java
> +        this.lastDigitsCardNumber = Objects.requireNonNull(lastDigitsCardNumber);
I originally had added that validation in this class, checking both that it's 4 digits and that it's fully numeric. I was throwing an exception in the `.of()` method if those criteria were not met. Thing is, we either return a bad response or we do something nasty (ie. return a default) - considering we are not validating any query param and the default would probably simply not ever match, I've decided to leave it like this, as it won't match anything unless it's 4 valid digits anyway

2018-08-29 16:16 UTC, simad commented on src/test/java/uk/gov/pay/connector/it/dao/ChargeDaoITest.java
> +                .withCardHolderNameLike(CardHolderName.of("pay"));
👍

2018-08-29 16:16 UTC, simad commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceGetChargesJsonITest.java
> +    }
👍

2018-08-29 16:23 UTC, simad commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +            predicates.add(likePredicate(cb, charge.get(CARD_DETAILS).get("cardHolderName"), params.getCardHolderName().toString().toLowerCase()));
Also if somebody is called “García”, that's his problem @rauligs

2018-08-29 17:35 UTC, rauligs commented on src/main/java/uk/gov/pay/connector/dao/ChargeDao.java
> +            predicates.add(likePredicate(cb, charge.get(CARD_DETAILS).get("cardHolderName"), params.getCardHolderName().toString().toLowerCase()));
I promise I won't use accents! 🤐

2018-08-29 17:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/LastDigitsCardNumber.java
> +        this.lastDigitsCardNumber = Objects.requireNonNull(lastDigitsCardNumber);
In theory, we could validate it to check it’s four digits (and do we do validate things like date formats).

I’ll be sad if we ever up in the situation where we’re using the `LastDigitsCardNumber` to represent something that we _know_ is exactly four digits and we’re unable to enforce that, but I suppose we could always split it into two objects then (one representing the search parameter and the other a confirmed valid value).

2018-08-30 08:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceGetChargesJsonITest.java
> +    }
Sorry, I meant here to have another test to check filtering by the last four digits

2018-08-30 08:47 UTC, alexbishop1 requested changes
Thanks for making the changes.

I still think `ChargesApiResourceGetChargesJsonITest` should have a test to check filtering by the last four digits, but other than I think it’s good to go.

2018-08-30 09:11 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceGetChargesJsonITest.java
> +    }
Whoops! This tests the transactions endpoint, which is only used by selfservice so doesn’t need to support searching for the last four digits.

2018-08-30 09:13 UTC, alexbishop1 approved these changes
I was mistaken about `ChargesApiResourceGetChargesJsonITest`: it tests the transactions endpoint, which is only used by selfservice so doesn’t need to support searching for the last four digits

2018-08-30 09:15 UTC, merged