Pp 4165 create capture resource
alphagov/pay-connector pull request #693
Opened 2018-09-11 14:55 UTC by georgeracu

## WHAT

* Added a new POST resource in `CardResource` that will be called on
`"/v1/api/accounts/{accountId}/charges/{chargeId}/capture"` when a service
will want to mark a delayed charge as `CAPTURE APPROVED`.

* When a charge is in status `AWAITING CAPTURE REQUEST` then we transition
to status `CAPTURE APPROVED`, we record an event and we return 204

* When a charge is in statuses `CAPTURED, CAPTURE APPROVED,
CAPTURE APPROVED RETRY, CAPTURE READY, CAPTURE SUBMITTED` then we
do not transition and we return 204

* When a charge is in a status that cannot transition to (none of the above)
then we return 409

* When a charge it doesn't exist then we return 404

* Updated documentation

with @danworth

2018-09-12 12:55 UTC, SandorArpa requested changes

2018-09-12 12:55 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/service/CardCaptureService.java
> +    ));
Fully understand why we're using Set but for the sake of consistency within a class I suggest to change `List<ChargeStatus> legalStatuses` to a Set as well

2018-09-12 12:58 UTC, danworth commented on src/main/java/uk/gov/pay/connector/service/CardCaptureService.java
> +    ));
Great idea, will do!

2018-09-13 09:22 UTC, SandorArpa approved these changes
LOKTM

2018-09-13 09:43 UTC, merged