Pp 4113 basic get refunds endpoint
alphagov/pay-connector pull request #696
Opened 2018-09-13 09:46 UTC by cobainc0

## WHAT
_A brief description of the pull request:_
Adds new Refunds endpoint & Pact tests
## HOW 
_Steps to test or reproduce:_
pact tests refundsExist and noRefundsExist

2018-09-24 14:18 UTC, simad requested changes
Good work. Quite a few comments to address, but looks promising!

2018-09-24 14:18 UTC, simad commented on src/main/java/uk/gov/pay/connector/dao/RefundDao.java
> +        CriteriaQuery<RefundEntity> cq = cb.createQuery(RefundEntity.class);
I can see this DAO being generalised because it's basically the same as the ChargeDao, but marshalling to RefundEntity rather than ChargeEntity. But it's an improvement which can be done as part of another PR. 👍 for now

2018-09-24 14:18 UTC, simad commented on src/main/java/uk/gov/pay/connector/service/SearchRefundsService.java
> +                    ChargeSearchParams searchParams = new ChargeSearchParams()
`ChargeSearchParams` is not really related to charge anymore. Could rename simply to `SearchParams` or something along those lines

2018-09-24 14:18 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/ChargesPaginationResponseBuilder.java
> -    public ChargesPaginationResponseBuilder withChargeResponses(List<ChargeResponse> chargeResponses) {
We are generifying (which is probably not a real word, but 🤷‍♀️ ) the builder so that it's not Charge specific anymore. It should probably be renamed to `PaginationResponseBuilder` or something like that

2018-09-24 14:18 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/ChargesPaginationResponseBuilder.java
> -    public ChargesPaginationResponseBuilder withChargeResponses(List<ChargeResponse> chargeResponses) {
Same for `chargeResponses`

2018-09-24 14:18 UTC, simad commented on src/main/java/uk/gov/pay/connector/service/SearchRefundsService.java
> +    private Response search(ChargeSearchParams searchParams, UriInfo uriInfo) {
This is duplicating `AbstractSearchStrategy`. This is not really great because we introduce two places where the same logic is stored, so two places to change, we need to add tests etc. etc.


You can implement a RefundSearchStrategy which extends `AbstractSearchStrategy`. 
It seems you can get rid of `  private final CardTypeDao cardTypeDao;` and remove the card type from `abstract protected R buildResponse(UriInfo uriInfo, T transaction);`.
The abstract search strategy will have two types, T and R. R is `ChargeResponse` or `SearchRefundsResponse`, depending on the search strategy.

This is the first way that came to my mind for avoiding duplication. Let me know if you need help refactoring this.

2018-09-24 14:18 UTC, simad commented on src/main/java/uk/gov/pay/connector/service/SearchRefundsService.java
> +    private static Optional<List> validateQueryParams(List<Pair<String, Long>> nonNegativePairMap) {
In general, `Optional<List>` makes _never_ sense. If you return a List of errors, the list is either empty (meaning no error) or full (meaning there are errors). You don't need to represent that via an optional.

2018-09-24 14:18 UTC, simad commented on src/main/java/uk/gov/pay/connector/service/SearchRefundsService.java
> +            invalidResponse.addAll(invalidQueryParams.keySet()
you don't need to addAll, you can just map directly. Ie. it should be possible to do
```
List<String> bla = invalidQueryParams.keySet().stream()
                    .map(param -> String.format(invalidQueryParams.get(param), param))
                    .collect(Collectors.toList())

```

2018-09-25 16:46 UTC, cobainc0 commented on src/main/java/uk/gov/pay/connector/service/SearchRefundsService.java
> +    private Response search(ChargeSearchParams searchParams, UriInfo uriInfo) {
Thanks. This is very informative.

2018-09-25 16:46 UTC, cobainc0 commented on src/main/java/uk/gov/pay/connector/resources/ChargesPaginationResponseBuilder.java
> -    public ChargesPaginationResponseBuilder withChargeResponses(List<ChargeResponse> chargeResponses) {
Sounds like a word to me.

2018-09-26 12:17 UTC, simad approved these changes

2018-09-26 12:17 UTC, simad commented
There is a test which should be removed and moved to a new package. Happy to approve for now and do that later. 👍

2018-09-26 12:24 UTC, merged