Pp 4111 email refund
alphagov/pay-connector pull request #703
Opened 2018-09-18 09:01 UTC by simad

## WHAT
 - Adding type to email notifications, to distinguish between refund and confirmation
 - A gateway account can now have multiple notifications (at least two)
 - Made the patch endpoint modify both `template_body` and `enabled` of a notification, so that
   the post endpoint can be made redundant and removed once selfservice is merged
 - Email notifications is now serialised as part of the gateway account object, this removes
   the need to the email notifications dao which will be removed once the `GET` email notification
   endpoint will be removed

2018-09-24 14:22 UTC, alexbishop1 requested changes
I’ve left a few comments. Also, I expect some connector internal API docs need to updated to reflect the changes here.

It’s a bit late for this now but in the future, could you please try to split features like this into a series of smaller PRs? For example, this could have been a PR to make it so that email notifications are serialised as part of the gateway account, then a PR to change the model so a gateway account can have a separate refund email associated with it, then a PR to make the changes to the email notification endpoint to allow it to be used to configure the refund email, and finally a PR to actually send the refund email.

Going further, even small changes with ripple effects (especially in tests) like renaming `GatewayAccountRequest` to `PatchRequest` and changing `RequestValidator` to use empty lists rather than empty optionals could have each been their own PRs.

I don’t need to tell you the benefits of small PRs but I think I would have found this much easier to review if it was actually several smaller things. Keeping track of all the different aspects being modified (especially when they’re by necessity interleaved across different files and it’s not always immediately clear which aspect a particular change relates to) can make my head hurt and I find it trickier to do things like ensure test coverage is being maintained when there’s so much going on. I wasn’t actually able to review this as well as I would have liked, whereas with small PRs I would have been able to focus on each individual bit more thoroughly.

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ConnectorApp.java
> +        environment.jersey().register(new ValidationExceptionMapper());
Is this our first use of exception mappers in connector? The inconsistency troubles me a bit but if we do generally want to move to using exception mappers (like we do in Direct Debit connector) then I guess we have to start somewhere…

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/EmailCollectionMode.java
> +            return EmailCollectionMode.valueOf(mode.toUpperCase());
I don’t think we need to bother supporting lower-case variants of the names — it’s just additional complexity that we may end up supporting forever for no real good reason

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/GatewayAccount.java
> +    public static final String FIELD_NOTIFY_REFUND_ISSUED_TEMPLATE_ID = "refund_issued_template_id";
No we have `FIELD_NOTIFY_REFUND_ISSUED_TEMPLATE_ID`, is `FIELD_NOTIFY_TEMPLATE_ID` only applicable to payment confirmation emails? Should we rename it?

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/GatewayAccountEntity.java
> +    public Map<String, Object> withoutCredentials() {
The generic type parameter being changed to a wider type (`Object`) makes me sad, but the ultimate cause of my sadness is serialising JSON from a map, so let’s leave it for now and try to rationalise how we serialise gateway accounts (at least four different ways, by my count) later.

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/EmailCollectionMode.java
> +    MANDATORY, OPTIONAL, OFF;
I wonder about trying to make this names more explicit (at the expense of brevity). Something like `USER_MUST_ENTER_EMAIL`, `USER_MAY_ENTER_EMAIL_BUT_NOT_REQUIRED`, `USER_NOT_ASKED_FOR_EMAIL`.

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +                                    Arrays.asList(EMAIL_NOTIFICATION_ENABLED, EMAIL_NOTIFICATION_TEMPLATE_BODY)))
It took me longer than I care admit to figure out what we list we end up with here. Since it’s just five static strings, it might be more straightforward to just whack them into a list and have it as a static field (though actually a set would probably be more appropriate).

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +                    Pair<EmailNotificationType, String> patchInfo = getNotificationTypeFromPath(emailPatchRequest);
Not generally a huge fan of `Pair`: I’d almost prefer to use an inner class so we can name the two fields within it

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +                    EmailNotificationType type = patchInfo.getLeft();
Could you also assign `patchInfo.getRight()` to a local variable here please? I’ve forgotten what it is by the time I get to the `patch(…)` call

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +                            });
Could you yank this block out into a private method called `newDisabledEmailNotificationEntityWithNoTemplate()` or something? It took a while to figure out the intent of this

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +        String[] paths = emailPatchRequest.getPath().split("/");
It feels like tokenising the path should be something the `PatchRequest` should be able to do

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +        if (paths.length < 2) {
Doesn’t the slash at the beginning mean there will usually be three items?

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +            return Pair.of(EmailNotificationType.PAYMENT_CONFIRMED, "enabled");
If this gets out of sync with the validation, we’ll end up assuming anything without a slash means enable payment confirmation emails, which is terrifying, but I’m OK if this is temporary

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +    private void patch(EmailNotificationEntity emailNotificationEntity, String attribute, PatchRequestBuilder.PatchRequest emailPatchRequest) {
It feels a bit wrong that this needs the `attribute` when it also has the `emailPatchRequest` that it’s parsed out of: I think either nothing should be parsed before calling this method, or everything this method needs should be parsed, not half and half

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +        }
It feels like the resource isn’t the right place to be doing this (though I appreciate that this resource is already very heavy). Eventually we probably want to have a generic `JsonPatchService` or something.

Overall, I found the changes in this class very hard to follow. I think it might be clearer if the body first gets parsed into a `PatchRequest`, then the `PatchRequest` is processed to produce an object whose type represents the change (e.g. `EnableEmailNotificationRequest`, `ReplaceEmailTemplateBodyRequest` etc.) and whose fields represent the appropriate values. This would then be passed to a service to apply the actual change.

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +    //PP-4111 backward compatibility, remove once selfservice is merged
Why is there so much new functionality added to this method if the entire method is going to be removed soon?

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        }
So this means we are not doing any validation on requests with a `"path:" "email_collection_mode"`?

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +            if(null == valueNode) {
I know this was already like this but it’s possible this could be a `NullNode`

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountResource.java
> +        entity.addNotification(EmailNotificationType.PAYMENT_CONFIRMED, new EmailNotificationEntity(entity));
Why wasn’t this needed before?

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/NotificationService.java
> +    private UserNotificationService userNotificationService;
This can be `final`

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/NotificationService.java
> +                userNotificationService.sendRefundIssuedEmail(refundEntity);
This means that the email will be sent only when the notification saying the payment has been refunded has received. I thought the requirement was to send it when the button was pressed (which may be hours or even days earlier).

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> +        Boolean isEmailEnabled = Optional.ofNullable(chargeEntity.getGatewayAccount().
This `Boolean` can be a primitive; it doesn’t need to be boxed

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> +                .orElse(false);
It took me a little bit of time to figure out what the `Optional.ofNullable(…)` is wrapping. Perhaps the linebreaks could be altered to make it clearer:

```java
boolean isEmailEnabled = Optional.ofNullable(chargeEntity.getGatewayAccount().getEmailNotifications().get(emailNotificationType))
    .map(EmailNotificationEntity::isEnabled)
    .orElse(false);
```

Alternatively, this could be moved out into its own method, which could take the luxury of intermediate local variables etc. to show what’s going on.

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> -                && !isBlank(notifySettings.get("api_token"))
Are we not worried about this any more?

2018-09-24 14:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> +    private String getTemplateIdFor(EmailNotificationType type) {
So we have `getCustomTemplate(…)` and `getTemplateIdFor(…)`, both of which switch on the `EmailNotificationType`. Could we somehow encapsulate the two strings into a single object? Or maybe just inline this last one into `getNotifyClientSettings(…)`:

```java
switch (emailNotificationType){
    case REFUND_ISSUED:
        Pair.of(notifyClientFactory.getInstance(), refundIssuedEmailTemplateId);
    case PAYMENT_CONFIRMED:
        return Pair.of(notifyClientFactory.getInstance(), confirmationEmailTemplateId);
}
```

2018-09-24 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/EmailNotificationResourceITest.java
> +    public void patchEnableNotification_shouldUpdateSuccessfully() {
This is now testing disabling email notifications now, right? (Which I assume is because the default is to have them enabled. We may want to make explicitly enable/disable email notifications when setting up the test account fixture.)

2018-09-24 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/EmailNotificationResourceITest.java
> +        assertThat(confirmationEmail.get("enabled"), is(true));
Why are we also checking the payment confirmed emails are enabled here? Is it just to check that toggling the refund emails doesn’t have any effect on the payment confirmation emails?

2018-09-24 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/EmailNotificationResourceITest.java
> +        assertThat(confirmationEmail.get("template_body"), is("Lorem ipsum dolor sit amet, consectetur adipiscing elit."));
It’s not immediately clear where this _lorem ipsum_ comes from. If we’re checking that it hasn’t changed, we might want to either explicitly set this test up in the fixture or grab the current value in a local variable before the request is made and then compare the new value to that one.

2018-09-24 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/EmailNotificationResourceITest.java
> +    public void patchTemplateBodyNotification_shouldUpdateSuccessfullyNotificationIfMissing() {
Can this be named in such a way that it makes it clear it creates the notification configuration if it‘s “missing”?

2018-09-24 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITest.java
> +                .statusCode(INTERNAL_SERVER_ERROR.getStatusCode());
Hmm, feels like this should be a 4xx error because there was a problem with the request…

2018-09-24 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidatorTest.java
> +import static junit.framework.TestCase.fail;
Please use `org.junit.Assert.fail`

2018-09-24 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/GatewayAccountUpdaterTest.java
> +        verify(entity, times(1)).setEmailCollectionMode(EmailCollectionMode.OFF);
Don’t need `times(1)` (it’s the default)

2018-09-24 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/GatewayAccountUpdaterTest.java
> +        verify(gatewayAccountDao, times(1)).merge(entity);
Verifying that the above two lines are called in order would be useful here

2018-09-24 14:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/UserNotificationServiceTest.java
> +        when(mockNotifyClient.sendEmail(any(), any(), any(), any())).thenReturn(mockNotificationCreatedResponse);
I know this is just copied from an existing test but we can usually do better than a bunch of `any()`s

2018-09-25 08:49 UTC, simad commented on src/main/java/uk/gov/pay/connector/app/ConnectorApp.java
> +        environment.jersey().register(new ValidationExceptionMapper());
Yes it is. We should definitely move there and this was a good place to start, I think.

2018-09-25 08:51 UTC, simad commented on src/main/java/uk/gov/pay/connector/model/domain/EmailCollectionMode.java
> +            return EmailCollectionMode.valueOf(mode.toUpperCase());
It's a pretty safe check we have almost in every enum. I think it solved a few headdaches so that people can write slightly better js code on the frontend side. If you don't feel strongly about it, I'd keep it, otherwise I'll kill it with fire

2018-09-25 08:51 UTC, simad commented on src/main/java/uk/gov/pay/connector/model/domain/GatewayAccount.java
> +    public static final String FIELD_NOTIFY_REFUND_ISSUED_TEMPLATE_ID = "refund_issued_template_id";
yes it is, I'll leave the variable "template_id" as it is but I'll rename the field 👍

2018-09-25 08:53 UTC, simad commented on src/main/java/uk/gov/pay/connector/model/domain/GatewayAccountEntity.java
> +    public Map<String, Object> withoutCredentials() {
yes, indeed :) usually when there is Object somewhere I consider it a code smell, but as you said it's the expression of a broader problem (using plain maps to serialise json). We definitely have to refactor the GatewayAccount handling, it's a mess right now

2018-09-25 08:55 UTC, simad commented on src/main/java/uk/gov/pay/connector/model/domain/EmailCollectionMode.java
> +    MANDATORY, OPTIONAL, OFF;
I find the terse ones pretty clear - but maybe because I've discussed about them in ACs and at kickoff etc. Do you think we should go for the longer ones?

2018-09-25 08:56 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +                                    Arrays.asList(EMAIL_NOTIFICATION_ENABLED, EMAIL_NOTIFICATION_TEMPLATE_BODY)))
👍

2018-09-25 09:12 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +                    Pair<EmailNotificationType, String> patchInfo = getNotificationTypeFromPath(emailPatchRequest);
agreed! I didn't add to add more bulk to this. Will do it now

2018-09-25 09:35 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +                            });
👍 I added a comment but it's always better to do it through the code

2018-09-25 09:35 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +                    EmailNotificationType type = patchInfo.getLeft();
done with the inner class

2018-09-25 09:42 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +            return Pair.of(EmailNotificationType.PAYMENT_CONFIRMED, "enabled");
yes this will be removed as soon as selfservice is in

2018-09-25 10:42 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +    private void patch(EmailNotificationEntity emailNotificationEntity, String attribute, PatchRequestBuilder.PatchRequest emailPatchRequest) {
Agreed. I wanted to do a broader refactoring of this whole logic, ie. separate completely the handling of a Patch request (which should be generic). and the specific handling of a patch email notification. It would've taken too long and made the PR even bigger than what it already is, so I decided to make it work and do tiny bits of refactoring

2018-09-25 10:42 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +        }
Ideally, that would be the case. Resources in connector are super heavy unfortunately. See comment above

2018-09-25 10:45 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +    //PP-4111 backward compatibility, remove once selfservice is merged
because it's a lie, it was meant for the `POST` endpoint above 😳

2018-09-25 10:50 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        }
This whole validation is a bit twisted :( will try to make a small change to introduce email collection validation, but it needs a broader refactoring

2018-09-25 11:02 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        }
Done, the whole `GatewayAccountRequestValidator` needs to be refactored. It is mixing up gateway account specific logic (ie. notify settings and so on) and generic patch validation. We should definitely split these responsibilities.

2018-09-25 11:03 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +            if(null == valueNode) {
this makes me sad

2018-09-25 11:04 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountResource.java
> +        entity.addNotification(EmailNotificationType.PAYMENT_CONFIRMED, new EmailNotificationEntity(entity));
because sadly it was done by overriding the persist method of the entity

2018-09-25 11:04 UTC, simad commented on src/main/java/uk/gov/pay/connector/service/NotificationService.java
> +    private UserNotificationService userNotificationService;
👍

2018-09-25 11:17 UTC, simad commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> +        Boolean isEmailEnabled = Optional.ofNullable(chargeEntity.getGatewayAccount().
oopsie

2018-09-25 11:17 UTC, simad commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> +                .orElse(false);
but `map()`

2018-09-25 11:18 UTC, simad commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> -                && !isBlank(notifySettings.get("api_token"))
I want to refactor everything :(

2018-09-25 11:32 UTC, simad commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> +    private String getTemplateIdFor(EmailNotificationType type) {
yes :) sorry to point out again that it needs a broader refactoring - I want to introduce an object for notify settings (instead of plain map) and that will contain some logic to discern whether to use custom branding or not etc. etc. will do it next

2018-09-25 12:21 UTC, simad commented on src/test/java/uk/gov/pay/connector/it/resources/GatewayAccountResourceITest.java
> +                .statusCode(INTERNAL_SERVER_ERROR.getStatusCode());
Yes, added that in the validation

2018-09-25 12:21 UTC, simad commented on src/test/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidatorTest.java
> +import static junit.framework.TestCase.fail;
oops, my bad

2018-09-25 12:21 UTC, simad commented on src/test/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidatorTest.java
> +import static junit.framework.TestCase.fail;
didn't spot that

2018-09-25 12:21 UTC, simad commented on src/test/java/uk/gov/pay/connector/service/GatewayAccountUpdaterTest.java
> +        verify(entity, times(1)).setEmailCollectionMode(EmailCollectionMode.OFF);
I just copied things \o/

2018-09-25 12:23 UTC, simad commented on src/test/java/uk/gov/pay/connector/service/GatewayAccountUpdaterTest.java
> +        verify(gatewayAccountDao, times(1)).merge(entity);
👍

2018-09-25 12:24 UTC, simad commented on src/test/java/uk/gov/pay/connector/service/UserNotificationServiceTest.java
> +        when(mockNotifyClient.sendEmail(any(), any(), any(), any())).thenReturn(mockNotificationCreatedResponse);
shit, I usually replace that but this time I didn't spot it, sorry

2018-09-25 13:44 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/EmailCollectionMode.java
> +            return EmailCollectionMode.valueOf(mode.toUpperCase());
It’s not the hill I’m going to die on but when it comes to accepting computer-generated input (as opposed to user-generated input), I think it’s fine to be fairly restrictive. It’s shouldn’t be too onerous for someone working on another microservice to use the canonical case.

(Also, converting to upper-case has some interesting subtleties: `toUpperCase()` can actually give different results depending on the default locale of the system the JVM is running on, with interesting consequences like `str.toUpperCase().toLowerCase()` not necessarily returning something equal to the original string etc.)

2018-09-25 13:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/EmailCollectionMode.java
> +    MANDATORY, OPTIONAL, OFF;
I’m happy for you to decide. I don’t think the terse ones are bad by any means. The appeal to me of more explicit names is that they are more self-describing, particularly when encountered out of context (imagine I just came across `OFF` but didn’t know the name of the enum or the other variants). The disadvantage is that they tend to be longer but this may not be an issue if they’re only used in a few places.

2018-09-25 13:55 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> +                .orElse(false);
I don’t follow.

By moving it out to its own method, I meant there could be a method like this:

```java
private boolean isEmailEnbled(GatewayAccountEntity gatewayAccount, EmailNotificationType emailNotificationType) {
    EmailNotificationEntity emailNotification = gatewayAccount.getEmailNotifications().get(emailNotificationType);
    return Optional.ofNullable(emailNotification).map(EmailNotificationEntity::isEnabled).orElse(false); // or even just emailNotification != null ? emailNotification.isEnabled() : false;
```

… which could then be used like this:

```java
boolean isEmailEnabled = isEmailEnabled(chargeEntity.getGatewayAccount(), emailNotificationType);
```

2018-09-26 15:23 UTC, alexbishop1 requested changes
This is getting fairly close. I’ve left a few comments. There’s also still some unaddressed ones from my first review, which you might want to look at again (none of them are show-stoppers: I’ve left new comments on this round for the ones I’m more concerned about).

2018-09-26 15:23 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/builder/PatchRequestBuilder.java
> +            return asList(path.substring(1).split("/"));
I assume the `substring(1)` is to skip the leading `/`. Can we be sure this will always be there? I think I’d feel more confident if it was something like `Arrays.stream(path.split("/")).skip(1).collect(Collectors.toList())`, which won’t blow up if it isn’t.

2018-09-26 15:23 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +    private NotificationPatchInfo getNotificationTypeFromPath(PatchRequestBuilder.PatchRequest emailPatchRequest) {
This method gets more than just the notification type so probably wants to be renamed

2018-09-26 15:23 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +        private String value;
`final`!

2018-09-26 15:23 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountRequestValidator.java
> +        if (path.equalsIgnoreCase(FIELD_NOTIFY_SETTINGS)) {
Not convinced by the need to do a case-insensitive comparison here but I’ll leave that up to you

2018-09-26 15:23 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> -                && !isBlank(notifySettings.get("api_token"))
Refactoring is good but as it stands, some validation is being removed. I’m not sure we want to do that.

2018-09-26 16:04 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +        private String value;
owwwww 👍 sorry

2018-09-26 16:06 UTC, simad commented on src/main/java/uk/gov/pay/connector/resources/EmailNotificationResource.java
> +    private NotificationPatchInfo getNotificationTypeFromPath(PatchRequestBuilder.PatchRequest emailPatchRequest) {
👍

2018-09-26 16:07 UTC, simad commented on src/main/java/uk/gov/pay/connector/model/builder/PatchRequestBuilder.java
> +            return asList(path.substring(1).split("/"));
ideally i'd like to throw an exception if the patch is malformed rather than making sure things don't blow up. I'll see if I can do that without making too many changes

2018-09-26 16:10 UTC, simad commented on src/main/java/uk/gov/pay/connector/model/builder/PatchRequestBuilder.java
> +            return asList(path.substring(1).split("/"));
there is the `isValidPath()` function but I can't make it throw on malformed (as in missing /) patches because it wouldn't work with existing code. Will make the change you suggested and flag it for improvement

2018-09-27 10:27 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/UserNotificationService.java
> -                && !isBlank(notifySettings.get("api_token"))
Oh, I see, the validation has been just moved further down into the new `NotifyClientSettings` inner class

2018-09-27 10:32 UTC, alexbishop1 approved these changes
Most of my most pressing concerns have been addressed so I’m approving.

Hopefully, your forthcoming clean-up and the removal of the legacy endpoints when selfservice has been updated will make this even better.

2018-09-27 11:33 UTC, merged