PP-4139 Add first_digits_card_number column to charge tables
alphagov/pay-connector pull request #704
Opened 2018-09-19 10:29 UTC by simad

## WHAT
 - Also, indexing using GIN (hic) on both that column and on the last 4 digits, which seemed to have escaped the previous story

2018-09-19 12:00 UTC, alexbishop1 requested changes
SQL (or XML that will become SQL) looks great but I don’t think the names are quite right

2018-09-19 12:00 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +    <changeSet id="add trigram index to charges.last_digits_card_number" runInTransaction="false" author="">
This isn’t a trigram index, is it?

2018-09-19 12:00 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +            CREATE INDEX CONCURRENTLY idx_last_digits_card_number_idx ON charges(last_digits_card_number);
Not sure we need `idx` at the beginning and the end!

2018-09-19 12:55 UTC, simad commented on src/main/resources/migrations.xml
> +    <changeSet id="add trigram index to charges.last_digits_card_number" runInTransaction="false" author="">
righto, I had it as trigram but removed it and forgot to rename the  rest xD

2018-09-19 15:48 UTC, alexbishop1 approved these changes

2018-09-19 15:50 UTC, merged

2018-10-08 09:51 UTC, DanailMinchev commented on src/main/resources/migrations.xml
> +            CREATE INDEX CONCURRENTLY idx_last_digits_card_number_idx ON charges(last_digits_card_number);
I guess this comment was not addressed, because we use `idx` at the beginning and the end as a convention for other indexes

2018-10-08 09:55 UTC, alexbishop1 commented on src/main/resources/migrations.xml
> +            CREATE INDEX CONCURRENTLY idx_last_digits_card_number_idx ON charges(last_digits_card_number);
We actually seem to be inconsistent. It’s a little redundant but I guess it doesn’t matter in the grand scheme of things.