PP-4139 Retrieve first six digits of credit card from the db
alphagov/pay-connector pull request #705
Opened 2018-09-19 15:52 UTC by simad

## WHAT
This PR simply makes sure we can retrieve the six digits from the db, and it is returned to the frontend charge response similarly to how's done for last 4 digits. Next PR(s) will expand this one, adding search and probably refactoring the domain objects in attempt to find a saner way through connector.

2018-09-20 09:40 UTC, alexbishop1 requested changes
Looks good! Just a few comments

2018-09-20 09:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/FirstDigitsCardNumber.java
> +        this.firstDigitsCardNumber = Objects.requireNonNull(firstDigitsCardNumber);
Can we guarantee if this object is instantiated, it will always be six digits? If so, can we validate it with a regex (like we do for `SortCode` in Direct Debit connector)? It would be really nice to enforce this from outset — if it gets too widely used, our future selves may be too scared to change it later.

2018-09-20 09:40 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/FirstDigitsCardNumber.java
> +        return String.valueOf(firstDigitsCardNumber);
`firstDigitsCardNumber` is already a `String`

2018-09-20 09:40 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/DatabaseFixtures.java
> +            databaseTestHelper.updateChargeCardDetails(chargeId, cardBrand, lastDigitsCardNumber, firstDigitsCardNumber,cardHolderName, expiryDate, billingAddress.getLine1(), billingAddress.getLine2(
Missing space after comma

2018-09-20 09:57 UTC, simad commented on src/main/java/uk/gov/pay/connector/model/FirstDigitsCardNumber.java
> +        this.firstDigitsCardNumber = Objects.requireNonNull(firstDigitsCardNumber);
I am doing that as part of the next PR which introduces searching for first digits. I will try to validate both last and first digits in a sane way.

2018-09-20 09:57 UTC, simad commented on src/main/java/uk/gov/pay/connector/model/FirstDigitsCardNumber.java
> +        return String.valueOf(firstDigitsCardNumber);
rightO

2018-09-20 11:05 UTC, alexbishop1 submitted a review, later dismissed

2018-09-21 09:01 UTC, alexbishop1 approved these changes

2018-09-21 09:08 UTC, merged