PP-4126 Add corporate surcharge and total amount
alphagov/pay-connector pull request #713
Opened 2018-09-26 14:03 UTC by georgeracu

## WHAT

- Added fields `corporate_card` and `card_type` to request object `AuthCardDetails`
- `corporate_card` will map to `Boolean` and `card_type` to two possible values
`CREDIT` and `DEBIT` from `CardTypeEntity.Type`
- Added `totalAmount` to `ChargeEntity` which defaults to `amount` if no `corporateSurcharge`
- Added `corporateSurcharge` and `totalAmount` to `ChargeResponse`
- Added `corporateSurcharge` and `totalAmount` to `FrontendChargeResponse`
- Added `corporateSurcharge` and `totalAmount` to `TransactionResponse`
- Updated `CardAuthoriseService` to add corporate surcharge when authorisation required for
corporate card. This will check the type of the card and will set a surcharge based on the
values set int th gateway account for that given charge
- Corporate surcharge and total amount will be added to the response object only if
corporate surcharge is present, otherwise none will be put in the response
- Extracted test string values to constants
- Renamed method from `getTransactions` to `getCharges` as we don't have a concept
of `Transaction` anymore
- Removed duplicate field declaration
- Added tests for new functionality

with @SandorArpa

2018-09-27 16:19 UTC, alexbishop1 requested changes
Implementation looks good in general. Left a few suggestions.

I’m not convinced this will correctly include the corporate surcharge in payments returned from the `v1/api/accounts/ACCOUNT_ID/transactions` endpoint. I remember getting this working being quite involved. See https://github.com/alphagov/pay-connector/pull/673/files (where we did a similar thing for `"delayed_capture"` and look at the `Transaction` class and friends.

Not sure about renaming the methods in `RestAssured` client for reasons explained in the comment attached to that class.

Finally (too late for this now), this could have been done as two separate PRs: one to persist the surcharge to the charge entity and another to include it in the responses.

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/CardType.java
> +public enum CardType {
I wonder if there’s a way we could name this to make the distinction with the “other” card type clearer. `IdentifiedCardType` or `CardTypeUsedToMakePayment` or something?

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/CardTypeEntity.java
>      public enum Type {
Again, maybe we could call this something like `SupportedCardType`

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/ChargeService.java
> +        if (chargeEntity.getCorporateSurcharge() != null) {
How hard would it be to make `ChargeEntity.getCorporateSurcharge()` return an `Optional<Long>`? As well as allowing us to use a beautiful `ifPresent(…)` here, it would also make it more obvious that it’s not always set.

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +public interface CorporateSurchargeCalculator {
I think I’d prefer it if this was just a regular class that’s injected where it’s needed. Being injected would mean it could be mocked in tests (probably not an issue here because it’s basically just adding two numbers).

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +     */
I think it’s pretty clear from the code what this method does; I don’t think we really need the comment

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +        if (corporateCard != null && corporateCard) {
We could make the `authCardDetails.isCorporateCard()` method just return `false` if the `Boolean` is `null` so we don’t have to care about that possibility here. I don’t think we have any real reason to distinguish between frontend telling us the card isn’t corporate or not telling us anything at all.

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +            if (cardType != null) {
Again, there’s possibly an argument for defaulting this to `CREDIT_OR_DEBIT` rather than returning `null` (though I’m less sold on this than I am with having `corporateCard` default to `false`)

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +                if (cardType.equals(CardType.CREDIT) && gatewayAccount.getCorporateCreditCardSurchargeAmount() > 0) {
I was pondering if we do something clever with the enum here. Imagine there was a method on `GatewayAccountEntity` called `getCorporateSurchargeAmount(CardType)`, taking a `CardType` as its argument and returning the appropriate surcharge (which could be a simple `switch` statement). This method would just need to do:

 ```java
if (gatewayAccount.getCorporateSurchargeAmount(cardType) > 0) {
   // …
} // No need for an else if block!
```

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +                    chargeEntity.setCorporateSurcharge(gatewayAccount.getCorporateDebitCardSurchargeAmount());
Rather than modifying the entity directly, this method could return the result as either a `long` (with a possible zero value) or an `Optional<Long>`. Then the caller could be responsible for modifying the `ChargeEntity`. That would make this method pure.

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +     */
Again, not sure the comment is really necessary

2018-09-27 16:19 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +        if (charge.getCorporateSurcharge() != null && charge.getCorporateSurcharge() > 0) {
The part after the `&&` can be removed without affecting the result

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/base/ChargingITestBase.java
> +    private static final String CARD_HOLDER_NAME = "Scrooge McDuck";
We should use this in all our tests!

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceITest.java
> +    private static final Long AMOUNT = 6234L;
Unclear if this actually needed to be changed

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceITest.java
> +                .getCharges()
This makes the test call a different endpoint `/v1/api/accounts/{accountId}/charges` rather than `/v1/api/accounts/{accountId}/transactions`. I don’t think we want that.

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceITest.java
> +    }
Do we need versions of this test that check the other endpoints in the `ChargesApiResource` class (for there is a plethora)?

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesFrontendResourceITest.java
> +        ValidatableResponse response = connectorRestApi.withHeader(HttpHeaders.ACCEPT, APPLICATION_JSON).getCharges();
I’m not sure why this has been changed

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/TransactionsApiResourceITest.java
> +                .getCharges()
Going by the name, I assume the `TransactionsApiResourceITest` is intended to test the `getTransactions()` endpoint, not the `getCharges()` one

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/worldpay/WorldpayCardResourceITest.java
> +    public void shouldAuthoriseChargeWithoutCorporateCard_ForValidAuthorisationDetails() {
Once frontend is always sending `"corporate_card"` and friends, we can probably remove this test

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeServiceTest.java
> +    public void shouldFindChargeForChargeIdWhenChargeStatusIsAuthorisationReady_andCorporateSurcharge() {
I think `AuthorisationReady` can be removed from the name of this test: it’s not essential to what’s being tested

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeServiceTest.java
> +        ChargeResponseBuilder chargeResponseWithoutCorporateSurcharge = chargeResponseBuilderOf(chargeEntity.get());
Not sure adding `WithoutCorporateSurcharge` is adding much. We can probably assume the no surcharge is the standard case and doesn’t need to be explicitly called out.

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeServiceTest.java
> +        assertThat(chargeResponse, is(chargeResponseWithoutCorporateSurcharge.build()));
I think this can just be changed back a single `assertThat(chargeResponseForAccount.get(), is(expectedChargeResponse.build())`: the `equals(…)` method should take care of ensuring the two new fields are `null`.

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/RestAssuredClient.java
> +    public ValidatableResponse getCharges() {
OK, this is solving some of my earlier confusion!

Please put renames like this with large ripple effects in a separate PR.

In any case, I’m not sure we actually want to rename this. If I recall correctly, these endpoints can return both charges _and_ refunds intermixed. Generally we use the term “transactions” when we mean both.

2018-09-27 16:19 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculatorTest.java
> +}
Nice comprehensive set of tests

2018-09-28 08:39 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/model/domain/CardType.java
> +public enum CardType {
CardType -> PayersCardType
CardEntity.Type -> CardEntity.AcceptedType

2018-09-28 08:40 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/service/ChargeService.java
> +        if (chargeEntity.getCorporateSurcharge() != null) {
I thought that using an Object instead of a primitive would make that obvious but I'll change it to Optional.

2018-09-28 08:40 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +public interface CorporateSurchargeCalculator {
agreed

2018-10-01 14:37 UTC, alexbishop1 requested changes
Thanks for making the requested changes.

It’s clearer now that the method renames have been taken out (but I think one might have been missed).

Thanks also for explaining that this only does the charges endpoint and that the others will be done in a separate PR.

Left a few comments, all of them fairly minor.

2018-10-01 14:37 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/model/domain/PayersCardType.java
> +public enum PayersCardType {
Love this name

2018-10-01 14:37 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/resources/GatewayAccountResource.java
> +            return badRequestResponse(format("AcceptedCardType(s) referenced by id(s) '%s' not found", String.join(",", extractNotFoundCardTypeIds(cardTypeIds, cardTypeEntities))));
I wouldn’t camel-case `AcceptedCardType` if it doesn’t refer to an actual type

2018-10-01 14:37 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/CardAuthoriseService.java
> +                }
```java
getCorporateSurchargeFor(authCardDetails, chargeEntity).ifPresent(chargeEntity::setCorporateSurcharge);
```

2018-10-01 14:37 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/ChargeService.java
> +            reponseBuilder
Could you add another `s` to `reponseBuilder` please?

2018-10-01 14:37 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/service/ChargeService.java
> +        }
```java
chargeEntity.getCorporateSurcharge().ifPresent(corporateSurcharge ->
    reponseBuilder.withCorporateSurcharge(corporateSurcharge)
        .withTotalAmount(CorporateSurchargeCalculator.getTotalAmountFor(chargeEntity)));
```

2018-10-01 14:37 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +    public static Optional<Long> getCorporateSurchargeFor(AuthCardDetails authCardDetails, ChargeEntity chargeEntity) {
I think this can just be a regular non-static method i.e. we should create an instance of `CorporateSurchargeCalculator` and inject it where needed using Guice

2018-10-01 14:37 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +        return charge.getAmount();
```java
return charge.getCorporateSurcharge()
    .map(surcharge -> surcharge + charge.getAmount())
    .orElseGet(charge::getAmount);
```

2018-10-01 14:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesApiResourceITest.java
> +    }
You have explained that those endpoint changes will be coming in another PR

2018-10-01 14:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/TransactionsApiV2ResourceITest.java
> +                .getChargesV2()
I thought we decided not to do this method name change for now

2018-10-01 14:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/CardAuthoriseServiceTest.java
> +    public void doAuthoriseWithCorporateCard_shouldRespondAuthorisationSuccess() {
Can this be named in such a way to make it clear that even though it’s a corporate card, we don’t expect a surcharge to be applied because the account doesn’t have a surcharge?

2018-10-01 14:37 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculatorTest.java
> +    public void shouldNotGetCorporateSurchargeForNull() {
Could you specify what exactly it is that’s null here please?

2018-10-02 12:48 UTC, alexbishop1 submitted a review, later dismissed
I still think the `CorporateSurchargeCalculator` would be better as an injected instance rather than a class a static methods but that’s tiny on the grand scheme of things, so I’m approving

2018-10-02 13:35 UTC, alexbishop1 approved these changes

2018-10-02 15:02 UTC, merged