PP-4126 Add corporate surcharge and total amount
alphagov/pay-connector pull request #726
Opened 2018-10-08 11:06 UTC by georgeracu

WIP - Do not merge

## WHAT
_A brief description of the pull request:_

## HOW 
_Steps to test or reproduce:_

2018-10-09 10:05 UTC, danworth requested changes
Hello, it looks good. I've made two suggestions, one regarding the response building to ensure that `totalAmount` is set whenever `corporateSurcharge` is (which seems appropriate) and avoid duplication of the logic. Another around wether `getTotalAmount` could be a method on the `Transaction` class (happy to hear your thoughts if you considered and dismissed such an idea).

2018-10-09 10:05 UTC, danworth commented on src/main/java/uk/gov/pay/connector/dao/TransactionDao.java
> -import uk.gov.pay.connector.model.LastDigitsCardNumber;
👍 appears this isn't used and hence removed.

2018-10-09 10:05 UTC, danworth commented on src/main/java/uk/gov/pay/connector/dao/TransactionDao.java
> +
👍 tidying up :)

2018-10-09 10:05 UTC, danworth commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> +        return chargeDao.findByExternalId(chargeId)
Tidier 👍

2018-10-09 10:05 UTC, danworth commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> +            if (surcharge > 0) {
It seems having this logic within the `.withCorporateSurcharge` method to also set the `totalAmount` would be safer in that it will ensure the `totalAmount` is always set when `corporateSurcharge` is and avoid the duplication in the TransactionSearchStrategy a little further down. You could then just pass in the value if present and put the `if (surcharge > 0)` logic in there too (since this may change and it'll be easy to find in the one file responsible for creating the response).

2018-10-09 10:05 UTC, danworth commented on src/main/java/uk/gov/pay/connector/service/search/TransactionSearchStrategy.java
> +        transaction.getCorporateSurcharge().ifPresent(surcharge -> {
Same as above, to avoid this duplication the logic and call to set the totalAmount if surcharge is > 0 could be within the `withCorporateSurchage`.

2018-10-09 10:05 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +    public static Long getTotalAmountFor(Transaction transaction) {
Certainly one way to do it. Did you consider having `getTotalAmount()` as a method on the `Transaction` class, it seems a simple calculation to add its own `amount` to its own `corporateSurcharge` and return it? This avoids needing a utility method in a separate class. It also makes it clear to anyone in the future who looks at `Transaction` class that there is an `amount` and a `totalAmount` which might prompt them to consider which they really need should they not know about this utility method.

2018-10-09 13:23 UTC, georgeracu commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +    public static Long getTotalAmountFor(Transaction transaction) {
I went on and off on having this method on the `Transaction` object and I believe is better to be in a utility method because:
* `Transaction` is holding data, should not be aware of the business logic used to calculate different amounts (same goes with `total`, a bit in our way at the moment, but we need to live with it)
* Having it in a separate utility method makes it easy to change the business logic and to add other values that get calculated on the fly. Might seem premature, but I think we should have our data objects pure, to keep only values from our database.

2018-10-10 10:21 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> +            if (surcharge > 0) {
As discussed, we came to the decision to use a utility class for the purpose of calculating total amount. `ResponseBuilder` classes are the few in `connector` that are pure in a sense that they do not contain business logic. `.withCorporateSurcharge` and `.withTotalAmount` are virtual values (meaning they are not stored and their only representation is in the outgoing Json response). That's why we decided to 'hide' them in plain sight and use the `CalculateCorporateSurcharge` utility class to the benefit of future generations to come. Adding logic (eg setting the `totalAmount` when setting the `corporateSurcharge`) would make (in our opinion) connector even more spaghetti bound. I agree it does not look too pretty but on the other hand it makes the whole process very visible.

2018-10-10 10:22 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/service/search/TransactionSearchStrategy.java
> +        transaction.getCorporateSurcharge().ifPresent(surcharge -> {
Either way the duplication would be present as both endpoints need the logic of setting `corporateSurcharge` and `totalAmount`.

2018-10-10 10:30 UTC, danworth commented on src/main/java/uk/gov/pay/connector/util/charge/CorporateSurchargeCalculator.java
> +    public static Long getTotalAmountFor(Transaction transaction) {
Ok, thanks for the explanation. I'm happy to go with your judgement 👍

2018-10-10 10:31 UTC, danworth commented on src/main/java/uk/gov/pay/connector/resources/ChargesFrontendResource.java
> +            if (surcharge > 0) {
Ok, thanks for the explanation. I'm happy to go with your judgement 👍

2018-10-10 10:31 UTC, danworth approved these changes

2018-10-10 10:50 UTC, merged