PP-4280 Reorganised PSP (paymentserverprovider) related classes
alphagov/pay-connector pull request #738
Opened 2018-10-11 20:52 UTC by kbottla

## WHAT
Organised packages/classes related to payment service providers (PSPs).

@mrlumbu

2018-10-12 14:01 UTC, alexbishop1 requested changes
Not going to look through all of this but I trust you (thanks so much for not combining this with other changes!).

I did spot one place where it seems fully-qualified class name is being used unnecessarily.

Also — and this is just a thought, not a request — `gateway` might be shorter than `paymentserviceprovider` in package names (generally, “gateway” refers specifically to card payment processors, whereas “payment service provider” is more broad).

Now might be a good opportunity to remove all the wildcard imports from the modified classes (in IntelliJ, select all of the files in the _Version Control_ view and then open the _Code_ menu and choose _Optimize Imports_) since they’re changing anyway.

2018-10-12 14:01 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/UnknownStatusTest.java
> +    private final uk.gov.pay.connector.paymentserviceprovider.model.status.UnknownStatus UnknownStatus = new UnknownStatus();
🤨

2018-10-12 14:10 UTC, mrlumbu commented
@alexbishop1  `gateway` is not a bad idea. I would like to standardise on one term (duh). Or maybe `paymentgateway`? Then use this everywhere - `PaymentProvider` makes no sense. We could just use `gateway` everywhere, but it feels a bit too generic, even the bounded context of connector

2018-10-12 14:15 UTC, alexbishop1 commented
I’m sure we could bikeshed on the names forever. The way connector alternates between “gateway” and “(payment) provider” is frustrating, though it seems to mainly use “gateway” (though often in the context of “gateway account”, which is a concept that we’ve allowed to expand to represent more than purely an account with a payment gateway.

I don’t think `gateway` is too generic for connector: it’s a fairly well-defined term within the domain of card payments.

The abbreviation `psp` is another option and has the appeal of being short.

2018-10-12 14:18 UTC, mrlumbu commented
Ok, let's go with `gateway`, if you're happy with that @kbottla?

2018-10-12 14:18 UTC, kbottla commented
That sounds good to me :)

2018-10-12 14:19 UTC, mrlumbu commented
In a future PR we'll use gateway everywhere that we currently use PaymentProvider and friends

2018-10-12 15:58 UTC, kbottla commented
Thanks @alexbishop1 
- I have renamed package to `gateway`
- Wild imports have been removed for organised packages
- Removed fully classified name in `UnknownStatusTest`

2018-10-15 08:56 UTC, alexbishop1 approved these changes

2018-10-15 08:56 UTC, merged