PP-4280 Organised Charge domain classes
alphagov/pay-connector pull request #746
Opened 2018-10-15 14:46 UTC by kbottla

## WHAT

- Organised charge related classes into 'charge' package and sub packages
- Mostly includes changes to package names & corresponding imports
- Qualifier changes for few static variables 

Doesn't include

Any changes to existing functionality

2018-10-15 16:23 UTC, mrlumbu requested changes
https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/model/domain/ChargeStatus.java
https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/model/domain/CardDetailsEntity.java 
https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/model/FirstDigitsCardNumber.java
https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/model/LastDigitsCardNumber.java
probably all belong in `charge`

2018-10-15 16:28 UTC, kbottla commented
Thanks @mrlumbu . Moved specified classes to `charge` domain

2018-10-15 16:38 UTC, mrlumbu submitted a review, later dismissed

2018-10-16 10:53 UTC, mrlumbu approved these changes

2018-10-16 10:53 UTC, merged