PP-4261 Refactor cherges sweep to use config file
alphagov/pay-connector pull request #780
Opened 2018-10-30 10:18 UTC by SandorArpa

## WHAT
Use config file for charge expiry windows instead of hard coded values.

## HOW 
- refactor ChargeExpiryService to use config file for expiry windows

2018-10-31 13:56 UTC, mrlumbu requested changes

2018-10-31 13:56 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/app/ChargesSweepTimeConfig.java
> +public class ChargesSweepTimeConfig extends Configuration {
Can we call it `ChargeSweepConfig` (this applies for this class, but also to config etc)

2018-10-31 13:56 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/app/ChargesSweepTimeConfig.java
> +    private int chargeExpirySeconds;
can we call this `defaultChargeExpiryThreshold` or similar, and make same changes across getters, config etc. This might seem a bit pernickety, but I think it better explains what it is

2018-10-31 13:56 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/app/ChargesSweepTimeConfig.java
> +    private int awaitingCaptureExpirySeconds;
likewise can we call this `awaitingCaptureExpiryThreshold`

2018-11-01 13:39 UTC, danworth commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +    @JsonProperty("chargesSweepTimeConfig")
Should this JsonProperty be updated to `chargesSweepConfig` to match the name change of the class?

2018-11-01 13:40 UTC, SandorArpa commented on src/main/java/uk/gov/pay/connector/app/ConnectorConfiguration.java
> +    @JsonProperty("chargesSweepTimeConfig")
👍

2018-11-01 13:51 UTC, danworth approved these changes
Looks good, basing my review on-top of Dom's rather than starting again. Changes requested have been made and looks good.

2018-11-02 11:08 UTC, mrlumbu approved these changes

2018-11-02 13:27 UTC, merged