PP-4297 return capture url when a charge is eligible
alphagov/pay-connector pull request #782
Opened 2018-10-30 14:07 UTC by SandorArpa

## WHAT
Return `capture` url when a charge state is in `AWAITING_CAPTURE_REQUEST`.

## HOW 
- add URL when eligible to ChargeResponse
- add relevant test

2018-10-31 11:28 UTC, mrlumbu commented
Possibly a silly question, but why is this needed?

2018-10-31 13:25 UTC, SandorArpa commented
@mrlumbu I added the reason from the story to the description.
The way we present a charge's state through publicapi is not clear enough to determine whether a charge is awaiting capture request.
```
"state": {
        "status": "submitted",
        "finished": false
    }
```
We do have a field `"delayed_capture": true` but even the combination of the two can refer to either`AWAITING_CAPTURE_REQUEST` or `AUTHORISATION_SUCCESS`

2018-10-31 13:47 UTC, mrlumbu commented
Ok cool. Can we talk about this? The thing I find a bit strange is that we are generating a URL in connector, but obviously ultimately the URL that will be required is a publicapi one. So really publicapi will have to look at whether this url is present in the response from the connector, then do something with it (i.e create a new url, which will probably be entirely different from this one), at which point this url is really just acting as a flag, so may as well be a flag. Quite possibly I'm missing something here

2018-10-31 14:12 UTC, alexbishop1 commented
I don’t think you’re missing anything, @mrlumbu. This could be a flag, I suppose (I didn’t think of that when writing the story). A URL is nice from a RESTful perspective in that connector is telling you about operations you can perform on the URL, similar to how it includes other links like `self`, `refunds` and `next_url` (though `next_url` is a bit different because it’s passed straight through by public API without being converted from a connector URL to a public API URL).

2018-10-31 16:05 UTC, alexbishop1 requested changes
Looks good — just a query about the test.

What’s going on with `ChargesApiResourceGetChargesJsonITest` and `ChargesApiResourceJsonPaginationITest`?

And let’s chat with Dom about this being a flag.

2018-10-31 16:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +        Long accountId = 10L;
Why do we have an `accountId` of 10 and various hard-coded account IDs of 1?

2018-10-31 16:05 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +        expectedChargeResponse.withLink("capture", POST, new URI(SERVICE_HOST + "/v1/api/accounts/1/charges/" + externalId + "/capture"));
I wonder if it’s worth having a test (or adding to another test) to check the capture URL isn’t included if the payment is in another state

2018-10-31 16:24 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +        expectedChargeResponse.withLink("capture", POST, new URI(SERVICE_HOST + "/v1/api/accounts/1/charges/" + externalId + "/capture"));
I did consider but given how the tests are written, they would break if capture url surfaced in any other charge state.

2018-10-31 16:24 UTC, SandorArpa commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +        Long accountId = 10L;
copy-paste, will fix it

2018-10-31 16:37 UTC, SandorArpa commented
Both `ChargesApiResourceGetChargesJsonITest` and `ChargesApiResourceJsonPaginationITest` were empty classes. Looking back at the repository history their content was removed when we got rid of the unused endpoint they correspond to.

2018-11-01 10:22 UTC, alexbishop1 approved these changes
Unfortunately, Dom isn’t working today so we can’t discuss the URL/flag issue with him but I’m happy with this, so approving

2018-11-01 10:22 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +        gatewayAccount = new GatewayAccountEntity("sandbox", new HashMap<>(), TEST);
Nice change to enable to removal of duplicate code

2018-11-01 10:55 UTC, merged