PP-4313 Add decrypter for apple pay payloads
alphagov/pay-connector pull request #792
Opened 2018-11-02 09:38 UTC by simad

## WHAT
A first stab at integrating Apple's suggested implementation of a decrypter. There are a few things which will be improved, like `private Map<String, String> paymentData;` (still unsure as to what we actually are going to take from that map, so will be more strongly typed as other stories progress), and general exception handling.

2018-11-02 12:04 UTC, alexbishop1 requested changes
Looks good overall but I won’t pretend to understand the cryptography stuff!

A few comments — I’ll be interested to see how this evolves as we start integrating it into our application

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ApplePayConfig.java
> +public class ApplePayConfig extends GatewayConfig {
Does this need to extend `GatewayConfig`?

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ApplePayConfig.java
> +        return publicCertificate.getBytes();
This uses the platform default character encoding. It’s good to be explicit, so please use `publicCertificate.getBytes(StandardCharsets.UTF_8)` instead.

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/ApplePayConfig.java
> +        return privateKey.getBytes();
As above: `privateKey.getBytes(StandardCharsets.UTF_8)`

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/WorldpayConfig.java
> +    public ApplePayConfig getApplePay() {
I imagine `getApplePayConfig()` would be better unless there’s an existing convention I‘m missing

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +import com.sun.org.apache.xerces.internal.impl.dv.util.HexBin;
We shouldn’t rely on `com.sun` packages because they’re JDK internals. I haven’t checked but I can imagine that this won’t continue to work on Java 11 (I know some other `com.sun.org.apache.xerces.internal` stuff doesn’t). Can you find an alternative? I imagine Apache Commons Codec or Guava has something.

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    private static final Charset UTF_8 = Charset.forName("UTF-8");
This could be replaced by static-importing `java.nio.charset.StandardCharsets.UTF_8` and just using that everywhere

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    private ObjectMapper objectMapper;
Looks like these three fields can be `final`

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +            LOGGER.error("Error while trying to decrypt apple payload");
It’s the “Apple Pay payload” 😀

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +            throw new InvalidKeyException("Error while trying to decrypt apple payload");
We’re losing the original exception here. For example, if the `"Asymmetric keys do not match!`" `InvalidKeyException` is thrown, we won’t record that cause anywhere.

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    }
I’m going to trust this is doing the right thing (I understand this code is basically just copied and pasted from Apple’s examples)

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +        byteArrayOutputStream.write(HexBin.decode(new String((certificate.getExtensionValue("1.2.840.113635.100.6.32")), UTF_8).substring(4)));
Can we extract `"1.2.840.113635.100.6.32"` to a constant and give it a meaningful name?

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    private Certificate generateCertificate() throws Exception {
Can we be more specific than `Exception`?

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +        return certificate;
We can `try`-with-resources this:

```java
try (InputStream stream = new ByteArrayInputStream(publicCertificate)) {
    CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
    return certificateFactory.generateCertificate(stream);
}
```

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePaymentData.java
> +public class ApplePaymentData implements AuthorisationDetails {
Unless this absolutely has to extend `AuthorisationDetails`, I wouldn’t. It’s a basically useless interface (it defines no methods!) that was introduced to allow us to shoehorn authorisation-based-on-card-details and authorisation-based-on-a-3D-Secure-authentication-result into the same code path. It was a terrible idea. And I say that as one of the people who introduced it!

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePaymentData.java
> +public class ApplePaymentData implements AuthorisationDetails {
I’m not sure how I feel that this has no constructor and is only ever created by an `ObjectMapper`. Though I can see the advantages from a code conciseness point of view, it very much ties it to the idea that it comes from a JSON representation.

Also, it’s not immediately obvious that this class is mapped from JSON, so someone could, say, decide to rename `applicationPrimaryAccountNumber` and break it because it wouldn’t match `application_primary_account_number` in the JSON any more (I’m assuming standard Jackson renaming is in play here).

So in terms of a concrete suggestion, I have two options:

1. Ponder how horrific it would be if this object were just a regular POJO with a constructor, with `ApplePayDecrypter` responsible for extracting the data from the JSON and instantiating this object via the constructor
2. Add `@JsonProperty` annotations to the fields with the JSON key names in them

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/AsymmetricKeyVerifier.java
> +        byte[] data = UUID.randomUUID().toString().getBytes();
Another `getBytes(StandardCharsets.UTF_8)` opportunity

2018-11-02 12:04 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/AsymmetricKeyVerifier.java
> +    private byte[] signData(byte[] data) throws Exception {
It makes me a bit sad that we have `throws Exception` here. Can we list them out: `throws NoSuchAlgorithmException, InvalidKeyException, SignatureException`? Or are we expecting unchecked exceptions?

2018-11-02 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +    private final byte[] ephemeralKey = Base64.decode( "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEl/XAbOgrSCupps/QbIxJ3u4QZ1PlbO5uGDD1zj/JGMoephYSEgw+63gHQHekx3T8duXN3CoYafUpuQlwOeK6/w==");
These two can be constants, right?

2018-11-02 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +        byte[] publicCertificate = Base64.decode("MIIEeTCCBCCgAwIBAgIIUkIKsiYxaKowCgYIKoZIzj0EAwIwgYExOzA5BgNVBAMMMlRlc3QgQXBwbGUgV29ybGR3aWRlIERldmVsb3BlcnMgUmVsYXRpb25zIENBIC0gRUNDMSAwHgYDVQQLDBdDZ
Can we put the Base64 strings into constants please? It’s a bit hard to follow the code with occasional multi-thousand-character interruptions!

2018-11-02 12:04 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +        when(mockApplePayConfig.getPublicCertificate()).thenReturn("nope".getBytes());
`"nope".getBytes(StandardCharsets.UTF_8)` please

2018-11-02 12:16 UTC, simad commented on src/main/java/uk/gov/pay/connector/app/ApplePayConfig.java
> +public class ApplePayConfig extends GatewayConfig {
🤦‍♀️

2018-11-02 12:16 UTC, simad commented on src/main/java/uk/gov/pay/connector/app/ApplePayConfig.java
> +        return publicCertificate.getBytes();
Nice catch. You're right!

2018-11-02 12:18 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +import com.sun.org.apache.xerces.internal.impl.dv.util.HexBin;
Sure, I'll check.

2018-11-02 12:21 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +import com.sun.org.apache.xerces.internal.impl.dv.util.HexBin;
Bouncycastle (which is the dependency we introduced - has a hex encoder/decoder. In case, ApacheCommons does, too)

2018-11-02 12:21 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/AsymmetricKeyVerifier.java
> +        byte[] data = UUID.randomUUID().toString().getBytes();
yep

2018-11-02 12:22 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/AsymmetricKeyVerifier.java
> +    private byte[] signData(byte[] data) throws Exception {
We can. I was waiting to use this class in depth (and test out edge cases etc.) to check which exceptions are thrown during a "standard" journey. Will list them out for now and maybe revisit once I wire this class in 👍

2018-11-02 12:25 UTC, simad commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +    private final byte[] ephemeralKey = Base64.decode( "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEl/XAbOgrSCupps/QbIxJ3u4QZ1PlbO5uGDD1zj/JGMoephYSEgw+63gHQHekx3T8duXN3CoYafUpuQlwOeK6/w==");
I also failed to spot those spaces next to those parenthesis. Oh dear

2018-11-02 12:30 UTC, simad commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +    private final byte[] ephemeralKey = Base64.decode( "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEl/XAbOgrSCupps/QbIxJ3u4QZ1PlbO5uGDD1zj/JGMoephYSEgw+63gHQHekx3T8duXN3CoYafUpuQlwOeK6/w==");
Having them as a `byte[]` constant means having something like: ```[-47, -59, -121, 102, 61, -49, -53, 109, 13, -58, 31, 21, -84, 3, 95, 113, 116, -123, 21, -90, -115, 8, -109, 61, 30, -112, -113, -119, 72, 91, -21, 113, -106, -117, -65, -128, -55, -83, 1, -102, -62, -97, 16, -70, 10, -4, -6, 126, -42, 27, -26, 39, 51, -76, 14, -39, 29, 98, -69, 75, 65, 25, -54, 68, -91, 12, 95, -30, -97, 18, -60, 14, -35, -30, -117, 16, -26, -111, -101, 93, -86, 127, 88, -32, 92, 110, -57, 80, 77, 107, -8, 25, 107, 43, -48, 66, -37, -124, 51, -55, -103, 42, 97, 86, -35, 77, 38, -60, -16, 36, -26, 14, -24, -125, 73, 88, -48, -117, 71, -63, -61, 26, 62, 49, -40, -20, 90, 15, -102, -89, -92, 67, -106, 100, -105, 84, -91, -18, 25, 45, 109, -93, -112, 30, -3, 80, -25, -64, 16, 76, -72, 51, 88, 38, 34, 88, 73, 31, 75, 89, 78, -34, 59, -95, -53, -22, 71, -70, -5, 24, -41, 113, 24, 95, -59, -20, 94, 103, 92, -67, 93, 58, 19, 112, 58, -62, -48, -50, -15, 51, 121, 0, 30, 68, -14, 13, 93, -12, -101, -83, -52, 41, -42, -5, 114, -108, -107, -1, -80, -43, -126, 63, 125, 1, 127, 87, -84, -71, 85, 38, 119, 64, -100, 18, -56, -18, 51, 44, 56, 80, -109, -122, -113, 58, 83, 71, -55, 39, -115, 23, 14, 73, 81, -15, 126, 113, -29, 115, 74, 47, -25, 54, 74, 41, -108, 52, 19, 25, -110, 38, 75, -54, 4, 18, 82, -79, 67, -29, 87, 10, 111, -2, -44, 35, 32, 125, 115, -76, -92, -11, 66, 102, 76, -51, -72, 20, -25, -107, -73, -12, 71, -39, -62, 23, -6, -119, 17, 7, -91, 51, 123, 5, 70, 100, 65, 111, 87, -13, -42, 108, -102, -102, 56, 37, -79, 33, 35, 35, 37, -49, 7, 2, 69, -102, -47, 13, 64, 69, 82, -109, -52, 36, -70, 102, 11, 15, 21, -105, 26, -93, 70, 119, -2, 62, 58, -112, 44, 77, -3, 22, 30, 96, 110, -31, 126, 10, -19, 104, 127, 33, -86, 123, -30, 113, -89, 55, -110, 24, 69, 1, 79, 81, 110, 51, 25, 10, 97, -99, 87, 60, -82, 107, 28, -1, -31, 34, -122, -76, 56, 13, -37, 108, -68, -80, -5, 34, 88, -28, 98, -24, -45, 62, -44, 11, 57, -100, 117, -116, -128, -2, -35, 59, 106, 46, 35, 124, 28, -71, -84, 71, 0, 49, -33, 26, 110, 90, 53]``` which is a bit too verbose for my taste :D better ideas?

2018-11-02 12:31 UTC, simad commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +    private final byte[] ephemeralKey = Base64.decode( "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEl/XAbOgrSCupps/QbIxJ3u4QZ1PlbO5uGDD1zj/JGMoephYSEgw+63gHQHekx3T8duXN3CoYafUpuQlwOeK6/w==");
I could generate the data myself and then encode it and make sure it is what we expect, which is also better. I'll try and see

2018-11-02 12:31 UTC, simad commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +        when(mockApplePayConfig.getPublicCertificate()).thenReturn("nope".getBytes());
roger

2018-11-02 12:31 UTC, simad commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +        byte[] publicCertificate = Base64.decode("MIIEeTCCBCCgAwIBAgIIUkIKsiYxaKowCgYIKoZIzj0EAwIwgYExOzA5BgNVBAMMMlRlc3QgQXBwbGUgV29ybGR3aWRlIERldmVsb3BlcnMgUmVsYXRpb25zIENBIC0gRUNDMSAwHgYDVQQLDBdDZ
👍

2018-11-02 12:40 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    private static final Charset UTF_8 = Charset.forName("UTF-8");
👍

2018-11-02 12:41 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +            LOGGER.error("Error while trying to decrypt apple payload");
yo dawg

2018-11-02 12:42 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +            throw new InvalidKeyException("Error while trying to decrypt apple payload");
Yes, this is what I meant in the PR description with (will fix exception mapping) etc. I will make sure we bubble up what we want to bubble up properly when I actually wire the code in. If it's a burning issue right now I'll modify it

2018-11-02 12:42 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    }
yes, I also quickly went through it with Ed.

2018-11-02 12:42 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +        byteArrayOutputStream.write(HexBin.decode(new String((certificate.getExtensionValue("1.2.840.113635.100.6.32")), UTF_8).substring(4)));
sure

2018-11-02 13:44 UTC, simad commented on src/main/java/uk/gov/pay/connector/app/WorldpayConfig.java
> +    public ApplePayConfig getApplePay() {
Renamed!

2018-11-02 13:44 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    private ObjectMapper objectMapper;
Done 👍

2018-11-02 13:45 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    private Certificate generateCertificate() throws Exception {
Indeed

2018-11-02 13:46 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +        return certificate;
👍

2018-11-02 13:47 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePaymentData.java
> +public class ApplePaymentData implements AuthorisationDetails {
I see. I was looking for a way to shoehorn apple pay related stuff in the same code path, too. Which proved to be quite a bad idea indeed. Will remove for now, let's see when I integrate the code how it looks like

2018-11-02 14:06 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePaymentData.java
> +public class ApplePaymentData implements AuthorisationDetails {
I understand completely what you mean but I am a bit ambivalent towards this. I could add JsonProperty annotations, indeed, but that would make this look like something we might expect to serialise. It is a POJO for what we are concerned, just a POJO which is currently deserialised by jackson rather than explicitly constructed.
The properties match what comes from apple (ie. `applicationPrimaryAccountNumber` is in the decrypted apple payload) - if somebody renames any property a test will break, which is ok.

Between the two solutions, will add `@JsonProperty annotations` :(

2018-11-02 15:44 UTC, alexbishop1 requested changes
Just a couple of small things

2018-11-02 15:44 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/app/WorldpayConfig.java
> +        return applePay;
Can you rename the variable to `applePayConfig` to match please?

2018-11-02 15:44 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/AsymmetricKeyVerifier.java
> +        byte[] data = UUID.randomUUID().toString().getBytes(UTF_8);
I was going to comment on this in the first review round but then I forgot.

So here we’re generating a UUID, getting the string representation of it and then getting the UTF-8 bytes of that string and putting them in an array. That seems a little tortuous and isn’t going to give us a result where every byte is random. Is the intention here to just get an array of random bytes? We should probably just do that directly.

2018-11-02 15:44 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +    private final String encodedPublicCertificate = "MIIEeTCCBCCgAwIBAgIIUkIKsiYxaKowCgYIKoZIzj0EAwIwgYExOzA5BgNVBAMMMlRlc3QgQXBwbGUgV29ybGR3aWRlIERldmVsb3BlcnMgUmVsYXRpb25zIENBIC0gRUNDMSAwHgYDVQQLDB
These and friends can all become `static` constants

2018-11-02 15:44 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +        when(mockApplePayConfig.getPublicCertificate()).thenReturn("nope".getBytes());
Looks like you forgot to do it!

2018-11-02 15:44 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +        when(mockApplePayConfig.getPrivateKey()).thenReturn("nope".getBytes());
One more place for `getBytes(StandardCharsets.UTF_8)`

2018-11-02 16:11 UTC, simad commented on src/main/java/uk/gov/pay/connector/app/WorldpayConfig.java
> +        return applePay;
:+1:

2018-11-02 16:12 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/AsymmetricKeyVerifier.java
> +        byte[] data = UUID.randomUUID().toString().getBytes(UTF_8);
I _assume_ the intent was that one, yes. I've replaced it with a direct `byte[]` generation, 16

2018-11-02 16:12 UTC, simad commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +    private final String encodedPublicCertificate = "MIIEeTCCBCCgAwIBAgIIUkIKsiYxaKowCgYIKoZIzj0EAwIwgYExOzA5BgNVBAMMMlRlc3QgQXBwbGUgV29ybGR3aWRlIERldmVsb3BlcnMgUmVsYXRpb25zIENBIC0gRUNDMSAwHgYDVQQLDB
done

2018-11-02 16:12 UTC, simad commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> +        when(mockApplePayConfig.getPrivateKey()).thenReturn("nope".getBytes());
they were so many :(

2018-11-02 16:50 UTC, alexbishop1 submitted a review, later dismissed

2018-11-02 16:57 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/AsymmetricKeyVerifier.java
> +        byte[] data = RandomUtils.nextBytes(16);
Actually, come to think of it, should this use a cryptographically-secure random source?

2018-11-02 17:45 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/AsymmetricKeyVerifier.java
> +        byte[] data = RandomUtils.nextBytes(16);
Done

2018-11-05 10:50 UTC, alexbishop1 approved these changes

2018-11-05 10:50 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/util/XMLUnmarshaller.java
> +        InputSource inputSource = new InputSource(new ByteArrayInputStream(payload.getBytes(UTF_8)));
Completely tangential to what you’re currently doing but it would probably be more straightforward to just use a `StringReader` here:

```java
InputSource inputSource = new InputSource(new StringReader(payload));
```

2018-11-05 11:04 UTC, merged