PP-4341: Integration test for creating a charge with Stripe
alphagov/pay-connector pull request #814
Opened 2018-11-08 17:00 UTC by oswaldquek

@oswaldquek

2018-11-08 17:02 UTC, oswaldquek commented
renaming to "WIP" as i still haven't configured timeouts for stripe yet

2018-11-09 17:11 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +                stripeUrlEncodedSourcePayload(request),
why are we sending a url encoded payload

2018-11-09 17:18 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +                stripeUrlEncodedSourcePayload(request),
originally because Krishna's play_stripe_integration branch did it: https://github.com/alphagov/pay-connector/blob/247987c2f658bf4a0c364acd9615dbac6ec35127/src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java#L39.

i did try using json but stripe threw a bad request exception.

if you look at https://stripe.com/docs/api/tokens/create_card?lang=curl the curl example they give is 
```
curl https://api.stripe.com/v1/tokens \
   -u sk_test_5R92VZnYjN96ga3p5w07S8wL: \
   -d card[number]=4242424242424242 \
   -d card[exp_month]=12 \
   -d card[exp_year]=2019 \
   -d card[cvc]=123
```
which doesn't look json.

2018-11-12 09:45 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +                stripeUrlEncodedSourcePayload(request),
It is how stripe expects data. See Stripe java client https://github.com/stripe/stripe-java/blob/6cd60ea620c02044e06de85be700a165f923a320/src/main/java/com/stripe/net/LiveStripeResponseGetter.java#L236

2018-11-12 13:19 UTC, kbottla requested changes

2018-11-12 13:19 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +                APPLICATION_JSON_TYPE);
Not sure it JSON type works ? Can we use same encoding used to create token? I think Stripe always expects in the form `application/x-www-form-urlencoded` (see Stripe API json - https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json) .

2018-11-12 13:19 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +        String token = sourceResponse.readEntity(Map.class).get("id").toString();
Can we deserialise response to an object here ? It will be inline with the way we handle responses and will be less error prone.

I got `NullPointerException` at this line when I ran StripePaymentProviderTest.createChargeInStripe

2018-11-12 13:19 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/contract/StripePaymentProviderTest.java
> +    public void createChargeInStripe() {
Cannot create charge with Stripe ( after setting authToken & stripeAccountId). Getting `java.lang.NullPointerException
	at uk.gov.pay.connector.gateway.stripe.StripePaymentProvider.authorise(StripePaymentProvider.java:95)`

2018-11-12 13:19 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +    private String stripeAuthoriseJsonPayload(AuthorisationGatewayRequest request, String token) {
Can we name it like `stripeAuthorisePayload ` -  if all payloads are of same type (i.e.,  application/x-www-form-urlencoded)

2018-11-12 13:19 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +    private String stripeUrlEncodedSourcePayload(AuthorisationGatewayRequest request) {
Same as for renaming `stripeAuthoriseJsonPayload`

2018-11-12 13:19 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/rules/StripeMockClient.java
> +                .willReturn(aResponse().withHeader(CONTENT_TYPE, APPLICATION_JSON).withStatus(200).withBody(responseBody)));
payload should be `APPLICATION_FORM_URLENCODED` as per Stripe API https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json

2018-11-12 13:19 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/rules/StripeMockClient.java
> +        paymentServiceResponse(payload, "/v1/charges", APPLICATION_JSON);
payload should be `APPLICATION_FORM_URLENCODED` as per Stripe API https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json

2018-11-12 13:19 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeResourceITest.java
> +    private static final String CVC = "123";
I would like to see a few more tests covering exception conditions for Authorisation ( in a separate PR if not in this one). Few could be `invalid token ID`,  `auth declined`

2018-11-12 13:19 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeResourceITest.java
> +                .withHeader("Content-Type", equalTo(APPLICATION_JSON)));
As above, Content-Type should be `APPLICATION_FORM_URLENCODED`

2018-11-12 14:28 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +        String token = sourceResponse.readEntity(Map.class).get("id").toString();
Hmm it works for me and Dom. Are you sure you're setting the correct values?

2018-11-12 14:31 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeResourceITest.java
> +    private static final String CVC = "123";
These are valid scenarios; however given the real purpose of this PR is to create an integration test (StripePaymentProviderTest) that will be run manually I will do these in another PR.

2018-11-12 14:34 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/rules/StripeMockClient.java
> +                .willReturn(aResponse().withHeader(CONTENT_TYPE, APPLICATION_JSON).withStatus(200).withBody(responseBody)));
oh that is a useful document. the responses for /v1/tokens and /v1/charges are "application/json" though.

2018-11-12 14:36 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +        String token = sourceResponse.readEntity(Map.class).get("id").toString();
I got a null pointer exception at one point as well - if Stripe returns an unauthorised response

2018-11-12 14:37 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +        String token = sourceResponse.readEntity(Map.class).get("id").toString();
I'm not how less error prone deserialising the the json response will be here. The response from the /v1/token call will always have an `id`.

2018-11-12 14:39 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/contract/StripePaymentProviderTest.java
> +    public void createChargeInStripe() {
Are you sure you're setting the correct values? @mrlumbu has tested this and it works. I've created a charge successfully https://dashboard.stripe.com/test/charges/ch_1DVgDGHj08j2jFuB0KPeYMIF via this test.

2018-11-12 14:42 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +        String token = sourceResponse.readEntity(Map.class).get("id").toString();
@mrlumbu @kbottla ok. should the unauthorised scenario be part of this test (StripePaymentProvider test) though? This is a manual test to test we can make a charge via Stripe. Seems like it would be a better scenario to test in StripeResourceITest.

2018-11-12 14:45 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +        String token = sourceResponse.readEntity(Map.class).get("id").toString();
Here we're actually talking about what the StripePaymentProvider does, not what the test is doing. I think ideally we would deserialise the stripe response to a validatable object before carrying on, but that can be done separately - I agree the main point of this is to get a payment working

2018-11-12 14:46 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +        String token = sourceResponse.readEntity(Map.class).get("id").toString();
Don't think it is required for tests under `uk.gov.pay.connector.it.contract` but required for integration tests `uk.gov.pay.connector.it.resources.stripe.StripeResourceITest`

2018-11-12 14:47 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/contract/StripePaymentProviderTest.java
> +    public void createChargeInStripe() {
I am pretty sure with the settings.

2018-11-12 14:47 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/rules/StripeMockClient.java
> +                .willReturn(aResponse().withHeader(CONTENT_TYPE, APPLICATION_JSON).withStatus(200).withBody(responseBody)));
Yes, responses are always JSON but the content type is always encoded

2018-11-12 14:49 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +        String token = sourceResponse.readEntity(Map.class).get("id").toString();
yes in that case i'll make that in another PR that adds more tests to StripeResourceITest

2018-11-12 14:50 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/rules/StripeMockClient.java
> +                .willReturn(aResponse().withHeader(CONTENT_TYPE, APPLICATION_JSON).withStatus(200).withBody(responseBody)));
content type is "application/json". from the openapi spec, a response to "v1/tokens" is:
```
"responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/token"
                }
              }
            },
            "description": "Successful response."
          }```

2018-11-12 14:51 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeResourceITest.java
> +    private static final String CVC = "123";
In that case, it would be great if PR description reflects this fact and a bit more about any other changes introduced.

2018-11-12 14:53 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/rules/StripeMockClient.java
> +                .willReturn(aResponse().withHeader(CONTENT_TYPE, APPLICATION_JSON).withStatus(200).withBody(responseBody)));
I think it is the same we are talking about. The responses we get from Stripe are always 'application/json'. The request data (all requests) we send should be encoded.

2018-11-12 14:55 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeResourceITest.java
> +    private static final String CVC = "123";
apologies for the confusion. the PR does say "integration test" but the tests that end with "ITest" are also technically integration tests.

2018-11-12 14:58 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/rules/StripeMockClient.java
> +                .willReturn(aResponse().withHeader(CONTENT_TYPE, APPLICATION_JSON).withStatus(200).withBody(responseBody)));
this line of code is stubbing a response to a post request, so "application/json" is correct here, unless i'm misreading something?

2018-11-12 15:09 UTC, kbottla approved these changes
LGTM! - for happy path with Stripe Authorisation

2018-11-12 15:14 UTC, merged