PP-4313 Change decrypter test data to be 3DSecure
alphagov/pay-connector pull request #827
Opened 2018-11-13 13:20 UTC by simad

## WHAT
 - We have now valid test private key / certs / ephemeral key and a payload which deserialises to a payment of type 3DSecure, which is what we are going to use in anger
 - Moreover, having those test keys will allow us to complete an end to end flow for local dev, which is 👌

2018-11-13 15:20 UTC, alexbishop1 requested changes
Good to see this functionality evolving towards where we want it to be

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/AppleDecryptedPaymentData.java
> +public class AppleDecryptedPaymentData implements AuthorisationDetails {
I assume we’ve sadly come to the conclusion that `AppleDecryptedPaymentData` has to implement `AuthorisationDetails`?

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/AppleDecryptedPaymentData.java
> +    private String transactionAmount;
The amount is a string?

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +import org.glassfish.jersey.internal.util.Base64;
`internal` 🙀
Looks like `java.util.Base64` can be used here

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePaymentData.java
> +public class ApplePaymentData implements AuthorisationDetails {
I’m having trouble understanding what the difference is between `ApplePaymentData` and `AppleDecryptedPaymentData` is

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDate.java
> +    private LocalDate date;
This can probably be `final`

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDate.java
> +        this.date = from(date);
If this is never going to be `null`, we can use `Objects.requireNonNull` to ensure this, which would also eliminate the need for the `null` checks in the `equals` and `hashCode` methods

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDate.java
> +}
What is this class giving us that we can’t just get using a `LocalDate`? Is it just the string (de)serialisation? Is it feasible to use `LocalDate` directly and just de-serialise from and serialise to the appropriate formats (which hardly look exotic) where necessary?

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDateDeserialiser.java
> +        return new AppleCardExpiryDate(node.asText());
There doesn’t seem to be much logic here: it just takes the text and relies on `AppleCardExpiryDate` to parse it. I’m surprised we can’t use something generic built in to Jackson to do that.

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/api/PaymentInfo.java
> +public class PaymentInfo {
This is the information we get from Apple Pay that isn’t encrypted, right? I’d prefer a less generic name than `PaymentInfo` but I can’t think of one right now. Might want to at least prefix it with `Apple` though.

2018-11-13 15:20 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/api/PaymentInfo.java
> +                '}';
I assume the cardholder name and email are excluded because they’re personally-identifiable information and we don’t want that ending up in the logs if possible? It might be worth adding a comment to state that we’re doing that so someone doesn’t “helpfully” add them.

2018-11-13 15:20 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> -        );
Do we have tests elsewhere that cover this stuff?

2018-11-13 15:22 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/AppleDecryptedPaymentData.java
> +public class AppleDecryptedPaymentData implements AuthorisationDetails {
Yes, I was hoping to avoid this but in another branch I am carrying out the work to wire it up and it seems we have to. I'll still try to avoid this as much as possible - also because this are in connector is undergoing a big refactoring, so 🤞

2018-11-13 15:26 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/AppleDecryptedPaymentData.java
> +    private String transactionAmount;
`transactionAmount | number | Transaction amount.`

nope :D fixed, it is a `long`. We are not using this value, tho, for now, as we get the value from the charge entity

2018-11-13 15:27 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +import org.glassfish.jersey.internal.util.Base64;
oopsy

2018-11-13 15:30 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePaymentData.java
> +public class ApplePaymentData implements AuthorisationDetails {
Let me explain. Please sit down. It's a very subtle difference, I thought a lot about this - so, when the Universe was created ..
.
.
.
I just renamed the class and the old one has been resurrected by a rebase. Damn zombies.

2018-11-13 15:30 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDate.java
> +    private LocalDate date;
yep

2018-11-13 15:31 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDate.java
> +        this.date = from(date);
👍

2018-11-13 15:31 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDateDeserialiser.java
> +        return new AppleCardExpiryDate(node.asText());
yes I was thinking exactly this when going through the changeset, I'll try to figure this out *opens up jackson's docs*

2018-11-13 15:33 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDate.java
> +}
Nice catch - this class will be enhanced a bit when wiring things up **spoiler alert** I will introduce a getFormattedMonth() (0 padded month) and getFormattedYear() which will be used in the worldpay xml templates (instead of having this logic directly in the xml, like we do for other templates, and it's a bit 😱 )

2018-11-13 15:37 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDateDeserialiser.java
> +        return new AppleCardExpiryDate(node.asText());
Turns up the deserialised was not even needed! Hurray. Also, shame on me

2018-11-13 15:38 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/api/PaymentInfo.java
> +public class PaymentInfo {
I thought about keeping it generic because this is created by frontend and _I imagine_ we will be able to share the same info between e-wallets. I'll rename it to `ApplePaymentInfo` and then maybe rename it back when and if we introduce Google Pay and it makes sense to do so

2018-11-13 15:39 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/api/PaymentInfo.java
> +                '}';
right 👍

2018-11-13 16:01 UTC, simad commented on src/test/java/uk/gov/pay/connector/applepay/ApplePayDecrypterTest.java
> -        );
I have added the tests back - I kind of assumed those cases would not happen because that payload comes from apple, and I thought it was all encrypted so hardly temper-able. It still comes from client side, so we should check for those cases.

2018-11-13 17:22 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDate.java
> +}
I’m not convinced we should be creating our own wrapper domain object just so we can add formatting convenience methods. For example, `getFormattedMonth()` could be achieved with just `localDate.format(DateTimeFormatter.ofPattern("MM"))`, which could be done immediately before passing the data to the XML template (doing it de-serialisation time as we are here feels a bit like mixing concerns).

I’m happy to trust your judgement on this but I think the bar should be pretty high for implementing our own domain model type that is — in terms of the data it can hold — identical to one of the Java built-in types.

Personally, I’d see how far I could get just using `LocalDate` but you’ve obviously got a lot more context on this and have a better idea of where this is going so I’m happy to defer to your decision here.

2018-11-13 17:32 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/api/AppleCardExpiryDate.java
> +}
I see and agree. I'll remove the class, let's see if things still smooth later on, I can always reintroduce it. Cheers

2018-11-14 15:21 UTC, alexbishop1 approved these changes
It’s awesome how the second version of this PR actually had fewer lines than the first!

2018-11-14 15:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    private final static Base64.Decoder BASE64_DECODER = Base64.getDecoder();
I just checked if `Base64.Decoder` is threadsafe and you’re good, it is!

Also, I think we usually follow the Java Language Specification, which is `private static final` rather than `private final static`.

2018-11-14 15:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/applepay/AppleDecryptedPaymentData.java
> +    private LocalDate applicationExpirationDate;
Neat, I didn’t know it was possible to de-serialise to a `LocalDate` with a custom pattern like this

2018-11-14 15:22 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/ApplePayDecrypter.java
> +    private final static Base64.Decoder BASE64_DECODER = Base64.getDecoder();
👍 will fix in the next PR

2018-11-14 15:24 UTC, simad commented on src/main/java/uk/gov/pay/connector/applepay/AppleDecryptedPaymentData.java
> +    private LocalDate applicationExpirationDate;
yes, pretty cool. Learned a new thing myself :D

2018-11-14 15:24 UTC, merged