PP-4341: Handle a card authorisation failure
alphagov/pay-connector pull request #839
Opened 2018-11-15 14:58 UTC by oswaldquek

Technically a 400 is a response to a malformed syntax but for consistentcy with
the current code in CardResource.authoriseCharge:

```
return isAuthorisationDeclined(response) ? badRequestResponse("This transaction was declined.")
```

a relevant test has been added to handle a card auth failure (E.g. invalid
number, rejected for fraud, invalid expiry date etc).

From the stripe docs I believe a card auth failure returns with a json that
looks like
```
{
  "id": "ch_1DRQ842eIIpdlo2CPbf7NNDv_test",
  "object": "charge",
  "failure_code": "card_error",
  "failure_message": "The expiry date was incorrect",
  "fraud_details": {
  },
  "status": "failed"
}
```
Any other errors (including Unauthorized 401) should look like
```
{
  "error": {
    "message": "Invalid API Key provided: sk_test_************S8wL",
    "type": "invalid_request_error"
  }
}
```

I've also taken the opportunity to improve the logging by logging the relevant external charge id as well.

@oswaldquek

## WHAT
_A brief description of the pull request:_

## HOW 
_Steps to test or reproduce:_

2018-11-15 15:45 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +                case 400:
We may not need this here as 400 can be due to incorrect payload and other error are given below:
https://github.com/stripe/stripe-java/blob/6cd60ea620c02044e06de85be700a165f923a320/src/main/java/com/stripe/net/LiveStripeResponseGetter.java#L699

In case if authorisation declined / payment failed, I think stripe returns charge with `outcome` populated and status 2xx (a question to confirm with stripe team)
https://stripe.com/docs/declines

2018-11-15 15:54 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +                case 400:
it may very well be a 402, as that throws a CardException https://github.com/stripe/stripe-java/blob/6cd60ea620c02044e06de85be700a165f923a320/src/main/java/com/stripe/exception/CardException.java
but we should confirm with the stripe team on these things.

2018-11-15 15:55 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +                case 400:
maybe this is one of the reasons to use the Stripe client, as we don't have to worry about what json is returned...

2018-11-19 11:09 UTC, georgeracu commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +                            request.getChargeExternalId(), stripeAuthResponse.getErrorCode(), stripeAuthResponse.getErrorMessage());
Given that there are actually 3 calls that potentially throw the same Exception type, when calling `stripeAuthResponse.` you might get a `NullPointerException` as this `GatewayClientException` could have bee thrown creating the token or the source. It feels like we need to handle each of this calls into their own `try catch` blocks so we can handle exceptions for each one. Probably a good point to ask ourselves if using Stripe's client is more useful that us doing all this work 🤔

2018-11-20 12:11 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +                case 400:
After doing manual testing with error scenarios as documented in https://stripe.com/docs/testing#cards-responses, I can confirm the error code returned is 402 and the response looks something like
```
{
  "error": {
    "charge": "ch_1DYXGiHj08j2jFuB0QNS2Qm9",
    "code": "processing_error",
    "doc_url": "https://stripe.com/docs/error-codes/processing-error",
    "message": "An error occurred while processing your card. Try again in a little bit.",
    "type": "card_error"
  }
}
```

2018-11-21 11:05 UTC, kbottla requested changes
It looks good overall 👍. Very minor comments/suggestions.

2018-11-21 11:05 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/DownstreamException.java
> +        this.message = message;
Can it be `super(message)`?  A call on exception e.getMessage() not likely to return anything

2018-11-21 11:05 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/json/StripeCreateChargeResponse.java
> +public class StripeCreateChargeResponse {
Can we please name it to StripeChargeResponse to be consistent with all other response object naming

2018-11-21 11:05 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +            GatewayError gatewayError = new GatewayError(stripeErrorResponse.getError().getMessage(), GENERIC_GATEWAY_ERROR);
This works, but we have static factory methods for specific use cases. `GatewayError.baseError(msg)` ?

2018-11-21 11:05 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +        GatewayError gatewayError = new GatewayError("There was an internal server error. ErrorId: " + errorId, UNEXPECTED_HTTP_STATUS_CODE_FROM_GATEWAY);
This works, but we have static factory methods for specific use cases. `GatewayError.unexpectedStatusCodeFromGateway(msg)` ?

2018-11-21 11:05 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/handler/StripeCaptureHandler.java
> +            GatewayError gatewayError = new GatewayError(stripeErrorResponse.getError().getMessage(), GENERIC_GATEWAY_ERROR);
Same as above with using static factory methods.

2018-11-21 11:05 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/handler/StripeCaptureHandler.java
> +            GatewayError gatewayError = new GatewayError("An internal server error occurred. ErrorId: " + errorId, UNEXPECTED_HTTP_STATUS_CODE_FROM_GATEWAY);
Same as above with using static factory methods.

2018-11-21 11:05 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeResourceITest.java
> +                .body("message", is("Your card has expired."));
Not sure how this message gets propagated to frontend. Do we present as is to the user in frontend?

2018-11-21 11:55 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/json/StripeCreateChargeResponse.java
> +public class StripeCreateChargeResponse {
I'd prefer it to be StripeChargeResponse as it makes it clear the object is meant to be deserialized from the action of creating a charge. It would make it confusing in the future when we implement refund and cancel if this object were named StripeChargeResponse.

2018-11-21 11:58 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +            GatewayError gatewayError = new GatewayError(stripeErrorResponse.getError().getMessage(), GENERIC_GATEWAY_ERROR);
Personally I'd like to keep it `new GatewayError(stripeErrorResponse.getError().getMessage(), GENERIC_GATEWAY_ERROR);` as it is very readable in the sense that I know we're returning a `GENERIC_GATEWAY_ERROR` type and I don't have to go into the `GatewayError.baseError` method to ascertain the error type. Also if I'm not meant to use the `new GatewayError` constructor it shouldn't be there for me to use...

2018-11-21 11:58 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/DownstreamException.java
> +        this.message = message;
good spot, will change

2018-11-21 12:19 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/json/StripeCreateChargeResponse.java
> +public class StripeCreateChargeResponse {
👍

2018-11-21 12:34 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +            GatewayError gatewayError = new GatewayError(stripeErrorResponse.getError().getMessage(), GENERIC_GATEWAY_ERROR);
In my opinion, this is probably leading to multiple approaches to the way we construct GatewayError in codebase and also have to update code throughout if we decide to change `GENERIC_GATEWAY_ERROR` to something else.

2018-11-21 13:01 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeResourceITest.java
> +                .body("message", is("Your card has expired."));
It's up to the self-service and publicapi to decide how they would want to deal with errors and it's not really our concern here.

2018-11-21 13:02 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +            GatewayError gatewayError = new GatewayError(stripeErrorResponse.getError().getMessage(), GENERIC_GATEWAY_ERROR);
If we want to lock down how we construct GatewayError that's probably a discussion for the wider team and would be out of scope for this PR. Refactoring `GENERIC_GATEWAY_ERROR` wouldn't be hard either as IntelliJ will do it nicely for us.

2018-11-21 13:07 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +            GatewayError gatewayError = new GatewayError(stripeErrorResponse.getError().getMessage(), GENERIC_GATEWAY_ERROR);
but i agree it would be worth bringing this up at a code quality meeting or something!

2018-11-21 13:09 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/stripe/StripeResourceITest.java
> +                .body("message", is("Your card has expired."));
The reason for asking is - 
If this is used as is, we may end up showing error stripe specific error messages received to the users. It is fine, if not used.
Don't think it is used as is by frontend which is fine

2018-11-21 13:22 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +            GatewayError gatewayError = new GatewayError(stripeErrorResponse.getError().getMessage(), GENERIC_GATEWAY_ERROR);
i have changed it to use the static method :) i didn't make the GatewayError constructor private though as it would introduce a lot of code changes to this PR. that can be done in a separate PR.

2018-11-21 13:27 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +            GatewayError gatewayError = new GatewayError(stripeErrorResponse.getError().getMessage(), GENERIC_GATEWAY_ERROR);
👍

2018-11-21 13:27 UTC, kbottla approved these changes

2018-11-21 18:15 UTC, merged