PP-4314 Add ApplePayAuthoriser interface to payment providers
alphagov/pay-connector pull request #851
Opened 2018-11-19 15:39 UTC by simad

- With the introduction of apple pay there are basically two ways to move forward: either by shoeorning an apple pay auth order in the normal "card" authorise path, or by creating a separate interface
 - As we are currently refactoring connector and will probably get rid of the PaymentProviders interface, I have opted for separating the two paths. This allow us to implement the `ApplePayAuthoriser` interface only for payment providers which support apple pay (currently sandbox and worldpay) without having to do things like throw an unsupported operation exception for the rest of providers. This also means having a bit of duplication which will hopefully be extracted away as we move forward with the refactorings

2018-11-20 17:21 UTC, alexbishop1 requested changes
This looks good.

I’m still not sure about the `ApplePayAuthoriser` interface itself. I can see that it’s nice that we indicate which payment gateways support Apple Pay but it doesn’t really have a plain card payment parallel and it’s a shame that the actual implementation ends up in the already-doing-more-than-it-probably-should-be `SandboxPaymentProvider` and `WorldpayPaymentProvider` I may ponder on this a bit more but I have no qualms with the functionality itself.

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        if (authCardDetails.getCardNo().length() > 6) {
I assume for Apple Pay this is going to be under six digits (because we don’t have a full card number, just the last four digits) but I don’t fully understand what’s going on. Could you explain it to me please?

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxCardNumbers.java
> +                .anyMatch(a -> a.contains(cardNumber));
Not sure why we’re doing substring matches now

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxCardNumbers.java
> +            "0002");
I think we’ve reached the stage where we need some explanation of what these numbers are — maybe we could extract each of them to appropriately-named constants

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxPaymentProvider.java
> +            LOGGER.info("sandbox auth has been called with an error card number");
Not sure logging like this is going to be very useful in non-local environments with an identifier for the payment

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxPaymentProvider.java
> +    public GatewayResponse<BaseAuthoriseResponse> authorise(ApplePayAuthorisationGatewayRequest request) {
We now have three methods named `authorise`, which I found quite hard to follow. I understand the public ones may need to share the name because polymorphism but I think at least the `private` one could be renamed. Also, can we have the public methods at the top with the private methods at the bottom?

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxPaymentProvider.java
> +        return authorise(lastDigitsCardNumber);
Not convinced about sometimes passing a full card number to the private `authorise(String)` method and sometimes passing the last four digits. Could these be separate methods? I think this would also mean we don’t need to do the substring stuff in `SandboxCardNumbers` (at the expense of a little code duplication).

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +    public GatewayResponse<BaseAuthoriseResponse> authorise3dsResponse(Auth3dsResponseGatewayRequest request) {
Hooray for more precise types!

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                .with3dsRequired(request.getGatewayAccount().isRequires3ds())
A bit tangential, but why does this matter? I thought with Apple Pay we send through 3D Secure authentication stuff (or Apple Pay authentication stuff disguised as 3D Secure authentication stuff) with every authorisation request.

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureService.java
> +        return paymentProvider;
This change isn’t really doing anything

2018-11-20 17:21 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/PaymentProviders.java
> +    public ApplePayAuthoriser getAppleAuthoriserFor(ChargeEntity chargeEntity) {
`getApplePayAuthoriserFor`

2018-11-20 17:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/sandbox/SandboxPaymentProviderTest.java
> +        AppleDecryptedPaymentData applePaymentData = AuthUtils.ApplePay.buildDecryptedPaymentData("Mr. Payment", "mr@payment.test", "4242");
It would be nice if `"4242"` could be an appropriately-named constant

2018-11-20 17:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/sandbox/SandboxPaymentProviderTest.java
> +    }
Can we do a test for an authorisation error?

2018-11-20 17:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProviderTest.java
> +        worldpayPaymentProvider.authorise(getApplePayAuthorisationRequest(chargeEntity));
I have to confess that I was staring at this test for ages before I realised, “This is the Apple Pay bit! This is what makes this test different from the others!”

I think as we’ve created more variants of the authorisation tests, a lot of boilerplate has been copied and pasted between them. We could perhaps try to consolidate some of it into a `@Before` method in a follow-up PR.

2018-11-20 17:21 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/util/AuthUtils.java
> +        public static AppleDecryptedPaymentData buildDecryptedPaymentData(String cardHolderName, String email, String lastFourDigitsCardNumber) {
Recently (very recently: perhaps after you started doing this work), we’ve done some work to remove a lot of test fixture stuff from `AuthUtils` in favour of `AuthCardDetailsFixture`. Could we do something the Apple Pay authorisation test fixtures? Perhaps in a follow-up PR?

2018-11-20 17:58 UTC, simad commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        if (authCardDetails.getCardNo().length() > 6) {
This is where we are setting the details for last 4 digits and first 6 digits - you're right, in case of apple pay cardNo will have 4 digits, so that `FirstDigitsCardNumber.of(StringUtils.left(authCardDetails.getCardNo(), 6))` would not pass the validation because it assumes we have 6 digits. So, I am not setting the first 6 digits in case we don't have the full card number.
This means first six digits will be null for apple pay payments

2018-11-20 17:59 UTC, simad commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxCardNumbers.java
> +                .anyMatch(a -> a.contains(cardNumber));
it's not a substring match, I forgot to rename `a` to a properly named rejectedCardsList or something - that function is just checking that the list of rejected cards contains cardNumber. Will rename, sorry!

2018-11-20 18:00 UTC, simad commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxCardNumbers.java
> +            "0002");
👍 sounds good

2018-11-21 09:54 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxCardNumbers.java
> +                .anyMatch(a -> a.contains(cardNumber));
Of course, it’s doing `contains` on a `List`, not a `String` (`String` doesn’t even have `contains`!)

2018-11-21 10:13 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        if (authCardDetails.getCardNo().length() > 6) {
It’s a shame that it’s not obvious from this specific code under which circumstances the card number won’t have the first six digits and it’s unfortunate that the card number is sometimes a card number and other times only has the last four digits. More broadly, I don’t really understand why we have two `AuthorisationDetails` implementations used for Apple Pay: `AuthCardDetails` and `AppleDecryptedPaymentData`. I would have hoped we could have one class that contains just what’s available.

2018-11-21 10:26 UTC, simad commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        if (authCardDetails.getCardNo().length() > 6) {
AuthCardDetails is what is used by jpa to put stuff in the database, that's the problem with the mashup of json + jpa + domain object we have. So I have to get our model AppleDecryptedPaymentData and kind of match it to what we store in the db (AuthCardDetails).

2018-11-21 10:26 UTC, simad commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        if (authCardDetails.getCardNo().length() > 6) {
If you have a better idea / better way to do this, it would be awesome!

2018-11-21 10:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        if (authCardDetails.getCardNo().length() > 6) {
Ah, our wonderful domain objects that are JSON, JPA, floor wax and dessert topping! At least we have a rough plan for gradually unpicking this now.

So is it that `AppleDecryptedPaymentData` is the incoming JSON, which then gets converted to `AuthCardDetails` (which can also represent incoming JSON but isn’t in this case) so it can be persisted to the database?

I guess leave it as it is for now and hopefully we’ll make it better later. It might be an idea to put a comment next to `if (authCardDetails.getCardNo().length() > 6)` explaining that for Apple Pay authorisations the card number is only the four digits (a comment that will hopefully become unnecessary when future refactoring makes our code wonderfully self-describing and comprehensible).

2018-11-21 10:55 UTC, simad commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        if (authCardDetails.getCardNo().length() > 6) {
precisely :( `AppleDecryptedPaymentData` is the decrypted version of the incoming encrypted json payload, and it is a fairly pure pojo, but AuthCardDetails is both what comes from frontend AND what's stored in the db :(
I'll try to think of a way to make `authCardDetails.getCardNo().length() > 6` not needing a comment, but if it takes too long I might just leave it and improve things later on. Thank you :)

2018-11-21 11:29 UTC, alexbishop1 commented
As promised, I pondered a bit more about the `ApplePayAuthoriser` interface. I like the direction it’s going in, which is similar to the new `CaptureHandler` interface in that it encapsulates the methods for a single payment gateway operation.

The main difference is in the implementations: while the concrete implementation of`ApplePayAuthoriser` is`WorldpayPaymentProvider` (or equivalent for other gateways), the concrete implementation of `CaptureHandler` is `WorldpayCaptureHandler` (or equivalent for other gateways). Furthermore, while the appropriate `ApplePayAuthoriser` implementation is obtained from `PaymentProviders`, the appropriate `CaptureHandler` is obtained from the `WorldpayPaymentProvider` or whatever.

Could you make `ApplePayAuthoriser` behave a bit more like `CaptureHandler` please? That is, rename it to `ApplePayAuthorisationHandler`, put the concrete implementations in new `WorldpayApplePayAuthorisationHandler` and `SandboxApplePayAuthorisationHandler` classes (rather than `WorldpayPaymentProvider` and `SandboxPaymentProvider` respectively) and make it so that the `ApplePayAuthorisationHandler` instance is obtained from the `WorldpayPaymentProvider` and `SandboxPaymentProvider` (rather than the `PaymentProviders` class).

I hope that we’re intending to continue down this path and will eventually have interfaces like `CardAuthorisationHandler` (for plain card authorisations), `Card3dsResponseAuthorisationHandler` (for authorisations using the response of 3D Secure authentication) and `RefundHandler` etc., each with their own gateway-specific implementations. This would stop `WorldpayPaymentProvider` and friends from being such huge beasts (and I’m quite looking forward to breaking up the monstrous test classes: not only would they be smaller, but it would be easier to share common code in a `@Before` method because each test class would only be dealing with a single operation).

2018-11-21 11:46 UTC, simad commented on src/test/java/uk/gov/pay/connector/gateway/sandbox/SandboxPaymentProviderTest.java
> +        AppleDecryptedPaymentData applePaymentData = AuthUtils.ApplePay.buildDecryptedPaymentData("Mr. Payment", "mr@payment.test", "4242");
👍

2018-11-21 11:46 UTC, simad commented on src/main/java/uk/gov/pay/connector/gateway/PaymentProviders.java
> +    public ApplePayAuthoriser getAppleAuthoriserFor(ChargeEntity chargeEntity) {
👍

2018-11-21 11:51 UTC, simad commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxPaymentProvider.java
> +            LOGGER.info("sandbox auth has been called with an error card number");
removed those lines

2018-11-21 11:52 UTC, simad commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +    public GatewayResponse<BaseAuthoriseResponse> authorise3dsResponse(Auth3dsResponseGatewayRequest request) {
It is still a super clunky interface but it didn't make any sense to have a generic response when we know that authorise will have an authorise response :(

2018-11-21 11:53 UTC, simad commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxPaymentProvider.java
> +        return authorise(lastDigitsCardNumber);
they could be separate of course, but it is literally the same code

2018-11-21 11:58 UTC, simad commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CardCaptureService.java
> +        return paymentProvider;
I had originally removed the getPaymentProviderFor and then put it back to reduce the change, copy paste fail

2018-11-21 12:08 UTC, simad commented on src/main/java/uk/gov/pay/connector/gateway/worldpay/WorldpayPaymentProvider.java
> +                .with3dsRequired(request.getGatewayAccount().isRequires3ds())
true, it does not matter at all. copy paste again :)

2018-11-22 13:55 UTC, simad commented on src/test/java/uk/gov/pay/connector/util/AuthUtils.java
> +        public static AppleDecryptedPaymentData buildDecryptedPaymentData(String cardHolderName, String email, String lastFourDigitsCardNumber) {
Sure, I'll do it in the next PR. Cheers :)

2018-11-22 19:06 UTC, alexbishop1 approved these changes
Thanks for making the changes!

I think moving the Apple Pay authorisation logic into separate gateway-specific classes worked out well and it’s great that this meant that the changes to `WorldpayPaymentProvider` and `SandboxPaymentProvider` basically thinned out to nothing and that some of my review comments ceased to be relevant.

I’ve left a few comments but there’s nothing serious enough to withhold approval. Could you look at addressing them in a follow-up PR (perhaps along with `AuthUtils` to `AuthCardDetailsFixture` migration)?

2018-11-22 19:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        return authCardDetails.getCardNo().length() > 6;
Maybe a comment like `// Apple Pay etc. don’t give us a full card number, just the last four digits here` might make the _why_ clearer?

2018-11-22 19:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +        throw new UnsupportedOperationException("Apple Pay is not supported for EPDQ");
Minor, but it’s “ePDQ”

2018-11-22 19:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/SandboxCardNumbers.java
> +            new CardError(AUTHORISATION_REJECTED, "The CVC code is incorrect."));
I find this change from the “bad” card maps being `Map<String, CardError>` to `Map<List<String>, CardError>` makes the look-up logic hard to follow and we kind of lose the benefit of it being a map because we have to sequentially look at each key until we find the one we want.

I think it was clearer when it was `Map<String, CardError>`. I assume the change to `Map<List<String>, CardError>` was to avoid lots of repitition from many card numbers being mapped to the same `CardError`. We could do something like this to handle that:

```java

private static Map<String, CardError> ERROR_CARDS = Stream.of(
        PROCESSING_ERROR_CARD_NUMBER,
        PROCESSING_ERROR_APPLE_PAY_LAST_DIGITS_CARD_NUMBER)
        .collect(toMap(
                Function.identity(),
                cardNumber -> new CardError(AUTHORISATION_ERROR, "This transaction could be not be processed.")));
```

Then `isErrorCard(String)` and `cardErrorFor(String)` can go back to how they used to be.

2018-11-22 19:06 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/applepay/SandboxApplePayAuthorisationHandler.java
> +        LOGGER.info("sandbox apple pay auth");
I thought this line was going away

2018-11-22 19:06 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/sandbox/applepay/SandboxApplePayAuthorisationHandlerTest.java
> +    public void authorise_shouldGetGatewayErrorWhenLastDigitsCardNumbersAreExpectedToFailForAuthorisation_forApplePay() {
Thanks for adding an authorisation error test

2018-11-22 19:06 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/sandbox/applepay/SandboxApplePayAuthorisationHandlerTest.java
> +}
Hooray! This stuff this is testing is small enough that the test class only needs to be 83 lines!

2018-11-23 09:54 UTC, simad commented on src/main/java/uk/gov/pay/connector/gateway/sandbox/applepay/SandboxApplePayAuthorisationHandler.java
> +        LOGGER.info("sandbox apple pay auth");
It will in the next pr 🗡

2018-11-23 09:54 UTC, merged

2018-11-23 11:22 UTC, simad commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java
> +        return authCardDetails.getCardNo().length() > 6;
oki doki

2018-11-23 11:23 UTC, simad commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqPaymentProvider.java
> +        throw new UnsupportedOperationException("Apple Pay is not supported for EPDQ");
rOGER