PP-4374 Introduced EpdqNotificationService
alphagov/pay-connector pull request #859
Opened 2018-11-22 14:25 UTC by kbottla

## WHAT

Part of refactoring notification handling (see https://github.com/alphagov/pay-connector/pull/787 for the original full attempt...). Introducing gateway specific service objects to handle notifications instead of generalised notification handler (`NotificationService`). We don't need a generalised `NotificationService` as each gateway notification has dedicated notification resource endpoint. Having separate service object will make it easier to understand and follow through the path.  

- Added `EpdqNotificationService` to delegate EPDQ notification processing to service instead of a generic handler.
- NotificationResource for EPDQ notifications now uses `EpdqNotificationService`

Note that any existing code that handles EPDQ notifications still stays and will be removed in subsequent PRs

## HOW 
- Existing tests in `EpdqNotificationResourceITest` should continue to pass
- All tests in `EpdqNotificationServiceTest`, `EpdqNotificationServiceStatusMapperTest` should pass

2018-11-22 15:55 UTC, oswaldquek commented
Can there be an explaining of how this is a refactor? It seems to be adding new functionality (the EpdqNotificationService) rather than refactoring existing functionality. At least it's not clear to me...

2018-11-22 16:20 UTC, kbottla commented
@oswaldquek Added more info to description. Hope this helps.

2018-11-22 16:41 UTC, oswaldquek commented
@kbottla thanks, that helped

2018-11-23 10:00 UTC, oswaldquek requested changes

2018-11-23 10:00 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +        if (!verifyNotificationSignature(notification, charge)) {
i think this line would read better as `if (!notificationSignatureVerififed(notification, charge)) {`

2018-11-23 10:00 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<ChargeStatus> newChargeStateForChargeNotification(String notificationStatus, ChargeStatus chargeStatus) {
why is this method not private? it's not used outside of this class

2018-11-23 10:00 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<RefundStatus> newRefundStateForRefundNotification(String notificationStatus) {
why is this method not private? it's not used outside of this class

2018-11-23 10:00 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotification.java
> +    public class EpdqParseException extends Exception {
Can this be moved to its own class? It feels like the responsibility of `EpdqNotification` is to hold information about the notification from epdq, not to hold exception classes.

2018-11-23 10:00 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +public class EpdqNotificationServiceStatusMapperTest {
Are you aware of this test? https://github.com/alphagov/pay-connector/blob/32a0acca2b169c9c4ca34d2e8d54bcf45f293ba4/src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqStatusMapperTest.java
It looks like there's an already existing `EpdqStatusMapper`: https://github.com/alphagov/pay-connector/blob/32a0acca2b169c9c4ca34d2e8d54bcf45f293ba4/src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqStatusMapper.java

2018-11-23 10:00 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceTest.java
> +    public void givenAChargeCapturedNotification_chargeNotificationProcessorInvokedWithNotificationAndCharge() throws EpdqNotification.EpdqParseException {
`EpdqNotification.EpdqParseException` does not need to be thrown

2018-11-23 10:00 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceTest.java
> +    private EpdqNotificationService notificationService;
There doesn't seem to be any test where the notification signature is not verified.

2018-11-23 10:00 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqNotificationResourceITest.java
> +        String epdqAuthorisedNotificationCode = "5";
It would be clearer if `"5"` was replaced with `EpdqStatusMapper.EPDQ_AUTHORISED`

2018-11-23 10:00 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqNotificationResourceITest.java
> +        String epdqAuthorisedCancelledNotificationCode = "6";
It would be clearer if "6" was replaced with EpdqStatusMapper.EPDQ_AUTHORISED_CANCELLED

2018-11-23 10:12 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<ChargeStatus> newChargeStateForChargeNotification(String notificationStatus, ChargeStatus chargeStatus) {
this method might not be needed as there is https://github.com/alphagov/pay-connector/blob/32a0acca2b169c9c4ca34d2e8d54bcf45f293ba4/src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqStatusMapper.java

2018-11-23 10:12 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<RefundStatus> newRefundStateForRefundNotification(String notificationStatus) {
this method might not be needed as there is https://github.com/alphagov/pay-connector/blob/32a0acca2b169c9c4ca34d2e8d54bcf45f293ba4/src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqStatusMapper.java

2018-11-23 11:30 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +public class EpdqNotificationServiceStatusMapperTest {
Yes, I am aware of it. It was used in the previous handler model. We now have status mapping with in EpdqNotificationService which handles charge and refund statuses separately (`newChargeStateForChargeNotification(), newRefundStateForRefundNotification()`).

We will eventually be getting rid of existing unused code but in separate PR. But including it current PR will make it too big.

2018-11-23 11:30 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceTest.java
> +    public void givenAChargeCapturedNotification_chargeNotificationProcessorInvokedWithNotificationAndCharge() throws EpdqNotification.EpdqParseException {
👍

2018-11-23 11:30 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqNotificationResourceITest.java
> +        String epdqAuthorisedNotificationCode = "5";
👍 Good spot. Updated, but to `EpdqNotification.StatusCode.EPDQ_AUTHORISED;`

2018-11-23 11:30 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/epdq/EpdqNotificationResourceITest.java
> +        String epdqAuthorisedCancelledNotificationCode = "6";
Updated, but to `EpdqNotification.StatusCode.EPDQ_AUTHORISED_CANCELLED;`

2018-11-23 11:30 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<ChargeStatus> newChargeStateForChargeNotification(String notificationStatus, ChargeStatus chargeStatus) {
This is slightly inconvenient for me too but need to keep it package private to be able to add tests specific for Status mapping `EpdqNotificationServiceStatusMapperTest`. I am happy to change it if there is any better way to test status mapping only.
 
`EpdqStatusMapper` will be removed as it is no longer required by new EpdqNotificationService but in a separate PR.

2018-11-23 11:30 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<RefundStatus> newRefundStateForRefundNotification(String notificationStatus) {
This is slightly inconvenient for me too but need to keep it package private to be able to add tests specific for Status mapping `EpdqNotificationServiceStatusMapperTest`. I am happy to change it if there is any better way to test status mapping only.
 
`EpdqStatusMapper` will be removed as it is no longer required by new EpdqNotificationService but in a separate PR.

2018-11-23 11:30 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotification.java
> +    public class EpdqParseException extends Exception {
👍

2018-11-23 11:30 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +        if (!verifyNotificationSignature(notification, charge)) {
I think `isValidNotificationSignature` defines it well.

2018-11-23 11:30 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceTest.java
> +    private EpdqNotificationService notificationService;
New test available `shouldNotUpdateIfShaPhraseExpectedIsIncorrect`

2018-11-23 13:16 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<ChargeStatus> newChargeStateForChargeNotification(String notificationStatus, ChargeStatus chargeStatus) {
So one way to do it is to extract the `newChargeStateForChargeNotification` and `newRefundStateForRefundNotification` into another class, just like the existing `EpdqStatusMapper`. Another way would be to test it by calling `EpdqNotificationService.handleNotificationFor` and verifying `chargeNotificationProcessor` was invoked with the correct new charge status.

2018-11-23 13:17 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationServiceStatusMapperTest.java
> +public class EpdqNotificationServiceStatusMapperTest {
ok, understood 👍

2018-11-23 13:24 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<ChargeStatus> newChargeStateForChargeNotification(String notificationStatus, ChargeStatus chargeStatus) {
i don't think it's good practice to make method non-private for the sake of testing

2018-11-23 13:24 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<ChargeStatus> newChargeStateForChargeNotification(String notificationStatus, ChargeStatus chargeStatus) {
Extracting into new classes will give same visibility as it is now. Doesn't make much difference.

testing `handleNotificationFor` seems to be an overkill to test different statuses exhaustively compared to current testing.

2018-11-23 13:42 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<ChargeStatus> newChargeStateForChargeNotification(String notificationStatus, ChargeStatus chargeStatus) {
it doesn't set a good precedent if we make methods non-private just because it will make testing easier... we should test things the right way even if it's more troublesome. we shouldn't modify production code just to make testing code easier.

2018-11-23 14:48 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<ChargeStatus> newChargeStateForChargeNotification(String notificationStatus, ChargeStatus chargeStatus) {
Package-private still encapsulates a level of detail. So personally won't be an issue to have  `static` methods as package-private given they don't have any state and also doesn't alter state. It all comes down to context. But to get out of the deadlock I have changed them to private 😄

2018-11-23 15:37 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/gateway/epdq/EpdqNotificationService.java
> +    static Optional<ChargeStatus> newChargeStateForChargeNotification(String notificationStatus, ChargeStatus chargeStatus) {
yeah, I don't think we need to be precious about private versus package private. Ultimately we're not writing library code here - if something is a tad more visible than it strictly needs to be, we're not going to be paying for it in 10 years time

2018-11-23 15:43 UTC, oswaldquek approved these changes

2018-11-23 15:44 UTC, kbottla commented
Thanks @oswaldquek

2018-11-23 15:44 UTC, merged