PP-4290 Add prepaid corporate card surcharge
alphagov/pay-connector pull request #874
Opened 2018-11-26 15:21 UTC by DanailMinchev

## WHAT

This PR updates  surcharge calculator to consider prepaid cards and has some refactoring of CorporateCardSurchargeCalculator tests

## HOW 

- Added `PayersPrepaidCardType` that should be used to map from and to JSON when
  dealing with prepaid nature of the card (`PREPAID`, `NOT_PREPAID`, `UNKNOWN`)
  used to make a payment. This is also used to calculate corporate
  surcharges, based on other rules.
- Modified `CorporateCardSurchargeCalculator` to consider prepaid card surcharge
  when calculating the value in `CorporateCardSurchargeCalculator#getCorporateCardSurchargeFor`
- Split `CorporateCardSurchargeCalculatorTest` test into code regions to
  help navigation within the file
- Added tests to cover all scenarios
- Refactored duplicated setup and assertions within `CorporateCardSurchargeCalculatorTest` to improve clarity

with @danworth

2018-11-26 17:38 UTC, alexbishop1 requested changes
This looks fine but I have a few suggestions to improve clarity and intent

2018-11-26 17:38 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/util/CorporateCardSurchargeCalculator.java
> +                return Optional.of(chargeEntity.getGatewayAccount().getCorporateCreditCardSurchargeAmount());
I think we might want to rename `getCorporateCreditCardSurchargeAmount()` to `getCorporateNonPrepaidCreditCardSurchargeAmount()` (and rename `getCorporateDebitCardSurchargeAmount()` to `getCorporateNonPrepaidDebitCardSurchargeAmount()`) to make the exclusiveness obvious

2018-11-26 17:38 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/util/CorporateCardSurchargeCalculator.java
> +
As I’ve discussed with you in person, I really think it would make this simpler if we separated out calculating the surcharge value (which may be zero) from wrapping it up in an `Optional`. We wouldn’t need all these `> 0` checks then, which would make the logic simpler.

I’m also not sure about all the `isCreditSurcharge(AuthCardDetails, ChargeEntity)` etc. private methods. Although they make the public method simpler, the method calls obscure the actual logic and make it harder to grasp what’s going on at a higher level.

I think something like this (in another method) would be clearer:

```java
if (authCardDetails.isCorporateCard()) {
    GatewayAccountEntity gatewayAccount = chargeEntity.getGatewayAccount();
    switch (authCardDetails.getPayersPrepaidCardType()) {
        case NOT_PREPAID:
            switch (authCardDetails.getPayersCardType()) {
                case CREDIT:
                    return gatewayAccount.getCorporateCreditCardSurchargeAmount();
                case DEBIT:
                    return gatewayAccount.getCorporateDebitCardSurchargeAmount();
                case CREDIT_OR_DEBIT:
                    return 0;
            }
        case PREPAID:
            switch (authCardDetails.getPayersCardType()) {
                case CREDIT:
                    return gatewayAccount.getPrepaidCorporateCreditCardSurchargeAmount();
                case DEBIT:
                    return gatewayAccount.getPrepaidCorporateDebitCardSurchargeAmount();
                case CREDIT_OR_DEBIT:
                    return 0;
            }
        case UNKNOWN:
            return 0;
    }
}
return 0;
```

As I said in person, I wouldn’t be afraid to put this in another class and have this existing class just call it and wrap the result into an `Optional`.

2018-11-26 17:38 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/model/PayersPrepaidCardType.java
> +public enum PayersPrepaidCardType {
Not really sure that `PayersPrepaidCardType` fully captures what this represents (and it’s quite similar to `PayersCardType`). Maybe `PayersCardPrepaidStatus`?

2018-11-26 17:38 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/util/CorporateCardSurchargeCalculatorTest.java
> +    private static final long CREDIT_CARD_SURCHARGE_AMOUNT = 50L;
I think we want `NON_PREPAID` in this (and friends)

2018-11-26 17:38 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/util/CorporateCardSurchargeCalculatorTest.java
> +        GatewayAccountEntity gatewayAccountEntity = defaultGatewayAccountEntity();
I think it would be clearer where the `GatewayAccountEntity` comes from if this line was:

```java
GatewayAccountEntity gatewayAccountEntity = ChargeEntityFixture.defaultGatewayAccountEntity();
```

2018-11-26 17:51 UTC, DanailMinchev commented on src/main/java/uk/gov/pay/connector/charge/util/CorporateCardSurchargeCalculator.java
> +
👍 yes we were thinking to do it as a next change, as discussed this can be implemented in this PR

2018-11-26 17:58 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/util/CorporateCardSurchargeCalculator.java
> +
Yep, this looks much cleaner and a great suggestion. Happy to put it in this PR as Dan say's.

2018-11-26 18:00 UTC, danworth commented on src/main/java/uk/gov/pay/connector/gateway/model/PayersPrepaidCardType.java
> +public enum PayersPrepaidCardType {
Agreed `PayersCardPrepaidStatus` seems clearer and more distinguishable from `PayersCardType`.

2018-11-27 16:04 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/util/CorporateCardSurchargeCalculator.java
> +
We've implemented this suggestion.

2018-11-27 17:46 UTC, alexbishop1 requested changes
Looks good — just a couple of small requests

2018-11-27 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/util/FixedSurchargeCalculator.java
> +class FixedSurchargeCalculator {
A bit picky but can we make this specific? `FixedCorporateCardSurchargeCalculator`

2018-11-27 17:46 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/charge/util/FixedSurchargeCalculator.java
> +    }
This certainly isn’t the most beautiful code in the world but it’s nice it’s fairly comprehensible and all fits on screen at once!

2018-11-27 17:46 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/util/FixedSurchargeCalculatorTest.java
> +    }
I’d be quite tempted to inline these two methods into each of the tests. It would make the `FixedSurchargeCalculator.calculate(AuthCardDetails, ChargeEntity)` calls and assertions obvious. It would make each test larger, of course, but only by two lines.

2018-11-28 13:39 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/util/FixedSurchargeCalculator.java
> +class FixedSurchargeCalculator {
Not picky at all, good suggestion. Will do.

2018-11-28 13:57 UTC, danworth commented on src/test/java/uk/gov/pay/connector/charge/util/FixedSurchargeCalculatorTest.java
> +    }
OK, now we've removed the Optional presence/get logic its shrunk these private methods. Agreed that the greater clarity around calls and assertions is worth the extra two lines. Will do.

2018-11-28 13:58 UTC, danworth commented on src/main/java/uk/gov/pay/connector/charge/util/FixedSurchargeCalculator.java
> +    }
Agreed, thanks for the code :)

2018-11-28 17:37 UTC, alexbishop1 approved these changes

2018-11-29 08:35 UTC, rhowe-gds commented
Ignore Snyk - it's clearly having a moment. You haven't changed any dependencies so there's nothing for it to validate anyway

2018-11-29 08:36 UTC, merged