WIP PP 4439 implement stripe refund
alphagov/pay-connector pull request #889
Opened 2018-11-30 16:39 UTC by georgeracu

## WHAT
- Implemented Stripe full refund. This is different from the partial
    refund in that we don't specify the amount. This behaviour will trigger
    a full refund. We also specify to reverse funds, which means that money
    will be transferred from gateway account

2018-12-03 15:19 UTC, oswaldquek requested changes

2018-12-03 15:19 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +    public void shouldRefundSuccessfully_forStripe() {
i'm not convinced this test is really needed. it's testing ChargeRefundService, not stripe.

2018-12-03 15:19 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandlerTest.java
> +package uk.gov.pay.connector.gateway.stripe.handler;
Can we make things consistent and move this test to the `uk.gov.pay.connector.gateway.stripe` package please. All the other tests are in this package.

2018-12-03 15:19 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandlerTest.java
> +public class StripeRefundHandlerTest {
can we have a test for 1) partial refund 2) refunding an already refunded charge and 3) trying to refund more money than is left on a charge? it might take some manual running to see the actual responses from Stripe for these scenarios.

2018-12-03 15:19 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandler.java
> +                    format("gateway-operations.%s.%s.cancel", gatewayAccount.getGatewayName(), gatewayAccount.getType()));
it should be `gateway-operations.%s.%s.refunds` instead

2018-12-03 15:19 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandler.java
> +    /**
i'm not sure about these comments below as you're always passing in an amount. if the amount were an optional then it would make more sense to have these comments.

2018-12-03 16:17 UTC, georgeracu commented on src/main/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandler.java
> +                    format("gateway-operations.%s.%s.cancel", gatewayAccount.getGatewayName(), gatewayAccount.getType()));
Well spotted :)

2018-12-03 16:17 UTC, georgeracu commented on src/main/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandler.java
> +    /**
I will remove them.

2018-12-03 16:18 UTC, georgeracu commented on src/test/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandlerTest.java
> +package uk.gov.pay.connector.gateway.stripe.handler;
Moved :)

2018-12-03 16:18 UTC, georgeracu commented on src/test/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandlerTest.java
> +public class StripeRefundHandlerTest {
Unfortunately there's no difference between full refund and partial refund in the response.
I added tests for refunding already refunded and refunding more than available

2018-12-03 16:19 UTC, georgeracu commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +    public void shouldRefundSuccessfully_forStripe() {
Hmm, you are probably right. No value in having it

2018-12-04 10:44 UTC, oswaldquek approved these changes

2018-12-04 10:54 UTC, merged