WIP PP-4439 remove transaction flow
alphagov/pay-connector pull request #896
Opened 2018-12-04 16:18 UTC by georgeracu

## WHAT
- Remove last traces of TransactionFlow and co.
- Make public methods annotated with `@Transactional` so they will be picked up by GuicePersist
- Remove custom `merge()` calls as they are now handled by JPA

2018-12-05 11:38 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
> +    private void logUnsuccessfulResponseReasons(ChargeEntity chargeEntity, GatewayResponse<BaseCancelResponse> gatewayResponse) {
not a big deal but does this really need to be in its own method? it's pretty much a one-liner. i think i'm just trying to draw a line when things should or should not be refactored into its own method and i think code would be neater if there were less methods.

2018-12-05 11:48 UTC, oswaldquek requested changes
Not so much a request of changes, but some things to consider. I'm happy to approve if you don't think my suggestions are necessary.

2018-12-05 11:48 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +         * todo: refactor this code to not return empty String
i don't think it's too difficult to do this refactor in this PR? might as well ;)

2018-12-06 16:56 UTC, georgeracu commented on src/main/java/uk/gov/pay/connector/charge/service/ChargeExpiryService.java
> +    private void logUnsuccessfulResponseReasons(ChargeEntity chargeEntity, GatewayResponse<BaseCancelResponse> gatewayResponse) {
👍

2018-12-06 17:01 UTC, georgeracu commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +         * todo: refactor this code to not return empty String
👍

2018-12-06 17:05 UTC, oswaldquek submitted a review, later dismissed

2018-12-07 11:46 UTC, oswaldquek approved these changes

2018-12-07 11:48 UTC, merged