PP-4509: Remove errorId
alphagov/pay-connector pull request #907
Opened 2018-12-12 15:41 UTC by oswaldquek

errorId was originally put there to enable a support person to dig deeper into
a cause of failure without returning the cause back to the client. However
using the charge external id will do just fine.

@oswaldquek

2018-12-14 15:42 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/model/request/RefundGatewayRequest.java
> +        this.externalChargeId = externalChargeId;
Really not sure about this. Refunds have references (identifiers also shared with the payment gateways) but they are not the same as the external ID of the associated charge.

2018-12-17 15:32 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/model/request/RefundGatewayRequest.java
> +        this.externalChargeId = externalChargeId;
I'll revert this back to "reference". 

When a refund entity first gets, created, the reference is not populated: https://github.com/alphagov/pay-connector/blob/8452d22a58548caca05a237221deb4e99e5f3701/src/main/java/uk/gov/pay/connector/refund/model/domain/RefundEntity.java#L87.

However when we make a RefundGatewayRequest, it's created with
```
    public static RefundGatewayRequest valueOf(RefundEntity refundEntity) {
        return new RefundGatewayRequest(
                refundEntity.getChargeEntity().getGatewayTransactionId(),
                refundEntity.getChargeEntity().getGatewayAccount(),
                String.valueOf(refundEntity.getAmount()),
                refundEntity.getExternalId());
    }
```
At this point the refundEntity's external id is null??

2018-12-17 16:59 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/model/request/RefundGatewayRequest.java
> +        this.externalChargeId = externalChargeId;
I think it works like this:

1. When a `RefundEntity` is created, it gets assigned a random new `externalId` (this is not the same as the associated charge’s `externalId`)
2. When we send the refund to the gateway (using the `RefundGatewayRequest`), we sometimes (depending on the gateway: we definitely do this for Worldpay) include the `RefundEntity`’s `externalId`, which we refer to in some of our variables and comments as our `reference`
3. When we receive the response from the gateway in `ChargeRefundService`, we populate the `reference` on the `RefundEntity` with a reference provided by the gateway — if the gateway does not provide one (Worldpay doesn’t), we use the `RefundEntity`’s `externalId` 
4. We then rely on the gateway providing this latter `reference` in subsequent notifications so we can match them up to the refund

So I think the appropriate thing to call this variable is `refundExternalId` and we should update the comments in this class so they don’t talk about sending “our reference”.

2018-12-17 17:30 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/model/request/RefundGatewayRequest.java
> +        this.externalChargeId = externalChargeId;
@alexbishop1 thanks for the clarification. i've updated RefundGatewayRequest's reference field to refundExternalId. also i realised i was not looking properly when i said the refundEntity's external id is null!

2018-12-20 12:34 UTC, alexbishop1 requested changes
Nice change and some good logging improvements

2018-12-20 12:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/model/request/RefundGatewayRequest.java
> +                .append("EvaluatedGatewayRefundRequest[\n")
Name doesn’t look right

2018-12-20 12:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/model/request/RefundGatewayRequest.java
> +                .append("\nchargeExternalId:")
This label seems lost

2018-12-20 12:34 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/gateway/stripe/handler/StripeCancelHandler.java
> +            GatewayError gatewayError = unexpectedStatusCodeFromGateway("An internal server error occurred while canceling charge_external_id: " + request.getExternalChargeId());
Don’t really need the underscores; it’s not a variable name

2018-12-20 12:34 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/gateway/stripe/StripeCancelHandlerTest.java
> +        assertThat(gatewayResponse.getGatewayError().get().getMessage(), containsString("An internal server error occurred while canceling charge_external_id: " + request.getExternalChargeId()));
Two “l”s in “cancelling” in British English

2018-12-20 12:59 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/gateway/stripe/StripeCancelHandlerTest.java
> +        assertThat(gatewayResponse.getGatewayError().get().getMessage(), containsString("An internal server error occurred while canceling charge_external_id: " + request.getExternalChargeId()));
but the less code the better! 😛

2018-12-20 13:03 UTC, alexbishop1 approved these changes
A few `charge_external_id`s hanging around in logging and exception messages but I’m not going to be petty about that

2018-12-20 13:19 UTC, merged