[WIP] BAU: Add extra logging to Stripe HTTP Client
alphagov/pay-connector pull request #911
Opened 2018-12-13 11:40 UTC by IreneLau-GDS

# WHAT
We were experiencing problems with test where HTTP calls out to Stripe don't seem to reach them. We need to up the logging to see what is happening.

2018-12-13 11:56 UTC, oswaldquek requested changes

2018-12-13 11:56 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +        logger.error("Other unexpected HTTP status code {} from gateway=[stripe]", response.getStatus());
might it be useful to log the response body as well?

2018-12-13 12:12 UTC, IreneLau-GDS commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +        logger.error("Other unexpected HTTP status code {} from gateway=[stripe]", response.getStatus());
Do they even reply with a body? I can only see in their doc that they send back specific error code. 

If not, there is no point to try to cast the `Response` object to `HttpResponse` just to get a body that has nothing.

2018-12-13 12:14 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +        logger.error("Other unexpected HTTP status code {} from gateway=[stripe]", response.getStatus());
I'm not sure they reply with a body but it can't hurt to log `response.getEntity(String.class)`. if there is a specific error code from them it'll be in the body too.

2018-12-13 12:17 UTC, IreneLau-GDS commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +        logger.error("Other unexpected HTTP status code {} from gateway=[stripe]", response.getStatus());
If you say so...

2018-12-13 12:40 UTC, kbottla requested changes

2018-12-13 12:40 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +            throwIfErrorResponse(response, metricsPrefix);
Don't think this move works. `throwIfErrorResponse` throws few checked exceptions based on response status (4xx,5xx) which will be caught here by `catch (Exception e)` which is not desired.
We want to throw exceptions so payment provider can deal with them.

2018-12-13 12:40 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +                response.getStatus(), response.readEntity(String.class));
This will be logged even for 2xx & 3xx errors. Is this what it is intended for ?

2018-12-13 13:19 UTC, IreneLau-GDS commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +            throwIfErrorResponse(response, metricsPrefix);
Okay then I'll add a null check because where it was before can throw an NPE.

2018-12-13 13:23 UTC, IreneLau-GDS commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +                response.getStatus(), response.readEntity(String.class));
If you look at the existing `GatewayClient`, I'm afraid that's exactly what it is doing.

https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/gateway/GatewayClient.java#L81-L87 

That raise a question though, why are we throwing exceptions for certain status code for stripe but not for the other gateway?

2018-12-13 13:38 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +            throwIfErrorResponse(response, metricsPrefix);
you can always `catch (GatewayClientException |  DownstreamException e) { throw e }` if you want to avoid catching the NPE

2018-12-13 14:49 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +                response.getStatus(), response.readEntity(String.class));
Yes, `GatewayClient` is logging non 200 responses.

Current log statement will log `everything` including 200 which is not unexpected

2018-12-13 14:57 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +                response.getStatus(), response.readEntity(String.class));
> That raise a question though, why are we throwing exceptions for certain status code for stripe but not for the other gateway?

Reason is error messages can be in the format specific to Payment provider (json in case of Stripe). To keep StripeGateway free from handling gateway specific error codes, exceptions are propagated and relevant PaymentProvider can process error messages

2018-12-13 16:43 UTC, IreneLau-GDS commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +            throwIfErrorResponse(response, metricsPrefix);
Then rethrow? That would be nasty. I'd rather do a null check.

2018-12-13 19:01 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +        if (response != null) {
i don't like this null check... why would it be null? it's successful at this point. this method MUST return a valid Response object if there was no error. if you're that concerned about the null i like moving `throwIfErrorResponse` into the `try` block and doing `catch (GatewayClientException| DownstreamException e) { throw e }` is the lesser evil.

2018-12-14 09:55 UTC, IreneLau-GDS commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +        logger.error("Other unexpected HTTP status code {} from gateway=[stripe]", response.getStatus());
@oswaldquek that didn't work BTW. So I've checked it to just print the whole response object. The default toString did print the output, not the reference to the object.

2018-12-14 10:00 UTC, IreneLau-GDS commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +        if (response != null) {
I think you are right. it will not happen. Let me remove it.

2018-12-14 10:30 UTC, oswaldquek submitted a review, later dismissed

2018-12-14 10:36 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +        logger.error("Other unexpected HTTP status gateway=[stripe], response=[]", response);
We will be logging this for all statuses (including 2xx). All won't be `unexpected`.

2018-12-14 13:58 UTC, IreneLau-GDS commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClient.java
> +        if (response != null) {
Removed.

2018-12-14 14:29 UTC, oswaldquek submitted a review, later dismissed

2018-12-14 15:07 UTC, kbottla approved these changes
LGTM!!!

2018-12-14 15:25 UTC, merged