PP 4439 - Refactor PaymentProvider.refund() response
alphagov/pay-connector pull request #915
Opened 2018-12-17 13:35 UTC by kbottla

## WHAT
- This change simplifies the response object (GatewayResponse<BaseRefundResponse> --> GatewayRefundResponse) returned from PaymentProvider refund operation (inline with capture refactoring PR #898).
- ChargeRefundService has also been refactored to update refund based on state returned by PaymentProvider and not based on specific payment provider

## HOW 
_Steps to test or reproduce:_

2018-12-17 18:33 UTC, oswaldquek requested changes
haven't gotten round to reviewing everything yet but just one comment so far

2018-12-17 18:33 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/model/response/GatewayRefundResponse.java
> +        return reference;
this should be `return Optional.ofNullable(reference)` as you're passing in a null reference in line 26. also if there's an error it's not guaranteed the `refundResponse.getReference()` is not null (line 31).

2018-12-18 10:00 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/model/response/GatewayRefundResponse.java
> +        return reference;
👍 Good spot. I have changed factory method to pass `Optional.empty()` instead of null. As reference is already Optional, can't use `return Optional.ofNulllable` straight away

2018-12-18 10:49 UTC, oswaldquek requested changes

2018-12-18 10:49 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandler.java
> +                    StripeRefundResponse.of(request.getTransactionId(), error.getCode(), error.getMessage()),
I don't think passing in the `request.getTransactionId()` as the reference is correct here. The reference is an id returned by Stripe as a result of a successful refund request. The `request.getTransactionId()` is actually the charge entity's gateway transaction id: https://github.com/alphagov/pay-connector/blob/32a0acca2b169c9c4ca34d2e8d54bcf45f293ba4/src/main/java/uk/gov/pay/connector/gateway/model/request/RefundGatewayRequest.java#L59 and is not the reference.

since `GatewayClientException` is a 4xx error and Stripe seems to return something like
```
{
  "error": {
    "message": "The transfer tr_blah_blah_blah is already fully reversed.",
    "type": "invalid_request_error"
  }
}
```
 i think the reference should be null in this case.

2018-12-18 10:49 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/response/StripeRefundResponse.java
> +    public static StripeRefundResponse of(String reference, String errorCode, String errorMessage) {
since reference might be null in the event of an error it's likely you'll need a constructor that only takes an errorCode and errorMessage

2018-12-18 10:49 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
lines 121-127. one of the purposes of https://github.com/alphagov/pay-connector/pull/898 really is to make the `CardCaptureService` payment provider agnostic. i think you can do the same here instead of relying on the payment provider name? we should do this because Stripe and Sandbox payment providers both return a COMPLETE status, and therefore a REFUNDED status here.

2018-12-18 10:49 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
see https://github.com/alphagov/pay-connector/blob/beea6fa714eaf76f1531a536cabf2469d6484a18/src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java#L344-L355 as an example of making it payment provider agnostic.

2018-12-18 10:49 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/model/response/GatewayRefundResponse.java
> +        return reference;
👍

2018-12-18 11:11 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/handler/StripeRefundHandler.java
> +                    StripeRefundResponse.of(request.getTransactionId(), error.getCode(), error.getMessage()),
👍 Removed reference

2018-12-18 11:11 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/response/StripeRefundResponse.java
> +    public static StripeRefundResponse of(String reference, String errorCode, String errorMessage) {
Added new factory method for only errorCode and errorMessage

2018-12-18 11:11 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
As far the refund status is concerned, we are not depending anymore on payment provider and relying on refund state returned.
Only reason we still see payment provider and can't extract entire update logic is because of email notifications sent only for sandbox.

2018-12-18 11:30 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
I don't think sending a notification is a sandbox specific thing. It seems logical to me that if a refund's status is REFUNDED, the user should expect an email notification, regardless of whether the PSP was Stripe or Sandbox. but check with @mrlumbu or @alexbishop1

2018-12-18 11:31 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
Also I think lines 121-123 
```
if (refundStatus == REFUNDED) {
             getRefundReference(refundEntity, gatewayResponse).ifPresent(refundEntity::setReference);	                 refundEntity.setStatus(REFUND_SUBMITTED);
             }
```
is very confusing.

Generally this section of code needs a bit more clarity.

2018-12-18 11:32 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/gateway/stripe/response/StripeRefundResponse.java
> +    public static StripeRefundResponse of(String reference, String errorCode, String errorMessage) {
👍 
`public static StripeRefundResponse of(String reference, String errorCode, String errorMessage)` isn't being used anymore though so can be removed.

2018-12-18 11:40 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
This is not a new functionality introduced.

https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java#L128-L132

2018-12-18 11:42 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
Not sure how lines 121-123 became
`if (refundStatus == REFUNDED) {
             getRefundReference(refundEntity, gatewayResponse).ifPresent(refundEntity::setReference);	                 refundEntity.setStatus(REFUND_SUBMITTED);
             }`

This is the code that I can see
`if (refundStatus == REFUNDED) {
                refundEntity.setStatus(REFUND_SUBMITTED);
            }`

2018-12-18 11:45 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
Sorry, not sure how I copied that wrong. but `if (refundStatus == REFUNDED) { refundEntity.setStatus(REFUND_SUBMITTED); }` is very confusing. why is this being done?

2018-12-18 11:47 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/response/StripeRefundResponse.java
> +    public static StripeRefundResponse of(String reference, String errorCode, String errorMessage) {
Oops! Removed unused factory method

2018-12-18 11:47 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
"This is not a new functionality introduced."

Yes, of course. But we've introduced a new payment provider Stripe. It makes sense to send email notifications for any provider which returns a COMPLETE status.

2018-12-18 11:54 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
Depends on what our functionality is. 
- Do we send refund email notifications to users (at any point) ? cc @alexbishop1 @mrlumbu.

As far as I can see it is only for Sandbox that we send notifications.

2018-12-18 12:09 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
> if (refundStatus == REFUNDED) { refundEntity.setStatus(REFUND_SUBMITTED); } is very confusing. why is this being done? there doesn't seem to be any rationale behind this code.

This will enable to store history of events for refunds and also displayed (for services) in frontend as:
```
Refunded                           amount   date 
Refund Submitted by [user email]   amount   date 
```

2018-12-18 12:13 UTC, mrlumbu commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
@kbottla no, we definitely send them for all gateways, it's just that I believe we send them once we have received a successful refund notification for ePDQ, Worldpay, Smartpay, which is why we have that hacky bit of code for sandbox. I can dig out the code in a bit, or I'm sure you can find it

2018-12-18 12:39 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
We don't at the moment. It is been missed out on refactoring notifications. Just raised another PR for the fix

2018-12-18 13:12 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
@kbottla the other PR is for worldpay. i believe we should send refund notification for Stripe which means we can get rid of references to the Sandbox payment provider here.

2018-12-18 13:14 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
basically, `if (refundStatus == REFUNDED)`, send refund notification.

2018-12-18 13:16 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +                refundEntity.setStatus(REFUND_SUBMITTED);
i understand this is for storing history of events for refunds, but where is this history stored? 

if you look at 

https://github.com/alphagov/pay-connector/blob/beea6fa714eaf76f1531a536cabf2469d6484a18/src/main/java/uk/gov/pay/connector/charge/service/ChargeService.java#L344-L355

it makes all this very clear.

2018-12-18 14:17 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +            }
The other PR is for RefundNotificationsProcessor (which is a fix). I have already made suggested changes (`if (refundStatus == REFUNDED)`) for Stripe.

2018-12-18 14:20 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +                refundEntity.setStatus(REFUND_SUBMITTED);
RefundHistory is being handled by Customiser and eclipselink here
https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/refund/model/domain/RefundEntity.java#L52

We can look at refactoring history writing separately if any improvements are needed.

2018-12-18 14:43 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +                refundEntity.setStatus(REFUND_SUBMITTED);
cool, that HistoryCustomizer looks interesting. i don't think any refactoring is needed. i'm more concerned about readability and understanding code - reading it as if i were a new developer on the project. i think there should be some comment then, about why you're setting the RefundEntity's status to REFUND_SUBMITTED. 
i think it'll also be good to modify SandboxRefundITest to assert the RefundHistory of a refund processed by Sandbox payment provider has a REFUND_SUBMITTED and REFUNDED status.

basically i think everything could be collapsed to:
```
if (refundStatus == REFUNDED) {
                refundEntity.setStatus(REFUND_SUBMITTED);
                userNotificationService.sendRefundIssuedEmail(refundEntity);
                refundEntity.setStatus(REFUNDED);
            } else refundEntity.setStatus(refundStatus);
```

2018-12-18 14:44 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +                refundEntity.setStatus(REFUND_SUBMITTED);
sorry to be a pain

2018-12-19 10:26 UTC, oswaldquek requested changes
sorry just one change requested to make the comment clearer for developers.

2018-12-19 10:26 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +                // refund. This will also help services to view refund history in detail in self service
Can this be changed to ```If the gateway confirms refunds immediately, the refund status needs to be set to REFUND_SUBMITTED and then REFUNDED. This will help services to view refund history in detail in self service. By setting the refund status like `refundEntity.setStatus(REFUND_SUBMITTED)` for example, the refund status history is magically captured by the @Customizer(HistoryCustomizer.class) annotation on RefundEntity.```

Again I'm approaching this with the eyes of a new developer and I think it's important to tell HOW this history is persisted in the database, rather than saying "insert history to record".

2018-12-19 10:39 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/service/ChargeRefundService.java
> +                // refund. This will also help services to view refund history in detail in self service
I see your point. But I am not comfortable mixing up why (business desc) and how (tech choices) and also anytime (which is in multiple places) we use `refund.setStatus` \@Customiser comes into action. I feel this may not be right place to describe tech implementation

2018-12-19 14:28 UTC, oswaldquek requested changes
i'm happy with the implementation. just two things: 1) testing the event history once is enough... we don't need to assert the event history for every test as it will further pollute existing tests and affect readability. in fact i'd prefer if you just created an assertEventHistoryForASuccessfulRefund test 2) it's better to use the refundDao to get event history as you can verify the order in which events happen as they have a timestamp which you can use to sort.

2018-12-19 14:28 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/model/domain/RefundHistory.java
> + */
we don't need this comment anymore. i originally thought it was the `@Customizer(HistoryCustomizer.class)` that updates the refunds_history table but it's actually the `@Transactional` annotation on a method that causes the refund entity and the history table to be updated.

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInDBForSuccessfulOrPartialRefund(defaultTestCharge);
this can be deleted as it is already asserted in the `shouldBeAbleToRequestARefund_partialAmount` test which is sufficient. no need to go overboard here.

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInDBForSuccessfulOrPartialRefund(defaultTestCharge);
this can be deleted as it is already asserted in the `shouldBeAbleToRequestARefund_partialAmount` test which is sufficient. no need to go overboard here.

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInDBForTwoRefunds(defaultTestCharge);
can delete this as already asserted in `shouldBeAbleToRefundTwoRequestsWhereAmountAvailableMatch`.

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertThat(refundsFoundByChargeId.size(), is(1));
don't think we need this assertion.

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInDBForSuccessfulOrPartialRefund(defaultTestCharge);
don't think we need this assertion.

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertThat(refundsHistory.size(), is(0));
this can be simplified by using `assertThat(refundDao.searchHistoryByChargeId(defaultTestCharge.getChargeId()), hasSize(0))`

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertThat(refundsHistory.size(), is(0));
don't need this assertion as already tested

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertThat(refundsHistory.size(), is(0));
don't need this assertion as already tested

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInDBForSuccessfulOrPartialRefund(defaultTestCharge);
don't need this assertion as already tested

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        List<String> refundsHistory = databaseTestHelper.getRefundsHistoryByChargeId(defaultTestCharge.getChargeId()).stream().map(x -> x.get("status").toString()).collect(Collectors.toList());
i'd rather `refundDao.searchHistoryByChargeId` was used as you get the `List<RefundHistory>` returned. it will be quite easy to order the list based on historyStartDate. because i'm not sure asserting events "containsInAnyOrder" is actually correct here.

2018-12-19 14:28 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertThat(refundsHistory, containsInAnyOrder("REFUND SUBMITTED", "REFUNDED", "CREATED", "REFUND SUBMITTED", "REFUNDED", "CREATED"));
same comment as above

2018-12-19 14:32 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/refund/model/domain/RefundHistory.java
> + */
It is still @Customizer(HistoryCustomizer.class) that is responsible to insert into history.

Transactional is more about enabling boundaries for the operations and if we do multiple operations in a single transaction they won't be treated individually.

2018-12-19 14:34 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInDBForSuccessfulOrPartialRefund(defaultTestCharge);
We do it refunds record. It is better to have refunds history together. 
Having only one test won't cover full/partial refunds and also if that tests gets removed we are back to square 1. I feel we should add them wherever we check for refunds.

2018-12-19 14:45 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/refund/model/domain/RefundHistory.java
> + */
ok, i understand 👍

2018-12-19 14:47 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInDBForSuccessfulOrPartialRefund(defaultTestCharge);
?? it's already tested in `shouldBeAbleToRequestARefund_partialAmount`. all i'm saying is you don't have to go overboard and re-test it here (and for nearly every method in this test class).

2018-12-19 14:54 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInDBForSuccessfulOrPartialRefund(defaultTestCharge);
May be it is confusing to have common method ?
My intention is, if each test is considered on its own it should cover `issue refund, check response, check refunds & refunds history in DB for that particular transaction`

2018-12-19 14:59 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        List<String> refundsHistory = databaseTestHelper.getRefundsHistoryByChargeId(defaultTestCharge.getChargeId()).stream().map(x -> x.get("status").toString()).collect(Collectors.toList());
Not against using history_start_date. Updated query to order by statuses and removed  containsInAnyOrder.

2018-12-19 15:25 UTC, kbottla commented
> 1) testing the event history once is enough... we don't need to assert the event history for every test as it will further pollute existing tests and affect readability. in fact i'd prefer if you just created an assertEventHistoryForASuccessfulRefund test 

I don't think it as a right place to test refundHistory alone as these are resource tests. As each test is for different scenario we verify `response, refund record from DB` in each test. I have extended tests to check for refunds history. Anyone looking at an individual test can understand different aspects to be looked out for these tests.

> 2) it's better to use the refundDao to get event history as you can verify the order in which events happen as they have a timestamp which you can use to sort.

Updated helper to sort by date and checking the statuses in order. Felt it a bit like polluting test class if mixing helper and dao for different reasons.

2018-12-19 17:18 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInOrderInDBForSuccessfulOrPartialRefund(defaultTestCharge);
we definitely don't need this assertion here as this is already done in the `shouldBeAbleToRequestARefund_fullAmount` test. this test (`shouldFailRequestingARefund_whenChargeRefundIsFull`) makes a full refund as well before making another refund. so the event history is already tested.

2018-12-19 17:19 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInOrderInDBForSuccessfulOrPartialRefund(defaultTestCharge);
we should keep code as clean as possible and not add unnecessary tests

2018-12-19 17:22 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/resources/sandbox/SandboxRefundITest.java
> +        assertRefundsHistoryInOrderInDBForSuccessfulOrPartialRefund(defaultTestCharge);
👍 Removed.

2018-12-19 17:23 UTC, oswaldquek approved these changes

2018-12-19 17:25 UTC, oswaldquek commented
I actually think we should test refund history as it's own test as the end user can see this history. This is got by calling the `"/v1/api/accounts/{accountId}/charges/{chargeId}/events"` endpoint. So it makes perfect sense to have a resource level test where a refund is made and we assert the event history. This PR has gone on for long enough though so will approve. I will create the test separately.

2018-12-19 17:29 UTC, kbottla commented
There is probably a test already although I haven't looked into its details
https://github.com/alphagov/pay-connector/blob/master/src/test/java/uk/gov/pay/connector/it/resources/ChargeEventsResourceITest.java#L92

2018-12-19 17:34 UTC, merged