PP-4550 Fix Stripe Client bug
alphagov/pay-connector pull request #926
Opened 2018-12-27 14:49 UTC by georgeracu

## WHAT

- Fixed the case when `StripeGatewayClient` was hanging on requests after a while.
This behaviour has been linked to the Jersey Client where we didn't close
the `Response`.
- Given that we were propagating the `Response` object from the client a few
levels up to be handled by the caller of the client, the lifespan of this
object was long and it was keeping busy HTTP connections. The client now
returns a custom Response object, not a `javax.ws.rs.core.Response` one.
This new object type holds the response body, the status and family of the
status from the initial Response. The client will send back this new custom
object and any classes interested in using it will use the String payload
to map into the object type they need (if the payload is returned).
- Updated the tests to match the new response type
- Replaced a `WireMockRule` with a class rule, to keep the server running
between test classes. This change fixed a random test failure, that was
failing because the WireMock server failed to respond to the HTTP request
- Updated tests such that mocks will match against known URIs and not `any()`
- Deleted base test class as it was used only in one child class

2018-12-28 11:51 UTC, kbottla requested changes
Looks good overall. Some minor comments and a comment about ObjectMapper instantiation.

2018-12-28 11:51 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/Stripe3dsSourceAuthorisationResponse.java
> +            Stripe3dsSourceResponse stripe3dsSourceResponse = new ObjectMapper().readValue(jsonResponse, Stripe3dsSourceResponse.class);
It may be big change now. But `new ObjectMapper()` is expensive operation as per https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance.

2018-12-28 11:51 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClientResponse.java
> +    private javax.ws.rs.core.Response.Status.Family statusFamily;
Is there any reason full package name is used ? I think it would read nice without full package name.

2018-12-28 11:51 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClientResponse.java
> +    StripeGatewayClientResponse(javax.ws.rs.core.Response response) {
Same as above for full package name

2018-12-28 11:51 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClientResponse.java
> +    javax.ws.rs.core.Response.Status.Family getFamily() {
Same as above

2018-12-28 11:51 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripePaymentProvider.java
> +    public static <T> T getObjectFromJson(String jsonResponse, Class<T> targetType) {
If we want to avoid `new ObjectMapper`, This could be in another object (injected into PaymentProvider and Handlers) with ObjectMapper injected.

Common catch block can also be in one place.

> catch (IOException e) {
             logger.info("There was an exception parsing the payload [{}] into an [{}]", jsonResponse, targetType);
             throw new WebApplicationException(format("There was an exception parsing the payload [%s] into an [%s]", jsonResponse, targetType));
         }

2018-12-28 12:24 UTC, georgeracu commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClientResponse.java
> +    private javax.ws.rs.core.Response.Status.Family statusFamily;
A leftover from when the `StripeGatewayClientResponse` was called `Response` and this line required to fully qualify the name. Will fix it :)

2018-12-28 12:24 UTC, georgeracu commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClientResponse.java
> +    StripeGatewayClientResponse(javax.ws.rs.core.Response response) {
👍

2018-12-28 12:24 UTC, georgeracu commented on src/main/java/uk/gov/pay/connector/gateway/stripe/StripeGatewayClientResponse.java
> +    javax.ws.rs.core.Response.Status.Family getFamily() {
👍

2018-12-31 10:25 UTC, kbottla submitted a review, later dismissed
Thanks for the changes. Looks like `getObjectFromJson` method doesn't belong to StripeGatewayClient, but we can look at it separately.

My initial thought is to have a class like `JsonObjectMapper` with ObjectMapper injected
```
    public JsonObjectMapper(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

   ..... getObjectFromJson method ...
```

and inject the above into gateway handlers


```
    public StripePaymentProvider(StripeGatewayClient stripeGatewayClient,
                                 ConnectorConfiguration configuration,
                                 JsonObjectMapper jsonObjectMapper
    )
```

2018-12-31 12:06 UTC, kbottla approved these changes
Looks good 👍 🏅

2018-12-31 12:08 UTC, merged