BAU: IntelliJ-inspired code cleanups
alphagov/pay-connector pull request #932
Opened 2019-01-02 07:54 UTC by rhowe-gds

## WHAT
Address some rather dull issues identified by IntelliJ

* Unnecessary variables
* Static things accessed via instances
* Times when primitive types are more appropriate
* Suppress some warnings about our unchecked use of Optionals in tests

## HOW 
See if the changes look sensible
See if CI passes

2019-01-02 09:57 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/common/model/domain/PaymentGatewayStateTransitionsTest.java
> +        assertThat(PaymentGatewayStateTransitions.isValidTransition(CREATED, AUTHORISATION_READY), is(false));
these could be simplified further by importing `import static uk.gov.pay.connector.common.model.domain.PaymentGatewayStateTransitions.isValidTransition;`

2019-01-02 09:59 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/CardResourceAuthoriseITest.java
> +    @SuppressWarnings("UnnecessaryLocalVariable")
am not sure about these

2019-01-02 10:01 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesFrontendResourceITest.java
> +        String serviceName = "a cool service";
why these two lines?

2019-01-02 10:04 UTC, rhowe-gds commented on src/test/java/uk/gov/pay/connector/it/resources/ChargesFrontendResourceITest.java
> +        String serviceName = "a cool service";
Because I blindly did what IntelliJ told me without thinking - they can just go into the assertions below. I'll fix up.

2019-01-02 10:17 UTC, alexbishop1 requested changes
Looks good overall but I have a few qualms

2019-01-02 10:17 UTC, alexbishop1 commented on src/main/java/uk/gov/pay/connector/refund/service/SearchRefundsService.java
> +        RefundSearchStrategy refundSearchStrategy = new RefundSearchStrategy(refundDao);
I think a better change here might be to keep the `RefundSearchStrategy` as a field and initialise it in the `@Inject` method, eliminating the need to store the `RefundDao` as a field:

```java
@Inject
public SearchRefundsService(RefundDao refundDao) {
    this.refundSearchStrategy = new RefundSearchStrategy(refundDao);
}
```

(It’s definitely a good to not assign the `refundSearchStrategy` with each method invocation, especially given that multiple threads could be trying to do this at the same time.)

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/app/ConnectorConfigurationTest.java
> +@SuppressWarnings("OptionalGetWithoutIsPresent")
Can you put this on the specific test please?

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/service/ChargeServiceTest.java
> +@SuppressWarnings("OptionalGetWithoutIsPresent")
Can you put this on the specific tests that need it please (since there’s only a couple)?

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/charge/util/CorporateCardSurchargeCalculatorTest.java
> +@SuppressWarnings("OptionalGetWithoutIsPresent")
Please put this on the specific test

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/base/ChargingITestBase.java
> +@SuppressWarnings("OptionalGetWithoutIsPresent")
Can you move this to the `datesFrom(List<String>)` method please?

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/ChargeDaoCardDetailsITest.java
> +@SuppressWarnings("OptionalGetWithoutIsPresent")
Again, on the specific test please

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/dao/ChargeDaoITest.java
> +@SuppressWarnings("OptionalGetWithoutIsPresent")
You know what I’m going to say

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/it/resources/CardResourceAuthoriseITest.java
> +    @SuppressWarnings("UnnecessaryLocalVariable")
Ideally this should be on each individual local variable assignment or, failing that, each test that requires it

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/junit/PostgresTestDocker.java
> +            connection.createStatement().execute("CREATE DATABASE " + PostgresTestDocker.DB_NAME + " WITH owner=" + dbUser + " TEMPLATE postgres");
We can just use `DB_NAME` here

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/ChargeEntityFixture.java
> +        String email = "test@email.com";
While you’re at it, can you change this to a definitely not valid email address like `test@email.test` please?

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/ChargeEntityFixture.java
> +        WalletType walletType1 = walletType;
It looks like this method is actually useless as it currently stands

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/model/domain/RefundEntityFixture.java
> +        RefundEntityFixture.userExternalId = userExternalId;
I think the correct change here is to make `userExternalId` not `static`

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +                object.getChargeEntity().equals(chargeEntity);
Please rename `object` to ` refundEntity`

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/service/ChargeRefundServiceTest.java
> +                object.getAmount().equals(String.valueOf(amountInPence));
Please rename `object` to ` refundGatewayRequest`

2019-01-02 10:17 UTC, alexbishop1 commented on src/test/java/uk/gov/pay/connector/usernotification/service/UserNotificationServiceTest.java
> +@SuppressWarnings("OptionalGetWithoutIsPresent")
On the specific tests please

2019-01-03 08:34 UTC, rhowe-gds commented on src/test/java/uk/gov/pay/connector/model/domain/RefundEntityFixture.java
> +        RefundEntityFixture.userExternalId = userExternalId;
Ugh, it's referenced all over the place

2019-01-03 09:35 UTC, oswaldquek commented
i'm generally not sold on most of the SuppressWarning annotations. They aren't production code. They're make-intellij-happy code.

2019-06-17 10:21 UTC, rhowe-gds commented
This is so stale it's easier to redo from scratch

2019-06-17 10:21 UTC, closed without merging