PP-4270 Multithreaded capture process
alphagov/pay-connector pull request #947
Opened 2019-01-07 16:55 UTC by kbottla

## WHAT
### `Background`

The capture process (captures charges asynchronously in the background) in connector is a single threaded job that takes a number of charges (based on batch size) and captures them one by one. Potential issues with this approach:

1. Multiple connector nodes could potentially end up with overlap of charges being captured.
2. The average response time (live) to capture charges is ~130ms. A batch size of 50 will take ~5 seconds to complete capture. So a single connector capture job scheduled every 10 seconds can only capture ~17k charges/day. Given a high volume of transactions (~1 million/day), capture processes can take weeks to capture charges from a single day and may end up with expiring authorisations.
3. Increasing number of connector nodes doesn't necessarily multiply the number of charges that can be captured as charges can overlap with other connector jobs

### `Solution`

Proposed solution is to introduce a queue (within connector node) and run multi-threaded capture process so that charges can be captured in parallel and quickly. For a batch size of 50 charges and with 10 capture threads we can clear the batch with in ~500ms. It can also likely to mitigate the issue of overlapping charges between connector nodes.

### `Changes`

- CaptureProcessScheduler now schedules multiple threads to capture charges
- Scheduler first loads shared queue (with charges awaiting capture)
- Each thread reads (removes charge from head of the queue - if queue is not empty) a charge from queue to process it further.
        - `ArrayBlockingQueue` is used as a queue which seemed most suitable to use as it is a fixed size queue that can hold charges equivalent to batch size, thread safe and size() method is constant-time operation. Although it is blocking queue, operations used (poll(), isEmpty()) are non blocking. So a thread can exit from operation without being blocked.

**Alternative considered:** 
Considered introducing blocking threads which wait (indefinitely) for charges to be available in queue. But due to the blocking nature all capture related unit tests will become invalid. We need complex test setup to terminate threads / add a mechanism to timeout tests to be able to use queue blocking methods (queue.take()).

2019-01-08 12:34 UTC, oswaldquek reviewed
I have two minor comments. 

I think this solution will work. However, it is a little complicated. In my head it would be easier if the only thing that is scheduled is the loading of the capture queue. Then in the background we have a number of workers (the `captureProcessConfig.getSchedulerThreads()`) that are constantly polling this capture queue and capturing charges when the queue is not empty, rather than scheduling when they capture charges. Maybe some input from other team members would be useful to get some consensus.

2019-01-08 12:34 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CaptureProcessScheduler.java
> +                .threads(schedulerThreads + 1)
why is 1 added to schedulerThreads here?

2019-01-08 12:34 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CaptureProcessScheduler.java
> +                cardCaptureProcess.loadCaptureQueue();
we only need to load the capture queue once. could this line go before the for loop?

2019-01-08 13:02 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CaptureProcessScheduler.java
> +                cardCaptureProcess.loadCaptureQueue();
👍 good spot. Moved it out of loop.

2019-01-08 13:02 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CaptureProcessScheduler.java
> +                .threads(schedulerThreads + 1)
It is for the main thread (loading + capture) and capture only threads (schedulerThreads)

2019-01-08 13:14 UTC, oswaldquek requested changes
ok. given we are likely going to use a real queue at some point, it won't make much difference between my solution and the current implementation, so i'm happy with that.

only thing is i'd like to see an integration test with at least 2 `schedulerThreads` where we it can be verified a charge's status is updated via the capturing process.

2019-01-08 13:14 UTC, oswaldquek commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CaptureProcessScheduler.java
> +                .threads(schedulerThreads + 1)
hmm then why was the adding of the 1 not there before? will things not work if the 1 is not added? again I approach reading code as a new developer. i'm loathe to this kind of thing unless there's a clear comment.

2019-01-08 13:27 UTC, kbottla commented on src/main/java/uk/gov/pay/connector/paymentprocessor/service/CaptureProcessScheduler.java
> +                .threads(schedulerThreads + 1)
We only have one thread before which calls runCapture (which does both loading + capturing charges). 
Things will work without 1 but it will be one less thread available from thread pool for capture threads.

2019-01-09 11:07 UTC, oswaldquek requested changes

2019-01-09 11:07 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +@RunWith(MockitoJUnitRunner.class)
don't actually need this as there are no `@Mock` annotations on fields

2019-01-09 11:07 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    public GuiceAppWithPostgresRule app = new GuiceAppWithPostgresRule(
i would recommend using `@RunWith(DropwizardJUnitRunner.class)` to run this test. one of the benefits is you don't need to find a port for the wireMockRule as you get that for free. you can simply do this:
https://github.com/alphagov/pay-connector/blob/56c8ab1670b342db58d0c697ec1000f51ed9cd20/src/test/java/uk/gov/pay/connector/it/base/ChargingITestBase.java#L85

2019-01-09 11:07 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +            config("captureProcessConfig.schedulerRandomIntervalMaximumInSeconds", "1")
if you use `@RunWith(DropwizardJUnitRunner.class)` you can override the configs like in the SendRefundEmailTest:
https://github.com/alphagov/pay-connector/blob/56c8ab1670b342db58d0c697ec1000f51ed9cd20/src/test/java/uk/gov/pay/connector/it/SendRefundEmailTest.java#L46

you could then also ignore the `config("worldpay.urls.test", "http://localhost:" + port + "/jsp/merchant/xml/paymentService.jsp")` part as you get that for free.

2019-01-09 11:07 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    private DatabaseFixtures.TestCharge createTestCharge(String paymentProvider, ChargeStatus chargeStatus) {
it seems this method was copied from `CardCaptureProcessBaseITest`. could we avoid code duplication and put this as a static method in `ChargeUtils.java` please. it won't hurt to do some easy refactoring here.

2019-01-09 11:07 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +        captureProcessScheduler.start();
since this is an integration test, we shouldn't have to do call `captureProcessScheduler.start()` here as it should be automatically started when the dropwizard app starts up.

2019-01-09 11:07 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +        verify(mockAppender, times(4)).doAppend(loggingEventArgumentCaptor.capture());
personally i'm happy with the assertion that the charge's status is CAPTURE_SUBMITTED. but if you really want to test the mockAppender, is it possible to verify it got called with the actual logs, e.g. "Capturing: 1 of 1 charges", "Capturing [1 of 1] [chargeId=...]" etc?

2019-01-09 12:08 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +@RunWith(MockitoJUnitRunner.class)
👍

2019-01-09 12:08 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +        verify(mockAppender, times(4)).doAppend(loggingEventArgumentCaptor.capture());
My aim is to check if multiple threads are working on capture process (one way which I have done is to check the logging activity by threads) . I don't think we need to check exact logging as the test is if multiple threads are being created by scheduler and capture process is invoked.

2019-01-09 12:08 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    public GuiceAppWithPostgresRule app = new GuiceAppWithPostgresRule(
I would prefer lightweight version for testing internal services (which is the initial aim of GuiceAppWithPostgresRule) as opposed to spinning entire app to test this. We will have control over the methods to invoke and check at the same time.

2019-01-09 12:08 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    private DatabaseFixtures.TestCharge createTestCharge(String paymentProvider, ChargeStatus chargeStatus) {
👍 Extracted creatingCharge to ChargeUtils. But not done for `CardCaptureProcessBaseITest`.  It would be good to do refactoring in a separate PR.

2019-01-09 12:08 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +        captureProcessScheduler.start();
We need to call `start()` when using GuiceAppWithPostgresRule

2019-01-09 12:23 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +        verify(mockAppender, times(4)).doAppend(loggingEventArgumentCaptor.capture());
okay I have updated test slightly to check partial strings for threads completing capture.

2019-01-09 12:25 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    public GuiceAppWithPostgresRule app = new GuiceAppWithPostgresRule(
It doesn't matter with the `@RunWith(DropwizardJUnitRunner.class)` because the database would only be spun up once for the entire run of the build so you're not really saving anything here. The benefits of using DropwizardJUnitRunner - less code because you don't need to `findFreePort` or configure the `worldpay.urls.test` - are clear.

2019-01-09 12:25 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +        verify(mockAppender, times(4)).doAppend(loggingEventArgumentCaptor.capture());
ok. 👍

2019-01-09 14:45 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    public GuiceAppWithPostgresRule app = new GuiceAppWithPostgresRule(
It won't make difference when all tests are run, but difference can be seen when running the test isolated.
`@RunWith(DropwizardJUnitRunner.class)` - spins up jetty server which increases the time to execute test and feedback cycle for developers

Also DropwizardJUnitRunner doesn't seem to be starting capture thread(s) (even on master branch which is single threaded). Not sure at the moment if this is the behaviour expected  and the reason `GuiceAppWithPostgresRule` was introduced

2019-01-09 15:00 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    public GuiceAppWithPostgresRule app = new GuiceAppWithPostgresRule(
Hmm well if the capture threads aren't started automatically already suggests there's a problem. The point of an integration test is that one avoids calling things manually, e.g. `captureProcessScheduler.start()` as this should be done automatically when the app is spun up. There's a reason why using `GuiceAppWithPostgresRule` is bad in this case - it's not testing things properly.

2019-01-09 15:01 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    private DatabaseFixtures.TestCharge createTestCharge(String paymentProvider, ChargeStatus chargeStatus) {
It wouldn't hurt to do this refactoring in this PR really. It's not that much code.

2019-01-09 15:38 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    public GuiceAppWithPostgresRule app = new GuiceAppWithPostgresRule(
It may be a problem with DropwizardJUnitRunner as it doesn't even work with master branch. 
`captureProcessScheduler.start()` is working fine but I think it has problem with getting threads from ThreadPool.

2019-01-09 18:15 UTC, kbottla commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +    public GuiceAppWithPostgresRule app = new GuiceAppWithPostgresRule(
okay so the problem was not with acquiring threads, but threads being killed due to exception (DB migrations were incomplete and capture threads being scheduled during jetty startup). Still not convinced to use DropwizardJUnitRunner as we has to wait for server to start (when test is run in isolation). 

Both (DropwizardJUnitRunner, GuiceAppWithPostgresRule) need to wait for DB migrations to complete, so the solution is similar except that for DropwizardJUnitRunner need to wait a bit longer for capture process to kick in and could cause flakiness if server startup and migrations take longer than the wait

2019-01-10 10:42 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +                @ConfigOverride(key = "captureProcessConfig.schedulerInitialDelayInSeconds", value = "10"), // delay so DB migrations can be complete before capture process
i guess waiting for the DB to start up is unavoidable :(

2019-01-10 10:42 UTC, oswaldquek commented on src/test/java/uk/gov/pay/connector/it/scheduler/CaptureProcessSchedulerITest.java
> +                @ConfigOverride(key = "captureProcessConfig.schedulerRandomIntervalMinimumInSeconds", value = "5"),
is there any reason why you chose 5? if i changed `schedulerRandomIntervalMinimumInSeconds` and `schedulerRandomIntervalMaximumInSeconds` to 1 the test fails :(

2019-01-10 11:14 UTC, oswaldquek approved these changes

2019-01-10 11:55 UTC, merged